import type { LessonDetail, PathDetail } from '@/types/database.types';

// ---------------------------------------------------------------------------
// PATH DETAILS (enriched metadata per path)
// ---------------------------------------------------------------------------
export const PATH_DETAILS: Record<string, Omit<PathDetail, 'id' | 'order_index' | 'is_active'>> = {
  french: {
    slug: 'french',
    title: 'Cuisine Française',
    description: 'Maîtrise les classiques de la gastronomie française',
    emoji: '🇫🇷',
    color: '#0055A4',
    country: 'France',
    history: "La cuisine française est reconnue patrimoine culturel immatériel de l'UNESCO depuis 2010. Elle a été codifiée au XIXe siècle par Auguste Escoffier, qui a révolutionné la restauration moderne. La brigade de cuisine, le menu dégustation, les sauces mères — tout vient de cette tradition.",
    key_ingredients: ["Beurre AOP", "Crème fraîche", "Herbes de Provence", "Vin blanc sec", "Moutarde de Dijon", "Échalotes"],
    famous_chefs: ["Auguste Escoffier", "Paul Bocuse", "Joël Robuchon", "Alain Ducasse"],
  },
  italian: {
    slug: 'italian',
    title: 'Cuisine Italienne',
    description: 'Pasta, pizza e molto altro!',
    emoji: '🇮🇹',
    color: '#CE2B37',
    country: 'Italie',
    history: "La cuisine italienne est l'une des plus influentes au monde. Née de 20 régions aux identités culinaires distinctes, elle repose sur la qualité des ingrédients plutôt que sur la complexité des techniques. La pasta existe depuis le XIIIe siècle, bien avant que Marco Polo ne revienne de Chine.",
    key_ingredients: ["Tomates San Marzano", "Huile d'olive extra vierge", "Parmigiano Reggiano", "Basilic frais", "Farine 00", "Mozzarella di bufala"],
    famous_chefs: ["Massimo Bottura", "Carlo Cracco", "Gennaro Contaldo", "Antonio Carluccio"],
  },
  japanese: {
    slug: 'japanese',
    title: 'Cuisine Japonaise',
    description: "Sushi, ramen, et l'art du dashi",
    emoji: '🇯🇵',
    color: '#BC002D',
    country: 'Japon',
    history: "La cuisine japonaise (washoku) est patrimoine de l'UNESCO depuis 2013. Elle repose sur 5 principes fondamentaux : 5 couleurs, 5 saveurs (dont l'umami, découvert en 1908 par le chimiste Kikunae Ikeda), 5 méthodes de cuisson. Le couteau japonais (hocho) est forgé comme une lame de samouraï.",
    key_ingredients: ["Dashi (kombu + bonite)", "Mirin", "Sauce soja", "Miso blanc", "Riz japonais à grain court", "Wasabi frais"],
    famous_chefs: ["Jiro Ono", "Nobu Matsuhisa", "Yoshihiro Murata", "Tetsuya Wakuda"],
  },
  moroccan: {
    slug: 'moroccan',
    title: 'Cuisine Marocaine',
    description: 'Tajine, couscous et ras-el-hanout',
    emoji: '🇲🇦',
    color: '#C1272D',
    country: 'Maroc',
    history: "La cuisine marocaine est le fruit de 3000 ans de civilisations : berbère, arabe, andalouse et juive. Le couscous — déclaré patrimoine de l'UNESCO en 2020 — se roule à la main depuis des millénaires. Le ras-el-hanout (\"tête de l'épicier\") peut contenir jusqu'à 50 épices différentes.",
    key_ingredients: ["Ras-el-hanout", "Safran de Taliouine", "Argan", "Charmoula", "Citrons confits", "Fleur d'oranger"],
    famous_chefs: ["Moha Fedal", "Fatéma Hal", "Najat Kaanache"],
  },
  mexican: {
    slug: 'mexican',
    title: 'Cuisine Mexicaine',
    description: 'Tacos, guacamole et mole',
    emoji: '🇲🇽',
    color: '#006847',
    country: 'Mexique',
    history: "La cuisine mexicaine est patrimoine de l'UNESCO depuis 2010. Le mole negro d'Oaxaca contient jusqu'à 36 ingrédients et peut prendre 3 jours à préparer. Le chocolat, la vanille, les tomates, les piments, l'avocat — tous originaires du Mexique, offerts au monde entier.",
    key_ingredients: ["Piments ancho/chipotle/poblano", "Tomatilles", "Épazote", "Masa harina", "Achiote", "Crema mexicana"],
    famous_chefs: ["Enrique Olvera", "Elena Reygadas", "Ricardo Muñoz Zurita"],
  },
  indian: {
    slug: 'indian',
    title: 'Cuisine Indienne',
    description: 'Curry, masala et pains naan',
    emoji: '🇮🇳',
    color: '#FF9933',
    country: 'Inde',
    history: "La cuisine indienne est l'une des plus anciennes du monde — 5000 ans d'histoire. Elle suit les principes de l'Ayurveda, médecine traditionnelle qui classe les aliments selon leurs effets sur l'énergie du corps. Le curry n'est pas une épice mais un concept anglais : en Inde, chaque plat a sa propre masala.",
    key_ingredients: ["Garam masala", "Ghee", "Cumin noir (kalonji)", "Fenugrec", "Tamarin", "Cardamome verte"],
    famous_chefs: ["Vikas Khanna", "Sanjeev Kapoor", "Manish Mehrotra", "Gaggan Anand"],
  },
  thai: {
    slug: 'thai',
    title: 'Cuisine Thaïlandaise',
    description: 'Pad thaï, laak et soupes de coco',
    emoji: '🇹🇭',
    color: '#A51931',
    country: 'Thaïlande',
    history: "La cuisine thaïlandaise cherche l'équilibre parfait entre 4 saveurs : sucré, salé, acide et pimenté. Autrefois réservée à la cour royale, la cuisine thaïe élaborée est classée patrimoine culturel national. La citronnelle, le galanga et les feuilles de kaffir sont des ingrédients que beaucoup confondent avec leurs cousins européens.",
    key_ingredients: ["Citronnelle", "Galanga", "Feuilles de kaffir", "Pâte de crevettes (kapi)", "Nam pla (sauce poisson)", "Basilic thaï"],
    famous_chefs: ["Bo Songvisava", "Dylan Jones", "Duangporn Songvisava"],
  },
  greek: {
    slug: 'greek',
    title: 'Cuisine Grecque',
    description: 'Mezze, moussaka et tzatziki',
    emoji: '🇬🇷',
    color: '#0D5EAF',
    country: 'Grèce',
    history: "La cuisine grecque est l'ancêtre de la cuisine méditerranéenne. Hippocrate, père de la médecine, considérait que 'que ta nourriture soit ta médecine'. L'huile d'olive grecque est produite depuis 5000 ans. La moussaka telle qu'on la connaît a été standardisée en 1920 par le chef Nikolaos Tselementes.",
    key_ingredients: ["Huile d'olive Kalamata", "Feta AOP", "Origan frais", "Citron de Grèce", "Miel de thym", "Cédrat confit"],
    famous_chefs: ["Yiannis Lucacos", "Nikos Karathanos", "Lefteris Lazarou"],
  },
  chinese: {
    slug: 'chinese',
    title: 'Cuisine Chinoise',
    description: 'Wok, dim sum et sauces authentiques',
    emoji: '🇨🇳',
    color: '#DE2910',
    country: 'Chine',
    history: "La cuisine chinoise est la plus diverse au monde, avec 8 grandes cuisines régionales (Cantonaise, Sichuanaise, Shanghaiaise...). Le wok a 2000 ans d'histoire. L'umami, découvert officiellement au Japon, était utilisé en Chine depuis des siècles via la sauce soja et les champignons shiitake séchés.",
    key_ingredients: ["Huile de sésame", "Sauce hoisin", "Vinaigre de Chinkiang", "Pâte de piment doubanjiang", "Vin de Shaoxing", "Cinq-épices"],
    famous_chefs: ["Ken Hom", "Martin Yan", "Fuchsia Dunlop"],
  },
  pastry: {
    slug: 'pastry',
    title: 'Pâtisserie',
    description: 'Gâteaux, éclairs et macarons',
    emoji: '🎂',
    color: '#F4A6C0',
    country: 'France / Monde',
    history: "La pâtisserie française s'est développée à Versailles pour impressionner les cours européennes. Le macaron parisien actuel a été créé en 1930 par Pierre Desfontaines (Ladurée). L'éclair au chocolat date du XIXe siècle. La pâte feuilletée, selon la légende, aurait été inventée par le peintre Claude Lorrain avant de devenir chef pâtissier.",
    key_ingredients: ["Beurre de tourage 84%", "Farine T45", "Praliné noisette", "Chocolat Valrhona", "Glucose liquide", "Gélatine en feuilles"],
    famous_chefs: ["Pierre Hermé", "Cédric Grolet", "Christophe Michalak", "Gaston Lenôtre"],
  },
  bbq: {
    slug: 'bbq',
    title: 'Barbecue & Grillades',
    description: 'Marinades, fumage et cuissons directes',
    emoji: '🔥',
    color: '#8B0000',
    country: 'États-Unis / Monde',
    history: "Le BBQ américain puise ses racines dans les traditions culinaires des esclaves afro-américains du Sud, qui transformaient des morceaux de viande bas de gamme en plats légendaires via le fumage lent. Chaque région a son style : Kansas City (sauce tomate), Caroline du Nord (vinaigre), Texas (boeuf nature), Memphis (sec).",
    key_ingredients: ["Bois de hickory / mesquite / cerisier", "Paprika fumé", "Sel rose de curing", "Moutarde américaine", "Vinaigre de cidre", "Brown sugar"],
    famous_chefs: ["Aaron Franklin", "Rodney Scott", "Myron Mixon"],
  },
  vegan: {
    slug: 'vegan',
    title: 'Cuisine Vegan',
    description: '100% végétal, 100% savoureux',
    emoji: '🌿',
    color: '#2E7D32',
    country: 'Monde',
    history: "Le végétalisme existe depuis l'Antiquité dans les traditions bouddhistes et jaïnes. Le terme 'vegan' a été créé en 1944 par Donald Watson à Leicester. La cuisine vegan moderne s'appuie sur des techniques innovantes : fermentation, texturisation du gluten, émulsification à l'aquafaba (eau de pois chiche).",
    key_ingredients: ["Aquafaba (eau de pois chiche)", "Levure nutritionnelle", "Tamari (soja sans gluten)", "Cashews trempés", "Agar-agar", "Protéines de pois"],
    famous_chefs: ["Alexis Gauthier", "Matthew Kenney", "Tal Ronnen"],
  },
};

// ---------------------------------------------------------------------------
// LESSON DETAILS (ingredients + anecdotes + tips per lesson)
// ---------------------------------------------------------------------------
export const LESSON_DETAILS: Record<string, Omit<LessonDetail, 'id' | 'path_id' | 'order_index' | 'xp_reward' | 'thumbnail_url'>> = {

  // ── FRENCH ──────────────────────────────────────────────────────────────
  'Les Sauces de Base': {
    title: 'Les Sauces de Base',
    description: 'Béchamel, velouté, hollandaise…',
    duration_minutes: 35,
    difficulty: 'medium',
    ingredients: [
      { name: 'Beurre', quantity: '50', unit: 'g', emoji: '🧈', tip: 'Beurre à 82% min de matière grasse' },
      { name: 'Farine', quantity: '50', unit: 'g', emoji: '🌾' },
      { name: 'Lait entier', quantity: '500', unit: 'ml', emoji: '🥛', tip: 'Chaud pour éviter les grumeaux' },
      { name: 'Noix de muscade', quantity: '1 pincée', emoji: '🌰' },
      { name: 'Sel & poivre blanc', quantity: 'QS', emoji: '🧂' },
    ],
    anecdote: "Les 5 sauces mères françaises (béchamel, velouté, espagnole, hollandaise, tomat) ont été codifiées par Auguste Escoffier vers 1900. Avant lui, Marie-Antoine Carême en avait défini 4. Ces sauces sont la colonne vertébrale de toute la cuisine française classique.",
    chef_tip: "Pour une béchamel sans grumeaux : incorporez le lait chaud en 3 fois en fouettant vigoureusement. Le roux doit refroidir légèrement avant d'ajouter le lait.",
    cultural_note: "La béchamel porte le nom du marquis Louis de Béchameil, financier et courtisan de Louis XIV. Mais c'est probablement un cuisinier anonyme qui l'a inventée — Béchameil n'a fait qu'y apposer son nom.",
  },
  'La Quiche Lorraine': {
    title: 'La Quiche Lorraine',
    description: 'Tarte salée aux lardons et fromage',
    duration_minutes: 50,
    difficulty: 'easy',
    ingredients: [
      { name: 'Pâte brisée', quantity: '250', unit: 'g', emoji: '🫓' },
      { name: 'Lardons fumés', quantity: '200', unit: 'g', emoji: '🥓', tip: 'Blanchir 2 min pour retirer l\'excès de sel' },
      { name: 'Œufs entiers', quantity: '3', emoji: '🥚' },
      { name: 'Crème fraîche épaisse', quantity: '200', unit: 'ml', emoji: '🥛', tip: '30% MG minimum' },
      { name: 'Gruyère râpé', quantity: '100', unit: 'g', emoji: '🧀', tip: 'Optionnel — non traditionnel !' },
      { name: 'Noix de muscade', quantity: '1 pincée', emoji: '🌰' },
    ],
    anecdote: "La vraie quiche lorraine traditionnelle ne contient PAS de fromage ! Seulement des lardons, des œufs et de la crème. Le fromage est une addition moderne. 'Quiche' vient du mot allemand 'Kuchen' (gâteau) — la Lorraine ayant été longtemps sous influence germanique.",
    chef_tip: "Piquez le fond de tarte à la fourchette et cuisez-le 10 min à blanc. La migaine (mélange œufs-crème) doit être à température ambiante avant d'être versée sur les lardons.",
    cultural_note: "La quiche lorraine est née à Nancy et Metz, villes de la région Lorraine. Sa popularité mondiale date de l'après-guerre, quand des soldats américains l'ont découverte et ramenée chez eux.",
  },
  'Le Bœuf Bourguignon': {
    title: 'Le Bœuf Bourguignon',
    description: 'Mijotage et braising à la française',
    duration_minutes: 180,
    difficulty: 'medium',
    ingredients: [
      { name: 'Bœuf paleron ou joue', quantity: '1.2', unit: 'kg', emoji: '🥩', tip: 'Couper en cubes de 5 cm, pas plus petit' },
      { name: 'Pinot Noir de Bourgogne', quantity: '750', unit: 'ml', emoji: '🍷', tip: 'Boire ce qu\'on cuisine !' },
      { name: 'Lardons', quantity: '150', unit: 'g', emoji: '🥓' },
      { name: 'Champignons de Paris', quantity: '300', unit: 'g', emoji: '🍄' },
      { name: 'Oignons grelots', quantity: '200', unit: 'g', emoji: '🧅' },
      { name: 'Bouquet garni', quantity: '1', emoji: '🌿' },
      { name: 'Carottes', quantity: '2', emoji: '🥕' },
      { name: 'Farine', quantity: '2 cs', emoji: '🌾', tip: 'Pour le singer (fariner la viande)' },
    ],
    anecdote: "Julia Child a popularisé le bœuf bourguignon aux États-Unis dans les années 60 via son émission de télévision et son livre 'Mastering the Art of French Cooking'. Elle disait que c'était son plat préféré. La recette date en réalité du Moyen Âge, quand on utilisait le vin pour attendrir des viandes coriaces.",
    chef_tip: "Saisissez la viande EN PETITES QUANTITÉS — si vous en mettez trop, elle bout au lieu de dorer. La couleur brune (réaction de Maillard) apporte 80% du goût final.",
    cultural_note: "La Bourgogne est la région viticole la plus prestigieuse de France. Le vin qu'on y cuisine est le même qu'on y boit : le Pinot Noir. Un vrai Bourguignon ne transige pas sur ce point.",
  },
  'Les Crêpes': {
    title: 'Les Crêpes',
    description: 'Fine crêpe dorée sucrée ou salée',
    duration_minutes: 30,
    difficulty: 'easy',
    ingredients: [
      { name: 'Farine T45', quantity: '250', unit: 'g', emoji: '🌾' },
      { name: 'Œufs', quantity: '3', emoji: '🥚' },
      { name: 'Lait', quantity: '500', unit: 'ml', emoji: '🥛' },
      { name: 'Beurre fondu', quantity: '50', unit: 'g', emoji: '🧈' },
      { name: 'Sucre', quantity: '30', unit: 'g', emoji: '🍬', tip: 'Uniquement pour version sucrée' },
      { name: 'Rhum', quantity: '1 cs', emoji: '🍶', tip: 'Optionnel — arôme classique' },
    ],
    anecdote: "La chandeleur (2 février) est la fête des crêpes en France. La tradition veut qu'on tienne une pièce d'or dans la main gauche en faisant sauter la première crêpe de la main droite — pour s'assurer la prospérité. Les Bretons sont fiers de leurs galettes de sarrasin (crêpes salées), qui existent depuis le XIIIe siècle.",
    chef_tip: "Laissez reposer la pâte 1 heure minimum. Cela permet aux protéines du gluten de se détendre — vos crêpes seront plus souples et moins élastiques.",
    cultural_note: "La crêpe Suzette a été inventée par accident en 1895 à Monte-Carlo par le jeune Auguste Escoffier, alors qu'il travaillait pour le Prince de Galles (futur Édouard VII). Le flambage au Grand Marnier était une erreur devenue un classique.",
  },

  // ── JAPANESE ────────────────────────────────────────────────────────────
  'Le Dashi': {
    title: 'Le Dashi',
    description: 'Le bouillon fondateur de la cuisine japonaise',
    duration_minutes: 20,
    difficulty: 'easy',
    ingredients: [
      { name: 'Kombu séché', quantity: '10', unit: 'g', emoji: '🌿', tip: 'Ne pas laver — la poudre blanche est savoureuse !' },
      { name: 'Katsuobushi (bonite séchée)', quantity: '20', unit: 'g', emoji: '🐟' },
      { name: 'Eau froide', quantity: '1', unit: 'L', emoji: '💧', tip: 'Eau de source si possible' },
    ],
    anecdote: "Le dashi est l'épine dorsale de 90% de la cuisine japonaise. Il a permis au chercheur Kikunae Ikeda de découvrir en 1908 la cinquième saveur : l'umami. L'acide glutamique du kombu et l'inosinate de la bonite créent ensemble une synergie umami extraordinaire.",
    chef_tip: "Ne jamais faire bouillir le kombu — chauffez l'eau à 60°C et laissez infuser 30 min. La bonite se verse en une seule fois quand l'eau frémit, puis on coupe le feu immédiatement.",
    cultural_note: "Il existe deux types de dashi : le ichiban dashi (première infusion, délicat) et le niban dashi (deuxième infusion, plus corsé pour les sauces). Les chefs étoilés japonais consacrent parfois une heure entière à préparer leur dashi du matin.",
  },
  'Les Sushis': {
    title: 'Les Sushis',
    description: 'Riz vinaigré, nori et garnitures',
    duration_minutes: 60,
    difficulty: 'hard',
    ingredients: [
      { name: 'Riz japonais Koshihikari', quantity: '300', unit: 'g', emoji: '🍚', tip: 'Rincer 5x jusqu\'à eau claire' },
      { name: 'Vinaigre de riz', quantity: '60', unit: 'ml', emoji: '🫙' },
      { name: 'Sucre', quantity: '20', unit: 'g', emoji: '🍬' },
      { name: 'Sel fin', quantity: '10', unit: 'g', emoji: '🧂' },
      { name: 'Saumon sashimi grade', quantity: '200', unit: 'g', emoji: '🐟', tip: 'Certifié sashimi-grade = congelé -20°C/7j' },
      { name: 'Nori premium', quantity: '5 feuilles', emoji: '🌿' },
      { name: 'Wasabi frais', quantity: 'QS', emoji: '🌿' },
    ],
    anecdote: "Le sushi tel qu'on le connaît (nigiri) a été inventé vers 1820 à Tokyo (alors Edo) par Hanaya Yohei. C'était un fast-food de rue ! Le sushi fermenté originel (narezushi) existe depuis 1300 ans et prend des mois à préparer. Le saumon en sushi ? Une invention norvégienne des années 1980 pour exporter leur saumon d'élevage au Japon.",
    chef_tip: "Préparez le riz à sushi ('shari') en l'assaisonnant avec un éventail pour le refroidir rapidement sans le rendre collant. La texture idéale : chaque grain doit être individuel mais légèrement collant.",
    cultural_note: "Jiro Ono, 97 ans, tient un restaurant 3 étoiles Michelin de 10 places à Tokyo où les réservations sont impossibles à obtenir. Il dit se lever à 5h chaque matin depuis 75 ans. Son dojo : 'Une fois que tu décides ton métier, plonge-y totalement.'",
  },

  // ── MOROCCAN ────────────────────────────────────────────────────────────
  'Le Tajine d\'Agneau': {
    title: "Le Tajine d'Agneau",
    description: 'Viande fondante aux pruneaux et amandes',
    duration_minutes: 120,
    difficulty: 'medium',
    ingredients: [
      { name: 'Épaule d\'agneau', quantity: '1.2', unit: 'kg', emoji: '🍖', tip: 'Demander au boucher de couper en morceaux de 4 cm' },
      { name: 'Pruneaux d\'Agen', quantity: '200', unit: 'g', emoji: '🫐', tip: 'Tremper 30 min dans du thé à la menthe' },
      { name: 'Amandes mondées', quantity: '100', unit: 'g', emoji: '🌰' },
      { name: 'Oignons', quantity: '3', emoji: '🧅' },
      { name: 'Safran de Taliouine', quantity: '1 pincée', emoji: '🌸', tip: 'Infuser dans 2 cs d\'eau chaude avant usage' },
      { name: 'Ras-el-hanout', quantity: '2 cs', emoji: '🫙' },
      { name: 'Gingembre en poudre', quantity: '1 cs', emoji: '🫚' },
      { name: 'Miel', quantity: '2 cs', emoji: '🍯' },
      { name: 'Huile d\'argan', quantity: '3 cs', emoji: '🫗' },
    ],
    anecdote: "Le tajine tire son nom du plat conique en terre cuite dans lequel il cuit. La vapeur monte, se condense sur le couvercle et retombe sur la viande — une distillation naturelle qui concentre les arômes. On dit que chaque famille marocaine a sa propre recette de tajine, jalousement gardée.",
    chef_tip: "Cuisez à feu très doux (150°C au four ou flamme minimale). La fonte lente à basse température est le secret de la tendreté. Ne jamais ouvrir le couvercle pendant la cuisson.",
    cultural_note: "La ville de Fès est considérée comme la capitale gastronomique du Maroc. Les femmes y sont gardiennes des recettes ancestrales, transmises oralement de mère en fille. Certaines recettes de tajine remontent à la cour de l'empire almohade du XIIIe siècle.",
  },

  // ── ITALIAN ─────────────────────────────────────────────────────────────
  'Les Pâtes Fraîches': {
    title: 'Les Pâtes Fraîches',
    description: 'Tagliatelle, fettuccine maison',
    duration_minutes: 45,
    difficulty: 'medium',
    ingredients: [
      { name: 'Farine 00 (grano tenero)', quantity: '300', unit: 'g', emoji: '🌾', tip: 'La farine 00 donne une texture soyeuse' },
      { name: 'Semoule de blé dur', quantity: '100', unit: 'g', emoji: '🌾', tip: 'Pour la texture al dente' },
      { name: 'Œufs entiers (gros)', quantity: '3', emoji: '🥚' },
      { name: 'Jaunes d\'œufs', quantity: '2', emoji: '🥚', tip: 'Plus de jaunes = pâte plus riche et jaune' },
      { name: 'Huile d\'olive', quantity: '1 cs', emoji: '🫒' },
      { name: 'Sel fin', quantity: '1 pincée', emoji: '🧂' },
    ],
    anecdote: "La légende dit que les tagliatelle ont été créées en 1487 à Bologne par un cuisinier nommé Zefirano pour le mariage de Lucrèce Borgia — inspiré par ses cheveux blonds. L'Academia della Cucina Italiana a même déposé une portion de tagliatelle en or à la chambre de commerce de Bologne pour certifier la largeur exacte : 8mm cuit (1/12270ème de la largeur de la Tour des Asinelli).",
    chef_tip: "Pétrir 10 minutes vigoureusement jusqu'à obtenir une pâte lisse comme de la soie. La reposer 30 min filmée à température ambiante est INDISPENSABLE pour détendre le gluten.",
    cultural_note: "Chaque région d'Italie a ses propres pâtes. Bologne : tagliatelle et tortellini. Rome : rigatoni et tonnarelli. Naples : spaghetti et paccheri. Sardaigne : malloreddus. La forme de la pâte n'est pas aléatoire — elle est pensée pour retenir une sauce spécifique.",
  },
  'Le Risotto': {
    title: 'Le Risotto',
    description: 'Al dente avec mantecatura',
    duration_minutes: 30,
    difficulty: 'hard',
    ingredients: [
      { name: 'Riz Carnaroli (ou Arborio)', quantity: '320', unit: 'g', emoji: '🍚', tip: 'Carnaroli tient mieux la cuisson qu\'Arborio' },
      { name: 'Bouillon chaud (légumes ou volaille)', quantity: '1.2', unit: 'L', emoji: '🫕', tip: 'Doit être CHAUD — ajout de froid casse la cuisson' },
      { name: 'Vin blanc sec', quantity: '150', unit: 'ml', emoji: '🍾' },
      { name: 'Échalotes', quantity: '2', emoji: '🧅' },
      { name: 'Beurre froid', quantity: '60', unit: 'g', emoji: '🧈', tip: 'TRÈS froid pour la mantecatura finale' },
      { name: 'Parmigiano Reggiano 36 mois', quantity: '80', unit: 'g', emoji: '🧀' },
      { name: 'Huile d\'olive', quantity: '3 cs', emoji: '🫒' },
    ],
    anecdote: "La mantecatura est l'étape finale magique du risotto : on ajoute beurre froid et parmesan hors du feu et on mélange vigoureusement pour créer une émulsion crémeuse. Les Italiens disent 'fare la mantecatura' comme on dirait 'monter au beurre'. Sans cette étape, c'est du riz — pas un risotto.",
    chef_tip: "Le risotto doit être servi all'onda (vague) : si vous penchez l'assiette, il doit légèrement s'étaler comme une vague. S'il reste en dôme, il est trop ferme. S'il coule comme de la soupe, trop liquide.",
    cultural_note: "Le risotto Milanese (risotto alla milanese) avec safran est une recette du XVIe siècle. Selon la légende, un maître verrier ajouta du safran à son risotto par erreur, en voulant colorer le verre. Le risque prit il était jaune doré mais délicieux.",
  },
  'Le Tiramisu': {
    title: 'Le Tiramisu',
    description: 'Mascarpone, café, savoiardi',
    duration_minutes: 30,
    difficulty: 'easy',
    ingredients: [
      { name: 'Mascarpone', quantity: '500', unit: 'g', emoji: '🧀', tip: 'Sortir 30 min avant — ne doit pas être trop froid' },
      { name: 'Œufs (jaunes séparés)', quantity: '5', emoji: '🥚' },
      { name: 'Sucre en poudre', quantity: '100', unit: 'g', emoji: '🍬' },
      { name: 'Biscuits savoiardi (doigts de dame)', quantity: '300', unit: 'g', emoji: '🍪' },
      { name: 'Café espresso fort refroidi', quantity: '300', unit: 'ml', emoji: '☕', tip: 'Ajouter 2 cs de Marsala ou Amaretto' },
      { name: 'Cacao amer en poudre', quantity: 'QS', emoji: '🍫' },
    ],
    anecdote: "Le tiramisu ('tire-moi vers le haut' en italien) est apparu dans les années 1960-70 en Vénétie. Il existe une querelle entre Trévise (restaurant 'Le Beccherie', 1969) et Frioul pour sa paternité. Le tiramisu original ne contenait pas de crème fraîche, encore moins de Nutella — ces versions sont des hérésies aux yeux des Italiens.",
    chef_tip: "Montez les blancs en neige ferme séparément et incorporez-les délicatement à la crème mascarpone en soulevant avec une maryse. Ce geste préserve les bulles d'air qui donnent la légèreté.",
    cultural_note: "Le mascarpone est un fromage frais de Lombardie fabriqué en chauffant la crème et en y ajoutant du jus de citron. Son nom viendrait du lombard 'mascherpa' (fromage de sérac). Sa texture crémeuse le rend unique — aucun autre fromage ne peut le remplacer.",
  },

  // ── INDIAN ──────────────────────────────────────────────────────────────
  'Le Curry Butter Chicken': {
    title: 'Le Curry Butter Chicken',
    description: 'Poulet en sauce tomate-crème épicée',
    duration_minutes: 50,
    difficulty: 'medium',
    ingredients: [
      { name: 'Poulet (hauts de cuisse)', quantity: '800', unit: 'g', emoji: '🍗', tip: 'Désosser et couper en 4cm — plus savoureux que le blanc' },
      { name: 'Yaourt entier', quantity: '150', unit: 'g', emoji: '🥛', tip: 'Pour la marinade — attendrit le poulet' },
      { name: 'Tomates concassées', quantity: '400', unit: 'g', emoji: '🍅' },
      { name: 'Crème liquide entière', quantity: '150', unit: 'ml', emoji: '🥛' },
      { name: 'Beurre (ghee de préférence)', quantity: '60', unit: 'g', emoji: '🧈' },
      { name: 'Garam masala', quantity: '2 cc', emoji: '🫙' },
      { name: 'Cumin en poudre', quantity: '1 cc', emoji: '🫙' },
      { name: 'Paprika fumé', quantity: '2 cc', emoji: '🫙' },
      { name: 'Gingembre frais râpé', quantity: '2 cm', emoji: '🫚' },
      { name: 'Ail', quantity: '4 gousses', emoji: '🧄' },
      { name: 'Kashmiri chili (couleur)', quantity: '2 cc', emoji: '🌶️' },
    ],
    anecdote: "Le Butter Chicken (Murgh Makhani) a été inventé par accident vers 1948 au restaurant Moti Mahal de Delhi. Le chef Kundan Lal Gujral a mélangé du poulet tandoori restant avec une sauce tomate-beurre pour ne pas le gaspiller. C'est aujourd'hui le plat indien le plus commandé au monde.",
    chef_tip: "Marinez le poulet au moins 4 heures (idéalement une nuit) dans le yaourt et les épices. La protéase du yaourt attendrit les fibres de la viande. Faites cuire le poulet séparément à haute température avant de l'ajouter à la sauce.",
    cultural_note: "L'Inde est le pays qui consomme le moins de viande par habitant au monde — 80% de la population est végétarienne ou semi-végétarienne. Le curry 'de restaurant' qu'on connaît à l'étranger est souvent très différent de la cuisine familiale indienne, plus variée et plus épicée.",
  },

  // ── FRENCH NEW LESSONS ───────────────────────────────────────────────────
  'La Ratatouille': {
    title: 'La Ratatouille',
    description: 'Légumes provençaux mijotés à l\'huile d\'olive',
    duration_minutes: 50,
    difficulty: 'easy',
    ingredients: [
      { name: 'Courgettes', quantity: '2', emoji: '🥒' },
      { name: 'Aubergines', quantity: '1 grosse', emoji: '🍆' },
      { name: 'Poivrons (rouge + jaune)', quantity: '2', emoji: '🫑' },
      { name: 'Tomates mûres', quantity: '4', emoji: '🍅', tip: 'Monder (ébouillanter) pour retirer la peau' },
      { name: 'Oignons', quantity: '2', emoji: '🧅' },
      { name: 'Ail', quantity: '3 gousses', emoji: '🧄' },
      { name: 'Huile d\'olive', quantity: '8 cs', emoji: '🫒', tip: 'Soyez généreux — c\'est la base de la saveur' },
      { name: 'Thym & basilic frais', quantity: 'QS', emoji: '🌿' },
    ],
    anecdote: "La ratatouille est un plat d'été niçois. Son nom vient du verbe 'touiller' (remuer). Le film Pixar de 2007 l'a rendue célèbre dans le monde entier. La recette 'confit byaldi' du chef Thomas Keller (qui a inspiré le film) est différente : les légumes sont tranchés finement et disposés en couches.",
    chef_tip: "Le secret : faites cuire chaque légume séparément avant de les réunir. Les courgettes, aubergines et poivrons ont des temps de cuisson différents. Réunissez-les en fin pour 20 min ensemble.",
    cultural_note: "La Provence est la région française la plus ensoleillée — ses légumes d'été sont incomparables. La ratatouille se mange chaude, froide ou tiède, le lendemain elle est encore meilleure.",
  },

  'Le Confit de Canard': {
    title: 'Le Confit de Canard',
    description: 'Cuisson lente dans la graisse, tradition gasconne',
    duration_minutes: 180,
    difficulty: 'medium',
    ingredients: [
      { name: 'Cuisses de canard', quantity: '4', emoji: '🦆', tip: 'Label Rouge ou Fermier du Gers' },
      { name: 'Gros sel de Guérande', quantity: '50', unit: 'g', emoji: '🧂', tip: 'Mélanger avec thym, laurier, ail pour la saumure sèche' },
      { name: 'Graisse de canard', quantity: '500', unit: 'g', emoji: '🫙', tip: 'Ou huile de tournesol en dépannage' },
      { name: 'Ail', quantity: '6 gousses', emoji: '🧄' },
      { name: 'Thym & laurier', quantity: 'QS', emoji: '🌿' },
      { name: 'Pommes de terre sarladaises', quantity: '800', unit: 'g', emoji: '🥔', tip: 'Cuites dans la graisse de canard — incontournable' },
    ],
    anecdote: "Le confit de canard est né de la nécessité : en Gascogne, les paysans abattaient les canards en automne et conservaient la viande dans sa propre graisse pour l'hiver. La graisse est un excellent conservateur naturel — un confit peut se garder des mois. Aujourd'hui, c'est un plat de luxe.",
    chef_tip: "La technique en 2 temps : 1) Saler les cuisses 12h au frigo. 2) Cuire à 80-90°C dans la graisse pendant 2h30. Terminez en faisant dorer la peau à la poêle très chaude pendant 3 minutes.",
    cultural_note: "La Gascogne (actuel Gers) est le berceau du confit et du foie gras. Armagnac, magret, cassoulet, confit — cette région a plus de recettes emblématiques au km² que n'importe où en France.",
  },

  'La Tarte Tatin': {
    title: 'La Tarte Tatin',
    description: 'Tarte renversée aux pommes caramélisées',
    duration_minutes: 60,
    difficulty: 'medium',
    ingredients: [
      { name: 'Pommes Golden ou Reinette', quantity: '8', emoji: '🍎', tip: 'Pommes fermes qui tiennent à la cuisson' },
      { name: 'Beurre', quantity: '80', unit: 'g', emoji: '🧈', tip: 'Beurre demi-sel pour une touche bretonne' },
      { name: 'Sucre en poudre', quantity: '150', unit: 'g', emoji: '🍬' },
      { name: 'Pâte feuilletée', quantity: '1 rouleau', emoji: '🫓', tip: 'Ou pâte brisée pour une version plus rustique' },
      { name: 'Vanille', quantity: '1 gousse', emoji: '🍦' },
    ],
    anecdote: "La tarte Tatin a été inventée par accident vers 1898 par les sœurs Stéphanie et Caroline Tatin à l'Hôtel Tatin à Lamotte-Beuvron (Sologne). Stéphanie aurait oublié la pâte et posé les pommes directement dans le moule beurré-sucré, ajoutant la pâte par-dessus — puis retournant l'ensemble. L'accident est devenu un classique.",
    chef_tip: "Caramélisez d'abord le beurre et le sucre dans la poêle, ajoutez les pommes coupées en quartiers épais et laissez-les colorer 15-20 min. La pâte se pose dessus comme un couvercle, puis on enfourne et on retourne.",
    cultural_note: "La tarte Tatin figure au patrimoine gastronomique français. Elle est aujourd'hui servie dans des restaurants du monde entier. La ville de Lamotte-Beuvron organise chaque année un concours de tarte Tatin.",
  },

  'Le Coq au Vin': {
    title: 'Le Coq au Vin',
    description: 'Poulet braisé au vin rouge, lardons, champignons',
    duration_minutes: 120,
    difficulty: 'medium',
    ingredients: [
      { name: 'Poulet fermier (ou coq)', quantity: '1.8', unit: 'kg', emoji: '🍗', tip: 'Couper en 8 morceaux — garde la peau pour la couleur' },
      { name: 'Pinot Noir de Bourgogne', quantity: '750', unit: 'ml', emoji: '🍷' },
      { name: 'Lardons fumés', quantity: '200', unit: 'g', emoji: '🥓' },
      { name: 'Champignons de Paris', quantity: '250', unit: 'g', emoji: '🍄' },
      { name: 'Oignons grelots', quantity: '200', unit: 'g', emoji: '🧅' },
      { name: 'Ail', quantity: '4 gousses', emoji: '🧄' },
      { name: 'Cognac', quantity: '5 cs', emoji: '🥃', tip: 'Pour flamber et parfumer' },
      { name: 'Bouquet garni', quantity: '1', emoji: '🌿' },
    ],
    anecdote: "Julia Child a popularisé le coq au vin en Amérique dans les années 60. Le 'coq' original était un vieux mâle trop coriace pour être rôti — la cuisson prolongée dans le vin l'attendrissait. Aujourd'hui on utilise du poulet fermier plus tendre, mais la technique reste identique.",
    chef_tip: "Marinez les morceaux de poulet dans le vin avec les aromates pendant 12 heures. Égouttez, séchez et saisissez à feu vif. La coloration est essentielle pour la saveur finale.",
    cultural_note: "Le coq au vin est le plat emblématique de la Bourgogne. Chaque région a sa variante : coq au Riesling en Alsace, coq au Champagne en Champagne, coq au cidre en Normandie.",
  },

  'Le Pot-au-Feu': {
    title: 'Le Pot-au-Feu',
    description: 'Le plat national français par excellence — viandes et légumes mijotés dans un bouillon parfumé.',
    emoji: '🍲',
    ingredients: [
      { name: 'Paleron de bœuf', quantity: '500', unit: 'g', emoji: '🥩', tip: 'Ou plat de côtes — les morceaux gélatineux sont clés' },
      { name: 'Os à moelle', quantity: '2', emoji: '🦴' },
      { name: 'Carottes', quantity: '4', emoji: '🥕' },
      { name: 'Poireaux', quantity: '2', emoji: '🥬' },
      { name: 'Navet', quantity: '2', emoji: '🫚' },
      { name: 'Céleri branche', quantity: '2', emoji: '🌿' },
      { name: 'Oignon brûlé', quantity: '1', emoji: '🧅', tip: 'Brûlé à sec donne couleur et goût au bouillon' },
      { name: 'Bouquet garni', quantity: '1', emoji: '🌿' },
      { name: 'Gros sel', quantity: 'q.s.', emoji: '🧂' },
    ],
    anecdote: "Le pot-au-feu est cité comme symbole de la cuisine française depuis le XIVe siècle. Henri IV souhaitait que chaque paysan français puisse s'offrir une poule au pot le dimanche — l'esprit de générosité du pot-au-feu est ancré dans l'identité nationale.",
    chef_tip: "Démarrez toujours la viande dans l'eau froide — cela clarifie le bouillon en laissant les protéines coaguler lentement. Écumez abondamment au début. Servez le bouillon en entrée, puis la viande avec cornichons, moutarde à l'ancienne et fleur de sel.",
    cultural_note: "Alexandre Dumas écrivait : 'Le pot-au-feu est la base de l'empire français'. C'est le seul plat où le bouillon, les légumes ET la viande sont trois services distincts servis successivement.",
  },

  'Les Gougères': {
    title: 'Les Gougères',
    description: 'Petits choux au fromage bourguignons — l\'amuse-bouche parfait avec un verre de Chablis.',
    emoji: '🧀',
    ingredients: [
      { name: 'Eau', quantity: '150', unit: 'ml', emoji: '💧' },
      { name: 'Beurre', quantity: '60', unit: 'g', emoji: '🧈' },
      { name: 'Farine', quantity: '90', unit: 'g', emoji: '🌾' },
      { name: 'Œufs', quantity: '3', emoji: '🥚' },
      { name: 'Gruyère râpé', quantity: '100', unit: 'g', emoji: '🧀', tip: 'Comté ou emmental fonctionnent aussi' },
      { name: 'Sel, poivre', emoji: '🧂' },
      { name: 'Muscade', quantity: '1 pincée', emoji: '🫙' },
    ],
    anecdote: "Les gougères sont nées en Bourgogne au XVIIIe siècle. Elles sont traditionnellement servies lors des dégustations de vins dans les caves bourguignonnes — le fromage en pâte équilibre l'acidité des grands crus blancs comme le Meursault.",
    chef_tip: "La pâte à choux doit être assez ferme pour tenir à la poche à douille — ajoutez les œufs un à un et testez la consistance après chaque. Une bonne pâte forme un 'V' au bout de la spatule. Parsemez de gruyère supplémentaire avant d'enfourner.",
    cultural_note: "Dans les grandes maisons bourguignonnes, on ne dit jamais 'non' à une gougère. Elles sortent du four juste avant les convives — le croustillant ne dure que 10 minutes.",
  },

  'La Bavette à l\'Échalote': {
    title: "La Bavette à l'Échalote",
    description: 'La pièce du boucher par excellence — cuisson vive, sauce réduite au vinaigre et échalotes confites.',
    emoji: '🥩',
    ingredients: [
      { name: 'Bavette d\'aloyau', quantity: '300', unit: 'g', emoji: '🥩', tip: 'Comptez 150g par personne — pièce tendre et savoureuse' },
      { name: 'Échalotes', quantity: '3', emoji: '🧅' },
      { name: 'Beurre', quantity: '40', unit: 'g', emoji: '🧈' },
      { name: 'Vinaigre de vin rouge', quantity: '3', unit: 'c.s.', emoji: '🍷' },
      { name: 'Persil plat', quantity: '1 bouquet', emoji: '🌿' },
      { name: 'Sel, poivre', emoji: '🧂' },
    ],
    anecdote: "La bavette à l'échalote est la pièce préférée des bistrots parisiens depuis la Belle Époque. Elle est issue du flanc du bœuf — un muscle très travaillé qui concentre la saveur mais demande une cuisson courte et une découpe en travers du grain.",
    chef_tip: "Cuisez la bavette dans une poêle en fonte très chaude, 2-3 minutes par face pour une belle caramélisation. Laissez reposer 2 minutes avant de couper. Pour la sauce : faites fondre les échalotes dans le beurre, déglacez au vinaigre, réduisez de moitié.",
    cultural_note: "Le terme 'pièce du boucher' vient du fait que le boucher gardait traditionnellement ces morceaux savoureux pour lui — la bavette, la hampe, l'onglet. Aujourd'hui on les trouve chez tout bon boucher, mais ils restent sous-cotés.",
  },

  'Les Oeufs Cocotte': {
    title: 'Les Oeufs Cocotte',
    description: 'Œufs cuits au four en ramequin — simple, rapide, et infiniment personnalisable.',
    emoji: '🥚',
    ingredients: [
      { name: 'Œufs frais', quantity: '2', emoji: '🥚', tip: 'Très frais — le blanc se tient mieux' },
      { name: 'Crème fraîche épaisse', quantity: '2', unit: 'c.s.', emoji: '🫙' },
      { name: 'Beurre', quantity: '10', unit: 'g', emoji: '🧈' },
      { name: 'Ciboulette ciselée', emoji: '🌿' },
      { name: 'Sel, poivre', emoji: '🧂' },
      { name: 'Garniture au choix', emoji: '🍄', tip: 'Lardons, champignons, saumon fumé, épinards...' },
    ],
    anecdote: "Les œufs en cocotte sont mentionnés dans les écrits d'Escoffier dès 1900. Ils étaient servis dans les sanatoriums et hôtels de luxe comme plat de convalescence — légère, nourrissant, élégant. Aujourd'hui c'est l'entrée bistrot la plus facile à impressionner.",
    chef_tip: "Cuisez au bain-marie au four à 180°C pendant 10-12 minutes. Le blanc doit être pris mais le jaune encore coulant. Couvrez le ramequin de papier alu les 8 premières minutes. Servez directement dans le ramequin avec des mouillettes grillées.",
    cultural_note: "Le terme 'cocotte' vient du mot enfantin pour poule. Les ramequins en porcelaine blanche sont l'ustensile canonique — ils retiennent la chaleur uniformément et passent directement à table.",
  },

  'Le Paris-Brest': {
    title: 'Le Paris-Brest',
    description: 'Choux en couronne garnis de crème pralinée — créé en 1910 pour célébrer la course cycliste.',
    emoji: '🍩',
    ingredients: [
      { name: 'Pâte à choux', quantity: '1 portion', emoji: '🍩' },
      { name: 'Crème pâtissière', quantity: '250', unit: 'g', emoji: '🫙' },
      { name: 'Beurre pommade', quantity: '150', unit: 'g', emoji: '🧈' },
      { name: 'Praliné noisettes', quantity: '100', unit: 'g', emoji: '🌰', tip: 'Fait maison : noisettes caramélisées et mixées' },
      { name: 'Amandes effilées', quantity: '50', unit: 'g', emoji: '🌾' },
      { name: 'Sucre glace', emoji: '🍬' },
    ],
    anecdote: "Le Paris-Brest a été créé en 1910 par le pâtissier Louis Durand de Maisons-Laffitte, à la demande de Pierre Giffard, organisateur de la course Paris-Brest-Paris. La forme en roue de vélo est intentionnelle — la course faisait 1200 km aller-retour.",
    chef_tip: "Le secret est la crème mousseline pralinée : incorporez le beurre pommade dans la crème pâtissière refroidie, au fouet, jusqu'à obtenir une texture légère et aérée. Le praliné maison (noisettes caramélisées puis mixées) change tout.",
    cultural_note: "La course Paris-Brest-Paris existe toujours — c'est la plus ancienne course cycliste de permanence au monde. Les participants la complètent en moins de 90 heures. Le Paris-Brest est toujours vendu dans les pâtisseries du parcours.",
  },

  'La Tempura': {
    title: 'La Tempura',
    description: 'Beignets ultra-légers — la technique de friture japonaise introduite par les Portugais.',
    emoji: '🍤',
    ingredients: [
      { name: 'Crevettes', quantity: '8', emoji: '🦐', tip: 'Incisez le ventre pour éviter qu\'elles se recroquevillent' },
      { name: 'Légumes variés', emoji: '🥦', tip: 'Patate douce, courgette, shiitake, piment vert' },
      { name: 'Farine à tempura', quantity: '150', unit: 'g', emoji: '🌾' },
      { name: 'Eau glacée', quantity: '200', unit: 'ml', emoji: '❄️', tip: 'Clé du croustillant — ne pas mélanger trop' },
      { name: 'Jaune d\'œuf', quantity: '1', emoji: '🥚' },
      { name: 'Huile de friture', quantity: '1', unit: 'L', emoji: '🫙' },
      { name: 'Sauce tentsuyu (dashi + mirin + soja)', emoji: '🍜' },
    ],
    anecdote: "La tempura a été introduite au Japon par les missionnaires jésuites portugais au XVIe siècle. Le mot vient de 'Quatuor anni tempora' (les quatre temps de jeûne chrétien). Les Japonais ont perfectionné la technique jusqu'à en faire un art — il faut des années d'apprentissage dans les restaurants de tempura traditionnels.",
    chef_tip: "Ne mélangez jamais trop la pâte — les grumeaux sont vos alliés (ils créent des poches d'air croustillantes). Maintenez l'huile à 170-180°C. Faites frire en petites quantités pour ne pas faire chuter la température.",
    cultural_note: "À Tokyo, les restaurants de tempura haut de gamme servent chaque pièce dès qu'elle sort de la friture, une par une. Le chef frit devant vous. Une séance peut durer 90 minutes et coûter 200€ — la maîtrise du feu et de la pâte justifient cet art.",
  },

  'Les Tacos al Pastor': {
    title: 'Les Tacos al Pastor',
    description: 'Porc mariné cuit à la broche verticale — l\'héritage libanais du Mexique.',
    emoji: '🌮',
    ingredients: [
      { name: 'Échine de porc', quantity: '500', unit: 'g', emoji: '🥩' },
      { name: 'Piments guajillo séchés', quantity: '4', emoji: '🌶️', tip: 'Faire tremper 20 min dans l\'eau chaude' },
      { name: 'Piments ancho séchés', quantity: '2', emoji: '🌶️' },
      { name: 'Ananas frais', quantity: '1/4', emoji: '🍍', tip: 'Dans la marinade ET en garniture' },
      { name: 'Vinaigre de cidre', quantity: '2', unit: 'c.s.', emoji: '🍎' },
      { name: 'Achiote (rocou)', quantity: '1', unit: 'c.s.', emoji: '🟠', tip: 'Donne la couleur orange caractéristique' },
      { name: 'Tortillas de maïs', quantity: '12', emoji: '🫓' },
      { name: 'Coriandre, oignon, lime', emoji: '🌿' },
    ],
    anecdote: "Les tacos al pastor sont nés à Puebla dans les années 1930, créés par des immigrés libanais qui ont adapté leur technique du shawarma au porc et aux saveurs mexicaines. La broche verticale (trompo) vient directement du monde arabe. C'est l'exemple parfait de métissage culinaire.",
    chef_tip: "Sans trompo, faites mariner le porc 24h minimum et cuisez-le en tranches fines à la poêle très chaude. L'ananas dans la marinade attendrit la viande (bromélaïne). Servez avec un carré d'ananas grillé — c'est obligatoire.",
    cultural_note: "À Mexico City, les meilleurs tacos al pastor se trouvent dans les taquerías de rue qui fonctionnent depuis des générations. Le taquero (tacos chef) découpe le porc du trompo avec une dextérité impressionnante. Le vrai al pastor n'a pas de fromage.",
  },

  'Les Bases Pâtissières': {
    title: 'Les Bases Pâtissières',
    description: 'Les piliers de la pâtisserie française — pâtes, crèmes, et la science du sucre.',
    emoji: '🎂',
    ingredients: [
      { name: 'Farine T45 (pâtisserie)', emoji: '🌾', tip: 'Plus fine que la T55 — gluten plus faible, texture plus tendre' },
      { name: 'Sucre semoule', emoji: '🍬' },
      { name: 'Beurre 82% MG', emoji: '🧈', tip: 'Le beurre de qualité change tout en pâtisserie' },
      { name: 'Œufs extra-frais', emoji: '🥚', tip: 'Tempérés (sorti 30 min avant)' },
      { name: 'Sel fin', emoji: '🧂', tip: 'Même en sucré — il révèle les arômes' },
      { name: 'Vanille en gousse', emoji: '🌿' },
    ],
    anecdote: "La pâtisserie française moderne est née avec Marie-Antoine Carême (1784-1833), qui l'a codifiée et élevée au rang d'art architectural. Il construisait des pièces montées en pâte feuilletée de plusieurs mètres de haut. Ses livres ont établi les bases que l'on enseigne encore aujourd'hui.",
    chef_tip: "En pâtisserie, pesez tout au gramme près. Le 'coup de main' s'apprend, mais les proportions ne s'improvisent pas. Lisez toujours la recette entière avant de commencer, et préparez tous vos ingrédients (mise en place) avant de toucher quoi que ce soit.",
    cultural_note: "La France est le seul pays à avoir une appellation 'Meilleur Ouvrier de France' (MOF) en pâtisserie — un concours d'État d'une exigence absolue. Les lauréats portent un col tricolore et ont consacré des années à maîtriser chaque geste.",
  },

  'La Crème Pâtissière': {
    title: 'La Crème Pâtissière',
    description: 'La base de la pâtisserie française — éclairs, tartes aux fruits, mille-feuilles.',
    emoji: '🫙',
    ingredients: [
      { name: 'Lait entier', quantity: '500', unit: 'ml', emoji: '🥛' },
      { name: 'Jaunes d\'œufs', quantity: '4', emoji: '🥚' },
      { name: 'Sucre semoule', quantity: '100', unit: 'g', emoji: '🍬' },
      { name: 'Fécule de maïs (Maïzena)', quantity: '40', unit: 'g', emoji: '🌽' },
      { name: 'Beurre', quantity: '30', unit: 'g', emoji: '🧈', tip: 'Incorporé hors du feu pour l\'onctuosité' },
      { name: 'Vanille gousse', quantity: '1', emoji: '🌿' },
    ],
    anecdote: "La crème pâtissière (ou 'pastry cream') est la mère de nombreuses préparations : crème légère (+ chantilly), crème mousseline (+ beurre), crème chiboust (+ meringue italienne). Maîtriser la crème pâtissière c'est débloquer un monde entier de desserts.",
    chef_tip: "Fouettez les jaunes avec le sucre jusqu'à blanchissement avant d'ajouter la fécule. Versez le lait chaud en filet tout en fouettant pour tempérer. Recuisez à la casserole en remuant constamment jusqu'à ébullition — 1 minute d'ébullition détruit les enzymes du jaune qui liquéfieraient la crème.",
    cultural_note: "La pâtisserie japonaise a adopté la crème pâtissière avec passion — leurs 'custard cream puffs' (shu cream) sont devenus un symbole de leur patisserie. Chaque boulangerie Beard Papa en vend des millions par an au Japon.",
  },

  'Les Éclairs au Chocolat': {
    title: 'Les Éclairs au Chocolat',
    description: 'Choux allongés garnis de crème pâtissière au chocolat et glaçage fondant.',
    emoji: '🍫',
    ingredients: [
      { name: 'Pâte à choux', quantity: '1 portion', emoji: '🍩' },
      { name: 'Crème pâtissière', quantity: '300', unit: 'g', emoji: '🫙' },
      { name: 'Chocolat noir 70%', quantity: '100', unit: 'g', emoji: '🍫' },
      { name: 'Crème liquide', quantity: '50', unit: 'ml', emoji: '🫙' },
      { name: 'Sucre glace', emoji: '🍬' },
    ],
    anecdote: "L'éclair aurait été inventé par Marie-Antoine Carême dans les années 1820. Son nom viendrait du fait qu'il se dévore 'en un éclair'. À Paris, la maison L'Éclair de Génie a révolutionné la pâtisserie moderne en 2012 avec des éclairs haute couture aux 30 saveurs.",
    chef_tip: "Percez 3 petits trous sous l'éclair avec la pointe d'une douille unie pour le garnir — cela évite de le couper. Trempez le dessus dans le glaçage tiède (fondu mais pas chaud) en tenant l'éclair horizontalement et en le retournant d'un geste franc.",
    cultural_note: "L'éclair au chocolat est le gâteau préféré des Français selon un sondage de 2017. La version café (café et ganache café) est sa rivale directe. Les pâtissiers parisiens rivalisent de créativité : éclairs au matcha, au caramel beurre salé, à la framboise...",
  },

  'La Pâte Feuilletée': {
    title: 'La Pâte Feuilletée',
    description: 'La reine des pâtes — 729 couches de beurre et de détrempe pour un croustillant incomparable.',
    emoji: '🥐',
    ingredients: [
      { name: 'Farine T55', quantity: '250', unit: 'g', emoji: '🌾' },
      { name: 'Eau froide', quantity: '125', unit: 'ml', emoji: '💧' },
      { name: 'Sel', quantity: '5', unit: 'g', emoji: '🧂' },
      { name: 'Beurre sec (84% MG) pour tourage', quantity: '200', unit: 'g', emoji: '🧈', tip: 'Beurre de tourage ou beurre AOP Poitou-Charentes bien froid' },
      { name: 'Beurre pour la détrempe', quantity: '20', unit: 'g', emoji: '🧈' },
    ],
    anecdote: "La légende attribue l'invention de la pâte feuilletée à Claude Lorrain, peintre du XVIIe siècle, qui aurait été apprenti pâtissier. La recette est citée dans 'La Varenne' (1651), premier livre de cuisine français moderne. Les 3⁶ = 729 couches d'un feuilletage classique à 6 tours restent la référence absolue.",
    chef_tip: "Travaillez dans un environnement froid (moins de 18°C idéalement). Entre chaque tour, laissez reposer 20-30 minutes au réfrigérateur pour détendre le gluten et refroidir le beurre. Ne roulez jamais avec trop de farine — elle assèche le feuilletage.",
    cultural_note: "Le croissant est fait de pâte feuilletée levée (avec levure). La pâte feuilletée pure est utilisée pour les mille-feuilles, les galettes des rois, les pithiviers, les palmiers, les chaussons aux pommes. Sa maîtrise est un marqueur du niveau technique d'un pâtissier.",
  },

  'Les Bases Méditerranéennes': {
    title: 'Les Bases Méditerranéennes',
    description: 'La trinité grecque : huile d\'olive, citron et herbes de la mer.',
    emoji: '🫒',
    ingredients: [
      { name: 'Huile d\'olive extra vierge grecque', emoji: '🫒', tip: 'AOP de Kalamata ou Crète — couleur dorée, arôme fruité' },
      { name: 'Citron non traité', emoji: '🍋', tip: 'Le zeste est aussi important que le jus' },
      { name: 'Origan séché', emoji: '🌿', tip: 'L\'origan grec séché est bien plus intense que le frais' },
      { name: 'Ail', emoji: '🧄' },
      { name: 'Feta AOP', emoji: '🧀' },
      { name: 'Olives de Kalamata', emoji: '🫒' },
    ],
    anecdote: "Le régime méditerranéen a été inscrit au patrimoine immatériel de l'UNESCO en 2013. Des études menées sur 7 pays depuis les années 1950 (Seven Countries Study) ont démontré que les populations côtières méditerranéennes avaient les plus faibles taux de maladies cardiovasculaires — grâce notamment à l'huile d'olive.",
    chef_tip: "En cuisine grecque, l'huile d'olive est utilisée crue sur les plats chauds, jamais uniquement pour la cuisson. Le citron est pressé à la dernière seconde. Apprenez à doser l'origan : une pincée au bon moment parfume tout le plat.",
    cultural_note: "La Grèce produit 70% de l'huile d'olive Kalamata mondiale et est le 3e producteur mondial. La tradition de l'olivier remonte à 6000 ans en Grèce — Athéna aurait offert le premier olivier à la cité qui porta son nom.",
  },

  'Le Tzatziki': {
    title: 'Le Tzatziki',
    description: 'Sauce froide au yaourt, concombre et ail — le condiment phare de la cuisine grecque.',
    emoji: '🥣',
    ingredients: [
      { name: 'Yaourt grec épais (10% MG)', quantity: '400', unit: 'g', emoji: '🥛', tip: 'Strainer si nécessaire — doit être très ferme' },
      { name: 'Concombre', quantity: '1/2', emoji: '🥒', tip: 'Epépiner, râper et BIEN essorer — l\'eau tue le tzatziki' },
      { name: 'Ail', quantity: '2', unit: 'gousses', emoji: '🧄' },
      { name: 'Huile d\'olive', quantity: '2', unit: 'c.s.', emoji: '🫒' },
      { name: 'Aneth ou menthe fraîche', emoji: '🌿' },
      { name: 'Vinaigre de vin blanc', quantity: '1', unit: 'c.c.', emoji: '🍶' },
      { name: 'Sel', emoji: '🧂' },
    ],
    anecdote: "Le tzatziki vient du persan 'zhaziki'. Il a été adopté par les Grecs via l'Empire Ottoman. En Turquie, le même plat s'appelle 'cacık'. La variante indienne est le raita, iranienne le mast-o-khiar — preuve que les idées culinaires voyagent avec les routes commerciales.",
    chef_tip: "L'étape cruciale : après avoir râpé le concombre, posez-le dans un torchon propre et TORDEZ pour extraire toute l'eau. Un tzatziki trop liquide n'adhère pas aux aliments. Laissez reposer 1h au frais avant de servir pour que les arômes se développent.",
    cultural_note: "En Grèce, le tzatziki est servi avec presque tout : souvlaki, moussaka, légumes grillés, pain pita. Il est considéré comme un 'meze' (petit plat d'accompagnement) plutôt qu'une sauce. On ne le verse jamais — on le pose à côté.",
  },

  'La Moussaka': {
    title: 'La Moussaka',
    description: 'Le gratin emblématique grec : aubergines, viande hachée et béchamel.',
    emoji: '🫕',
    ingredients: [
      { name: 'Aubergines', quantity: '3', emoji: '🍆', tip: 'Salez et laissez dégorger 30 min pour éliminer l\'amertume' },
      { name: 'Viande hachée d\'agneau (ou bœuf)', quantity: '500', unit: 'g', emoji: '🥩' },
      { name: 'Tomates concassées', quantity: '400', unit: 'g', emoji: '🍅' },
      { name: 'Oignon', quantity: '2', emoji: '🧅' },
      { name: 'Cannelle', quantity: '1', unit: 'c.c.', emoji: '🫙', tip: 'La touche grecque indispensable' },
      { name: 'Béchamel épaisse', quantity: '500', unit: 'ml', emoji: '🫙' },
      { name: 'Parmesan râpé', quantity: '50', unit: 'g', emoji: '🧀' },
    ],
    anecdote: "La moussaka a été standardisée et 'classicisée' par Nikolaos Tselementes, le premier chef grec formé à l'école française, dans son livre de 1910. Avant lui, la moussaka n'avait pas de béchamel. Tselementes a introduit l'influence de la cuisine française dans la gastronomie grecque.",
    chef_tip: "Faites frire ou rôtir les aubergines séparément avant le montage — elles doivent être bien colorées et fondantes. La béchamel doit être épaisse (presque une crème) pour tenir à la coupe. Laissez reposer 15 minutes après cuisson avant de servir.",
    cultural_note: "La moussaka est le plat grec le plus connu à l'étranger, mais en Grèce on la mange surtout comme plat familial du dimanche. Elle est souvent meilleure réchauffée le lendemain — les saveurs ont eu le temps de se développer.",
  },

  'Les Techniques au Wok': {
    title: 'Les Techniques au Wok',
    description: 'Maîtriser le feu vif du wok : sauté, fumée et umami instantané.',
    emoji: '🥘',
    ingredients: [
      { name: 'Wok en acier au carbone', emoji: '🍳', tip: 'Assaisonnez-le comme une poêle en fonte — il s\'améliore avec le temps' },
      { name: 'Huile à haute température (arachide, tournesol)', emoji: '🫙' },
      { name: 'Gingembre frais', emoji: '🫚', tip: 'Toujours ajouté en début de cuisson dans l\'huile chaude' },
      { name: 'Ail', emoji: '🧄' },
      { name: 'Sauce soja', emoji: '🍶' },
      { name: 'Huile de sésame toastée', emoji: '🌰', tip: 'Toujours en fin de cuisson — elle brûle vite' },
    ],
    anecdote: "Le wok existe depuis 2000 ans en Chine. Son invention a permis de cuire avec très peu de combustible — essentiel dans une Chine à la fois densément peuplée et pauvre en bois. La forme en cône concentre la chaleur au centre et permet de 'wok hei' — le souffle du wok, cette fumée caractéristique qui parfume la cuisine cantonaise.",
    chef_tip: "Le secret du wok hei : votre cuisinière domestique n'est pas assez puissante. Solution : chauffez le wok vide à feu maximum pendant 3-4 minutes avant de cuire, cuisinez en petites quantités (la nourriture doit sauter, pas mijoter), et ne remuez pas trop.",
    cultural_note: "La cuisine au wok est si rapide qu'elle demande toute la mise en place avant d'allumer le feu. Une fois lancé, un plat sauté prend moins de 3 minutes. Les cuisiniers de restauration cantonaise peuvent faire sauter 50 plats à l'heure en cuisine professionnelle.",
  },

  'Le Poulet Teriyaki': {
    title: 'Le Poulet Teriyaki',
    description: 'Cuisse de poulet laquée à la sauce teriyaki — umami sucré-salé.',
    emoji: '🍗',
    ingredients: [
      { name: 'Cuisses de poulet désossées', quantity: '4', emoji: '🍗', tip: 'La peau doit être croustillante — commencez côté peau dans une poêle froide' },
      { name: 'Sauce soja', quantity: '4', unit: 'c.s.', emoji: '🍶' },
      { name: 'Mirin', quantity: '4', unit: 'c.s.', emoji: '🍶', tip: 'Vin de riz doux — donne le brillant' },
      { name: 'Saké', quantity: '2', unit: 'c.s.', emoji: '🍶' },
      { name: 'Sucre', quantity: '1', unit: 'c.s.', emoji: '🍬' },
      { name: 'Graines de sésame', emoji: '🌰' },
      { name: 'Ciboule', emoji: '🌿' },
    ],
    anecdote: "Teri signifie 'brillant' et yaki 'grillé' en japonais. La sauce teriyaki a été popularisée aux États-Unis dès les années 1960 par les restaurants japonais de Seattle, où la communauté nikkei (Japonais-Américains) l'a adaptée avec du sucre de canne. La version américaine est plus sucrée que l'originale japonaise.",
    chef_tip: "Pour une peau ultra-croustillante : posez les cuisses côté peau dans une poêle FROIDE, puis allumez le feu moyen-fort. La graisse fond lentement et croustille parfaitement. Laquez avec la sauce en fin de cuisson — pas trop tôt ou elle brûle.",
    cultural_note: "Au Japon, le poulet teriyaki est souvent servi avec du riz blanc et de la salade de chou. La version la plus connue en dehors du Japon est le sandwich teriyaki de McDonald's Japon — lancé en 1973, il est toujours au menu et emblématique de la culture culinaire japonaise contemporaine.",
  },

  'Le Shabu-Shabu': {
    title: 'Le Shabu-Shabu',
    description: 'Fondue japonaise dans un bouillon dashi — viande wagyu et légumes de saison.',
    emoji: '🍲',
    ingredients: [
      { name: 'Bœuf wagyu ou bœuf à fondue en tranches fines', quantity: '300', unit: 'g', emoji: '🥩', tip: 'Demandez à votre boucher de le trancher à 2mm — ou mettez le bœuf au congélateur 30 min pour le couper vous-même' },
      { name: 'Bouillon dashi', quantity: '1.5', unit: 'L', emoji: '🍜' },
      { name: 'Tofu ferme', emoji: '⬜' },
      { name: 'Champignons shiitake et enoki', emoji: '🍄' },
      { name: 'Chou napa', emoji: '🥬' },
      { name: 'Ponzu (sauce soja + yuzu)', emoji: '🍊', tip: 'Sauce de trempage principale' },
      { name: 'Sauce sésame (goma dare)', emoji: '🌰', tip: 'L\'autre sauce de trempage — crémeuse et douce' },
    ],
    anecdote: "Shabu-shabu vient du son que fait la viande fine en agitant dans le bouillon chaud — 'shabu shabu' (froufrou, froufrou). Le plat est d'origine chinoise (hot-pot) mais a été japonisé dans les années 1950 à Osaka. C'est un repas convivial — tout le monde cuisine en même temps autour de la même casserole.",
    chef_tip: "Le bouillon doit frémir, pas bouillir. Chaque tranche de viande wagyu cuit en 10-15 secondes — pas plus, sinon elle devient dure. Commencez par les légumes, puis finissez par la viande. Le bouillon s'enrichit tout au long du repas.",
    cultural_note: "Au Japon, le shabu-shabu est un repas de fête que l'on partage en famille ou entre amis. Il existe des restaurants spécialisés où l'on choisit la qualité de viande (wagyu A5 pour les grandes occasions). La coutume est de ne pas parler pendant qu'on cuisine — on se concentre sur les gestes.",
  },

  'Les Ingrédients Clés': {
    title: 'Les Ingrédients Clés',
    description: 'Les piliers de la cuisine mexicaine : piments, masa, tomates et herbes.',
    emoji: '🌶️',
    ingredients: [
      { name: 'Piments séchés variés (guajillo, ancho, chipotle)', emoji: '🌶️', tip: 'Chaque variété a un profil de saveur unique — fruité, fumé, terreux' },
      { name: 'Masa harina', emoji: '🌽', tip: 'Farine de maïs nixtamalisée — base des tortillas et tamales' },
      { name: 'Tomatillos', emoji: '🍅', tip: 'Tomates vertes à enveloppe papyracée — base des salsas vertes' },
      { name: 'Épazote', emoji: '🌿', tip: 'Herbe aromatique incontournable dans les haricots noirs' },
      { name: 'Achiote (graines de rocou)', emoji: '🟠', tip: 'Colorant naturel rouge-orangé et arôme délicat' },
      { name: 'Chocolate de mesa (cacao amer)', emoji: '🍫', tip: 'Base du mole — différent du chocolat à dessert' },
    ],
    anecdote: "La cuisine mexicaine a été inscrite au patrimoine de l'UNESCO en 2010, première cuisine nationale à recevoir cette distinction. Le résultat d'une fusion entre les civilisations aztèque, maya et espagnole crée l'une des cuisines les plus complexes et riches du monde.",
    chef_tip: "Maîtrisez la réhydratation des piments séchés : faites-les griller à sec 30 secondes par face dans une poêle chaude (ils doivent ramollir et dégager un arôme), puis trempez-les 20-30 minutes dans de l'eau chaude (non bouillante). Conservez l'eau de trempage — elle ajoute saveur et couleur.",
    cultural_note: "Le Mexique est le pays d'origine du chocolat, de la vanille, du maïs, du cacao, de la tomate, du piment, de l'avocat et de la patate douce — des ingrédients qui ont révolutionné la cuisine mondiale après 1492. Sans le Mexique, pas de pizzas tomates, pas de chocolat européen.",
  },

  'Les Bases du Vegan': {
    title: 'Les Bases du Vegan',
    description: 'Remplacer les produits animaux sans compromis sur la saveur ou la nutrition.',
    emoji: '🌱',
    ingredients: [
      { name: 'Légumineuses (lentilles, pois chiches, haricots)', emoji: '🫘', tip: 'La protéine vegan la plus simple et économique' },
      { name: 'Tofu ferme', emoji: '⬜', tip: 'Pressez-le 30 min pour enlever l\'eau et obtenir une meilleure texture' },
      { name: 'Levure nutritionnelle', emoji: '🟡', tip: 'Saveur umami et fromagère — indispensable pour les sauces crémeuses' },
      { name: 'Graines (lin, chia, chanvre)', emoji: '🌻', tip: 'Graines de lin moulues + eau = substitut d\'œuf' },
      { name: 'Lait végétal non sucré', emoji: '🥛', tip: 'Soja pour cuisiner (tient à la chaleur), avoine pour le café' },
      { name: 'Noix de cajou', emoji: '🌰', tip: 'Trempées 4h et mixées = base de sauces crémeuses' },
    ],
    anecdote: "Le véganisme moderne a été codifié en 1944 par Donald Watson qui a fondé la Vegan Society en Angleterre. Mais des philosophes grecs comme Pythagore prônaient déjà le végétarisme au VIe siècle av. J.-C. Les moines bouddhistes asiatiques pratiquent une cuisine 100% végétale depuis plus de 2500 ans.",
    chef_tip: "L'umami est la clé d'une cuisine vegan savoureuse : champignons séchés, miso, sauce soja, levure nutritionnelle, tomates confites. Pour remplacer les œufs en pâtisserie : 1 c.s. de graines de lin moulues + 3 c.s. d'eau (laissez gélifier 5 min) = 1 œuf.",
    cultural_note: "La cuisine vegan la plus sophistiquée au monde vient d'Asie — cuisine bouddhiste japonaise (shojin ryori), cuisine temple coréenne, dim sum végétariens cantonais. Ces traditions millénaires prouvent qu'une cuisine d'exception peut se passer complètement de produits animaux.",
  },

  // ── GREEK PATH ────────────────────────────────────────────────────────────

  'La Spanakopita': {
    title: 'La Spanakopita',
    description: 'Tourte feuilletée aux épinards et à la feta, croustillante et savoureuse.',
    emoji: '🥬',
    ingredients: [
      { name: 'Pâte filo', emoji: '🥐', tip: 'Travaillez vite : elle sèche en 2 minutes à l\'air libre — couvrez d\'un torchon humide' },
      { name: 'Épinards frais (ou surgelés)', emoji: '🥬', tip: 'Surgelés : bien essorez après décongélation, sinon la tarte sera détrempée' },
      { name: 'Feta', emoji: '🧀', tip: 'Choisissez une feta grecque en saumure — bien plus savoureuse que les blocs sous vide' },
      { name: 'Oignons verts', emoji: '🧅', tip: 'Ils apportent une douceur que l\'oignon classique n\'a pas' },
      { name: 'Aneth frais', emoji: '🌿', tip: 'L\'herbe signature de la cuisine grecque — ne la remplacez pas' },
      { name: 'Beurre fondu ou huile d\'olive', emoji: '🫒', tip: 'Pour badigeonner chaque feuille de filo' },
    ],
    anecdote: "La spanakopita est mentionnée dans des manuscrits grecs du XIe siècle. Les moines orthodoxes l'ont codifiée lors des périodes de jeûne où la viande était interdite. Aujourd'hui, elle est servie à chaque baptême, mariage et fête de village en Grèce.",
    chef_tip: "Le secret d'une spanakopita parfaite : badigeonnez généreusement chaque feuille de filo. La couche grasse entre chaque feuille est ce qui crée les centaines de couches croustillantes à la cuisson.",
    cultural_note: "En Grèce, la spanakopita est la 'pizza' du pays — chaque région, chaque famille a sa version. Dans le nord, on l'appelle 'hortopita' et elle contient davantage d'herbes sauvages. En Crète, on utilise parfois de l'huile d'olive pure à la place du beurre.",
  },

  'La Souvlaki': {
    title: 'La Souvlaki',
    description: 'Brochettes de viande marinée grillées, servies avec pita et tzatziki.',
    emoji: '🍢',
    ingredients: [
      { name: 'Épaule d\'agneau ou porc', emoji: '🥩', tip: 'Coupez en cubes de 3cm — réguliers pour une cuisson homogène' },
      { name: 'Huile d\'olive', emoji: '🫒', tip: 'Base de toute marinade grecque' },
      { name: 'Citron', emoji: '🍋', tip: 'Jus + zeste — le citron attendrit la viande' },
      { name: 'Origan séché', emoji: '🌿', tip: 'L\'origan grec séché est bien plus parfumé que le frais' },
      { name: 'Ail', emoji: '🧄', tip: '4 gousses minimum pour 500g de viande' },
      { name: 'Pain pita', emoji: '🫓', tip: 'Réchauffez-le directement sur la grille 30 secondes par face' },
    ],
    anecdote: "La souvlaki est mentionnée par Aristophane au Ve siècle av. J.-C. — la viande grillée sur brochette est l'une des plus vieilles techniques de cuisson de l'humanité. Le mot vient du grec 'souvla' (broche) qui a la même racine que le latin 'subula'.",
    chef_tip: "Marinez minimum 4 heures, idéalement une nuit. Pour des brochettes qui ne collent pas au grill : huile le grill à froid, puis montez en température avant de déposer la viande.",
    cultural_note: "En Grèce, il existe deux versions de la souvlaki : les brochettes classiques et le 'kalamaki' (brochette fine). Les Athéniens se disputent encore pour savoir laquelle est l'originale. Les souvlaki shops ('souvlatzidika') sont ouverts jusqu'à 4h du matin — le fast-food grec par excellence.",
  },

  'Le Baklava': {
    title: 'Le Baklava',
    description: 'Pâtisserie feuilletée aux noix et au miel, imbibée de sirop parfumé.',
    emoji: '🍯',
    ingredients: [
      { name: 'Pâte filo', emoji: '🥐', tip: 'Minimum 20 feuilles pour un baklava généreux' },
      { name: 'Noix de Grenoble ou pistaches', emoji: '🫘', tip: 'Hachez grossièrement — pas en poudre fine' },
      { name: 'Beurre clarifié (ghee)', emoji: '🧈', tip: 'Le beurre clarifié supporte des températures plus hautes et ne brûle pas' },
      { name: 'Miel', emoji: '🍯', tip: 'Miel de thym grec si possible — son intensité parfume tout le sirop' },
      { name: 'Eau de rose', emoji: '🌹', tip: '1 c.s. dans le sirop suffit — trop en fait quelque chose de cosmétique' },
      { name: 'Cannelle', emoji: '🌰', tip: 'Mélangez aux noix pour les parfumer avant montage' },
    ],
    anecdote: "Le baklava est l'objet d'une vive dispute diplomatique entre la Grèce et la Turquie. Les deux pays revendiquent son invention. En réalité, il existait dans les cuisines ottomanes dès le XVe siècle et a été adopté et adapté par toutes les cultures du Moyen-Orient et des Balkans.",
    chef_tip: "Le secret du baklava parfait : versez le sirop FROID sur la pâte CHAUDE sortant du four (ou inversement). Le choc thermique permet au sirop de pénétrer uniformément sans détremper la pâte.",
    cultural_note: "Chaque pays du Moyen-Orient a sa version : le baklava turc à la pistache d'Antioche, le libanais au beurre de vache, l'iranien 'baqlava' parfumé à la cardamome et à l'eau de rose. En Grèce, le baklava aux noix et à la cannelle reste le classique.",
  },

  // ── THAI PATH ─────────────────────────────────────────────────────────────

  'Le Tom Kha Gaï': {
    title: 'Le Tom Kha Gaï',
    description: 'Soupe crémeuse à la noix de coco, galanga, citronnelle et poulet.',
    emoji: '🥥',
    ingredients: [
      { name: 'Lait de coco entier', emoji: '🥥', tip: 'Prenez du lait de coco en boîte — la crème se séparera à la cuisson, c\'est normal et souhaitable' },
      { name: 'Galanga', emoji: '🫚', tip: 'Ne remplacez pas par du gingembre — le galanga a une saveur plus poivrée et citronnée' },
      { name: 'Citronnelle', emoji: '🌿', tip: 'Écrasez les tiges avec le plat du couteau pour libérer les huiles essentielles' },
      { name: 'Feuilles de kaffir (combava)', emoji: '🍃', tip: 'Froissez-les avant d\'ajouter — elles libèrent leur parfum citronné' },
      { name: 'Champignons (shiitake ou pleurotes)', emoji: '🍄', tip: 'Ajoutez en fin de cuisson pour qu\'ils gardent leur texture' },
      { name: 'Sauce poisson (nam pla)', emoji: '🐟', tip: 'L\'assaisonnement de base de la cuisine thaïe — commence doucement' },
    ],
    anecdote: "Le 'kha' (galanga) est l'ingrédient qui donne son nom à cette soupe. Le galanga est utilisé en Thaïlande non seulement en cuisine mais aussi en médecine traditionnelle depuis des siècles pour ses propriétés anti-inflammatoires.",
    chef_tip: "Ne faites jamais bouillir le lait de coco à gros bouillons — il se décompose et perd sa douceur. Un frémissement doux est idéal. Équilibrez toujours : salé (sauce poisson), acide (citron vert), sucré (1 c.c. de sucre de palme), pimenté.",
    cultural_note: "La cuisine thaïe repose sur l'équilibre des 5 saveurs : sucré, salé, acide, amer, pimenté. Cette philosophie est bien antérieure à la cuisine moléculaire occidentale. Le Tom Kha Gaï est souvent servi en thérapeutique lors des rhumes en Thaïlande.",
  },

  'Le Green Curry': {
    title: 'Le Green Curry',
    description: 'Curry thaï vert au lait de coco, légumes croquants et herbes fraîches.',
    emoji: '🌿',
    ingredients: [
      { name: 'Pâte de curry vert', emoji: '🟢', tip: 'Faites-la revenir 2 min dans la crème de coco avant d\'ajouter le liquide — ça la "réveille"' },
      { name: 'Lait de coco', emoji: '🥥', tip: 'Utilisez la crème qui flotte en surface pour faire revenir la pâte' },
      { name: 'Aubergines thaïes (rondes, petites)', emoji: '🍆', tip: 'Coupez en quartiers juste avant de les ajouter — elles noircissent vite' },
      { name: 'Feuilles de basilic thaï', emoji: '🌿', tip: 'Ajoutez hors du feu en toute fin — la chaleur tue leur parfum' },
      { name: 'Piments verts frais', emoji: '🌶️', tip: 'Grattez les graines pour moins de piquant' },
      { name: 'Sucre de palme', emoji: '🟤', tip: 'Arrondit les saveurs — remplaçable par cassonade en dépannage' },
    ],
    anecdote: "La couleur verte du curry vient des piments verts frais, de la citronnelle et des feuilles de kaffir utilisés dans la pâte. Contrairement aux idées reçues, le curry vert n'est pas forcément plus pimenté que le rouge — cela dépend de la quantité de pâte utilisée.",
    chef_tip: "La pâte de curry doit 'frire' dans la crème de coco jusqu'à ce qu'elle dégage une odeur intense et que l'huile se sépare — c'est le signe que les épices sont bien torréfiées. Comptez 3-4 minutes à feu moyen.",
    cultural_note: "Il existe 4 grandes familles de curry thaï : vert (piments verts, herbacé), rouge (piments rouges séchés, plus doux), jaune (curcuma, influence indienne), Massaman (influences moyen-orientales, épices douces). Chaque région de Thaïlande a ses variantes.",
  },

  // ── MOROCCAN PATH ─────────────────────────────────────────────────────────

  'La Harira': {
    title: 'La Harira',
    description: 'Soupe épaisse aux tomates, lentilles, pois chiches et épices — le repas du Ramadan.',
    emoji: '🍲',
    ingredients: [
      { name: 'Tomates concassées', emoji: '🍅', tip: '500g de tomates fraîches ou 1 boîte 400g — les fraîches donnent plus de fraîcheur' },
      { name: 'Lentilles corail', emoji: '🔴', tip: 'Elles cuisent vite et épaississent la soupe naturellement' },
      { name: 'Pois chiches cuits', emoji: '🫘', tip: 'En boîte c\'est parfait — ajoutez en fin de cuisson pour les garder fermes' },
      { name: 'Céleri avec ses feuilles', emoji: '🥬', tip: 'Les feuilles sont essentielles — ne les jetez pas' },
      { name: 'Coriandre et persil frais', emoji: '🌿', tip: 'Quantités généreuses — elles définissent le parfum de la harira' },
      { name: 'Tadouira (farine + eau)', emoji: '🌾', tip: 'Mélange épaississant final : 2 c.s. farine + 100ml eau — versez en filet en remuant' },
    ],
    anecdote: "La harira est le plat qui rompt le jeûne du Ramadan au Maroc. Chaque soir du mois sacré, toutes les familles marocaines préparent cette soupe. On dit que si vous êtes perdu dans une médina marocaine au crépuscule du Ramadan, laissez-vous guider par l'odeur de la harira.",
    chef_tip: "La 'tadouira' (farine délayée) est le secret de texture de la harira — elle est ajoutée en fin de cuisson et transforme une soupe légère en un plat consistant. Remuez constamment après l'ajout pour éviter les grumeaux.",
    cultural_note: "La harira est mentionnée dans 'Les Mille et Une Nuits'. Elle était servie aux voyageurs dans les caravansérails comme repas de réconfort. Aujourd'hui, elle est indissociable du Ramadan : les mosquées du Maroc distribuent gratuitement de la harira aux personnes dans le besoin à l'heure de l'iftar.",
  },

  // ── INDIAN PATH ───────────────────────────────────────────────────────────

  'Le Biryani': {
    title: 'Le Biryani',
    description: 'Riz basmati parfumé aux épices, cuit en dum avec poulet ou agneau.',
    emoji: '🍚',
    ingredients: [
      { name: 'Riz basmati long grain', emoji: '🌾', tip: 'Rincez 5-6 fois jusqu\'à eau claire, puis faites tremper 30 min' },
      { name: 'Poulet ou agneau', emoji: '🍗', tip: 'Marinade yaourt + épices minimum 4 heures' },
      { name: 'Safran', emoji: '🌼', tip: 'Infusez dans 50ml de lait chaud — versez sur le riz à mi-cuisson pour le dégradé de couleurs' },
      { name: 'Oignons frits (barista)', emoji: '🧅', tip: 'Frire les oignons en lamelles jusqu\'à brun-doré et croustillant — c\'est laborieux mais irremplaçable' },
      { name: 'Ghee', emoji: '🧈', tip: 'Arrosez généreusement le riz avant la cuisson en dum' },
      { name: 'Épices entières (cardamome, clous de girofle, cannelle)', emoji: '🌶️', tip: 'Frites entières dans le ghee en début de cuisson pour les "bloom"' },
    ],
    anecdote: "Le biryani est arrivé en Inde avec les empereurs moghols au XVIe siècle. La cuisine moghole — fusion perso-arabe-indienne — est à l'origine de nombreux plats des restaurants indiens que nous connaissons. La cuisson en 'dum' (à l'étouffée avec la marmite scellée) est une technique perse.",
    chef_tip: "La cuisson en 'dum' : scellez la marmite avec de la pâte de farine (ou du papier alu épais) pour créer une chambre de vapeur. Cette vapeur parfumée pénètre le riz uniformément. Cuisson finale à feu très doux 20-25 minutes.",
    cultural_note: "Il existe des centaines de biryani régionaux en Inde : Hyderabad (le plus célèbre, avec viande en cuisson dum), Lucknow (dum pukht, viande précuite), Kolkata (influence de nawabs), Kerala (biryani au riz matta rouge). Pakistan, Bangladesh et Sri Lanka ont leurs propres versions.",
  },

  'Le Dosa': {
    title: 'Le Dosa',
    description: 'Crêpe croustillante de riz fermenté, accompagnée de chutney et sambar.',
    emoji: '🫓',
    ingredients: [
      { name: 'Riz à grain long', emoji: '🌾', tip: 'Trempez 6-8 heures — la fermentation est la clé de la texture' },
      { name: 'Lentilles noires (urad dal)', emoji: '🫘', tip: 'Ratio 3:1 (riz:lentilles) est le classique du sud de l\'Inde' },
      { name: 'Graines de fenugrec', emoji: '🌿', tip: '1/2 c.c. accélère la fermentation et donne une légère amertume' },
      { name: 'Huile de sésame', emoji: '🫚', tip: 'Pour graisser la poêle en fonte — essentiel pour le croustillant' },
      { name: 'Ghee', emoji: '🧈', tip: 'Badigeonnez le dosa pendant la cuisson pour la couleur dorée' },
    ],
    anecdote: "Le dosa est originaire du Tamil Nadu et du Karnataka, datant d'au moins le Ier siècle ap. J.-C. selon des textes tamouls. La fermentation naturelle du mélange riz-lentilles produit de l'acide lactique qui est la source de la saveur légèrement acidulée signature.",
    chef_tip: "Le secret d'un dosa croustillant : une poêle en fonte très chaude et quelques gouttes d'eau qui doivent s'évaporer instantanément quand vous les aspergez. Versez la pâte et étalez-la en spirale du centre vers l'extérieur en un seul geste rapide.",
    cultural_note: "Au Tamil Nadu, les 'tiffin centers' (restaurants de petit-déjeuner) ouvrent à 6h du matin et servent dosas, idlis et vadas. La culture du petit-déjeuner sud-indien est l'une des plus riches au monde. Le dosa masala (farci de pommes de terre épicées) est aujourd'hui servi dans le monde entier.",
  },

  // ── CHINESE PATH ──────────────────────────────────────────────────────────

  'Le Kung Pao Poulet': {
    title: 'Le Kung Pao Poulet',
    description: 'Poulet sauté au wok avec cacahuètes, piments et poivre du Sichuan.',
    emoji: '🥜',
    ingredients: [
      { name: 'Blanc de poulet', emoji: '🍗', tip: 'Coupez en cubes de 1,5 cm — réguliers pour une cuisson uniforme au wok' },
      { name: 'Cacahuètes grillées non salées', emoji: '🥜', tip: 'Ajoutez en toute fin de cuisson pour préserver le croustillant' },
      { name: 'Piments séchés du Sichuan', emoji: '🌶️', tip: 'Faites-les revenir entiers jusqu\'à assombrissement pour libérer leur parfum' },
      { name: 'Poivre du Sichuan', emoji: '🔴', tip: 'Légèrement torréfié et moulu — provoque la sensation de picotement-engourdissement unique' },
      { name: 'Sauce soja', emoji: '🫙', tip: 'Sauce soja claire (pas foncée) pour le wok — moins salée, plus parfumée' },
      { name: 'Vinaigre de riz', emoji: '🍶', tip: 'Balance le piment — ne l\'omettez pas' },
    ],
    anecdote: "Le Kung Pao (宫保) tire son nom de Ding Baozhen, gouverneur du Sichuan à la fin du XIXe siècle dont le titre officiel était 'Kung Pao' (Gardien du Palais). Ce plat était sa recette préférée. Pendant la Révolution Culturelle, le plat a été rebaptisé 'poulet aux piments et cacahuètes' — le nom 'Kung Pao' étant jugé trop aristocratique.",
    chef_tip: "La clé du wok parfait : 'wok hei' (la saveur du wok). Votre wok doit être à température maximale avant d'ajouter l'huile, et l'huile doit fumer légèrement avant le poulet. Ne surchargez jamais le wok — cuisinez en petites quantités si nécessaire.",
    cultural_note: "Le poivre du Sichuan (花椒) n'est pas un vrai poivre mais la baie d'un arbuste de la famille des citrus. La sensation d'engourdissement-picotement qu'il provoque s'appelle 'ma la' (麻辣) — engourdi-pimenté. La combinaison ma (poivre Sichuan) et la (piment) est la signature de la cuisine du Sichuan.",
  },

  'Les Raviolis Chinois (Jiaozi)': {
    title: 'Les Raviolis Chinois (Jiaozi)',
    description: 'Raviolis maison farcis au porc et ciboulette, poêlés ou bouillis.',
    emoji: '🥟',
    ingredients: [
      { name: 'Farine blanche', emoji: '🌾', tip: 'Eau bouillante pour une pâte plus tendre (cuisson à l\'eau) ou eau froide pour plus de mâche (poêle)' },
      { name: 'Porc haché (20% de matière grasse)', emoji: '🥩', tip: 'La matière grasse est essentielle — du porc trop maigre donnerait une farce sèche' },
      { name: 'Ciboulette chinoise (ou poireau vert)', emoji: '🌿', tip: 'La ciboulette chinoise est plus parfumée que la française — cherchez-la en épicerie asiatique' },
      { name: 'Gingembre frais râpé', emoji: '🫚', tip: 'Indispensable pour contrebalancer la graisse du porc' },
      { name: 'Sauce soja', emoji: '🫙', tip: 'Pour la farce et la sauce trempette' },
      { name: 'Huile de sésame', emoji: '🫚', tip: 'Quelques gouttes dans la farce et la sauce' },
    ],
    anecdote: "Le jiaozi a une histoire de 1800 ans. Selon la légende, le médecin Zhang Zhongjing les a inventés pour soigner les oreilles gelées de ses patients pendant l'hiver — la forme en demi-lune imitait une oreille. C'est pourquoi en Chine du Nord, on mange des jiaozi à minuit pendant le Nouvel An.",
    chef_tip: "Pour les potstickers (guotie) parfaits : déposez dans une poêle avec un peu d'huile, faites dorer le fond 2 min, versez 100ml d'eau et couvrez immédiatement. Cuisez à vapeur 6 min jusqu'à évaporation totale de l'eau. Retirez le couvercle et laissez recrisoer encore 1-2 min.",
    cultural_note: "En Chine, plier les jiaozi en famille la veille du Nouvel An est un rituel incontournable. Certaines familles cachent une pièce de monnaie dans l'un d'eux — celui qui le trouve aura de la chance toute l'année. Les jiaozi ont donné naissance aux gyoza japonais et aux mandu coréens.",
  },
};
