import type { LessonDetail, PathDetail } from '@/types/database.types';

// ---------------------------------------------------------------------------
// PATH DETAILS (enriched metadata per path)
// ---------------------------------------------------------------------------
export const PATH_DETAILS: Record<string, Omit<PathDetail, 'id' | 'order_index' | 'is_active'>> = {
  french: {
    slug: 'french',
    title: 'Cuisine Française',
    description: 'Maîtrise les classiques de la gastronomie française',
    emoji: '🇫🇷',
    color: '#0055A4',
    country: 'France',
    history: "La cuisine française est reconnue patrimoine culturel immatériel de l'UNESCO depuis 2010. Elle a été codifiée au XIXe siècle par Auguste Escoffier, qui a révolutionné la restauration moderne. La brigade de cuisine, le menu dégustation, les sauces mères — tout vient de cette tradition.",
    key_ingredients: ["Beurre AOP", "Crème fraîche", "Herbes de Provence", "Vin blanc sec", "Moutarde de Dijon", "Échalotes"],
    famous_chefs: ["Auguste Escoffier", "Paul Bocuse", "Joël Robuchon", "Alain Ducasse"],
  },
  italian: {
    slug: 'italian',
    title: 'Cuisine Italienne',
    description: 'Pasta, pizza e molto altro!',
    emoji: '🇮🇹',
    color: '#CE2B37',
    country: 'Italie',
    history: "La cuisine italienne est l'une des plus influentes au monde. Née de 20 régions aux identités culinaires distinctes, elle repose sur la qualité des ingrédients plutôt que sur la complexité des techniques. La pasta existe depuis le XIIIe siècle, bien avant que Marco Polo ne revienne de Chine.",
    key_ingredients: ["Tomates San Marzano", "Huile d'olive extra vierge", "Parmigiano Reggiano", "Basilic frais", "Farine 00", "Mozzarella di bufala"],
    famous_chefs: ["Massimo Bottura", "Carlo Cracco", "Gennaro Contaldo", "Antonio Carluccio"],
  },
  japanese: {
    slug: 'japanese',
    title: 'Cuisine Japonaise',
    description: "Sushi, ramen, et l'art du dashi",
    emoji: '🇯🇵',
    color: '#BC002D',
    country: 'Japon',
    history: "La cuisine japonaise (washoku) est patrimoine de l'UNESCO depuis 2013. Elle repose sur 5 principes fondamentaux : 5 couleurs, 5 saveurs (dont l'umami, découvert en 1908 par le chimiste Kikunae Ikeda), 5 méthodes de cuisson. Le couteau japonais (hocho) est forgé comme une lame de samouraï.",
    key_ingredients: ["Dashi (kombu + bonite)", "Mirin", "Sauce soja", "Miso blanc", "Riz japonais à grain court", "Wasabi frais"],
    famous_chefs: ["Jiro Ono", "Nobu Matsuhisa", "Yoshihiro Murata", "Tetsuya Wakuda"],
  },
  moroccan: {
    slug: 'moroccan',
    title: 'Cuisine Marocaine',
    description: 'Tajine, couscous et ras-el-hanout',
    emoji: '🇲🇦',
    color: '#C1272D',
    country: 'Maroc',
    history: "La cuisine marocaine est le fruit de 3000 ans de civilisations : berbère, arabe, andalouse et juive. Le couscous — déclaré patrimoine de l'UNESCO en 2020 — se roule à la main depuis des millénaires. Le ras-el-hanout (\"tête de l'épicier\") peut contenir jusqu'à 50 épices différentes.",
    key_ingredients: ["Ras-el-hanout", "Safran de Taliouine", "Argan", "Charmoula", "Citrons confits", "Fleur d'oranger"],
    famous_chefs: ["Moha Fedal", "Fatéma Hal", "Najat Kaanache"],
  },
  mexican: {
    slug: 'mexican',
    title: 'Cuisine Mexicaine',
    description: 'Tacos, guacamole et mole',
    emoji: '🇲🇽',
    color: '#006847',
    country: 'Mexique',
    history: "La cuisine mexicaine est patrimoine de l'UNESCO depuis 2010. Le mole negro d'Oaxaca contient jusqu'à 36 ingrédients et peut prendre 3 jours à préparer. Le chocolat, la vanille, les tomates, les piments, l'avocat — tous originaires du Mexique, offerts au monde entier.",
    key_ingredients: ["Piments ancho/chipotle/poblano", "Tomatilles", "Épazote", "Masa harina", "Achiote", "Crema mexicana"],
    famous_chefs: ["Enrique Olvera", "Elena Reygadas", "Ricardo Muñoz Zurita"],
  },
  indian: {
    slug: 'indian',
    title: 'Cuisine Indienne',
    description: 'Curry, masala et pains naan',
    emoji: '🇮🇳',
    color: '#FF9933',
    country: 'Inde',
    history: "La cuisine indienne est l'une des plus anciennes du monde — 5000 ans d'histoire. Elle suit les principes de l'Ayurveda, médecine traditionnelle qui classe les aliments selon leurs effets sur l'énergie du corps. Le curry n'est pas une épice mais un concept anglais : en Inde, chaque plat a sa propre masala.",
    key_ingredients: ["Garam masala", "Ghee", "Cumin noir (kalonji)", "Fenugrec", "Tamarin", "Cardamome verte"],
    famous_chefs: ["Vikas Khanna", "Sanjeev Kapoor", "Manish Mehrotra", "Gaggan Anand"],
  },
  thai: {
    slug: 'thai',
    title: 'Cuisine Thaïlandaise',
    description: 'Pad thaï, laak et soupes de coco',
    emoji: '🇹🇭',
    color: '#A51931',
    country: 'Thaïlande',
    history: "La cuisine thaïlandaise cherche l'équilibre parfait entre 4 saveurs : sucré, salé, acide et pimenté. Autrefois réservée à la cour royale, la cuisine thaïe élaborée est classée patrimoine culturel national. La citronnelle, le galanga et les feuilles de kaffir sont des ingrédients que beaucoup confondent avec leurs cousins européens.",
    key_ingredients: ["Citronnelle", "Galanga", "Feuilles de kaffir", "Pâte de crevettes (kapi)", "Nam pla (sauce poisson)", "Basilic thaï"],
    famous_chefs: ["Bo Songvisava", "Dylan Jones", "Duangporn Songvisava"],
  },
  greek: {
    slug: 'greek',
    title: 'Cuisine Grecque',
    description: 'Mezze, moussaka et tzatziki',
    emoji: '🇬🇷',
    color: '#0D5EAF',
    country: 'Grèce',
    history: "La cuisine grecque est l'ancêtre de la cuisine méditerranéenne. Hippocrate, père de la médecine, considérait que 'que ta nourriture soit ta médecine'. L'huile d'olive grecque est produite depuis 5000 ans. La moussaka telle qu'on la connaît a été standardisée en 1920 par le chef Nikolaos Tselementes.",
    key_ingredients: ["Huile d'olive Kalamata", "Feta AOP", "Origan frais", "Citron de Grèce", "Miel de thym", "Cédrat confit"],
    famous_chefs: ["Yiannis Lucacos", "Nikos Karathanos", "Lefteris Lazarou"],
  },
  chinese: {
    slug: 'chinese',
    title: 'Cuisine Chinoise',
    description: 'Wok, dim sum et sauces authentiques',
    emoji: '🇨🇳',
    color: '#DE2910',
    country: 'Chine',
    history: "La cuisine chinoise est la plus diverse au monde, avec 8 grandes cuisines régionales (Cantonaise, Sichuanaise, Shanghaiaise...). Le wok a 2000 ans d'histoire. L'umami, découvert officiellement au Japon, était utilisé en Chine depuis des siècles via la sauce soja et les champignons shiitake séchés.",
    key_ingredients: ["Huile de sésame", "Sauce hoisin", "Vinaigre de Chinkiang", "Pâte de piment doubanjiang", "Vin de Shaoxing", "Cinq-épices"],
    famous_chefs: ["Ken Hom", "Martin Yan", "Fuchsia Dunlop"],
  },
  pastry: {
    slug: 'pastry',
    title: 'Pâtisserie',
    description: 'Gâteaux, éclairs et macarons',
    emoji: '🎂',
    color: '#F4A6C0',
    country: 'France / Monde',
    history: "La pâtisserie française s'est développée à Versailles pour impressionner les cours européennes. Le macaron parisien actuel a été créé en 1930 par Pierre Desfontaines (Ladurée). L'éclair au chocolat date du XIXe siècle. La pâte feuilletée, selon la légende, aurait été inventée par le peintre Claude Lorrain avant de devenir chef pâtissier.",
    key_ingredients: ["Beurre de tourage 84%", "Farine T45", "Praliné noisette", "Chocolat Valrhona", "Glucose liquide", "Gélatine en feuilles"],
    famous_chefs: ["Pierre Hermé", "Cédric Grolet", "Christophe Michalak", "Gaston Lenôtre"],
  },
  bbq: {
    slug: 'bbq',
    title: 'Barbecue & Grillades',
    description: 'Marinades, fumage et cuissons directes',
    emoji: '🔥',
    color: '#8B0000',
    country: 'États-Unis / Monde',
    history: "Le BBQ américain puise ses racines dans les traditions culinaires des esclaves afro-américains du Sud, qui transformaient des morceaux de viande bas de gamme en plats légendaires via le fumage lent. Chaque région a son style : Kansas City (sauce tomate), Caroline du Nord (vinaigre), Texas (boeuf nature), Memphis (sec).",
    key_ingredients: ["Bois de hickory / mesquite / cerisier", "Paprika fumé", "Sel rose de curing", "Moutarde américaine", "Vinaigre de cidre", "Brown sugar"],
    famous_chefs: ["Aaron Franklin", "Rodney Scott", "Myron Mixon"],
  },
  vegan: {
    slug: 'vegan',
    title: 'Cuisine Vegan',
    description: '100% végétal, 100% savoureux',
    emoji: '🌿',
    color: '#2E7D32',
    country: 'Monde',
    history: "Le végétalisme existe depuis l'Antiquité dans les traditions bouddhistes et jaïnes. Le terme 'vegan' a été créé en 1944 par Donald Watson à Leicester. La cuisine vegan moderne s'appuie sur des techniques innovantes : fermentation, texturisation du gluten, émulsification à l'aquafaba (eau de pois chiche).",
    key_ingredients: ["Aquafaba (eau de pois chiche)", "Levure nutritionnelle", "Tamari (soja sans gluten)", "Cashews trempés", "Agar-agar", "Protéines de pois"],
    famous_chefs: ["Alexis Gauthier", "Matthew Kenney", "Tal Ronnen"],
  },
};

// ---------------------------------------------------------------------------
// LESSON DETAILS (ingredients + anecdotes + tips per lesson)
// ---------------------------------------------------------------------------
export const LESSON_DETAILS: Record<string, Omit<LessonDetail, 'id' | 'path_id' | 'order_index' | 'xp_reward' | 'thumbnail_url'>> = {

  // ── FRENCH ──────────────────────────────────────────────────────────────
  'Les Sauces de Base': {
    title: 'Les Sauces de Base',
    description: 'Béchamel, velouté, hollandaise…',
    duration_minutes: 35,
    difficulty: 'medium',
    ingredients: [
      { name: 'Beurre', quantity: '50', unit: 'g', emoji: '🧈', tip: 'Beurre à 82% min de matière grasse' },
      { name: 'Farine', quantity: '50', unit: 'g', emoji: '🌾' },
      { name: 'Lait entier', quantity: '500', unit: 'ml', emoji: '🥛', tip: 'Chaud pour éviter les grumeaux' },
      { name: 'Noix de muscade', quantity: '1 pincée', emoji: '🌰' },
      { name: 'Sel & poivre blanc', quantity: 'QS', emoji: '🧂' },
    ],
    anecdote: "Les 5 sauces mères françaises (béchamel, velouté, espagnole, hollandaise, tomat) ont été codifiées par Auguste Escoffier vers 1900. Avant lui, Marie-Antoine Carême en avait défini 4. Ces sauces sont la colonne vertébrale de toute la cuisine française classique.",
    chef_tip: "Pour une béchamel sans grumeaux : incorporez le lait chaud en 3 fois en fouettant vigoureusement. Le roux doit refroidir légèrement avant d'ajouter le lait.",
    cultural_note: "La béchamel porte le nom du marquis Louis de Béchameil, financier et courtisan de Louis XIV. Mais c'est probablement un cuisinier anonyme qui l'a inventée — Béchameil n'a fait qu'y apposer son nom.",
  },
  'La Quiche Lorraine': {
    title: 'La Quiche Lorraine',
    description: 'Tarte salée aux lardons et fromage',
    duration_minutes: 50,
    difficulty: 'easy',
    ingredients: [
      { name: 'Pâte brisée', quantity: '250', unit: 'g', emoji: '🫓' },
      { name: 'Lardons fumés', quantity: '200', unit: 'g', emoji: '🥓', tip: 'Blanchir 2 min pour retirer l\'excès de sel' },
      { name: 'Œufs entiers', quantity: '3', emoji: '🥚' },
      { name: 'Crème fraîche épaisse', quantity: '200', unit: 'ml', emoji: '🥛', tip: '30% MG minimum' },
      { name: 'Gruyère râpé', quantity: '100', unit: 'g', emoji: '🧀', tip: 'Optionnel — non traditionnel !' },
      { name: 'Noix de muscade', quantity: '1 pincée', emoji: '🌰' },
    ],
    anecdote: "La vraie quiche lorraine traditionnelle ne contient PAS de fromage ! Seulement des lardons, des œufs et de la crème. Le fromage est une addition moderne. 'Quiche' vient du mot allemand 'Kuchen' (gâteau) — la Lorraine ayant été longtemps sous influence germanique.",
    chef_tip: "Piquez le fond de tarte à la fourchette et cuisez-le 10 min à blanc. La migaine (mélange œufs-crème) doit être à température ambiante avant d'être versée sur les lardons.",
    cultural_note: "La quiche lorraine est née à Nancy et Metz, villes de la région Lorraine. Sa popularité mondiale date de l'après-guerre, quand des soldats américains l'ont découverte et ramenée chez eux.",
  },
  'Le Bœuf Bourguignon': {
    title: 'Le Bœuf Bourguignon',
    description: 'Mijotage et braising à la française',
    duration_minutes: 180,
    difficulty: 'medium',
    ingredients: [
      { name: 'Bœuf paleron ou joue', quantity: '1.2', unit: 'kg', emoji: '🥩', tip: 'Couper en cubes de 5 cm, pas plus petit' },
      { name: 'Pinot Noir de Bourgogne', quantity: '750', unit: 'ml', emoji: '🍷', tip: 'Boire ce qu\'on cuisine !' },
      { name: 'Lardons', quantity: '150', unit: 'g', emoji: '🥓' },
      { name: 'Champignons de Paris', quantity: '300', unit: 'g', emoji: '🍄' },
      { name: 'Oignons grelots', quantity: '200', unit: 'g', emoji: '🧅' },
      { name: 'Bouquet garni', quantity: '1', emoji: '🌿' },
      { name: 'Carottes', quantity: '2', emoji: '🥕' },
      { name: 'Farine', quantity: '2 cs', emoji: '🌾', tip: 'Pour le singer (fariner la viande)' },
    ],
    anecdote: "Julia Child a popularisé le bœuf bourguignon aux États-Unis dans les années 60 via son émission de télévision et son livre 'Mastering the Art of French Cooking'. Elle disait que c'était son plat préféré. La recette date en réalité du Moyen Âge, quand on utilisait le vin pour attendrir des viandes coriaces.",
    chef_tip: "Saisissez la viande EN PETITES QUANTITÉS — si vous en mettez trop, elle bout au lieu de dorer. La couleur brune (réaction de Maillard) apporte 80% du goût final.",
    cultural_note: "La Bourgogne est la région viticole la plus prestigieuse de France. Le vin qu'on y cuisine est le même qu'on y boit : le Pinot Noir. Un vrai Bourguignon ne transige pas sur ce point.",
  },
  'Les Crêpes': {
    title: 'Les Crêpes',
    description: 'Fine crêpe dorée sucrée ou salée',
    duration_minutes: 30,
    difficulty: 'easy',
    ingredients: [
      { name: 'Farine T45', quantity: '250', unit: 'g', emoji: '🌾' },
      { name: 'Œufs', quantity: '3', emoji: '🥚' },
      { name: 'Lait', quantity: '500', unit: 'ml', emoji: '🥛' },
      { name: 'Beurre fondu', quantity: '50', unit: 'g', emoji: '🧈' },
      { name: 'Sucre', quantity: '30', unit: 'g', emoji: '🍬', tip: 'Uniquement pour version sucrée' },
      { name: 'Rhum', quantity: '1 cs', emoji: '🍶', tip: 'Optionnel — arôme classique' },
    ],
    anecdote: "La chandeleur (2 février) est la fête des crêpes en France. La tradition veut qu'on tienne une pièce d'or dans la main gauche en faisant sauter la première crêpe de la main droite — pour s'assurer la prospérité. Les Bretons sont fiers de leurs galettes de sarrasin (crêpes salées), qui existent depuis le XIIIe siècle.",
    chef_tip: "Laissez reposer la pâte 1 heure minimum. Cela permet aux protéines du gluten de se détendre — vos crêpes seront plus souples et moins élastiques.",
    cultural_note: "La crêpe Suzette a été inventée par accident en 1895 à Monte-Carlo par le jeune Auguste Escoffier, alors qu'il travaillait pour le Prince de Galles (futur Édouard VII). Le flambage au Grand Marnier était une erreur devenue un classique.",
  },

  // ── JAPANESE ────────────────────────────────────────────────────────────
  'Le Dashi': {
    title: 'Le Dashi',
    description: 'Le bouillon fondateur de la cuisine japonaise',
    duration_minutes: 20,
    difficulty: 'easy',
    ingredients: [
      { name: 'Kombu séché', quantity: '10', unit: 'g', emoji: '🌿', tip: 'Ne pas laver — la poudre blanche est savoureuse !' },
      { name: 'Katsuobushi (bonite séchée)', quantity: '20', unit: 'g', emoji: '🐟' },
      { name: 'Eau froide', quantity: '1', unit: 'L', emoji: '💧', tip: 'Eau de source si possible' },
    ],
    anecdote: "Le dashi est l'épine dorsale de 90% de la cuisine japonaise. Il a permis au chercheur Kikunae Ikeda de découvrir en 1908 la cinquième saveur : l'umami. L'acide glutamique du kombu et l'inosinate de la bonite créent ensemble une synergie umami extraordinaire.",
    chef_tip: "Ne jamais faire bouillir le kombu — chauffez l'eau à 60°C et laissez infuser 30 min. La bonite se verse en une seule fois quand l'eau frémit, puis on coupe le feu immédiatement.",
    cultural_note: "Il existe deux types de dashi : le ichiban dashi (première infusion, délicat) et le niban dashi (deuxième infusion, plus corsé pour les sauces). Les chefs étoilés japonais consacrent parfois une heure entière à préparer leur dashi du matin.",
  },
  'Les Sushis': {
    title: 'Les Sushis',
    description: 'Riz vinaigré, nori et garnitures',
    duration_minutes: 60,
    difficulty: 'hard',
    ingredients: [
      { name: 'Riz japonais Koshihikari', quantity: '300', unit: 'g', emoji: '🍚', tip: 'Rincer 5x jusqu\'à eau claire' },
      { name: 'Vinaigre de riz', quantity: '60', unit: 'ml', emoji: '🫙' },
      { name: 'Sucre', quantity: '20', unit: 'g', emoji: '🍬' },
      { name: 'Sel fin', quantity: '10', unit: 'g', emoji: '🧂' },
      { name: 'Saumon sashimi grade', quantity: '200', unit: 'g', emoji: '🐟', tip: 'Certifié sashimi-grade = congelé -20°C/7j' },
      { name: 'Nori premium', quantity: '5 feuilles', emoji: '🌿' },
      { name: 'Wasabi frais', quantity: 'QS', emoji: '🌿' },
    ],
    anecdote: "Le sushi tel qu'on le connaît (nigiri) a été inventé vers 1820 à Tokyo (alors Edo) par Hanaya Yohei. C'était un fast-food de rue ! Le sushi fermenté originel (narezushi) existe depuis 1300 ans et prend des mois à préparer. Le saumon en sushi ? Une invention norvégienne des années 1980 pour exporter leur saumon d'élevage au Japon.",
    chef_tip: "Préparez le riz à sushi ('shari') en l'assaisonnant avec un éventail pour le refroidir rapidement sans le rendre collant. La texture idéale : chaque grain doit être individuel mais légèrement collant.",
    cultural_note: "Jiro Ono, 97 ans, tient un restaurant 3 étoiles Michelin de 10 places à Tokyo où les réservations sont impossibles à obtenir. Il dit se lever à 5h chaque matin depuis 75 ans. Son dojo : 'Une fois que tu décides ton métier, plonge-y totalement.'",
  },

  // ── MOROCCAN ────────────────────────────────────────────────────────────
  'Le Tajine d\'Agneau': {
    title: "Le Tajine d'Agneau",
    description: 'Viande fondante aux pruneaux et amandes',
    duration_minutes: 120,
    difficulty: 'medium',
    ingredients: [
      { name: 'Épaule d\'agneau', quantity: '1.2', unit: 'kg', emoji: '🍖', tip: 'Demander au boucher de couper en morceaux de 4 cm' },
      { name: 'Pruneaux d\'Agen', quantity: '200', unit: 'g', emoji: '🫐', tip: 'Tremper 30 min dans du thé à la menthe' },
      { name: 'Amandes mondées', quantity: '100', unit: 'g', emoji: '🌰' },
      { name: 'Oignons', quantity: '3', emoji: '🧅' },
      { name: 'Safran de Taliouine', quantity: '1 pincée', emoji: '🌸', tip: 'Infuser dans 2 cs d\'eau chaude avant usage' },
      { name: 'Ras-el-hanout', quantity: '2 cs', emoji: '🫙' },
      { name: 'Gingembre en poudre', quantity: '1 cs', emoji: '🫚' },
      { name: 'Miel', quantity: '2 cs', emoji: '🍯' },
      { name: 'Huile d\'argan', quantity: '3 cs', emoji: '🫗' },
    ],
    anecdote: "Le tajine tire son nom du plat conique en terre cuite dans lequel il cuit. La vapeur monte, se condense sur le couvercle et retombe sur la viande — une distillation naturelle qui concentre les arômes. On dit que chaque famille marocaine a sa propre recette de tajine, jalousement gardée.",
    chef_tip: "Cuisez à feu très doux (150°C au four ou flamme minimale). La fonte lente à basse température est le secret de la tendreté. Ne jamais ouvrir le couvercle pendant la cuisson.",
    cultural_note: "La ville de Fès est considérée comme la capitale gastronomique du Maroc. Les femmes y sont gardiennes des recettes ancestrales, transmises oralement de mère en fille. Certaines recettes de tajine remontent à la cour de l'empire almohade du XIIIe siècle.",
  },

  // ── ITALIAN ─────────────────────────────────────────────────────────────
  'Les Pâtes Fraîches': {
    title: 'Les Pâtes Fraîches',
    description: 'Tagliatelle, fettuccine maison',
    duration_minutes: 45,
    difficulty: 'medium',
    ingredients: [
      { name: 'Farine 00 (grano tenero)', quantity: '300', unit: 'g', emoji: '🌾', tip: 'La farine 00 donne une texture soyeuse' },
      { name: 'Semoule de blé dur', quantity: '100', unit: 'g', emoji: '🌾', tip: 'Pour la texture al dente' },
      { name: 'Œufs entiers (gros)', quantity: '3', emoji: '🥚' },
      { name: 'Jaunes d\'œufs', quantity: '2', emoji: '🥚', tip: 'Plus de jaunes = pâte plus riche et jaune' },
      { name: 'Huile d\'olive', quantity: '1 cs', emoji: '🫒' },
      { name: 'Sel fin', quantity: '1 pincée', emoji: '🧂' },
    ],
    anecdote: "La légende dit que les tagliatelle ont été créées en 1487 à Bologne par un cuisinier nommé Zefirano pour le mariage de Lucrèce Borgia — inspiré par ses cheveux blonds. L'Academia della Cucina Italiana a même déposé une portion de tagliatelle en or à la chambre de commerce de Bologne pour certifier la largeur exacte : 8mm cuit (1/12270ème de la largeur de la Tour des Asinelli).",
    chef_tip: "Pétrir 10 minutes vigoureusement jusqu'à obtenir une pâte lisse comme de la soie. La reposer 30 min filmée à température ambiante est INDISPENSABLE pour détendre le gluten.",
    cultural_note: "Chaque région d'Italie a ses propres pâtes. Bologne : tagliatelle et tortellini. Rome : rigatoni et tonnarelli. Naples : spaghetti et paccheri. Sardaigne : malloreddus. La forme de la pâte n'est pas aléatoire — elle est pensée pour retenir une sauce spécifique.",
  },
  'Le Risotto': {
    title: 'Le Risotto',
    description: 'Al dente avec mantecatura',
    duration_minutes: 30,
    difficulty: 'hard',
    ingredients: [
      { name: 'Riz Carnaroli (ou Arborio)', quantity: '320', unit: 'g', emoji: '🍚', tip: 'Carnaroli tient mieux la cuisson qu\'Arborio' },
      { name: 'Bouillon chaud (légumes ou volaille)', quantity: '1.2', unit: 'L', emoji: '🫕', tip: 'Doit être CHAUD — ajout de froid casse la cuisson' },
      { name: 'Vin blanc sec', quantity: '150', unit: 'ml', emoji: '🍾' },
      { name: 'Échalotes', quantity: '2', emoji: '🧅' },
      { name: 'Beurre froid', quantity: '60', unit: 'g', emoji: '🧈', tip: 'TRÈS froid pour la mantecatura finale' },
      { name: 'Parmigiano Reggiano 36 mois', quantity: '80', unit: 'g', emoji: '🧀' },
      { name: 'Huile d\'olive', quantity: '3 cs', emoji: '🫒' },
    ],
    anecdote: "La mantecatura est l'étape finale magique du risotto : on ajoute beurre froid et parmesan hors du feu et on mélange vigoureusement pour créer une émulsion crémeuse. Les Italiens disent 'fare la mantecatura' comme on dirait 'monter au beurre'. Sans cette étape, c'est du riz — pas un risotto.",
    chef_tip: "Le risotto doit être servi all'onda (vague) : si vous penchez l'assiette, il doit légèrement s'étaler comme une vague. S'il reste en dôme, il est trop ferme. S'il coule comme de la soupe, trop liquide.",
    cultural_note: "Le risotto Milanese (risotto alla milanese) avec safran est une recette du XVIe siècle. Selon la légende, un maître verrier ajouta du safran à son risotto par erreur, en voulant colorer le verre. Le risque prit il était jaune doré mais délicieux.",
  },
  'Le Tiramisu': {
    title: 'Le Tiramisu',
    description: 'Mascarpone, café, savoiardi',
    duration_minutes: 30,
    difficulty: 'easy',
    ingredients: [
      { name: 'Mascarpone', quantity: '500', unit: 'g', emoji: '🧀', tip: 'Sortir 30 min avant — ne doit pas être trop froid' },
      { name: 'Œufs (jaunes séparés)', quantity: '5', emoji: '🥚' },
      { name: 'Sucre en poudre', quantity: '100', unit: 'g', emoji: '🍬' },
      { name: 'Biscuits savoiardi (doigts de dame)', quantity: '300', unit: 'g', emoji: '🍪' },
      { name: 'Café espresso fort refroidi', quantity: '300', unit: 'ml', emoji: '☕', tip: 'Ajouter 2 cs de Marsala ou Amaretto' },
      { name: 'Cacao amer en poudre', quantity: 'QS', emoji: '🍫' },
    ],
    anecdote: "Le tiramisu ('tire-moi vers le haut' en italien) est apparu dans les années 1960-70 en Vénétie. Il existe une querelle entre Trévise (restaurant 'Le Beccherie', 1969) et Frioul pour sa paternité. Le tiramisu original ne contenait pas de crème fraîche, encore moins de Nutella — ces versions sont des hérésies aux yeux des Italiens.",
    chef_tip: "Montez les blancs en neige ferme séparément et incorporez-les délicatement à la crème mascarpone en soulevant avec une maryse. Ce geste préserve les bulles d'air qui donnent la légèreté.",
    cultural_note: "Le mascarpone est un fromage frais de Lombardie fabriqué en chauffant la crème et en y ajoutant du jus de citron. Son nom viendrait du lombard 'mascherpa' (fromage de sérac). Sa texture crémeuse le rend unique — aucun autre fromage ne peut le remplacer.",
  },

  // ── INDIAN ──────────────────────────────────────────────────────────────
  'Le Curry Butter Chicken': {
    title: 'Le Curry Butter Chicken',
    description: 'Poulet en sauce tomate-crème épicée',
    duration_minutes: 50,
    difficulty: 'medium',
    ingredients: [
      { name: 'Poulet (hauts de cuisse)', quantity: '800', unit: 'g', emoji: '🍗', tip: 'Désosser et couper en 4cm — plus savoureux que le blanc' },
      { name: 'Yaourt entier', quantity: '150', unit: 'g', emoji: '🥛', tip: 'Pour la marinade — attendrit le poulet' },
      { name: 'Tomates concassées', quantity: '400', unit: 'g', emoji: '🍅' },
      { name: 'Crème liquide entière', quantity: '150', unit: 'ml', emoji: '🥛' },
      { name: 'Beurre (ghee de préférence)', quantity: '60', unit: 'g', emoji: '🧈' },
      { name: 'Garam masala', quantity: '2 cc', emoji: '🫙' },
      { name: 'Cumin en poudre', quantity: '1 cc', emoji: '🫙' },
      { name: 'Paprika fumé', quantity: '2 cc', emoji: '🫙' },
      { name: 'Gingembre frais râpé', quantity: '2 cm', emoji: '🫚' },
      { name: 'Ail', quantity: '4 gousses', emoji: '🧄' },
      { name: 'Kashmiri chili (couleur)', quantity: '2 cc', emoji: '🌶️' },
    ],
    anecdote: "Le Butter Chicken (Murgh Makhani) a été inventé par accident vers 1948 au restaurant Moti Mahal de Delhi. Le chef Kundan Lal Gujral a mélangé du poulet tandoori restant avec une sauce tomate-beurre pour ne pas le gaspiller. C'est aujourd'hui le plat indien le plus commandé au monde.",
    chef_tip: "Marinez le poulet au moins 4 heures (idéalement une nuit) dans le yaourt et les épices. La protéase du yaourt attendrit les fibres de la viande. Faites cuire le poulet séparément à haute température avant de l'ajouter à la sauce.",
    cultural_note: "L'Inde est le pays qui consomme le moins de viande par habitant au monde — 80% de la population est végétarienne ou semi-végétarienne. Le curry 'de restaurant' qu'on connaît à l'étranger est souvent très différent de la cuisine familiale indienne, plus variée et plus épicée.",
  },

  // ── PASTRY ──────────────────────────────────────────────────────────────
  'Les Macarons': {
    title: 'Les Macarons',
    description: 'Tant pour tant, meringue italienne',
    duration_minutes: 90,
    difficulty: 'hard',
    ingredients: [
      { name: 'Poudre d\'amandes blanches', quantity: '150', unit: 'g', emoji: '🌰', tip: 'Mixer et tamiser finement — CRUCIAL' },
      { name: 'Sucre glace', quantity: '150', unit: 'g', emoji: '🍬', tip: 'Tamiser avec la poudre d\'amandes' },
      { name: 'Blancs d\'œufs vieillis (à T°ambiante)', quantity: '110', unit: 'g', emoji: '🥚', tip: 'Séparer 48h avant, garder à température ambiante' },
      { name: 'Sucre en poudre', quantity: '150', unit: 'g', emoji: '🍬' },
      { name: 'Eau', quantity: '50', unit: 'g', emoji: '💧', tip: 'Pour le sirop de sucre' },
      { name: 'Colorant en gel (optionnel)', quantity: 'QS', emoji: '🎨', tip: 'Gel = plus concentré, ne liquéfie pas la pâte' },
    ],
    anecdote: "Le macaron parisien (deux coques réunies par une ganache) est différent du macaron de Nancy ou de Saint-Émilion (une seule coque). Pierre Hermé a révolutionné le macaron en 1997 en créant des saveurs inédites comme Ispahan (rose-litchi-framboise) ou Satine (passion-chocolat). Ses macarons se vendent jusqu'à 3€ pièce.",
    chef_tip: "La clé du macaron : le macaronnage. Mélangez la meringue avec la poudre en écrasant contre les parois jusqu'à ce que la pâte 'coule comme un ruban'. Trop peu : coques bosselées. Trop : coques plates et collantes.",
    cultural_note: "La meringue italienne (avec sirop cuit) est plus stable que la meringue française (sucre à froid). Pour les macarons professionnels, c'est toujours la meringue italienne qui est utilisée, car elle supporte mieux l'humidité.",
  },
};
