import type { LessonDetail, PathDetail } from '@/types/database.types';

// ---------------------------------------------------------------------------
// PATH DETAILS (enriched metadata per path)
// ---------------------------------------------------------------------------
export const PATH_DETAILS: Record<string, Omit<PathDetail, 'id' | 'order_index' | 'is_active'>> = {
  french: {
    slug: 'french',
    title: 'Cuisine Française',
    description: 'Maîtrise les classiques de la gastronomie française',
    emoji: '🇫🇷',
    color: '#0055A4',
    country: 'France',
    history: "La cuisine française est reconnue patrimoine culturel immatériel de l'UNESCO depuis 2010. Elle a été codifiée au XIXe siècle par Auguste Escoffier, qui a révolutionné la restauration moderne. La brigade de cuisine, le menu dégustation, les sauces mères — tout vient de cette tradition.",
    key_ingredients: ["Beurre AOP", "Crème fraîche", "Herbes de Provence", "Vin blanc sec", "Moutarde de Dijon", "Échalotes"],
    famous_chefs: ["Auguste Escoffier", "Paul Bocuse", "Joël Robuchon", "Alain Ducasse"],
  },
  italian: {
    slug: 'italian',
    title: 'Cuisine Italienne',
    description: 'Pasta, pizza e molto altro!',
    emoji: '🇮🇹',
    color: '#CE2B37',
    country: 'Italie',
    history: "La cuisine italienne est l'une des plus influentes au monde. Née de 20 régions aux identités culinaires distinctes, elle repose sur la qualité des ingrédients plutôt que sur la complexité des techniques. La pasta existe depuis le XIIIe siècle, bien avant que Marco Polo ne revienne de Chine.",
    key_ingredients: ["Tomates San Marzano", "Huile d'olive extra vierge", "Parmigiano Reggiano", "Basilic frais", "Farine 00", "Mozzarella di bufala"],
    famous_chefs: ["Massimo Bottura", "Carlo Cracco", "Gennaro Contaldo", "Antonio Carluccio"],
  },
  japanese: {
    slug: 'japanese',
    title: 'Cuisine Japonaise',
    description: "Sushi, ramen, et l'art du dashi",
    emoji: '🇯🇵',
    color: '#BC002D',
    country: 'Japon',
    history: "La cuisine japonaise (washoku) est patrimoine de l'UNESCO depuis 2013. Elle repose sur 5 principes fondamentaux : 5 couleurs, 5 saveurs (dont l'umami, découvert en 1908 par le chimiste Kikunae Ikeda), 5 méthodes de cuisson. Le couteau japonais (hocho) est forgé comme une lame de samouraï.",
    key_ingredients: ["Dashi (kombu + bonite)", "Mirin", "Sauce soja", "Miso blanc", "Riz japonais à grain court", "Wasabi frais"],
    famous_chefs: ["Jiro Ono", "Nobu Matsuhisa", "Yoshihiro Murata", "Tetsuya Wakuda"],
  },
  moroccan: {
    slug: 'moroccan',
    title: 'Cuisine Marocaine',
    description: 'Tajine, couscous et ras-el-hanout',
    emoji: '🇲🇦',
    color: '#C1272D',
    country: 'Maroc',
    history: "La cuisine marocaine est le fruit de 3000 ans de civilisations : berbère, arabe, andalouse et juive. Le couscous — déclaré patrimoine de l'UNESCO en 2020 — se roule à la main depuis des millénaires. Le ras-el-hanout (\"tête de l'épicier\") peut contenir jusqu'à 50 épices différentes.",
    key_ingredients: ["Ras-el-hanout", "Safran de Taliouine", "Argan", "Charmoula", "Citrons confits", "Fleur d'oranger"],
    famous_chefs: ["Moha Fedal", "Fatéma Hal", "Najat Kaanache"],
  },
  mexican: {
    slug: 'mexican',
    title: 'Cuisine Mexicaine',
    description: 'Tacos, guacamole et mole',
    emoji: '🇲🇽',
    color: '#006847',
    country: 'Mexique',
    history: "La cuisine mexicaine est patrimoine de l'UNESCO depuis 2010. Le mole negro d'Oaxaca contient jusqu'à 36 ingrédients et peut prendre 3 jours à préparer. Le chocolat, la vanille, les tomates, les piments, l'avocat — tous originaires du Mexique, offerts au monde entier.",
    key_ingredients: ["Piments ancho/chipotle/poblano", "Tomatilles", "Épazote", "Masa harina", "Achiote", "Crema mexicana"],
    famous_chefs: ["Enrique Olvera", "Elena Reygadas", "Ricardo Muñoz Zurita"],
  },
  indian: {
    slug: 'indian',
    title: 'Cuisine Indienne',
    description: 'Curry, masala et pains naan',
    emoji: '🇮🇳',
    color: '#FF9933',
    country: 'Inde',
    history: "La cuisine indienne est l'une des plus anciennes du monde — 5000 ans d'histoire. Elle suit les principes de l'Ayurveda, médecine traditionnelle qui classe les aliments selon leurs effets sur l'énergie du corps. Le curry n'est pas une épice mais un concept anglais : en Inde, chaque plat a sa propre masala.",
    key_ingredients: ["Garam masala", "Ghee", "Cumin noir (kalonji)", "Fenugrec", "Tamarin", "Cardamome verte"],
    famous_chefs: ["Vikas Khanna", "Sanjeev Kapoor", "Manish Mehrotra", "Gaggan Anand"],
  },
  thai: {
    slug: 'thai',
    title: 'Cuisine Thaïlandaise',
    description: 'Pad thaï, laak et soupes de coco',
    emoji: '🇹🇭',
    color: '#A51931',
    country: 'Thaïlande',
    history: "La cuisine thaïlandaise cherche l'équilibre parfait entre 4 saveurs : sucré, salé, acide et pimenté. Autrefois réservée à la cour royale, la cuisine thaïe élaborée est classée patrimoine culturel national. La citronnelle, le galanga et les feuilles de kaffir sont des ingrédients que beaucoup confondent avec leurs cousins européens.",
    key_ingredients: ["Citronnelle", "Galanga", "Feuilles de kaffir", "Pâte de crevettes (kapi)", "Nam pla (sauce poisson)", "Basilic thaï"],
    famous_chefs: ["Bo Songvisava", "Dylan Jones", "Duangporn Songvisava"],
  },
  greek: {
    slug: 'greek',
    title: 'Cuisine Grecque',
    description: 'Mezze, moussaka et tzatziki',
    emoji: '🇬🇷',
    color: '#0D5EAF',
    country: 'Grèce',
    history: "La cuisine grecque est l'ancêtre de la cuisine méditerranéenne. Hippocrate, père de la médecine, considérait que 'que ta nourriture soit ta médecine'. L'huile d'olive grecque est produite depuis 5000 ans. La moussaka telle qu'on la connaît a été standardisée en 1920 par le chef Nikolaos Tselementes.",
    key_ingredients: ["Huile d'olive Kalamata", "Feta AOP", "Origan frais", "Citron de Grèce", "Miel de thym", "Cédrat confit"],
    famous_chefs: ["Yiannis Lucacos", "Nikos Karathanos", "Lefteris Lazarou"],
  },
  chinese: {
    slug: 'chinese',
    title: 'Cuisine Chinoise',
    description: 'Wok, dim sum et sauces authentiques',
    emoji: '🇨🇳',
    color: '#DE2910',
    country: 'Chine',
    history: "La cuisine chinoise est la plus diverse au monde, avec 8 grandes cuisines régionales (Cantonaise, Sichuanaise, Shanghaiaise...). Le wok a 2000 ans d'histoire. L'umami, découvert officiellement au Japon, était utilisé en Chine depuis des siècles via la sauce soja et les champignons shiitake séchés.",
    key_ingredients: ["Huile de sésame", "Sauce hoisin", "Vinaigre de Chinkiang", "Pâte de piment doubanjiang", "Vin de Shaoxing", "Cinq-épices"],
    famous_chefs: ["Ken Hom", "Martin Yan", "Fuchsia Dunlop"],
  },
  pastry: {
    slug: 'pastry',
    title: 'Pâtisserie',
    description: 'Gâteaux, éclairs et macarons',
    emoji: '🎂',
    color: '#F4A6C0',
    country: 'France / Monde',
    history: "La pâtisserie française s'est développée à Versailles pour impressionner les cours européennes. Le macaron parisien actuel a été créé en 1930 par Pierre Desfontaines (Ladurée). L'éclair au chocolat date du XIXe siècle. La pâte feuilletée, selon la légende, aurait été inventée par le peintre Claude Lorrain avant de devenir chef pâtissier.",
    key_ingredients: ["Beurre de tourage 84%", "Farine T45", "Praliné noisette", "Chocolat Valrhona", "Glucose liquide", "Gélatine en feuilles"],
    famous_chefs: ["Pierre Hermé", "Cédric Grolet", "Christophe Michalak", "Gaston Lenôtre"],
  },
  bbq: {
    slug: 'bbq',
    title: 'Barbecue & Grillades',
    description: 'Marinades, fumage et cuissons directes',
    emoji: '🔥',
    color: '#8B0000',
    country: 'États-Unis / Monde',
    history: "Le BBQ américain puise ses racines dans les traditions culinaires des esclaves afro-américains du Sud, qui transformaient des morceaux de viande bas de gamme en plats légendaires via le fumage lent. Chaque région a son style : Kansas City (sauce tomate), Caroline du Nord (vinaigre), Texas (boeuf nature), Memphis (sec).",
    key_ingredients: ["Bois de hickory / mesquite / cerisier", "Paprika fumé", "Sel rose de curing", "Moutarde américaine", "Vinaigre de cidre", "Brown sugar"],
    famous_chefs: ["Aaron Franklin", "Rodney Scott", "Myron Mixon"],
  },
  vegan: {
    slug: 'vegan',
    title: 'Cuisine Vegan',
    description: '100% végétal, 100% savoureux',
    emoji: '🌿',
    color: '#2E7D32',
    country: 'Monde',
    history: "Le végétalisme existe depuis l'Antiquité dans les traditions bouddhistes et jaïnes. Le terme 'vegan' a été créé en 1944 par Donald Watson à Leicester. La cuisine vegan moderne s'appuie sur des techniques innovantes : fermentation, texturisation du gluten, émulsification à l'aquafaba (eau de pois chiche).",
    key_ingredients: ["Aquafaba (eau de pois chiche)", "Levure nutritionnelle", "Tamari (soja sans gluten)", "Cashews trempés", "Agar-agar", "Protéines de pois"],
    famous_chefs: ["Alexis Gauthier", "Matthew Kenney", "Tal Ronnen"],
  },
};

// ---------------------------------------------------------------------------
// LESSON DETAILS (ingredients + anecdotes + tips per lesson)
// ---------------------------------------------------------------------------
export const LESSON_DETAILS: Record<string, Omit<LessonDetail, 'id' | 'path_id' | 'order_index' | 'xp_reward' | 'thumbnail_url'>> = {

  // ── FRENCH ──────────────────────────────────────────────────────────────
  'Les Sauces de Base': {
    title: 'Les Sauces de Base',
    description: 'Béchamel, velouté, hollandaise…',
    duration_minutes: 35,
    difficulty: 'medium',
    ingredients: [
      { name: 'Beurre', quantity: '50', unit: 'g', emoji: '🧈', tip: 'Beurre à 82% min de matière grasse' },
      { name: 'Farine', quantity: '50', unit: 'g', emoji: '🌾' },
      { name: 'Lait entier', quantity: '500', unit: 'ml', emoji: '🥛', tip: 'Chaud pour éviter les grumeaux' },
      { name: 'Noix de muscade', quantity: '1 pincée', emoji: '🌰' },
      { name: 'Sel & poivre blanc', quantity: 'QS', emoji: '🧂' },
    ],
    anecdote: "Les 5 sauces mères françaises (béchamel, velouté, espagnole, hollandaise, tomat) ont été codifiées par Auguste Escoffier vers 1900. Avant lui, Marie-Antoine Carême en avait défini 4. Ces sauces sont la colonne vertébrale de toute la cuisine française classique.",
    chef_tip: "Pour une béchamel sans grumeaux : incorporez le lait chaud en 3 fois en fouettant vigoureusement. Le roux doit refroidir légèrement avant d'ajouter le lait.",
    cultural_note: "La béchamel porte le nom du marquis Louis de Béchameil, financier et courtisan de Louis XIV. Mais c'est probablement un cuisinier anonyme qui l'a inventée — Béchameil n'a fait qu'y apposer son nom.",
  },
  'La Quiche Lorraine': {
    title: 'La Quiche Lorraine',
    description: 'Tarte salée aux lardons et fromage',
    duration_minutes: 50,
    difficulty: 'easy',
    ingredients: [
      { name: 'Pâte brisée', quantity: '250', unit: 'g', emoji: '🫓' },
      { name: 'Lardons fumés', quantity: '200', unit: 'g', emoji: '🥓', tip: 'Blanchir 2 min pour retirer l\'excès de sel' },
      { name: 'Œufs entiers', quantity: '3', emoji: '🥚' },
      { name: 'Crème fraîche épaisse', quantity: '200', unit: 'ml', emoji: '🥛', tip: '30% MG minimum' },
      { name: 'Gruyère râpé', quantity: '100', unit: 'g', emoji: '🧀', tip: 'Optionnel — non traditionnel !' },
      { name: 'Noix de muscade', quantity: '1 pincée', emoji: '🌰' },
    ],
    anecdote: "La vraie quiche lorraine traditionnelle ne contient PAS de fromage ! Seulement des lardons, des œufs et de la crème. Le fromage est une addition moderne. 'Quiche' vient du mot allemand 'Kuchen' (gâteau) — la Lorraine ayant été longtemps sous influence germanique.",
    chef_tip: "Piquez le fond de tarte à la fourchette et cuisez-le 10 min à blanc. La migaine (mélange œufs-crème) doit être à température ambiante avant d'être versée sur les lardons.",
    cultural_note: "La quiche lorraine est née à Nancy et Metz, villes de la région Lorraine. Sa popularité mondiale date de l'après-guerre, quand des soldats américains l'ont découverte et ramenée chez eux.",
  },
  'Le Bœuf Bourguignon': {
    title: 'Le Bœuf Bourguignon',
    description: 'Mijotage et braising à la française',
    duration_minutes: 180,
    difficulty: 'medium',
    ingredients: [
      { name: 'Bœuf paleron ou joue', quantity: '1.2', unit: 'kg', emoji: '🥩', tip: 'Couper en cubes de 5 cm, pas plus petit' },
      { name: 'Pinot Noir de Bourgogne', quantity: '750', unit: 'ml', emoji: '🍷', tip: 'Boire ce qu\'on cuisine !' },
      { name: 'Lardons', quantity: '150', unit: 'g', emoji: '🥓' },
      { name: 'Champignons de Paris', quantity: '300', unit: 'g', emoji: '🍄' },
      { name: 'Oignons grelots', quantity: '200', unit: 'g', emoji: '🧅' },
      { name: 'Bouquet garni', quantity: '1', emoji: '🌿' },
      { name: 'Carottes', quantity: '2', emoji: '🥕' },
      { name: 'Farine', quantity: '2 cs', emoji: '🌾', tip: 'Pour le singer (fariner la viande)' },
    ],
    anecdote: "Julia Child a popularisé le bœuf bourguignon aux États-Unis dans les années 60 via son émission de télévision et son livre 'Mastering the Art of French Cooking'. Elle disait que c'était son plat préféré. La recette date en réalité du Moyen Âge, quand on utilisait le vin pour attendrir des viandes coriaces.",
    chef_tip: "Saisissez la viande EN PETITES QUANTITÉS — si vous en mettez trop, elle bout au lieu de dorer. La couleur brune (réaction de Maillard) apporte 80% du goût final.",
    cultural_note: "La Bourgogne est la région viticole la plus prestigieuse de France. Le vin qu'on y cuisine est le même qu'on y boit : le Pinot Noir. Un vrai Bourguignon ne transige pas sur ce point.",
  },
  'Les Crêpes': {
    title: 'Les Crêpes',
    description: 'Fine crêpe dorée sucrée ou salée',
    duration_minutes: 30,
    difficulty: 'easy',
    ingredients: [
      { name: 'Farine T45', quantity: '250', unit: 'g', emoji: '🌾' },
      { name: 'Œufs', quantity: '3', emoji: '🥚' },
      { name: 'Lait', quantity: '500', unit: 'ml', emoji: '🥛' },
      { name: 'Beurre fondu', quantity: '50', unit: 'g', emoji: '🧈' },
      { name: 'Sucre', quantity: '30', unit: 'g', emoji: '🍬', tip: 'Uniquement pour version sucrée' },
      { name: 'Rhum', quantity: '1 cs', emoji: '🍶', tip: 'Optionnel — arôme classique' },
    ],
    anecdote: "La chandeleur (2 février) est la fête des crêpes en France. La tradition veut qu'on tienne une pièce d'or dans la main gauche en faisant sauter la première crêpe de la main droite — pour s'assurer la prospérité. Les Bretons sont fiers de leurs galettes de sarrasin (crêpes salées), qui existent depuis le XIIIe siècle.",
    chef_tip: "Laissez reposer la pâte 1 heure minimum. Cela permet aux protéines du gluten de se détendre — vos crêpes seront plus souples et moins élastiques.",
    cultural_note: "La crêpe Suzette a été inventée par accident en 1895 à Monte-Carlo par le jeune Auguste Escoffier, alors qu'il travaillait pour le Prince de Galles (futur Édouard VII). Le flambage au Grand Marnier était une erreur devenue un classique.",
  },

  // ── JAPANESE ────────────────────────────────────────────────────────────
  'Le Dashi': {
    title: 'Le Dashi',
    description: 'Le bouillon fondateur de la cuisine japonaise',
    duration_minutes: 20,
    difficulty: 'easy',
    ingredients: [
      { name: 'Kombu séché', quantity: '10', unit: 'g', emoji: '🌿', tip: 'Ne pas laver — la poudre blanche est savoureuse !' },
      { name: 'Katsuobushi (bonite séchée)', quantity: '20', unit: 'g', emoji: '🐟' },
      { name: 'Eau froide', quantity: '1', unit: 'L', emoji: '💧', tip: 'Eau de source si possible' },
    ],
    anecdote: "Le dashi est l'épine dorsale de 90% de la cuisine japonaise. Il a permis au chercheur Kikunae Ikeda de découvrir en 1908 la cinquième saveur : l'umami. L'acide glutamique du kombu et l'inosinate de la bonite créent ensemble une synergie umami extraordinaire.",
    chef_tip: "Ne jamais faire bouillir le kombu — chauffez l'eau à 60°C et laissez infuser 30 min. La bonite se verse en une seule fois quand l'eau frémit, puis on coupe le feu immédiatement.",
    cultural_note: "Il existe deux types de dashi : le ichiban dashi (première infusion, délicat) et le niban dashi (deuxième infusion, plus corsé pour les sauces). Les chefs étoilés japonais consacrent parfois une heure entière à préparer leur dashi du matin.",
  },
  'Les Sushis': {
    title: 'Les Sushis',
    description: 'Riz vinaigré, nori et garnitures',
    duration_minutes: 60,
    difficulty: 'hard',
    ingredients: [
      { name: 'Riz japonais Koshihikari', quantity: '300', unit: 'g', emoji: '🍚', tip: 'Rincer 5x jusqu\'à eau claire' },
      { name: 'Vinaigre de riz', quantity: '60', unit: 'ml', emoji: '🫙' },
      { name: 'Sucre', quantity: '20', unit: 'g', emoji: '🍬' },
      { name: 'Sel fin', quantity: '10', unit: 'g', emoji: '🧂' },
      { name: 'Saumon sashimi grade', quantity: '200', unit: 'g', emoji: '🐟', tip: 'Certifié sashimi-grade = congelé -20°C/7j' },
      { name: 'Nori premium', quantity: '5 feuilles', emoji: '🌿' },
      { name: 'Wasabi frais', quantity: 'QS', emoji: '🌿' },
    ],
    anecdote: "Le sushi tel qu'on le connaît (nigiri) a été inventé vers 1820 à Tokyo (alors Edo) par Hanaya Yohei. C'était un fast-food de rue ! Le sushi fermenté originel (narezushi) existe depuis 1300 ans et prend des mois à préparer. Le saumon en sushi ? Une invention norvégienne des années 1980 pour exporter leur saumon d'élevage au Japon.",
    chef_tip: "Préparez le riz à sushi ('shari') en l'assaisonnant avec un éventail pour le refroidir rapidement sans le rendre collant. La texture idéale : chaque grain doit être individuel mais légèrement collant.",
    cultural_note: "Jiro Ono, 97 ans, tient un restaurant 3 étoiles Michelin de 10 places à Tokyo où les réservations sont impossibles à obtenir. Il dit se lever à 5h chaque matin depuis 75 ans. Son dojo : 'Une fois que tu décides ton métier, plonge-y totalement.'",
  },

  // ── MOROCCAN ────────────────────────────────────────────────────────────
  'Le Tajine d\'Agneau': {
    title: "Le Tajine d'Agneau",
    description: 'Viande fondante aux pruneaux et amandes',
    duration_minutes: 120,
    difficulty: 'medium',
    ingredients: [
      { name: 'Épaule d\'agneau', quantity: '1.2', unit: 'kg', emoji: '🍖', tip: 'Demander au boucher de couper en morceaux de 4 cm' },
      { name: 'Pruneaux d\'Agen', quantity: '200', unit: 'g', emoji: '🫐', tip: 'Tremper 30 min dans du thé à la menthe' },
      { name: 'Amandes mondées', quantity: '100', unit: 'g', emoji: '🌰' },
      { name: 'Oignons', quantity: '3', emoji: '🧅' },
      { name: 'Safran de Taliouine', quantity: '1 pincée', emoji: '🌸', tip: 'Infuser dans 2 cs d\'eau chaude avant usage' },
      { name: 'Ras-el-hanout', quantity: '2 cs', emoji: '🫙' },
      { name: 'Gingembre en poudre', quantity: '1 cs', emoji: '🫚' },
      { name: 'Miel', quantity: '2 cs', emoji: '🍯' },
      { name: 'Huile d\'argan', quantity: '3 cs', emoji: '🫗' },
    ],
    anecdote: "Le tajine tire son nom du plat conique en terre cuite dans lequel il cuit. La vapeur monte, se condense sur le couvercle et retombe sur la viande — une distillation naturelle qui concentre les arômes. On dit que chaque famille marocaine a sa propre recette de tajine, jalousement gardée.",
    chef_tip: "Cuisez à feu très doux (150°C au four ou flamme minimale). La fonte lente à basse température est le secret de la tendreté. Ne jamais ouvrir le couvercle pendant la cuisson.",
    cultural_note: "La ville de Fès est considérée comme la capitale gastronomique du Maroc. Les femmes y sont gardiennes des recettes ancestrales, transmises oralement de mère en fille. Certaines recettes de tajine remontent à la cour de l'empire almohade du XIIIe siècle.",
  },

  // ── ITALIAN ─────────────────────────────────────────────────────────────
  'Les Pâtes Fraîches': {
    title: 'Les Pâtes Fraîches',
    description: 'Tagliatelle, fettuccine maison',
    duration_minutes: 45,
    difficulty: 'medium',
    ingredients: [
      { name: 'Farine 00 (grano tenero)', quantity: '300', unit: 'g', emoji: '🌾', tip: 'La farine 00 donne une texture soyeuse' },
      { name: 'Semoule de blé dur', quantity: '100', unit: 'g', emoji: '🌾', tip: 'Pour la texture al dente' },
      { name: 'Œufs entiers (gros)', quantity: '3', emoji: '🥚' },
      { name: 'Jaunes d\'œufs', quantity: '2', emoji: '🥚', tip: 'Plus de jaunes = pâte plus riche et jaune' },
      { name: 'Huile d\'olive', quantity: '1 cs', emoji: '🫒' },
      { name: 'Sel fin', quantity: '1 pincée', emoji: '🧂' },
    ],
    anecdote: "La légende dit que les tagliatelle ont été créées en 1487 à Bologne par un cuisinier nommé Zefirano pour le mariage de Lucrèce Borgia — inspiré par ses cheveux blonds. L'Academia della Cucina Italiana a même déposé une portion de tagliatelle en or à la chambre de commerce de Bologne pour certifier la largeur exacte : 8mm cuit (1/12270ème de la largeur de la Tour des Asinelli).",
    chef_tip: "Pétrir 10 minutes vigoureusement jusqu'à obtenir une pâte lisse comme de la soie. La reposer 30 min filmée à température ambiante est INDISPENSABLE pour détendre le gluten.",
    cultural_note: "Chaque région d'Italie a ses propres pâtes. Bologne : tagliatelle et tortellini. Rome : rigatoni et tonnarelli. Naples : spaghetti et paccheri. Sardaigne : malloreddus. La forme de la pâte n'est pas aléatoire — elle est pensée pour retenir une sauce spécifique.",
  },
  'Le Risotto': {
    title: 'Le Risotto',
    description: 'Al dente avec mantecatura',
    duration_minutes: 30,
    difficulty: 'hard',
    ingredients: [
      { name: 'Riz Carnaroli (ou Arborio)', quantity: '320', unit: 'g', emoji: '🍚', tip: 'Carnaroli tient mieux la cuisson qu\'Arborio' },
      { name: 'Bouillon chaud (légumes ou volaille)', quantity: '1.2', unit: 'L', emoji: '🫕', tip: 'Doit être CHAUD — ajout de froid casse la cuisson' },
      { name: 'Vin blanc sec', quantity: '150', unit: 'ml', emoji: '🍾' },
      { name: 'Échalotes', quantity: '2', emoji: '🧅' },
      { name: 'Beurre froid', quantity: '60', unit: 'g', emoji: '🧈', tip: 'TRÈS froid pour la mantecatura finale' },
      { name: 'Parmigiano Reggiano 36 mois', quantity: '80', unit: 'g', emoji: '🧀' },
      { name: 'Huile d\'olive', quantity: '3 cs', emoji: '🫒' },
    ],
    anecdote: "La mantecatura est l'étape finale magique du risotto : on ajoute beurre froid et parmesan hors du feu et on mélange vigoureusement pour créer une émulsion crémeuse. Les Italiens disent 'fare la mantecatura' comme on dirait 'monter au beurre'. Sans cette étape, c'est du riz — pas un risotto.",
    chef_tip: "Le risotto doit être servi all'onda (vague) : si vous penchez l'assiette, il doit légèrement s'étaler comme une vague. S'il reste en dôme, il est trop ferme. S'il coule comme de la soupe, trop liquide.",
    cultural_note: "Le risotto Milanese (risotto alla milanese) avec safran est une recette du XVIe siècle. Selon la légende, un maître verrier ajouta du safran à son risotto par erreur, en voulant colorer le verre. Le risque prit il était jaune doré mais délicieux.",
  },
  'Le Tiramisu': {
    title: 'Le Tiramisu',
    description: 'Mascarpone, café, savoiardi',
    duration_minutes: 30,
    difficulty: 'easy',
    ingredients: [
      { name: 'Mascarpone', quantity: '500', unit: 'g', emoji: '🧀', tip: 'Sortir 30 min avant — ne doit pas être trop froid' },
      { name: 'Œufs (jaunes séparés)', quantity: '5', emoji: '🥚' },
      { name: 'Sucre en poudre', quantity: '100', unit: 'g', emoji: '🍬' },
      { name: 'Biscuits savoiardi (doigts de dame)', quantity: '300', unit: 'g', emoji: '🍪' },
      { name: 'Café espresso fort refroidi', quantity: '300', unit: 'ml', emoji: '☕', tip: 'Ajouter 2 cs de Marsala ou Amaretto' },
      { name: 'Cacao amer en poudre', quantity: 'QS', emoji: '🍫' },
    ],
    anecdote: "Le tiramisu ('tire-moi vers le haut' en italien) est apparu dans les années 1960-70 en Vénétie. Il existe une querelle entre Trévise (restaurant 'Le Beccherie', 1969) et Frioul pour sa paternité. Le tiramisu original ne contenait pas de crème fraîche, encore moins de Nutella — ces versions sont des hérésies aux yeux des Italiens.",
    chef_tip: "Montez les blancs en neige ferme séparément et incorporez-les délicatement à la crème mascarpone en soulevant avec une maryse. Ce geste préserve les bulles d'air qui donnent la légèreté.",
    cultural_note: "Le mascarpone est un fromage frais de Lombardie fabriqué en chauffant la crème et en y ajoutant du jus de citron. Son nom viendrait du lombard 'mascherpa' (fromage de sérac). Sa texture crémeuse le rend unique — aucun autre fromage ne peut le remplacer.",
  },

  // ── INDIAN ──────────────────────────────────────────────────────────────
  'Le Curry Butter Chicken': {
    title: 'Le Curry Butter Chicken',
    description: 'Poulet en sauce tomate-crème épicée',
    duration_minutes: 50,
    difficulty: 'medium',
    ingredients: [
      { name: 'Poulet (hauts de cuisse)', quantity: '800', unit: 'g', emoji: '🍗', tip: 'Désosser et couper en 4cm — plus savoureux que le blanc' },
      { name: 'Yaourt entier', quantity: '150', unit: 'g', emoji: '🥛', tip: 'Pour la marinade — attendrit le poulet' },
      { name: 'Tomates concassées', quantity: '400', unit: 'g', emoji: '🍅' },
      { name: 'Crème liquide entière', quantity: '150', unit: 'ml', emoji: '🥛' },
      { name: 'Beurre (ghee de préférence)', quantity: '60', unit: 'g', emoji: '🧈' },
      { name: 'Garam masala', quantity: '2 cc', emoji: '🫙' },
      { name: 'Cumin en poudre', quantity: '1 cc', emoji: '🫙' },
      { name: 'Paprika fumé', quantity: '2 cc', emoji: '🫙' },
      { name: 'Gingembre frais râpé', quantity: '2 cm', emoji: '🫚' },
      { name: 'Ail', quantity: '4 gousses', emoji: '🧄' },
      { name: 'Kashmiri chili (couleur)', quantity: '2 cc', emoji: '🌶️' },
    ],
    anecdote: "Le Butter Chicken (Murgh Makhani) a été inventé par accident vers 1948 au restaurant Moti Mahal de Delhi. Le chef Kundan Lal Gujral a mélangé du poulet tandoori restant avec une sauce tomate-beurre pour ne pas le gaspiller. C'est aujourd'hui le plat indien le plus commandé au monde.",
    chef_tip: "Marinez le poulet au moins 4 heures (idéalement une nuit) dans le yaourt et les épices. La protéase du yaourt attendrit les fibres de la viande. Faites cuire le poulet séparément à haute température avant de l'ajouter à la sauce.",
    cultural_note: "L'Inde est le pays qui consomme le moins de viande par habitant au monde — 80% de la population est végétarienne ou semi-végétarienne. Le curry 'de restaurant' qu'on connaît à l'étranger est souvent très différent de la cuisine familiale indienne, plus variée et plus épicée.",
  },

  // ── FRENCH NEW LESSONS ───────────────────────────────────────────────────
  'La Ratatouille': {
    title: 'La Ratatouille',
    description: 'Légumes provençaux mijotés à l\'huile d\'olive',
    duration_minutes: 50,
    difficulty: 'easy',
    ingredients: [
      { name: 'Courgettes', quantity: '2', emoji: '🥒' },
      { name: 'Aubergines', quantity: '1 grosse', emoji: '🍆' },
      { name: 'Poivrons (rouge + jaune)', quantity: '2', emoji: '🫑' },
      { name: 'Tomates mûres', quantity: '4', emoji: '🍅', tip: 'Monder (ébouillanter) pour retirer la peau' },
      { name: 'Oignons', quantity: '2', emoji: '🧅' },
      { name: 'Ail', quantity: '3 gousses', emoji: '🧄' },
      { name: 'Huile d\'olive', quantity: '8 cs', emoji: '🫒', tip: 'Soyez généreux — c\'est la base de la saveur' },
      { name: 'Thym & basilic frais', quantity: 'QS', emoji: '🌿' },
    ],
    anecdote: "La ratatouille est un plat d'été niçois. Son nom vient du verbe 'touiller' (remuer). Le film Pixar de 2007 l'a rendue célèbre dans le monde entier. La recette 'confit byaldi' du chef Thomas Keller (qui a inspiré le film) est différente : les légumes sont tranchés finement et disposés en couches.",
    chef_tip: "Le secret : faites cuire chaque légume séparément avant de les réunir. Les courgettes, aubergines et poivrons ont des temps de cuisson différents. Réunissez-les en fin pour 20 min ensemble.",
    cultural_note: "La Provence est la région française la plus ensoleillée — ses légumes d'été sont incomparables. La ratatouille se mange chaude, froide ou tiède, le lendemain elle est encore meilleure.",
  },

  'Le Confit de Canard': {
    title: 'Le Confit de Canard',
    description: 'Cuisson lente dans la graisse, tradition gasconne',
    duration_minutes: 180,
    difficulty: 'medium',
    ingredients: [
      { name: 'Cuisses de canard', quantity: '4', emoji: '🦆', tip: 'Label Rouge ou Fermier du Gers' },
      { name: 'Gros sel de Guérande', quantity: '50', unit: 'g', emoji: '🧂', tip: 'Mélanger avec thym, laurier, ail pour la saumure sèche' },
      { name: 'Graisse de canard', quantity: '500', unit: 'g', emoji: '🫙', tip: 'Ou huile de tournesol en dépannage' },
      { name: 'Ail', quantity: '6 gousses', emoji: '🧄' },
      { name: 'Thym & laurier', quantity: 'QS', emoji: '🌿' },
      { name: 'Pommes de terre sarladaises', quantity: '800', unit: 'g', emoji: '🥔', tip: 'Cuites dans la graisse de canard — incontournable' },
    ],
    anecdote: "Le confit de canard est né de la nécessité : en Gascogne, les paysans abattaient les canards en automne et conservaient la viande dans sa propre graisse pour l'hiver. La graisse est un excellent conservateur naturel — un confit peut se garder des mois. Aujourd'hui, c'est un plat de luxe.",
    chef_tip: "La technique en 2 temps : 1) Saler les cuisses 12h au frigo. 2) Cuire à 80-90°C dans la graisse pendant 2h30. Terminez en faisant dorer la peau à la poêle très chaude pendant 3 minutes.",
    cultural_note: "La Gascogne (actuel Gers) est le berceau du confit et du foie gras. Armagnac, magret, cassoulet, confit — cette région a plus de recettes emblématiques au km² que n'importe où en France.",
  },

  'La Tarte Tatin': {
    title: 'La Tarte Tatin',
    description: 'Tarte renversée aux pommes caramélisées',
    duration_minutes: 60,
    difficulty: 'medium',
    ingredients: [
      { name: 'Pommes Golden ou Reinette', quantity: '8', emoji: '🍎', tip: 'Pommes fermes qui tiennent à la cuisson' },
      { name: 'Beurre', quantity: '80', unit: 'g', emoji: '🧈', tip: 'Beurre demi-sel pour une touche bretonne' },
      { name: 'Sucre en poudre', quantity: '150', unit: 'g', emoji: '🍬' },
      { name: 'Pâte feuilletée', quantity: '1 rouleau', emoji: '🫓', tip: 'Ou pâte brisée pour une version plus rustique' },
      { name: 'Vanille', quantity: '1 gousse', emoji: '🍦' },
    ],
    anecdote: "La tarte Tatin a été inventée par accident vers 1898 par les sœurs Stéphanie et Caroline Tatin à l'Hôtel Tatin à Lamotte-Beuvron (Sologne). Stéphanie aurait oublié la pâte et posé les pommes directement dans le moule beurré-sucré, ajoutant la pâte par-dessus — puis retournant l'ensemble. L'accident est devenu un classique.",
    chef_tip: "Caramélisez d'abord le beurre et le sucre dans la poêle, ajoutez les pommes coupées en quartiers épais et laissez-les colorer 15-20 min. La pâte se pose dessus comme un couvercle, puis on enfourne et on retourne.",
    cultural_note: "La tarte Tatin figure au patrimoine gastronomique français. Elle est aujourd'hui servie dans des restaurants du monde entier. La ville de Lamotte-Beuvron organise chaque année un concours de tarte Tatin.",
  },

  'Le Coq au Vin': {
    title: 'Le Coq au Vin',
    description: 'Poulet braisé au vin rouge, lardons, champignons',
    duration_minutes: 120,
    difficulty: 'medium',
    ingredients: [
      { name: 'Poulet fermier (ou coq)', quantity: '1.8', unit: 'kg', emoji: '🍗', tip: 'Couper en 8 morceaux — garde la peau pour la couleur' },
      { name: 'Pinot Noir de Bourgogne', quantity: '750', unit: 'ml', emoji: '🍷' },
      { name: 'Lardons fumés', quantity: '200', unit: 'g', emoji: '🥓' },
      { name: 'Champignons de Paris', quantity: '250', unit: 'g', emoji: '🍄' },
      { name: 'Oignons grelots', quantity: '200', unit: 'g', emoji: '🧅' },
      { name: 'Ail', quantity: '4 gousses', emoji: '🧄' },
      { name: 'Cognac', quantity: '5 cs', emoji: '🥃', tip: 'Pour flamber et parfumer' },
      { name: 'Bouquet garni', quantity: '1', emoji: '🌿' },
    ],
    anecdote: "Julia Child a popularisé le coq au vin en Amérique dans les années 60. Le 'coq' original était un vieux mâle trop coriace pour être rôti — la cuisson prolongée dans le vin l'attendrissait. Aujourd'hui on utilise du poulet fermier plus tendre, mais la technique reste identique.",
    chef_tip: "Marinez les morceaux de poulet dans le vin avec les aromates pendant 12 heures. Égouttez, séchez et saisissez à feu vif. La coloration est essentielle pour la saveur finale.",
    cultural_note: "Le coq au vin est le plat emblématique de la Bourgogne. Chaque région a sa variante : coq au Riesling en Alsace, coq au Champagne en Champagne, coq au cidre en Normandie.",
  },

  'La Vichyssoise': {
    title: 'La Vichyssoise',
    description: 'Soupe froide poireaux-pommes de terre',
    duration_minutes: 40,
    difficulty: 'easy',
    ingredients: [
      { name: 'Poireaux (partie blanche)', quantity: '4', emoji: '🌿', tip: 'Garder 1 cm du vert tendre' },
      { name: 'Pommes de terre Bintje', quantity: '500', unit: 'g', emoji: '🥔' },
      { name: 'Beurre', quantity: '50', unit: 'g', emoji: '🧈' },
      { name: 'Bouillon de volaille', quantity: '1', unit: 'L', emoji: '🫕' },
      { name: 'Crème fraîche liquide', quantity: '200', unit: 'ml', emoji: '🥛' },
      { name: 'Ciboulette fraîche', quantity: 'QS', emoji: '🌱', tip: 'Finement ciselée pour la garniture' },
    ],
    anecdote: "La vichyssoise a été créée en 1917 aux États-Unis par le chef français Louis Diat au Ritz-Carlton de New York — inspiré de la soupe aux poireaux de sa mère, qu'il servait froide pour la rendre plus rafraîchissante en été. Son nom rend hommage à Vichy, ville thermale près de sa ville natale.",
    chef_tip: "Après mixage, passer au chinois fin pour une texture parfaitement lisse et crémeuse. Rectifier l'assaisonnement après refroidissement — le froid atténue les saveurs, il faut souvent saler davantage.",
    cultural_note: "La vichyssoise est paradoxalement plus connue aux États-Unis qu'en France. En France, la soupe aux poireaux se mange chaude. La version froide américaine a été réimportée en Europe comme un 'classique français'.",
  },

  'La Bouillabaisse': {
    title: 'La Bouillabaisse',
    description: 'Soupe de poissons marseillaise et sa rouille',
    duration_minutes: 90,
    difficulty: 'hard',
    ingredients: [
      { name: 'Poissons de roche variés', quantity: '2', unit: 'kg', emoji: '🐟', tip: 'Vive, grondin, saint-pierre, scorpène — demandez au poissonnier' },
      { name: 'Safran', quantity: '1/2 g', emoji: '🌸', tip: 'Infuser dans l\'eau chaude avant usage' },
      { name: 'Fenouil', quantity: '1 bulbe', emoji: '🌿' },
      { name: 'Tomates', quantity: '3', emoji: '🍅' },
      { name: 'Ail', quantity: '8 gousses', emoji: '🧄' },
      { name: 'Huile d\'olive', quantity: '10 cs', emoji: '🫒' },
      { name: 'Peau d\'orange', quantity: '2 lanières', emoji: '🍊' },
      { name: 'Croûtons frottés à l\'ail', quantity: 'QS', emoji: '🫓' },
      { name: 'Rouille (aïoli au safran)', quantity: '1 bol', emoji: '🫙' },
    ],
    anecdote: "La bouillabaisse de Marseille ('bouil-abaisso' en provençal : 'ça bout, on baisse') était au XIXe siècle une soupe de pêcheurs bon marché, faite des poissons trop laids ou trop osseux pour être vendus. Aujourd'hui, une vraie bouillabaisse dans un grand restaurant marseillais coûte 60-80€ par personne.",
    chef_tip: "La bouillabaisse se sert en deux temps : d'abord le bouillon avec les croûtons et la rouille, puis les poissons sur un plat. Le bouillon doit être bouilli vigoureusement pour émulsionner l'huile d'olive.",
    cultural_note: "La Charte de la Bouillabaisse de Marseille (1980) définit les règles strictes : au moins 4 espèces de poissons de roche, safran, fenouil, peau d'orange. Les restaurants signataires s'engagent à la respecter.",
  },

  // ── JAPANESE NEW LESSONS ──────────────────────────────────────────────────
  'La Soupe Miso': {
    title: 'La Soupe Miso',
    description: 'Dashi, miso, tofu et wakamé',
    duration_minutes: 15,
    difficulty: 'easy',
    ingredients: [
      { name: 'Dashi (ichiban)', quantity: '800', unit: 'ml', emoji: '🫕', tip: 'Ou dashi instantané en granulés en dépannage' },
      { name: 'Miso blanc (shiro miso)', quantity: '3 cs', emoji: '🫙', tip: 'Doux et légèrement sucré — parfait pour débuter' },
      { name: 'Tofu soyeux', quantity: '150', unit: 'g', emoji: '⬜', tip: 'Couper en cubes de 1.5 cm' },
      { name: 'Wakamé séché', quantity: '5', unit: 'g', emoji: '🌿', tip: 'Réhydrater 5 min dans l\'eau froide' },
      { name: 'Ciboulette japonaise (negi)', quantity: '2 tiges', emoji: '🌱' },
    ],
    anecdote: "La soupe miso est consommée au Japon au petit-déjeuner, déjeuner et dîner — souvent deux fois par jour. Des études scientifiques japonaises montrent que sa consommation régulière est associée à une réduction du risque de cancer du sein. La fermentation du miso produit des acides aminés essentiels et des probiotiques.",
    chef_tip: "Ajoutez le miso hors du feu et ne le faites jamais bouillir — la chaleur détruit les enzymes bénéfiques et les arômes délicats. Délayez le miso dans une petite louche de bouillon avant de l'incorporer.",
    cultural_note: "Il existe plus de 1000 variétés de miso au Japon selon la région, la durée de fermentation (quelques semaines à 3 ans) et le type de base (soja, riz, orge). Le miso de Saikyo (Kyoto) est le plus doux, celui de Hatcho (Aichi) le plus intense.",
  },

  'Les Gyoza': {
    title: 'Les Gyoza',
    description: 'Raviolis japonais poêlés-vapeur croustillants',
    duration_minutes: 60,
    difficulty: 'medium',
    ingredients: [
      { name: 'Pâte à gyoza (ronde)', quantity: '30 feuilles', emoji: '⚪', tip: 'En épicerie asiatique — la maison c\'est possible mais complexe' },
      { name: 'Porc haché', quantity: '250', unit: 'g', emoji: '🥩' },
      { name: 'Chou chinois (hakusai)', quantity: '150', unit: 'g', emoji: '🥬', tip: 'Hacher et saler 10 min pour retirer l\'eau — CRUCIAL' },
      { name: 'Ciboulette chinoise (nira)', quantity: '30', unit: 'g', emoji: '🌱' },
      { name: 'Gingembre frais', quantity: '2 cm', emoji: '🫚' },
      { name: 'Sauce soja', quantity: '2 cs', emoji: '🫙' },
      { name: 'Huile de sésame', quantity: '1 cs', emoji: '🫗' },
      { name: 'Saké de cuisine', quantity: '1 cs', emoji: '🍶' },
    ],
    anecdote: "Les gyoza sont inspirés des jiaozi chinois, importés au Japon après la Seconde Guerre mondiale par les soldats revenus de Mandchourie. Les Japonais les ont adaptés : farce plus aillée, pliage différent, et surtout la cuisson yaki-gyoza (poêlé-vapeur) qui crée la face croustillante unique.",
    chef_tip: "La clé : après saisie, versez 50ml d'eau, couvrez immédiatement et laissez cuire à la vapeur 3 minutes. Retirez le couvercle et laissez l'eau s'évaporer jusqu'à entendre le crépitement — c'est le signe que le fond est croustillant.",
    cultural_note: "Utsunomiya (préfecture de Tochigi) et Hamamatsu se disputent le titre de capitale des gyoza au Japon. Ces deux villes organisent chaque année un festival du gyoza. Les habitants de Hamamatsu réclament 250 gyoza par famille et par an — record national.",
  },

  "L'Oyakodon": {
    title: "L'Oyakodon",
    description: "Poulet, oignon et œuf sur riz — le bol du parent",
    duration_minutes: 20,
    difficulty: 'easy',
    ingredients: [
      { name: 'Riz japonais cuit', quantity: '400', unit: 'g', emoji: '🍚' },
      { name: 'Hauts de cuisse de poulet', quantity: '300', unit: 'g', emoji: '🍗', tip: 'Sans peau, coupés en bouchées' },
      { name: 'Oignon', quantity: '1 gros', emoji: '🧅', tip: 'Émincer finement' },
      { name: 'Œufs', quantity: '4', emoji: '🥚', tip: 'Battre légèrement — les jaunes doivent rester visibles' },
      { name: 'Dashi', quantity: '150', unit: 'ml', emoji: '🫕' },
      { name: 'Sauce soja', quantity: '3 cs', emoji: '🫙' },
      { name: 'Mirin', quantity: '3 cs', emoji: '🍶' },
      { name: 'Sucre', quantity: '1 cc', emoji: '🍬' },
    ],
    anecdote: "Oyakodon signifie 'bol parent-enfant' (oyako = parent+enfant, don = bol de riz) car il réunit la poule (le parent) et l'œuf (l'enfant). C'est l'un des donburi les plus populaires au Japon — rapide, économique et réconfortant. Il est servi dans presque tous les restaurants de cuisine familiale.",
    chef_tip: "L'œuf se verse sur le poulet et l'oignon déjà cuits, puis on couvre 30 secondes seulement. L'œuf doit rester mi-cuit (onsen egg texture). Versez immédiatement sur le riz chaud — la cuisson continue dans le bol.",
    cultural_note: "Le donburi (bol de riz garni) est la version japonaise du fast-food. L'oyakodon, le gyudon (bœuf), le katsudon (tonkatsu) — ce sont les plats de la restauration rapide et des cantines japonaises. Yoshinoya, la chaîne de gyudon, a ouvert en 1899.",
  },

  'Le Teriyaki': {
    title: 'Le Teriyaki',
    description: 'Laquage sucré-salé au mirin et sauce soja',
    duration_minutes: 25,
    difficulty: 'easy',
    ingredients: [
      { name: 'Poulet ou saumon', quantity: '600', unit: 'g', emoji: '🍗', tip: 'Poulet cuisse ou filets de saumon avec peau' },
      { name: 'Sauce soja', quantity: '4 cs', emoji: '🫙' },
      { name: 'Mirin', quantity: '4 cs', emoji: '🍶', tip: 'Vin de riz doux — irremplaçable pour la brillance' },
      { name: 'Saké', quantity: '2 cs', emoji: '🍶' },
      { name: 'Sucre', quantity: '2 cc', emoji: '🍬' },
      { name: 'Graines de sésame', quantity: 'QS', emoji: '⚫' },
    ],
    anecdote: "Teriyaki vient de 'teri' (brillance du glaçage) et 'yaki' (cuisson au feu). La technique date de l'époque Edo (17e siècle). Le teriyaki qu'on connaît à l'étranger est une version américanisée — en japonais, le terme désigne une méthode de cuisson, pas une sauce spécifique.",
    chef_tip: "Saisissez la viande à sec d'abord, puis ajoutez la sauce en fin de cuisson. La sauce se concentre rapidement — surveillez pour éviter qu'elle ne brûle. Le sucre caramélise et crée le glaçage brillant.",
    cultural_note: "Les immigrants japonais à Hawaï ont adapté la sauce teriyaki avec du sucre de canne local au début du XXe siècle. Cette version plus sucrée est devenue la base du 'teriyaki américain'. La chaîne Teriyaki Madness compte 300 restaurants aux États-Unis.",
  },

  'Le Karaage': {
    title: 'Le Karaage',
    description: 'Poulet frit japonais — croustillant au gingembre',
    duration_minutes: 35,
    difficulty: 'easy',
    ingredients: [
      { name: 'Hauts de cuisse de poulet', quantity: '600', unit: 'g', emoji: '🍗', tip: 'Avec peau, sans os — coupés en 3 morceaux' },
      { name: 'Sauce soja', quantity: '3 cs', emoji: '🫙' },
      { name: 'Saké', quantity: '2 cs', emoji: '🍶' },
      { name: 'Gingembre frais râpé', quantity: '2 cm', emoji: '🫚' },
      { name: 'Ail', quantity: '2 gousses', emoji: '🧄', tip: 'Râpé finement' },
      { name: 'Fécule de pomme de terre (katakuriko)', quantity: '6 cs', emoji: '⬜', tip: 'La fécule de pomme de terre donne un croustillant supérieur à la farine' },
      { name: 'Huile de friture', quantity: 'QS', emoji: '🫗' },
      { name: 'Citron', quantity: '1', emoji: '🍋' },
    ],
    anecdote: "Le karaage est l'un des plats préférés des Japonais selon tous les sondages. La technique est apparue après la Seconde Guerre mondiale, inspirée par la friture de poulet américaine. Mais les Japonais l'ont totalement réappropriée avec la marinade gingembre-soja et la fécule de pomme de terre.",
    chef_tip: "Double friture : 1ère à 160°C pendant 3 min (cuisson intérieure), repos 2 min, 2ème à 190°C pendant 1 min (croustillant extérieur). Cette technique professionnelle garantit un karaage parfait.",
    cultural_note: "Nakatsu dans la préfecture d'Oita revendique d'être la capitale du karaage. La ville compte plus de 60 restaurants spécialisés pour 40 000 habitants. Un record mondial probable en densité de restaurants de poulet frit.",
  },

  // ── ITALIAN NEW LESSONS ───────────────────────────────────────────────────
  'Le Pesto Genovese': {
    title: 'Le Pesto Genovese',
    description: 'Basilic, pignons, pecorino au mortier',
    duration_minutes: 20,
    difficulty: 'easy',
    ingredients: [
      { name: 'Basilic frais (Genovese DOP)', quantity: '50', unit: 'g', emoji: '🌿', tip: 'Feuilles uniquement, ne pas laver — juste essuyer' },
      { name: 'Pignons de pin', quantity: '30', unit: 'g', emoji: '🌰', tip: 'Torréfier légèrement à sec pour plus de goût' },
      { name: 'Parmesan 24 mois', quantity: '40', unit: 'g', emoji: '🧀' },
      { name: 'Pecorino Sardo', quantity: '10', unit: 'g', emoji: '🧀', tip: 'Apporte de la vivacité — équilibre le parmesan' },
      { name: 'Ail', quantity: '1 petite gousse', emoji: '🧄', tip: 'Germe retiré pour moins d\'âpreté' },
      { name: 'Huile d\'olive DOP Ligure', quantity: '80', unit: 'ml', emoji: '🫒', tip: 'Ligure = plus douce, ne concurrence pas le basilic' },
      { name: 'Sel de mer', quantity: '1 pincée', emoji: '🧂' },
    ],
    anecdote: "Le pesto est une appellation protégée (IGP) — le 'Pesto Genovese DOP' doit être fait avec du basilic D.O.P. de la région de Gênes, de l'huile d'olive Riviera Ligure, et du fromage Parmigiano Reggiano ou Pecorino Sardo. Le Campionato Mondiale del Pesto al Mortaio se tient tous les 2 ans à Gênes.",
    chef_tip: "Gardez tous les ingrédients froids et travaillez rapidement. La chaleur du frottement du mortier peut oxyder le basilic. Certains chefs mettent même le mortier au réfrigérateur 30 min avant.",
    cultural_note: "Pesto vient du verbe latin 'pestare' (broyer, pilonner). La Ligurie, avec son célèbre port de Gênes, a diffusé le pesto dans le monde entier via ses marins au XIXe siècle. Les Génois étaient les principaux armateurs méditerranéens.",
  },

  'Les Gnocchi di Patate': {
    title: 'Les Gnocchi di Patate',
    description: 'Gnocchi maison légers comme des nuages',
    duration_minutes: 60,
    difficulty: 'medium',
    ingredients: [
      { name: 'Pommes de terre Bintje ou Russet', quantity: '800', unit: 'g', emoji: '🥔', tip: 'Cuire en robe des champs — jamais à l\'eau, elles absorbent trop d\'eau' },
      { name: 'Farine T55', quantity: '200', unit: 'g', emoji: '🌾', tip: 'Ajustez selon l\'humidité des pommes de terre' },
      { name: 'Jaune d\'œuf', quantity: '1', emoji: '🥚' },
      { name: 'Sel fin', quantity: '1 cc', emoji: '🧂' },
      { name: 'Noix de muscade', quantity: '1 pincée', emoji: '🌰' },
    ],
    anecdote: "Le gnocchi en Italie se prononce 'nyoki'. En dialecte vénitien, 'gnocco' signifie 'bosse' ou 'nœud dans le bois'. Les gnocchi existent depuis le Moyen Âge — avant l'arrivée de la pomme de terre en Europe, ils étaient faits de chapelure, de fromage ou de ricotta.",
    chef_tip: "Le secret : utiliser le moins de farine possible. Trop de farine = gnocchi caoutchouteux. Testez un gnocchi dans l'eau bouillante — s'il remonte en surface et reste ferme 30 secondes, la texture est bonne.",
    cultural_note: "Chaque région italienne a ses gnocchi : gnocchi di zucca (potiron) en Vénétie, strangolapreti (épinards-ricotta) en Toscane, gnocchi alla Sorrentina en Campanie. Les Américains ont adopté le gnocchi et l'ont transformé en plat de comfort food universel.",
  },

  'La Panna Cotta': {
    title: 'La Panna Cotta',
    description: 'Crème cuite, coulis de fruits rouges',
    duration_minutes: 20,
    difficulty: 'easy',
    ingredients: [
      { name: 'Crème liquide entière', quantity: '500', unit: 'ml', emoji: '🥛', tip: '35% MG — ne pas remplacer par de la crème allégée' },
      { name: 'Gélatine', quantity: '6', unit: 'g', emoji: '⬜', tip: 'Ou agar-agar 2g pour une version végane' },
      { name: 'Sucre en poudre', quantity: '60', unit: 'g', emoji: '🍬' },
      { name: 'Gousse de vanille', quantity: '1', emoji: '🌿' },
      { name: 'Coulis de framboises ou fraises', quantity: '200', unit: 'ml', emoji: '🍓' },
    ],
    anecdote: "La panna cotta vient du Piémont et daterait du début du XXe siècle. Contrairement aux idées reçues, c'est un dessert moderne — les premières recettes écrites apparaissent seulement dans les années 1960. Elle a été popularisée internationalement par les restaurants italiens dans les années 1990.",
    chef_tip: "Humidifiez les ramequins avec de l'eau froide avant de verser la panna cotta — elle se démoule plus facilement. Pour tester la texture : la panna cotta doit trembler légèrement comme une panna cotta 'vivante' quand on la touche.",
    cultural_note: "Panna cotta signifie 'crème cuite' en italien. Dans les restaurants haut de gamme, on varie les parfums : café, pistache, citron, fleur d'oranger. La version aux fruits rouges reste la plus populaire dans le monde.",
  },

  'Cacio e Pepe Romaine': {
    title: 'Cacio e Pepe Romaine',
    description: 'Pecorino, poivre noir, pas de crème',
    duration_minutes: 20,
    difficulty: 'hard',
    ingredients: [
      { name: 'Spaghetti ou tonnarelli', quantity: '320', unit: 'g', emoji: '🍝' },
      { name: 'Pecorino Romano DOP', quantity: '150', unit: 'g', emoji: '🧀', tip: 'Râper très finement — comme une neige' },
      { name: 'Poivre noir entier', quantity: '2 cc', emoji: '⚫', tip: 'Concasser grossièrement au mortier — pas moudre finement' },
      { name: 'Eau de cuisson des pâtes', quantity: '150', unit: 'ml', emoji: '💧', tip: 'L\'amide est le liant secret — irremplaçable' },
    ],
    anecdote: "Cacio e pepe est la recette romaine la plus minimaliste et la plus difficile à réussir — seulement 3 ingrédients, mais une technique précise. Le secret est dans la crème de fromage créée par l'amidon de l'eau de cuisson. Une bonne cacio e pepe ne doit JAMAIS contenir de crème fraîche, de beurre ou d'huile.",
    chef_tip: "Faites légèrement griller le poivre concassé à sec dans la poêle pour activer ses arômes. Ajoutez l'eau de cuisson amidonnée, retirez du feu et incorporez le pecorino en remuant vigoureusement pour créer une sauce crémeuse.",
    cultural_note: "Cacio signifie 'fromage' en dialecte romain (du latin 'caseus'). La cacio e pepe est une triade avec l'amatriciana et la gricia — les trois pâtes romaines emblématiques. Elles partagent le même poivre et le même Pecorino Romano, la fierté de Rome.",
  },

  // ── PASTRY ──────────────────────────────────────────────────────────────
  'Les Macarons': {
    title: 'Les Macarons',
    description: 'Tant pour tant, meringue italienne',
    duration_minutes: 90,
    difficulty: 'hard',
    ingredients: [
      { name: 'Poudre d\'amandes blanches', quantity: '150', unit: 'g', emoji: '🌰', tip: 'Mixer et tamiser finement — CRUCIAL' },
      { name: 'Sucre glace', quantity: '150', unit: 'g', emoji: '🍬', tip: 'Tamiser avec la poudre d\'amandes' },
      { name: 'Blancs d\'œufs vieillis (à T°ambiante)', quantity: '110', unit: 'g', emoji: '🥚', tip: 'Séparer 48h avant, garder à température ambiante' },
      { name: 'Sucre en poudre', quantity: '150', unit: 'g', emoji: '🍬' },
      { name: 'Eau', quantity: '50', unit: 'g', emoji: '💧', tip: 'Pour le sirop de sucre' },
      { name: 'Colorant en gel (optionnel)', quantity: 'QS', emoji: '🎨', tip: 'Gel = plus concentré, ne liquéfie pas la pâte' },
    ],
    anecdote: "Le macaron parisien (deux coques réunies par une ganache) est différent du macaron de Nancy ou de Saint-Émilion (une seule coque). Pierre Hermé a révolutionné le macaron en 1997 en créant des saveurs inédites comme Ispahan (rose-litchi-framboise) ou Satine (passion-chocolat). Ses macarons se vendent jusqu'à 3€ pièce.",
    chef_tip: "La clé du macaron : le macaronnage. Mélangez la meringue avec la poudre en écrasant contre les parois jusqu'à ce que la pâte 'coule comme un ruban'. Trop peu : coques bosselées. Trop : coques plates et collantes.",
    cultural_note: "La meringue italienne (avec sirop cuit) est plus stable que la meringue française (sucre à froid). Pour les macarons professionnels, c'est toujours la meringue italienne qui est utilisée, car elle supporte mieux l'humidité.",
  },

  // ── MOROCCAN NEW LESSONS ──────────────────────────────────────────────────
  'Le Couscous Royal': {
    title: 'Le Couscous Royal',
    description: 'Semoule vapeur et légumes mijotés',
    duration_minutes: 90,
    difficulty: 'medium',
    ingredients: [
      { name: 'Semoule fine', quantity: '500', unit: 'g', emoji: '🌾', tip: 'Huiler légèrement avant de rouler — les grains ne colleront pas' },
      { name: 'Agneau épaule', quantity: '600', unit: 'g', emoji: '🍖' },
      { name: 'Merguez', quantity: '8', emoji: '🌭' },
      { name: 'Poulet fermier (morceaux)', quantity: '600', unit: 'g', emoji: '🍗' },
      { name: 'Pois chiches (cuits)', quantity: '400', unit: 'g', emoji: '🫘' },
      { name: 'Carottes, navets, courgettes', quantity: '400', unit: 'g', emoji: '🥕' },
      { name: 'Ras-el-hanout', quantity: '2 cs', emoji: '🫙' },
      { name: 'Harissa', quantity: 'QS', emoji: '🌶️', tip: 'Servie à part — chacun dose selon son goût' },
    ],
    anecdote: "Le couscous a été proclamé patrimoine culturel immatériel de l'UNESCO en 2020, soutenu conjointement par le Maroc, l'Algérie, la Tunisie, la Mauritanie, le Mali, le Niger et la Mauritanie. C'est un patrimoine partagé de l'Afrique du Nord. La semoule se roule traditionnellement à la main — un art qui se transmet de mère en fille.",
    chef_tip: "Le secret du couscous parfait : 3 passages vapeur minimum. Entre chaque passage, roulez la semoule avec les doigts huilés pour séparer les grains. L'eau qui remonte dans le couscoussier doit frémir, pas bouillir violemment.",
    cultural_note: "Le 'Royal' désigne la version avec 3 viandes. Le vendredi est le jour traditionnel du couscous au Maroc — on se réunit en famille après la prière du vendredi. Il se mange toujours en commun, dans un grand plat central.",
  },

  "Le Tajine d'Agneau aux Pruneaux": {
    title: "Le Tajine d'Agneau aux Pruneaux",
    description: 'Viande fondante, sucrée-salée',
    duration_minutes: 120,
    difficulty: 'medium',
    ingredients: [
      { name: 'Épaule d\'agneau en morceaux', quantity: '1.2', unit: 'kg', emoji: '🍖' },
      { name: 'Pruneaux d\'Agen', quantity: '200', unit: 'g', emoji: '🫐' },
      { name: 'Amandes mondées', quantity: '80', unit: 'g', emoji: '🌰' },
      { name: 'Oignons râpés', quantity: '3', emoji: '🧅' },
      { name: 'Safran', quantity: '1 pincée', emoji: '🌸', tip: 'Infuser dans l\'eau chaude' },
      { name: 'Ras-el-hanout', quantity: '2 cs', emoji: '🫙' },
      { name: 'Miel', quantity: '2 cs', emoji: '🍯' },
      { name: 'Cannelle', quantity: '1 bâton', emoji: '🌿' },
    ],
    anecdote: "L'alliance sucré-salé dans la cuisine marocaine vient de l'influence andalouse du Moyen Âge. Les Maures chassés d'Espagne en 1492 ont apporté avec eux des techniques de cuisine raffinées incluant l'utilisation de fruits secs dans les plats de viande — une tradition héritée de la cuisine arabo-persane.",
    chef_tip: "Cuisez à feu très doux (flamme minimale) en couvrant hermétiquement. La condensation dans le couvercle conique du tajine arrose continuellement la viande. Ne soulevez pas le couvercle pendant la cuisson.",
    cultural_note: "Le plat tajine tire son nom du récipient en terre cuite. La forme conique du couvercle est fonctionnelle : la vapeur monte, se condense sur les parois froides et retombe sur les aliments, créant un circuit de cuisson naturel.",
  },

  // ── MEXICAN NEW LESSONS ───────────────────────────────────────────────────
  'Le Guacamole': {
    title: 'Le Guacamole',
    description: 'Avocats, citron vert, coriandre',
    duration_minutes: 10,
    difficulty: 'easy',
    ingredients: [
      { name: 'Avocats Hass bien mûrs', quantity: '3', emoji: '🥑', tip: 'Doit céder sous le pouce — un avocat trop ferme donne un guacamole sans saveur' },
      { name: 'Citron vert', quantity: '2', emoji: '🍋', tip: 'Le jus empêche l\'oxydation et apporte l\'acidité essentielle' },
      { name: 'Coriandre fraîche', quantity: '1 bouquet', emoji: '🌿' },
      { name: 'Oignon blanc', quantity: '1/4', emoji: '🧅', tip: 'Rincé sous l\'eau froide pour adoucir le piquant' },
      { name: 'Piment jalapeño', quantity: '1', emoji: '🌶️' },
      { name: 'Sel fin', quantity: 'QS', emoji: '🧂' },
    ],
    anecdote: "Le guacamole vient de l'aztèque 'ahuacamolli' (ahuacatl = avocat + molli = sauce). Les Aztèques le préparaient au molcajete (mortier de pierre volcanique) il y a plus de 500 ans. L'avocat Hass — la variété de 80% du marché mondial — a été développé par Rudolph Hass, facteur californien, dans les années 1930.",
    chef_tip: "Ne jamais mixer le guacamole — écrasez grossièrement à la fourchette pour garder des morceaux. Le noyau dans le bol ne préserve PAS l'avocat de l'oxydation (mythe). Seul le citron vert et la couverture hermétique le font.",
    cultural_note: "Le Mexique produit 30% des avocats mondiaux — principalement dans la région du Michoacán. La demande mondiale a créé des tensions sociales importantes. La période du Super Bowl américain génère une consommation de 60 000 tonnes de guacamole en un seul week-end.",
  },

  // ── INDIAN NEW LESSONS ────────────────────────────────────────────────────
  'Le Dal Makhani': {
    title: 'Le Dal Makhani',
    description: 'Lentilles noires en sauce crémeuse',
    duration_minutes: 240,
    difficulty: 'medium',
    ingredients: [
      { name: 'Lentilles beluga (urad dal entières)', quantity: '250', unit: 'g', emoji: '⚫', tip: 'Tremper 12h — réduisent le temps de cuisson et améliorent la digestibilité' },
      { name: 'Haricots rouges (rajma)', quantity: '50', unit: 'g', emoji: '🫘' },
      { name: 'Beurre (ghee)', quantity: '60', unit: 'g', emoji: '🧈' },
      { name: 'Tomates (conserve)', quantity: '400', unit: 'g', emoji: '🍅' },
      { name: 'Crème liquide', quantity: '100', unit: 'ml', emoji: '🥛' },
      { name: 'Ail-gingembre pâte', quantity: '2 cs', emoji: '🧄' },
      { name: 'Cumin, coriandre, garam masala', quantity: 'QS', emoji: '🫙' },
    ],
    anecdote: "Le Dal Makhani (makhani = beurre) a été créé par Kundan Lal Gujral au restaurant Moti Mahal de Delhi dans les années 1940. La recette originale cuit les lentilles 24 heures à feu très doux dans un tandoor. Dans les restaurants indiens étoilés, le dal makhani est parfois mijoté 72 heures.",
    chef_tip: "La longue cuisson est la clé : les lentilles doivent mijoter au moins 4 heures à feu très doux, en remuant régulièrement. Le beurre et la crème s'ajoutent en toute fin pour créer la richesse caractéristique.",
    cultural_note: "Le dal makhani est le plat symbole de la cuisine punjabi. Il est aujourd'hui servi dans les restaurants indiens du monde entier. La version végane (sans beurre ni crème) avec du lait de coco est populaire en Occident.",
  },

  // ── BBQ & GRILL ───────────────────────────────────────────────────────────
  'Les Marinades': {
    title: 'Les Marinades',
    description: 'Dry rub, sauce, lacage — les 3 méthodes',
    duration_minutes: 30,
    difficulty: 'easy',
    ingredients: [
      { name: 'Paprika fumé', quantity: '3 cs', emoji: '🫙' },
      { name: 'Cassonade brune', quantity: '2 cs', emoji: '🍬', tip: 'Le sucre crée la croûte caramélisée — le "bark" du BBQ' },
      { name: 'Sel kosher', quantity: '2 cs', emoji: '🧂' },
      { name: 'Poivre noir moulu', quantity: '1 cs', emoji: '⚫' },
      { name: 'Ail en poudre', quantity: '1 cs', emoji: '🧄' },
      { name: 'Cumin moulu', quantity: '1 cs', emoji: '🫙' },
      { name: 'Piment de Cayenne', quantity: '1/2 cc', emoji: '🌶️' },
    ],
    anecdote: "Le BBQ américain est né de la cuisson esclave du Sud des États-Unis au XVIIIe siècle. Les esclaves cuisaient les parties de porc les moins nobles (épaule, ribs, queue) au-dessus de feux lents — une technique héritée d'Afrique de l'Ouest. Ce sont eux qui ont inventé le BBQ tel qu'on le connaît.",
    chef_tip: "Le dry rub doit être appliqué au moins 4 heures avant (idéalement 24h au frigo). Le sel extrait d'abord l'humidité, qui se dissout et réabsorbe les épices — créant une marinade sèche naturelle appelée 'pellicle'.",
    cultural_note: "Les 4 styles régionaux de BBQ américain : Texas (bœuf, sel-poivre), Memphis (porc, dry rub), Kansas City (sauce sucrée), Carolina (vinaigre). Chaque style est une identité culturelle forte, et les débats entre fans sont passionnés.",
  },

  // ── VEGAN ─────────────────────────────────────────────────────────────────
  'Protéines Végétales': {
    title: 'Protéines Végétales',
    description: 'Tofu, tempeh, seitan et légumineuses',
    duration_minutes: 45,
    difficulty: 'easy',
    ingredients: [
      { name: 'Tofu ferme', quantity: '400', unit: 'g', emoji: '⬜', tip: 'Presser 30 min pour retirer l\'eau — sinon le tofu ne colore pas' },
      { name: 'Tempeh', quantity: '200', unit: 'g', emoji: '🟫', tip: 'Blanchir 5 min pour retirer l\'amertume' },
      { name: 'Sauce soja', quantity: '4 cs', emoji: '🫙' },
      { name: 'Huile de sésame', quantity: '2 cs', emoji: '🫗' },
      { name: 'Ail & gingembre', quantity: 'QS', emoji: '🧄' },
      { name: 'Maïzena', quantity: '2 cs', emoji: '⬜', tip: 'Enrober le tofu pour une croûte croustillante' },
    ],
    anecdote: "Le tofu existe depuis plus de 2000 ans en Chine. Selon la légende, il fut découvert par accident quand un chef chinois fit coaguler du lait de soja avec des cristaux de sel naturel. Le tempeh, fermenté à base de soja, est un superaliment d'Indonésie qui précède les études sur les probiotiques de plusieurs siècles.",
    chef_tip: "Le tofu frit croustillant : presser, couper en cubes, enrober de maïzena, frire à 180°C. Le tofu absorbe les saveurs comme une éponge — marinez-le toujours. Le tempeh se mange mariné et grillé ou émietté comme du bœuf haché.",
    cultural_note: "Les légumineuses (lentilles, pois chiches, haricots) contiennent 20-30% de protéines. Associées à une céréale (riz + lentilles = dhal, maïs + haricots = Mexique), elles forment une protéine complète avec tous les acides aminés essentiels.",
  },

  // ── THAI NEW LESSONS ──────────────────────────────────────────────────────
  'Le Pad Thaï': {
    title: 'Le Pad Thaï',
    description: 'Nouilles de riz sautées style Bangkok',
    duration_minutes: 25,
    difficulty: 'medium',
    ingredients: [
      { name: 'Nouilles de riz plates (5mm)', quantity: '200', unit: 'g', emoji: '🍜', tip: 'Tremper 30 min dans l\'eau froide — cuisson directe les rend pâteuses' },
      { name: 'Crevettes ou poulet', quantity: '250', unit: 'g', emoji: '🦐' },
      { name: 'Tofu ferme', quantity: '100', unit: 'g', emoji: '⬜' },
      { name: 'Œufs', quantity: '2', emoji: '🥚' },
      { name: 'Sauce de tamarin concentrée', quantity: '3 cs', emoji: '🫙', tip: 'C\'est l\'ingrédient clé — irremplaçable' },
      { name: 'Sauce poisson (nam pla)', quantity: '3 cs', emoji: '🫙' },
      { name: 'Sucre de palme', quantity: '2 cs', emoji: '🍬' },
      { name: 'Germes de soja, ciboulette, cacahuètes', quantity: 'QS', emoji: '🌱' },
    ],
    anecdote: "Le pad thaï a été inventé dans les années 1940 par le gouvernement thaïlandais pour promouvoir la nationalité thaïe et réduire la consommation de riz pendant une pénurie. Le Premier ministre Plaek Phibunsongkhram a littéralement lancé une campagne nationale pour que chaque citoyen mange du pad thaï. Le patriotisme peut être savoureux.",
    chef_tip: "Le wok doit être à feu maximum et fumant avant d'ajouter les ingrédients. Les nouilles s'ajoutent en dernier avec la sauce. Évitez de trop remuer — laissez les nouilles colorer légèrement. Le citron vert et le sucre de palme servis à table permettent l'ajustement personnel.",
    cultural_note: "En Thaïlande, il existe plus de 500 variantes régionales du pad thaï. La version de Bangkok (la plus connue) est différente des versions du nord (plus épicées) ou du sud (avec plus de fruits de mer). La version 'originale' gouvernementale de 1944 était bien différente de ce qu'on mange aujourd'hui.",
  },

  // ── GREEK NEW LESSONS ────────────────────────────────────────────────────
  'Le Tzatziki': {
    title: 'Le Tzatziki',
    description: 'Yaourt grec, concombre, ail, aneth',
    duration_minutes: 15,
    difficulty: 'easy',
    ingredients: [
      { name: 'Yaourt grec entier épais', quantity: '400', unit: 'g', emoji: '⚪', tip: 'Égoutter dans un linge 2h pour retirer le petit-lait — texture plus onctueuse' },
      { name: 'Concombre', quantity: '1 gros', emoji: '🥒', tip: 'Épépiner et saler 20 min puis presser — sinon le tzatziki sera aqueux' },
      { name: 'Ail', quantity: '2-3 gousses', emoji: '🧄', tip: 'Selon le goût — peut être beaucoup !' },
      { name: 'Huile d\'olive extra vierge', quantity: '3 cs', emoji: '🫒' },
      { name: 'Aneth ou menthe fraîche', quantity: '1 bouquet', emoji: '🌿' },
      { name: 'Vinaigre de vin blanc', quantity: '1 cs', emoji: '🫙' },
    ],
    anecdote: "Le tzatziki vient du turc 'cacık' qui lui-même vient du persan 'zhazh'. Cette sauce voyage avec les civilisations méditerranéennes depuis des siècles. En Inde, le 'raïta' est son équivalent au yaourt de buffle. La même idée (yaourt + légumes + aromates) a émergé indépendamment dans des cultures séparées.",
    chef_tip: "Le concombre doit être impérativement égoutté. Râpez-le, salez, laissez 20 min, puis pressez dans un linge propre — vous retirerez 50% de son eau. Sans cela, le tzatziki sera liquide en 30 minutes.",
    cultural_note: "La Grèce est le premier producteur mondial de yaourt par habitant. Le yaourt grec traditionnel est réalisé avec du lait de brebis ou chèvre, bien plus gras et savoureux que les versions industrielles. Un vrai tzatziki en Grèce peut contenir 6-8 gousses d'ail.",
  },

  // ── CHINESE NEW LESSONS ───────────────────────────────────────────────────
  'Les Dim Sum': {
    title: 'Les Dim Sum',
    description: 'Har gow, siu mai et raviolis vapeur',
    duration_minutes: 90,
    difficulty: 'hard',
    ingredients: [
      { name: 'Farine de blé translucide (wheat starch)', quantity: '200', unit: 'g', emoji: '⬜', tip: 'C\'est ce qui rend la pâte har gow translucide — irremplaçable' },
      { name: 'Fécule de tapioca', quantity: '50', unit: 'g', emoji: '⬜' },
      { name: 'Crevettes crues', quantity: '400', unit: 'g', emoji: '🦐', tip: 'Hacher grossièrement — la texture en morceaux est traditionnelle' },
      { name: 'Bambou en julienne', quantity: '100', unit: 'g', emoji: '🌿' },
      { name: 'Sauce huître', quantity: '2 cs', emoji: '🫙' },
      { name: 'Huile de sésame', quantity: '1 cs', emoji: '🫗' },
      { name: 'Porc haché pour siu mai', quantity: '200', unit: 'g', emoji: '🥩' },
    ],
    anecdote: "Le yum cha ('boire du thé') est une tradition cantonaise du dimanche matin où les familles se réunissent autour de dim sum et de thé. La tradition remonte à 1000 ans sur la Route de la Soie, où les auberges servaient des petites bouchées aux voyageurs avec le thé. Aujourd'hui, les meilleurs restaurants de dim sum à Hong Kong servent jusqu'à 150 variétés.",
    chef_tip: "La pâte har gow se travaille avec de l'eau bouillante (80°C minimum) qui gélatinise l'amidon et crée la translucidité. Elle doit être travaillée rapidement avant de refroidir. Les raviolis se plient avec la technique du plissage (12 plis minimum pour les puristes).",
    cultural_note: "Hong Kong est la capitale mondiale du dim sum. Le restaurant Tim Ho Wan a obtenu une étoile Michelin en 2009 pour ses dim sum à moins de 5 dollars hongkongais (0.60€). C'était à l'époque le restaurant étoilé le moins cher du monde.",
  },
};
