import type { RecipeDetail } from '@/types/database.types';

export const RECIPES: Record<string, RecipeDetail> = {
  'Le Bœuf Bourguignon': {
    lessonTitle: 'Le Bœuf Bourguignon',
    title: 'Bœuf Bourguignon',
    description: 'Le grand classique du braising français — bœuf fondant, sauce au vin rouge intense, lardons et champignons.',
    emoji: '🥩',
    prep_time_min: 30,
    cook_time_min: 180,
    servings: 6,
    difficulty: 'Moyen',
    ingredients: [
      { name: 'Paleron ou joue de bœuf', quantity: '1,5 kg', emoji: '🥩', note: 'Coupé en cubes de 5cm — demandez au boucher' },
      { name: 'Vin rouge de Bourgogne', quantity: '75 cl', emoji: '🍷', note: 'Pinot Noir de préférence — un vin que vous boiriez' },
      { name: 'Lardons fumés', quantity: '200 g', emoji: '🥓' },
      { name: 'Champignons de Paris', quantity: '300 g', emoji: '🍄' },
      { name: 'Carottes', quantity: '3 moyennes', emoji: '🥕', note: 'Coupées en rondelles épaisses' },
      { name: 'Oignons', quantity: '2 gros', emoji: '🧅', note: 'Émincés grossièrement' },
      { name: 'Ail', quantity: '4 gousses', emoji: '🧄' },
      { name: 'Concentré de tomates', quantity: '2 c.s.', emoji: '🍅' },
      { name: 'Farine', quantity: '2 c.s.', emoji: '🌾', note: 'Pour singer la viande' },
      { name: 'Bouillon de bœuf', quantity: '30 cl', emoji: '🫙' },
      { name: 'Bouquet garni (thym, laurier, persil)', quantity: '1', emoji: '🌿' },
      { name: 'Huile de tournesol', quantity: '3 c.s.', emoji: '🫙' },
      { name: 'Beurre', quantity: '30 g', emoji: '🧈' },
      { name: 'Sel et poivre noir', quantity: 'qsp', emoji: '🧂' },
    ],
    steps: [
      'Faites mariner le bœuf dans le vin rouge avec les carottes, oignons, ail et bouquet garni pendant 12h au réfrigérateur (facultatif mais recommandé).',
      'Égouttez la viande, réservez la marinade. Épongez les morceaux avec du papier absorbant — une viande humide ne colore pas.',
      'Dans une cocotte en fonte, faites revenir les lardons à sec jusqu\'à coloration. Réservez.',
      'Dans la même cocotte avec un peu d\'huile à feu vif, saisissez les morceaux de bœuf en 3-4 fois (pas trop en même temps). Ils doivent être bien dorés de toutes parts. Réservez.',
      'Faites revenir les oignons et carottes 5 min à feu moyen. Ajoutez l\'ail et le concentré de tomates, cuisez 2 min.',
      'Remettez la viande dans la cocotte, saupoudrez de farine et mélangez. Cuisez 2 min à feu moyen.',
      'Versez la marinade (ou le vin frais si pas de marinade) et le bouillon. La viande doit être couverte aux 3/4. Ajoutez le bouquet garni.',
      'Portez à ébullition, écumez les impuretés, puis réduisez à feu doux. Couvrez et laissez mijoter 2h30 à 3h.',
      'Pendant ce temps, faites sauter les champignons au beurre jusqu\'à évaporation de leur eau. Réservez.',
      'La viande est prête quand elle s\'effiloche à la fourchette. Retirez le bouquet garni.',
      'Ajoutez les lardons et champignons réservés. Rectifiez l\'assaisonnement. Servez avec des pommes de terre vapeur ou des tagliatelles fraîches.',
    ],
    chef_tip: 'Faites-le la veille — un bourguignon réchauffé est toujours meilleur. La nuit au réfrigérateur permet au collagène de se stabiliser et aux saveurs de se développer. Écumez la graisse solidifiée en surface avant de réchauffer.',
    anecdote: 'Julia Child a popularisé ce plat aux États-Unis avec son livre "Mastering the Art of French Cooking" (1961). Elle y consacre 8 pages. C\'est le plat qui a convaincu des générations d\'Américains que la cuisine française était accessible.',
  },

  'La Ratatouille': {
    lessonTitle: 'La Ratatouille',
    title: 'Ratatouille Provençale',
    description: 'Légumes d\'été confits à l\'huile d\'olive et aux herbes de Provence — chaque légume cuit séparément pour préserver sa texture.',
    emoji: '🍆',
    prep_time_min: 25,
    cook_time_min: 60,
    servings: 4,
    difficulty: 'Facile',
    ingredients: [
      { name: 'Aubergines', quantity: '2 moyennes (600 g)', emoji: '🍆', note: 'Coupées en dés de 2cm' },
      { name: 'Courgettes', quantity: '3 (600 g)', emoji: '🥒', note: 'Coupées en rondelles épaisses' },
      { name: 'Poivrons rouges et jaunes', quantity: '2 (400 g)', emoji: '🫑', note: 'Épépinés, coupés en lanières' },
      { name: 'Tomates bien mûres', quantity: '500 g', emoji: '🍅', note: 'Mondées et concassées, ou 400g de pelées en boîte' },
      { name: 'Oignon', quantity: '1 gros', emoji: '🧅', note: 'Émincé finement' },
      { name: 'Ail', quantity: '4 gousses', emoji: '🧄', note: 'Dégermé, haché' },
      { name: 'Huile d\'olive extra-vierge', quantity: '8 c.s.', emoji: '🫒', note: 'Généreuse — c\'est elle qui lie les légumes' },
      { name: 'Thym frais', quantity: '4 branches', emoji: '🌿' },
      { name: 'Basilic frais', quantity: '1 bouquet', emoji: '🌿', note: 'Ajouté en fin de cuisson' },
      { name: 'Laurier', quantity: '2 feuilles', emoji: '🍃' },
      { name: 'Sel et poivre', quantity: 'qsp', emoji: '🧂' },
    ],
    steps: [
      'Faites dégorger les aubergines : saupoudrez-les de sel, laissez 20 min, puis rincez et épongez. Cela élimine l\'amertume et réduit l\'absorption d\'huile.',
      'Dans une grande poêle avec 2 c.s. d\'huile, faites revenir les aubergines à feu vif jusqu\'à dorées (8 min). Réservez.',
      'Faites de même avec les courgettes (5 min), puis les poivrons (7 min). Réservez chaque légume séparément.',
      'Dans la même poêle avec 2 c.s. d\'huile, faites fondre l\'oignon 5 min à feu doux. Ajoutez l\'ail et cuisez 2 min sans coloration.',
      'Ajoutez les tomates, le thym et le laurier. Salez, cuisez à feu moyen 15 min jusqu\'à obtenir une sauce concentrée.',
      'Remettez tous les légumes dans la casserole. Mélangez délicatement, couvrez et laissez mijoter 20 min à feu doux.',
      'Retirez le couvercle, cuisez encore 10 min pour concentrer les sucs. Rectifiez l\'assaisonnement.',
      'Hors du feu, ajoutez les feuilles de basilic déchirées à la main et un filet d\'huile d\'olive crue. Servez tiède ou à température ambiante.',
    ],
    chef_tip: 'La technique de cuire chaque légume séparément (la ratatouille "niçoise") est plus longue mais donne un résultat infiniment meilleur qu\'une cuisson tout en même temps. Chaque légume a son temps de cuisson idéal — mélangés, certains deviennent bouillie pendant que d\'autres restent crus.',
    anecdote: 'Le film Ratatouille (Pixar, 2007) a mis le chef Auguste Gusteau et son restaurant étoilé au cœur du récit. Le plat que le critique Anton Ego goûte à la fin — qui le ramène en enfance — est une "confit byaldi", version raffinée de la ratatouille inventée par le chef Thomas Keller.',
  },

  'La Tarte Tatin': {
    lessonTitle: 'La Tarte Tatin',
    title: 'Tarte Tatin aux Pommes',
    description: 'Tarte caramélisée renversée — pommes confites dans un caramel beurré, pâte croustillante par-dessus, retournée à la sortie du four.',
    emoji: '🍎',
    prep_time_min: 20,
    cook_time_min: 40,
    servings: 6,
    difficulty: 'Moyen',
    ingredients: [
      { name: 'Pommes Golden ou Reine des Reinettes', quantity: '1,2 kg (8-9 pommes)', emoji: '🍎', note: 'Pelées, épépinées, coupées en 4' },
      { name: 'Sucre semoule', quantity: '150 g', emoji: '🍬', note: 'Pour le caramel' },
      { name: 'Beurre demi-sel', quantity: '80 g', emoji: '🧈', note: 'Le sel accentue le goût du caramel' },
      { name: 'Pâte feuilletée (ou brisée)', quantity: '1 rouleau (230 g)', emoji: '🥐', note: 'Du commerce ou maison — feuilletée pour plus de croustillant' },
      { name: 'Cannelle (facultatif)', quantity: '1 c.c.', emoji: '🟤' },
    ],
    steps: [
      'Préchauffez le four à 190°C. Préparez les pommes : pelez, épépinez, coupez en 4 quartiers réguliers.',
      'Dans une poêle allant au four (ou un moule à tatin en fonte), faites fondre le beurre à feu moyen. Ajoutez le sucre en une couche régulière.',
      'Cuisez à feu moyen sans remuer jusqu\'à obtenir un caramel blond ambré (5-7 min). Le caramel continuera à cuire au four — arrêtez-vous un peu avant la couleur souhaitée.',
      'Hors du feu, disposez les quartiers de pommes debout, serrés les uns contre les autres en cercles concentriques. Ils réduiront à la cuisson — serrez vraiment bien.',
      'Remettez sur feu moyen et cuisez 10 min — les pommes vont commencer à confire et rendre leur jus.',
      'Étalez la pâte en un disque légèrement plus grand que le moule. Posez-la sur les pommes en rentrant les bords autour des fruits (comme un drap de lit).',
      'Enfournez 25-30 min jusqu\'à ce que la pâte soit bien dorée.',
      'Sortez du four et laissez reposer 5 minutes (pas plus — le caramel se solidifie). Posez un plat sur le moule et retournez d\'un geste vif et décidé.',
      'Servez tiède avec une crème fraîche épaisse ou une boule de glace vanille.',
    ],
    chef_tip: 'Le moment du retournement est critique — attendez 5 min (pas plus) après la sortie du four. Avant de retourner, passez un couteau fin tout autour de la pâte pour décoller. Si une pomme reste dans le moule, replacez-la simplement avec une spatule.',
    anecdote: 'La tarte tatin a été créée par accident par les sœurs Stéphanie et Caroline Tatin à leur hôtel de Lamotte-Beuvron (Sologne) vers 1880. Selon la légende, Caroline a oublié la pâte, a posé les pommes directement dans le beurre-sucre, puis a recouvert de pâte en catastrophe. L\'hôtel Tatin existe encore et sert toujours la tarte originale.',
  },

  'Les Crêpes': {
    lessonTitle: 'Les Crêpes',
    title: 'Crêpes Bretonnes Classiques',
    description: 'La pâte à crêpes parfaite — fine, dorée, souple — avec le secret du repos et de la bonne cuisson sur crêpière.',
    emoji: '🥞',
    prep_time_min: 10,
    cook_time_min: 30,
    servings: 4,
    difficulty: 'Facile',
    ingredients: [
      { name: 'Farine T45', quantity: '250 g', emoji: '🌾' },
      { name: 'Œufs', quantity: '3 grands', emoji: '🥚' },
      { name: 'Lait entier', quantity: '50 cl', emoji: '🥛', note: 'Ajoutez progressivement pour éviter les grumeaux' },
      { name: 'Bière blonde (ou eau gazeuse)', quantity: '10 cl', emoji: '🍺', note: 'Secret pour des crêpes légères et aérées' },
      { name: 'Beurre fondu', quantity: '30 g', emoji: '🧈', note: 'Dans la pâte — plus une crêpe sera légèrement beurrée' },
      { name: 'Sucre vanillé', quantity: '1 sachet', emoji: '🍬', note: 'Pour les crêpes sucrées' },
      { name: 'Rhum ou fleur d\'oranger', quantity: '1 c.s.', emoji: '🍶', note: 'Facultatif, arôme traditionnel breton' },
      { name: 'Sel', quantity: '1 pincée', emoji: '🧂' },
      { name: 'Beurre demi-sel (pour la cuisson)', quantity: '50 g', emoji: '🧈' },
    ],
    steps: [
      'Dans un saladier, mettez la farine tamisée en puits. Cassez les œufs au centre et mélangez avec un fouet en partant du centre.',
      'Incorporez le lait progressivement en fouettant pour éviter les grumeaux. La pâte doit être très fluide.',
      'Ajoutez le beurre fondu, la bière, le sucre vanillé, le rhum et le sel. Mélangez.',
      'Laissez reposer la pâte 1h minimum à température ambiante (ou une nuit au réfrigérateur). Le gluten se détend, les crêpes seront plus souples.',
      'Chauffez la crêpière à feu moyen-vif. Frottez avec un morceau de beurre demi-sel sur un essuie-tout.',
      'Versez une louche de pâte (environ 80ml), inclinez la crêpière rapidement pour répartir en couche fine et uniforme.',
      'Cuisez 1-2 min jusqu\'à ce que les bords se décollent et que la surface soit sèche. Retournez avec une spatule fine ou lancez la crêpe.',
      'Cuisez 30 secondes de l\'autre côté. Empiler sur une assiette recouverte d\'un torchon pour garder moelleuses.',
      'Servez avec beurre-sucre, confiture, Nutella, ou garnissez en galettes salées.',
    ],
    chef_tip: 'Pour la première crêpe "test" (ratée par définition) : ne vous découragez pas, c\'est normal. Elle sert à jauger la température et à graisser la poêle. La pâte s\'améliore à partir de la 3ème crêpe quand la poêle est à bonne température.',
    anecdote: 'La Chandeleur (2 février) est la fête des crêpes en France. La tradition veut qu\'on tienne une pièce d\'or dans la main gauche et qu\'on fasse sauter la crêpe de la main droite — si elle retombe bien dans la poêle, la prospérité est assurée pour l\'année. Aujourd\'hui on se contente souvent de la pièce de 1€.',
  },

  'La Quiche Lorraine': {
    lessonTitle: 'La Quiche Lorraine',
    title: 'Quiche Lorraine Authentique',
    description: 'La vraie quiche lorraine : pâte brisée croustillante, appareil crème-œufs onctueux, lardons — sans fromage (c\'est la règle).',
    emoji: '🥧',
    prep_time_min: 25,
    cook_time_min: 45,
    servings: 6,
    difficulty: 'Facile',
    ingredients: [
      { name: 'Pâte brisée maison ou du commerce', quantity: '230 g', emoji: '🥐' },
      { name: 'Lardons fumés', quantity: '200 g', emoji: '🥓', note: 'Poitrines fumées non salées de préférence' },
      { name: 'Crème fraîche épaisse (30% MG)', quantity: '25 cl', emoji: '🫙' },
      { name: 'Lait entier', quantity: '10 cl', emoji: '🥛' },
      { name: 'Œufs entiers', quantity: '3', emoji: '🥚' },
      { name: 'Noix de muscade', quantity: '1 pincée', emoji: '🟤', note: 'Fraîchement râpée — le secret de la vraie lorraine' },
      { name: 'Sel et poivre blanc', quantity: 'qsp', emoji: '🧂' },
    ],
    steps: [
      'Préchauffez le four à 200°C. Foncez un moule à tarte de 28cm avec la pâte brisée. Piquez le fond avec une fourchette.',
      'Réfrigérez 20 min (le froid évite le retrait de la pâte à la cuisson). Couvrez de papier cuisson et de billes de céramique ou haricots secs.',
      'Cuisez à blanc 15 min, retirez les billes et le papier, cuisez encore 5 min. La pâte doit être légèrement dorée.',
      'Pendant ce temps, faites revenir les lardons à sec dans une poêle antiadhésive jusqu\'à légèrement dorés. Égouttez sur papier absorbant.',
      'Fouettez ensemble les œufs, la crème et le lait. Assaisonnez généreusement : sel, poivre blanc, muscade. La muscade est essentielle.',
      'Répartissez les lardons sur le fond de tarte précuit. Versez l\'appareil crème-œufs.',
      'Enfournez à 180°C (baissez le four) pendant 30-35 min. La quiche est cuite quand l\'appareil est pris mais tremble légèrement au centre.',
      'Laissez reposer 10 min avant de démouler et servir. Elle se mange tiède, jamais bouillante.',
    ],
    chef_tip: 'La cuisson à blanc (avec billes) est indispensable pour une pâte croustillante sous l\'appareil humide. Sans cette étape, le fond restera mou et pâteux — le fameux "fond sodden" des Anglais. Pré-cuisez toujours le fond pour une quiche parfaite.',
    anecdote: 'La quiche lorraine originale du XVIe siècle était sucrée — le mot "quiche" vient de "Küchen" (gâteau) en dialecte lorrain. Elle ne contenait pas de lardons mais du pain. La version aux lardons et crème s\'est développée progressivement. L\'ajout de fromage (gruyère) est une adaptation parisienne qui hérisse les Lorrains.',
  },

  'La Carbonara Authentique': {
    lessonTitle: 'La Carbonara Authentique',
    title: 'Pasta alla Carbonara',
    description: 'Rigatoni, guanciale croustillant, pecorino romano, poivre noir et jaunes d\'œufs — zéro crème, zéro lardon, zero compromis.',
    emoji: '🍝',
    prep_time_min: 10,
    cook_time_min: 15,
    servings: 2,
    difficulty: 'Moyen',
    ingredients: [
      { name: 'Rigatoni ou spaghetti', quantity: '200 g', emoji: '🍝' },
      { name: 'Guanciale (joue de porc)', quantity: '150 g', emoji: '🥓', note: 'Coupé en bâtonnets de 1cm — pas de pancetta, pas de lardons' },
      { name: 'Pecorino Romano DOP (finement râpé)', quantity: '80 g', emoji: '🧀', note: 'Ou moitié pecorino moitié parmesan' },
      { name: 'Jaunes d\'œufs', quantity: '4', emoji: '🥚', note: '2 jaunes par personne — les blancs font scrambled eggs' },
      { name: 'Poivre noir (grossièrement moulu)', quantity: '1 c.c. bien remplie', emoji: '⚫', note: 'Fraîchement moulu — le poivre est un ingrédient principal' },
      { name: 'Eau de cuisson des pâtes', quantity: '100 ml réservés', emoji: '💧', note: 'L\'amidon lie la sauce — ne l\'oubliez pas' },
    ],
    steps: [
      'Faites chauffer une grande casserole d\'eau LÉGÈREMENT salée (la sauce est déjà très salée avec le pecorino et le guanciale).',
      'Mélangez les jaunes d\'œufs avec le pecorino râpé et le poivre. Fouettez vigoureusement — la préparation doit être épaisse et crémeuse.',
      'Dans une poêle froide, mettez le guanciale et chauffez progressivement à feu moyen. La graisse doit fondre lentement (8-10 min) pour que les bâtonnets soient croustillants sans brûler.',
      'Quand le guanciale est bien doré, retirez la poêle du feu. Réservez la graisse fondue dans la poêle.',
      'Cuisez les pâtes al dente selon les instructions. Réservez 150ml d\'eau de cuisson avant d\'égoutter.',
      'Ajoutez 2 c.s. de graisse de guanciale dans le mélange œuf-fromage et mélangez.',
      'Versez les pâtes égouttées directement dans la poêle du guanciale (feu éteint depuis 2 min). Mélangez.',
      'Versez le mélange œuf-fromage sur les pâtes. Ajoutez 50ml d\'eau de cuisson. Mélangez vigoureusement — la sauce doit être crémeuse, pas coagulée.',
      'Si trop épais, ajoutez de l\'eau de cuisson cuillère par cuillère. Ajoutez le guanciale, mélangez. Servez IMMÉDIATEMENT avec plus de pecorino et de poivre.',
    ],
    chef_tip: 'La température est l\'ennemie. Si la poêle est trop chaude quand vous ajoutez les œufs, vous obtenez des scrambled eggs. La technique : retirez la poêle du feu, attendez 1-2 min que ça refroidisse légèrement, puis incorporez. L\'eau de cuisson chaude finit de chauffer les œufs doucement.',
    anecdote: 'La carbonara a probablement moins de 80 ans. Après la Seconde Guerre mondiale, les soldats américains avaient du bacon et des œufs en poudre — les Romains les auraient incorporés à des pâtes. La version authentique au guanciale est une interprétation plus tardive et plus noble de cette recette improvisée.',
  },

  'Le Risotto': {
    lessonTitle: 'Le Risotto',
    title: 'Risotto ai Funghi Porcini',
    description: 'Risotto crémeux aux cèpes — le riz arborio cuit dans le bouillon chaud, fini avec la mantecatura beurre-parmesan.',
    emoji: '🍚',
    prep_time_min: 15,
    cook_time_min: 30,
    servings: 4,
    difficulty: 'Moyen',
    ingredients: [
      { name: 'Riz arborio ou carnaroli', quantity: '320 g', emoji: '🍚', note: 'Carnaroli tient mieux la cuisson et pardonne plus les erreurs' },
      { name: 'Cèpes séchés', quantity: '30 g', emoji: '🍄', note: 'Réhydratés 30 min dans 300ml d\'eau chaude — gardez l\'eau de trempage' },
      { name: 'Champignons de Paris frais', quantity: '200 g', emoji: '🍄', note: 'Émincés et sautés séparément au beurre' },
      { name: 'Vin blanc sec', quantity: '15 cl', emoji: '🥂', note: 'Pinot Grigio ou Soave — s\'évapore complètement' },
      { name: 'Bouillon de volaille chaud', quantity: '1,2 L', emoji: '🫙', note: 'Maintenu frémissant à côté — ajouté louche par louche' },
      { name: 'Oignon jaune', quantity: '1 moyen', emoji: '🧅', note: 'Finement haché — il doit fondre, pas colorer' },
      { name: 'Beurre', quantity: '60 g', emoji: '🧈', note: 'Divisé en 2 : 30g pour la cuisson, 30g froid pour la mantecatura' },
      { name: 'Parmigiano-Reggiano', quantity: '80 g', emoji: '🧀', note: 'Fraîchement râpé — jamais de sachet' },
      { name: 'Huile d\'olive', quantity: '2 c.s.', emoji: '🫒' },
      { name: 'Sel et poivre', quantity: 'qsp', emoji: '🧂' },
    ],
    steps: [
      'Réhydratez les cèpes dans 300ml d\'eau chaude 30 min. Égouttez en gardant l\'eau de trempage (filtrez-la, elle est pleine d\'umami). Hachez grossièrement les cèpes.',
      'Faites chauffer le bouillon avec l\'eau de trempage filtrée dans une casserole adjacente. Maintenir à frémissement.',
      'Dans une grande casserole, faites fondre 30g de beurre avec l\'huile. Faites suer l\'oignon 5 min à feu doux sans coloration.',
      'Ajoutez le riz, faites-le \"nacrer\" 2 min en remuant — il doit devenir translucide sur les bords et opaque au centre.',
      'Versez le vin blanc d\'un coup. Remuez jusqu\'à absorption complète.',
      'Ajoutez les cèpes hachés. Commencez à ajouter le bouillon louche par louche (150ml à la fois) en remuant constamment.',
      'Attendez que chaque louche soit presque complètement absorbée avant d\'en ajouter une autre. Cette étape prend 18-20 min.',
      'Goûtez régulièrement : le riz doit être al dente, avec un tout petit point de résistance au centre.',
      'Quand le riz est prêt, retirez du feu. Ajoutez 30g de beurre FROID coupé en dés et le parmesan râpé.',
      'Mantecatura : remuez vigoureusement (ou faites des mouvements de va-et-vient avec la casserole) pendant 1-2 min jusqu\'à consistance crémeuse.',
      'Ajoutez les champignons sautés sur le dessus. Servez immédiatement dans des assiettes chaudes.',
    ],
    chef_tip: 'Le risotto attend personne — c\'est vous qui attendez le risotto. Ne le laissez jamais en plan sur la gazinière. La mantecatura (le movimento finale au beurre froid hors du feu) est l\'étape qui transforme le riz cuit en risotto crémeux. Sans elle, vous avez juste du riz au bouillon.',
    anecdote: 'Le risotto est né à Milan lors d\'un mariage en 1574 — selon la légende, un apprenti verrier du Duomo de Milan a versé par erreur du safran (qu\'il utilisait pour peindre les vitraux) dans un risotto. Le résultat doré a tant plu aux convives que la recette est restée.',
  },

  'Le Tiramisu': {
    lessonTitle: 'Le Tiramisu',
    title: 'Tiramisu Classique',
    description: 'Mascarpone crémeux, café espresso intense, biscuits savoiardi imbibés et cacao amer — le dessert italien le plus aimé du monde.',
    emoji: '☕',
    prep_time_min: 25,
    cook_time_min: 0,
    servings: 6,
    difficulty: 'Facile',
    ingredients: [
      { name: 'Mascarpone', quantity: '500 g', emoji: '🧀', note: 'À température ambiante — plus facile à fouetter' },
      { name: 'Œufs frais (jaunes + blancs séparés)', quantity: '4', emoji: '🥚', note: 'Œufs de qualité, très frais — utilisés crus' },
      { name: 'Sucre semoule', quantity: '100 g', emoji: '🍬', note: 'Divisé : 80g pour les jaunes, 20g pour les blancs' },
      { name: 'Café espresso très fort (refroidi)', quantity: '300 ml', emoji: '☕', note: '4-5 expressos — le café doit être intense' },
      { name: 'Amaretto ou Marsala (facultatif)', quantity: '3 c.s.', emoji: '🍶', note: 'Ajouté au café pour les adultes' },
      { name: 'Savoiardi (biscuits cuillère italiens)', quantity: '300 g (24-28 biscuits)', emoji: '🍪', note: 'Les vrais savoiardi italiens absorbent mieux' },
      { name: 'Cacao en poudre non sucré', quantity: '3 c.s.', emoji: '🍫', note: 'Tamisé sur le dessus — Van Houten ou qualité équivalente' },
    ],
    steps: [
      'Préparez le café très fort et laissez refroidir. Ajoutez l\'amaretto si désiré.',
      'Fouettez les jaunes d\'œufs avec 80g de sucre au batteur électrique pendant 5 min jusqu\'à la "nappe" — le mélange doit blanchir et tomber en ruban épais.',
      'Incorporez le mascarpone aux jaunes fouettés en mélangeant délicatement au fouet à la main. Ne fouettez pas trop.',
      'Montez les blancs en neige ferme avec 20g de sucre (ajouté en 2 fois quand les blancs sont mousseux).',
      'Incorporez les blancs en neige au mélange mascarpone en 3 fois, avec une maryse, en soulevant délicatement. La crème doit rester légère et aérienne.',
      'Trempez rapidement les savoiardi dans le café (1 seconde de chaque côté — ils ne doivent pas se décomposer) et disposez-les en couche dans un plat rectangulaire.',
      'Versez la moitié de la crème mascarpone. Lissez. Faites une deuxième couche de savoiardi imbibés.',
      'Terminez avec la reste de crème. Lissez la surface.',
      'Couvrez de film alimentaire et réfrigérez MINIMUM 6h, idéalement une nuit — le tiramisu est toujours meilleur le lendemain.',
      'Au moment de servir, tamisez généreusement le cacao amer sur toute la surface. Servez froid.',
    ],
    chef_tip: 'Le tiramisu "classique" utilise des œufs crus — choisissez des œufs ultra-frais de confiance. Pour une version pasteurisée, versez le sucre cuit à 121°C sur les jaunes comme une pâte à bombe. Le repos minimum de 6h est non négociable — c\'est ce qui donne la texture qui se tient au découpage.',
    anecdote: '"Tirami sù" signifie "remonte-moi le moral" ou "tire-moi vers le haut" en vénitien. La paternité est disputée entre plusieurs restaurants de Vénétie depuis les années 1960. Le restaurant Le Beccherie à Trévise revendique l\'invention en 1969. En 2017, le tiramisu a été inscrit au Registre des Produits Agroalimentaires Traditionnels d\'Italie.',
  },

  'Le Tajine d\'Agneau': {
    lessonTitle: 'Le Tajine d\'Agneau',
    title: "Tajine d'Agneau aux Pruneaux et Amandes",
    description: 'Agneau fondant cuit longuement dans un tajine en terre cuite, pruneaux confits, amandes dorées et miel — l\'équilibre sucré-salé marocain.',
    emoji: '🍲',
    prep_time_min: 20,
    cook_time_min: 150,
    servings: 4,
    difficulty: 'Moyen',
    ingredients: [
      { name: 'Épaule d\'agneau (désossée)', quantity: '1,2 kg', emoji: '🥩', note: 'Coupée en cubes de 4cm — ou souris d\'agneau entières' },
      { name: 'Pruneaux d\'Agen dénoyautés', quantity: '200 g', emoji: '🍇', note: 'Trempés 30 min dans de l\'eau tiède pour les attendrir' },
      { name: 'Amandes mondées', quantity: '100 g', emoji: '🌰', note: 'Frites dans le beurre jusqu\'à dorées' },
      { name: 'Oignons', quantity: '3 moyens', emoji: '🧅', note: 'Râpés ou finement émincés — fondent dans la sauce' },
      { name: 'Ail', quantity: '3 gousses', emoji: '🧄' },
      { name: 'Gingembre frais râpé', quantity: '1 c.s.', emoji: '🫚' },
      { name: 'Curcuma', quantity: '1 c.c.', emoji: '🟡' },
      { name: 'Cannelle en bâton', quantity: '1', emoji: '🟤' },
      { name: 'Ras-el-hanout', quantity: '1 c.c.', emoji: '🌶️' },
      { name: 'Miel d\'acacia', quantity: '2 c.s.', emoji: '🍯' },
      { name: 'Safran', quantity: '1 pincée', emoji: '🌸', note: 'Infusé dans 3 c.s. d\'eau chaude 15 min' },
      { name: 'Huile d\'olive', quantity: '3 c.s.', emoji: '🫒' },
      { name: 'Beurre', quantity: '30 g', emoji: '🧈' },
      { name: 'Sel et poivre', quantity: 'qsp', emoji: '🧂' },
      { name: 'Eau', quantity: '20 cl', emoji: '💧' },
    ],
    steps: [
      'Faites chauffer l\'huile dans le tajine (ou une cocotte) à feu moyen-vif. Faites dorer les morceaux d\'agneau sur toutes les faces. Réservez.',
      'Dans le même tajine, faites fondre le beurre et faites suer les oignons 10 min à feu doux jusqu\'à translucides.',
      'Ajoutez l\'ail, le gingembre, le curcuma, le ras-el-hanout et le bâton de cannelle. Faites revenir 2 min en remuant.',
      'Remettez l\'agneau dans le tajine. Versez l\'eau et le safran infusé. Salez et poivrez.',
      'Couvrez et laissez cuire 1h30 à 2h à feu très doux (ou au four à 160°C). L\'agneau doit être très fondant.',
      'Pendant ce temps, faites frire les amandes dans le beurre jusqu\'à dorées. Égouttez sur papier absorbant. Réservez.',
      '30 minutes avant la fin, ajoutez les pruneaux égouttés et le miel dans le tajine. Mélangez délicatement.',
      'En fin de cuisson, goûtez la sauce : elle doit être légèrement sucrée-épicée, concentrée et nappante. Rectifiez.',
      'Dressez dans le tajine : disposez les pruneaux autour de la viande, saupoudrez d\'amandes dorées et d\'un peu de cannelle.',
      'Servez avec de la semoule de couscous ou du pain marocain (khobz).',
    ],
    chef_tip: 'La cuisson longue et douce est l\'âme du tajine — ne cherchez pas à accélérer. L\'agneau devient fondant grâce au collagène qui se transforme en gélatine entre 70°C et 90°C. Un feu trop fort rend la viande sèche et coriace.',
    anecdote: 'Le tajine est à la fois le récipient en terre cuite et le plat qu\'il contient. Le couvercle conique crée une circulation de vapeur unique : la vapeur monte, se condense sur le couvercle froid et retombe sur les aliments — un système de cuisson à l\'étouffée auto-arrosant inventé par les Berbères il y a des millénaires.',
  },

  'Les Sushis': {
    lessonTitle: 'Les Sushis',
    title: 'Nigiri et Maki Sushi Maison',
    description: 'Riz à sushi vinaigré, thon et saumon frais en nigiri, maki concombre ou avocat — les bases du sushi à la maison.',
    emoji: '🍱',
    prep_time_min: 45,
    cook_time_min: 20,
    servings: 2,
    difficulty: 'Moyen',
    ingredients: [
      { name: 'Riz japonica à sushi (koshihikari)', quantity: '300 g', emoji: '🍚', note: 'Rincé jusqu\'à eau claire, cuit à la vapeur ou en casserole' },
      { name: 'Vinaigre de riz', quantity: '4 c.s.', emoji: '🫙' },
      { name: 'Sucre', quantity: '2 c.s.', emoji: '🍬' },
      { name: 'Sel', quantity: '1 c.c.', emoji: '🧂' },
      { name: 'Thon rouge (qualité sashimi)', quantity: '150 g', emoji: '🐟', note: 'Préalablement congelé -20°C 24h pour la sécurité alimentaire' },
      { name: 'Saumon atlantique (qualité sashimi)', quantity: '150 g', emoji: '🐠', note: 'Même précaution de congélation' },
      { name: 'Feuilles de nori', quantity: '4 feuilles', emoji: '🟩', note: 'Pour les maki' },
      { name: 'Concombre japonais', quantity: '1/2', emoji: '🥒', note: 'Taille-le en julienne fine pour les maki' },
      { name: 'Avocat mûr', quantity: '1', emoji: '🥑' },
      { name: 'Wasabi', quantity: 'qsp', emoji: '💚' },
      { name: 'Sauce soja japonaise (Kikkoman)', quantity: 'qsp', emoji: '🫙' },
      { name: 'Gingembre mariné (gari)', quantity: 'qsp', emoji: '🌸' },
    ],
    steps: [
      'Rincez le riz 6-7 fois jusqu\'à ce que l\'eau soit claire. Cuisez avec 360ml d\'eau (ratio 1:1,2) : portez à ébullition, couvrez, cuisez 12 min à feu très doux, retirez du feu 10 min sans ouvrir.',
      'Mélangez vinaigre de riz, sucre et sel. Chauffez légèrement pour dissoudre (sans bouillir).',
      'Transférez le riz dans un saladier en bois (hangiri). Versez l\'assaisonnement vinaigré, mélangez avec une spatule en coupant (mouvement comme une spatule, pas en tournant). Ventilez avec un éventail pour refroidir rapidement. Le riz doit briller.',
      'Pour les nigiri : mouillez vos mains avec de l\'eau vinaigrée (tezu). Prenez 15-18g de riz (une bouchée), formez un ovale compact de 3-4 pressions fermes. Posez une tranche de poisson (5-6g) par-dessus, pressez légèrement.',
      'Pour les maki : posez une demi-feuille de nori sur la natte (makisu). Étalez 120g de riz en couche fine en laissant 2cm en haut. Posez la garniture en ligne à 1/3 du bas.',
      'Roulez fermement en commençant par le bas, en vous aidant de la natte. Pressez bien à chaque tour. Scellez le bord avec un peu d\'eau.',
      'Coupez les maki avec un couteau mouillé : 8 pièces par rouleau. Essuyez la lame entre chaque coupe.',
      'Servez avec sauce soja, wasabi et gari (gingembre). Le wasabi se place sous le poisson sur le nigiri — pas dans la sauce soja.',
    ],
    chef_tip: 'La température du riz est cruciale : il doit être utilisé à température ambiante légèrement au-dessus (35-38°C, proche de la chaleur corporelle). Trop chaud, il cuit le poisson. Trop froid, il est compact et collant. Ne réfrigérez jamais le riz à sushi — il durcit irrémédiablement.',
    anecdote: 'Le sushi "moderne" (nigiri avec poisson cru) ne date que du début du XIXe siècle à Edo (Tokyo). Avant, le sushi était un plat fermenté (narezushi) où le poisson était conservé des mois dans le riz. Le nigiri était alors de la "fast food" de rue — servi rapidement dans les yatai (stands) du Japon pré-industriel.',
  },

  'Le Dashi': {
    lessonTitle: 'Le Dashi',
    title: 'Dashi Ichiban (Premier Bouillon)',
    description: 'Le bouillon fondateur de la cuisine japonaise — kombu et katsuobushi infusés pour un umami pur, délicat et profond.',
    emoji: '🍵',
    prep_time_min: 5,
    cook_time_min: 20,
    servings: 4,
    difficulty: 'Facile',
    ingredients: [
      { name: 'Kombu séché', quantity: '20 g (15x10cm)', emoji: '🟩', note: 'Essuyez avec un chiffon humide — ne lavez pas, la poudre blanche (mannitol) est l\'umami' },
      { name: 'Katsuobushi (flocons de bonite)', quantity: '20 g', emoji: '🟤', note: 'Flocons fins pour un dashi clair' },
      { name: 'Eau froide (eau de source idéalement)', quantity: '1 litre', emoji: '💧', note: 'L\'eau est le principal ingrédient — qualité essentielle' },
    ],
    steps: [
      'Placez le kombu dans l\'eau froide dans une casserole. Laissez tremper 30 min à 1h (facultatif mais recommandé — extrait plus de saveur à froid).',
      'Chauffez à feu moyen. Observez le kombu : des petites bulles vont se former autour de lui. Quand l\'eau atteint 60-65°C (frémissement très léger), retirez le kombu.',
      'Ne laissez JAMAIS bouillir avec le kombu — l\'amertume et la viscosité du kombu se libèrent à l\'ébullition.',
      'Portez l\'eau à ébullition (sans le kombu). Retirez du feu.',
      'Ajoutez les flocons de katsuobushi d\'un coup. Ne remuez pas. Laissez infuser 2-3 minutes.',
      'Filtrez délicatement à travers une passoire fine ou un torchon propre. Ne pressez pas — un dashi pressé devient trouble et amer.',
      'Le dashi ichiban est prêt. Utilisez immédiatement ou conservez 3 jours au réfrigérateur. Vous pouvez aussi congeler en glaçons.',
      'Les restes de kombu et katsuobushi servent à faire le "niban dashi" (second bouillon, moins délicat) ou peuvent être hachés et sautés comme condiment (furikake).',
    ],
    chef_tip: 'La règle d\'or du dashi : la température. Un dashi parfait ne bout jamais. Investissez dans un thermomètre de cuisine — ça change tout. À 60°C, le kombu libère ses saveurs délicates ; au-delà, il libère de l\'amertume. Le katsuobushi infuse à 80°C, pas à ébullition complète.',
    anecdote: 'Le dashi contient les deux principales sources d\'umami naturel : l\'acide glutamique du kombu et l\'inosinate de la bonite. Cette combinaison synergique (les deux ensemble amplifient l\'umami 8 fois plus que chacun séparément) a été découverte scientifiquement en 1960. Les Japonais la pratiquaient empiriquement depuis des siècles.',
  },

  'Le Ramen': {
    lessonTitle: 'Le Ramen',
    title: 'Ramen Shoyu Maison',
    description: 'Bouillon de poulet et sauce soja (shoyu), chashu de porc, œuf mariné, nori et ciboulette — version accessible du ramen maison.',
    emoji: '🍜',
    prep_time_min: 60,
    cook_time_min: 240,
    servings: 4,
    difficulty: 'Expert',
    ingredients: [
      { name: 'Carcasses de poulet', quantity: '2 kg', emoji: '🦴', note: 'Blanchies 5 min, rincées à l\'eau froide avant cuisson' },
      { name: 'Poitrine de porc (chashu)', quantity: '600 g', emoji: '🥩', note: 'Roulée serrée et ficelée' },
      { name: 'Sauce soja', quantity: '10 cl', emoji: '🫙' },
      { name: 'Mirin', quantity: '5 cl', emoji: '🍶' },
      { name: 'Saké de cuisine', quantity: '5 cl', emoji: '🍶' },
      { name: 'Sucre', quantity: '1 c.s.', emoji: '🍬' },
      { name: 'Oignons verts', quantity: '4', emoji: '🌿', note: 'Blancs pour le bouillon, verts pour garnir' },
      { name: 'Gingembre frais', quantity: '30 g', emoji: '🫚', note: 'En tranches pour le bouillon' },
      { name: 'Ail', quantity: '6 gousses', emoji: '🧄' },
      { name: 'Œufs', quantity: '4', emoji: '🥚', note: 'Pour les ajitsuke tamago (œufs marinés)' },
      { name: 'Nouilles ramen fraîches', quantity: '400 g', emoji: '🍜' },
      { name: 'Nori', quantity: '4 feuilles', emoji: '🟩' },
      { name: 'Huile de sésame', quantity: '2 c.c.', emoji: '🌰' },
    ],
    steps: [
      'CHASHU : roulez la poitrine serrée, ficelez. Dans une casserole, faites dorer de tous côtés. Ajoutez soja, mirin, saké, sucre et 20cl d\'eau. Cuisez à couvert à feu doux 2h en retournant toutes les 30 min. Réfrigérez dans la sauce.',
      'ŒUFS MARINÉS : faites bouillir les œufs 6 min 30. Plongez dans l\'eau glacée 5 min. Pelez. Faites mariner 12h dans 5cs soja + 3cs mirin + 10cl eau.',
      'BOUILLON : blanchissez les carcasses dans de l\'eau bouillante 5 min. Rincez abondamment à l\'eau froide (élimine impuretés et odeur).',
      'Mettez les carcasses rincées dans une grande casserole avec 3L d\'eau froide. Ajoutez gingembre, oignons verts (blancs), ail. Portez à ébullition.',
      'Maintenez à ébullition modérée (pas à gros bouillons) 3h. Écumez les premières 30 min. Le bouillon va réduire et se concentrer.',
      'Filtrez le bouillon. Vous obtenez environ 1,5L. Assaisonnez avec sauce soja (tare) : commencez avec 3cs et ajustez.',
      'ASSEMBLAGE : cuisez les nouilles séparément selon les instructions. Égouttez.',
      'Chauffez le bouillon à ébullition. Répartissez les nouilles dans les bols. Versez le bouillon brûlant.',
      'Garnissez : tranches de chashu réchauffées à la poêle, œuf coupé en 2, nori, oignons verts ciselés, filet de sésame.',
    ],
    chef_tip: 'Le ramen est une recette en 3 composants distincts à maîtriser séparément : le bouillon (tsuyu), la sauce d\'assaisonnement (tare) et les garnitures (toppings). Commencez par maîtriser l\'un, puis les autres. Le shoyu ramen est le plus accessible — son bouillon de poulet clair est plus facile à réussir que le tonkotsu (os de porc).',
    anecdote: 'Le ramen instantané a été inventé le 25 août 1958 par Momofuku Ando. Après des mois de recherche dans son hangar, il a mis au point le premier "Chicken Ramen" séché. Il a ensuite inventé le cup noodle en 1971 pour les voyages spatiaux. Ses produits ont nourri des générations dans le monde entier. Il est mort à 96 ans, ayant mangé du ramen presque chaque jour de sa vie.',
  },

  'Les Gyoza': {
    lessonTitle: 'Les Gyoza',
    title: 'Gyoza Yaki-Mushi (Poêlés-Vapeur)',
    description: 'Raviolis japonais croustillants en dessous et fondants au-dessus — farce porc-chou-gingembre, sauce ponzu-sésame.',
    emoji: '🥟',
    prep_time_min: 60,
    cook_time_min: 15,
    servings: 4,
    difficulty: 'Moyen',
    ingredients: [
      { name: 'Galettes de gyoza rondes', quantity: '30 pièces', emoji: '⚪', note: 'Du commerce (rayon réfrigéré épicerie asiatique) — plus régulières que maison' },
      { name: 'Porc haché (20% matière grasse)', quantity: '250 g', emoji: '🥩', note: 'Gras essentiel pour une farce juteuse' },
      { name: 'Chou chinois (ou chou blanc)', quantity: '200 g', emoji: '🥬', note: 'Haché très finement, puis salé et pressé pour extraire l\'eau' },
      { name: 'Ciboule (oignons verts)', quantity: '4 tiges', emoji: '🌿', note: 'Finement ciselée' },
      { name: 'Gingembre frais', quantity: '15 g', emoji: '🫚', note: 'Râpé finement' },
      { name: 'Ail', quantity: '2 gousses', emoji: '🧄', note: 'Pressé' },
      { name: 'Sauce soja', quantity: '1 c.s.', emoji: '🫙' },
      { name: 'Huile de sésame toastée', quantity: '1 c.s.', emoji: '🌰' },
      { name: 'Poivre blanc', quantity: '1/2 c.c.', emoji: '⚪' },
      { name: 'Huile neutre (pour la cuisson)', quantity: '2 c.s.', emoji: '🫙' },
      { name: 'Eau (pour la cuisson vapeur)', quantity: '70 ml', emoji: '💧' },
      { name: 'SAUCE : sauce soja + vinaigre de riz', quantity: '2cs + 1cs', emoji: '🫙' },
      { name: 'SAUCE : huile de chili (rayu)', quantity: 'quelques gouttes', emoji: '🌶️' },
    ],
    steps: [
      'Hachez le chou très finement. Saupoudrez de sel, mélangez et laissez 10 min. Pressez fortement dans un torchon pour extraire toute l\'eau (étape cruciale).',
      'Mélangez porc haché, chou essoré, ciboule, gingembre, ail, sauce soja, huile de sésame et poivre blanc. Mélangez vigoureusement à la main jusqu\'à texture collante et homogène.',
      'Remplissez un bol d\'eau. Posez une galette dans votre paume. Placez une c.c. rase de farce au centre.',
      'Mouillez le bord de la galette. Pliez en deux et scellez le centre. Faites 5-6 petits plis "plissés" sur le bord avant, en pinçant vers le bord arrière lisse.',
      'Déposez les gyoza pliés sur un plateau fariné en les gardant droits, côté plié vers le haut.',
      'Dans une poêle antiadhésive froide, versez l\'huile. Disposez les gyoza côte à côte, côté plat vers le bas. Chauffez à feu moyen-vif.',
      'Cuisez 2-3 min jusqu\'à ce que le fond soit doré et croustillant (levez un coin pour vérifier).',
      'Versez 70ml d\'eau FROIDE dans la poêle et couvrez IMMÉDIATEMENT avec un couvercle. Cuisez à la vapeur 5-6 min jusqu\'à absorption complète de l\'eau.',
      'Retirez le couvercle, cuisez encore 1-2 min pour recrisoer le fond. Servez immédiatement côté croustillant vers le haut.',
      'Mélangez sauce soja + vinaigre de riz + rayu pour la sauce d\'accompagnement.',
    ],
    chef_tip: 'Le secret du pliage : n\'essayez pas de faire des plis parfaits au début. Concentrez-vous sur l\'étanchéité — un gyoza bien scellé qui "explose" à la cuisson n\'est pas récupérable. 3-4 plis simples mais solides valent mieux que 7 plis beaux mais qui laissent passer la farce.',
    anecdote: 'Les gyoza japonais sont légèrement différents des jiaozi chinois dont ils descendent : pâte plus fine, plus d\'ail et de gingembre, technique de cuisson mixte poêle-vapeur (yaki-mushi) spécifique. La ville de Utsunomiya au Japon se dispute avec Hamamatsu le titre de "capitale nationale du gyoza". La consommation annuelle par habitant est suivie officiellement.',
  },

  'Le Curry Butter Chicken': {
    lessonTitle: 'Le Curry Butter Chicken',
    title: 'Murgh Makhani (Butter Chicken)',
    description: 'Poulet tandoori nappé d\'une sauce tomate-crème-épices veloutée — le curry indien le plus populaire dans le monde.',
    emoji: '🍛',
    prep_time_min: 30,
    cook_time_min: 45,
    servings: 4,
    difficulty: 'Moyen',
    ingredients: [
      { name: 'Hauts de cuisse de poulet (désossés)', quantity: '800 g', emoji: '🍗', note: 'La cuisse reste juteuse au four — le blanc sèche' },
      { name: 'Yaourt nature entier (marinade)', quantity: '150 g', emoji: '🥛' },
      { name: 'Tandoori masala', quantity: '2 c.s.', emoji: '🌶️' },
      { name: 'Garam masala', quantity: '1 c.s.', emoji: '🌶️' },
      { name: 'Tomates en boîte (pelées)', quantity: '400 g', emoji: '🍅', note: 'Base de la sauce makhani' },
      { name: 'Crème fraîche entière', quantity: '15 cl', emoji: '🫙' },
      { name: 'Beurre', quantity: '60 g', emoji: '🧈', note: '"Makhani" signifie "au beurre" en hindi' },
      { name: 'Oignon', quantity: '1 gros', emoji: '🧅', note: 'Finement émincé' },
      { name: 'Ail', quantity: '4 gousses', emoji: '🧄' },
      { name: 'Gingembre frais', quantity: '20 g', emoji: '🫚', note: 'Râpé' },
      { name: 'Cardamome (gousses)', quantity: '3', emoji: '🟢' },
      { name: 'Clous de girofle', quantity: '3', emoji: '🟤' },
      { name: 'Cumin (grains)', quantity: '1 c.c.', emoji: '🟤' },
      { name: 'Piment de Cayenne', quantity: '1/2 c.c.', emoji: '🌶️', note: 'Ajustez selon votre tolérance' },
      { name: 'Fenugrec (kasuri methi)', quantity: '1 c.c.', emoji: '🌿', note: 'Feuilles séchées — le secret du vrai butter chicken' },
      { name: 'Sucre ou miel', quantity: '1 c.c.', emoji: '🍬', note: 'Pour équilibrer l\'acidité des tomates' },
    ],
    steps: [
      'MARINADE : mélangez yaourt, tandoori masala, la moitié du garam masala, sel et jus de citron. Enrobez le poulet et réfrigérez 4h minimum (une nuit idéalement).',
      'Cuisez le poulet mariné au four à 220°C en grill pendant 15-20 min (ou faites griller en poêle-gril très chaude). Le poulet doit avoir des marques de grill et être légèrement carbonisé sur les bords. Coupez en morceaux.',
      'Dans une grande casserole, faites chauffer le beurre à feu moyen. Ajoutez cardamome, clous et cumin — attendez qu\'ils crépitent (30 sec).',
      'Ajoutez l\'oignon et faites-le dorer à feu moyen-vif 10-12 min jusqu\'à brun doré (caramélisé, pas brûlé). C\'est cette couleur qui donne la profondeur à la sauce.',
      'Ajoutez ail et gingembre, cuisez 2 min. Ajoutez le piment et le reste du garam masala, cuisez 1 min.',
      'Ajoutez les tomates. Cuisez à feu moyen 15-20 min jusqu\'à très concentrée et que l\'huile remonte en surface (signe que les tomates sont bien cuites).',
      'Mixez finement la sauce (mixeur plongeant ou blender). Passez au tamis pour une texture ultra-lisse si désiré.',
      'Remettez la sauce dans la casserole. Ajoutez le kasuri methi (froissé entre vos doigts pour libérer le parfum) et le sucre.',
      'Incorporez la crème. Goûtez, rectifiez sel et épices. Ajoutez le poulet grillé.',
      'Cuisez encore 10 min à feu doux pour que le poulet s\'imprègne de la sauce. Servez avec du riz basmati et du naan.',
    ],
    chef_tip: 'Le kasuri methi (feuilles de fenugrec séchées) est l\'ingrédient secret du butter chicken authentique. Son parfum légèrement amer-épicé est la signature des vrais restaurants indiens. Sans lui, le butter chicken est bon — avec lui, il est authentique.',
    anecdote: 'Le butter chicken a été créé vers 1950 au restaurant Moti Mahal de Delhi par Kundan Lal Gujral. Il cherchait à utiliser les restes de poulet tandoori du soir. Sa sauce tomate-crème-beurre pour enrober ces restes est devenue le curry le plus commandé dans les restaurants indiens du monde entier.',
  },

  'Le Guacamole': {
    lessonTitle: 'Le Guacamole',
    title: 'Guacamole Mexicain Authentique',
    description: 'Avocats écrasés grossièrement au molcajete, tomate, coriandre, lime et jalapeño — texture rustique, saveur fraîche.',
    emoji: '🥑',
    prep_time_min: 10,
    cook_time_min: 0,
    servings: 4,
    difficulty: 'Facile',
    ingredients: [
      { name: 'Avocats mûrs (Hass)', quantity: '3 gros', emoji: '🥑', note: 'Mûrs mais fermes — pas mousseux. Test : légère pression sans enfoncer' },
      { name: 'Lime (citron vert)', quantity: '1,5', emoji: '🍋', note: 'Jus frais pressé — pas de jus en bouteille' },
      { name: 'Oignon blanc', quantity: '1/4', emoji: '🧅', note: 'Haché très finement — rincer à l\'eau froide pour moins d\'âcreté' },
      { name: 'Piment jalapeño (ou serrano)', quantity: '1', emoji: '🌶️', note: 'Épépiné pour moins de piquant, gardez les graines pour plus' },
      { name: 'Coriandre fraîche', quantity: '3 c.s.', emoji: '🌿', note: 'Feuilles et tiges finement hachées' },
      { name: 'Tomate mûre', quantity: '1 petite', emoji: '🍅', note: 'Épépinée, coupée en dés de 5mm' },
      { name: 'Sel (de mer)', quantity: '1/2 c.c.', emoji: '🧂' },
      { name: 'Ail (facultatif)', quantity: '1/2 gousse', emoji: '🧄', note: 'Non traditionnel au Mexique mais largement utilisé' },
    ],
    steps: [
      'Coupez les avocats en deux, retirez le noyau. Avec une cuillère, scoop la chair directement dans le molcajete (mortier mexicain) ou un saladier.',
      'Ajoutez le sel et la moitié du jus de lime. Écrasez grossièrement avec une fourchette ou le pilon — gardez de la texture, ne mixez pas.',
      'Ajoutez l\'oignon rincé, le jalapeño haché, la coriandre. Mélangez délicatement.',
      'Ajoutez la tomate en dés. Mélangez.',
      'Goûtez : ajustez le sel, le jus de lime (équilibre acide), le piment (chaleur). Un bon guacamole doit être légèrement acide, légèrement pimenté, très savoureux.',
      'Servez immédiatement avec des chips de tortilla maison ou du commerce.',
    ],
    chef_tip: 'Pour un guacamole qui ne noircit pas : l\'oxydation vient du contact avec l\'air, pas du jus de citron (mythe). L\'astuce : pressez un film alimentaire directement sur la surface du guacamole, sans bulle d\'air. Conservez 24h maximum. Le noyau dans le guacamole ne sert à rien.',
    anecdote: 'Le guacamole existe depuis plus de 500 ans. Les Aztèques l\'appelaient "ahuacamolli" (sauce d\'avocat). Hernán Cortés l\'a découvert en 1519 et en a rapporté la recette en Espagne. L\'avocat Hass — la variété la plus cultivée au monde — a été développé en Californie dans les années 1920 par le facteur Rudolph Hass, qui a planté un noyau et obtenu un arbre aux fruits exceptionnels.',
  },

  'Les Tacos al Pastor': {
    lessonTitle: 'Les Tacos al Pastor',
    title: 'Tacos al Pastor',
    description: 'Porc mariné aux épices et ancho, cuit à la broche style libanais, servi avec ananas, coriandre et oignon sur tortilla de maïs.',
    emoji: '🌮',
    prep_time_min: 30,
    cook_time_min: 45,
    servings: 4,
    difficulty: 'Moyen',
    ingredients: [
      { name: 'Porc (épaule ou échine), tranches fines', quantity: '800 g', emoji: '🥩', note: 'Demandez au boucher de trancher finement (3-4mm)' },
      { name: 'Piments ancho séchés', quantity: '3', emoji: '🌶️', note: 'Réhydratés 20 min dans l\'eau chaude, épépinés' },
      { name: 'Piments guajillo séchés', quantity: '3', emoji: '🌶️', note: 'Même traitement' },
      { name: 'Vinaigre de cidre', quantity: '3 c.s.', emoji: '🫙' },
      { name: 'Achiote (annatto) en pâte', quantity: '1 c.s.', emoji: '🟠', note: 'Donne la couleur rouge caractéristique' },
      { name: 'Ail', quantity: '4 gousses', emoji: '🧄' },
      { name: 'Cumin moulu', quantity: '1 c.c.', emoji: '🟤' },
      { name: 'Origan mexicain séché', quantity: '1 c.c.', emoji: '🌿' },
      { name: 'Ananas frais', quantity: '200 g', emoji: '🍍', note: 'En tranches et en dés pour servir' },
      { name: 'Tortillas de maïs (6-8cm)', quantity: '16', emoji: '🫓', note: 'Réchauffées sur comal ou poêle sèche' },
      { name: 'Oignon blanc', quantity: '1', emoji: '🧅', note: 'Finement haché pour garnir' },
      { name: 'Coriandre fraîche', quantity: '1 bouquet', emoji: '🌿' },
      { name: 'Lime', quantity: '2', emoji: '🍋' },
      { name: 'Salsa verde ou rouge', quantity: 'qsp', emoji: '🟢' },
    ],
    steps: [
      'Réhydratez les piments ancho et guajillo dans l\'eau bouillante 20 min. Égouttez.',
      'Mixez les piments réhydratés avec l\'ail, vinaigre, achiote, cumin, origan, sel et 2 tranches d\'ananas. Vous obtenez la marinade rouge pastor.',
      'Enrobez les tranches de porc de marinade. Laissez mariner 4h minimum (une nuit au réfrigérateur idéalement).',
      'VERSION FOUR (à défaut de broche) : empilez les tranches marinées dans un plat. Couvrez et cuisez 30 min à 180°C. Découvrez et cuisez 15 min à 220°C pour caraméliser.',
      'VERSION POÊLE : faites griller les tranches 2-3 min par face dans une poêle très chaude avec peu d\'huile, en portions. Hachez grossièrement les tranches cuites.',
      'Chauffez les tortillas sur comal ou poêle sèche jusqu\'à légèrement dorées et souples (30 sec par face).',
      'Assemblage : 2 tortillas superposées par taco (tradition mexicaine). Porc haché chaud, quelques dés d\'ananas frais, oignon, coriandre.',
      'Arrosez de jus de lime et ajoutez la salsa. Mangez immédiatement.',
    ],
    chef_tip: 'La superposition de 2 tortillas est la coutume mexicaine pour les tacos al pastor — la chaleur et le jus détrempent vite une seule tortilla. Avec deux, la première absorbe les jus et la seconde reste structurée. En bonus, si la première se déchire, la seconde vous protège.',
    anecdote: 'Les tacos al pastor sont directement inspirés du shawarma libanais. Au début du XXe siècle, des immigrants libanais au Mexique ont apporté leur technique de cuisson à la broche verticale (shawarma d\'agneau). Les Mexicains ont adapté avec du porc et des épices locales (achiote, piments). Le mot "pastor" vient de "pasteur" — une référence aux bergers chrétiens libanais qui grillaient la viande.',
  },

  'Le Pad Thaï': {
    lessonTitle: 'Le Pad Thaï',
    title: 'Pad Thaï Authentique',
    description: 'Nouilles de riz sautées au wok, crevettes, tofu, œuf, cacahuètes, germes de soja et sauce tamarin — le plat national thaïlandais.',
    emoji: '🍝',
    prep_time_min: 20,
    cook_time_min: 15,
    servings: 2,
    difficulty: 'Moyen',
    ingredients: [
      { name: 'Nouilles de riz plates (sen lek, 3mm)', quantity: '200 g', emoji: '🍜', note: 'Trempées dans l\'eau froide 30 min, PAS cuites — elles finissent au wok' },
      { name: 'Crevettes (ou poulet ou tofu)', quantity: '200 g', emoji: '🍤', note: 'Décortiquées' },
      { name: 'Tofu ferme', quantity: '100 g', emoji: '⬜', note: 'Pressé, coupé en dés de 1cm, frit jusqu\'à doré' },
      { name: 'Œufs', quantity: '2', emoji: '🥚' },
      { name: 'Germes de soja frais', quantity: '100 g', emoji: '🌱' },
      { name: 'Ciboule (oignons verts)', quantity: '3 tiges', emoji: '🌿' },
      { name: 'Cacahuètes grillées non salées', quantity: '50 g', emoji: '🥜', note: 'Grossièrement concassées' },
      { name: 'SAUCE : pâte de tamarin', quantity: '2 c.s.', emoji: '🟤', note: 'Diluée dans 2 c.s. d\'eau chaude' },
      { name: 'SAUCE : sauce de poisson (nam pla)', quantity: '2 c.s.', emoji: '🫙' },
      { name: 'SAUCE : sucre de palme (ou cassonade)', quantity: '1 c.s.', emoji: '🟤' },
      { name: 'SAUCE : sauce sriracha ou piment', quantity: '1 c.c.', emoji: '🌶️' },
      { name: 'Huile de tournesol', quantity: '3 c.s.', emoji: '🫙', note: 'Wok doit être très chaud' },
      { name: 'Lime', quantity: '1', emoji: '🍋', note: 'Indispensable pour servir' },
    ],
    steps: [
      'Préparez la sauce : mélangez tamarin dilué, sauce de poisson, sucre de palme et sriracha. Goûtez — équilibrez les 4 saveurs (acide, salé, sucré, pimenté).',
      'Faites tremper les nouilles dans l\'eau froide 30 min. Égouttez bien.',
      'Chauffez le wok à feu maximum jusqu\'à fumée. Ajoutez 2 c.s. d\'huile.',
      'Sautez les crevettes (ou poulet) 1-2 min jusqu\'à cuits. Poussez sur le côté.',
      'Ajoutez le tofu frit, mélangez brièvement. Ajoutez les nouilles égouttées.',
      'Versez la sauce sur les nouilles. Mélangez et cuisez 1-2 min à feu vif — les nouilles absorbent la sauce.',
      'Poussez tout sur le côté. Cassez les œufs dans le wok, brouilllez 20 secondes, puis incorporez aux nouilles.',
      'Ajoutez la moitié des germes de soja et les blancs de ciboule. Cuisez 30 secondes en mélangeant.',
      'Servez immédiatement. Garnissez de cacahuètes, germes de soja restants, ciboule verte, quartier de lime.',
      'À table : pressez la lime, ajoutez sucre, piment séché, vinaigre selon votre goût (les 4 condiments traditionnels).',
    ],
    chef_tip: 'Cuisez en portion individuelle — deux portions au wok maximum. Trop de contenu dans le wok fait chuter la température et donne un pad thaï bouilli au lieu de sauté. Le secret du pad thaï de rue est la chaleur extrême du wok à gaz haute puissance. À la maison, chauffez au maximum et cuisez vite.',
    anecdote: 'Le pad thaï a été "inventé" en 1938 sur ordre du Premier ministre Phibunsongkhram pour unifier la nation autour d\'un plat national. Il a financé des stands de pad thaï partout dans le pays et lancé des campagnes publicitaires gouvernementales. En moins d\'une génération, ce plat "artificiel" est devenu authentiquement thaïlandais.',
  },
};
