-- Lessons 21-35 for Chinese, Pastry, BBQ, Vegan paths

-- ============================================================
-- CHINESE LESSONS 21-35
-- ============================================================
INSERT INTO public.lessons (id, path_id, title, description, order_index, duration_min, difficulty, chef_tip, cultural_note, vocabulary)
SELECT gen_random_uuid(), p.id, v.title, v.description, v.order_index, v.duration_min, v.difficulty, v.chef_tip, v.cultural_note, v.vocabulary::jsonb
FROM (VALUES
  ('Le Mapo Tofu', 'Tofu soyeux dans une sauce piquante au porc haché et pâte de haricots — cuisine du Sichuan.', 21, 25, 'intermediate', 'Le poivre du Sichuan donne la sensation d engourdissement caractéristique — ne le réduisez pas.', 'Le mapo tofu doit son nom à une vieille dame (mapo) grêlée qui tenait un restaurant à Chengdu.', '[{"term":"mapo","definition":"vieille dame grêlée — surnom de la cuisinière originale"},{"term":"doubanjiang","definition":"pâte de haricots fermentés pimentée du Sichuan"}]'),
  ('Les Xiaolongbao', 'Raviolis à la vapeur farcis de viande et bouillon gélatineux — trésor de Shanghai.', 22, 90, 'advanced', 'La gelée de bouillon est le secret : faites-la la veille et incorporez-la froide à la farce.', 'Les xiaolongbao sont la fierté de Shanghai — chaque restaurant garde sa recette secrète.', '[{"term":"xiaolongbao","definition":"petits pains dans le panier bambou"},{"term":"aspic","definition":"gelée de bouillon qui fond à la cuisson"}]'),
  ('Le Kung Pao Poulet', 'Poulet sauté aux cacahuètes, piments secs et poivre du Sichuan.', 23, 25, 'intermediate', 'Faites frire les piments secs dans l huile avant tout le reste pour infuser l huile.', 'Le kung pao a été nommé d après Ding Baozhen, gouverneur du Sichuan au XIXe siècle.', '[{"term":"kung pao","definition":"palais du garde — titre du gouverneur Ding"},{"term":"huajiao","definition":"poivre du Sichuan — créateur de l engourdissement"}]'),
  ('Le Canard Laqué de Pékin', 'Canard rôti à la peau croustillante et brillante, servi en crêpes.', 24, 180, 'advanced', 'Séchez le canard 24h au réfrigérateur après le badigeon pour une peau parfaitement croustillante.', 'Le canard laqué de Pékin est servi à la cour impériale depuis 1330.', '[{"term":"Beijing kaoya","definition":"canard rôti de Pékin"},{"term":"mianbing","definition":"crêpes de blé pour enrouler le canard"}]'),
  ('Les Nouilles Dan Dan', 'Nouilles dans une sauce sésame-piments avec porc haché croustillant.', 25, 30, 'intermediate', 'La sauce doit être préparée au dernier moment — elle s oxyde rapidement.', 'Le dan dan vient des colporteurs qui portaient leur marmite sur un bâton (dan dan).', '[{"term":"dan dan","definition":"bâton de porteur — équilibre des paniers"},{"term":"yacai","definition":"légume mariné du Sichuan, essentiel aux dan dan"}]'),
  ('Le Char Siu', 'Porc BBQ cantonais laqué miel-sauce aux huîtres, rouge et caramélisé.', 26, 30, 'intermediate', 'Le dernier brossage de miel doit se faire dans les 5 dernières minutes pour caraméliser sans brûler.', 'Le char siu est l une des viandes les plus populaires de Hong Kong et Guangzhou.', '[{"term":"char siu","definition":"porc suspendu et rôti"},{"term":"maltose","definition":"sucre de malt — donne la brillance caractéristique"}]'),
  ('Le Hotpot Sichuan', 'Bouillon épicé dans lequel on cuit viandes et légumes à table.', 27, 30, 'intermediate', 'Le secret du hotpot est la qualité des sauces de trempage — préparez-en plusieurs.', 'Le hotpot est le plat social par excellence en Chine — mangé en groupe autour d un seul pot.', '[{"term":"huoguo","definition":"pot chaud — hotpot en chinois"},{"term":"mala","definition":"engourdissant-piquant — le profil de saveur du hotpot sichuan"}]'),
  ('Les Raviolis Potstickers', 'Gyoza/jiaozi grillés d un côté, croustillants dessous et moelleux dessus.', 28, 45, 'intermediate', 'La technique eau-vapeur-friture est la clé : faites griller, ajoutez de l eau, couvrez.', 'Les potstickers ont été créés par accident quand un cuisinier de la cour oublia ses raviolis vapeur.', '[{"term":"guotie","definition":"coller à la poêle — potsticker en chinois"},{"term":"shuijiao","definition":"raviolis bouillis — la version bouillante"}]'),
  ('Le Riz Cantonais', 'Riz sauté aux œufs, légumes, crevettes et viande — la référence du riz sauté.', 29, 20, 'beginner', 'Utilisez du riz froid de la veille et un wok très chaud pour le riz cantonais parfait.', 'Le riz cantonais est né de la nécessité de recycler les restes — il devint l emblème de la cuisine cantonaise.', '[{"term":"chao fan","definition":"riz sauté en chinois"},{"term":"soy sauce","definition":"sauce soja — assaisonnement de base du riz cantonais"}]'),
  ('La Soupe Wonton', 'Raviolis farcis au porc dans un bouillon limpide aux légumes.', 30, 40, 'intermediate', 'Le bouillon doit être cristallin — cuisez à frémissement, jamais à ébullition vive.', 'Les wonton sont consommés lors des fêtes car leur forme rappelle les lingots d or porte-bonheur.', '[{"term":"wonton","definition":"nuage avaler — la forme des raviolis"},{"term":"shui jiao","definition":"raviolis bouillis — version aux œufs du wonton"}]'),
  ('Le Poulet Général Tso', 'Poulet frit dans une sauce sucrée-piquante-aigre — créée aux États-Unis par un chef taiwanais.', 31, 35, 'intermediate', 'La double friture rend le poulet très croustillant — une première fois pour cuire, une seconde pour croustiller.', 'Ironiquement, ce plat iconique de la cuisine chinoise américaine est inconnu en Chine.', '[{"term":"General Tso","definition":"Zuo Zongtang — général Qing, inspiration du plat"},{"term":"velveting","definition":"technique de marinades aux blancs d œuf pour attendrir"}]'),
  ('Le Congee Cantonais', 'Bouillie de riz crémeuse garnie de gingembre, ciboulette et œuf centenaire.', 32, 60, 'beginner', 'Plus vous cuisez le congee, plus il est crémeux — minimum 45 minutes de cuisson.', 'Le congee est le plat du réconfort pour les malades et les nouveau-nés en Chine.', '[{"term":"jook","definition":"congee en cantonais"},{"term":"pidan","definition":"œuf centenaire — cuit dans argile et cendres"}]'),
  ('Les Dumplings Har Gow', 'Raviolis vapeur à la crevette en pâte translucide — emblème du dim sum.', 33, 60, 'advanced', 'La pâte har gow translucide est délicate — travaillez-la rapidement pour qu elle ne sèche pas.', 'Le har gow est le test ultime d un chef dim sum — sa pâte transparente révèle tout.', '[{"term":"har gow","definition":"crevette rouleau — ravioli à la crevette"},{"term":"tang fen","definition":"farine de blé + amidon — pâte translucide du har gow"}]'),
  ('Le Sichuan Boiled Fish', 'Filets de poisson dans un bouillon rouge pimenté et engourdissant.', 34, 35, 'intermediate', 'L huile chaude versée sur le piment en fin de cuisson libère tous les arômes en une seconde.', 'Le shui zhu yu (poisson bouilli à l eau) est l une des spécialités les plus populaires du Sichuan.', '[{"term":"shui zhu","definition":"bouilli à l eau — mais en réalité cuit dans une huile épicée"},{"term":"la jiao","definition":"piment rouge — élément clé de la cuisine sichuanaise"}]'),
  ('Les Rouleaux de Printemps Frits', 'Rouleaux de pâte frite farcis de légumes et porc — apéritif incontournable.', 35, 45, 'intermediate', 'La température de l huile doit être à 180°C — trop froide, le rouleau absorbe l huile.', 'Les rouleaux de printemps étaient à l origine mangés au début du printemps (Fête de Lichun).', '[{"term":"chun juan","definition":"rouleau de printemps en mandarin"},{"term":"wrapper","definition":"feuille de riz ou de blé — l enveloppe du rouleau"}]')
) AS v(title, description, order_index, duration_min, difficulty, chef_tip, cultural_note, vocabulary)
CROSS JOIN (SELECT id FROM public.paths WHERE slug='chinese' LIMIT 1) p;

-- ============================================================
-- PASTRY LESSONS 21-35
-- ============================================================
INSERT INTO public.lessons (id, path_id, title, description, order_index, duration_min, difficulty, chef_tip, cultural_note, vocabulary)
SELECT gen_random_uuid(), p.id, v.title, v.description, v.order_index, v.duration_min, v.difficulty, v.chef_tip, v.cultural_note, v.vocabulary::jsonb
FROM (VALUES
  ('Le Soufflé au Grand Marnier', 'Soufflé à la liqueur d orange — léger comme l air, impressionnant.', 21, 30, 'advanced', 'Ne jamais ouvrir le four pendant les 12 premières minutes — le choc thermique ferait retomber le soufflé.', 'Le soufflé est l une des plus grandes prouesses de la pâtisserie française classique.', '[{"term":"soufflé","definition":"insufflé — gonflé par les blancs en neige"},{"term":"beurre pommade","definition":"beurre mou en pommade pour le moule"}]'),
  ('La Crème Brûlée', 'Crème vanille soyeuse sous une croûte de caramel cassante au chalumeau.', 22, 15, 'beginner', 'Faites la crème la veille — elle doit être froide pour que le caramel contraste parfaitement.', 'La crème brûlée est servie dans les restaurants étoilés français depuis le XVIIe siècle.', '[{"term":"brûlée","definition":"brûlée — caramélisée au chalumeau"},{"term":"bain-marie","definition":"cuisson dans un bain d eau chaude"}]'),
  ('Les Financiers aux Amandes', 'Petits gâteaux moelleux à la poudre d amandes et beurre noisette.', 23, 20, 'beginner', 'Le beurre noisette (poussé jusqu à coloration ambrée) est le secret des financiers parfaits.', 'Les financiers étaient vendus près de la Bourse de Paris pour les traders qui mangeaient debout.', '[{"term":"financier","definition":"lingot d or — forme rectangulaire caractéristique"},{"term":"beurre noisette","definition":"beurre cuit jusqu à odeur de noisette"}]'),
  ('Le Paris-Brest Revisité', 'Pâte à choux en couronne, crème pralinée légère — version contemporaine.', 24, 90, 'advanced', 'La crème pralinée doit être montée froide pour être ferme et aérienne à la fois.', 'Créé en 1910 pour célébrer la course cycliste Paris-Brest-Paris.', '[{"term":"pralin","definition":"caramel aux amandes et noisettes moulu"},{"term":"choux","definition":"pâte gonflant à la vapeur lors de la cuisson"}]'),
  ('La Pâte Feuilletée Inversée', 'Pâte feuilletée avec beurrage inversé — plus croustillante et régulière.', 25, 120, 'advanced', 'La feuilletée inversée est moins sujette au rétrécissement — idéale pour les galettes.', 'La pâte feuilletée comporte 729 couches dans une pâte classique à 6 tours.', '[{"term":"tourage","definition":"plier et étaler pour créer les couches"},{"term":"détrempe","definition":"pâte de base avant incorporation du beurre"}]'),
  ('Les Macarons Italiens', 'Coques légères à la meringue italienne, garnis de ganache ou buttercream.', 26, 90, 'advanced', 'Le macaronnage doit donner un ruban — ni trop ferme (croûte épaisse) ni trop liquide (plats).', 'Le macaron moderne a été popularisé par Ladurée à Paris à la fin du XIXe siècle.', '[{"term":"macaronnage","definition":"action de plier la pâte pour l aérer"},{"term":"croûtage","definition":"séchage des coques à l air avant cuisson"}]'),
  ('La Tarte au Citron Meringuée', 'Fond sablé, curd au citron crémeux, meringue italienne dorée.', 27, 75, 'intermediate', 'Le curd doit cuire jusqu à 83°C pour coaguler les œufs sans les brouiller.', 'La tarte au citron est née de l influence américaine (lemon pie) en France au XXe siècle.', '[{"term":"curd","definition":"crème de citron cuite aux œufs et beurre"},{"term":"meringue italienne","definition":"meringue cuite au sirop bouillant"}]'),
  ('Le Mille-feuille Classique', 'Trois couches de feuilletage, crème pâtissière à la vanille, glaçage blanc.', 28, 90, 'advanced', 'Montez le mille-feuille au dernier moment pour garder le feuilletage croustillant.', 'Le mille-feuille existe depuis 1651 (François Pierre de la Varenne) mais sa forme actuelle date du XIXe.', '[{"term":"mille-feuille","definition":"mille feuilles — les couches du feuilletage"},{"term":"glaçage royal","definition":"glaçage blanc au sucre glace pour le dessus"}]'),
  ('La Dacquoise aux Noisettes', 'Meringue aux noisettes moelleuse en biscuit, garnie de mousse pralinée.', 29, 60, 'intermediate', 'La dacquoise doit être légèrement détrempée par la crème — c est voulu.', 'La dacquoise est originaire de Dax dans les Landes — région réputée pour ses noisettes.', '[{"term":"dacquoise","definition":"biscuit meringué aux fruits secs"},{"term":"tant pour tant","definition":"mélange à parts égales sucre glace + poudre de fruits secs"}]'),
  ('Le Baba au Rhum', 'Gâteau brioché imbibé de sirop au rhum, servi avec chantilly.', 30, 90, 'intermediate', 'Le baba doit être sec avant d imbiber — l absorption sera maximale.', 'Le baba au rhum a été inventé à Paris en 1835 — inspiré du savarin.', '[{"term":"baba","definition":"vieillard en polonais — nom donné par le roi Stanislas"},{"term":"imbibage","definition":"action d tremper dans le sirop"}]'),
  ('La Religieuse au Café', 'Double choux fourrés à la crème café, glaçage fondant et décoration à la poche.', 31, 75, 'intermediate', 'Les deux choux doivent être exactement proportionnés — la tête doit être 2/3 du corps.', 'La religieuse ressemble à une religieuse en habit noir — d où son nom.', '[{"term":"fondant","definition":"glaçage blanc chauffé à 35°C pour napper"},{"term":"chiboust","definition":"crème pâtissière allégée à la meringue — parfois utilisée"}]'),
  ('Le Fraisier Moderne', 'Génoise, mousseline vanille, fraises fraîches — le classique des pâtisseries françaises.', 32, 90, 'advanced', 'Placez les fraises coupées parfaitement contre la paroi du cercle pour l effet visuel.', 'Le fraisier est la pièce maîtresse des vitrines de pâtisserie du printemps en France.', '[{"term":"mousseline","definition":"crème pâtissière montée au beurre"},{"term":"imbibage kirsch","definition":"sirop au kirsch pour la génoise"}]'),
  ('La Mousse au Chocolat sans Cuisson', 'Mousse légère au chocolat noir montée aux blancs en neige — rapide et intense.', 33, 20, 'beginner', 'Incorporez les blancs en trois fois pour ne pas faire retomber la mousse.', 'La mousse au chocolat a été créée par le peintre Toulouse-Lautrec qui en était fou.', '[{"term":"monter en neige","definition":"fouetter les blancs jusqu à formation de pics"},{"term":"incorporation","definition":"mélange délicat pour ne pas casser la mousse"}]'),
  ('Les Éclairs au Chocolat', 'Choux allongés, crème pâtissière chocolat intense, glaçage brillant.', 34, 75, 'intermediate', 'Percez deux trous sous l éclair pour le garnir des deux côtés — la crème est plus uniforme.', 'L éclair est la pâtisserie préférée des Français selon toutes les enquêtes.', '[{"term":"éclair","definition":"éclair — il disparaît aussi vite qu un éclair"},{"term":"couverture","definition":"chocolat de qualité avec fort taux de cacao"}]'),
  ('La Galette des Rois Frangipane', 'Feuilletage et frangipane aux amandes — le gâteau de l Épiphanie.', 35, 60, 'intermediate', 'Dorez deux fois avec de l œuf pour une galette vraiment dorée et brillante.', 'Chaque 6 janvier, la France entière mange des galettes pour trouver la fève.', '[{"term":"frangipane","definition":"mélange crème d amandes + crème pâtissière"},{"term":"fève","definition":"petite figurine cachée dans la galette"}]')
) AS v(title, description, order_index, duration_min, difficulty, chef_tip, cultural_note, vocabulary)
CROSS JOIN (SELECT id FROM public.paths WHERE slug='pastry' LIMIT 1) p;

-- ============================================================
-- BBQ LESSONS 21-35
-- ============================================================
INSERT INTO public.lessons (id, path_id, title, description, order_index, duration_min, difficulty, chef_tip, cultural_note, vocabulary)
SELECT gen_random_uuid(), p.id, v.title, v.description, v.order_index, v.duration_min, v.difficulty, v.chef_tip, v.cultural_note, v.vocabulary::jsonb
FROM (VALUES
  ('Le Brisket de Texas', 'Poitrine de bœuf fumée 12-14h au bois de chêne — le roi du BBQ texan.', 21, 840, 'advanced', 'La patience est la clé — ne regardez pas le thermomètre toutes les 5 minutes.', 'Le brisket est la pièce emblématique du BBQ de Texas, cuit entier sans marinade.', '[{"term":"brisket","definition":"poitrine de bœuf — pièce fibreuse qui fond après longue cuisson"},{"term":"bark","definition":"croûte sèche formée à la surface du brisket fumé"}]'),
  ('Les Ribs St-Louis Style', 'Côtes de porc parées à la St-Louis, fumées et laquées — tendres à l os.', 22, 360, 'intermediate', 'Retirez la membrane du côté os avec un papier absorbant pour un meilleur fumage.', 'Le style St-Louis est une coupe spécifique qui retire les bouts cartilagineux pour une côte uniforme.', '[{"term":"St-Louis style","definition":"coupe carrée des côtes de porc sans cartilage"},{"term":"3-2-1 method","definition":"3h fumé, 2h en papier, 1h sans — technique classique"}]'),
  ('Le Pulled Pork des Carolines', 'Épaule de porc fumée 8-10h, effilochée et sauce vinaigre — BBQ de Caroline du Nord.', 23, 600, 'advanced', 'Le sauce vinegar de Caroline du Nord est sans tomate — uniquement vinaigre, piment et sucre.', 'La Caroline du Nord a deux camps : l Est (vinaigre pur) vs l Ouest (avec tomate).', '[{"term":"pulled pork","definition":"porc effiloché après longue cuisson"},{"term":"vinegar sauce","definition":"sauce vinaigre pimentée sans tomate — style Carolines"}]'),
  ('La Volaille à la Bière (Beer Can Chicken)', 'Poulet entier assis sur une canette de bière, fumé — juteux à l intérieur, croustillant dehors.', 24, 90, 'intermediate', 'La bière crée de la vapeur interne qui garde le poulet juteux tout en fumant l extérieur.', 'Le beer can chicken est une invention américaine des années 90 devenu classique des BBQ party.', '[{"term":"beer can chicken","definition":"poulet sur canette — cuisson verticale à la vapeur"},{"term":"rub","definition":"mélange d épices sèches appliqué sur la viande"}]'),
  ('Les Burnt Ends de Kansas City', 'Extrémités caramélisées du brisket, recuites en sauce BBQ — bouchées caramélisées.', 25, 120, 'advanced', 'Les burnt ends doivent être caramélisés mais pas brûlés — la différence est de 10 minutes.', 'Les burnt ends étaient à l origine offerts gratuitement aux clients qui attendaient chez Arthur Bryant à Kansas City.', '[{"term":"burnt ends","definition":"bouts brûlés — extrémités plus grasses et plus cuites du brisket"},{"term":"point","definition":"la partie la plus grasse du brisket, d où viennent les burnt ends"}]'),
  ('Le Smoked Salmon Gravlax', 'Saumon fumé à froid sur planche de cèdre, mariné aux herbes nordiques.', 26, 30, 'intermediate', 'Le fumage à froid ne dépasse pas 30°C — le saumon ne cuit pas, il fume.', 'La planche de cèdre est une technique des populations autochtones de la côte Pacifique.', '[{"term":"cold smoking","definition":"fumage à froid — sous 30°C, le produit ne cuit pas"},{"term":"cedar plank","definition":"planche de cèdre pour fumage indirect"}]'),
  ('Les Côtes d Agneau à la Harissa', 'Côtelettes d agneau marinées à la harissa, grillées au charbon.', 27, 30, 'intermediate', 'L agneau doit rester rosé — ne dépassez pas 55°C à cœur.', 'La harissa grillée caramélise et crée une croûte épicée incomparable sur l agneau.', '[{"term":"harissa","definition":"pâte de piments nord-africaine"},{"term":"carré d agneau","definition":"les 8 côtes du dos de l agneau"}]'),
  ('Le Smoked Turkey Breast', 'Poitrine de dinde fumée au bois de pomme — tendre, dorée et parfumée.', 28, 240, 'intermediate', 'Injectez du bouillon beurré dans la poitrine avant de fumer pour garantir le moelleux.', 'La poitrine de dinde fumée est le plat star des BBQ de Thanksgiving aux États-Unis.', '[{"term":"injection","definition":"injecter de la marinade liquide dans la viande avec une seringue"},{"term":"apple wood","definition":"bois de pommier — fumée douce et fruitée pour la volaille"}]'),
  ('Les Saucisses Maison au Fumoir', 'Saucisses de porc et bœuf préparées et fumées maison.', 29, 180, 'advanced', 'La température interne doit atteindre 70°C pour la sécurité alimentaire.', 'Faire ses saucisses est l art ultime du charcutier — maîtrise du sel, sel nitrite et fumage.', '[{"term":"boyaux","definition":"intestins naturels pour l enveloppe des saucisses"},{"term":"sel nitrite","definition":"sel de conservation qui donne la couleur rose"}]'),
  ('Le Smoked Chicken Wings', 'Ailes de poulet fumées puis grillées — croustillantes et fumées.', 30, 120, 'beginner', 'La double cuisson (fumage + grill) donne la peau croustillante que le fumage seul ne peut pas faire.', 'Les wings au BBQ sont l apéritif star des Super Bowl Sundays américains.', '[{"term":"dry rub","definition":"mélange d épices sèches sans liquide"},{"term":"pit","definition":"fosse ou fumoir — l outil du pitmaster"}]'),
  ('Le Bœuf Argenté à la Patagonie', 'Côte de bœuf entière grillée sur croix de fer — l asado argentin.', 31, 180, 'advanced', 'L asado argentin est toujours cuit à basse température, lentement, sans couvercle.', 'L asado est la réunion sociale la plus importante en Argentine — famille et amis autour du feu.', '[{"term":"asado","definition":"grillade en espagnol — art argentin du feu"},{"term":"parrilla","definition":"gril argentin — la fierté de chaque asador"}]'),
  ('Les Légumes Grillés Fumés', 'Aubergines, poivrons et courgettes fumés au bois de hêtre.', 32, 45, 'beginner', 'Les légumes fumés sont meilleurs à température ambiante avec de l huile d olive.', 'Les légumes grillés fumés sont une alternative végétarienne de plus en plus populaire dans le BBQ.', '[{"term":"smoking wood","definition":"bois de fumage — chaque bois apporte des arômes différents"},{"term":"char","definition":"légères marques de brûlure sur les légumes grillés"}]'),
  ('La Côte de Bœuf Tomahawk', 'Côte de bœuf spectaculaire avec os extra-long, cuite en reverse sear.', 33, 90, 'advanced', 'Le reverse sear (four puis grill) garantit une cuisson parfaite jusqu au centre.', 'La côte tomahawk doit son nom à la hache amérindienne qu évoque sa forme.', '[{"term":"tomahawk","definition":"côte avec os extra-long de 30-40cm"},{"term":"reverse sear","definition":"cuire au four puis saisir — technique inverse du saisir-puis-cuire"}]'),
  ('Le Smoked Beef Short Ribs', 'Côtes de bœuf courtes fumées 8h — géantes, tendres, ultrafumées.', 34, 480, 'advanced', 'Ces côtes doivent atteindre 95°C — elles sont prêtes quand une sonde passe sans résistance.', 'Les beef short ribs sont les dinosaur ribs du BBQ — une côte peut peser 800g.', '[{"term":"short ribs","definition":"côtes courtes de bœuf — très grasses et gélatineuses"},{"term":"probe tender","definition":"tendre comme la sonde qui passe sans résistance"}]'),
  ('La Plancha aux Fruits de Mer', 'Crevettes, calamars et pétoncles grillés sur plancha chaude — technique espagnole.', 35, 20, 'beginner', 'La plancha doit être au maximum de sa chaleur pour saisir instantanément sans dessécher.', 'La plancha est originaire du Pays basque espagnol — cuisson à contact direct sur métal épais.', '[{"term":"plancha","definition":"plaque de métal très chaude — grill à contact direct"},{"term":"a la plancha","definition":"sur la plaque chaude — style de cuisson espagnol"}]')
) AS v(title, description, order_index, duration_min, difficulty, chef_tip, cultural_note, vocabulary)
CROSS JOIN (SELECT id FROM public.paths WHERE slug='bbq' LIMIT 1) p;

-- ============================================================
-- VEGAN LESSONS 21-35
-- ============================================================
INSERT INTO public.lessons (id, path_id, title, description, order_index, duration_min, difficulty, chef_tip, cultural_note, vocabulary)
SELECT gen_random_uuid(), p.id, v.title, v.description, v.order_index, v.duration_min, v.difficulty, v.chef_tip, v.cultural_note, v.vocabulary::jsonb
FROM (VALUES
  ('Le Jackfruit Pulled Pork', 'Jeune jackfruit effiloché en sauce BBQ — trompeusement semblable au porc.', 21, 45, 'beginner', 'Utilisez du jackfruit en saumure (pas au sirop sucré) pour un résultat optimal.', 'Le jackfruit est natif d Asie du Sud et utilisé depuis des siècles comme substitut de viande.', '[{"term":"jackfruit","definition":"fruit du jacquier — effiloche comme le porc"},{"term":"young jackfruit","definition":"jackfruit non mûr utilisé comme substitut de viande"}]'),
  ('Le Seitan Teriyaki', 'Seitan tranché et glacé à la sauce teriyaki — riche en protéines.', 22, 40, 'intermediate', 'Le seitan maison est bien meilleur que l industriel — faites-le avec de la farine de blé.', 'Le seitan (gluten de blé) est consommé dans les monastères bouddhistes depuis des siècles.', '[{"term":"seitan","definition":"protéine de gluten de blé texturée comme de la viande"},{"term":"vital wheat gluten","definition":"farine de gluten pur pour faire le seitan"}]'),
  ('Les Burgers de Haricots Noirs', 'Galettes de haricots noirs, cumin et coriandre — savoureux et riches.', 23, 30, 'beginner', 'Réfrigérez les galettes 30 min avant de les cuire pour qu elles tiennent mieux.', 'Les burgers végétaux ont explosé grâce à des innovations culinaires comme Beyond Meat.', '[{"term":"bean burger","definition":"galette végétale à base de légumineuses"},{"term":"flax egg","definition":"graine de lin moulue + eau — remplace l œuf liant"}]'),
  ('Le Curry de Chou-fleur Rôti', 'Chou-fleur entier rôti aux épices dans un curry crémeux à la noix de coco.', 24, 50, 'beginner', 'Rôtissez le chou-fleur entier d abord — il prend une saveur de noisette.', 'Le chou-fleur rôti entier est l une des plus belles présentations végétales au restaurant.', '[{"term":"cauliflower steak","definition":"tranche épaisse de chou-fleur grillée comme un steak"},{"term":"roasting","definition":"rôtissage à haute température pour caraméliser"}]'),
  ('Le Poke Bowl aux Algues', 'Riz sushi, tofu mariné sésame-tamari, avocat, algues et pickles.', 25, 20, 'beginner', 'Le tofu doit être pressé 1h pour absorber la marinade — sinon il l expulse à la cuisson.', 'Le poke vient de Hawaï et signifie couper en morceaux en hawaiien.', '[{"term":"poke","definition":"couper en morceaux en hawaiien"},{"term":"shoyu","definition":"sauce soja japonaise légère — base du poke hawaïen"}]'),
  ('Les Falafels Maison', 'Boulettes de pois chiches et herbes fraîches frites — légères et croustillantes.', 26, 30, 'intermediate', 'Utilisez des pois chiches secs trempés, jamais en conserve — les falafels tiendront bien.', 'Les falafels sont originaires du Moyen-Orient et constituent un fast food végétarien millénaire.', '[{"term":"falafel","definition":"boulette frite de pois chiches ou fèves"},{"term":"tahini","definition":"purée de sésame — sauce d accompagnement essentielle"}]'),
  ('Le Ramen Végétalien', 'Bouillon dashi de kombu et shiitake, nouilles, toppings vegans — profondeur umami.', 27, 60, 'intermediate', 'Le kombu donne plus d umami que les produits animaux — ne le cuisez jamais à ébullition.', 'Le ramen végétalien utilise les mêmes techniques que le ramen traditionnel, sans compromettre la saveur.', '[{"term":"kombu","definition":"algue brune riche en acide glutamique — umami naturel"},{"term":"tare","definition":"sauce de concentration pour assaisonner le bouillon"}]'),
  ('Le Gâteau au Chocolat Végétalien', 'Gâteau moelleux sans œufs ni lait — lait de soja, vinaigre et huile.', 28, 45, 'beginner', 'La réaction vinaigre + bicarbonate remplace la levée des œufs.', 'La pâtisserie végane utilise la chimie pour recréer les textures des produits animaux.', '[{"term":"flax egg","definition":"graine de lin moulue + eau pour remplacer l œuf"},{"term":"aquafaba","definition":"eau de cuisson des pois chiches — remplace les blancs d œuf"}]'),
  ('Le Tartare de Betterave', 'Betterave crue marinée en tartare, câpres, échalotes — élégant et coloré.', 29, 20, 'beginner', 'Coupez la betterave en brunoise fine pour imiter la texture du tartare de bœuf.', 'Le tartare végétal est servi dans les restaurants gastronomiques comme alternative raffinée.', '[{"term":"tartare","definition":"viande ou légume coupé finement et cru assaisonné"},{"term":"brunoise","definition":"coupe en tout petits dés réguliers — 2-3mm"}]'),
  ('La Quiche Végane aux Légumes', 'Flan de tofu soyeux aux légumes de saison dans un fond de tarte — sans œufs.', 30, 50, 'intermediate', 'Le kala namak (sel noir indien) apporte un goût d œuf au tofu soyeux.', 'La quiche végane prouve que le tofu peut remplacer les œufs dans les préparations salées.', '[{"term":"tofu soyeux","definition":"tofu mou à haute teneur en eau — texture crémeuse"},{"term":"kala namak","definition":"sel volcanique soufré — goût d oeuf sans oeuf"}]'),
  ('Les Rouleaux de Printemps Frais', 'Galettes de riz farcies de légumes croquants, herbes fraîches et tofu.', 31, 25, 'beginner', 'Trempez chaque galette 10 secondes seulement — elle finit de ramollir en roulant.', 'Les rouleaux frais du Vietnam (gỏi cuốn) sont légers et adaptés au véganisme.', '[{"term":"rice paper","definition":"galette de riz séchée — ramollie dans l eau avant usage"},{"term":"gỏi cuốn","definition":"rouleau de printemps frais — viet, à ne pas conffondre avec les frits"}]'),
  ('Le Cheesecake Végétalien', 'Base de noix et dattes, garniture de cajous trempés et citron — sans cuisson.', 32, 20, 'advanced', 'Les cajous doivent tremper au moins 8h pour devenir crémeux une fois mixés.', 'Le cheesecake sans cuisson au cajou est l une des innovations les plus réussies de la pâtisserie végane.', '[{"term":"cashew cream","definition":"cajous mixés en crème après trempage"},{"term":"no-bake","definition":"sans cuisson — texture obtenue par réfrigération ou congélation"}]'),
  ('Le Buddha Bowl Protéiné', 'Riz brun, edamame, tofu teriyaki, légumes rôtis, sauce tahini-tamari.', 33, 25, 'beginner', 'Chaque élément du bowl doit être assaisonné séparément pour un équilibre parfait.', 'Le buddha bowl est inspiré de la philosophie bouddhiste de plénitude et d équilibre.', '[{"term":"bowl","definition":"bol complet avec grains, protéines, légumes et sauce"},{"term":"edamame","definition":"fèves de soja jeunes en cosse — riches en protéines"}]'),
  ('La Soupe Miso aux Légumes', 'Bouillon dashi de kombu, miso blanc, tofu, wakamé et légumes de saison.', 34, 20, 'beginner', 'Ne jamais faire bouillir le miso — ajoutez-le hors feu pour préserver ses probiotiques.', 'La soupe miso est un aliment fermenté probiotique consommé quotidiennement au Japon.', '[{"term":"shiro miso","definition":"miso blanc doux — fermenté moins longtemps"},{"term":"wakamé","definition":"algue verte séchée — réhydratée dans le bouillon"}]'),
  ('Le Tiramisu Végétalien', 'Tiramisu sans mascarpone ni œufs — crème de cajou, café, cacao.', 35, 30, 'advanced', 'La crème de cajou doit être battue froide pour être assez ferme.', 'Le tiramisu végétalien prouve que les desserts italiens emblématiques peuvent être réinventés sans produits animaux.', '[{"term":"aquafaba","definition":"eau de conserve des pois chiches — monte comme des blancs d oeuf"},{"term":"cashew cream","definition":"crème de cajou — remplace le mascarpone"}]')
) AS v(title, description, order_index, duration_min, difficulty, chef_tip, cultural_note, vocabulary)
CROSS JOIN (SELECT id FROM public.paths WHERE slug='vegan' LIMIT 1) p;

-- ============================================================
-- RECIPES FOR CHINESE LESSONS 21-35
-- ============================================================
INSERT INTO public.recipes (id, lesson_id, title, description, emoji, prep_time_min, cook_time_min, servings, difficulty, avg_price_eur, ingredients, instructions, chef_tip, cultural_note)
SELECT gen_random_uuid(), l.id, v.title, v.description, v.emoji, v.prep_time_min, v.cook_time_min, v.servings, v.difficulty, v.avg_price_eur, v.ingredients::jsonb, v.instructions::jsonb, v.chef_tip, v.cultural_note
FROM (VALUES
  ('Le Mapo Tofu', 'Tofu soyeux au porc haché et pâte de haricots sichuanaise piquante.', '🌶️', 10, 20, 4, 'intermediate', 6.0,
   '[{"qty":"400g","item":"tofu soyeux"},{"qty":"150g","item":"porc haché"},{"qty":"2 c.s.","item":"doubanjiang (pâte de haricots pimentée)"},{"qty":"1 c.c.","item":"poivre du Sichuan moulu"},{"qty":"3 gousses","item":"ail"},{"qty":"2cm","item":"gingembre"},{"qty":"200ml","item":"bouillon de poulet"},{"qty":"1 c.s.","item":"maïzena"},{"qty":"huile","item":"de sésame et de cuisson"}]',
   '["Coupez le tofu en cubes de 2cm, égouttez","Faites revenir le porc dans l huile chaude","Ajoutez ail, gingembre et doubanjiang","Cuisez 2 min jusqu à rouge sombre et parfumé","Versez le bouillon, portez à ébullition","Ajoutez le tofu délicatement","Épaissir avec la maïzena diluée","Saupoudrez de poivre du Sichuan","Arrosez d huile de sésame"]',
   'Le poivre du Sichuan donne l engourdissement (mala) caractéristique — réduisez si vous êtes sensible.', 'Le mapo tofu doit son nom à la vieille dame grêlée (mapo) qui tenait le restaurant à Chengdu.'),
  ('Le Kung Pao Poulet', 'Poulet sauté aux cacahuètes et piments secs dans une sauce aigre-douce sichuanaise.', '🥜', 20, 15, 4, 'intermediate', 7.0,
   '[{"qty":"400g","item":"blanc de poulet en dés"},{"qty":"60g","item":"cacahuètes grillées"},{"qty":"8","item":"piments rouges secs"},{"qty":"1 c.c.","item":"poivre du Sichuan"},{"qty":"3 gousses","item":"ail"},{"qty":"sauce:","item":""},{"qty":"2 c.s.","item":"sauce soja"},{"qty":"1 c.s.","item":"vinaigre de riz"},{"qty":"1 c.s.","item":"sucre"},{"qty":"1 c.s.","item":"maïzena"}]',
   '["Marinez le poulet 15 min avec soja et maïzena","Mélangez la sauce (soja, vinaigre, sucre, maïzena)","Faites frire les piments secs dans l huile chaude 30 secondes","Ajoutez le poivre du Sichuan et ail","Ajoutez le poulet, cuisez à feu vif","Versez la sauce, cuisez jusqu à caramélisation","Ajoutez les cacahuètes en fin de cuisson"]',
   'Les piments frits dans l huile infusent leur saveur sans les brûler — technique essentielle.', 'Le kung pao a été nommé d après Ding Baozhen, gouverneur du Sichuan et garde impérial.'),
  ('Le Char Siu', 'Porc BBQ cantonais laqué au miel et sauce hoisin, rouge et caramélisé.', '🍖', 15, 45, 4, 'intermediate', 8.0,
   '[{"qty":"800g","item":"filet de porc"},{"qty":"3 c.s.","item":"sauce hoisin"},{"qty":"2 c.s.","item":"sauce soja"},{"qty":"2 c.s.","item":"miel"},{"qty":"2 c.s.","item":"vin de Shaoxing"},{"qty":"1 c.c.","item":"poudre cinq épices"},{"qty":"quelques gouttes","item":"colorant rouge (optionnel)"}]',
   '["Mélangez tous les ingrédients de marinade","Marinez le porc au moins 4h (idéalement 24h)","Préchauffez le four à 220°C","Posez le porc sur une grille au-dessus d un plat d eau","Enfournez 20 min","Badigeonnez avec la marinade restante","Enfournez encore 15 min","Badigeonnez de miel et passez 5 min en grill"]',
   'Le dernier passage au grill avec le miel caramélise sans brûler — surveillez de près.', 'Le char siu (porc suspendu et rôti) est central dans la cuisine cantonaise depuis des siècles.'),
  ('Le Riz Cantonais', 'Riz sauté aux œufs, crevettes et légumes — la référence de la cuisine chinoise.', '🍳', 10, 10, 4, 'beginner', 5.0,
   '[{"qty":"400g","item":"riz cuit de la veille (froid)"},{"qty":"200g","item":"crevettes décortiquées"},{"qty":"3","item":"œufs"},{"qty":"100g","item":"petits pois"},{"qty":"100g","item":"carottes en dés"},{"qty":"3 c.s.","item":"sauce soja"},{"qty":"huile","item":"de sésame"},{"qty":"2 gousses","item":"ail"}]',
   '["Chauffez le wok à feu maximum","Ajoutez l huile et faites sauter l ail","Ajoutez les crevettes, cuisez 1 min","Poussez sur le côté, ajoutez les œufs battus","Mélangez les œufs puis incorporez le riz","Ajoutez légumes et sauce soja","Cuisez en remuant constamment 3 min","Arrosez d huile de sésame avant de servir"]',
   'Le wok doit être extrêmement chaud pour obtenir le wok hei (goût légèrement fumé).', 'Le riz cantonais est né de la tradition de recycler les restes — maintenant c est un art culinaire à part entière.'),
  ('Le Congee Cantonais', 'Bouillie de riz crémeuse garnie de gingembre et ciboulette.', '🍚', 10, 60, 4, 'beginner', 4.0,
   '[{"qty":"150g","item":"riz jasmin"},{"qty":"1.5L","item":"bouillon de poulet"},{"qty":"200g","item":"filet de poulet"},{"qty":"5cm","item":"gingembre frais en julienne"},{"qty":"ciboulette","item":"émincée"},{"qty":"1","item":"œuf de centenaire (pidan) optionnel"},{"qty":"sauce soja","item":"pour servir"},{"qty":"huile de sésame","item":"pour servir"}]',
   '["Rincez le riz et mettez dans une casserole avec le bouillon","Portez à ébullition puis réduisez","Cuisez à frémissement 45-60 min en remuant souvent","Pochez le poulet dans le congee 15 min","Effilochez le poulet","Servez garni de gingembre, ciboulette et poulet","Assaisonnez avec sauce soja et huile de sésame à table"]',
   'Plus vous cuisez le congee longtemps, plus les grains se dissolvent et la texture devient crémeuse.', 'Le congee est le plat réconfort en Chine — servi aux malades, aux bébés et le matin froid.')
) AS v(lesson_title, title, description, emoji, prep_time_min, cook_time_min, servings, difficulty, avg_price_eur, ingredients, instructions, chef_tip, cultural_note)
JOIN public.lessons l ON l.title = v.lesson_title;

-- ============================================================
-- RECIPES FOR PASTRY LESSONS 21-35
-- ============================================================
INSERT INTO public.recipes (id, lesson_id, title, description, emoji, prep_time_min, cook_time_min, servings, difficulty, avg_price_eur, ingredients, instructions, chef_tip, cultural_note)
SELECT gen_random_uuid(), l.id, v.title, v.description, v.emoji, v.prep_time_min, v.cook_time_min, v.servings, v.difficulty, v.avg_price_eur, v.ingredients::jsonb, v.instructions::jsonb, v.chef_tip, v.cultural_note
FROM (VALUES
  ('La Crème Brûlée', 'Crème vanille soyeuse sous une croûte de caramel au chalumeau.', '🔥', 15, 45, 4, 'beginner', 5.0,
   '[{"qty":"500ml","item":"crème liquide entière"},{"qty":"6","item":"jaunes d œuf"},{"qty":"80g","item":"sucre"},{"qty":"1","item":"gousse de vanille"},{"qty":"4 c.s.","item":"sucre cassonade pour caraméliser"}]',
   '["Préchauffez le four à 160°C","Faites chauffer la crème avec la vanille fendue","Fouettez jaunes et sucre sans faire mousser","Versez la crème chaude peu à peu sur les œufs","Filtrez et versez dans des ramequins","Cuisez au bain-marie 40 min (la crème doit trembler légèrement)","Refroidissez au réfrigérateur 4h minimum","Saupoudrez de cassonade et brûlez au chalumeau"]',
   'La crème doit trembler comme une gelée au centre quand vous sortez du four — elle finira de cuire en refroidissant.', 'La crème brûlée est mentionnée dans les livres de cuisine français dès le XVIIe siècle.'),
  ('Les Financiers aux Amandes', 'Petits gâteaux à la poudre d amandes et beurre noisette — moelleux et dorés.', '💛', 15, 15, 12, 'beginner', 4.0,
   '[{"qty":"150g","item":"beurre"},{"qty":"180g","item":"sucre glace"},{"qty":"60g","item":"farine"},{"qty":"120g","item":"poudre d amandes"},{"qty":"4","item":"blancs d œuf"},{"qty":"1 c.c.","item":"extrait de vanille"}]',
   '["Faites fondre le beurre jusqu à coloration ambrée et odeur de noisette","Laissez refroidir légèrement","Mélangez sucre glace, farine et poudre d amandes","Incorporez les blancs non battus","Ajoutez le beurre noisette tiède et vanille","Remplissez les moules à 3/4","Enfournez à 200°C 12-15 min","Ils doivent être dorés avec un centre légèrement moelleux"]',
   'Le beurre noisette est la signature des financiers — ne le brûlez pas, arrêtez à la couleur caramel.', 'Les financiers étaient vendus en lingots près de la Bourse de Paris pour que les traders les mangent sans se salir les mains.'),
  ('Les Macarons Italiens', 'Coques légères à la meringue italienne, garnis de ganache chocolat.', '🍬', 30, 15, 20, 'advanced', 8.0,
   '[{"qty":"150g","item":"poudre d amandes"},{"qty":"150g","item":"sucre glace"},{"qty":"110g","item":"blancs d œuf (vieillis)"},{"qty":"pour meringue italienne:","item":""},{"qty":"150g","item":"sucre"},{"qty":"50ml","item":"eau"},{"qty":"pour ganache:","item":""},{"qty":"150g","item":"chocolat noir"},{"qty":"100ml","item":"crème liquide"}]',
   '["Mixez poudre d amandes et sucre glace, tamisez","Faites le sirop: sucre + eau à 118°C","Versez sur 55g de blancs montés en fouettant — meringue italienne","Incorporez la meringue aux 55g de blancs restants mélangés à la poudre","Macaronnez jusqu au ruban","Pochez sur papier cuisson, laissez croûter 30 min","Enfournez 14 min à 150°C","Garnissez de ganache après refroidissement"]',
   'Les blancs vieillis (séparés 48h à température ambiante) donnent de meilleures coques.', 'Le macaron moderne bicolore a été popularisé par Ladurée à Paris à la fin du XIXe siècle.'),
  ('La Tarte au Citron Meringuée', 'Curd de citron crémeux sur fond sablé, meringue italienne dorée au chalumeau.', '🍋', 45, 30, 8, 'intermediate', 6.0,
   '[{"qty":"pour le sablé:","item":""},{"qty":"200g","item":"farine"},{"qty":"100g","item":"beurre froid"},{"qty":"80g","item":"sucre glace"},{"qty":"1","item":"œuf"},{"qty":"pour le curd:","item":""},{"qty":"150ml","item":"jus de citron frais"},{"qty":"4","item":"œufs"},{"qty":"150g","item":"sucre"},{"qty":"120g","item":"beurre"},{"qty":"zestes","item":"de 2 citrons"}]',
   '["Faites le sablé: mélangez farine, beurre, sucre, œuf, réfrigérez 1h, étalez et foncez un moule","Cuisez à blanc 15 min à 180°C","Faites le curd: chauffez jus+sucre+œufs à 83°C en remuant","Hors feu, incorporez le beurre et les zestes, mixez","Versez dans le fond cuit, réfrigérez 2h","Faites la meringue italienne","Pochez sur le curd, brûlez au chalumeau"]',
   'Le curd doit atteindre exactement 83°C — un thermomètre est indispensable pour cette recette.', 'La tarte au citron meringuée est née de l influence américaine des lemon pies importés en France.'),
  ('Les Éclairs au Chocolat', 'Choux allongés à la crème chocolat, glaçage brillant au fondant.', '⚡', 30, 25, 8, 'intermediate', 5.0,
   '[{"qty":"pour la pâte à choux:","item":""},{"qty":"125ml","item":"eau"},{"qty":"125ml","item":"lait"},{"qty":"100g","item":"beurre"},{"qty":"150g","item":"farine"},{"qty":"4","item":"œufs"},{"qty":"pour la crème chocolat:","item":""},{"qty":"500ml","item":"lait"},{"qty":"4","item":"jaunes"},{"qty":"80g","item":"sucre"},{"qty":"40g","item":"maïzena"},{"qty":"100g","item":"chocolat noir"}]',
   '["Faites la pâte à choux: portez eau+lait+beurre à ébullition, ajoutez farine, desséchez à la casserole, incorporez les œufs un à un","Pochez en éclairs de 12cm","Cuisez 25 min à 180°C sans ouvrir le four","Faites la crème: fouettez jaunes+sucre+maïzena, versez lait chaud, cuisez jusqu épaississement, ajoutez chocolat","Garnissez les éclairs","Nappez de fondant chauffé à 35°C"]',
   'Ne jamais ouvrir le four pendant la cuisson des choux — la vapeur est essentielle à la montée.', 'L éclair est la pâtisserie préférée des Français — le mot signifie la vitesse à laquelle il disparaît.')
) AS v(lesson_title, title, description, emoji, prep_time_min, cook_time_min, servings, difficulty, avg_price_eur, ingredients, instructions, chef_tip, cultural_note)
JOIN public.lessons l ON l.title = v.lesson_title;

-- ============================================================
-- RECIPES FOR BBQ LESSONS 21-35
-- ============================================================
INSERT INTO public.recipes (id, lesson_id, title, description, emoji, prep_time_min, cook_time_min, servings, difficulty, avg_price_eur, ingredients, instructions, chef_tip, cultural_note)
SELECT gen_random_uuid(), l.id, v.title, v.description, v.emoji, v.prep_time_min, v.cook_time_min, v.servings, v.difficulty, v.avg_price_eur, v.ingredients::jsonb, v.instructions::jsonb, v.chef_tip, v.cultural_note
FROM (VALUES
  ('Les Ribs St-Louis Style', 'Côtes de porc St-Louis fumées et laquées — la recette 3-2-1.', '🥩', 30, 360, 4, 'intermediate', 12.0,
   '[{"qty":"2","item":"carrés de ribs St-Louis (1.5kg chacun)"},{"qty":"pour le rub:","item":""},{"qty":"3 c.s.","item":"paprika fumé"},{"qty":"2 c.s.","item":"cassonade"},{"qty":"1 c.s.","item":"sel"},{"qty":"1 c.s.","item":"poivre noir"},{"qty":"1 c.c.","item":"poudre d ail"},{"qty":"sauce BBQ","item":"pour laquer en fin"}]',
   '["Retirez la membrane côté os avec du papier absorbant","Mélangez les épices du rub","Massez les ribs généreusement des deux côtés","Réfrigérez 1h ou toute la nuit","3h de fumage à 110°C (bois de pomme ou cerisier)","Emballez dans du papier aluminium avec un peu de jus de pomme, 2h à 110°C","Sortez du papier, laquez de sauce BBQ, 1h découvert","Les os doivent sortir de 1cm"]',
   'La méthode 3-2-1 garantit des ribs toujours parfaits — tendres mais pas réduits en bouillie.', 'Le style St-Louis est une coupe précise qui rend les ribs uniformes pour une cuisson régulière.'),
  ('Le Pulled Pork des Carolines', 'Épaule de porc fumée 10h, effilochée et sauce vinaigre.', '🐷', 30, 600, 8, 'advanced', 10.0,
   '[{"qty":"2kg","item":"épaule de porc avec os"},{"qty":"rub:","item":""},{"qty":"2 c.s.","item":"paprika"},{"qty":"1 c.s.","item":"sel"},{"qty":"1 c.s.","item":"sucre brun"},{"qty":"1 c.c.","item":"cayenne"},{"qty":"sauce Carolina:","item":""},{"qty":"200ml","item":"vinaigre de cidre"},{"qty":"1 c.s.","item":"sucre"},{"qty":"1 c.c.","item":"piment rouge"},{"qty":"sel","item":"au goût"}]',
   '["Massez l épaule avec le rub la veille","Fumez à 110°C avec bois de hickory pendant 5h","La température interne doit atteindre 90°C","À 75°C, enveloppez dans du papier kraft encore 3-5h","Laissez reposer 1h emballé","Effilochez avec deux fourchettes ou à la main","Mélangez avec la sauce vinaigre Carolina","Servez dans des buns avec coleslaw"]',
   'L épaule est prête quand l os se retire sans effort — ne regardez pas l horloge mais le thermomètre.', 'La Caroline du Nord a deux écoles de BBQ: l Est utilise vinaigre pur, l Ouest ajoute de la tomate.'),
  ('Les Côtes d Agneau à la Harissa', 'Côtelettes d agneau marinées à la harissa grillées au charbon.', '🔥', 15, 15, 4, 'intermediate', 14.0,
   '[{"qty":"8","item":"côtelettes d agneau"},{"qty":"3 c.s.","item":"harissa"},{"qty":"2 c.s.","item":"huile d olive"},{"qty":"jus","item":"d 1 citron"},{"qty":"2 gousses","item":"ail"},{"qty":"1 c.c.","item":"cumin"},{"qty":"sel","item":"et poivre noir"}]',
   '["Mélangez harissa, huile, citron, ail et cumin","Enduisez les côtelettes et marinez 2h minimum","Préparez les braises — elles doivent être blanches et intenses","Grillez 3-4 min de chaque côté","Température à cœur: 55°C pour rosé","Laissez reposer 3 min avant de servir","Servez avec du pain plat et yaourt au citron"]',
   'L agneau doit être rosé — dépassez 60°C et vous perdez toute la tendreté du carré.', 'La harissa grillée caramélise et crée une croûte épicée qui contraste avec la tendreté de l agneau.'),
  ('Le Smoked Chicken Wings', 'Ailes de poulet fumées puis grillées — croustillantes et fumées.', '🍗', 10, 120, 4, 'beginner', 7.0,
   '[{"qty":"1.2kg","item":"ailes de poulet"},{"qty":"rub:","item":""},{"qty":"2 c.s.","item":"paprika fumé"},{"qty":"1 c.s.","item":"sel"},{"qty":"1 c.s.","item":"poudre d ail"},{"qty":"1 c.c.","item":"cayenne"},{"qty":"1 c.s.","item":"cassonade"},{"qty":"sauce Buffalo:","item":""},{"qty":"100g","item":"beurre"},{"qty":"100ml","item":"sauce pimentée type Frank s"}]',
   '["Séchez les ailes avec du papier absorbant","Massez avec le rub et réfrigérez 1h","Fumez à 120°C pendant 1h30 avec bois de cerisier","Montez la température à 220°C pour 20 min de grill","Ou terminez directement au barbecue à grille chaude","Mélangez beurre fondu et sauce pimentée","Nappez les ailes et servez immédiatement"]',
   'Le séchage des ailes avant le rub est essentiel pour une peau croustillante.', 'Les wings au Buffalo sauce ont été inventées en 1964 au Anchor Bar de Buffalo, New York.')
) AS v(lesson_title, title, description, emoji, prep_time_min, cook_time_min, servings, difficulty, avg_price_eur, ingredients, instructions, chef_tip, cultural_note)
JOIN public.lessons l ON l.title = v.lesson_title;

-- ============================================================
-- RECIPES FOR VEGAN LESSONS 21-35
-- ============================================================
INSERT INTO public.recipes (id, lesson_id, title, description, emoji, prep_time_min, cook_time_min, servings, difficulty, avg_price_eur, ingredients, instructions, chef_tip, cultural_note)
SELECT gen_random_uuid(), l.id, v.title, v.description, v.emoji, v.prep_time_min, v.cook_time_min, v.servings, v.difficulty, v.avg_price_eur, v.ingredients::jsonb, v.instructions::jsonb, v.chef_tip, v.cultural_note
FROM (VALUES
  ('Le Jackfruit Pulled Pork', 'Jackfruit effiloché en sauce BBQ — substitut de viande bluffant.', '🌿', 10, 35, 4, 'beginner', 5.0,
   '[{"qty":"800g","item":"jackfruit jeune en saumure (conserve)"},{"qty":"200ml","item":"sauce BBQ végane"},{"qty":"1","item":"oignon"},{"qty":"3 gousses","item":"ail"},{"qty":"1 c.c.","item":"paprika fumé"},{"qty":"1 c.c.","item":"cumin"},{"qty":"sel","item":"et poivre"}]',
   '["Égouttez et rincez le jackfruit","Épongez bien avec du papier absorbant","Faites revenir oignon et ail dans l huile","Ajoutez le jackfruit et les épices","Cuisez à feu moyen 15 min en éffilochant avec deux fourchettes","Versez la sauce BBQ","Cuisez encore 10 min jusqu à caramélisation","Servez dans des buns avec coleslaw végétalien"]',
   'Le jackfruit en saumure (pas au sirop) est le seul format utilisable pour cette recette.', 'Le jackfruit pousse en Inde et en Asie du Sud-Est où il est consommé depuis des millénaires comme substitut de viande.'),
  ('Les Falafels Maison', 'Boulettes de pois chiches et herbes fraîches croustillantes.', '🧆', 20, 15, 4, 'intermediate', 4.0,
   '[{"qty":"300g","item":"pois chiches secs trempés 12h"},{"qty":"1","item":"oignon"},{"qty":"3 gousses","item":"ail"},{"qty":"bouquet","item":"de persil et coriandre fraîche"},{"qty":"1 c.c.","item":"cumin"},{"qty":"1 c.c.","item":"coriandre moulue"},{"qty":"1 c.c.","item":"levure chimique"},{"qty":"huile","item":"pour friture"}]',
   '["Ne cuisez pas les pois chiches — utilisez-les crus trempés","Mixez grossièrement avec oignon, ail, herbes et épices","Ajoutez la levure chimique","La texture doit être granuleuse, pas lisse","Réfrigérez 30 min","Formez des boulettes ou disques","Faites frire à 175°C 3-4 min","Servez dans un pain pita avec tahini et légumes"]',
   'Ne pas cuire les pois chiches — ils seraient trop mous et les falafels se déferaient à la friture.', 'Les falafels sont mentionnés dans des textes coptes du IVe siècle — l un des plus anciens fast foods du monde.'),
  ('Le Ramen Végétalien', 'Bouillon dashi kombu-shiitake, nouilles de blé, garnitures vegan.', '🍜', 20, 60, 4, 'intermediate', 7.0,
   '[{"qty":"1 grande pièce","item":"kombu (algue)"},{"qty":"30g","item":"shiitake séchés"},{"qty":"2L","item":"eau froide"},{"qty":"4","item":"portions de ramen"},{"qty":"garnitures:","item":""},{"qty":"200g","item":"tofu ferme grillé"},{"qty":"2","item":"œufs vegan (narutomaki vegan)"},{"qty":"100g","item":"maïs"},{"qty":"feuilles","item":"de nori"},{"qty":"tare:","item":""},{"qty":"4 c.s.","item":"sauce soja"},{"qty":"1 c.s.","item":"miso blanc"}]',
   '["Trempez kombu et shiitake dans l eau froide 30 min","Chauffez doucement à 60°C pendant 30 min (ne jamais bouillir le kombu)","Retirez le kombu, faites bouillir les shiitakes 10 min","Filtrez — c est le dashi végétalien","Faites la tare: soja + miso","Cuisez les ramen selon instructions","Servez bouillon + tare dans les bols","Déposez les garnitures artistiquement"]',
   'Le kombu ne doit jamais bouillir — au-dessus de 80°C, il devient amer et libère des mucilages.', 'Le dashi de kombu est riche en acide glutamique naturel — l umami pur végétalien.')
) AS v(lesson_title, title, description, emoji, prep_time_min, cook_time_min, servings, difficulty, avg_price_eur, ingredients, instructions, chef_tip, cultural_note)
JOIN public.lessons l ON l.title = v.lesson_title;

-- ============================================================
-- EXERCISES FOR CHINESE LESSONS 21-35
-- ============================================================
INSERT INTO public.exercises (id, lesson_id, type, question, options, correct_answer, explanation, order_index)
SELECT gen_random_uuid(), l.id, v.type, v.question, v.options::jsonb, v.correct_answer, v.explanation, v.order_index
FROM (VALUES
  ('Le Mapo Tofu', 'multiple_choice', 'De quelle ville est originaire le mapo tofu ?', '["Chengdu","Beijing","Shanghai","Guangzhou"]', 'Chengdu', 'Le mapo tofu est une spécialité de Chengdu, capitale culinaire du Sichuan.', 1),
  ('Le Mapo Tofu', 'fill_in_blank', 'La pâte de haricots fermentés pimentée du Sichuan s appelle ___', '[]', 'doubanjiang', 'Le doubanjiang est l ingrédient le plus important de nombreux plats sichuanais.', 2),
  ('Les Xiaolongbao', 'multiple_choice', 'Quel est le secret des xiaolongbao pour avoir du bouillon à l intérieur ?', '["Une gelée de bouillon incorporée froide","Du bouillon liquide injecté","Des légumes qui rendent du jus","Un aspic ajouté après cuisson"]', 'Une gelée de bouillon incorporée froide', 'La gelée fond pendant la cuisson vapeur et se transforme en bouillon chaud.', 1),
  ('Les Xiaolongbao', 'fill_in_blank', 'Les xiaolongbao sont la fierté culinaire de ___', '[]', 'Shanghai', 'Shanghai est célèbre pour ses xiaolongbao — chaque restaurant garde sa recette secrète.', 2),
  ('Le Kung Pao Poulet', 'multiple_choice', 'D après qui le kung pao a-t-il été nommé ?', '["Le gouverneur du Sichuan Ding Baozhen","Un cuisinier de la cour impériale","Un moine bouddhiste","Un général de la dynastique Qing"]', 'Le gouverneur du Sichuan Ding Baozhen', 'Ding Baozhen était le gouverneur du Sichuan et son titre de garde impérial était kung pao.', 1),
  ('Le Kung Pao Poulet', 'fill_in_blank', 'Le ___ du Sichuan donne la sensation d engourdissement dans le kung pao', '[]', 'poivre', 'Le poivre du Sichuan (huajiao) contient de l hydroxy-alpha-sanshool qui engourdit les papilles.', 2),
  ('Le Canard Laqué de Pékin', 'multiple_choice', 'Depuis quand le canard laqué est-il servi à la cour impériale ?', '["1330","1644","1800","1912"]', '1330', 'Le canard laqué apparaît dans des textes de la cour de l Empereur Yuan en 1330.', 1),
  ('Le Canard Laqué de Pékin', 'fill_in_blank', 'Le canard laqué de Pékin est servi dans des ___ de blé', '[]', 'crêpes', 'Les crêpes de blé fines sont roulées avec le canard, concombre et sauce hoisin.', 2),
  ('Les Nouilles Dan Dan', 'multiple_choice', 'D où vient le nom dan dan ?', '["Du bâton de porteur de colporteur","D un plat en céramique","D un chef cuisinier","D une ville du Sichuan"]', 'Du bâton de porteur de colporteur', 'Les colporteurs portaient la marmite et les nouilles sur un bâton équilibré (dan dan).', 1),
  ('Les Nouilles Dan Dan', 'fill_in_blank', 'Le légume mariné du Sichuan essentiel aux dan dan s appelle ___', '[]', 'yacai', 'Le yacai est une moutarde marinée du Sichuan qui apporte sel et texture aux dan dan mian.', 2),
  ('Le Char Siu', 'multiple_choice', 'Que signifie char siu en cantonais ?', '["Porc suspendu et rôti","Porc au miel","Porc rouge laqué","Porc à la fumée"]', 'Porc suspendu et rôti', 'Le char siu était traditionnellement suspendu dans le four à rôtir sur des crochets.', 1),
  ('Le Char Siu', 'fill_in_blank', 'Le sucre de malt qui donne la brillance du char siu s appelle ___', '[]', 'maltose', 'Le maltose est moins sucré que le sucre ordinaire et forme une brillance caractéristique.', 2),
  ('Le Hotpot Sichuan', 'multiple_choice', 'Qu est-ce que le mala dans le hotpot sichuan ?', '["Engourdissant-piquant — deux sensations combinées","Très piquant uniquement","Légèrement pimenté","Une herbe aromatique"]', 'Engourdissant-piquant — deux sensations combinées', 'Ma (engourdissement du poivre Sichuan) + la (piquant des piments) = mala, le profil du hotpot.', 1),
  ('Le Hotpot Sichuan', 'fill_in_blank', 'Le hotpot en chinois s appelle ___', '[]', 'huoguo', 'Huoguo signifie littéralement pot chaud ou pot de feu en mandarin.', 2),
  ('Les Raviolis Potstickers', 'multiple_choice', 'Quelle est la technique de cuisson des potstickers ?', '["Griller, puis vapeur avec eau, puis griller encore","Uniquement frire","Cuire à la vapeur uniquement","Griller très longtemps à feu doux"]', 'Griller, puis vapeur avec eau, puis griller encore', 'La technique eau-vapeur-friture donne le dessous croustillant et le dessus vapeur moelleux.', 1),
  ('Les Raviolis Potstickers', 'fill_in_blank', 'Les potstickers en chinois s appellent ___', '[]', 'guotie', 'Guotie signifie coller à la poêle — ce qui leur arrive si on ne surveille pas la cuisson.', 2),
  ('Le Riz Cantonais', 'multiple_choice', 'Qu est-ce que le wok hei ?', '["Le goût fumé de la cuisson au wok très chaud","La sauce soja ajoutée","Le riz cuit à la vapeur","Les épices de la cuisine cantonaise"]', 'Le goût fumé de la cuisson au wok très chaud', 'Le wok hei (souffle du wok) est l arôme légèrement fumé produit par la cuisson à très haute température.', 1),
  ('Le Riz Cantonais', 'fill_in_blank', 'Le riz cantonais doit être ___ et froid pour bien sauter', '[]', 'de la veille', 'Le riz frais est trop humide — les grains collent au lieu de sauter séparément dans le wok.', 2),
  ('La Soupe Wonton', 'multiple_choice', 'Pourquoi mange-t-on des wonton lors des fêtes ?', '["Leur forme rappelle les lingots d or","Ils sont délicieux","Ils sont bon marché","Ils se préparent facilement"]', 'Leur forme rappelle les lingots d or', 'Les wonton pliés ressemblent aux lingots d or — symbole de prospérité en Chine.', 1),
  ('La Soupe Wonton', 'fill_in_blank', 'Le bouillon des wonton doit être ___ et transparent', '[]', 'cristallin', 'Un bouillon cristallin cuit à frémissement révèle la qualité des ingrédients — signe de maîtrise.', 2),
  ('Le Poulet Général Tso', 'multiple_choice', 'Le poulet Général Tso est-il connu en Chine ?', '["Non, c est un plat sino-américain","Oui, dans tout le pays","Oui, dans le Hunan","Oui, à Pékin uniquement"]', 'Non, c est un plat sino-américain', 'Ironiquement, ce plat emblématique de la cuisine chinoise aux USA est pratiquement inconnu en Chine.', 1),
  ('Le Poulet Général Tso', 'fill_in_blank', 'La technique de marinade aux blancs d œuf pour attendrir la viande s appelle ___', '[]', 'velveting', 'Le velveting est une technique chinoise qui donne une texture veloutée à la viande ou aux crevettes.', 2),
  ('Le Congee Cantonais', 'multiple_choice', 'Quand mange-t-on le congee en Chine ?', '["Quand on est malade ou pour le petit-déjeuner","Uniquement pour le dîner","Lors des fêtes uniquement","Le dimanche midi"]', 'Quand on est malade ou pour le petit-déjeuner', 'Le congee est le plat réconfortant des malades et le petit-déjeuner classique en Chine et Hong Kong.', 1),
  ('Le Congee Cantonais', 'fill_in_blank', 'L œuf cuit dans argile et cendres s appelle l œuf ___', '[]', 'centenaire', 'L œuf centenaire (pidan) est cuit pendant des semaines dans un mélange d argile, cendres et sel.', 2),
  ('Les Dumplings Har Gow', 'multiple_choice', 'Pourquoi le har gow est-il le test ultime d un chef dim sum ?', '["Sa pâte translucide révèle toute imperfection","Il est très difficile à cuire","La farce est complexe","Il demande beaucoup de temps"]', 'Sa pâte translucide révèle toute imperfection", "Il est très difficile à cuire', 'Sa pâte translucide révèle toute imperfection', 'La pâte tang fen du har gow est translucide — les plis, l épaisseur, le remplissage sont tous visibles.', 1),
  ('Les Dumplings Har Gow', 'fill_in_blank', 'Har gow signifie ___ rouleau en cantonais', '[]', 'crevette', 'Har = crevette, gow = rouleau/ravioli — c est littéralement le ravioli à la crevette.', 2),
  ('Le Sichuan Boiled Fish', 'multiple_choice', 'Comment s appelle le poisson bouilli sichuanais en mandarin ?', '["Shui zhu yu","Mala yu","Douban yu","Hong shao yu"]', 'Shui zhu yu', 'Shui = eau, zhu = bouillir, yu = poisson — bien que le résultat final soit baigné d huile épicée.', 1),
  ('Le Sichuan Boiled Fish', 'fill_in_blank', 'L huile chaude versée sur les piments en fin de cuisson ___ tous les arômes', '[]', 'libère', 'Le choc thermique de l huile chaude sur le piment et le poivre du Sichuan libère les huiles essentielles.', 2),
  ('Les Rouleaux de Printemps Frits', 'multiple_choice', 'Pourquoi les rouleaux de printemps s appellent-ils ainsi ?', '["Ils étaient mangés au début du printemps","Ils contiennent des légumes de printemps","Leur couleur est verte","Ils sont légers comme le printemps"]', 'Ils étaient mangés au début du printemps', 'Les rouleaux de printemps étaient traditionnellement mangés lors de la fête de Lichun (début du printemps).', 1),
  ('Les Rouleaux de Printemps Frits', 'fill_in_blank', 'La température idéale de l huile pour frire les rouleaux est ___°C', '[]', '180', 'À 180°C, la pâte dore rapidement sans absorber trop d huile — le rouleau reste léger.', 2)
) AS v(lesson_title, type, question, options, correct_answer, explanation, order_index)
JOIN public.lessons l ON l.title = v.lesson_title;

-- ============================================================
-- EXERCISES FOR PASTRY LESSONS 21-35
-- ============================================================
INSERT INTO public.exercises (id, lesson_id, type, question, options, correct_answer, explanation, order_index)
SELECT gen_random_uuid(), l.id, v.type, v.question, v.options::jsonb, v.correct_answer, v.explanation, v.order_index
FROM (VALUES
  ('Le Soufflé au Grand Marnier', 'multiple_choice', 'Pourquoi ne jamais ouvrir le four pendant un soufflé ?', '["Le choc thermique ferait retomber le soufflé","Pour éviter de brûler","Le four deviendrait trop chaud","Pour garder l humidité"]', 'Le choc thermique ferait retomber le soufflé', 'La différence de température entre le four et l air ambiant fait s effondrer les blancs montés.', 1),
  ('Le Soufflé au Grand Marnier', 'fill_in_blank', 'Le soufflé gonfle grâce aux ___ en neige incorporés', '[]', 'blancs', 'Les blancs d œuf montés en neige créent des bulles d air qui se dilatent à la chaleur.', 2),
  ('La Crème Brûlée', 'multiple_choice', 'Comment savoir si la crème brûlée est cuite ?', '["Elle doit trembler légèrement au centre","Elle doit être ferme","Elle doit bouillonner","Le thermomètre indique 100°C"]', 'Elle doit trembler légèrement au centre', 'Une crème brûlée trop ferme au four sera caoutchouteuse — elle finit de cuire en refroidissant.', 1),
  ('La Crème Brûlée', 'fill_in_blank', 'La crème brûlée est cuite dans un ___ pour une cuisson douce et uniforme', '[]', 'bain-marie', 'Le bain-marie maintient une température constante de 90°C maximum, idéale pour les œufs.', 2),
  ('Les Financiers aux Amandes', 'multiple_choice', 'Quel est le secret des financiers ?', '["Le beurre noisette","Le beurre blanc","Le beurre clarifié","Le beurre fondu simple"]', 'Le beurre noisette', 'Le beurre noisette (beurre brun) développe des arômes de noisette et caramel absents du beurre normal.', 1),
  ('Les Financiers aux Amandes', 'fill_in_blank', 'Les financiers ont une forme de ___ qui rappelle les lingots', '[]', 'rectangle', 'La forme rectangulaire en lingot d or a donné son nom à la pâtisserie proche de la Bourse.', 2),
  ('Le Paris-Brest Revisité', 'multiple_choice', 'Pourquoi le Paris-Brest a-t-il une forme de roue ?', '["Il célèbre la course cycliste Paris-Brest","Pour être plus beau","Pour faciliter le service","Par tradition médiévale"]', 'Il célèbre la course cycliste Paris-Brest', 'Le gâteau a été créé en 1910 par Louis Durand pour commémorer la course cycliste.', 1),
  ('Le Paris-Brest Revisité', 'fill_in_blank', 'La crème pralinée est de la crème pâtissière montée avec du ___', '[]', 'pralin', 'Le pralin (amandes et noisettes caramélisées moulues) donne la saveur distinctive du Paris-Brest.', 2),
  ('La Pâte Feuilletée Inversée', 'multiple_choice', 'Combien de couches a une pâte feuilletée classique à 6 tours ?', '["729","512","1024","2048"]', '729', 'À chaque tour double, les couches sont multipliées par 3 — après 6 tours: 3^6 = 729 couches.', 1),
  ('La Pâte Feuilletée Inversée', 'fill_in_blank', 'L action de plier et étaler la pâte pour créer les couches s appelle le ___', '[]', 'tourage', 'Le tourage est l opération fondamentale de la pâte feuilletée — réalisé 6 fois avec repos au froid.', 2),
  ('Les Macarons Italiens', 'multiple_choice', 'Que doit faire la pâte à macarons pendant le macaronnage ?', '["Tomber en ruban continu","Rester ferme","Devenir très liquide","Faire des bulles"]', 'Tomber en ruban continu', 'Le ruban est le signe que la pâte est correctement travaillée — ni trop ferme, ni trop liquide.', 1),
  ('Les Macarons Italiens', 'fill_in_blank', 'Le ___ est le séchage des coques à l air avant d enfourner', '[]', 'croûtage', 'Le croûtage (15-30 min) forme une pellicule sèche qui donne la collerette caractéristique.', 2),
  ('La Tarte au Citron Meringuée', 'multiple_choice', 'À quelle température doit cuire le curd de citron ?', '["83°C","70°C","100°C","60°C"]', '83°C', 'À 83°C, les œufs coagulent sans grainer — c est la limite de la pasteurisation des jaunes.', 1),
  ('La Tarte au Citron Meringuée', 'fill_in_blank', 'La meringue italienne est faite avec un ___ bouillant versé sur les blancs', '[]', 'sirop', 'Le sirop à 118°C pasteurise les blancs et donne une meringue stable et brillante.', 2),
  ('Le Mille-feuille Classique', 'multiple_choice', 'Quand faut-il monter un mille-feuille ?', '["Au dernier moment","Plusieurs heures à l avance","La veille","2 jours avant"]', 'Au dernier moment', 'L humidité de la crème ramollit le feuilletage — monté trop tôt, le mille-feuille perd son croustillant.', 1),
  ('Le Mille-feuille Classique', 'fill_in_blank', 'Le mille-feuille a été inventé en ___ par François Pierre de la Varenne', '[]', '1651', 'La Varenne a décrit cette pâtisserie dans son livre Le Cuisinier François de 1651.', 2),
  ('La Dacquoise aux Noisettes', 'multiple_choice', 'D où vient la dacquoise ?', '["Dax dans les Landes","Bordeaux","Bayonne","Toulouse"]', 'Dax dans les Landes', 'La dacquoise vient de la ville de Dax dans les Landes, région productrice de noisettes.', 1),
  ('La Dacquoise aux Noisettes', 'fill_in_blank', 'Le mélange à parts égales sucre glace et poudre de fruits secs s appelle ___', '[]', 'tant pour tant', 'Le tant pour tant est la base de nombreuses recettes de biscuits meringués aux fruits secs.', 2),
  ('Le Baba au Rhum', 'multiple_choice', 'Qui a inspiré le nom du baba au rhum ?', '["Le roi Stanislas de Pologne","Un chef pâtissier polonais","Un marin polonais","Un cuisinier parisien"]', 'Le roi Stanislas de Pologne', 'Le roi Stanislas Leszczynski, exilé à Paris, aimait tremper son gâteau dans du vin et aurait donné son nom au baba.', 1),
  ('Le Baba au Rhum', 'fill_in_blank', 'Le baba doit être ___ avant d être imbibé pour maximiser l absorption', '[]', 'sec', 'Un baba sec absorbe deux fois plus de sirop qu un baba humide — laissez-le sécher à l air.', 2),
  ('La Religieuse au Café', 'multiple_choice', 'Pourquoi cette pâtisserie s appelle-t-elle la religieuse ?', '["Elle ressemble à une religieuse en habit noir","Elle vient d un couvent","Elle était faite par des sœurs","Elle est austère comme une religieuse"]', 'Elle ressemble à une religieuse en habit noir', 'Les deux choux nappés de fondant brun ressemblent à une religieuse en habit sombre.', 1),
  ('La Religieuse au Café', 'fill_in_blank', 'Le glaçage blanc chauffé à 35°C pour napper les choux s appelle le ___', '[]', 'fondant', 'Le fondant est un sucre cuit et travaillé — chauffé à 35°C il retrouve sa fluidité pour napper.', 2),
  ('Le Fraisier Moderne', 'multiple_choice', 'Qu est-ce que la crème mousseline ?', '["Crème pâtissière montée au beurre","Crème fouettée","Crème pâtissière seule","Beurre monté au fouet"]', 'Crème pâtissière montée au beurre', 'La crème mousseline est une crème pâtissière enrichie de beurre pommade battu — légère et stable.', 1),
  ('Le Fraisier Moderne', 'fill_in_blank', 'Les fraises sont placées ___ la paroi du cercle pour l effet visuel', '[]', 'contre', 'Les fraises coupées visibles contre le cercle sont la signature visuelle du fraisier.', 2),
  ('La Mousse au Chocolat sans Cuisson', 'multiple_choice', 'Qui est la personnalité historique liée à la mousse au chocolat ?', '["Toulouse-Lautrec","Auguste Escoffier","Marie-Antoine Carême","Paul Bocuse"]', 'Toulouse-Lautrec', 'Le peintre Toulouse-Lautrec était un passionné de cuisine et aurait popularisé la mousse au chocolat.', 1),
  ('La Mousse au Chocolat sans Cuisson', 'fill_in_blank', 'On incorpore les blancs en ___ fois pour ne pas casser la mousse', '[]', 'trois', 'Le premier tiers détend le mélange, les deux suivants l aèrent sans trop travailler les blancs.', 2),
  ('Les Éclairs au Chocolat', 'multiple_choice', 'D où vient le nom de l éclair ?', '["La vitesse à laquelle il disparaît","La forme allongée","La brillance du glaçage","L inspiration d un chef"]', 'La vitesse à laquelle il disparaît', 'L éclair se mange si vite qu il disparaît comme un éclair — c est la raison poétique de son nom.', 1),
  ('Les Éclairs au Chocolat', 'fill_in_blank', 'L éclair est la pâtisserie ___ des Français selon les sondages', '[]', 'préférée', 'Les éclairs au chocolat ou au café trustent régulièrement la première place des pâtisseries préférées en France.', 2),
  ('La Galette des Rois Frangipane', 'multiple_choice', 'La frangipane est un mélange de quoi ?', '["Crème d amandes et crème pâtissière","Beurre et amandes seulement","Crème fouettée et pralin","Œufs et sucre"]', 'Crème d amandes et crème pâtissière', 'La frangipane classique est 2/3 crème d amandes + 1/3 crème pâtissière — plus légère que la crème d amandes seule.', 1),
  ('La Galette des Rois Frangipane', 'fill_in_blank', 'La petite figurine cachée dans la galette s appelle la ___', '[]', 'fève', 'À l origine c était une vraie fève de légumineuse — aujourd hui c est une figurine en porcelaine.', 2)
) AS v(lesson_title, type, question, options, correct_answer, explanation, order_index)
JOIN public.lessons l ON l.title = v.lesson_title;

-- ============================================================
-- EXERCISES FOR BBQ LESSONS 21-35
-- ============================================================
INSERT INTO public.exercises (id, lesson_id, type, question, options, correct_answer, explanation, order_index)
SELECT gen_random_uuid(), l.id, v.type, v.question, v.options::jsonb, v.correct_answer, v.explanation, v.order_index
FROM (VALUES
  ('Le Brisket de Texas', 'multiple_choice', 'Combien de temps fume-t-on un brisket de Texas ?', '["12-14 heures","4-5 heures","2-3 heures","24 heures"]', '12-14 heures', 'Le brisket de Texas doit fumer lentement à basse température pour que le collagène se gélatinise.', 1),
  ('Le Brisket de Texas', 'fill_in_blank', 'La croûte sèche qui se forme à la surface du brisket s appelle le ___', '[]', 'bark', 'Le bark est la couche externe caramélisée — signe d un brisket parfaitement fumé.', 2),
  ('Les Ribs St-Louis Style', 'multiple_choice', 'Que signifie la méthode 3-2-1 pour les ribs ?', '["3h fumé, 2h en papier, 1h sans papier","3h marinés, 2h fumés, 1h grill","3 couches de sauce, 2 retournements, 1h repos","3 types de bois, 2h de chaleur, 1 sauce"]', '3h fumé, 2h en papier, 1h sans papier', 'La méthode 3-2-1 garantit des ribs tendres (papier aluminium) avec une finition laquée.', 1),
  ('Les Ribs St-Louis Style', 'fill_in_blank', 'On retire la ___ des ribs côté os pour un meilleur fumage', '[]', 'membrane', 'La membrane (plèvre) imperméable empêche les saveurs de pénétrer — retirez-la systématiquement.', 2),
  ('Le Pulled Pork des Carolines', 'multiple_choice', 'Quelle est la différence de sauce BBQ entre l Est et l Ouest des Carolines ?', '["Est: vinaigre pur, Ouest: vinaigre + tomate","Est: tomate, Ouest: vinaigre","Est: miel, Ouest: moutarde","Aucune différence"]', 'Est: vinaigre pur, Ouest: vinaigre + tomate', 'La querelle de sauce BBQ en Caroline du Nord est une identité régionale forte.', 1),
  ('Le Pulled Pork des Carolines', 'fill_in_blank', 'Le porc effiloché après longue cuisson s appelle ___', '[]', 'pulled pork', 'Pulled pork signifie porc tiré — le collagène fondu rend les fibres si tendres qu elles s effilochent à la main.', 2),
  ('La Volaille à la Bière', 'multiple_choice', 'Quel effet a la bière dans la cuisson beer can chicken ?', '["Crée de la vapeur interne qui hydrate le poulet","Donne du goût à la chair","Caramélise la peau","Réduit le temps de cuisson"]', 'Crée de la vapeur interne qui hydrate le poulet', 'La bière s évapore lentement et maintient le poulet humide de l intérieur pendant la cuisson.', 1),
  ('La Volaille à la Bière', 'fill_in_blank', 'Le mélange d épices sèches appliqué sur la viande avant cuisson s appelle le ___', '[]', 'rub', 'Le rub (frottage) est composé de sel, sucre, épices et herbes — il crée la croûte de saveur.', 2),
  ('Les Burnt Ends de Kansas City', 'multiple_choice', 'D où viennent les burnt ends à Kansas City ?', '["Offerts gratuitement chez Arthur Bryant","Inventés par un chef","Importés du Texas","Tradition amérindienne"]', 'Offerts gratuitement chez Arthur Bryant', 'Arthur Bryant donnait les bouts de brisket plus cuits et plus caramélisés aux clients qui attendaient.', 1),
  ('Les Burnt Ends de Kansas City', 'fill_in_blank', 'Les burnt ends viennent de la partie ___ du brisket, la plus grasse', '[]', 'point', 'Le point (ou deckle) est la partie la plus grasse et la plus riche en collagène du brisket.', 2),
  ('Le Smoked Salmon Gravlax', 'multiple_choice', 'Qu est-ce que le fumage à froid ?', '["Fumage sous 30°C — le produit ne cuit pas","Fumage avec de la glace","Fumage en chambre froide","Fumage très rapide"]', 'Fumage sous 30°C — le produit ne cuit pas', 'Le cold smoking préserve la texture crue du saumon en l imprégnant d arômes de fumée.', 1),
  ('Le Smoked Salmon Gravlax', 'fill_in_blank', 'La planche de ___ est utilisée pour fumer le saumon en cuisson indirecte', '[]', 'cèdre', 'La planche de cèdre dégage des arômes de bois résineux qui parfument délicatement le saumon.', 2),
  ('Les Côtes d Agneau à la Harissa', 'multiple_choice', 'À quelle température à cœur l agneau reste-t-il rosé ?', '["55°C","65°C","72°C","45°C"]', '55°C', 'À 55°C, les fibres d agneau sont chaudes et tendres — au-dessus de 65°C elles deviennent grises et dures.', 1),
  ('Les Côtes d Agneau à la Harissa', 'fill_in_blank', 'La harissa est une pâte de ___ nord-africaine', '[]', 'piments', 'La harissa est faite de piments rouges, ail, huile et épices — originaire de Tunisie.', 2),
  ('Le Smoked Turkey Breast', 'multiple_choice', 'Pourquoi injecter du bouillon dans la poitrine de dinde ?', '["La poitrine est une viande sèche — l injection garantit le moelleux","Pour saler la viande","Pour accélérer la cuisson","Pour donner de la saveur uniquement"]', 'La poitrine est une viande sèche — l injection garantit le moelleux', 'La poitrine de dinde a peu de gras interne — l injection de bouillon beurré compense.', 1),
  ('Le Smoked Turkey Breast', 'fill_in_blank', 'Le bois de ___ donne une fumée douce et fruitée idéale pour la volaille', '[]', 'pommier', 'Le bois de pommier (apple wood) donne une fumée légèrement sucrée parfaite pour la volaille et le porc.', 2),
  ('Les Saucisses Maison au Fumoir', 'multiple_choice', 'Pourquoi utilise-t-on du sel nitrite dans les saucisses ?', '["Conservation et couleur rose","Uniquement pour la couleur","Goût salé plus fort","Texture plus ferme"]', 'Conservation et couleur rose', 'Le sel nitrite (sel de Prague) inhibe les bactéries et donne la couleur rose caractéristique.', 1),
  ('Les Saucisses Maison au Fumoir', 'fill_in_blank', 'Les enveloppes naturelles des saucisses s appellent des ___', '[]', 'boyaux', 'Les boyaux naturels sont des intestins de porc, mouton ou bœuf selon le calibre de saucisse.', 2),
  ('Le Smoked Chicken Wings', 'multiple_choice', 'Pourquoi combiner fumage et grill pour les ailes ?', '["Le fumage seul ne donne pas de peau croustillante","Pour aller plus vite","Pour plus de fumée","Le grill seul n est pas assez chaud"]', 'Le fumage seul ne donne pas de peau croustillante', 'La chaleur basse du fumage cuit mais ne dessèche pas la peau — le grill à haute température croustille.', 1),
  ('Le Smoked Chicken Wings', 'fill_in_blank', 'Le terme américain pour le fumoir est ___', '[]', 'pit', 'Le pit (fosse) était à l origine une fosse en terre où on faisait cuire la viande — le terme est resté.', 2),
  ('Le Bœuf Argenté à la Patagonie', 'multiple_choice', 'Quelle est la caractéristique de l asado argentin ?', '["Cuisson lente à basse température sans couvercle","Cuisson rapide à haute température","Cuisson sous pression","Cuisson dans de l eau"]', 'Cuisson lente à basse température sans couvercle', 'L asado argentin valorise le feu, le temps et la patience — impossible de le presser.', 1),
  ('Le Bœuf Argenté à la Patagonie', 'fill_in_blank', 'Le gril argentin s appelle la ___', '[]', 'parrilla', 'La parrilla est le gril à braises argentin — la pièce maîtresse de chaque foyer argentin.', 2),
  ('Les Légumes Grillés Fumés', 'multiple_choice', 'Comment sont meilleurs les légumes grillés fumés ?', '["À température ambiante avec huile d olive","Chauds sortant du feu","Froids sortant du réfrigérateur","Dans une sauce"]', 'À température ambiante avec huile d olive', 'Les arômes du fumage s expriment mieux à température ambiante qu à chaud ou froid.', 1),
  ('Les Légumes Grillés Fumés', 'fill_in_blank', 'Chaque bois de fumage apporte des ___ différents aux aliments', '[]', 'arômes', 'Cerisier = doux et fruité, hickory = intense, mesquite = fort, pommier = sucré et léger.', 2),
  ('La Côte de Bœuf Tomahawk', 'multiple_choice', 'Qu est-ce que la technique reverse sear ?', '["Cuisson au four d abord puis saisir au grill","Saisir d abord puis finir au four","Cuisson uniquement à feu vif","Cuisson sous vide"]', 'Cuisson au four d abord puis saisir au grill', 'Le reverse sear cuit uniformément la viande au four et crée la croûte Maillard au grill.', 1),
  ('La Côte de Bœuf Tomahawk', 'fill_in_blank', 'La côte tomahawk a un os de ___ cm qui évoque la hache amérindienne', '[]', '30 à 40', 'L os extra-long du tomahawk est gardé entier — il sert de manche lors de la découpe.', 2),
  ('Le Smoked Beef Short Ribs', 'multiple_choice', 'Comment savoir si les beef short ribs sont prêts ?', '["Une sonde passe sans résistance à 95°C","Le thermomètre indique 75°C","Après 8h de cuisson exactement","La viande change de couleur"]', 'Une sonde passe sans résistance à 95°C', 'Le probe tender (sonde sans résistance) signifie que le collagène s est transformé en gélatine.', 1),
  ('Le Smoked Beef Short Ribs', 'fill_in_blank', 'Les beef short ribs sont aussi appelées les côtes ___', '[]', 'dinosaures', 'Leur taille gigantesque (800g par côte) leur a valu le surnom de dinosaur ribs.', 2),
  ('La Plancha aux Fruits de Mer', 'multiple_choice', 'D où vient la technique de la plancha ?', '["Pays basque espagnol","Provence française","Catalogne","Andalousie"]', 'Pays basque espagnol', 'La plancha est une tradition culinaire basque — cuisson rapide à contact direct sur métal épais.', 1),
  ('La Plancha aux Fruits de Mer', 'fill_in_blank', 'La plancha doit être au ___ de sa chaleur pour saisir instantanément', '[]', 'maximum', 'Une plancha très chaude saisit les fruits de mer en secondes — trop froide, ils cuisent au lieu de griller.', 2)
) AS v(lesson_title, type, question, options, correct_answer, explanation, order_index)
JOIN public.lessons l ON l.title = v.lesson_title;

-- ============================================================
-- EXERCISES FOR VEGAN LESSONS 21-35
-- ============================================================
INSERT INTO public.exercises (id, lesson_id, type, question, options, correct_answer, explanation, order_index)
SELECT gen_random_uuid(), l.id, v.type, v.question, v.options::jsonb, v.correct_answer, v.explanation, v.order_index
FROM (VALUES
  ('Le Jackfruit Pulled Pork', 'multiple_choice', 'Quel type de jackfruit utilise-t-on pour le pulled pork ?', '["Jeune en saumure","Mûr au sirop","Séché","Congelé"]', 'Jeune en saumure', 'Le jackfruit mûr est sucré et fruité — le jeune en saumure est neutre et effilochable comme de la viande.', 1),
  ('Le Jackfruit Pulled Pork', 'fill_in_blank', 'Le jackfruit est natif d ___ du Sud', '[]', 'Asie', 'Le jackfruit (fruit du jacquier) est le plus grand fruit comestible du monde, originaire d Inde et d Asie.', 2),
  ('Le Seitan Teriyaki', 'multiple_choice', 'Le seitan est fabriqué à partir de quoi ?', '["Gluten de blé","Soja","Pois chiches","Lentilles"]', 'Gluten de blé', 'Le seitan est la protéine du gluten de blé — riche en protéines et avec une texture proche de la viande.', 1),
  ('Le Seitan Teriyaki', 'fill_in_blank', 'Le seitan est consommé depuis des siècles dans les monastères ___', '[]', 'bouddhistes', 'Le bouddhisme interdit la viande — le seitan est né dans les monastères bouddhistes comme alternative.', 2),
  ('Les Burgers de Haricots Noirs', 'multiple_choice', 'Pourquoi réfrigérer les galettes de haricots avant cuisson ?', '["Pour qu elles tiennent mieux","Pour les attendrir","Pour gagner du temps","Pour les mariner"]', 'Pour qu elles tiennent mieux', 'Le froid raffermit les amidons — les galettes ne s effondrent pas à la cuisson.', 1),
  ('Les Burgers de Haricots Noirs', 'fill_in_blank', 'La graine de lin moulue mélangée à de l eau remplace les ___ dans les recettes véganes', '[]', 'œufs', 'Le flax egg (lin + eau) crée un gel visqueux qui lie les ingrédients comme un œuf.', 2),
  ('Le Curry de Chou-fleur Rôti', 'multiple_choice', 'Pourquoi rôtir le chou-fleur entier avant de le mettre dans le curry ?', '["Il développe une saveur de noisette","Pour le cuire complètement","Pour changer sa couleur","Pour le ramollir"]', 'Il développe une saveur de noisette', 'La caramélisation à haute température crée des arômes de noisette — impossible avec le chou-fleur bouilli.', 1),
  ('Le Curry de Chou-fleur Rôti', 'fill_in_blank', 'Une tranche épaisse de chou-fleur grillée comme un steak s appelle un ___', '[]', 'cauliflower steak', 'Le cauliflower steak est une coupe gastronomique qui valorise le chou-fleur comme pièce principale.', 2),
  ('Le Poke Bowl aux Algues', 'multiple_choice', 'Que signifie poke en hawaiien ?', '["Couper en morceaux","Mélanger","Assaisonner","Marinader"]', 'Couper en morceaux', 'Poke décrit la façon dont le poisson ou le tofu est coupé en petits cubes dans ce plat.', 1),
  ('Le Poke Bowl aux Algues', 'fill_in_blank', 'Le tofu doit être ___ 1h avant d absorber une marinade', '[]', 'pressé', 'Le tofu contient beaucoup d eau — si on ne le presse pas, il expulse la marinade au lieu de l absorber.', 2),
  ('Les Falafels Maison', 'multiple_choice', 'Pourquoi utiliser des pois chiches secs (trempés) plutôt qu en conserve ?', '["Sinon les falafels se désintègrent à la friture","Les conserves ne vont pas dans les falafels","Les secs sont moins chers","Pour le goût"]', 'Sinon les falafels se désintègrent à la friture', 'Les pois chiches en conserve sont trop mous — les falafels tombent en morceaux dans l huile.', 1),
  ('Les Falafels Maison', 'fill_in_blank', 'La purée de sésame servie avec les falafels s appelle le ___', '[]', 'tahini', 'Le tahini est de la pâte de sésame — sauce de base de toute la cuisine du Moyen-Orient.', 2),
  ('Le Ramen Végétalien', 'multiple_choice', 'Pourquoi ne jamais faire bouillir le kombu ?', '["Il devient amer au-dessus de 80°C","Il perd ses minéraux","Il colore le bouillon","Il prend trop de place"]', 'Il devient amer au-dessus de 80°C', 'Le kombu libère des mucilages amers à ébullition — infusez-le toujours en dessous de 80°C.', 1),
  ('Le Ramen Végétalien', 'fill_in_blank', 'La sauce de concentration pour assaisonner le bouillon de ramen s appelle la ___', '[]', 'tare', 'La tare est ajoutée dans le bol avant le bouillon — chaque ramen style a sa propre tare.', 2),
  ('Le Gâteau au Chocolat Végétalien', 'multiple_choice', 'Qu est-ce que l aquafaba ?', '["Eau de conserve des pois chiches","Eau alcaline","Jus de soja","Eau de trempage des haricots"]', 'Eau de conserve des pois chiches', 'L aquafaba contient des protéines et amidons qui montent en neige comme des blancs d œuf.', 1),
  ('Le Gâteau au Chocolat Végétalien', 'fill_in_blank', 'La réaction du vinaigre et du ___ remplace la levée des œufs dans la pâtisserie végane', '[]', 'bicarbonate', 'Le bicarbonate + acide (vinaigre ou citron) produit du CO2 qui fait lever la pâte comme les œufs.', 2),
  ('Le Tartare de Betterave', 'multiple_choice', 'Comment couper la betterave pour le tartare ?', '["En brunoise — petits dés de 2-3mm","En tranches fines","En julienne","Au robot mixeur"]', 'En brunoise — petits dés de 2-3mm', 'La brunoise fine imite la texture du tartare de bœuf — c est la coupe appropriée.', 1),
  ('Le Tartare de Betterave', 'fill_in_blank', 'La brunoise est une coupe en tout petits dés de ___ mm', '[]', '2 à 3', 'La brunoise est la coupe culinaire la plus fine — elle demande un bon couteau et de la précision.', 2),
  ('La Quiche Végane aux Légumes', 'multiple_choice', 'Quel sel donne un goût d œuf au tofu soyeux ?', '["Kala namak (sel noir indien)","Sel de mer","Fleur de sel","Sel rose de l Himalaya"]', 'Kala namak (sel noir indien)', 'Le kala namak est un sel volcanique soufré — l odeur et le goût soufré imitent l œuf cuit.', 1),
  ('La Quiche Végane aux Légumes', 'fill_in_blank', 'Le tofu à haute teneur en eau avec texture crémeuse s appelle le tofu ___', '[]', 'soyeux', 'Le tofu soyeux (silken tofu) a une texture de crème épaisse — parfait pour les flans et crèmes.', 2),
  ('Les Rouleaux de Printemps Frais', 'multiple_choice', 'Comment ramollir les galettes de riz ?', '["Tremper 10 secondes dans de l eau tiède","Les cuire à la vapeur","Les faire bouillir","Les laisser tremper 5 minutes"]', 'Tremper 10 secondes dans de l eau tiède', 'La galette finit de ramollir pendant le roulage — trop molle, elle colle et se déchire.', 1),
  ('Les Rouleaux de Printemps Frais', 'fill_in_blank', 'Les rouleaux frais vietnamiens s appellent ___', '[]', 'gỏi cuốn', 'Gỏi cuốn sont les rouleaux frais vietnamiens — à différencier des chả giò (rouleaux frits).', 2),
  ('Le Cheesecake Végétalien', 'multiple_choice', 'Combien de temps tremper les cajous pour le cheesecake ?', '["Au moins 8 heures","30 minutes","2 heures","24 heures maximum"]', 'Au moins 8 heures', 'Les cajous trempés 8h+ se mixent en crème lisse — insuffisamment trempés, la texture reste granuleuse.', 1),
  ('Le Cheesecake Végétalien', 'fill_in_blank', 'Le cheesecake vegán est sans ___ — la texture est obtenue par réfrigération', '[]', 'cuisson', 'Le no-bake cheesecake prend au réfrigérateur ou au congélateur — pas de four nécessaire.', 2),
  ('Le Buddha Bowl Protéiné', 'multiple_choice', 'Quelle est la philosophie du buddha bowl ?', '["Plénitude et équilibre — grains, protéines, légumes, sauce","Minimalisme","Toujours végétalien","Contient nécessairement du bouddha"]', 'Plénitude et équilibre — grains, protéines, légumes, sauce', 'Le buddha bowl représente un repas complet et équilibré en un seul bol.', 1),
  ('Le Buddha Bowl Protéiné', 'fill_in_blank', 'Les fèves de soja jeunes en cosse riches en protéines s appellent ___', '[]', 'edamame', 'L edamame (枝豆 — haricot sur branche) est la fève de soja récoltée jeune, riche en protéines complètes.', 2),
  ('La Soupe Miso aux Légumes', 'multiple_choice', 'Pourquoi ne jamais faire bouillir le miso ?', '["Pour préserver ses probiotiques","Pour garder sa couleur","Pour la sécurité alimentaire","Pour éviter l amertume"]', 'Pour préserver ses probiotiques', 'La chaleur au-dessus de 60°C détruit les bactéries bénéfiques du miso fermenté.', 1),
  ('La Soupe Miso aux Légumes', 'fill_in_blank', 'L algue verte séchée réhydratée dans le bouillon s appelle ___', '[]', 'wakamé', 'Le wakamé (Undaria pinnatifida) est l algue la plus consommée dans la soupe miso traditionnelle.', 2),
  ('Le Tiramisu Végétalien', 'multiple_choice', 'Qu est-ce qui remplace le mascarpone dans le tiramisu végétalien ?', '["Crème de cajou trempés","Tofu soyeux","Crème de coco","Margarine fouettée"]', 'Crème de cajou trempés', 'La crème de cajou trempés et mixés imite la richesse crémeuse du mascarpone.', 1),
  ('Le Tiramisu Végétalien', 'fill_in_blank', 'L aquafaba montée en neige remplace les ___ dans le tiramisu végétalien', '[]', 'blancs d œuf', 'L aquafaba des pois chiches monte en neige ferme et stable — indistinguable des blancs d œuf pour les yeux.', 2)
) AS v(lesson_title, type, question, options, correct_answer, explanation, order_index)
JOIN public.lessons l ON l.title = v.lesson_title;
