-- Recipes for Chinese, Pastry, BBQ, Vegan lessons 36-50 (batch 6)

-- ==================== CHINESE RECIPES ====================
INSERT INTO public.recipes (id, lesson_id, title, description, emoji, prep_time_min, cook_time_min, servings, difficulty, avg_price_eur, ingredients, instructions, chef_tip, cultural_note)
SELECT gen_random_uuid(), l.id, v.title, v.description, v.emoji, v.prep_time_min, v.cook_time_min, v.servings, v.difficulty, v.avg_price_eur, v.ingredients::jsonb, v.instructions::jsonb, v.chef_tip, v.cultural_note
FROM (VALUES
  ('Le Mapo Tofu', 'Mapo Tofu Authentique du Sichuan', 'Ce plat mythique du Sichuan marie tofu soyeux, porc haché et sauce doubanjiang dans une préparation engourdissante et pimentée.', '🌶️', 10, 20, 4, 'intermediate', 6.50,
   '[{"qty":"400g","item":"tofu soyeux"},{"qty":"150g","item":"porc haché"},{"qty":"3 cs","item":"doubanjiang (pâte de haricots pimentés)"},{"qty":"2","item":"gousses d''ail émincées"},{"qty":"2 cm","item":"gingembre frais râpé"},{"qty":"1 cs","item":"sauce soja"},{"qty":"1 cc","item":"poivre du Sichuan moulu"},{"qty":"200ml","item":"bouillon de poulet"},{"qty":"1 cc","item":"fécule de maïs diluée"},{"qty":"2 cs","item":"huile de sésame"},{"qty":"2","item":"tiges de ciboulette émincées"}]',
   '["Coupez le tofu en cubes de 2 cm, égouttez-le 10 minutes sur du papier absorbant.","Faites revenir le porc haché dans un wok à feu vif jusqu''à ce qu''il soit bien doré.","Ajoutez le doubanjiang, l''ail et le gingembre, faites revenir 2 minutes pour libérer les arômes.","Versez le bouillon, ajoutez la sauce soja et le tofu délicatement.","Laissez mijoter 5 minutes puis épaississez avec la fécule diluée.","Terminez avec le poivre du Sichuan moulu et l''huile de sésame.","Garnissez de ciboulette et servez immédiatement sur du riz blanc."]',
   'Ajoutez le poivre du Sichuan juste avant de servir pour préserver son effet anesthésiant.', 'Le mapo tofu est né dans une gargote de Chengdu tenue par une vieille femme au visage grêlé, "mapo" signifiant "vieille dame grêlée".'),
  ('Le Char Siu', 'Char Siu Cantonais Laqué', 'Ce porc rôti laqué au miel et cinq épices, avec sa couleur rouge caractéristique, est l''emblème de la charcuterie cantonaise.', '🍖', 720, 40, 4, 'intermediate', 9.00,
   '[{"qty":"800g","item":"épaule ou filet de porc"},{"qty":"3 cs","item":"sauce hoisin"},{"qty":"2 cs","item":"sauce soja sucrée"},{"qty":"2 cs","item":"miel"},{"qty":"1 cs","item":"maltose"},{"qty":"1 cc","item":"cinq épices en poudre"},{"qty":"2","item":"gousses d''ail émincées"},{"qty":"1 cs","item":"huile de sésame"},{"qty":"2 cc","item":"colorant rouge alimentaire (facultatif)"}]',
   '["Mélangez tous les ingrédients de la marinade dans un bol.","Incisez légèrement le porc pour que la marinade pénètre.","Faites mariner au minimum 12h (idéalement 24h) au réfrigérateur.","Préchauffez le four à 200°C avec un plat d''eau dans le bas.","Disposez le porc sur une grille et faites rôtir 20 minutes.","Badigeonnez de marinade, retournez et faites rôtir encore 15 minutes.","Appliquez une dernière couche de miel mélangé au maltose et caramélisez 5 minutes sous le gril.","Laissez reposer 10 minutes avant de trancher."]',
   'Le maltose mélangé au miel donne un glaçage plus brillant et qui tient mieux que le miel seul.', 'Le char siu est vendu dans des boucheries cantonaises suspendues sous des crochets dorés, le spectacle visuel le plus appétissant de Hong Kong.'),
  ('Le Riz Cantonais', 'Riz Cantonnais Complet', 'Ce riz sauté classique avec crevettes, jambon, petits pois, carottes et œufs brouillés est un plat complet emblématique de la cuisine cantonaise.', '🍳', 15, 10, 4, 'beginner', 5.50,
   '[{"qty":"400g","item":"riz cuit de la veille (froid)"},{"qty":"150g","item":"crevettes décortiquées"},{"qty":"100g","item":"jambon coupé en dés"},{"qty":"2","item":"carottes coupées en dés"},{"qty":"100g","item":"petits pois surgelés"},{"qty":"3","item":"œufs battus"},{"qty":"3 cs","item":"sauce soja"},{"qty":"1 cs","item":"huile de sésame"},{"qty":"2 cs","item":"huile neutre"},{"qty":"2","item":"tiges de ciboulette émincées"},{"qty":"sel et poivre","item":"selon goût"}]',
   '["Faites chauffer le wok à feu maximum jusqu''à ce qu''il fume.","Ajoutez l''huile neutre et faites sauter les crevettes 2 minutes, réservez.","Dans le même wok très chaud, faites sauter carottes et petits pois 2 minutes.","Poussez les légumes sur le côté et versez les œufs battus au centre.","Brouiller rapidement les œufs puis mélangez avec les légumes.","Ajoutez le riz froid émietté et sautez à feu maximum en remuant constamment.","Incorporez jambon et crevettes, assaisonnez de sauce soja.","Terminez avec l''huile de sésame et la ciboulette."]',
   'Ne remplissez pas trop le wok: cuisez en deux fois si nécessaire pour maintenir la chaleur maximale.', 'Le riz cantonais représente l''art du wok hei: cette saveur fumée obtenue par la réaction du wok ultra-chaud est le signe d''un chef maîtrisant parfaitement la cuisson.'),
  ('Le Congee de Poulet', 'Congee de Poulet Réconfortant', 'Cette bouillie de riz crémeuse cuite longtemps avec bouillon de poulet, gingembre et ciboulette est le plat réconfortant par excellence de la cuisine chinoise.', '🍚', 10, 60, 4, 'beginner', 4.50,
   '[{"qty":"200g","item":"riz à grain rond"},{"qty":"1","item":"carcasse de poulet ou 4 pilons"},{"qty":"1.5L","item":"bouillon de poulet"},{"qty":"4 cm","item":"gingembre frais tranché"},{"qty":"2","item":"tiges de ciboulette"},{"qty":"2 cs","item":"sauce soja"},{"qty":"1 cs","item":"huile de sésame"},{"qty":"sel","item":"selon goût"},{"qty":"poivre blanc","item":"selon goût"},{"qty":"optionnel","item":"œufs de caille, cacahuètes, youtiao (beignets de riz)"}]',
   '["Rincez le riz plusieurs fois jusqu''à ce que l''eau soit claire.","Dans une grande casserole, portez le bouillon avec le gingembre à ébullition.","Ajoutez le riz et le poulet, réduisez à feu doux.","Faites cuire à découvert 45-60 minutes en remuant régulièrement.","Le congee doit avoir une consistance crémeuse, presque comme une soupe épaisse.","Retirez la carcasse, effilochez la chair de poulet et remettez-la dans le congee.","Assaisonnez avec sauce soja, sel et poivre blanc.","Servez garni d''huile de sésame et ciboulette émincée."]',
   'Pour plus d''onctuosité, ajoutez une cuillère de graisse de poulet ou d''huile neutre en fin de cuisson.', 'En Chine, le congee est le plat des malades, des nouveau-nés et des personnes âgées: simple, nourrissant et facile à digérer, il est préparé depuis plus de 2 000 ans.'),
  ('La Fondue Chinoise Hot Pot', 'Hot Pot de Bœuf et Légumes', 'Ce repas convivial autour d''un bouillon frémissant où chacun cuit ses propres tranches de bœuf, légumes et tofu est un festin social authentique.', '🫕', 20, 30, 4, 'beginner', 15.00,
   '[{"qty":"400g","item":"bœuf en fines tranches (ou agneau)"},{"qty":"200g","item":"tofu ferme en cubes"},{"qty":"200g","item":"champignons shiitake"},{"qty":"1","item":"chou chinois émincé"},{"qty":"200g","item":"vermicelles de riz"},{"qty":"2L","item":"bouillon de bœuf ou poulet"},{"qty":"3 cm","item":"gingembre tranché"},{"qty":"2","item":"tiges de ciboule"},{"qty":"3 cs","item":"tahini"},{"qty":"2 cs","item":"sauce soja"},{"qty":"1 cs","item":"vinaigre de riz"},{"qty":"1 cc","item":"huile de piment"}]',
   '["Préparez le bouillon: faites chauffer le bouillon avec gingembre et ciboule dans le hot pot ou une grande casserole.","Préparez la sauce trempette: mélangez tahini, sauce soja, vinaigre de riz et huile de piment.","Disposez tous les ingrédients crus sur la table dans des assiettes séparées.","Portez le bouillon à ébullition sur le réchaud de table.","Chaque convive cuit ses aliments à sa convenance dans le bouillon frémissant.","La viande prend 30 secondes, les légumes 2-3 minutes, le tofu 3-4 minutes.","Trempez dans la sauce et dégustez immédiatement.","En fin de repas, le bouillon enrichi peut être consommé comme soupe."]',
   'Congelez légèrement la viande avant de la trancher pour obtenir des lamelles ultra-fines.', 'Le hot pot est l''expérience sociale par excellence en Chine: on passe des heures à table, à parler et à manger, le bouillon qui se bonifie au fil des aliments cuits.')
) AS v(lesson_title, title, description, emoji, prep_time_min, cook_time_min, servings, difficulty, avg_price_eur, ingredients, instructions, chef_tip, cultural_note)
JOIN public.lessons l ON l.title = v.lesson_title;

-- ==================== PASTRY RECIPES ====================
INSERT INTO public.recipes (id, lesson_id, title, description, emoji, prep_time_min, cook_time_min, servings, difficulty, avg_price_eur, ingredients, instructions, chef_tip, cultural_note)
SELECT gen_random_uuid(), l.id, v.title, v.description, v.emoji, v.prep_time_min, v.cook_time_min, v.servings, v.difficulty, v.avg_price_eur, v.ingredients::jsonb, v.instructions::jsonb, v.chef_tip, v.cultural_note
FROM (VALUES
  ('La Tarte au Citron Meringuée', 'Tarte au Citron Meringuée Classique', 'Cette tarte iconique associe une pâte sablée croustillante, une crème au citron vif et acidulé et une meringue italienne brillante et moelleuse.', '🍋', 45, 35, 8, 'intermediate', 7.00,
   '[{"qty":"200g","item":"farine"},{"qty":"100g","item":"beurre froid en dés"},{"qty":"50g","item":"sucre glace"},{"qty":"1","item":"jaune d''œuf"},{"qty":"4","item":"citrons (zeste et jus)"},{"qty":"200g","item":"sucre"},{"qty":"4","item":"œufs entiers"},{"qty":"150g","item":"beurre"},{"qty":"3","item":"blancs d''œufs (meringue)"},{"qty":"150g","item":"sucre semoule (meringue)"},{"qty":"50ml","item":"eau (meringue)"}]',
   '["Préparez la pâte sablée: sablez farine et beurre, ajoutez sucre glace et jaune d''œuf, formez une boule, réfrigérez 30 minutes.","Étalez la pâte, foncez un moule de 24 cm, piquez et cuisez à blanc 20 minutes à 180°C.","Crème citron: fouettez œufs, sucre, zestes et jus de citron dans une casserole.","Cuisez à feu doux en remuant jusqu''à épaississement (82°C), hors du feu incorporez le beurre.","Versez la crème dans le fond de tarte cuit, réfrigérez 2 heures.","Meringue italienne: cuisez sucre et eau à 121°C, versez en filet sur les blancs montés.","Fouettez jusqu''à refroidissement, garnissez la tarte et dorez au chalumeau."]',
   'Zestez les citrons avant de les presser: les zestes contiennent les huiles essentielles les plus parfumées.', 'La tarte au citron meringuée est née aux États-Unis au XIXe siècle sous le nom "Lemon meringue pie" avant d''être perfectionnée par la pâtisserie française.'),
  ('Les Macarons Parisiens', 'Macarons Parisiens à la Vanille et Ganache', 'Ces délicates coques de meringue aux amandes garnies d''une ganache crémeuse à la vanille sont le summum de la pâtisserie française.', '🫐', 40, 15, 30, 'advanced', 12.00,
   '[{"qty":"150g","item":"farine d''amandes"},{"qty":"150g","item":"sucre glace"},{"qty":"110g","item":"blancs d''œufs vieillis (divisés en 55g)"},{"qty":"150g","item":"sucre semoule"},{"qty":"50ml","item":"eau"},{"qty":"200ml","item":"crème entière"},{"qty":"200g","item":"chocolat blanc"},{"qty":"2","item":"gousses de vanille"},{"qty":"20g","item":"beurre"}]',
   '["Mixez finement farine d''amandes et sucre glace (tant-pour-tant), tamisez.","Faites un sirop: cuisez sucre et eau à 121°C.","Montez 55g de blancs en neige, versez le sirop en filet en fouettant (meringue italienne).","Ajoutez les 55g de blancs crus au tant-pour-tant, incorporez la meringue (macaronage).","Pochez des cercles de 3 cm sur papier sulfurisé.","Laissez croûter 30-45 minutes à température ambiante.","Cuisez 13-14 minutes à 150°C. Laissez refroidir complètement.","Ganache: chauffez la crème avec la vanille, versez sur le chocolat blanc, ajoutez le beurre.","Réfrigérez la ganache puis pochez entre deux coques. Attendez 24h avant de déguster."]',
   'Les blancs "vieillis" (séparés 24-48h avant) sont moins humides et donnent de meilleures coques.', 'Ladurée popularisa le macaron parisien bicolore au début du XXe siècle; Pierre Hermé le révolutionna dans les années 1990 avec des saveurs inédites.'),
  ('La Bûche de Noël', 'Bûche de Noël au Chocolat', 'Cette bûche festive associe une génoise au cacao légère, une crème au beurre au chocolat et une décoration façon écorce d''arbre.', '🪵', 60, 20, 8, 'intermediate', 10.00,
   '[{"qty":"4","item":"œufs"},{"qty":"120g","item":"sucre"},{"qty":"100g","item":"farine"},{"qty":"20g","item":"cacao en poudre"},{"qty":"200g","item":"beurre mou"},{"qty":"150g","item":"sucre glace"},{"qty":"100g","item":"chocolat noir fondu"},{"qty":"2 cs","item":"cacao amer"},{"qty":"100ml","item":"sirop de sucre (pour imbiber)"},{"qty":"50ml","item":"rhum ou extrait de vanille"}]',
   '["Génoise: fouettez œufs et sucre jusqu''à tripler de volume (5 minutes au batteur).","Incorporez délicatement farine et cacao tamisés.","Étalez sur une plaque recouverte de papier sulfurisé, cuisez 10 min à 180°C.","Retournez sur un torchon humide, roulez encore chaud, laissez refroidir enroulé.","Crème au beurre: fouettez beurre mou et sucre glace, ajoutez chocolat fondu refroidi.","Déroulez la génoise, imbibez de sirop vanillé ou rhum.","Étalez 2/3 de la crème, roulez à nouveau, réfrigérez 30 minutes.","Nappez avec le reste de crème, striez avec une fourchette pour imiter l''écorce.","Décorez de champignons meringués, sucre glace et décors en chocolat."]',
   'Assurez-vous que la génoise est bien imbibée de sirop pour éviter qu''elle se fissure en la roulant.', 'La bûche de Noël commémore l''ancienne tradition germanique de brûler une énorme bûche dans la cheminée pendant les 12 jours de Noël pour chasser les mauvais esprits.'),
  ('Le Kouign-Amann', 'Kouign-Amann Breton Authentique', 'Cette pâte levée feuilletée, généreusement beurrée et sucrée, caramélisée à la cuisson: le gâteau breton le plus indécent et délicieux.', '🧈', 30, 40, 8, 'intermediate', 5.50,
   '[{"qty":"300g","item":"farine"},{"qty":"7g","item":"levure boulangère sèche"},{"qty":"150ml","item":"eau tiède"},{"qty":"1 cc","item":"sel"},{"qty":"200g","item":"beurre demi-sel froid"},{"qty":"200g","item":"sucre en poudre"},{"qty":"1","item":"pincée de fleur de sel (finition)"}]',
   '["Mélangez farine, levure, sel et eau, pétrissez 5 minutes pour une pâte souple. Laissez lever 1h.","Sur un plan fariné, étalez la pâte en rectangle. Posez le beurre froid en dés au centre.","Repliez la pâte sur le beurre, étalez en rectangle, pliez en trois (tour simple). Réfrigérez 15 min.","Répétez l''opération 2 fois pour 3 tours en tout.","Étalez la pâte en cercle, parsemez la moitié du sucre.","Pliez en quatre, parsemez le reste du sucre, pliez à nouveau.","Étalez en cercle de 24 cm, déposez dans un moule beurré.","Laissez lever 30 minutes, parsemez de fleur de sel.","Cuisez 35-40 minutes à 200°C jusqu''à caramélisation profonde.","Retournez immédiatement sur une grille: le caramel coule à l''envers."]',
   'Ne vous alarmez pas si le caramel déborde: c''est normal et délicieux. Protégez le fond du four avec une feuille d''aluminium.', 'Le kouign-amann fut accidentellement créé en 1860 par Yves-René Scordia qui n''avait que de la pâte à pain, du beurre et du sucre dans sa boulangerie de Douarnenez.'),
  ('La Charlotte aux Framboises', 'Charlotte aux Framboises Légère', 'Ce dessert élégant tapissé de biscuits à la cuillère imbibés de framboises et garni d''une bavaroise framboise est une fraîcheur estivale inoubliable.', '🍓', 30, 0, 6, 'intermediate', 11.00,
   '[{"qty":"24","item":"biscuits à la cuillère"},{"qty":"500g","item":"framboises fraîches ou surgelées"},{"qty":"3 cs","item":"sucre"},{"qty":"4","item":"feuilles de gélatine"},{"qty":"300ml","item":"crème entière froide"},{"qty":"200ml","item":"lait entier"},{"qty":"3","item":"jaunes d''œufs"},{"qty":"80g","item":"sucre (pour la bavaroise)"},{"qty":"1","item":"gousse de vanille"},{"qty":"100ml","item":"coulis de framboise (pour imbiber)"}]',
   '["Faites un coulis: mixez 200g de framboises avec 2 cs de sucre, passez au tamis.","Réservez quelques framboises pour la décoration.","Trempez rapidement les biscuits dans le coulis dilué avec un peu d''eau.","Tapissez le fond et les bords d''un moule à charlotte de biscuits imbibés.","Crème anglaise: faites chauffer le lait avec la vanille, versez sur jaunes et sucre fouettés, cuisez à 82°C.","Faites tremper la gélatine dans l''eau froide, incorporez-la à la crème anglaise chaude.","Laissez refroidir jusqu''à ce que le mélange commence à se gélifier (consistance miel).","Fouettez la crème froide en chantilly souple, incorporez délicatement à la bavaroise.","Versez la moitié dans le moule, ajoutez des framboises, versez le reste.","Refermez avec des biscuits, réfrigérez au minimum 4 heures.","Démoulez, décorez de framboises fraîches et d''un filet de coulis."]',
   'Un moule à charlotte avec des bords droits est essentiel pour un démoulage net et une présentation parfaite.', 'La charlotte doit son nom à la reine Charlotte, épouse de George III d''Angleterre, grande amateur de desserts; c''est Antonin Carême qui en créa la version moderne au XIXe siècle.')
) AS v(lesson_title, title, description, emoji, prep_time_min, cook_time_min, servings, difficulty, avg_price_eur, ingredients, instructions, chef_tip, cultural_note)
JOIN public.lessons l ON l.title = v.lesson_title;

-- ==================== BBQ RECIPES ====================
INSERT INTO public.recipes (id, lesson_id, title, description, emoji, prep_time_min, cook_time_min, servings, difficulty, avg_price_eur, ingredients, instructions, chef_tip, cultural_note)
SELECT gen_random_uuid(), l.id, v.title, v.description, v.emoji, v.prep_time_min, v.cook_time_min, v.servings, v.difficulty, v.avg_price_eur, v.ingredients::jsonb, v.instructions::jsonb, v.chef_tip, v.cultural_note
FROM (VALUES
  ('Le Brisket de Texas', 'Brisket de Texas Fumé 12 Heures', 'La poitrine de bœuf fumée lentement avec bois de chêne ou hickory, avec son bark noir et son anneau rose de fumée, est la quintessence du BBQ américain.', '🥩', 20, 720, 10, 'advanced', 45.00,
   '[{"qty":"3 à 4 kg","item":"poitrine de bœuf entière (brisket)"},{"qty":"60g","item":"sel de mer grossier"},{"qty":"60g","item":"poivre noir grossièrement concassé"},{"qty":"bois de fumage","item":"chêne, hickory ou cerisier"}]',
   '["La veille, assaisonnez généreusement le brisket de sel et poivre (le "Texas crutch").","Réfrigérez à découvert toute la nuit pour sécher la surface.","Préchauffez le fumoir à 107-120°C (225-250°F) et ajoutez les copeaux de bois trempés.","Placez le brisket gras vers le haut sur la grille du fumoir.","Fumez 6-8 heures jusqu''à atteindre 74°C interne (phase de stall possible).","Enveloppez hermétiquement dans du papier boucher rose (pas d''aluminium).","Poursuivez la cuisson 4-6h jusqu''à 95-97°C interne et tendresse absolue.","Laissez reposer enveloppé dans une glacière avec serviettes 1-2 heures avant de trancher.","Tranchez perpendiculairement aux fibres de la viande."]',
   'Investissez dans un bon thermomètre à sonde: c''est l''outil indispensable pour un brisket parfait.', 'Le brisket est la star des concours BBQ américains; certains pitcrafters passent des années à perfectionner leur technique. La méthode texane (sel + poivre uniquement) est la plus respectée.'),
  ('Les Ribs St. Louis Style', 'Ribs Style St. Louis Méthode 3-2-1', 'Ces côtes de porc préparées selon la méthode 3-2-1 atteignent une tendresse absolue avec une sauce BBQ caramélisée irrésistible.', '🍖', 20, 360, 4, 'intermediate', 18.00,
   '[{"qty":"2 racks","item":"côtes de porc style St. Louis"},{"qty":"3 cs","item":"paprika fumé"},{"qty":"2 cs","item":"cassonade"},{"qty":"1 cs","item":"sel"},{"qty":"1 cs","item":"poivre noir"},{"qty":"1 cc","item":"ail en poudre"},{"qty":"1 cc","item":"oignon en poudre"},{"qty":"1 cc","item":"piment de Cayenne"},{"qty":"200ml","item":"sauce BBQ du commerce ou maison"},{"qty":"50ml","item":"jus de pomme ou bière"},{"qty":"bois de fumage","item":"cerisier ou pommier"}]',
   '["Mélangez toutes les épices pour le rub sec.","Retirez la membrane du dos des côtes en la soulevant avec un couteau.","Enduisez généreusement de rub des deux côtés, laissez reposer 1h minimum.","Préchauffez le fumoir à 107°C avec le bois choisi.","Phase 1 (3h): fumez les ribs gras vers le haut sans les toucher.","Phase 2 (2h): enveloppez dans l''aluminium avec jus de pomme, remettez au fumoir.","Phase 3 (1h): déballez, appliquez la sauce BBQ, laissez caraméliser.","Vérifiez la tendresse: les os doivent dépasser de 5-8 mm et la viande se fissurer légèrement.","Coupez entre les os et servez immédiatement."]',
   'La membrane du dos doit impérativement être retirée sinon elle devient caoutchouteuse à la cuisson.', 'St. Louis est la capitale non officielle des ribs américains; son style de coupe précise garantit une cuisson uniforme et une présentation commerciale parfaite.'),
  ('Le Pulled Pork Carolina', 'Pulled Pork Style Caroline du Nord', 'L''épaule de porc fumée 10 heures, effilochée et nappée de vinegar sauce, est l''âme du BBQ des Carolines.', '🥙', 30, 600, 8, 'intermediate', 25.00,
   '[{"qty":"2.5 kg","item":"épaule de porc avec os"},{"qty":"3 cs","item":"sel"},{"qty":"3 cs","item":"cassonade"},{"qty":"2 cs","item":"paprika"},{"qty":"1 cs","item":"poivre noir"},{"qty":"1 cc","item":"piment de Cayenne"},{"qty":"bois de fumage","item":"hickory ou noyer"},{"qty":"200ml","item":"vinaigre de cidre"},{"qty":"1 cs","item":"flocons de piment"},{"qty":"1 cc","item":"sel (vinegar sauce)"},{"qty":"1 cc","item":"sucre (vinegar sauce)"}]',
   '["Mélangez sel, cassonade, paprika, poivre et piment pour le rub.","Enduisez généreusement l''épaule de porc, réfrigérez 12h.","Préchauffez le fumoir à 107°C avec le bois hickory.","Fumez l''épaule 8-10 heures jusqu''à 74°C interne.","Enveloppez dans du papier boucher, poursuivez jusqu''à 95°C.","Laissez reposer 1h dans une glacière.","Préparez la vinegar sauce: mélangez vinaigre, flocons de piment, sel et sucre.","Effilochez le porc avec deux fourchettes en retirant les excès de gras.","Mélangez le porc effiloché avec une partie de la vinegar sauce.","Servez dans des buns de brioche avec coleslaw."]',
   'Effilochez pendant que le porc est encore chaud: il s''effiloche infiniment plus facilement.', 'La Caroline du Nord est la capitale historique du BBQ américain; la sauce au vinaigre sans tomate est considérée comme la sauce BBQ la plus ancienne et authentique des États-Unis.'),
  ('Les Ailes de Poulet Buffalo', 'Ailes de Poulet Buffalo Authentiques', 'Ces ailes croustillantes nappées de la sauce Buffalo originale (beurre et Frank''s RedHot) avec sauce blue cheese sont un classique de la cuisine américaine.', '🍗', 15, 40, 4, 'beginner', 12.00,
   '[{"qty":"1.2 kg","item":"ailes de poulet"},{"qty":"2 cc","item":"levure chimique"},{"qty":"1 cc","item":"sel"},{"qty":"1 cc","item":"poivre noir"},{"qty":"120ml","item":"sauce Frank''s RedHot"},{"qty":"80g","item":"beurre fondu"},{"qty":"1 cc","item":"vinaigre blanc"},{"qty":"150ml","item":"crème fraîche épaisse (blue cheese dip)"},{"qty":"80g","item":"fromage bleu émietté (blue cheese dip)"},{"qty":"1","item":"gousse d''ail émincée (blue cheese dip)"},{"qty":"1 cs","item":"jus de citron (blue cheese dip)"}]',
   '["Séchez les ailes avec du papier absorbant (étape cruciale).","Mélangez levure chimique, sel et poivre, enrobez les ailes uniformément.","Disposez sur grille, réfrigérez à découvert 1-2h pour sécher davantage.","Cuisez au four à 220°C sur grille pendant 35-40 minutes, en retournant à mi-cuisson.","Préparez la sauce Buffalo: mélangez beurre fondu et sauce hot sauce, ajoutez vinaigre.","Blue cheese dip: mélangez crème, fromage bleu, ail et citron, réfrigérez.","Nappez immédiatement les ailes chaudes de sauce Buffalo.","Servez avec le dip au fromage bleu et des branches de céleri."]',
   'La levure chimique rend la peau ultra-croustillante au four sans friture, secret des ailes parfaites.', 'Les ailes Buffalo sont nées en 1964 au Anchor Bar de Buffalo, NY, quand Teressa Bellissimo les improvisa pour les amis de son fils. Aujourd''hui, les Américains consomment plus de 1 milliard d''ailes pendant le Super Bowl.'),
  ('Le Salmon Cédré', 'Saumon sur Planche de Cèdre', 'Ce filet de saumon cuit directement sur une planche de cèdre trempée acquiert un arôme boisé délicat qui sublime sa chair grasse et fondante.', '🐟', 130, 20, 4, 'beginner', 18.00,
   '[{"qty":"700g","item":"filet de saumon avec peau"},{"qty":"1","item":"planche de cèdre alimentaire"},{"qty":"2 cs","item":"sirop d''érable"},{"qty":"1 cs","item":"moutarde à l''ancienne"},{"qty":"1 cs","item":"sauce soja"},{"qty":"1 cc","item":"gingembre râpé"},{"qty":"1","item":"gousse d''ail émincée"},{"qty":"sel et poivre","item":"selon goût"},{"qty":"citron","item":"pour servir"},{"qty":"aneth frais","item":"pour garnir"}]',
   '["Immergez la planche de cèdre dans l''eau 2 heures minimum (posez un poids dessus).","Mélangez sirop d''érable, moutarde, sauce soja, gingembre et ail pour la marinade.","Assaisonnez le saumon de sel et poivre, appliquez la marinade sur la chair.","Préchauffez le BBQ à chaleur moyenne-élevée.","Posez la planche trempée directement sur la grille chaude, fermez le couvercle 2 minutes.","Déposez le saumon peau vers le bas sur la planche.","Fermez le couvercle, cuisez 15-20 minutes selon l''épaisseur.","Le saumon est prêt quand il se défait facilement à la fourchette.","Servez directement sur la planche avec citron et aneth."]',
   'Si la planche commence à flamber, versez un peu d''eau sur les bords; une légère fumée est normale et désirée.', 'La cuisson sur planche de cèdre est une tradition millénaire des nations autochtones du Pacifique Nord-Ouest; ils séchaient et fumaient leur saumon sur des planches de bois pour les conserver.')
) AS v(lesson_title, title, description, emoji, prep_time_min, cook_time_min, servings, difficulty, avg_price_eur, ingredients, instructions, chef_tip, cultural_note)
JOIN public.lessons l ON l.title = v.lesson_title;

-- ==================== VEGAN RECIPES ====================
INSERT INTO public.recipes (id, lesson_id, title, description, emoji, prep_time_min, cook_time_min, servings, difficulty, avg_price_eur, ingredients, instructions, chef_tip, cultural_note)
SELECT gen_random_uuid(), l.id, v.title, v.description, v.emoji, v.prep_time_min, v.cook_time_min, v.servings, v.difficulty, v.avg_price_eur, v.ingredients::jsonb, v.instructions::jsonb, v.chef_tip, v.cultural_note
FROM (VALUES
  ('Le Bowl de Buddha', 'Buddha Bowl Complet et Nourrissant', 'Ce bol généreux associe quinoa doré, pois chiches rôtis croustillants, légumes colorés et sauce tahini crémeuse pour un repas équilibré et savoureux.', '🥗', 15, 30, 2, 'beginner', 7.00,
   '[{"qty":"150g","item":"quinoa"},{"qty":"1 boîte","item":"pois chiches égouttés et rincés"},{"qty":"2 cs","item":"huile d''olive"},{"qty":"1 cc","item":"paprika fumé"},{"qty":"1","item":"patate douce"},{"qty":"100g","item":"épinards frais"},{"qty":"1","item":"avocat tranché"},{"qty":"200g","item":"concombre coupé"},{"qty":"3 cs","item":"tahini"},{"qty":"2 cs","item":"jus de citron"},{"qty":"1","item":"gousse d''ail"},{"qty":"sel, poivre","item":"selon goût"},{"qty":"graines de sésame","item":"pour garnir"}]',
   '["Cuisez le quinoa: 150g quinoa + 300ml eau, portez à ébullition, réduisez 15 min à couvert.","Séchez les pois chiches avec du papier absorbant, enrobez d''huile et paprika.","Rôtissez pois chiches et patate douce en cubes à 200°C pendant 25-30 minutes.","Sauce tahini: mélangez tahini, jus de citron, ail écrasé, eau pour diluer et sel.","Montez les bols: quinoa en base, épinards d''un côté, pois chiches chauds, patate douce, avocat, concombre.","Versez généreusement la sauce tahini.","Parsemez de graines de sésame et servez."]',
   'Préparez les composants en avance (quinoa, légumes rôtis) et assemblez les bols à la minute pour la fraîcheur.', 'Le mouvement "clean eating" des années 2010 a popularisé les Buddha bowls dans le monde entier; aujourd''hui, leur beauté colorée fait de chaque bol une œuvre d''art Instagram.'),
  ('Le Curry de Patates Douces et Pois Chiches', 'Curry de Patates Douces au Lait de Coco', 'Ce curry vegan réconfortant et coloré marie patates douces fondantes, pois chiches et lait de coco dans un bouillon épicé aux herbes indiennes.', '🍛', 10, 30, 4, 'beginner', 6.50,
   '[{"qty":"2","item":"patates douces coupées en cubes"},{"qty":"1 boîte","item":"pois chiches égouttés"},{"qty":"400ml","item":"lait de coco entier"},{"qty":"200ml","item":"bouillon de légumes"},{"qty":"1","item":"oignon émincé"},{"qty":"3","item":"gousses d''ail"},{"qty":"2 cm","item":"gingembre râpé"},{"qty":"1 boîte","item":"tomates concassées"},{"qty":"2 cs","item":"curry en poudre"},{"qty":"1 cc","item":"curcuma"},{"qty":"1 cc","item":"garam masala"},{"qty":"2 cs","item":"huile de coco"},{"qty":"coriandre fraîche","item":"pour servir"}]',
   '["Faites revenir oignon, ail et gingembre dans l''huile de coco 3 minutes.","Ajoutez le curry en poudre et le curcuma, faites revenir 1 minute pour libérer les arômes.","Ajoutez les tomates concassées, mélangez bien.","Incorporez patates douces, pois chiches et bouillon de légumes.","Laissez mijoter 20 minutes jusqu''à ce que les patates soient tendres.","Ajoutez le lait de coco, mélangez et laissez chauffer 5 minutes.","Ajoutez le garam masala, assaisonnez en sel.","Servez sur du riz basmati, garni de coriandre fraîche."]',
   'Faites revenir les épices sèches dans l''huile 1 minute avant d''ajouter les liquides: les arômes se libèrent beaucoup mieux.', 'Le curry végétarien est au cœur de l''alimentation hindoue depuis des millénaires; en Inde, des millions de personnes suivent un régime strictement végétarien pour des raisons religieuses ou éthiques.'),
  ('Les Falafels Maison', 'Falafels Maison Croustillants', 'Ces boulettes de pois chiches crus trempés, herbes fraîches et épices orientales, croustillantes dehors et moelleuses dedans, sont le street food végétal parfait.', '🧆', 480, 20, 4, 'beginner', 5.50,
   '[{"qty":"250g","item":"pois chiches crus (trempés 12h)"},{"qty":"1","item":"oignon grossièrement haché"},{"qty":"4","item":"gousses d''ail"},{"qty":"1 bouquet","item":"persil frais"},{"qty":"1 bouquet","item":"coriandre fraîche"},{"qty":"1 cc","item":"cumin moulu"},{"qty":"1 cc","item":"coriandre moulue"},{"qty":"1/2 cc","item":"piment de Cayenne"},{"qty":"1 cc","item":"sel"},{"qty":"2 cc","item":"levure chimique"},{"qty":"huile","item":"pour friture"}]',
   '["Égouttez et rincez les pois chiches trempés (ne les cuisez surtout pas!).","Mixez grossièrement pois chiches, oignon, ail, herbes et épices.","La texture doit être granuleuse, pas lisse: des morceaux sont essentiels.","Ajoutez la levure chimique, mélangez, réfrigérez 30 minutes.","Formez des boulettes de la taille d''une noix.","Chauffez l''huile à 175°C, testez avec une boulette: elle doit remonter et dorer en 30 sec.","Faites frire les falafels 3-4 minutes jusqu''à dorure profonde.","Égouttez sur papier absorbant, servez immédiatement dans une pita avec houmous, salade et tahini."]',
   'Si les falafels se désagrègent à la friture, ajoutez 1 cs de farine de pois chiche pour les lier.', 'Les falafels sont originaires d''Égypte où ils étaient à l''origine faits avec des fèves (ful); les communautés juives d''Alexandrie les introduisirent en Israël avec des pois chiches dans les années 1950.'),
  ('Le Tiramisu Vegan', 'Tiramisu Vegan à l''Aquafaba', 'Ce tiramisu entièrement végétal utilise aquafaba montée en neige et crème de cajou pour recréer la texture aérienne et le goût crémeux de l''original.', '☕', 30, 0, 6, 'intermediate', 9.00,
   '[{"qty":"200g","item":"biscuits à la cuillère végans"},{"qty":"200ml","item":"café fort refroidi"},{"qty":"2 cs","item":"Kahlúa ou amaretto (optionnel)"},{"qty":"300g","item":"noix de cajou trempées 4h"},{"qty":"200ml","item":"crème de coco réfrigérée"},{"qty":"80g","item":"sucre glace"},{"qty":"1 cc","item":"extrait de vanille"},{"qty":"120ml","item":"aquafaba (eau de pois chiches)"},{"qty":"1 cs","item":"sucre (pour l''aquafaba)"},{"qty":"cacao amer","item":"pour saupoudrer"}]',
   '["Égouttez les cajous, mixez-les avec la crème de coco, sucre glace et vanille jusqu''à obtenir une crème lisse.","Fouettez l''aquafaba avec le sucre jusqu''à formation de pics fermes (5-8 minutes au batteur).","Incorporez délicatement l''aquafaba en neige à la crème de cajou en soulevant la masse.","Mélangez café et Kahlúa dans une assiette creuse.","Trempez rapidement les biscuits dans le café (1-2 secondes par face).","Tapissez le fond d''un plat de biscuits imbibés.","Étalez la moitié de la crème, ajoutez une couche de biscuits imbibés.","Terminez avec le reste de crème, saupoudrez généreusement de cacao.","Réfrigérez 4 heures minimum avant de servir."]',
   'L''aquafaba doit être bien froid pour monter correctement; si vous avez du mal, placez le bol au congélateur 5 minutes avant de fouetter.', 'L''aquafaba (littéralement "eau de fève") fut découvert en 2014 par le cuisinier français Joël Roessel, révolutionnant la pâtisserie végane avec cette alternative naturelle aux blancs d''œufs.'),
  ('Le Kimchi Maison Vegan', 'Kimchi Maison Végétalien', 'Ce kimchi fermenté sans aucun produit animal reproduit les saveurs complexes, acidulées et pimentées du kimchi coréen traditionnel.', '🥬', 30, 1440, 8, 'intermediate', 5.00,
   '[{"qty":"1","item":"chou napa (chinois), environ 1.5 kg"},{"qty":"3 cs","item":"gros sel"},{"qty":"1 cs","item":"miso blanc"},{"qty":"5 cs","item":"gochugaru (piment coréen en flocons)"},{"qty":"5","item":"gousses d''ail"},{"qty":"3 cm","item":"gingembre frais"},{"qty":"1 cs","item":"sucre"},{"qty":"4","item":"oignons verts émincés"},{"qty":"1","item":"carotte râpée"},{"qty":"2 cs","item":"sauce soja"},{"qty":"1 feuille","item":"algue nori séchée émiettée"}]',
   '["Coupez le chou en quartiers puis en morceaux de 5 cm.","Saupoudrez de sel, mélangez bien, laissez dégorger 2 heures en retournant régulièrement.","Rincez le chou 3 fois à l''eau claire, essorez bien.","Mixez ail, gingembre, miso, sauce soja, sucre et nori pour la pâte umami.","Mélangez avec le gochugaru pour obtenir la pâte de kimchi.","Protégez vos mains avec des gants, mélangez chou, oignons verts, carotte et pâte.","Massez bien pour que la pâte enrobe tous les légumes.","Tassez dans des bocaux en verre, fermez hermétiquement.","Laissez fermenter à température ambiante 1-3 jours selon la saison.","Goûtez: quand l''acidité vous convient, réfrigérez pour stopper la fermentation."]',
   'Le kimchi continue de fermenter lentement au réfrigérateur; il est meilleur après 1-2 semaines et se conserve des mois.', 'Le kimchi est le pilier de la cuisine coréenne, inscrit au Patrimoine Culturel Immatériel de l''UNESCO en 2013. En Corée du Sud, chaque famille a ses propres variations; la tradition du kimjang (préparation collective hivernale) est un événement social majeur.')
) AS v(lesson_title, title, description, emoji, prep_time_min, cook_time_min, servings, difficulty, avg_price_eur, ingredients, instructions, chef_tip, cultural_note)
JOIN public.lessons l ON l.title = v.lesson_title;
