-- Lessons 36-50 for French, Italian, Japanese, Moroccan paths

-- ============================================================
-- FRENCH LESSONS 36-50
-- ============================================================
INSERT INTO public.lessons (id, path_id, title, description, order_index, duration_min, difficulty, chef_tip, cultural_note, vocabulary)
SELECT gen_random_uuid(), p.id, v.title, v.description, v.order_index, v.duration_min, v.difficulty, v.chef_tip, v.cultural_note, v.vocabulary::jsonb
FROM (VALUES
  ('La Tarte Flambée Alsacienne', 'Fines pâte croustillante, crème fraîche, oignons et lardons — spécialité d Alsace.', 36, 30, 'beginner', 'La pâte doit être ultra-fine — étalez-la aussi mince que possible.', 'La tarte flambée (Flammekueche) était à l origine cuite dans les fours à pain très chauds.', '[{"term":"Flammekueche","definition":"tarte flambée en alsacien — flamme kuchen"},{"term":"fromage blanc","definition":"base crémeuse de la tarte flambée authentique"}]'),
  ('Les Grenouilles à la Provençale', 'Cuisses de grenouilles sautées à l ail, persil et beurre citronné.', 37, 20, 'intermediate', 'Les cuisses de grenouilles cuisent très vite — 2 minutes par côté maximum.', 'La grenouille est un cliché culinaire français mais reste un mets délicat apprécié.', '[{"term":"cuisses","definition":"les pattes arrières de la grenouille"},{"term":"persillade","definition":"mélange ail et persil haché"}]'),
  ('Le Gratin de Macaronis Lyonnais', 'Macaronis gratinés au comté et jambon — confort lyonnais.', 38, 40, 'beginner', 'Le comté vieux est le fromage idéal — sa saveur complexe élève tout le plat.', 'Le gratin de macaronis est l incontournable des bouchons lyonnais depuis le XIXe.', '[{"term":"comté","definition":"fromage AOP de Franche-Comté — idéal pour gratiner"},{"term":"bouchon","definition":"restaurant traditionnel lyonnais"}]'),
  ('La Bouillabaisse Marseillaise', 'Soupe de poissons méditerranéens au safran, servie avec rouille et croûtons.', 39, 90, 'advanced', 'La bouillabaisse doit bouillir violemment (bouille et abaisse) pour émulsionner le gras.', 'La vraie bouillabaisse a une Charte avec 6 poissons obligatoires — une AOP non officielle.', '[{"term":"rouille","definition":"sauce à l ail, safran et huile d olive"},{"term":"bouillabaisse","definition":"bouit-abaisse — ça bout, on abaisse le feu"}]'),
  ('Le Gratin de Cardons à la Moelle', 'Cardons blanchis, sauce béchamel, moelle de bœuf et parmesan — plat de Noël lyonnais.', 40, 90, 'advanced', 'Les cardons doivent être blanchis longuement (20 min) pour perdre leur amertume.', 'Le gratin de cardons est LE plat du réveillon de Noël lyonnais — une tradition absolue.', '[{"term":"cardon","definition":"légume cousin de l artichaut, tige comestible"},{"term":"moelle","definition":"substance grasse de l intérieur de l os de bœuf"}]'),
  ('Le Vacherin Mont d Or', 'Fromage coulant cuit au four dans sa boîte, avec pommes de terre.', 41, 25, 'beginner', 'Percez le dessus et arrosez de vin blanc avant d enfourner pour plus de saveur.', 'Le Mont d Or (ou Vacherin) n est disponible qu en automne-hiver — un plaisir saisonnier.', '[{"term":"Mont d Or","definition":"fromage AOP du Jura suisse et franc-comtois"},{"term":"croûte lavée","definition":"fromages dont la croûte est frottée à la saumure"}]'),
  ('Le Lapin à la Moutarde', 'Lapin braisé dans une sauce moutarde et crème fraîche — classique français.', 42, 75, 'intermediate', 'Enduisez le lapin de moutarde avant de le saisir — elle forme une croûte parfumée.', 'Le lapin à la moutarde est l un des classiques de la cuisine bourgeoise française.', '[{"term":"lapin de garenne","definition":"lapin sauvage — goût plus fort que le lapin d élevage"},{"term":"moutarde de Dijon","definition":"moutarde forte au vinaigre — incontournable"}]'),
  ('Le Pâté en Croûte', 'Terrine de viande enveloppée de pâte feuilletée — charcuterie de fête.', 43, 180, 'advanced', 'Versez la gelée par le trou du pâté en croûte refroidi pour combler les espaces.', 'Le pâté en croûte a fait l objet d un championnat du monde depuis 2009 à Lyon.', '[{"term":"farce","definition":"mélange de viandes hachées et épicées"},{"term":"gelée","definition":"bouillon gélatineux versé dans le pâté après cuisson"}]'),
  ('Les Pommes Sarladaises', 'Pommes de terre sautées à la graisse de canard et à l ail — spécialité du Périgord.', 44, 45, 'beginner', 'La graisse de canard doit être chaude et abondante — ne lésinez pas.', 'Sarlat est la capitale gastronomique du Périgord noir, terre du foie gras et de la truffe.', '[{"term":"graisse de canard","definition":"corps gras du canard — base de la cuisine du Sud-Ouest"},{"term":"Périgord","definition":"région du Sud-Ouest française, capitale gastronomique"}]'),
  ('Le Civet de Chevreuil', 'Chevreuil mariné au vin rouge, braisé avec légumes racines — plat de chasse.', 45, 240, 'advanced', 'La marinade de 24-48h est indispensable pour attendrir le gibier.', 'Le chevreuil est le gibier le plus courant en France — disponible en automne lors de la chasse.', '[{"term":"chevreuil","definition":"cervidé sauvage européen — gibier à poil"},{"term":"civet","definition":"ragoût de gibier au vin et sang — cuisson longue"}]'),
  ('Le Soufflé au Comté', 'Soufflé salé au fromage comté — légèreté absolue et saveur intense.', 46, 35, 'advanced', 'Présentez immédiatement — les soufflés n attendent pas.', 'Le soufflé salé est la démonstration de maîtrise des grands chefs français.', '[{"term":"beurre pommade","definition":"beurre mou pour chemiser le moule"},{"term":"gratin","definition":"chapelure ou fromage sur le dessus du soufflé"}]'),
  ('Les Œufs Meurette', 'Œufs pochés dans une sauce au vin rouge avec lardons, champignons et croûtons.', 47, 40, 'intermediate', 'Le vinaigre dans l eau de pochage maintient le blanc de l œuf compact.', 'La meurette est la sauce bourguignonne par excellence — vin rouge, fond de veau, lardons.', '[{"term":"poché","definition":"cuit dans un liquide frémissant sans coquille"},{"term":"meurette","definition":"sauce bourguignonne au vin rouge"}]'),
  ('Le Foie Gras Poêlé', 'Escalope de foie gras poêlée dorée, servie avec chutney de figues.', 48, 15, 'advanced', 'La poêle doit être très chaude et sèche — le foie gras libère assez de gras lui-même.', 'Le foie gras est classé patrimoine gastronomique et culturel de la France.', '[{"term":"lobe","definition":"morceau entier du foie gras"},{"term":"torchon","definition":"foie gras cuit emballé dans un torchon"}]'),
  ('Le Pot-au-Feu de la Mer', 'Poissons et fruits de mer pochés dans un bouillon de légumes et herbes.', 49, 60, 'intermediate', 'Pochez les poissons par ordre de cuisson pour qu ils soient tous prêts en même temps.', 'Le pot-au-feu de la mer est la version maritime du grand classique français.', '[{"term":"nage","definition":"bouillon parfumé pour pocher les poissons"},{"term":"julienne","definition":"légumes coupés en fins bâtonnets pour la garniture"}]'),
  ('Le Bœuf Bourguignon Traditionnel', 'Bœuf braisé au vin de Bourgogne, lardons, champignons et petits oignons glacés.', 50, 180, 'intermediate', 'Faites mariner le bœuf 24h dans le vin pour une saveur plus profonde.', 'Le bœuf bourguignon est le symbole de la cuisine française dans le monde entier.', '[{"term":"braiser","definition":"cuire longuement dans un liquide couvert"},{"term":"lardon","definition":"morceau de lard fumé — base aromatique du bourguignon"}]')
) AS v(title, description, order_index, duration_min, difficulty, chef_tip, cultural_note, vocabulary)
CROSS JOIN (SELECT id FROM public.paths WHERE slug='french' LIMIT 1) p;

-- ============================================================
-- ITALIAN LESSONS 36-50
-- ============================================================
INSERT INTO public.lessons (id, path_id, title, description, order_index, duration_min, difficulty, chef_tip, cultural_note, vocabulary)
SELECT gen_random_uuid(), p.id, v.title, v.description, v.order_index, v.duration_min, v.difficulty, v.chef_tip, v.cultural_note, v.vocabulary::jsonb
FROM (VALUES
  ('La Pizza Margherita Napolitaine', 'Pizza à la farine 00, tomate San Marzano, mozzarella di bufala, basilic.', 36, 180, 'intermediate', 'La pâte doit lever 24h minimum pour des bulles légères et une saveur développée.', 'La pizza Margherita a été créée en 1889 pour la reine Margherite de Savoie.', '[{"term":"farine 00","definition":"farine italienne très fine — idéale pour la pizza"},{"term":"San Marzano","definition":"tomate AOP de la région de Naples"}]'),
  ('Le Vitello Tonnato', 'Veau poché tranché finement, nappé d une sauce crémeuse au thon et câpres.', 37, 60, 'intermediate', 'Le veau doit être froid avant de napper — la sauce tient mieux.', 'Le vitello tonnato est la mise en bouche des grandes tables piémontaises.', '[{"term":"vitello","definition":"veau en italien"},{"term":"tonnato","definition":"sauce au thon — association inhabituelle mais parfaite"}]'),
  ('Les Bigoli al Torchio', 'Pâtes épaisses maison à la presse, sauce aux anchois et oignon doux de Venise.', 38, 60, 'intermediate', 'Les bigoli doivent être épais — leur texture rugueuse accroche la sauce.', 'Les bigoli sont les pâtes emblématiques de Venise, pressées à travers le torchio (presse).', '[{"term":"bigoli","definition":"pâtes épaisses vénitiennes pressées"},{"term":"torchio","definition":"presse à pâtes en bois traditionnelle"}]'),
  ('La Bagna Cauda', 'Fondue chaude d anchois et ail dans l huile d olive — trempette piémontaise.', 39, 20, 'beginner', 'Blanchissez l ail 3 fois dans du lait pour adoucir son goût piquant.', 'La bagna cauda (bain chaud) est le plat convivial du Piémont — partagé au centre de la table.', '[{"term":"bagna cauda","definition":"bain chaud en piémontais"},{"term":"anchois","definition":"petit poisson salé et fermenté — umami intense"}]'),
  ('Le Brodetto di Pesce Adriatique', 'Soupe de poissons adriatiques au safran et vin blanc — variante du Frioul.', 40, 50, 'intermediate', 'Ajoutez les poissons les plus fragiles en dernier — ils cuisent très vite.', 'Chaque ville côtière adriatique a sa version du brodetto — elles se disputent la meilleure.', '[{"term":"brodetto","definition":"soupe de poissons adriatique"},{"term":"safran","definition":"épice dorée qui parfume et colore le brodetto"}]'),
  ('La Ribollita Toscane (avancée)', 'Version avancée de la ribollita — pain rassis, cavolo nero et cannellini bouillis deux fois.', 41, 90, 'intermediate', 'La rebollita est meilleure le lendemain — les saveurs se développent en refroidissant.', 'Ribollita signifie rebouillie — elle était réchauffée le lendemain pour un plat encore plus savoureux.', '[{"term":"ribollita","definition":"rebouillie — soupe toscane réchauffée deux fois"},{"term":"cavolo nero","definition":"chou noir toscan — ingrédient emblématique de la ribollita"}]'),
  ('Les Gnocchi al Gorgonzola', 'Gnocchi de pommes de terre dans une sauce crémeuse au gorgonzola dolce et noix.', 42, 50, 'intermediate', 'Le gorgonzola dolce est moins piquant — il fond doucement sans dominer.', 'Le gorgonzola est l un des fromages AOP les plus anciens d Italie — créé en 879.', '[{"term":"gnocchi","definition":"petites boulettes de pomme de terre"},{"term":"gorgonzola dolce","definition":"gorgonzola jeune et crémeux — moins piquant"}]'),
  ('Le Fritto Misto Veneziano', 'Mélange de fruits de mer et légumes frits dans une pâte légère — à la vénitienne.', 43, 40, 'intermediate', 'La pâte à friture vénitienne utilise de l eau gazeuse très froide pour la légèreté.', 'Le fritto misto est le plat de fête des osterie (trattorie) de Venise.', '[{"term":"fritto misto","definition":"mélange frit — assortiment de la mer"},{"term":"osteria","definition":"taverne vénitienne — restauration simple"}]'),
  ('La Pasta alla Norma Sicilienne', 'Pâtes aux aubergines frites, sauce tomate et ricotta salée — Catane.', 44, 40, 'beginner', 'Les aubergines doivent être frites séparément pour rester croustillantes.', 'La pasta alla Norma a été nommée en hommage à l opéra Norma de Bellini, né à Catane.', '[{"term":"Norma","definition":"opéra de Bellini — génie de Catane"},{"term":"ricotta salata","definition":"ricotta séchée et salée — différente de la fraîche"}]'),
  ('La Focaccia di Recco', 'Focaccia fine fourrée de stracchino fondu — spécialité de Recco en Ligurie.', 45, 45, 'advanced', 'La pâte doit être ultra-fine — presque transparente — elle ne lève pas.', 'La focaccia di Recco a une IGP européenne — seul Recco et ses alentours peuvent la produire.', '[{"term":"stracchino","definition":"fromage frais ligure très fondant"},{"term":"Recco","definition":"petite ville de Ligurie, berceau de cette focaccia"}]'),
  ('Le Brasato al Barolo', 'Joue de bœuf braisée au vin Barolo 4h — roi des brasati piémontais.', 46, 270, 'advanced', 'Utilisez un vrai Barolo — pas un vin bas de gamme, la qualité du vin compte.', 'Le brasato al Barolo est le plat de fête par excellence du Piémont.', '[{"term":"brasato","definition":"braisé — viande cuite longtemps dans le vin"},{"term":"Barolo","definition":"roi des vins rouges italiens — du Piémont"}]'),
  ('Les Sarde in Saor', 'Sardines marinées en agrodolce (aigre-doux) avec oignons, raisins et pignons.', 47, 30, 'beginner', 'Les sarde in saor se mangent froides après 24h de marinade — patience requise.', 'Ce plat de conservation vénitien permettait aux marins de transporter des sardines en mer.', '[{"term":"saor","definition":"saveur en vénitien — sauce aigre-douce"},{"term":"agrodolce","definition":"aigre-doux — mariage vinaigre et sucre"}]'),
  ('Le Tartufo di Pizzo', 'Boule de glace à deux parfums enrobée de chocolat noir — Pizzo, Calabre.', 48, 30, 'intermediate', 'Travaillez vite — la glace doit rester dure pour façonner les boules.', 'Le tartufo di Pizzo est une IGP calabraise — né dans les années 50 à Pizzo Calabro.', '[{"term":"tartufo","definition":"truffe — allusion à la forme arrondie"},{"term":"gelato","definition":"crème glacée italienne à base de lait entier"}]'),
  ('La Pastiera Napoletana', 'Tarte de Pâques napolitaine au blé cuit, ricotta, fleur d oranger.', 49, 120, 'advanced', 'La pastiera doit reposer 2-3 jours avant dégustation pour que les saveurs se fondent.', 'La pastiera est LE dessert de Pâques napolitain — chaque famille a sa recette jalousement gardée.', '[{"term":"pastiera","definition":"tarte de Pâques napolitaine au blé et ricotta"},{"term":"acqua di fiori d arancio","definition":"eau de fleur d oranger — parfum caractéristique"}]'),
  ('Le Risotto Nero alle Seppie', 'Risotto noir à l encre de seiche avec seiches tendres — classique vénitien.', 50, 45, 'intermediate', 'L encre de seiche doit être ajoutée en cours de cuisson pour colorer uniformément.', 'Le risotto nero est la fierté de Venise — sa couleur noire est spectaculaire et son goût iodé unique.', '[{"term":"nero","definition":"noir en italien — la couleur de l encre de seiche"},{"term":"seppia","definition":"seiche — mollusque dont l encre colore le risotto"}]')
) AS v(title, description, order_index, duration_min, difficulty, chef_tip, cultural_note, vocabulary)
CROSS JOIN (SELECT id FROM public.paths WHERE slug='italian' LIMIT 1) p;

-- ============================================================
-- JAPANESE LESSONS 36-50
-- ============================================================
INSERT INTO public.lessons (id, path_id, title, description, order_index, duration_min, difficulty, chef_tip, cultural_note, vocabulary)
SELECT gen_random_uuid(), p.id, v.title, v.description, v.order_index, v.duration_min, v.difficulty, v.chef_tip, v.cultural_note, v.vocabulary::jsonb
FROM (VALUES
  ('Le Ramen Tonkotsu', 'Bouillon de porc trouble et crémeux cuit 12h, nouilles fines, chashu et menma.', 36, 720, 'advanced', 'L ébullition vive pendant 4h émulsionne le collagène et donne la blancheur lactée du bouillon.', 'Le ramen tonkotsu est né à Fukuoka (Hakata) dans les années 1940.', '[{"term":"tonkotsu","definition":"os de porc — base du bouillon"},{"term":"chashu","definition":"porc poché et laqué — garniture essentielle du ramen"}]'),
  ('Le Sukiyaki', 'Bœuf tranché finement cuit à table dans un bouillon sucré-salé — kaiseki de rue.', 37, 30, 'beginner', 'Trempez chaque bouchée dans un œuf cru battu avant de manger — texture soyeuse incomparable.', 'Le sukiyaki est le plat de fête familial japonais pour le Nouvel An et les célébrations.', '[{"term":"warishita","definition":"bouillon sucré-salé du sukiyaki"},{"term":"shirataki","definition":"nouilles de konjac gélatineuses sans calories"}]'),
  ('La Tempura de Crevettes', 'Crevettes et légumes en beurure légère frite dans l huile chaude — une technique parfaite.', 38, 30, 'intermediate', 'La pâte à tempura doit être froide et grumeleuse — les grumeaux donnent le croustillant.', 'La tempura a été introduite au Japon par les jésuites portugais au XVIe siècle.', '[{"term":"tentsuyu","definition":"sauce dashi+mirin+soja pour tremper la tempura"},{"term":"daikon oroshi","definition":"radis blanc râpé pour accompagner"}]'),
  ('Le Chirashi Sushi', 'Riz vinaigré garni de sashimis variés disposés en éventail — sushi facile et festif.', 39, 40, 'intermediate', 'Le riz sushi doit être à température ambiante — ni trop chaud, ni froid.', 'Le chirashi (éparpillé) est la version conviviale des sushis, servie dans un grand bol.', '[{"term":"chirashi","definition":"éparpillé en japonais — garnitures posées sur le riz"},{"term":"sumeshi","definition":"riz sushi assaisonné au vinaigre"}]'),
  ('La Soupe au Tofu Agedashi', 'Tofu frit léger dans un bouillon dashi délicat — entrée traditionnelle japonaise.', 40, 25, 'intermediate', 'Le tofu doit être séché parfaitement puis poudré de katakuriko avant de frire.', 'L agedashi tofu est l une des préparations les plus délicates de la cuisine japonaise.', '[{"term":"agedashi","definition":"frit et trempé dans le dashi"},{"term":"katakuriko","definition":"fécule de pomme de terre — enrobe le tofu pour frire"}]'),
  ('Le Soba Sarashina', 'Nouilles soba blanches de haute qualité au dashi léger — la quintessence du soba.', 41, 30, 'advanced', 'Le sarashina soba est fait avec le cœur du sarrasin — la farine la plus pure et la plus blanche.', 'Le soba sarashina est le soba premium des grandes maisons de Tokyo depuis l époque Edo.', '[{"term":"sarashina","definition":"soba blanc de haute qualité au cœur de sarrasin"},{"term":"tsuyu","definition":"bouillon concentré pour tremper le soba froid"}]'),
  ('Le Shabu-Shabu Ponzu', 'Bœuf marbré fondu en fraction de seconde dans le bouillon, sauce ponzu.', 42, 20, 'beginner', 'Faites tremper les tranches de bœuf 2-3 secondes seulement — le fond du pot suffit.', 'Le shabu-shabu (bruit de l agitation dans le bouillon) est un plat de fête japonais.', '[{"term":"ponzu","definition":"sauce soja et jus d agrumes — rafraîchissante"},{"term":"wagyu","definition":"bœuf japonais marmelé — le meilleur pour shabu-shabu"}]'),
  ('Les Mochi Daifuku', 'Pâte de riz gluant farcie de pâte de haricots rouges — mochi de fête.', 43, 45, 'intermediate', 'Trempez vos mains dans la fécule de pomme de terre pour manipuler le mochi sans coller.', 'Le daifuku (grand bonheur) est offert lors des cérémonies et fêtes japonaises.', '[{"term":"daifuku","definition":"grand bonheur — mochi fourré"},{"term":"anko","definition":"pâte sucrée de haricots adzuki rouges"}]'),
  ('Le Curry Japonais Maison', 'Curry japonais doux au bœuf et légumes — riche et onctueux, style maison.', 44, 60, 'beginner', 'Ajoutez une pomme râpée pour adoucir et épaissir naturellement la sauce.', 'Le curry japonais vient de l Inde via l Angleterre au XIXe — il est maintenant totalement japonisé.', '[{"term":"roux de curry","definition":"blocs de curry japonais prêts à l emploi"},{"term":"Fukujinzuke","definition":"condiment de légumes marinés servi avec le curry"}]'),
  ('Les Onigiri au Saumon Grillé', 'Boulettes de riz compactes fourrées de saumon grillé, enveloppées de nori.', 45, 25, 'beginner', 'Salez légèrement vos mains avant de former les onigiri — cela parfume et conserve.', 'Les onigiri sont le casse-croûte national japonais — disponibles dans tous les konbini 24h/24.', '[{"term":"onigiri","definition":"boulette de riz compressée"},{"term":"nori","definition":"algue séchée — enveloppe l onigiri"}]'),
  ('Le Yaki Udon', 'Larges nouilles de blé sautées aux légumes et sauce soja-mirin — version grillée.', 46, 20, 'beginner', 'Les udon doivent être légèrement dorées — cuisez à feu vif pour le grillé.', 'Le yaki udon est la version sautée des udon, popularisée dans les teppanyaki restaurants.', '[{"term":"udon","definition":"larges nouilles blanches de blé"},{"term":"tsuyu","definition":"sauce de base — dashi, soja, mirin"}]'),
  ('Le Katsudon', 'Katsu de porc sur riz, napé d un mélange œufs-bouillon — le bowl japonais.', 47, 30, 'beginner', 'L œuf doit être encore légèrement baveuse quand vous le versez sur le riz.', 'Le katsudon est le plat favori des étudiants japonais avant les examens — pour la victoire.', '[{"term":"katsu","definition":"escalope de viande panée et frite"},{"term":"donburi","definition":"bol de riz garni — les dons sont des plats de riz en bol"}]'),
  ('La Soupe Tonjiru Avancée', 'Soupe miso au porc, racines et légumes d hiver — version enrichie.', 48, 40, 'intermediate', 'Utilisez du miso de riz rouge (hatcho) pour plus de profondeur.', 'Le tonjiru est la soupe réconfortante de l hiver japonais — chaque famille a sa version.', '[{"term":"tonjiru","definition":"soupe de porc (ton=cochon, jiru=soupe)"},{"term":"gobo","definition":"bardane japonaise — racine aromatique"}]'),
  ('Le Tamago Kake Gohan', 'Riz chaud avec un œuf cru et sauce soja — le petit-déjeuner japonais par excellence.', 49, 5, 'beginner', 'Utilisez des œufs ultra-frais (max 5 jours) pour le TKG authentique et sûr.', 'Le TKG (tamago kake gohan) est le petit-déjeuner favori du Japon — simple et parfait.', '[{"term":"TKG","definition":"tamago kake gohan — abbréviation japonaise populaire"},{"term":"tamago","definition":"œuf en japonais"}]'),
  ('Le Chirashi de Saint-Valentin', 'Riz vinaigré, sashimis de luxe, œufs de saumon et oursins — chirashi de fête ultime.', 50, 50, 'advanced', 'L uni (oursin) doit être posé au dernier moment — il s oxyde rapidement.', 'Le chirashi de luxe est servi lors des grandes occasions : mariages, anniversaires, Hinamatsuri.', '[{"term":"uni","definition":"oursin — le luxe du chirashi japonais"},{"term":"ikura","definition":"œufs de saumon marinés en soja et mirin"}]')
) AS v(title, description, order_index, duration_min, difficulty, chef_tip, cultural_note, vocabulary)
CROSS JOIN (SELECT id FROM public.paths WHERE slug='japanese' LIMIT 1) p;

-- ============================================================
-- MOROCCAN LESSONS 36-50
-- ============================================================
INSERT INTO public.lessons (id, path_id, title, description, order_index, duration_min, difficulty, chef_tip, cultural_note, vocabulary)
SELECT gen_random_uuid(), p.id, v.title, v.description, v.order_index, v.duration_min, v.difficulty, v.chef_tip, v.cultural_note, v.vocabulary::jsonb
FROM (VALUES
  ('Le Tajine de Poulet au Citron Confit', 'Poulet braisé aux olives et citrons confits marocains — le tajine le plus célèbre.', 36, 90, 'intermediate', 'Utilisez uniquement la peau du citron confit — la chair est trop salée.', 'Le citron confit est un condiment fondamental de la cuisine marocaine, préparé en grande quantité.', '[{"term":"citron confit","definition":"citron fermenté dans le sel pendant 1 mois"},{"term":"olives violettes","definition":"olives marocaines légèrement amères pour le tajine"}]'),
  ('Le Harira Enrichie', 'Version enrichie de la soupe harira aux vermicelles, coriandre et citron.', 37, 60, 'intermediate', 'Le tedouira (épaississant farine-eau) est ajouté en dernier pour la consistance.', 'La harira est la soupe de rupture du jeûne (iftar) pendant le Ramadan.', '[{"term":"harira","definition":"soupe nationale marocaine aux lentilles et pois chiches"},{"term":"tedouira","definition":"mélange farine et eau qui épaissit la harira"}]'),
  ('La Trid au Poulet', 'Crêpes msemen superposées au poulet braisé et sauce au safran — plat de mariage.', 38, 90, 'advanced', 'Les crêpes msemen doivent être très fines pour absorber le bouillon.', 'Le trid est le plat des noces marocaines — mentionné comme plat favori du Prophète Muhammad.', '[{"term":"msemen","definition":"crêpe feuilletée marocaine à la semoule"},{"term":"smen","definition":"beurre fermenté marocain — arôme distinctif"}]'),
  ('Les Kemia Marocaines', 'Assortiment de petits plats froids — carottes, zaalouk, taktouka, chermoula.', 39, 40, 'beginner', 'Les kemia se servent à température ambiante — jamais froides du réfrigérateur.', 'Les kemia sont les tapas marocaines — obligatoires avant tout repas traditionnel.', '[{"term":"kemia","definition":"petits plats d entrée marocains — équivalent des tapas"},{"term":"chermoula","definition":"marinade herbes, épices et citron — très polyvalente"}]'),
  ('Le Méchoui d Agneau', 'Agneau entier rôti à la braise pendant des heures — plat des grandes fêtes.', 40, 360, 'advanced', 'L agneau doit être badigeonné toutes les 30 minutes pour rester juteux.', 'Le méchoui est le plat des Aïd et des mariages — un art en soi pour les maîtres rôtisseurs.', '[{"term":"méchoui","definition":"agneau rôti entier à la braise — du mot arabe rôtir"},{"term":"cumin","definition":"épice incontournable du méchoui marocain"}]'),
  ('Le Mrouzia Festive', 'Agneau aux amandes, raisins et épices ras el hanout en sauce miel — Aïd al-Adha.', 41, 180, 'advanced', 'Le ras el hanout doit contenir au moins 20 épices pour la mrouzia authentique.', 'La mrouzia est préparée uniquement pour l Aïd al-Adha — une fois par an.', '[{"term":"mrouzia","definition":"tajine festif sucré-salé de l Aïd"},{"term":"ras el hanout","definition":"tête de l épicerie — mélange de 20 à 30 épices"}]'),
  ('Les Crêpes Baghrir Avancées', 'Baghrir à mille trous perfectionnés — plus moelleux et plus aérien.', 42, 30, 'beginner', 'La pâte doit reposer 30 minutes pour que les trous se forment à la cuisson.', 'La baghrir est la crêpe du petit-déjeuner marocain, souvent trempée dans du beurre et miel.', '[{"term":"baghrir","definition":"crêpe marocaine à mille trous à la semoule fine"},{"term":"beurre-miel","definition":"accompanement traditionnel des baghrir"}]'),
  ('La Pastilla au Pigeon', 'Version originale de la pastilla au pigeon et amandes — version de fête ancienne.', 43, 120, 'advanced', 'Le contraste sucré-salé-épicé est la signature de la pastilla — ne réduisez pas le sucre.', 'La pastilla originale est au pigeon (avant le poulet) — recette de la cuisine berbère ancienne.', '[{"term":"pastilla","definition":"tourte feuilletée sucrée-salée marocaine"},{"term":"warka","definition":"feuille de pastilla marocaine très fine et délicate"}]'),
  ('Le Couscous au Beurre Frais', 'Couscous roulé à la main, cuit à la vapeur trois fois, beurre frais.', 44, 90, 'intermediate', 'Roulez le couscous à la main avec un peu d eau pour obtenir des grains séparés.', 'Le couscous roulé à la main est un art féminin transmis de mère en fille au Maroc.', '[{"term":"rouler","definition":"technique de main pour séparer et humidifier le couscous"},{"term":"couscoussier","definition":"la marmite à deux niveaux pour cuire le couscous"}]'),
  ('La Soupe de Fèves Bessara', 'Purée de fèves sèches à l huile d olive, cumin et paprika — petit-déjeuner populaire.', 45, 60, 'beginner', 'Ajoutez de l huile d olive crue en filet sur la bessara servie — c est fondamental.', 'La bessara est le petit-déjeuner des travailleurs marocains — nourrissante et économique.', '[{"term":"bessara","definition":"purée de fèves sèches marocaine"},{"term":"fèves sèches","definition":"fèves déshydratées — plus riches en protéines que les fraîches"}]'),
  ('Le Tajine de Sardines Farcies', 'Sardines farcies à la chermoula, cuites au tajine avec tomates et citron.', 46, 45, 'intermediate', 'La chermoula doit être bien épicée — c est elle qui parfume les sardines.', 'Ce plat côtier marocain est particulièrement populaire à Safi et Essaouira.', '[{"term":"sardines farcies","definition":"sardines ouvertes et farcies de chermoula"},{"term":"chermoula","definition":"marinade marocaine aux herbes, ail, épices et citron"}]'),
  ('Les Sellou (Sfouf)', 'Pâte sèche énergétique de semoule grillée, beurre, miel et amandes — Ramadan.', 47, 45, 'beginner', 'Le sellou doit avoir la consistance d une pâte à modeler souple — pas trop sec.', 'Le sellou est préparé pour le Ramadan et pour les femmes qui viennent d accoucher.', '[{"term":"sellou","definition":"confiserie énergétique marocaine de Ramadan"},{"term":"anis","definition":"épice caractéristique du sellou"}]'),
  ('Les Choumicha Kaab el Ghazal', 'Cornes de gazelle fourrées à la pâte d amandes — pâtisserie marocaine de fête.', 48, 90, 'intermediate', 'Les cornes doivent être très fines — travaillez la pâte longtemps pour l assouplir.', 'Les cornes de gazelle (kaab el ghazal) sont la pâtisserie marocaine la plus connue à l international.', '[{"term":"kaab el ghazal","definition":"cheville de gazelle — forme de la pâtisserie"},{"term":"eau de fleur d oranger","definition":"parfum caractéristique de la pâtisserie marocaine"}]'),
  ('Le Thé à la Menthe Cérémonie', 'L art du thé marocain : thé vert Gunpowder, menthe fraîche, sucre en pain.', 49, 20, 'beginner', 'Versez le thé de haut pour créer la mousse — signe d hospitalité.', 'Le thé à la menthe est le symbole de l hospitalité marocaine — trois verres sont la tradition.', '[{"term":"atay","definition":"thé en darija marocain"},{"term":"Gunpowder","definition":"thé vert chinois en billes — base du thé marocain"}]'),
  ('Le Diffa Marocaine Complète', 'Repas festif complet : kemia, soupe, tajine, couscous, pastilla, thé.', 50, 240, 'advanced', 'La diffa commence par les petits plats et se termine par le couscous et les douceurs.', 'La diffa est le grand festin marocain des occasions exceptionnelles — mariages et Aid.', '[{"term":"diffa","definition":"festin marocain — repas de fête complet"},{"term":"sequence","definition":"l ordre des plats dans la diffa marocaine traditionnelle"}]')
) AS v(title, description, order_index, duration_min, difficulty, chef_tip, cultural_note, vocabulary)
CROSS JOIN (SELECT id FROM public.paths WHERE slug='moroccan' LIMIT 1) p;

-- ============================================================
-- RECIPES FOR FRENCH LESSONS 36-50
-- ============================================================
INSERT INTO public.recipes (id, lesson_id, title, description, emoji, prep_time_min, cook_time_min, servings, difficulty, avg_price_eur, ingredients, instructions, chef_tip, cultural_note)
SELECT gen_random_uuid(), l.id, v.title, v.description, v.emoji, v.prep_time_min, v.cook_time_min, v.servings, v.difficulty, v.avg_price_eur, v.ingredients::jsonb, v.instructions::jsonb, v.chef_tip, v.cultural_note
FROM (VALUES
  ('La Tarte Flambée Alsacienne', 'Tarte flambée croustillante à la crème fraîche, oignons et lardons.', '🫕', 20, 10, 4, 'beginner', 7.0,
   '[{"qty":"300g","item":"farine"},{"qty":"150ml","item":"eau tiède"},{"qty":"1 c.c.","item":"sel"},{"qty":"2 c.s.","item":"huile"},{"qty":"300ml","item":"crème fraîche épaisse"},{"qty":"200g","item":"lardons"},{"qty":"2","item":"oignons en fines rondelles"},{"qty":"sel, poivre","item":"et muscade"}]',
   '["Mélangez farine, eau, sel, huile — pétrie 5 min","Pas de levure — la pâte ne lève pas","Étalez très finement sur papier cuisson","Mélangez crème fraîche, sel, poivre, muscade","Étalez sur la pâte","Disposez oignons et lardons","Enfournez à 280°C (max) 8-10 min jusqu à bords carbonisés","Servez immédiatement"]',
   'La pâte doit être ultra-fine — presque transparente. C est cela qui fait la flammekueche.', 'La tarte flambée était cuite dans les fours à pain alsaciens pour tester leur température avant le pain.'),
  ('Le Lapin à la Moutarde', 'Lapin braisé dans une sauce crémeuse à la moutarde de Dijon.', '🐰', 15, 60, 4, 'intermediate', 9.0,
   '[{"qty":"1","item":"lapin coupé en morceaux"},{"qty":"4 c.s.","item":"moutarde de Dijon forte"},{"qty":"200ml","item":"vin blanc sec"},{"qty":"200ml","item":"crème fraîche épaisse"},{"qty":"2 gousses","item":"ail"},{"qty":"thym","item":"et laurier"},{"qty":"30g","item":"beurre"}]',
   '["Enduisez les morceaux de lapin de moutarde","Faites dorer dans le beurre 5 min par côté","Ajoutez ail et herbes","Versez le vin blanc, grattez le fond","Couvrez et laissez braiser 45 min","Retirez le lapin","Ajoutez la crème à la sauce","Réduisez 5 min, vérifiez l assaisonnement","Remettez le lapin dans la sauce"]',
   'L enduisage de moutarde avant la cuisson forme une croûte parfumée qui se fond ensuite dans la sauce.', 'Le lapin à la moutarde est un grand classique de la cuisine bourgeoise française.'),
  ('Les Pommes Sarladaises', 'Pommes de terre fondantes à la graisse de canard et à l ail.', '🥔', 15, 45, 4, 'beginner', 5.0,
   '[{"qty":"800g","item":"pommes de terre à chair ferme"},{"qty":"100g","item":"graisse de canard"},{"qty":"4 gousses","item":"ail"},{"qty":"persil plat","item":"fraîs"},{"qty":"sel","item":"et poivre"}]',
   '["Pelez et tranchez les pommes de terre en rondelles de 3mm","Séchez avec du papier absorbant","Faites fondre la graisse de canard dans une poêle","Ajoutez les pommes de terre en couche uniforme","Cuisez à feu moyen 30-35 min en retournant régulièrement","Ajoutez l ail haché les 5 dernières minutes","Assaisonnez et parsemez de persil"]',
   'La graisse de canard en grande quantité est le secret — pas d huile, pas de beurre, uniquement la graisse.', 'Sarlat-la-Canéda dans le Périgord est la capitale gastronomique de la région foie gras et truffe.'),
  ('Le Bœuf Bourguignon Traditionnel', 'Bœuf braisé au vin de Bourgogne avec champignons et lardons.', '🥩', 30, 180, 6, 'intermediate', 12.0,
   '[{"qty":"1.2kg","item":"bœuf à braiser (joue ou paleron)"},{"qty":"750ml","item":"vin rouge de Bourgogne"},{"qty":"200g","item":"lardons"},{"qty":"200g","item":"champignons de Paris"},{"qty":"200g","item":"petits oignons grelots"},{"qty":"3","item":"carottes"},{"qty":"2 gousses","item":"ail"},{"qty":"thym","item":"et laurier"},{"qty":"2 c.s.","item":"farine"}]',
   '["Marinez le bœuf coupé en cubes dans le vin 24h","Égouttez et séchez la viande, réservez la marinade","Faites revenir les lardons, réservez","Dorez la viande en plusieurs fois","Farinez, cuisez 2 min","Ajoutez la marinade, légumes et herbes","Couvrez et enfournez 2h30 à 160°C","Ajoutez champignons et oignons glacés la dernière heure"]',
   'Le bœuf bourguignon est toujours meilleur réchauffé le lendemain — les saveurs s unifient.', 'Le bœuf bourguignon est le plat français le plus connu à l international, popularisé par Julia Child aux USA.')
) AS v(lesson_title, title, description, emoji, prep_time_min, cook_time_min, servings, difficulty, avg_price_eur, ingredients, instructions, chef_tip, cultural_note)
JOIN public.lessons l ON l.title = v.lesson_title;

-- ============================================================
-- RECIPES FOR ITALIAN LESSONS 36-50
-- ============================================================
INSERT INTO public.recipes (id, lesson_id, title, description, emoji, prep_time_min, cook_time_min, servings, difficulty, avg_price_eur, ingredients, instructions, chef_tip, cultural_note)
SELECT gen_random_uuid(), l.id, v.title, v.description, v.emoji, v.prep_time_min, v.cook_time_min, v.servings, v.difficulty, v.avg_price_eur, v.ingredients::jsonb, v.instructions::jsonb, v.chef_tip, v.cultural_note
FROM (VALUES
  ('La Pizza Margherita Napolitaine', 'Pizza napolitaine classique à la mozzarella di bufala et basilic frais.', '🍕', 30, 10, 4, 'intermediate', 8.0,
   '[{"qty":"500g","item":"farine 00"},{"qty":"325ml","item":"eau froide"},{"qty":"10g","item":"sel"},{"qty":"2g","item":"levure fraîche"},{"qty":"400ml","item":"tomates San Marzano écrasées"},{"qty":"300g","item":"mozzarella di bufala"},{"qty":"feuilles","item":"de basilic frais"},{"qty":"huile","item":"d olive extra-vierge"}]',
   '["Mélangez eau et levure, ajoutez farine et sel","Pétrissez 10 min, pâte lisse","Faites lever 24h au réfrigérateur","Formez 4 pâtons, laissez lever 2h à température","Étalez à la main (pas de rouleau) en cercle","Garnissez de tomates, sel, huile","Enfournez à max (280-300°C) 60-90 secondes","Sortez du four, ajoutez mozzarella et basilic"]',
   'La pâte napolitaine se travaille à la main — jamais au rouleau. L air doit rester dans les bords.', 'La pizza Margherita a été créée en 1889 par Raffaele Esposito pour la reine Margherite de Savoie à Naples.'),
  ('Le Vitello Tonnato', 'Veau poché tranché fin avec sauce crémeuse au thon et câpres.', '🐟', 20, 40, 6, 'intermediate', 12.0,
   '[{"qty":"800g","item":"noix de veau"},{"qty":"légumes","item":"pour le pochage (oignon, céleri, carotte)"},{"qty":"sauce tonnato:","item":""},{"qty":"200g","item":"thon en conserve à l huile"},{"qty":"4","item":"filets d anchois"},{"qty":"2 c.s.","item":"câpres"},{"qty":"2","item":"jaunes d œuf"},{"qty":"150ml","item":"huile d olive"},{"qty":"jus","item":"d 1 citron"}]',
   '["Pochez le veau dans un bouillon de légumes 40 min","Laissez refroidir dans le bouillon","Mixez thon, anchois, câpres, jaunes d œuf","Incorporez l huile en filet comme une mayonnaise","Ajoutez jus de citron et 2 c.s. de bouillon pour fluidifier","Tranchez le veau très fin","Nappez de sauce et garnissez de câpres","Réfrigérez 2h avant de servir"]',
   'Le veau doit être tranché aussi fin que possible — presque comme de la charcuterie.', 'Le vitello tonnato est l antipasto roi du Piémont — son association veau-thon semble bizarre mais est divine.'),
  ('La Bagna Cauda', 'Fondue chaude d anchois et ail dans l huile d olive — trempette piémontaise.', '🫕', 15, 20, 4, 'beginner', 8.0,
   '[{"qty":"8 gousses","item":"ail"},{"qty":"150ml","item":"lait (pour blanchir l ail)"},{"qty":"200ml","item":"huile d olive extra-vierge"},{"qty":"80g","item":"anchois salés rincés"},{"qty":"50g","item":"beurre"},{"qty":"légumes crus:","item":"poivrons, cardons, carottes, choux..."}]',
   '["Blanchissez l ail 3 fois dans le lait","Égouttez et mixez en purée","Chauffez l huile à feu très doux","Ajoutez la purée d ail et les anchois","Remuez jusqu à dissolution des anchois (20 min)","Ajoutez le beurre en fin de cuisson","Servez dans un plat à bain-marie sur bougie","Trempez les légumes crus"]',
   'L ail blanchi 3 fois dans le lait perd son piquant — il devient doux et crémeux.', 'La bagna cauda est le symbole de l automne piémontais — partagé au centre de la table entre amis.'),
  ('Le Risotto Nero alle Seppie', 'Risotto noir à l encre de seiche avec seiches tendres.', '🦑', 15, 30, 4, 'intermediate', 14.0,
   '[{"qty":"320g","item":"riz à risotto (Carnaroli)"},{"qty":"400g","item":"seiches nettoyées"},{"qty":"2 sachets","item":"d encre de seiche"},{"qty":"200ml","item":"vin blanc"},{"qty":"1L","item":"fumet de poisson chaud"},{"qty":"1","item":"oignon"},{"qty":"3 gousses","item":"ail"},{"qty":"50g","item":"beurre"},{"qty":"huile","item":"d olive"}]',
   '["Faites revenir oignon et ail dans l huile","Ajoutez les seiches en dés, cuisez 5 min","Ajoutez le riz, nacrez 2 min","Versez le vin blanc, laissez absorber","Ajoutez l encre de seiche","Ajoutez le fumet louche par louche en remuant","Cuisez 18 min total","Mantecate avec beurre froid hors feu","Servez sans fromage — la règle du risotto ai frutti di mare"]',
   'L encre de seiche est ajoutée tôt pour une couleur uniforme et profonde.', 'Le risotto nero est la fierté de Venise — servi sans parmesan contrairement aux autres risotti.')
) AS v(lesson_title, title, description, emoji, prep_time_min, cook_time_min, servings, difficulty, avg_price_eur, ingredients, instructions, chef_tip, cultural_note)
JOIN public.lessons l ON l.title = v.lesson_title;

-- ============================================================
-- RECIPES FOR JAPANESE LESSONS 36-50
-- ============================================================
INSERT INTO public.recipes (id, lesson_id, title, description, emoji, prep_time_min, cook_time_min, servings, difficulty, avg_price_eur, ingredients, instructions, chef_tip, cultural_note)
SELECT gen_random_uuid(), l.id, v.title, v.description, v.emoji, v.prep_time_min, v.cook_time_min, v.servings, v.difficulty, v.avg_price_eur, v.ingredients::jsonb, v.instructions::jsonb, v.chef_tip, v.cultural_note
FROM (VALUES
  ('Le Sukiyaki', 'Bœuf tranché fin cuit dans un bouillon sucré-salé, avec œuf cru pour tremper.', '🥩', 20, 20, 4, 'beginner', 16.0,
   '[{"qty":"400g","item":"bœuf (tranché très fin)"},{"qty":"200g","item":"tofu ferme"},{"qty":"200g","item":"champignons shiitake"},{"qty":"100g","item":"shirataki"},{"qty":"4","item":"feuilles de chou"},{"qty":"warishita:","item":""},{"qty":"100ml","item":"sauce soja"},{"qty":"100ml","item":"mirin"},{"qty":"2 c.s.","item":"sucre"},{"qty":"4","item":"œufs frais (pour tremper)"}]',
   '["Préparez le warishita: soja + mirin + sucre, portez à ébullition","Disposez tous les ingrédients dans la fondue","Versez le warishita dans la poêle chaude","Cuisez les ingrédients selon votre préférence","Chaque convive prend les aliments et les trempe dans l œuf cru battu","Ajoutez les ingrédients au fur et à mesure","Complétez le warishita si nécessaire"]',
   'L œuf cru battu dans lequel on trempe chaque bouchée est la signature du sukiyaki — ne l omettez pas.', 'Le sukiyaki est le plat de célébration japonais — servi pour le Nouvel An et les grandes occasions.'),
  ('La Tempura de Crevettes', 'Crevettes et légumes frits dans une pâte légère et croustillante.', '🍤', 20, 20, 4, 'intermediate', 12.0,
   '[{"qty":"12","item":"grosses crevettes décortiquées (queue gardée)"},{"qty":"légumes:","item":"patate douce, poivron, shiitake"},{"qty":"pâte tempura:","item":""},{"qty":"150g","item":"farine à tempura (ou farine + maïzena)"},{"qty":"200ml","item":"eau glacée"},{"qty":"1","item":"jaune d œuf"},{"qty":"tentsuyu:","item":""},{"qty":"200ml","item":"dashi"},{"qty":"50ml","item":"sauce soja"},{"qty":"50ml","item":"mirin"}]',
   '["Préparez le tentsuyu: chauffez dashi + soja + mirin","Faites 4 incisions sous chaque crevette pour éviter qu elle se recourbe","Préparez la pâte tempura: mélangez brièvement — des grumeaux sont normaux","L eau doit être glacée","Chauffez l huile à 175°C","Trempez crevettes et légumes dans la pâte","Faites frire 2-3 min","Servez immédiatement avec tentsuyu et daikon râpé"]',
   'La pâte grumeleuse est intentionnelle — les grumeaux croustillent. Ne jamais fouetter trop.', 'La tempura a été introduite au Japon par les missionnaires jésuites portugais au XVIe siècle.'),
  ('Les Mochi Daifuku', 'Mochi moelleux fourré de pâte de haricots rouges sucrée.', '🍡', 30, 15, 8, 'intermediate', 5.0,
   '[{"qty":"200g","item":"shiratamako (farine de riz gluant)"},{"qty":"180ml","item":"eau"},{"qty":"50g","item":"sucre"},{"qty":"200g","item":"anko (pâte de haricots rouges)"},{"qty":"fécule","item":"de pomme de terre pour manipuler"}]',
   '["Mélangez shiratamako, eau et sucre dans un bol allant au micro-ondes","Cuisez 2 min, remuez, cuisez encore 2 min","Le mochi doit être translucide et élastique","Laissez tiédir","Saupoudrez le plan de travail de fécule de pomme de terre","Étalez le mochi en disques","Placez une boule d anko au centre","Refermez soigneusement et formez une boule"]',
   'Trempez vos mains dans la fécule constamment — le mochi colle partout sinon.', 'Le daifuku (grand bonheur) est offert lors des fêtes japonaises et dans les temples.')
) AS v(lesson_title, title, description, emoji, prep_time_min, cook_time_min, servings, difficulty, avg_price_eur, ingredients, instructions, chef_tip, cultural_note)
JOIN public.lessons l ON l.title = v.lesson_title;

-- ============================================================
-- RECIPES FOR MOROCCAN LESSONS 36-50
-- ============================================================
INSERT INTO public.recipes (id, lesson_id, title, description, emoji, prep_time_min, cook_time_min, servings, difficulty, avg_price_eur, ingredients, instructions, chef_tip, cultural_note)
SELECT gen_random_uuid(), l.id, v.title, v.description, v.emoji, v.prep_time_min, v.cook_time_min, v.servings, v.difficulty, v.avg_price_eur, v.ingredients::jsonb, v.instructions::jsonb, v.chef_tip, v.cultural_note
FROM (VALUES
  ('Le Tajine de Poulet au Citron Confit', 'Poulet braisé aux olives et citrons confits — le tajine emblématique du Maroc.', '🍋', 20, 75, 4, 'intermediate', 9.0,
   '[{"qty":"1","item":"poulet entier coupé en morceaux"},{"qty":"2","item":"citrons confits (seulement la peau)"},{"qty":"150g","item":"olives violettes marocaines"},{"qty":"2","item":"oignons"},{"qty":"3 gousses","item":"ail"},{"qty":"épices:","item":"safran, gingembre, cumin, coriandre"},{"qty":"coriandre","item":"fraîche"},{"qty":"huile","item":"d olive"}]',
   '["Faites revenir les oignons émincés dans l huile d olive","Ajoutez ail et épices, cuisez 2 min","Ajoutez les morceaux de poulet, dorez légèrement","Ajoutez 200ml d eau","Couvrez et laissez mijoter 45 min","Ajoutez la peau de citron confit et les olives","Laissez encore 15 min","Parsemez de coriandre fraîche"]',
   'Utilisez uniquement la peau du citron confit — la pulpe est trop salée et amère.', 'Le citron confit est fermenté au sel pendant un mois — il développe des saveurs umami profondes.'),
  ('La Mrouzia Festive', 'Agneau aux amandes, raisins et miel en sauce ras el hanout — plat de l Aïd.', '🍖', 20, 180, 6, 'advanced', 15.0,
   '[{"qty":"1.2kg","item":"agneau (épaule en gros morceaux)"},{"qty":"100g","item":"amandes entières mondées"},{"qty":"100g","item":"raisins secs"},{"qty":"3 c.s.","item":"miel"},{"qty":"2 c.s.","item":"ras el hanout"},{"qty":"1 c.c.","item":"gingembre"},{"qty":"1 c.c.","item":"cannelle"},{"qty":"1 c.c.","item":"safran"},{"qty":"beurre","item":"pour cuire"}]',
   '["Faites revenir l agneau dans le beurre avec le safran","Ajoutez toutes les épices et 300ml d eau","Couvrez et laissez mijoter 1h30","Ajoutez amandes, raisins et miel","Réduisez la sauce à feu vif sans couvercle","La sauce doit être sirupeuse et brillante","Servez avec du couscous ou du pain marocain"]',
   'Le ras el hanout doit être de qualité — c est l épice principale de la mrouzia.', 'La mrouzia est préparée avec le mouton de l Aïd al-Adha — une fois par an pour la fête du sacrifice.'),
  ('Le Couscous au Beurre Frais', 'Couscous cuit à la vapeur trois fois, beurre frais et bouillon — la base parfaite.', '🌾', 20, 60, 6, 'intermediate', 6.0,
   '[{"qty":"500g","item":"couscous de blé dur"},{"qty":"100g","item":"beurre frais"},{"qty":"sel","item":"au goût"},{"qty":"eau tiède","item":"pour hydrater"},{"qty":"500ml","item":"bouillon de légumes ou viande pour servir"}]',
   '["Versez le couscous dans un grand plat","Ajoutez 200ml d eau salée et mélangez à la main","Laissez gonfler 10 min","Roulez à la main pour séparer les grains","Cuisez à la vapeur 20 min dans le couscoussier","Sortez, étalez, ajoutez beurre et un peu d eau","Roulez à nouveau","Deuxième passage vapeur 20 min","Troisième passage si nécessaire pour des grains parfaits"]',
   'La technique de roulage à la main entre chaque passage vapeur est le secret des grains séparés.', 'Rouler le couscous est un art transmis de mère en fille au Maroc — chaque famille a sa technique.')
) AS v(lesson_title, title, description, emoji, prep_time_min, cook_time_min, servings, difficulty, avg_price_eur, ingredients, instructions, chef_tip, cultural_note)
JOIN public.lessons l ON l.title = v.lesson_title;

-- ============================================================
-- EXERCISES FOR FRENCH LESSONS 36-50
-- ============================================================
INSERT INTO public.exercises (id, lesson_id, type, question, options, correct_answer, explanation, order_index)
SELECT gen_random_uuid(), l.id, v.type, v.question, v.options::jsonb, v.correct_answer, v.explanation, v.order_index
FROM (VALUES
  ('La Tarte Flambée Alsacienne', 'multiple_choice', 'Quel est l autre nom de la tarte flambée en alsacien ?', '["Flammekueche","Zwiebelkuchen","Käsekuchen","Speckkuchen"]', 'Flammekueche', 'Flammekueche signifie tarte cuite dans la flamme — elle était cuite directement dans le feu.', 1),
  ('La Tarte Flambée Alsacienne', 'fill_in_blank', 'La pâte de la tarte flambée doit être ultra-___ — presque transparente', '[]', 'fine', 'La finesse de la pâte est la caractéristique principale — elle croustille et se carbonise légèrement.', 2),
  ('Les Grenouilles à la Provençale', 'multiple_choice', 'Quelle est la persillade ?', '["Mélange d ail et persil haché","Sauce persil","Huile de persil","Bouquet garni"]', 'Mélange d ail et persil haché', 'La persillade est la base aromatique de nombreux plats français — rapide et puissante.', 1),
  ('Les Grenouilles à la Provençale', 'fill_in_blank', 'Les cuisses de grenouilles cuisent très vite — ___ minutes par côté maximum', '[]', '2', 'Les grenouilles sont très maigres et cuisent en quelques secondes — trop cuites, elles deviennent caoutchouteuses.', 2),
  ('Le Gratin de Macaronis Lyonnais', 'multiple_choice', 'Quel fromage est idéal pour le gratin lyonnais ?', '["Comté vieux","Emmental","Gruyère","Reblochon"]', 'Comté vieux', 'Le comté affiné plus de 12 mois a des notes complexes de noisette qui élèvent tout gratin.', 1),
  ('Le Gratin de Macaronis Lyonnais', 'fill_in_blank', 'Les restaurants traditionnels lyonnais s appellent des ___', '[]', 'bouchons', 'Les bouchons lyonnais sont des restaurants familiaux avec une cuisine traditionnelle et populaire.', 2),
  ('La Bouillabaisse Marseillaise', 'multiple_choice', 'Que signifie le mot bouillabaisse ?', '["Ça bout, on abaisse le feu","Grande bouilloire","Soupe de base","Faire bouillir deux fois"]', 'Ça bout, on abaisse le feu', 'L étymologie provençale: bouilli (ça bout) + abaisse (on baisse) décrit la technique de cuisson.', 1),
  ('La Bouillabaisse Marseillaise', 'fill_in_blank', 'La sauce à l ail et au safran servie avec la bouillabaisse s appelle la ___', '[]', 'rouille', 'La rouille (rousse en provençal — pour la couleur) est l accompagnement essentiel de la bouillabaisse.', 2),
  ('Le Gratin de Cardons à la Moelle', 'multiple_choice', 'À quel repas le gratin de cardons est-il traditionnellement servi à Lyon ?', '["Le réveillon de Noël","Le repas de Pâques","Le mariage","La fête des mères"]', 'Le réveillon de Noël', 'Le gratin de cardons à la moelle est LE plat du réveillon lyonnais — une tradition immuable.', 1),
  ('Le Gratin de Cardons à la Moelle', 'fill_in_blank', 'Le cardon est un légume cousin de l ___', '[]', 'artichaut', 'Le cardon et l artichaut sont deux variétés de la même plante — le cardon utilise les tiges.', 2),
  ('Le Vacherin Mont d Or', 'multiple_choice', 'Quand est disponible le Mont d Or ?', '["Automne-hiver uniquement","Toute l année","Été seulement","Printemps-été"]', 'Automne-hiver uniquement', 'Le Mont d Or est un fromage à AOP saisonnière — produit uniquement de août à mars.', 1),
  ('Le Vacherin Mont d Or', 'fill_in_blank', 'Pour cuire le Mont d Or au four, on l ___ de vin blanc avant d enfourner', '[]', 'arrose', 'Le vin blanc pénètre dans la croûte et parfume la crème intérieure du fromage.', 2),
  ('Le Lapin à la Moutarde', 'multiple_choice', 'Pourquoi enduire le lapin de moutarde avant de le saisir ?', '["Pour former une croûte parfumée","Pour l attendrir","Pour éviter qu il colle","Pour la couleur"]', 'Pour former une croûte parfumée', 'La moutarde forme une croûte à la cuisson qui se fond ensuite dans la sauce crémeuse.', 1),
  ('Le Lapin à la Moutarde', 'fill_in_blank', 'La ___ de Dijon est la moutarde française la plus connue', '[]', 'moutarde', 'La moutarde de Dijon est forte et vinaigrée — incontournable dans la cuisine française.', 2),
  ('Le Pâté en Croûte', 'multiple_choice', 'Qu ajoute-t-on dans le trou du pâté en croûte après cuisson ?', '["De la gelée pour combler les espaces","De la farce supplémentaire","Du beurre","Du vin"]', 'De la gelée pour combler les espaces', 'La viande rétrécit à la cuisson — la gelée remplie les espaces vides et conserve.', 1),
  ('Le Pâté en Croûte', 'fill_in_blank', 'Il existe un championnat du monde du pâté en croûte depuis 2009 à ___', '[]', 'Lyon', 'Lyon est la capitale de la gastronomie française — le pâté en croûte y est élevé au rang d art.', 2),
  ('Les Pommes Sarladaises', 'multiple_choice', 'Quel corps gras utilise-t-on pour les pommes sarladaises ?', '["Graisse de canard","Beurre","Huile d olive","Saindoux"]', 'Graisse de canard', 'La graisse de canard est la matière grasse emblématique de la cuisine du Périgord et du Sud-Ouest.', 1),
  ('Les Pommes Sarladaises', 'fill_in_blank', 'Sarlat est la capitale gastronomique du ___', '[]', 'Périgord', 'Le Périgord (Dordogne) est la région du foie gras, de la truffe noire et des pommes sarladaises.', 2),
  ('Le Civet de Chevreuil', 'multiple_choice', 'Combien de temps faut-il mariner le chevreuil ?', '["24-48 heures","2 heures","30 minutes","1 semaine"]', '24-48 heures', 'Le gibier a une chair forte — la longue marinade au vin attendrit et parfume la viande.', 1),
  ('Le Civet de Chevreuil', 'fill_in_blank', 'Le chevreuil est disponible en automne lors de la ___', '[]', 'chasse', 'La saison de chasse en France commence en automne — le chevreuil est l un des gibiers les plus courants.', 2),
  ('Le Soufflé au Comté', 'multiple_choice', 'Quelle est la règle d or du soufflé salé ?', '["Le servir immédiatement","Le préparer à l avance","Le réchauffer au micro-ondes","Le mettre au réfrigérateur avant"]', 'Le servir immédiatement', 'Un soufflé attend personne — il commence à retomber dès la sortie du four.', 1),
  ('Le Soufflé au Comté', 'fill_in_blank', 'Le soufflé gonfle grâce à la dilatation des ___ en neige à la chaleur', '[]', 'blancs', 'Les bulles d air des blancs en neige se dilatent à la chaleur du four — le soufflé monte.', 2),
  ('Les Œufs Meurette', 'multiple_choice', 'Quel est l ingrédient caractéristique de la meurette bourguignonne ?', '["Vin rouge de Bourgogne","Vin blanc","Beurre blanc","Crème fraîche"]', 'Vin rouge de Bourgogne', 'La sauce meurette est à base de vin rouge — c est la sauce bourguignonne par définition.', 1),
  ('Les Œufs Meurette', 'fill_in_blank', 'On ajoute du ___ dans l eau de pochage pour maintenir les blancs compacts', '[]', 'vinaigre', 'L acide (vinaigre ou citron) fait coaguler les protéines du blanc d œuf rapidement.', 2),
  ('Le Foie Gras Poêlé', 'multiple_choice', 'Le foie gras est classé dans quelle catégorie patrimoniale ?', '["Patrimoine gastronomique et culturel de France","Patrimoine mondial de l UNESCO","AOP européenne","Monument historique"]', 'Patrimoine gastronomique et culturel de France', 'Une loi de 2005 classe le foie gras comme patrimoine gastronomique et culturel protégé.', 1),
  ('Le Foie Gras Poêlé', 'fill_in_blank', 'La poêle doit être très chaude et ___ pour saisir le foie gras', '[]', 'sèche', 'Le foie gras libère son propre gras à la cuisson — ne jamais ajouter de matière grasse.', 2),
  ('Le Pot-au-Feu de la Mer', 'multiple_choice', 'Qu est-ce qu une nage en cuisine ?', '["Bouillon parfumé pour pocher les poissons","Technique de cuisson à la vapeur","Sauce crème aux herbes","Bouillon à base d arêtes"]', 'Bouillon parfumé pour pocher les poissons', 'La nage est un court-bouillon aromatisé spécifiquement pour la cuisson des produits de la mer.', 1),
  ('Le Pot-au-Feu de la Mer', 'fill_in_blank', 'Les légumes coupés en fins bâtonnets pour la garniture s appellent une ___', '[]', 'julienne', 'La julienne est une coupe précise en bâtonnets fins de 3-4mm — élégante pour les garnitu.', 2),
  ('Le Bœuf Bourguignon Traditionnel', 'multiple_choice', 'Qui a rendu le bœuf bourguignon célèbre aux États-Unis ?', '["Julia Child","Paul Bocuse","Auguste Escoffier","Fernand Point"]', 'Julia Child', 'Julia Child a popularisé le bœuf bourguignon auprès des Américains dans les années 1960.', 1),
  ('Le Bœuf Bourguignon Traditionnel', 'fill_in_blank', 'Le bœuf bourguignon est toujours meilleur réchauffé le ___ pour que les saveurs s unifient', '[]', 'lendemain', 'Comme tous les ragoûts, le bourguignon gagne en saveur en reposant une nuit au réfrigérateur.', 2)
) AS v(lesson_title, type, question, options, correct_answer, explanation, order_index)
JOIN public.lessons l ON l.title = v.lesson_title;

-- ============================================================
-- EXERCISES FOR ITALIAN LESSONS 36-50
-- ============================================================
INSERT INTO public.exercises (id, lesson_id, type, question, options, correct_answer, explanation, order_index)
SELECT gen_random_uuid(), l.id, v.type, v.question, v.options::jsonb, v.correct_answer, v.explanation, v.order_index
FROM (VALUES
  ('La Pizza Margherita Napolitaine', 'multiple_choice', 'Pour qui la pizza Margherita a-t-elle été créée ?', '["La reine Margherite de Savoie","Le roi Victor-Emmanuel","La princesse Diana","Le pape Léon XIII"]', 'La reine Margherite de Savoie', 'En 1889, Raffaele Esposito créa cette pizza pour la reine Margherite lors de sa visite à Naples.', 1),
  ('La Pizza Margherita Napolitaine', 'fill_in_blank', 'La pâte napolitaine doit lever ___ heures minimum au réfrigérateur', '[]', '24', 'La fermentation lente au froid développe des arômes complexes et des bulles légères.', 2),
  ('Le Vitello Tonnato', 'multiple_choice', 'Quel fromage NE doit PAS accompagner le vitello tonnato ?', '["Parmesan","La sauce tonnato suffit","Pecorino","Grana Padano"]', 'La sauce tonnato suffit', 'Le vitello tonnato est servi uniquement avec sa sauce tonnato et des câpres — le fromage n a pas sa place.', 1),
  ('Le Vitello Tonnato', 'fill_in_blank', 'Le vitello tonnato est l antipasto emblématique du ___', '[]', 'Piémont', 'Le Piémont (autour de Turin) est la région d origine du vitello tonnato — servi dans toutes les grandes tables.', 2),
  ('Les Bigoli al Torchio', 'multiple_choice', 'Comment s appelle la presse à pâtes vénitienne ?', '["Torchio","Bigolaro","Imperia","Macchina"]', 'Torchio', 'Le torchio est la presse en bois traditionnelle de Venise pour faire les bigoli.', 1),
  ('Les Bigoli al Torchio', 'fill_in_blank', 'La texture ___ des bigoli accroche bien la sauce', '[]', 'rugueuse', 'La surface rugueuse des bigoli (pâtes fraîches maison) retient mieux la sauce que les pâtes lisses.', 2),
  ('La Bagna Cauda', 'multiple_choice', 'Combien de fois blanchit-on l ail dans le lait pour la bagna cauda ?', '["3 fois","1 fois","5 fois","Pas de blanchissage"]', '3 fois', 'Trois blanchissages dans le lait éliminent progressivement le piquant de l ail — il devient doux.', 1),
  ('La Bagna Cauda', 'fill_in_blank', 'Bagna cauda signifie ___ en piémontais', '[]', 'bain chaud', 'Le nom décrit la fondue chaude dans laquelle on trempe les légumes à la bagna cauda.', 2),
  ('Le Brodetto di Pesce Adriatique', 'multiple_choice', 'Quelle épice parfume et colore le brodetto adriatique ?', '["Safran","Curcuma","Paprika","Piment"]', 'Safran', 'Le safran donne la couleur dorée et l arôme délicat caractéristiques du brodetto.', 1),
  ('Le Brodetto di Pesce Adriatique', 'fill_in_blank', 'Le brodetto est une soupe de ___ de la côte adriatique italienne', '[]', 'poissons', 'Chaque ville adriatique (Ancona, Rimini, Chioggia) a sa version du brodetto.', 2),
  ('Les Gnocchi al Gorgonzola', 'multiple_choice', 'Quelle version du gorgonzola est la moins piquante ?', '["Gorgonzola dolce","Gorgonzola piccante","Gorgonzola stagionato","Gorgonzola DOP"]', 'Gorgonzola dolce', 'Le gorgonzola dolce (doux) est jeune et crémeux — le piccante est affiné et puissant.', 1),
  ('Les Gnocchi al Gorgonzola', 'fill_in_blank', 'Le gorgonzola est l un des fromages AOP les plus anciens d Italie — créé en ___', '[]', '879', 'Le gorgonzola est mentionné dans des documents historiques de l an 879 après J.-C.', 2),
  ('La Pasta alla Norma Sicilienne', 'multiple_choice', 'En quel honneur la pasta alla Norma a-t-elle été nommée ?', '["L opéra Norma de Bellini","Une cuisinière sicilienne","La ville de Catane","Un saint patron"]', 'L opéra Norma de Bellini', 'Vincenzo Bellini est né à Catane — la pasta a été nommée en hommage à son opéra Norma.', 1),
  ('La Pasta alla Norma Sicilienne', 'fill_in_blank', 'La ricotta séchée et salée utilisée dans la pasta alla Norma s appelle ricotta ___', '[]', 'salata', 'La ricotta salata est différente de la fraîche — elle est pressée, séchée et salée.', 2),
  ('La Focaccia di Recco', 'multiple_choice', 'Quelle protection européenne a la focaccia di Recco ?', '["IGP (Indication Géographique Protégée)","AOP","Label Rouge","STG"]', 'IGP (Indication Géographique Protégée)', 'Seul Recco et ses communes voisines peuvent légalement appeler leur produit focaccia di Recco.', 1),
  ('La Focaccia di Recco', 'fill_in_blank', 'La focaccia di Recco est fourrée de ___ fondu', '[]', 'stracchino', 'Le stracchino est un fromage frais ligure ultra-fondant — spécifique à la focaccia di Recco.', 2),
  ('Le Brasato al Barolo', 'multiple_choice', 'Le Barolo vient de quelle région italienne ?', '["Piémont","Toscane","Veneto","Sicile"]', 'Piémont', 'Le Barolo est produit dans les collines des Langhe en Piémont — roi des vins italiens.', 1),
  ('Le Brasato al Barolo', 'fill_in_blank', 'Le brasato signifie ___ — la viande est cuite longtemps dans le vin', '[]', 'braisé', 'Brasato vient de brace (braises) — cuit à feu doux dans le liquide de cuisson.', 2),
  ('Les Sarde in Saor', 'multiple_choice', 'Pourquoi les sarde in saor se mangent-elles froides après 24h ?', '["La marinade a besoin de temps pour pénétrer","Pour des raisons d hygiène","C est plus facile à manger","C est une tradition uniquement"]', 'La marinade a besoin de temps pour pénétrer', 'La marinade agrodolce équilibre les saveurs en 24h — mangées fraîches, elles seraient trop acides.', 1),
  ('Les Sarde in Saor', 'fill_in_blank', 'Saor signifie ___ en vénitien', '[]', 'saveur', 'Le mot saor a évolué pour désigner la technique de marinade aigre-douce vénitienne.', 2),
  ('Le Tartufo di Pizzo', 'multiple_choice', 'D où vient le tartufo di Pizzo ?', '["Pizzo Calabro en Calabre","Piémont","Sicile","Sardaigne"]', 'Pizzo Calabro en Calabre', 'Le tartufo di Pizzo est une IGP calabraise née dans la ville de Pizzo dans les années 1950.', 1),
  ('Le Tartufo di Pizzo', 'fill_in_blank', 'Tartufo signifie ___ en italien — par analogie à la forme arrondie', '[]', 'truffe', 'La forme arrondie et irrégulière rappelle la truffe — d où le nom tartufo.', 2),
  ('La Pastiera Napoletana', 'multiple_choice', 'Quand mange-t-on la pastiera napolitaine ?', '["À Pâques","À Noël","Au Carnaval","Toute l année"]', 'À Pâques', 'La pastiera est LE dessert de Pâques napolitain — préparée une semaine à l avance.', 1),
  ('La Pastiera Napoletana', 'fill_in_blank', 'L eau de ___ parfume la pastiera napolitaine de façon caractéristique', '[]', 'fleur d oranger', 'L acqua di fiori d arancio est l arôme central de la pastiera — inremplaçable.', 2),
  ('Le Risotto Nero alle Seppie', 'multiple_choice', 'Que ne met-on JAMAIS sur le risotto nero ?', '["Parmesan","Huile d olive","Basilic","Persil"]', 'Parmesan', 'Les fruits de mer et le fromage ne se mélangent pas dans la cuisine italienne — règle absolue.', 1),
  ('Le Risotto Nero alle Seppie', 'fill_in_blank', 'Le risotto nero est coloré par l ___ de seiche', '[]', 'encre', 'L encre de seiche contient de la mélanine — elle colore le risotto en noir profond.', 2),
  ('Le Fritto Misto Veneziano', 'multiple_choice', 'Quel liquide rend la pâte à tempura vénitienne légère ?', '["Eau gazeuse très froide","Bière glacée","Eau plate","Lait froid"]', 'Eau gazeuse très froide', 'Les bulles de l eau gazeuse + le froid créent une pâte aérée qui croustille sans peser.', 1),
  ('Le Fritto Misto Veneziano', 'fill_in_blank', 'Les tavernes vénitiennes où l on mange le fritto misto s appellent des ___', '[]', 'osterie', 'L osteria (taverne) est le restaurant populaire vénitien — détendu, avec une carte simple.', 2),
  ('La Ribollita Toscane (avancée)', 'multiple_choice', 'Que signifie ribollita en italien ?', '["Rebouillie","Chou bouilli","Soupe de haricots","Rechauffée"]', 'Rebouillie', 'La ribollita est bouillie une première fois, puis rebouillie le lendemain avec du pain — meilleure le 2e jour.', 1),
  ('La Ribollita Toscane (avancée)', 'fill_in_blank', 'Le chou noir toscan emblématique de la ribollita s appelle ___', '[]', 'cavolo nero', 'Le cavolo nero (chou noir) est un ingrédient iconique de la cuisine toscane hivernale.', 2)
) AS v(lesson_title, type, question, options, correct_answer, explanation, order_index)
JOIN public.lessons l ON l.title = v.lesson_title;

-- ============================================================
-- EXERCISES FOR JAPANESE LESSONS 36-50
-- ============================================================
INSERT INTO public.exercises (id, lesson_id, type, question, options, correct_answer, explanation, order_index)
SELECT gen_random_uuid(), l.id, v.type, v.question, v.options::jsonb, v.correct_answer, v.explanation, v.order_index
FROM (VALUES
  ('Le Ramen Tonkotsu', 'multiple_choice', 'De quelle ville est originaire le ramen tonkotsu ?', '["Fukuoka (Hakata)","Tokyo","Osaka","Sapporo"]', 'Fukuoka (Hakata)', 'Le tonkotsu ramen est né à Fukuoka (Hakata) dans les années 1940 — le ramen le plus célèbre du Kyushu.', 1),
  ('Le Ramen Tonkotsu', 'fill_in_blank', 'Le porc poché et laqué qui garnit le ramen s appelle le ___', '[]', 'chashu', 'Le chashu est du porc roulé, ficelé, poché dans du soja et mirin — tranché pour garnir le ramen.', 2),
  ('Le Sukiyaki', 'multiple_choice', 'Quelle est la particularité du service du sukiyaki ?', '["On trempe les aliments dans un œuf cru battu","On mange directement dans la poêle","Le bouillon est servi séparément","Les légumes sont mangés crus"]', 'On trempe les aliments dans un œuf cru battu', 'L œuf cru battu enrobe chaque bouchée d une couche soyeuse — c est la signature du sukiyaki.', 1),
  ('Le Sukiyaki', 'fill_in_blank', 'Le bouillon sucré-salé du sukiyaki s appelle ___', '[]', 'warishita', 'Le warishita est composé de soja, mirin et sucre — il caramélise légèrement à la cuisson.', 2),
  ('La Tempura de Crevettes', 'multiple_choice', 'Qui a introduit la tempura au Japon ?', '["Les jésuites portugais au XVIe siècle","Les marchands chinois","Les Hollandais","Les Coréens"]', 'Les jésuites portugais au XVIe siècle', 'Les missionnaires portugais ont apporté la technique de friture en pâte (Quatro Tempora) au Japon.', 1),
  ('La Tempura de Crevettes', 'fill_in_blank', 'La pâte à tempura doit être ___ pour être croustillante', '[]', 'grumeleuse', 'Les grumeaux de farine non dissoute sont intentionnels — ils croustillent à la friture.', 2),
  ('Le Chirashi Sushi', 'multiple_choice', 'Que signifie chirashi en japonais ?', '["Éparpillé","Mélangé","Disposé","Coloré"]', 'Éparpillé', 'Les garnitures sont éparpillées librement sur le riz — à l opposé des makis où tout est structuré.', 1),
  ('Le Chirashi Sushi', 'fill_in_blank', 'Le riz sushi assaisonné au vinaigre s appelle ___', '[]', 'sumeshi', 'Le sumeshi est assaisonné de vinaigre de riz, sucre et sel — préparé chaud mais mangé tiède.', 2),
  ('La Soupe au Tofu Agedashi', 'multiple_choice', 'Pourquoi poudrer le tofu de katakuriko avant de frire ?', '["Pour une croûte dorée et croustillante","Pour le goût","Pour la couleur","Pour qu il tienne ensemble"]', 'Pour une croûte dorée et croustillante', 'La fécule crée une fine croûte croustillante qui contraste avec le tofu soyeux intérieur.', 1),
  ('La Soupe au Tofu Agedashi', 'fill_in_blank', 'La fécule de pomme de terre japonaise qui enrobe le tofu s appelle ___', '[]', 'katakuriko', 'Le katakuriko (fécule de pomme de terre japonaise) donne une texture plus légère que la farine.', 2),
  ('Le Soba Sarashina', 'multiple_choice', 'Le soba sarashina est fabriqué avec quelle partie du sarrasin ?', '["Le cœur — la partie la plus pure","La coque complète","La plante entière","Les feuilles du sarrasin"]', 'Le cœur — la partie la plus pure', 'Le sarashina utilise le cœur (partie centrale) du grain de sarrasin — la farine la plus blanche et fine.', 1),
  ('Le Soba Sarashina', 'fill_in_blank', 'Le bouillon concentré pour tremper le soba froid s appelle ___', '[]', 'tsuyu', 'Le tsuyu est un concentré de dashi, soja et mirin — dilué pour le soba froid, utilisé pur pour le chaud.', 2),
  ('Le Shabu-Shabu Ponzu', 'multiple_choice', 'Combien de secondes trempe-t-on le bœuf dans le bouillon du shabu-shabu ?', '["2-3 secondes","30 secondes","2 minutes","Jusqu à bien cuit"]', '2-3 secondes', 'Le bœuf wagyu est si bien marbré qu il cuit en 2-3 secondes dans le bouillon frémissant.', 1),
  ('Le Shabu-Shabu Ponzu', 'fill_in_blank', 'Le bœuf japonais marbré idéal pour le shabu-shabu s appelle ___', '[]', 'wagyu', 'Le wagyu (bœuf japonais) a une texture fondante unique grâce à son persillage exceptionnel.', 2),
  ('Les Mochi Daifuku', 'multiple_choice', 'Que signifie daifuku en japonais ?', '["Grand bonheur","Grande boule","Riz heureux","Douceur de fête"]', 'Grand bonheur', 'Le daifuku (大福) est un mochi porte-bonheur — offert pour les fêtes et les occasions spéciales.', 1),
  ('Les Mochi Daifuku', 'fill_in_blank', 'La pâte sucrée de haricots adzuki utilisée dans les mochi s appelle ___', '[]', 'anko', 'L anko peut être tsubuan (grains entiers) ou koshian (purée lisse) — les deux existent dans le daifuku.', 2),
  ('Le Curry Japonais Maison', 'multiple_choice', 'Via quel pays le curry est-il arrivé au Japon ?', '["L Angleterre (influence indienne)","La Chine","La Thaïlande","L Inde directement"]', 'L Angleterre (influence indienne)', 'Le curry a été apporté au Japon par la marine britannique au XIXe siècle — déjà adapté.', 1),
  ('Le Curry Japonais Maison', 'fill_in_blank', 'Les blocs de curry japonais prêts à l emploi s appellent ___', '[]', 'roux de curry', 'Le roux de curry (comme S&B ou House Foods) est le format le plus utilisé dans les foyers japonais.', 2),
  ('Les Onigiri au Saumon Grillé', 'multiple_choice', 'Pourquoi saler les mains avant de former les onigiri ?', '["Pour parfumer et conserver le riz","Pour éviter que ça colle","Pour la texture","C est une tradition sans raison pratique"]', 'Pour parfumer et conserver le riz', 'Le sel sur les mains assaisonne légèrement l extérieur de l onigiri et aide à la conservation.', 1),
  ('Les Onigiri au Saumon Grillé', 'fill_in_blank', 'Les onigiri sont disponibles dans tous les ___ japonais 24h/24', '[]', 'konbini', 'Les konbini (convenience stores comme Lawson, 7-Eleven) vendent des onigiri en permanence.', 2),
  ('Le Yaki Udon', 'multiple_choice', 'Que signifie yaki en japonais ?', '["Grillé/sauté","Bouilli","Cuit à la vapeur","Friture"]', 'Grillé/sauté', 'Yaki signifie cuit sur le feu — grill ou poêle. Yaki-niku (viande grillée), yakitori (poulet grillé).', 1),
  ('Le Yaki Udon', 'fill_in_blank', 'Les larges nouilles blanches de blé s appellent ___', '[]', 'udon', 'Les udon sont les plus larges des nouilles japonaises — épaisses, blanches et moelleuses.', 2),
  ('Le Katsudon', 'multiple_choice', 'Pourquoi le katsudon est-il le favori des étudiants japonais avant les examens ?', '["Katsu signifie victoire — pour la chance","C est peu cher","C est nourrissant","C est rapide à manger"]', 'Katsu signifie victoire — pour la chance', 'Katsu (勝つ) signifie gagner ou vaincre en japonais — manger du katsudon avant un examen porte chance.', 1),
  ('Le Katsudon', 'fill_in_blank', 'Les bols de riz garnis japonais s appellent des ___', '[]', 'donburi', 'Donburi (丼) est le bol et le type de plat — katsudon, gyudon, oyakodon sont tous des donburi.', 2),
  ('Le Tamago Kake Gohan', 'multiple_choice', 'Quelle est la règle de sécurité pour le TKG ?', '["Utiliser des œufs ultra-frais de moins de 5 jours","Cuire légèrement l œuf","Utiliser des œufs pasteurisés uniquement","Éviter les œufs de ferme"]', 'Utiliser des œufs ultra-frais de moins de 5 jours', 'L œuf étant consommé cru, la fraîcheur est essentielle — au Japon les œufs sont garantis.', 1),
  ('Le Tamago Kake Gohan', 'fill_in_blank', 'TKG est l abréviation de tamago ___ gohan', '[]', 'kake', 'Kake (掛け) signifie versé sur — l œuf est versé sur le riz chaud.', 2),
  ('Le Chirashi de Saint-Valentin', 'multiple_choice', 'Quand doit-on poser l uni (oursin) sur le chirashi ?', '["Au dernier moment — il s oxyde rapidement","1h avant pour qu il prenne la température","La veille pour mariner","En même temps que les autres garnitures"]', 'Au dernier moment — il s oxyde rapidement', 'L uni perd sa texture et son goût en quelques minutes à l air — posez-le à la dernière seconde.', 1),
  ('Le Chirashi de Saint-Valentin', 'fill_in_blank', 'Les œufs de saumon marinés en soja et mirin s appellent ___', '[]', 'ikura', 'L ikura (イクラ) vient du mot russe ikra (caviar) — les œufs de saumon marinés japonais.', 2),
  ('La Soupe Tonjiru Avancée', 'multiple_choice', 'Quel miso utilise-t-on pour une soupe tonjiru plus profonde ?', '["Miso de riz rouge (hatcho)","Miso blanc","Miso mix","Miso de soja"]', 'Miso de riz rouge (hatcho)', 'Le hatcho miso est fermenté 3 ans — il a une profondeur et une intensité incomparables.', 1),
  ('La Soupe Tonjiru Avancée', 'fill_in_blank', 'La racine aromatique japonaise utilisée dans le tonjiru s appelle ___', '[]', 'gobo', 'Le gobo (bardane japonaise) a une saveur terreuse et légèrement amère — essentiel au tonjiru.', 2)
) AS v(lesson_title, type, question, options, correct_answer, explanation, order_index)
JOIN public.lessons l ON l.title = v.lesson_title;

-- ============================================================
-- EXERCISES FOR MOROCCAN LESSONS 36-50
-- ============================================================
INSERT INTO public.exercises (id, lesson_id, type, question, options, correct_answer, explanation, order_index)
SELECT gen_random_uuid(), l.id, v.type, v.question, v.options::jsonb, v.correct_answer, v.explanation, v.order_index
FROM (VALUES
  ('Le Tajine de Poulet au Citron Confit', 'multiple_choice', 'Quelle partie du citron confit utilise-t-on dans le tajine ?', '["La peau uniquement","La pulpe uniquement","Les deux — pulpe et peau","Le jus extrait"]', 'La peau uniquement', 'La pulpe du citron confit est trop salée et amère — seule la peau parfumée est utilisée.', 1),
  ('Le Tajine de Poulet au Citron Confit', 'fill_in_blank', 'Le citron confit est fermenté dans le ___ pendant un mois', '[]', 'sel', 'La lacto-fermentation au sel transforme le citron et développe des saveurs umami complexes.', 2),
  ('La Harira Enrichie', 'multiple_choice', 'Lors de quel événement religieux la harira est-elle traditionnellement consommée ?', '["L iftar du Ramadan","L Aïd al-Adha","Le Mouloud","Le Nouvel An hégire"]', 'L iftar du Ramadan', 'La harira est LA soupe de rupture du jeûne — servie au coucher du soleil pendant tout le Ramadan.', 1),
  ('La Harira Enrichie', 'fill_in_blank', 'Le mélange farine-eau qui épaissit la harira s appelle le ___', '[]', 'tedouira', 'Le tedouira est ajouté en fin de cuisson et donne à la harira sa consistance caractéristique.', 2),
  ('La Trid au Poulet', 'multiple_choice', 'Lors de quel événement sert-on traditionnellement le trid ?', '["Les noces marocaines","Les funérailles","Le Ramadan","L anniversaire"]', 'Les noces marocaines', 'Le trid est le plat des mariages marocains — considéré comme un plat de prestige.', 1),
  ('La Trid au Poulet', 'fill_in_blank', 'Les crêpes feuilletées marocaines à la semoule s appellent ___', '[]', 'msemen', 'Le msemen est une crêpe feuilletée carrée — utilisée pour le trid et servie aussi au petit-déjeuner.', 2),
  ('Les Kemia Marocaines', 'multiple_choice', 'À quelle température servent-on les kemia ?', '["À température ambiante","Froides du réfrigérateur","Très chaudes","Tièdes seulement"]', 'À température ambiante', 'Les arômes des épices et de l huile d olive s expriment mieux à température ambiante.', 1),
  ('Les Kemia Marocaines', 'fill_in_blank', 'La marinade marocaine polyvalente aux herbes, épices et citron s appelle ___', '[]', 'chermoula', 'La chermoula est utilisée pour mariner le poisson, les légumes et comme sauce d accompagnement.', 2),
  ('Le Méchoui d Agneau', 'multiple_choice', 'À quels événements sert-on le méchoui ?', '["L Aïd et les mariages","Le Ramadan uniquement","Les anniversaires","Les fêtes nationales"]', 'L Aïd et les mariages', 'Le méchoui est le plat des grandes fêtes — son envergure (un agneau entier) demande une grande tablée.', 1),
  ('Le Méchoui d Agneau', 'fill_in_blank', 'L agneau doit être badigeonné toutes les ___ minutes pour rester juteux', '[]', '30', 'Le badigeonnage régulier (épices, beurre, huile) empêche le dessèchement et dore la peau.', 2),
  ('La Mrouzia Festive', 'multiple_choice', 'Lors de quelle fête prépare-t-on la mrouzia ?', '["L Aïd al-Adha","Le Ramadan","Le Mouloud","L Aïd el-Fitr"]', 'L Aïd al-Adha', 'La mrouzia est préparée avec la viande du mouton sacrifié lors de l Aïd al-Adha (fête du sacrifice).', 1),
  ('La Mrouzia Festive', 'fill_in_blank', 'Le ras el hanout contient entre ___ et 30 épices différentes', '[]', '20', 'Le ras el hanout (tête de l épicerie) est le mélange d épices le plus complexe du Maroc.', 2),
  ('Les Crêpes Baghrir Avancées', 'multiple_choice', 'Pourquoi la pâte à baghrir doit-elle reposer 30 minutes ?', '["Pour que les trous se forment à la cuisson","Pour lever","Pour épaissir","C est une tradition sans effet"]', 'Pour que les trous se forment à la cuisson', 'La fermentation courte crée des bulles de CO2 — elles percent la crêpe et créent les mille trous.', 1),
  ('Les Crêpes Baghrir Avancées', 'fill_in_blank', 'Le baghrir s appelle la crêpe à ___ trous', '[]', 'mille', 'Mille trous (baghrir) — la surface criblée de petits trous est la caractéristique distinctive.', 2),
  ('La Pastilla au Pigeon', 'multiple_choice', 'Quelle est la garniture originale de la pastilla ?', '["Pigeon","Poulet","Agneau","Crevettes"]', 'Pigeon', 'La pastilla originale est au pigeon — le poulet est une adaptation plus récente et plus accessible.', 1),
  ('La Pastilla au Pigeon', 'fill_in_blank', 'La feuille de pastilla marocaine ultra-fine s appelle la ___', '[]', 'warka', 'La warka est plus fine que le phyllo grec — elle est préparée en tamponnant la pâte sur une surface chaude.', 2),
  ('Le Couscous au Beurre Frais', 'multiple_choice', 'Combien de fois cuit-on le couscous à la vapeur pour la perfection ?', '["Trois fois","Une fois","Deux fois","Quatre fois"]', 'Trois fois', 'Trois passages vapeur avec roulage entre chaque garantissent des grains parfaitement séparés.', 1),
  ('Le Couscous au Beurre Frais', 'fill_in_blank', 'La marmite à deux niveaux pour cuire le couscous s appelle un ___', '[]', 'couscoussier', 'Le couscoussier a une marmite en bas pour le bouillon et un panier perforé en haut pour le couscous.', 2),
  ('La Soupe de Fèves Bessara', 'multiple_choice', 'Quel condiment est indispensable sur la bessara servie ?', '["Filet d huile d olive crue","Crème fraîche","Beurre fondu","Sauce harissa"]', 'Filet d huile d olive crue', 'L huile d olive crue versée sur la bessara chaude est fondamentale — jamais l omettre.', 1),
  ('La Soupe de Fèves Bessara', 'fill_in_blank', 'La bessara est le petit-déjeuner des ___ marocains', '[]', 'travailleurs', 'La bessara est nourrissante et bon marché — le petit-déjeuner populaire des classes laborieuses.', 2),
  ('Le Tajine de Sardines Farcies', 'multiple_choice', 'De quelle ville côtière ce tajine est-il populaire ?', '["Safi et Essaouira","Casablanca","Tanger","Agadir"]', 'Safi et Essaouira', 'Safi est la capitale de la sardine au Maroc — Essaouira est réputée pour ses poissons grillés.', 1),
  ('Le Tajine de Sardines Farcies', 'fill_in_blank', 'Les sardines sont farcies avec de la ___', '[]', 'chermoula', 'La chermoula (marinade marocaine) est la farce et sauce des sardines farcies.', 2),
  ('Les Sellou (Sfouf)', 'multiple_choice', 'Pour qui prépare-t-on le sellou traditionnellement ?', '["Les femmes enceintes ou accouchées et pour le Ramadan","Les hommes seulement","Les enfants","Les anciens"]', 'Les femmes enceintes ou accouchées et pour le Ramadan', 'Le sellou est très énergétique — il nourrit et réconforte les femmes après l accouchement.', 1),
  ('Les Sellou (Sfouf)', 'fill_in_blank', 'L épice caractéristique du sellou est l ___', '[]', 'anis', 'L anis vert donne son arôme distinctif au sellou — reconnaissable entre tous.', 2),
  ('Les Choumicha Kaab el Ghazal', 'multiple_choice', 'Que signifie kaab el ghazal en arabe ?', '["Cheville de gazelle","Patte de gazelle","Corne de gazelle","Œil de gazelle"]', 'Cheville de gazelle', 'La forme incurvée de la pâtisserie rappelle la cheville délicate d une gazelle.', 1),
  ('Les Choumicha Kaab el Ghazal', 'fill_in_blank', 'L eau de ___ d oranger parfume la pâtisserie marocaine de façon caractéristique', '[]', 'fleur', 'L eau de fleur d oranger (nasrate) est l arôme de base de toute la pâtisserie marocaine.', 2),
  ('Le Thé à la Menthe Cérémonie', 'multiple_choice', 'Comment verse-t-on le thé marocain et pourquoi ?', '["De haut pour créer la mousse — signe d hospitalité","Au ras du verre pour ne pas renverser","Dans la théière d abord","À l envers dans le verre"]', 'De haut pour créer la mousse — signe d hospitalité', 'La hauteur du versement crée la mousse qui oxygène le thé et signifie que le maître de maison est généreux.', 1),
  ('Le Thé à la Menthe Cérémonie', 'fill_in_blank', 'Le thé vert en billes utilisé pour le thé marocain s appelle ___', '[]', 'Gunpowder', 'Le thé Gunpowder (poudre à canon) est ainsi nommé car ses billes ressemblent à de la poudre noire.', 2),
  ('La Diffa Marocaine Complète', 'multiple_choice', 'Lors de quels événements sert-on la diffa ?', '["Mariages et Aid","Ramadan uniquement","Tous les jours du vendredi","Visites de dignitaires"]', 'Mariages et Aid', 'La diffa est le festin des grandes occasions — mariages, Aid et réceptions officielles.', 1),
  ('La Diffa Marocaine Complète', 'fill_in_blank', 'Diffa signifie ___ marocain en arabe', '[]', 'festin', 'La diffa (ضيافة) vient du mot arabe pour hospitalité — un festin est l expression suprême de l accueil.', 2)
) AS v(lesson_title, type, question, options, correct_answer, explanation, order_index)
JOIN public.lessons l ON l.title = v.lesson_title;
