-- Lessons 21-35 for Mexican, Indian, Thai, Greek paths

-- ============================================================
-- MEXICAN LESSONS 21-35
-- ============================================================
INSERT INTO public.lessons (id, path_id, title, description, order_index, duration_min, difficulty, chef_tip, cultural_note, vocabulary)
SELECT gen_random_uuid(), p.id, v.title, v.description, v.order_index, v.duration_min, v.difficulty, v.chef_tip, v.cultural_note, v.vocabulary::jsonb
FROM (VALUES
  ('Les Tamales de Maïs', 'Masa de maïs farcie, enveloppée dans des feuilles de maïs et cuite à la vapeur.', 21, 50, 'intermediate', 'La masa doit être assez humide pour coller à vos mains.', 'Les tamales sont préparés en famille lors des fêtes.', '[{"term":"masa","definition":"pâte de maïs nixtamalisé"},{"term":"hoja","definition":"feuille de maïs séchée"}]'),
  ('Le Pozole Rojo', 'Soupe de maïs hominy dans un bouillon rouge épicé avec porc effiloché.', 22, 55, 'intermediate', 'Faites griller les piments secs à sec avant de les réhydrater.', 'Le pozole était un plat rituel aztèque.', '[{"term":"hominy","definition":"maïs traité à la chaux"},{"term":"pozole","definition":"soupe traditionnelle de maïs"}]'),
  ('Les Chiles Rellenos', 'Piments poblano farcis au fromage, enrobés de pâte à beignet et frits.', 23, 45, 'intermediate', 'Brûlez la peau des piments directement sur la flamme pour les peler facilement.', 'Les chiles rellenos sont un classique de la cuisine poblana.', '[{"term":"poblano","definition":"piment doux et fumé du Mexique"},{"term":"capear","definition":"enrober de pâte à l''œuf"}]'),
  ('La Sopa de Lima', 'Soupe de poulet au citron vert de Yucatán, avec tortillas croustillantes.', 24, 40, 'beginner', 'Ajoutez le jus de lime en fin de cuisson pour préserver sa fraîcheur.', 'Ce plat est emblématique de la cuisine maya du Yucatán.', '[{"term":"lima","definition":"citron aigre du Yucatán"},{"term":"recado","definition":"pâte d''épices yucatèque"}]'),
  ('Le Mole Poblano', 'Sauce complexe aux piments, cacao, épices sur poulet — le roi des moles.', 25, 90, 'advanced', 'Le mole se bonifie avec le temps — préparez-le la veille.', 'Le mole poblano est patrimoine culinaire immatériel du Mexique.', '[{"term":"mole","definition":"sauce complexe aux épices"},{"term":"mulato","definition":"piment séché brun-noir"}]'),
  ('Les Tlayudas Oaxaqueñas', 'Grande tortilla croustillante garnie de haricots, fromage Oaxaca et tasajo.', 26, 35, 'beginner', 'La tortilla doit être croustillante en dessous mais moelleuse au centre.', 'La tlayuda est le plat de rue emblématique d''Oaxaca.', '[{"term":"tasajo","definition":"viande de bœuf séchée oaxaqueña"},{"term":"quesillo","definition":"fromage d''Oaxaca filant"}]'),
  ('Le Birria de Res', 'Bœuf braisé dans une sauce de piments séchés, servi avec consommé.', 27, 120, 'advanced', 'Plongez les tacos dans le consommé chaud avant de les manger.', 'La birria est originaire de Jalisco et dédiée aux célébrations.', '[{"term":"birria","definition":"ragoût de viande épicée"},{"term":"consommé","definition":"bouillon de birria servi séparément"}]'),
  ('Les Enfrijoladas', 'Tortillas plongées dans une sauce aux haricots noirs, garnies de fromage.', 28, 30, 'beginner', 'Réchauffez les tortillas dans la sauce pour qu''elles s''imprègnent bien.', 'Les enfrijoladas sont un plat de récupération mexicain du quotidien.', '[{"term":"frijoles","definition":"haricots noirs mexicains"},{"term":"epazote","definition":"herbe aromatique mexicaine"}]'),
  ('La Cochinita Pibil', 'Porc mariné à l''achiote, cuit lentement dans des feuilles de bananier.', 29, 180, 'advanced', 'Les oignons marinés à la lime sont indispensables pour équilibrer le gras.', 'La cochinita pibil est le plat festif du Yucatán.', '[{"term":"achiote","definition":"graine rouge donnant couleur et saveur"},{"term":"pibil","definition":"cuisson en fosse maya"}]'),
  ('Les Quesadillas au Huitlacoche', 'Tortillas fourrées au champignon de maïs, un délice terreux et umami.', 30, 25, 'beginner', 'Le huitlacoche se marie bien avec la fleur de courgette et le fromage frais.', 'Le huitlacoche est appelé "truffe mexicaine".', '[{"term":"huitlacoche","definition":"champignon parasite du maïs, délicat"},{"term":"quesillo","definition":"fromage blanc frais mexicain"}]'),
  ('Le Caldo de Pollo Mexicain', 'Bouillon de poulet généreux aux légumes, herbes et jalapeño.', 31, 45, 'beginner', 'Ajoutez l''épazote frais en fin de cuisson pour le parfum authentique.', 'Le caldo de pollo mexicain est le remède universel des familles.', '[{"term":"epazote","definition":"herbe aromatique mexicaine"},{"term":"calabacita","definition":"courgette mexicaine"}]'),
  ('Les Tortas Ahogadas', 'Sandwich trempé dans une sauce piquante de tomates et piments — spécialité de Guadalajara.', 32, 35, 'intermediate', 'La torta doit être complètement immergée dans la sauce avant de servir.', 'Nées à Guadalajara, les tortas ahogadas sont un incontournable du Mexique.', '[{"term":"birote","definition":"pain dur et croustillant de Jalisco"},{"term":"ahogada","definition":"noyée — trempée dans la sauce"}]'),
  ('Le Sopa Azteca', 'Soupe de tortillas croustillantes dans un bouillon de tomates et chipotle.', 33, 30, 'beginner', 'Ajoutez les tortillas juste avant de servir pour qu''elles restent légèrement croustillantes.', 'Cette soupe reconstituante est aussi appelée "sopa de tortilla".', '[{"term":"chipotle","definition":"jalapeño fumé et séché"},{"term":"pasilla","definition":"piment séché doux et terreux"}]'),
  ('Les Gorditas de Chicharrón', 'Galettes épaisses de masa farcies de couenne de porc croustillante et salsa.', 34, 40, 'intermediate', 'Faites une poche dans la gordita avec un couteau pendant qu''elle est encore chaude.', 'Les gorditas sont vendues sur les marchés mexicains dès l''aube.', '[{"term":"chicharrón","definition":"couenne de porc soufflée et croustillante"},{"term":"gordita","definition":"galette épaisse de masa"}]'),
  ('Le Champurrado', 'Chocolat chaud épais à base de masa, cannelle et piloncillo.', 35, 20, 'beginner', 'Fouettez sans cesse pour éviter que la masa accroche au fond.', 'Le champurrado est le réconfort hivernal des Mexicains, servi avec des tamales.', '[{"term":"piloncillo","definition":"sucre de canne brut non raffiné"},{"term":"masa","definition":"pâte de maïs nixtamalisé"}]')
) AS v(title, description, order_index, duration_min, difficulty, chef_tip, cultural_note, vocabulary)
CROSS JOIN (SELECT id FROM public.paths WHERE slug='mexican' LIMIT 1) p;

-- ============================================================
-- INDIAN LESSONS 21-35
-- ============================================================
INSERT INTO public.lessons (id, path_id, title, description, order_index, duration_min, difficulty, chef_tip, cultural_note, vocabulary)
SELECT gen_random_uuid(), p.id, v.title, v.description, v.order_index, v.duration_min, v.difficulty, v.chef_tip, v.cultural_note, v.vocabulary::jsonb
FROM (VALUES
  ('Le Dal Makhani', 'Lentilles noires mijotées toute la nuit au beurre et à la crème — le roi des dals.', 21, 480, 'intermediate', 'La cuisson lente sur feu très doux est le secret du dal makhani authentique.', 'Ce plat est originaire du Punjab et popularisé par le restaurant Moti Mahal de Delhi.', '[{"term":"urad dal","definition":"lentilles noires entières"},{"term":"makhani","definition":"beurre en hindi"}]'),
  ('Le Palak Paneer', 'Fromage indien dans une sauce d''épinards veloutée aux épices.', 22, 40, 'beginner', 'Plongez les épinards blanchis dans de l''eau glacée pour conserver leur couleur verte.', 'Le palak paneer est un plat végétarien emblématique du nord de l''Inde.', '[{"term":"palak","definition":"épinards en hindi"},{"term":"paneer","definition":"fromage frais indien non fermenté"}]'),
  ('Le Chana Masala', 'Pois chiches dans une sauce épicée aux tomates, oignon et épices complexes.', 23, 45, 'beginner', 'Ajoutez un peu de jus de tamarin en fin de cuisson pour l''acidité caractéristique.', 'Le chana masala est le plat du petit-déjeuner favori du Punjab.', '[{"term":"chana","definition":"pois chiches en hindi"},{"term":"amchur","definition":"poudre de mangue verte séchée"}]'),
  ('Le Biryani d''Agneau Hyderabadi', 'Riz basmati et agneau épicé cuits ensemble sous dum — plat de fête.', 24, 120, 'advanced', 'Sceller la marmite avec de la pâte de farine pour une cuisson dum parfaite.', 'Le biryani hyderabadi est le joyau de la cuisine Nizami.', '[{"term":"dum","definition":"cuisson à l''étouffée sous pression"},{"term":"kewra","definition":"eau florale de pandanus"}]'),
  ('Le Rogan Josh', 'Agneau braisé dans une sauce kashmiris aux épices cachemiriennes et yogourt.', 25, 90, 'intermediate', 'Le ratan jot (colorant naturel rouge) donne la couleur rouge caractéristique.', 'Le rogan josh est la fierté culinaire du Cachemire.', '[{"term":"rogan josh","definition":"gras rouge — allusion à la couleur du plat"},{"term":"maval","definition":"épice cachemirienne florale"}]'),
  ('Les Pakoras d''Oignon', 'Beignets croustillants d''oignons frits dans une pâte de pois chiches épicée.', 26, 25, 'beginner', 'La pâte doit être épaisse pour que les pakoras soient croustillants.', 'Les pakoras sont le snack de la mousson en Inde.', '[{"term":"besan","definition":"farine de pois chiches"},{"term":"pakora","definition":"beignet frit indien"}]'),
  ('Le Pav Bhaji', 'Purée de légumes épicée servie avec des petits pains beurrés — street food de Mumbai.', 27, 40, 'beginner', 'Écrasez bien les légumes dans la poêle avec le pav bhaji masala pour l''authenticité.', 'Le pav bhaji est né dans les usines textiles de Mumbai pour nourrir les ouvriers.', '[{"term":"pav","definition":"petit pain moelleux indien"},{"term":"bhaji","definition":"légumes cuits épicés"}]'),
  ('Le Kadhi Pakora', 'Soupe de yogourt et farine de pois chiches avec des beignets — plat du Punjab.', 28, 50, 'intermediate', 'Le kadhi doit mijoter longtemps pour que la farine de pois chiches perde son goût cru.', 'Le kadhi est un plat de confort indien servi avec du riz.', '[{"term":"kadhi","definition":"soupe de yogourt épicée"},{"term":"tempering","definition":"technique d''huile épicée versée sur le plat"}]'),
  ('Le Aloo Gobi', 'Chou-fleur et pommes de terre sautés aux épices dans un style sec et doré.', 29, 35, 'beginner', 'Cuisez à feu moyen-fort pour caraméliser les légumes sans les braiser.', 'L''aloo gobi est un classique quotidien de l''Inde du Nord.', '[{"term":"aloo","definition":"pomme de terre en hindi"},{"term":"gobi","definition":"chou-fleur en hindi"}]'),
  ('Le Saag Aloo', 'Pommes de terre épicées dans une sauce de feuilles vertes (moutarde, épinards).', 30, 40, 'beginner', 'Mélangez les feuilles de moutarde et d''épinards pour un équilibre parfait.', 'Le saag est particulièrement populaire en hiver dans le Punjab.', '[{"term":"saag","definition":"feuilles vertes cuites"},{"term":"makki di roti","definition":"pain de maïs servi avec le saag"}]'),
  ('Le Lassi à la Mangue', 'Boisson de yogourt et mangue, fraîche et légèrement épicée.', 31, 10, 'beginner', 'Utilisez de la mangue Alphonso pour le goût le plus authentique.', 'Le lassi est la boisson traditionnelle du Punjab, servi en grand verre de terre cuite.', '[{"term":"lassi","definition":"boisson au yogourt battu"},{"term":"Alphonso","definition":"variété de mangue indienne la plus prisée"}]'),
  ('Le Dosa Masala', 'Crêpe de riz et lentilles fermentée, garnie de pommes de terre épicées.', 32, 60, 'intermediate', 'La pâte doit fermenter 8-12h dans un endroit chaud pour développer l''acidité.', 'Le dosa est le plat du petit-déjeuner incontournable du sud de l''Inde.', '[{"term":"dosa","definition":"crêpe fermentée de riz et urad dal"},{"term":"sambar","definition":"soupe de lentilles aux légumes du Sud"}]'),
  ('Le Chole Bhature', 'Pois chiches épicés avec des beignets de pâte levée — brunch légendaire de Delhi.', 33, 60, 'intermediate', 'La pâte bhature doit reposer au moins 1h pour être bien aérée.', 'Le chole bhature est le brunch favori des Delhiites le dimanche matin.', '[{"term":"bhature","definition":"pain frit gonflé à la farine de blé"},{"term":"chole","definition":"pois chiches marinés aux épices"}]'),
  ('Le Gulab Jamun', 'Boulettes de lait concentré frites, trempées dans un sirop à la rose et cardamome.', 34, 45, 'intermediate', 'Faites frire à feu doux pour que les boulettes cuisent à cœur sans brûler.', 'Les gulab jamun sont le dessert incontournable des fêtes hindoues.', '[{"term":"gulab","definition":"rose en persan"},{"term":"jamun","definition":"fruit noir — par analogie de forme"}]'),
  ('Le Halwa de Carottes', 'Carottes râpées cuites dans du lait, ghee et sucre, parfumées à la cardamome.', 35, 50, 'beginner', 'Cuisez les carottes à feu vif en remuant sans cesse pour évaporer le lait.', 'Le gajar ka halwa est le dessert hivernal des mariages indiens.', '[{"term":"gajar","definition":"carotte en hindi"},{"term":"khoya","definition":"lait concentré solide réduit"}]')
) AS v(title, description, order_index, duration_min, difficulty, chef_tip, cultural_note, vocabulary)
CROSS JOIN (SELECT id FROM public.paths WHERE slug='indian' LIMIT 1) p;

-- ============================================================
-- THAI LESSONS 21-35
-- ============================================================
INSERT INTO public.lessons (id, path_id, title, description, order_index, duration_min, difficulty, chef_tip, cultural_note, vocabulary)
SELECT gen_random_uuid(), p.id, v.title, v.description, v.order_index, v.duration_min, v.difficulty, v.chef_tip, v.cultural_note, v.vocabulary::jsonb
FROM (VALUES
  ('Le Khao Pad Sapparod', 'Riz sauté à l''ananas servi dans l''ananas évide — un classique thaï festif.', 21, 25, 'beginner', 'Utilisez du riz de la veille pour éviter qu''il colle.', 'Ce plat est souvent servi dans les fruits évidés pour l''effet visuel.', '[{"term":"khao pad","definition":"riz sauté en thaï"},{"term":"sapparod","definition":"ananas en thaï"}]'),
  ('Le Gaeng Massaman', 'Curry riche à la noix de coco, pommes de terre et cacahuètes — influence persane.', 22, 60, 'intermediate', 'Le massaman s''améliore le lendemain — préparez-le à l''avance.', 'Le massaman est un curry d''influence musulmane du sud de la Thaïlande.', '[{"term":"massaman","definition":"curry d''influence persano-malaise"},{"term":"peanuts","definition":"cacahuètes — essentiel au massaman"}]'),
  ('Le Hoy Tod', 'Omelette de moules croustillante sur lit de pousses de haricots — street food de Bangkok.', 23, 25, 'intermediate', 'La poêle doit être très chaude pour que les bords soient croustillants.', 'Le hoy tod est emblématique des marchés nocturnes de Bangkok.', '[{"term":"hoy","definition":"fruit de mer en thaï"},{"term":"tod","definition":"friture en thaï"}]'),
  ('Le Yam Woon Sen', 'Salade de vermicelles de verre épicée aux crevettes, citron vert et herbes.', 24, 25, 'beginner', 'Rincez les vermicelles à l''eau froide après la cuisson pour les rendre glissants.', 'Les salades yam thaïlandaises combinent piquant, acide, sucré et umami.', '[{"term":"woon sen","definition":"vermicelles de verre thaïs"},{"term":"yam","definition":"salade épicée en thaï"}]'),
  ('Le Khao Niao Mamuang', 'Riz gluant à la noix de coco et mangue fraîche — dessert thaï emblématique.', 25, 40, 'beginner', 'Faites tremper le riz gluant 4h minimum avant la cuisson à la vapeur.', 'Ce dessert est saisonnier — disponible quand les mangues sont mûres (avril-juin).', '[{"term":"khao niao","definition":"riz gluant en thaï"},{"term":"mamuang","definition":"mangue en thaï"}]'),
  ('Le Pad See Ew', 'Larges nouilles de riz sautées au bœuf, brocoli chinois et sauce soja sucrée.', 26, 20, 'beginner', 'Le wok doit être extrêmement chaud pour obtenir le wok hei (goût fumé).', 'Le pad see ew est la version sucrée-salée du pad thaï.', '[{"term":"sen yai","definition":"larges nouilles de riz"},{"term":"see ew","definition":"sauce soja sucrée foncée"}]'),
  ('Le Gaeng Keow Wan', 'Curry vert au lait de coco avec aubergines thaïes, basilic et poulet.', 27, 35, 'intermediate', 'Faites revenir la pâte de curry dans la crème de coco avant d''ajouter le lait.', 'Le curry vert est le plus piquant des curries thaïs classiques.', '[{"term":"keow wan","definition":"vert doux — la couleur des piments verts"},{"term":"makrut","definition":"citronnier kaffir, feuilles aromatiques"}]'),
  ('Le Khao Tom', 'Riz cuit en bouillie dans un bouillon clair avec gingembre et ciboulette.', 28, 30, 'beginner', 'Ajoutez les condiments (gingembre, ail frit) à table plutôt qu''à la cuisson.', 'Le khao tom est le plat du matin et du soir des familles thaïlandaises.', '[{"term":"khao tom","definition":"riz cuit à l''eau — bouillie de riz"},{"term":"khanom chin","definition":"nouilles de riz fermentées thaïes"}]'),
  ('Le Nam Prik Ong', 'Sauce de tomates et porc haché aux piments — trempette du nord thaï.', 29, 30, 'beginner', 'Servez avec des légumes crus et des couennes de porc frites.', 'Les nam prik sont les trempettes du nord de la Thaïlande (Chiang Mai).', '[{"term":"nam prik","definition":"trempette/sauce épicée thaïe"},{"term":"ong","definition":"tomate en dialecte du nord"}]'),
  ('Le Pla Rad Prik', 'Poisson frit entier nappé d''une sauce aigre-douce au piment — plat festif.', 30, 35, 'intermediate', 'Le poisson doit être très sec avant de frire pour éviter les éclaboussures.', 'Ce plat spectaculaire est souvent servi lors des repas de famille importants.', '[{"term":"pla","definition":"poisson en thaï"},{"term":"rad prik","definition":"napper de sauce au piment"}]'),
  ('Le Khanom Krok', 'Petits gâteaux de riz à la noix de coco, mi-croquants mi-crémeux.', 31, 30, 'beginner', 'La poêle à khanom krok doit être très chaude et bien huilée.', 'Ces gâteaux de rue sont cuits dans des moules en fonte spéciaux.', '[{"term":"khanom","definition":"dessert/pâtisserie en thaï"},{"term":"krok","definition":"mortier — forme des moules"}]'),
  ('Le Gaeng Pa', 'Curry de jungle sans lait de coco, piquant et herbacé — du nord montagneux.', 32, 45, 'advanced', 'Sans lait de coco, le curry pa est plus léger mais requiert des épices de qualité.', 'Le gaeng pa vient des régions montagneuses où la noix de coco n''existe pas.', '[{"term":"pa","definition":"forêt/jungle en thaï"},{"term":"grachai","definition":"gingembre sauvage thaï"}]'),
  ('Le Khua Kling', 'Porc haché sauté au curry sec — plat intensément épicé du sud.', 33, 25, 'advanced', 'Le khua kling est très piquant — ajustez les piments selon votre tolérance.', 'Ce plat est la fierté culinaire de la ville de Nakhon Si Thammarat.', '[{"term":"khua","definition":"sauter à sec en thaï"},{"term":"kling","definition":"rouler/enrober de la pâte d''épices"}]'),
  ('Le Kai Jiew Moo Sap', 'Omelette thaïe au porc haché, simple et dorée — plat du quotidien.', 34, 10, 'beginner', 'L''omelette thaïe est plus cuite que la française — laissez les bords dorer.', 'L''omelette est la solution de secours de toutes les familles thaïes.', '[{"term":"kai jiew","definition":"omelette en thaï"},{"term":"moo sap","definition":"porc haché en thaï"}]'),
  ('Le Tub Tim Krob', 'Dessert de châtaignes d''eau enrobées de sirop rouge dans du lait de coco glacé.', 35, 25, 'beginner', 'Colorez les châtaignes en rouge vif avec du colorant naturel de betterave.', 'Ces gemmes rouges flottant dans le lait de coco sont un symbole de fête.', '[{"term":"tub tim","definition":"rubis en thaï"},{"term":"krob","definition":"croustillant en thaï"}]')
) AS v(title, description, order_index, duration_min, difficulty, chef_tip, cultural_note, vocabulary)
CROSS JOIN (SELECT id FROM public.paths WHERE slug='thai' LIMIT 1) p;

-- ============================================================
-- GREEK LESSONS 21-35
-- ============================================================
INSERT INTO public.lessons (id, path_id, title, description, order_index, duration_min, difficulty, chef_tip, cultural_note, vocabulary)
SELECT gen_random_uuid(), p.id, v.title, v.description, v.order_index, v.duration_min, v.difficulty, v.chef_tip, v.cultural_note, v.vocabulary::jsonb
FROM (VALUES
  ('Le Pastitsio', 'Gratin de pâtes tubulaires à la viande et béchamel — le lasagne grec.', 21, 75, 'intermediate', 'Laissez reposer 15 min avant de servir pour que les couches se tiennent.', 'Le pastitsio est le plat des grandes occasions familiales grecques.', '[{"term":"pastitsio","definition":"gratin de pâtes à la viande grec"},{"term":"kima","definition":"viande hachée en grec"}]'),
  ('La Gemista', 'Tomates et poivrons farcis au riz, herbes et viande — plat d''été grec.', 22, 60, 'beginner', 'Versez un peu de jus de tomate dans le fond du plat pour que les légumes n''accrochent pas.', 'La gemista est le plat de l''été grec, préparée dans chaque famille.', '[{"term":"gemista","definition":"légumes farcis en grec"},{"term":"yemisi","definition":"remplir en grec"}]'),
  ('Le Kleftiko', 'Agneau cuit lentement dans du papier, fondant et parfumé — recette de bergers.', 23, 180, 'intermediate', 'Sceller hermétiquement le papier pour que les saveurs restent emprisonnées.', 'Le kleftiko était cuit dans des fosses par les klephtes (brigands) pour ne pas faire de fumée.', '[{"term":"kleftiko","definition":"volé — cuit en secret par les brigands"},{"term":"sti souvla","definition":"à la broche en grec"}]'),
  ('Le Fasolada', 'Soupe de haricots blancs aux légumes et huile d''olive — la soupe nationale grecque.', 24, 75, 'beginner', 'Ajoutez un filet généreux d''huile d''olive juste avant de servir.', 'Le fasolada est considéré comme la soupe nationale de la Grèce.', '[{"term":"fasolada","definition":"soupe de haricots en grec"},{"term":"haricots blancs","definition":"légumineuse centrale de la cuisine grecque"}]'),
  ('La Kakavia', 'Soupe de poissons méditerranéens dans un bouillon safran — bouillabaisse grecque.', 25, 50, 'intermediate', 'Ajoutez les poissons par ordre de cuisson — les plus fragiles en dernier.', 'La kakavia est la soupe des pêcheurs grecs depuis l''Antiquité.', '[{"term":"kakavia","definition":"marmite des pêcheurs grecs"},{"term":"safran","definition":"épice dorée caractéristique de la kakavia"}]'),
  ('Les Loukoumades', 'Beignets de pâte levée frits, nappés de miel et cannelle.', 26, 30, 'beginner', 'Servez immédiatement — les loukoumades perdent leur croustillant rapidement.', 'Les loukoumades étaient offerts aux vainqueurs des Jeux olympiques antiques.', '[{"term":"loukoumades","definition":"beignets grecs au miel"},{"term":"kanela","definition":"cannelle en grec"}]'),
  ('Le Tiropita', 'Tourte feuilletée au fromage feta et œufs — pâtisserie salée grecque.', 27, 45, 'intermediate', 'Badigeonnez chaque feuille de phyllo de beurre fondu pour le croustillant.', 'Le tiropita est la pâtisserie salée la plus populaire des boulangeries grecques.', '[{"term":"tiropita","definition":"tourte au fromage"},{"term":"phyllo","definition":"feuille de pâte ultrafine"}]'),
  ('Le Revithia Stifado', 'Pois chiches mijotés avec oignons, vin rouge et épices douces.', 28, 90, 'beginner', 'Plus c''est mijoté, meilleur c''est — préparez la veille.', 'Ce plat végétarien est souvent cuisiné les jours de jeûne orthodoxes.', '[{"term":"revithia","definition":"pois chiches en grec"},{"term":"stifado","definition":"ragoût avec petits oignons et épices"}]'),
  ('La Bourdeto', 'Poisson cuit dans un bouillon de tomates et piment rouge de Corfou.', 29, 40, 'intermediate', 'Le piment rouge de Corfou donne la couleur et le piquant caractéristiques.', 'La bourdeto est la spécialité de l''île de Corfou, influencée par la cuisine vénitienne.', '[{"term":"bourdeto","definition":"plat de poisson épicé de Corfou"},{"term":"scorpène","definition":"poisson méditerranéen typiquement utilisé"}]'),
  ('Le Soutzoukakia', 'Boulettes de viande épicées en sauce tomate à la cannelle — spécialité de Smyrne.', 30, 45, 'intermediate', 'Le cumin et la cannelle sont les épices essentielles des soutzoukakia.', 'Les soutzoukakia viennent de Smyrne (Izmir) et ont été apportés par les réfugiés grecs.', '[{"term":"soutzoukakia","definition":"boulettes de viande de Smyrne"},{"term":"Smyrne","definition":"ancienne ville grecque d''Anatolie"}]'),
  ('Les Vrasta Chortarakia', 'Légumes verts sauvages bouillis, nappés d''huile d''olive et citron.', 31, 20, 'beginner', 'Récupérez l''eau de cuisson — c''est une tisane nutritive.', 'La tradition de cueillette des herbes sauvages est centrale dans la vie grecque rurale.', '[{"term":"horta","definition":"légumes verts sauvages"},{"term":"vrasta","definition":"bouillis en grec"}]'),
  ('Le Keftedes Me Saltsa', 'Boulettes de viande frites servies dans une sauce tomate maison.', 32, 45, 'beginner', 'Ajoutez de la mie de pain trempée dans le lait pour des boulettes moelleuses.', 'Les keftedes sont le plat préféré des enfants grecs.', '[{"term":"keftedes","definition":"boulettes de viande grecques"},{"term":"saltsa","definition":"sauce en grec"}]'),
  ('Le Htipiti', 'Tartinnade de feta et poivrons rôtis épicée à la turque-grecque.', 33, 20, 'beginner', 'Mixez grossièrement pour garder une texture — pas trop lisse.', 'Le htipiti est une mezze classique des îles grecques et de Macédoine.', '[{"term":"htipiti","definition":"battu/fouetté en grec"},{"term":"mezze","definition":"petits plats partagés de l''est méditerranéen"}]'),
  ('Le Galatopita', 'Tarte au lait semoule cuite dans une pâte feuilletée, saupoudrée de cannelle.', 34, 50, 'beginner', 'Laissez refroidir complètement avant de découper pour que la crème soit ferme.', 'La galatopita est le dessert du dimanche dans les familles grecques.', '[{"term":"gala","definition":"lait en grec"},{"term":"pita","definition":"tarte/galette en grec"}]'),
  ('Le Magiritsa', 'Soupe pascale aux abats d''agneau, riz, aneth et avgolemono.', 35, 60, 'advanced', 'La soupe magiritsa est traditionnellement mangée après la messe de Pâques à minuit.', 'Rupture du jeûne du Carême — la première chose mangée après Pâques orthodoxes.', '[{"term":"magiritsa","definition":"soupe de Pâques grecque"},{"term":"avgolemono","definition":"sauce aux œufs et citron"}]')
) AS v(title, description, order_index, duration_min, difficulty, chef_tip, cultural_note, vocabulary)
CROSS JOIN (SELECT id FROM public.paths WHERE slug='greek' LIMIT 1) p;

-- ============================================================
-- RECIPES FOR MEXICAN LESSONS 21-35
-- ============================================================
INSERT INTO public.recipes (id, lesson_id, title, description, emoji, prep_time_min, cook_time_min, servings, difficulty, avg_price_eur, ingredients, instructions, chef_tip, cultural_note)
SELECT gen_random_uuid(), l.id, v.title, v.description, v.emoji, v.prep_time_min, v.cook_time_min, v.servings, v.difficulty, v.avg_price_eur, v.ingredients::jsonb, v.instructions::jsonb, v.chef_tip, v.cultural_note
FROM (VALUES
  ('Les Tamales de Maïs', 'Tamales vapeur à la masa de maïs fourrée au porc épicé.', '🌽', 60, 90, 8, 'intermediate', 8.0,
   '[{"qty":"500g","item":"masa harina"},{"qty":"300ml","item":"bouillon de poulet chaud"},{"qty":"100g","item":"lard fondu ou beurre"},{"qty":"200g","item":"porc effiloché cuit"},{"qty":"3 c.s.","item":"salsa rouge"},{"qty":"12","item":"feuilles de maïs séchées"}]',
   '["Trempez les feuilles de maïs 30 min dans de l eau tiède","Mélangez masa harina, bouillon et lard jusqu à obtenir une pâte souple","Étalez 2 c.s. de masa sur chaque feuille","Déposez une cuillère de porc et salsa au centre","Refermez la feuille et attachez avec une bandelette","Cuisez à la vapeur 1h30 — ils sont prêts quand la masa se détache facilement"]',
   'La masa doit être assez humide pour coller légèrement à vos mains mais ne pas coller aux doigts.', 'Les tamales sont préparés en famille lors des fêtes et de Noël (Navidad).'),
  ('Le Pozole Rojo', 'Soupe festive de maïs hominy au porc dans un bouillon rouge épicé.', '🍲', 30, 120, 6, 'intermediate', 9.0,
   '[{"qty":"400g","item":"maïs hominy en conserve"},{"qty":"600g","item":"épaule de porc"},{"qty":"3","item":"piments guajillo séchés"},{"qty":"2","item":"piments ancho séchés"},{"qty":"4 gousses","item":"ail"},{"qty":"1","item":"oignon"},{"qty":"1 c.c.","item":"origan mexicain"},{"qty":"sel","item":"et poivre"}]',
   '["Réhydratez les piments 20 min dans l eau chaude","Mixez les piments avec 2 gousses d ail et de l eau de trempage","Cuisez le porc dans 2L d eau avec ail, sel, origan","Retirez le porc, effilochez-le","Ajoutez la purée de piments et le hominy au bouillon","Mijotez 30 min, ajoutez le porc effiloché","Servez avec radis, laitue, origan et citron vert"]',
   'Faites griller les piments secs à sec 30 secondes avant de les réhydrater pour libérer leurs arômes.', 'Le pozole était un plat rituel des Aztèques, originellement préparé avec de la viande humaine lors des sacrifices.'),
  ('Les Chiles Rellenos', 'Piments poblano farcis au fromage, en pâte à beignet.', '🌶️', 30, 30, 4, 'intermediate', 7.0,
   '[{"qty":"4","item":"piments poblano"},{"qty":"200g","item":"fromage Oaxaca ou mozzarella"},{"qty":"4","item":"œufs séparés"},{"qty":"3 c.s.","item":"farine"},{"qty":"huile","item":"pour friture"},{"qty":"400ml","item":"sauce tomate épicée"}]',
   '["Brûlez les piments sur la flamme directe en tournant","Placez dans un sac plastique 10 min pour que la vapeur facilite le pelage","Pelez, faites une fente et retirez les graines","Farcissez de fromage et refermez avec un cure-dent","Battez les blancs en neige ferme, incorporez les jaunes","Farinez les piments, trempez dans la pâte","Faites frire 3 min de chaque côté","Servez nappés de sauce tomate"]',
   'La pâte doit être légère et aérée — les blancs en neige sont le secret.', 'Les chiles rellenos sont un classique de la cuisine poblana, région du Mexique.'),
  ('La Cochinita Pibil', 'Porc mariné à l achiote, cuit lentement dans des feuilles de bananier.', '🐷', 30, 180, 8, 'advanced', 10.0,
   '[{"qty":"1.5kg","item":"épaule de porc"},{"qty":"100g","item":"pâte d achiote"},{"qty":"150ml","item":"jus d orange"},{"qty":"50ml","item":"jus de citron vert"},{"qty":"4 gousses","item":"ail"},{"qty":"1 c.c.","item":"cumin"},{"qty":"feuilles","item":"de bananier"},{"qty":"2","item":"oignons rouges pour pickles"}]',
   '["Mixez achiote, jus d agrumes, ail et cumin en marinade","Badigeonnez le porc et laissez mariner 4h minimum","Enveloppez dans les feuilles de bananier","Enfournez à 160°C pendant 3 heures","Effilochez la viande dans son jus","Picklez les oignons dans jus de citron vert + sel + origan 1h","Servez dans des tortillas avec les oignons pickles"]',
   'Les oignons marinés à la lime sont indispensables — ils équilibrent le gras de la viande.', 'La cuisson pibil est une technique maya de cuisson en fosse enterrée avec des pierres chaudes.'),
  ('Le Mole Poblano', 'Sauce mole aux piments et cacao sur poulet — le roi des moles.', '🍫', 60, 120, 6, 'advanced', 12.0,
   '[{"qty":"1","item":"poulet entier coupé"},{"qty":"4","item":"piments mulato séchés"},{"qty":"3","item":"piments ancho séchés"},{"qty":"2","item":"piments chipotle"},{"qty":"50g","item":"chocolat noir 70%"},{"qty":"30g","item":"graines de sésame"},{"qty":"30g","item":"cacahuètes grillées"},{"qty":"2","item":"tomates"},{"qty":"4 gousses","item":"ail"},{"qty":"1","item":"oignon"},{"qty":"épices","item":"cannelle, clou, poivre noir"}]',
   '["Faites griller les piments à sec puis réhydratez 30 min","Faites revenir tomates, ail, oignon à sec jusqu à brûler légèrement","Mixez piments, tomates, ail, oignon avec les épices","Faites revenir la purée dans de l huile 5 min","Ajoutez bouillon de poulet peu à peu en mélangeant","Ajoutez cacahuètes, sésame et chocolat","Mijotez 30 min en remuant","Pochez le poulet dans le mole 20 min"]',
   'Le mole se bonifie avec le temps — préparez-le la veille pour le meilleur résultat.', 'Le mole poblano compte plus de 20 ingrédients — il est patrimoine culinaire immatériel du Mexique.')
) AS v(lesson_title, title, description, emoji, prep_time_min, cook_time_min, servings, difficulty, avg_price_eur, ingredients, instructions, chef_tip, cultural_note)
JOIN public.lessons l ON l.title = v.lesson_title;

-- ============================================================
-- RECIPES FOR INDIAN LESSONS 21-35
-- ============================================================
INSERT INTO public.recipes (id, lesson_id, title, description, emoji, prep_time_min, cook_time_min, servings, difficulty, avg_price_eur, ingredients, instructions, chef_tip, cultural_note)
SELECT gen_random_uuid(), l.id, v.title, v.description, v.emoji, v.prep_time_min, v.cook_time_min, v.servings, v.difficulty, v.avg_price_eur, v.ingredients::jsonb, v.instructions::jsonb, v.chef_tip, v.cultural_note
FROM (VALUES
  ('Le Dal Makhani', 'Dal makhani aux lentilles noires, beurre et crème — version express.', '🫘', 20, 120, 4, 'intermediate', 6.0,
   '[{"qty":"200g","item":"lentilles noires (urad dal entières)"},{"qty":"50g","item":"haricots rouges"},{"qty":"2 c.s.","item":"beurre"},{"qty":"200ml","item":"crème fraîche"},{"qty":"400ml","item":"tomates concassées"},{"qty":"4 gousses","item":"ail"},{"qty":"2cm","item":"gingembre frais"},{"qty":"1 c.c.","item":"cumin"},{"qty":"1 c.c.","item":"garam masala"},{"qty":"sel","item":"au goût"}]',
   '["Faites tremper les lentilles et haricots 8h","Cuisez à la cocotte-minute 30 min","Faites revenir ail et gingembre au beurre","Ajoutez les tomates et épices, cuisez 10 min","Incorporez les lentilles cuites écrasées partiellement","Ajoutez la crème et laissez mijoter 30 min à feu doux","Servez avec du naan chaud et du beurre"]',
   'L authentique dal makhani mijote 8-12 heures. En cocotte-minute, on peut obtenir un bon résultat en 2h.', 'Le dal makhani a été inventé par Kundan Lal Gujral au restaurant Moti Mahal de Delhi dans les années 50.'),
  ('Le Palak Paneer', 'Paneer dans une sauce d épinards veloutée aux épices indiennes.', '🧀', 20, 30, 4, 'beginner', 7.0,
   '[{"qty":"400g","item":"épinards frais"},{"qty":"250g","item":"paneer coupé en dés"},{"qty":"1","item":"oignon"},{"qty":"3 gousses","item":"ail"},{"qty":"2cm","item":"gingembre"},{"qty":"2","item":"tomates"},{"qty":"1 c.c.","item":"cumin"},{"qty":"1 c.c.","item":"garam masala"},{"qty":"100ml","item":"crème fraîche"},{"qty":"2 c.s.","item":"huile"}]',
   '["Blanchissez les épinards 2 min, plongez dans l eau glacée","Mixez en purée lisse","Faites revenir cumin dans l huile","Ajoutez oignon, ail, gingembre, cuisez 5 min","Ajoutez tomates et épices, cuisez 10 min","Incorporez la purée d épinards","Ajoutez paneer et crème, mijotez 5 min"]',
   'L eau glacée après blanchissage préserve la couleur verte vive des épinards.', 'Le palak paneer est un pilier de la cuisine végétarienne du nord de l Inde, populaire dans tout le sous-continent.'),
  ('Le Chana Masala', 'Pois chiches épicés dans une sauce tomate acidulée au tamarin.', '🫘', 20, 40, 4, 'beginner', 5.0,
   '[{"qty":"400g","item":"pois chiches en conserve"},{"qty":"2","item":"oignons"},{"qty":"3","item":"tomates"},{"qty":"4 gousses","item":"ail"},{"qty":"2cm","item":"gingembre"},{"qty":"1 c.s.","item":"jus de tamarin"},{"qty":"1 c.c.","item":"amchur (mangue séchée)"},{"qty":"épices","item":"cumin, coriandre, garam masala"}]',
   '["Faites revenir les oignons jusqu à dorés profonds","Ajoutez ail, gingembre, épices","Ajoutez les tomates, cuisez jusqu à sauce épaisse","Incorporez les pois chiches et 200ml d eau","Ajoutez tamarin et amchur","Mijotez 20 min","Garnissez de coriandre fraîche"]',
   'L amchur (poudre de mangue verte) apporte l acidité caractéristique du chana masala.', 'Le chana masala est servi au petit-déjeuner avec du bhature (pain frit gonflé) dans le Punjab.'),
  ('Les Pakoras d Oignon', 'Beignets croustillants d oignons à la farine de pois chiches.', '🧅', 15, 20, 4, 'beginner', 4.0,
   '[{"qty":"2","item":"oignons en fines rondelles"},{"qty":"150g","item":"besan (farine de pois chiches)"},{"qty":"1 c.c.","item":"curcuma"},{"qty":"1 c.c.","item":"piment en poudre"},{"qty":"1 c.c.","item":"graines d ajwain"},{"qty":"eau","item":"pour la pâte"},{"qty":"huile","item":"pour friture"},{"qty":"sel","item":"au goût"}]',
   '["Mélangez besan avec épices et sel","Ajoutez de l eau peu à peu pour une pâte épaisse","Incorporez les oignons en rondelles","Chauffez l huile à 175°C","Déposez des cuillères de mélange dans l huile","Faites frire 3-4 min jusqu à dorés et croustillants","Égouttez et servez avec chutney de coriandre"]',
   'La pâte doit être épaisse et non coulante — les pakoras seront plus croustillants.', 'En Inde, quand la mousson commence et qu il pleut, la tradition est de faire des pakoras et du chaï.'),
  ('Le Gulab Jamun', 'Boulettes moelleuses de lait frites dans un sirop parfumé à la rose.', '🌹', 20, 30, 6, 'intermediate', 5.0,
   '[{"qty":"200g","item":"lait en poudre entier"},{"qty":"3 c.s.","item":"farine"},{"qty":"1/2 c.c.","item":"levure chimique"},{"qty":"2 c.s.","item":"beurre fondu"},{"qty":"lait","item":"pour lier la pâte"},{"qty":"300g","item":"sucre"},{"qty":"300ml","item":"eau"},{"qty":"1 c.c.","item":"eau de rose"},{"qty":"5","item":"cardamomes écrasées"}]',
   '["Faites le sirop: sucre + eau + cardamome, cuisez 10 min","Ajoutez l eau de rose au sirop hors feu","Mélangez lait en poudre, farine, levure, beurre","Ajoutez du lait peu à peu pour une pâte souple","Formez des boulettes lisses sans craquelures","Faites frire à feu doux 10 min en tournant","Plongez immédiatement dans le sirop chaud 30 min"]',
   'Faites frire à feu très doux — les boulettes doivent dorer lentement pour cuire à cœur.', 'Le gulab jamun est servi chaud ou froid lors de toutes les fêtes hindoues et au restaurant.')
) AS v(lesson_title, title, description, emoji, prep_time_min, cook_time_min, servings, difficulty, avg_price_eur, ingredients, instructions, chef_tip, cultural_note)
JOIN public.lessons l ON l.title = v.lesson_title;

-- ============================================================
-- RECIPES FOR THAI LESSONS 21-35
-- ============================================================
INSERT INTO public.recipes (id, lesson_id, title, description, emoji, prep_time_min, cook_time_min, servings, difficulty, avg_price_eur, ingredients, instructions, chef_tip, cultural_note)
SELECT gen_random_uuid(), l.id, v.title, v.description, v.emoji, v.prep_time_min, v.cook_time_min, v.servings, v.difficulty, v.avg_price_eur, v.ingredients::jsonb, v.instructions::jsonb, v.chef_tip, v.cultural_note
FROM (VALUES
  ('Le Khao Pad Sapparod', 'Riz sauté à l ananas servi dans l ananas évidé.', '🍍', 15, 15, 2, 'beginner', 8.0,
   '[{"qty":"300g","item":"riz cuit de la veille"},{"qty":"1","item":"ananas entier évidé"},{"qty":"150g","item":"crevettes décortiquées"},{"qty":"2","item":"œufs"},{"qty":"3 c.s.","item":"sauce soja"},{"qty":"1 c.s.","item":"sauce poisson"},{"qty":"1","item":"oignon rouge émincé"},{"qty":"2 gousses","item":"ail"},{"qty":"2 c.s.","item":"huile"}]',
   '["Évidez l ananas en gardant la coquille","Coupez la chair en dés","Chauffez l huile dans le wok à feu très vif","Faites revenir ail et oignon 1 min","Ajoutez les crevettes, cuisez 2 min","Poussez sur le côté, brouilles les œufs","Ajoutez le riz froid, sauces soja et poisson","Incorporez les dés d ananas","Servez dans la coquille d ananas"]',
   'Le riz doit être froid et de la veille — le riz frais colle et devient pâteux.', 'Ce plat est popularisé dans les restaurants thaïlandais pour son effet visuel spectaculaire.'),
  ('Le Gaeng Massaman', 'Curry massaman à la noix de coco, pommes de terre et cacahuètes.', '🥜', 20, 60, 4, 'intermediate', 9.0,
   '[{"qty":"500g","item":"poulet en morceaux"},{"qty":"2 c.s.","item":"pâte de curry massaman"},{"qty":"400ml","item":"lait de coco"},{"qty":"300g","item":"pommes de terre"},{"qty":"50g","item":"cacahuètes grillées"},{"qty":"2 c.s.","item":"sauce poisson"},{"qty":"1 c.s.","item":"sucre de palme"},{"qty":"2","item":"feuilles de laurier"},{"qty":"3","item":"cardamomes"}]',
   '["Faites revenir la pâte de curry dans la crème de coco (partie solide) 3 min","Ajoutez le poulet et dorez","Versez le reste du lait de coco et 200ml d eau","Ajoutez pommes de terre, cardamomes, laurier","Mijotez 30 min à feu doux","Assaisonnez avec sauce poisson et sucre de palme","Ajoutez les cacahuètes en fin de cuisson"]',
   'Le massaman se bonifie le lendemain — les épices ont le temps de se fondre.', 'Le massaman est d influence persane et malaise, arrivé en Thaïlande avec les marchands musulmans.'),
  ('Le Khao Niao Mamuang', 'Riz gluant à la noix de coco avec mangue fraîche mûre.', '🥭', 240, 30, 4, 'beginner', 7.0,
   '[{"qty":"300g","item":"riz gluant"},{"qty":"400ml","item":"lait de coco"},{"qty":"3 c.s.","item":"sucre"},{"qty":"1 c.c.","item":"sel"},{"qty":"2","item":"mangues mûres"},{"qty":"2 c.s.","item":"graines de sésame grillées"},{"qty":"feuilles","item":"de pandan pour arôme"}]',
   '["Trempez le riz gluant 4h minimum dans l eau froide","Égouttez et cuisez à la vapeur 25 min sur feuilles de pandan","Chauffez lait de coco avec sucre et sel","Mélangez le riz chaud avec le lait de coco sucré","Laissez absorber 15 min","Tranchez les mangues en éventail","Servez le riz avec les mangues et sésame"]',
   'La qualité de la mangue est déterminante — elle doit être bien mûre et parfumée.', 'Ce dessert est saisonnier en Thaïlande — les mangues sont au pic de maturité d avril à juin.'),
  ('Le Gaeng Keow Wan', 'Curry vert au lait de coco avec aubergines thaïes et basilic.', '🌿', 15, 25, 4, 'intermediate', 8.0,
   '[{"qty":"500g","item":"poulet en tranches"},{"qty":"2 c.s.","item":"pâte de curry vert"},{"qty":"400ml","item":"lait de coco"},{"qty":"150g","item":"aubergines thaïes"},{"qty":"2 c.s.","item":"sauce poisson"},{"qty":"1 c.s.","item":"sucre de palme"},{"qty":"poignée","item":"de basilic thaï"},{"qty":"4","item":"feuilles de combava"}]',
   '["Faites revenir la pâte de curry dans la crème de coco 2 min","Ajoutez le poulet et cuisez 3 min","Versez le lait de coco restant","Ajoutez les aubergines coupées en deux","Assaisonnez avec sauce poisson et sucre de palme","Ajoutez feuilles de combava","Cuisez 10 min à frémissement","Ajoutez le basilic hors feu"]',
   'La pâte de curry vert doit être frite dans la crème de coco avant d ajouter le lait — le gras libère les arômes.', 'Le curry vert est le plus piquant des curries thaïs — il utilise des piments verts frais dans sa pâte.')
) AS v(lesson_title, title, description, emoji, prep_time_min, cook_time_min, servings, difficulty, avg_price_eur, ingredients, instructions, chef_tip, cultural_note)
JOIN public.lessons l ON l.title = v.lesson_title;

-- ============================================================
-- RECIPES FOR GREEK LESSONS 21-35
-- ============================================================
INSERT INTO public.recipes (id, lesson_id, title, description, emoji, prep_time_min, cook_time_min, servings, difficulty, avg_price_eur, ingredients, instructions, chef_tip, cultural_note)
SELECT gen_random_uuid(), l.id, v.title, v.description, v.emoji, v.prep_time_min, v.cook_time_min, v.servings, v.difficulty, v.avg_price_eur, v.ingredients::jsonb, v.instructions::jsonb, v.chef_tip, v.cultural_note
FROM (VALUES
  ('Le Pastitsio', 'Gratin de pâtes tubulaires à la viande et béchamel dorée.', '🍝', 30, 60, 6, 'intermediate', 8.0,
   '[{"qty":"400g","item":"pâtes tubulaires (penne)"},{"qty":"500g","item":"viande hachée mixte"},{"qty":"400ml","item":"sauce tomate"},{"qty":"1","item":"oignon"},{"qty":"1 c.c.","item":"cannelle"},{"qty":"pour béchamel:","item":""},{"qty":"50g","item":"beurre"},{"qty":"50g","item":"farine"},{"qty":"500ml","item":"lait"},{"qty":"2","item":"œufs"},{"qty":"100g","item":"parmesan râpé"}]',
   '["Cuisez les pâtes al dente","Faites revenir oignon et viande, ajoutez tomate et cannelle","Faites la béchamel: beurre + farine + lait, cuisez jusqu à épaississement","Hors feu, ajoutez œufs et parmesan","Dans un plat, couche de pâtes, viande, pâtes, béchamel","Enfournez à 180°C 45 min jusqu à doré","Laissez reposer 15 min avant de servir"]',
   'La cannelle est le secret du pastitsio — elle différencie ce plat du simple gratin.', 'Le pastitsio est le plat des grandes occasions familiales grecques, comme les mariages et baptêmes.'),
  ('La Gemista', 'Tomates et poivrons farcis au riz et herbes fraîches.', '🫑', 20, 60, 4, 'beginner', 7.0,
   '[{"qty":"4","item":"tomates mûres"},{"qty":"4","item":"poivrons"},{"qty":"150g","item":"riz long grain"},{"qty":"2","item":"oignons émincés"},{"qty":"bouquet","item":"de persil et menthe"},{"qty":"100ml","item":"huile d olive"},{"qty":"sel, poivre","item":"et sucre"}]',
   '["Évidez tomates et poivrons en gardant les chapeaux","Réservez la chair des tomates","Faites revenir oignon dans l huile","Ajoutez riz, chair de tomate, herbes, sel","Remplissez les légumes aux 3/4 (riz gonfle)","Remettez les chapeaux","Arrosez d huile d olive","Enfournez à 180°C 1h en arrosant régulièrement"]',
   'Ajoutez un peu de sucre dans la farce — cela équilibre l acidité des tomates.', 'La gemista est le plat familial de l été grec, préparée dans chaque foyer quand les légumes du jardin arrivent.'),
  ('Les Loukoumades', 'Beignets levés au miel et cannelle — la pâtisserie la plus ancienne de Grèce.', '🍯', 10, 20, 4, 'beginner', 4.0,
   '[{"qty":"200g","item":"farine"},{"qty":"1 sachet","item":"levure de boulanger"},{"qty":"250ml","item":"eau tiède"},{"qty":"1 c.c.","item":"sel"},{"qty":"huile","item":"pour friture"},{"qty":"200g","item":"miel"},{"qty":"1 c.c.","item":"cannelle"},{"qty":"2 c.s.","item":"graines de sésame"}]',
   '["Dissolvez la levure dans l eau tiède 10 min","Ajoutez la farine et sel, mélangez","Couvrez et laissez reposer 1h","La pâte doit être mousseuse","Chauffez l huile à 175°C","Déposez des cuillères de pâte dans l huile","Faites frire 3 min en tournant","Égouttez et nappez de miel, saupoudrez cannelle et sésame"]',
   'Servez immédiatement — les loukoumades perdent leur croustillant en 5 minutes.', 'Les loukoumades étaient offerts aux vainqueurs des Jeux olympiques antiques, trempés dans du miel.'),
  ('Le Tiropita', 'Tourte feuilletée à la feta et aux œufs, croustillante et dorée.', '🥧', 20, 45, 6, 'intermediate', 6.0,
   '[{"qty":"500g","item":"feta émiettée"},{"qty":"4","item":"œufs"},{"qty":"200g","item":"fromage blanc"},{"qty":"1 c.c.","item":"poivre noir"},{"qty":"10 feuilles","item":"de phyllo"},{"qty":"100g","item":"beurre fondu"},{"qty":"graines","item":"de sésame pour décoration"}]',
   '["Mélangez feta émiettée, œufs, fromage blanc et poivre","Huilez un plat allant au four","Disposez 5 feuilles de phyllo en badigeonnant de beurre entre chaque","Versez la garniture au fromage","Couvrez avec 5 feuilles de phyllo beurrées","Scarifiez le dessus légèrement","Saupoudrez de sésame","Enfournez à 180°C 40-45 min"]',
   'Ne serrez pas trop le phyllo — il doit rester libre pour devenir croustillant.', 'Le tiropita est vendu dans chaque boulangerie (fourno) grecque dès le matin pour le petit-déjeuner.')
) AS v(lesson_title, title, description, emoji, prep_time_min, cook_time_min, servings, difficulty, avg_price_eur, ingredients, instructions, chef_tip, cultural_note)
JOIN public.lessons l ON l.title = v.lesson_title;

-- ============================================================
-- EXERCISES FOR MEXICAN LESSONS 21-35
-- ============================================================
INSERT INTO public.exercises (id, lesson_id, type, question, options, correct_answer, explanation, order_index)
SELECT gen_random_uuid(), l.id, v.type, v.question, v.options::jsonb, v.correct_answer, v.explanation, v.order_index
FROM (VALUES
  ('Les Tamales de Maïs', 'multiple_choice', 'Comment savoir si les tamales sont cuits ?', '["La masa se détache facilement de la feuille","La feuille devient verte","La vapeur sent le maïs","Le temps de cuisson est écoulé"]', 'La masa se détache facilement de la feuille', 'Quand la masa est cuite, elle ne colle plus à la feuille — c est le test traditionnel.', 1),
  ('Les Tamales de Maïs', 'fill_in_blank', 'La pâte de maïs nixtamalisé utilisée dans les tamales s appelle la ___', '[]', 'masa', 'La masa est la pâte de maïs traité à la chaux, base de nombreux plats mexicains.', 2),
  ('Le Pozole Rojo', 'multiple_choice', 'Quel est l ingrédient principal du pozole ?', '["Maïs hominy","Riz blanc","Quinoa","Lentilles"]', 'Maïs hominy', 'Le hominy est du maïs traité à la chaux (nixtamalisé), base du pozole.', 1),
  ('Le Pozole Rojo', 'fill_in_blank', 'Pour libérer les arômes, on fait ___ les piments secs à sec avant de les réhydrater', '[]', 'griller', 'La chaleur à sec active les huiles essentielles des piments séchés.', 2),
  ('Les Chiles Rellenos', 'multiple_choice', 'Comment peler facilement un piment poblano ?', '["Le brûler sur la flamme puis mettre dans un sac","Le plonger dans l eau bouillante","Le peler à cru avec un couteau","Le faire bouillir 10 minutes"]', 'Le brûler sur la flamme puis mettre dans un sac', 'La chaleur directe brûle la peau et la vapeur dans le sac la décolle.', 1),
  ('Les Chiles Rellenos', 'fill_in_blank', 'Les piments poblano farcis au fromage s appellent les ___', '[]', 'chiles rellenos', 'Rellenos signifie farcis en espagnol.', 2),
  ('La Sopa de Lima', 'multiple_choice', 'De quelle région est originaire la sopa de lima ?', '["Yucatán","Oaxaca","Jalisco","Chihuahua"]', 'Yucatán', 'La sopa de lima est une spécialité de la cuisine maya du Yucatán.', 1),
  ('La Sopa de Lima', 'fill_in_blank', 'La ___ est l herbe aromatique typique de la cuisine du Yucatán', '[]', 'epazote', 'L epazote est une herbe mexicaine avec un arôme fort et distinctif.', 2),
  ('Le Mole Poblano', 'multiple_choice', 'Quel ingrédient inattendu entre dans la composition du mole ?', '["Chocolat noir","Vanille","Cannelle en stick","Café"]', 'Chocolat noir', 'Le cacao apporte amertume et profondeur au mole poblano.', 1),
  ('Le Mole Poblano', 'fill_in_blank', 'Le mole se ___ avec le temps — préparez-le la veille', '[]', 'bonifie', 'Comme beaucoup de plats épicés complexes, le mole gagne en saveur avec le temps.', 2),
  ('Les Tlayudas Oaxaqueñas', 'multiple_choice', 'De quelle ville est originaire la tlayuda ?', '["Oaxaca","Puebla","Mexico","Guadalajara"]', 'Oaxaca', 'La tlayuda est le plat de rue emblématique de la ville d Oaxaca.', 1),
  ('Les Tlayudas Oaxaqueñas', 'fill_in_blank', 'Le fromage filant d Oaxaca s appelle le ___', '[]', 'quesillo', 'Le quesillo (fromage d Oaxaca) est un fromage à pâte filée similaire à la mozzarella.', 2),
  ('Le Birria de Res', 'multiple_choice', 'Quelle est la particularité du service du birria ?', '["Les tacos sont trempés dans le consommé","La viande est servie crue","Le birria est mangé froid","Il est servi avec des spaghettis"]', 'Les tacos sont trempés dans le consommé', 'Les birria tacos sont plongés dans le bouillon rouge avant de les manger — une expérience unique.', 1),
  ('Le Birria de Res', 'fill_in_blank', 'Le birria est originaire de l état de ___', '[]', 'Jalisco', 'Jalisco est l état mexicain dont Guadalajara est la capitale.', 2),
  ('Les Enfrijoladas', 'multiple_choice', 'Quelle herbe mexicaine est traditionnellement ajoutée aux haricots noirs ?', '["Epazote","Coriandre","Menthe","Basilic"]', 'Epazote', 'L epazote est l herbe traditionnelle des plats de haricots mexicains.', 1),
  ('Les Enfrijoladas', 'fill_in_blank', 'Les tortillas trempées dans une sauce de haricots s appellent les ___', '[]', 'enfrijoladas', 'Du mot frijoles (haricots) — en-frijoladas signifie enveloppées dans les haricots.', 2),
  ('La Cochinita Pibil', 'multiple_choice', 'Quelle épice donne la couleur rouge à la cochinita pibil ?', '["Achiote","Paprika","Piment chipotle","Safran"]', 'Achiote', 'L achiote (rocou) est une graine rouge qui donne couleur et saveur à la cochinita.', 1),
  ('La Cochinita Pibil', 'fill_in_blank', 'La technique maya de cuisson en fosse s appelle le ___', '[]', 'pibil', 'Pibil est une technique maya de cuisson en fosse enterrée avec des pierres chaudes.', 2),
  ('Les Quesadillas au Huitlacoche', 'multiple_choice', 'Quel surnom a le huitlacoche ?', '["Truffe mexicaine","Champignon d or","Maïs de jade","Caviar du Mexique"]', 'Truffe mexicaine', 'Comme la truffe, le huitlacoche est un champignon parasite très prisé pour son goût unique.', 1),
  ('Les Quesadillas au Huitlacoche', 'fill_in_blank', 'Le huitlacoche est un ___ qui pousse sur le maïs', '[]', 'champignon', 'C est un champignon parasite (Ustilago maydis) qui transforme les grains de maïs.', 2),
  ('Le Caldo de Pollo Mexicain', 'multiple_choice', 'Quelle herbe est ajoutée au bouillon de pollo mexicain en fin de cuisson ?', '["Epazote","Persil","Coriandre sèche","Romarin"]', 'Epazote', 'L epazote est l herbe caractéristique de la cuisine mexicaine avec un arôme pénétrant.', 1),
  ('Le Caldo de Pollo Mexicain', 'fill_in_blank', 'La courgette mexicaine utilisée dans le caldo s appelle ___', '[]', 'calabacita', 'La calabacita est une petite courgette mexicaine plus douce que la courgette européenne.', 2),
  ('Les Tortas Ahogadas', 'multiple_choice', 'De quelle ville viennent les tortas ahogadas ?', '["Guadalajara","Mexico","Monterrey","Tijuana"]', 'Guadalajara', 'Les tortas ahogadas sont la spécialité incontournable de Guadalajara (Jalisco).', 1),
  ('Les Tortas Ahogadas', 'fill_in_blank', 'Le pain dur et croustillant de Jalisco s appelle le ___', '[]', 'birote', 'Le birote est un pain croustillant local indispensable pour les tortas ahogadas authentiques.', 2),
  ('Le Sopa Azteca', 'multiple_choice', 'Quel piment fumé est utilisé dans la sopa azteca ?', '["Chipotle","Guajillo","Pasilla","Mulato"]', 'Chipotle', 'Le chipotle est un jalapeño fumé et séché qui apporte une saveur fumée caractéristique.', 1),
  ('Le Sopa Azteca', 'fill_in_blank', 'Les tortillas sont ajoutées ___ de servir pour garder leur texture', '[]', 'juste avant', 'Les tortillas ajoutées trop tôt deviennent molles — ajoutez-les au dernier moment.', 2),
  ('Les Gorditas de Chicharrón', 'multiple_choice', 'Qu est-ce que le chicharrón ?', '["Couenne de porc soufflée","Fromage frit","Bœuf séché","Maïs grillé"]', 'Couenne de porc soufflée', 'Le chicharrón est de la couenne de porc frite à haute température jusqu à souffler.', 1),
  ('Les Gorditas de Chicharrón', 'fill_in_blank', 'Une galette épaisse de masa s appelle une ___', '[]', 'gordita', 'Gordita signifie petite grosse en espagnol — une galette épaisse et dansée.', 2),
  ('Le Champurrado', 'multiple_choice', 'Quel ingrédient rend le champurrado épais ?', '["Masa (pâte de maïs)","Farine de blé","Amidon de maïs","Riz cuit"]', 'Masa (pâte de maïs)', 'La masa nixtamalisée épaissit le champurrado et lui donne son corps caractéristique.', 1),
  ('Le Champurrado', 'fill_in_blank', 'Le sucre de canne brut non raffiné utilisé au Mexique s appelle le ___', '[]', 'piloncillo', 'Le piloncillo est vendu en cônes bruns solides et a une saveur de mélasse.', 2)
) AS v(lesson_title, type, question, options, correct_answer, explanation, order_index)
JOIN public.lessons l ON l.title = v.lesson_title;

-- ============================================================
-- EXERCISES FOR INDIAN LESSONS 21-35
-- ============================================================
INSERT INTO public.exercises (id, lesson_id, type, question, options, correct_answer, explanation, order_index)
SELECT gen_random_uuid(), l.id, v.type, v.question, v.options::jsonb, v.correct_answer, v.explanation, v.order_index
FROM (VALUES
  ('Le Dal Makhani', 'multiple_choice', 'Dans quel restaurant a été inventé le dal makhani ?', '["Moti Mahal à Delhi","Taj à Mumbai","Bukhara à Delhi","Dasaprakash à Chennai"]', 'Moti Mahal à Delhi', 'Kundan Lal Gujral a créé le dal makhani au restaurant Moti Mahal de Delhi dans les années 50.', 1),
  ('Le Dal Makhani', 'fill_in_blank', 'Les lentilles noires entières utilisées dans le dal makhani s appellent ___', '[]', 'urad dal', 'L urad dal entier est différent de l urad dal fendu — plus riche et plus crémeux.', 2),
  ('Le Palak Paneer', 'multiple_choice', 'Pourquoi plonge-t-on les épinards dans l eau glacée après blanchissage ?', '["Pour conserver la couleur verte","Pour les attendrir","Pour enlever l amertume","Pour les congeler"]', 'Pour conserver la couleur verte', 'L eau glacée stoppe la cuisson et préserve la chlorophylle — d où la couleur verte vive.', 1),
  ('Le Palak Paneer', 'fill_in_blank', 'Le fromage frais indien non fermenté s appelle le ___', '[]', 'paneer', 'Le paneer est un fromage à pâte fraîche obtenu en faisant cailler du lait avec du jus de citron.', 2),
  ('Le Chana Masala', 'multiple_choice', 'Quel ingrédient apporte l acidité caractéristique du chana masala ?', '["Amchur (mangue séchée)","Tamarin","Jus de citron","Vinaigre"]', 'Amchur (mangue séchée)', 'L amchur est de la mangue verte séchée et moulue — elle apporte acidité et fruité.', 1),
  ('Le Chana Masala', 'fill_in_blank', 'Les pois chiches en hindi s appellent ___', '[]', 'chana', 'Chana masala signifie littéralement pois chiches avec des épices.', 2),
  ('Le Biryani d Agneau Hyderabadi', 'multiple_choice', 'Quelle technique de cuisson scelle la marmite du biryani ?', '["Pâte de farine (dum)","Couvercle hermétique","Film alimentaire","Feuille d aluminium"]', 'Pâte de farine (dum)', 'Le dum est la technique de cuisson à l étouffée — la vapeur interne cuit le riz et la viande ensemble.', 1),
  ('Le Biryani d Agneau Hyderabadi', 'fill_in_blank', 'Le biryani hyderabadi vient de la cuisine ___', '[]', 'Nizami', 'La cuisine Nizami est la cuisine royale des Nizam d Hyderabad, d influence moghole et persane.', 2),
  ('Le Rogan Josh', 'multiple_choice', 'De quelle région indienne vient le rogan josh ?', '["Cachemire","Punjab","Rajasthan","Gujarat"]', 'Cachemire', 'Le rogan josh est le plat emblématique de la cuisine cachemirienne.', 1),
  ('Le Rogan Josh', 'fill_in_blank', 'La couleur rouge caractéristique du rogan josh vient du colorant naturel ___', '[]', 'ratan jot', 'Le ratan jot (alkanna tinctoria) est une racine qui donne la couleur rouge au rogan josh authentique.', 2),
  ('Les Pakoras d Oignon', 'multiple_choice', 'Quelle farine est utilisée pour la pâte à pakoras ?', '["Besan (farine de pois chiches)","Farine de blé","Farine de riz","Fécule de pomme de terre"]', 'Besan (farine de pois chiches)', 'Le besan donne une pâte croustillante et légère, naturellement sans gluten.', 1),
  ('Les Pakoras d Oignon', 'fill_in_blank', 'Les pakoras sont traditionnellement mangés pendant la ___', '[]', 'mousson', 'La tradition indienne veut qu on mange des pakoras et du chaï dès que la pluie commence.', 2),
  ('Le Pav Bhaji', 'multiple_choice', 'Dans quelle ville le pav bhaji a-t-il été inventé ?', '["Mumbai","Delhi","Kolkata","Chennai"]', 'Mumbai', 'Le pav bhaji est né dans les usines textiles de Mumbai pour nourrir les ouvriers rapidement.', 1),
  ('Le Pav Bhaji', 'fill_in_blank', 'Le petit pain moelleux servi avec le bhaji s appelle le ___', '[]', 'pav', 'Le pav est un petit pain de style portugais introduit à Goa et popularisé à Mumbai.', 2),
  ('Le Kadhi Pakora', 'multiple_choice', 'De quelle région est originaire le kadhi pakora ?', '["Punjab","Rajasthan","Maharashtra","Kerala"]', 'Punjab', 'Le kadhi pakora est l un des plats les plus réconfortants du Punjab.', 1),
  ('Le Kadhi Pakora', 'fill_in_blank', 'Le kadhi est une soupe de ___ et farine de pois chiches', '[]', 'yogourt', 'Le mélange yogourt et besan crée une soupe crémeuse et acidulée caractéristique.', 2),
  ('Le Aloo Gobi', 'multiple_choice', 'Comment cuisiner l aloo gobi de façon authentique ?', '["Sautés à feu moyen-fort pour caraméliser","Bouillis dans de l eau","Cuits à la vapeur","Frits dans beaucoup d huile"]', 'Sautés à feu moyen-fort pour caraméliser', 'L aloo gobi authentique est sec et doré — pas braisé ni bouilli.', 1),
  ('Le Aloo Gobi', 'fill_in_blank', 'Aloo signifie ___ et gobi signifie chou-fleur en hindi', '[]', 'pomme de terre', 'Aloo gobi est littéralement pomme de terre chou-fleur — les deux ingrédients du plat.', 2),
  ('Le Saag Aloo', 'multiple_choice', 'Quelles feuilles vertes composent traditionnellement le saag ?', '["Moutarde et épinards","Basilic et menthe","Coriandre et persil","Poireaux et chou"]', 'Moutarde et épinards', 'Le saag classique du Punjab mélange feuilles de moutarde et épinards.', 1),
  ('Le Saag Aloo', 'fill_in_blank', 'Le pain de maïs servi avec le saag s appelle ___', '[]', 'makki di roti', 'La makki di roti (pain de maïs) est le pain traditionnel du Punjab en hiver.', 2),
  ('Le Lassi à la Mangue', 'multiple_choice', 'Quelle variété de mangue est la plus utilisée dans le lassi indien ?', '["Alphonso","Ataulfo","Haden","Kent"]', 'Alphonso', 'La mangue Alphonso de Ratnagiri est considérée comme la reine des mangues — sucrée et parfumée.', 1),
  ('Le Lassi à la Mangue', 'fill_in_blank', 'Le lassi est originaire de l état du ___', '[]', 'Punjab', 'Le lassi est la boisson traditionnelle du Punjab, servi dans des grands verres de terre cuite.', 2),
  ('Le Dosa Masala', 'multiple_choice', 'Combien de temps faut-il faire fermenter la pâte à dosa ?', '["8 à 12 heures","30 minutes","2 heures","48 heures"]', '8 à 12 heures', 'La fermentation développe l acidité et les bulles d air qui rendent le dosa croustillant.', 1),
  ('Le Dosa Masala', 'fill_in_blank', 'La soupe de lentilles aux légumes servie avec le dosa s appelle ___', '[]', 'sambar', 'Le sambar est un incontournable du petit-déjeuner du sud de l Inde.', 2),
  ('Le Chole Bhature', 'multiple_choice', 'Quand mange-t-on le chole bhature à Delhi ?', '["Le dimanche matin","Au dîner","En collation","Pendant les fêtes uniquement"]', 'Le dimanche matin', 'Le chole bhature est le brunch du dimanche des familles de Delhi — une tradition sacrée.', 1),
  ('Le Chole Bhature', 'fill_in_blank', 'Le pain frit gonflé servi avec les chole s appelle ___', '[]', 'bhature', 'Le bhature est un pain frit à la farine de blé et yogourt qui gonfle comme un ballon.', 2),
  ('Le Gulab Jamun', 'multiple_choice', 'Quel arôme parfume le sirop des gulab jamun ?', '["Eau de rose et cardamome","Vanille et cannelle","Safran et pistache","Orange et citron"]', 'Eau de rose et cardamome', 'Gulab signifie rose — l eau de rose est l arôme essentiel de ce dessert.', 1),
  ('Le Gulab Jamun', 'fill_in_blank', 'Les boulettes de gulab jamun sont faites à base de ___', '[]', 'lait en poudre', 'Le lait en poudre réduit (khoya) donne aux gulab jamun leur texture spongieuse caractéristique.', 2),
  ('Le Halwa de Carottes', 'multiple_choice', 'Quel autre nom a le halwa de carottes en hindi ?', '["Gajar ka halwa","Carrot mithai","Lal halwa","Meetha gajar"]', 'Gajar ka halwa', 'Gajar signifie carotte et halwa signifie dessert de farine ou légume cuit en confiture sucrée.', 1),
  ('Le Halwa de Carottes', 'fill_in_blank', 'Le lait concentré solide réduit utilisé dans le halwa s appelle ___', '[]', 'khoya', 'Le khoya est obtenu en faisant réduire du lait entier pendant des heures — très riche en matière grasse.', 2)
) AS v(lesson_title, type, question, options, correct_answer, explanation, order_index)
JOIN public.lessons l ON l.title = v.lesson_title;

-- ============================================================
-- EXERCISES FOR THAI LESSONS 21-35
-- ============================================================
INSERT INTO public.exercises (id, lesson_id, type, question, options, correct_answer, explanation, order_index)
SELECT gen_random_uuid(), l.id, v.type, v.question, v.options::jsonb, v.correct_answer, v.explanation, v.order_index
FROM (VALUES
  ('Le Khao Pad Sapparod', 'multiple_choice', 'Pourquoi utilise-t-on du riz de la veille pour le khao pad ?', '["Il ne colle pas","Il est plus nutritif","Il a plus de goût","Il cuit plus vite"]', 'Il ne colle pas', 'Le riz frais est trop humide et colle — le riz refroidi de la veille garde ses grains séparés.', 1),
  ('Le Khao Pad Sapparod', 'fill_in_blank', 'Khao pad signifie ___ sauté en thaï', '[]', 'riz', 'Khao signifie riz et pad signifie sauter à la poêle/wok.', 2),
  ('Le Gaeng Massaman', 'multiple_choice', 'Quelle influence a le curry massaman ?', '["Persane et malaise","Chinoise et indienne","Japonaise et vietnamienne","Française et portugaise"]', 'Persane et malaise', 'Le massaman est arrivé en Thaïlande avec les marchands musulmans persans et malais.', 1),
  ('Le Gaeng Massaman', 'fill_in_blank', 'Le massaman est un curry d influence ___ du sud de la Thaïlande', '[]', 'musulmane', 'Les marchands musulmans ont apporté ce curry riche en épices au sud de la Thaïlande.', 2),
  ('Le Hoy Tod', 'multiple_choice', 'Qu est-ce que le hoy tod ?', '["Omelette de moules croustillante","Soupe de moules","Moules à la vapeur","Beignets de moules"]', 'Omelette de moules croustillante', 'Le hoy tod est une omelette croustillante de moules et pousses de haricots, spécialité de Bangkok.', 1),
  ('Le Hoy Tod', 'fill_in_blank', 'Le hoy tod est emblématique des marchés ___ de Bangkok', '[]', 'nocturnes', 'Les marchés nocturnes (talad rot fai) de Bangkok sont célèbres pour le hoy tod.', 2),
  ('Le Yam Woon Sen', 'multiple_choice', 'Que signifie yam en thaï ?', '["Salade épicée","Soupe","Plat sauté","Curry"]', 'Salade épicée', 'Les yam thaïlandaises combinent toujours les quatre saveurs: piquant, acide, sucré et umami.', 1),
  ('Le Yam Woon Sen', 'fill_in_blank', 'Les vermicelles de verre thaïs s appellent ___', '[]', 'woon sen', 'Le woon sen est fabriqué à partir d amidon de haricot mungo — il devient transparent à la cuisson.', 2),
  ('Le Khao Niao Mamuang', 'multiple_choice', 'Combien de temps faut-il tremper le riz gluant avant cuisson ?', '["Au moins 4 heures","30 minutes","1 heure","Toute la nuit uniquement"]', 'Au moins 4 heures', 'Le trempage permet au riz gluant de cuire uniformément à la vapeur.', 1),
  ('Le Khao Niao Mamuang', 'fill_in_blank', 'Le riz gluant à la mangue est disponible quand les mangues sont mûres en ___ et ___', '[]', 'avril et juin', 'Les mangues Nam Dok Mai et Mamuang Khiao Sawoei sont au pic en avril-juin en Thaïlande.', 2),
  ('Le Pad See Ew', 'multiple_choice', 'Qu est-ce que le wok hei ?', '["Le goût fumé obtenu avec un wok très chaud","Une sauce thaïlandaise","Un type de nouille","Une technique de découpe"]', 'Le goût fumé obtenu avec un wok très chaud', 'Le wok hei (souffle du wok) est l arôme fumé caractéristique de la cuisine au wok à haute température.', 1),
  ('Le Pad See Ew', 'fill_in_blank', 'Les larges nouilles de riz s appellent ___', '[]', 'sen yai', 'Sen yai signifie grande nouille en thaï — ce sont de larges rubans de riz.', 2),
  ('Le Gaeng Keow Wan', 'multiple_choice', 'Le curry vert thaï est-il le plus ou moins piquant des curries thaïs ?', '["Le plus piquant","Le moins piquant","Le plus doux","Le même piquant que le rouge"]', 'Le plus piquant', 'Les piments verts frais dans la pâte de curry vert le rendent plus piquant que le rouge ou le jaune.', 1),
  ('Le Gaeng Keow Wan', 'fill_in_blank', 'Les feuilles aromatiques de combava s appellent en thaï ___', '[]', 'makrut', 'Le makrut (kaffir lime) donne ses feuilles parfumées à de nombreux plats thaïs.', 2),
  ('Le Khao Tom', 'multiple_choice', 'Quand mange-t-on le khao tom en Thaïlande ?', '["Le matin et le soir","Uniquement au déjeuner","Pendant les fêtes","Au restaurant uniquement"]', 'Le matin et le soir', 'Le khao tom est la bouillie de riz réconfortante du matin et du soir des familles thaïes.', 1),
  ('Le Khao Tom', 'fill_in_blank', 'Khao tom signifie riz ___ en thaï', '[]', 'cuit à l eau', 'La bouillie de riz est obtenue en cuisant le riz dans beaucoup plus d eau que d habitude.', 2),
  ('Le Nam Prik Ong', 'multiple_choice', 'Le nam prik ong vient de quelle région de Thaïlande ?', '["Nord (Chiang Mai)","Sud","Bangkok","Isan"]', 'Nord (Chiang Mai)', 'Les nam prik (trempettes épicées) sont une spécialité du nord de la Thaïlande.', 1),
  ('Le Nam Prik Ong', 'fill_in_blank', 'Le nam prik est une ___ épicée thaïe', '[]', 'trempette', 'Les nam prik accompagnent les légumes crus, le riz gluant et les couennes frites.', 2),
  ('Le Pla Rad Prik', 'multiple_choice', 'Comment préparer le poisson avant de le frire pour éviter les éclaboussures ?', '["Le sécher soigneusement","Le saler","Le mariner","Le congeler puis décongeler"]', 'Le sécher soigneusement', 'L eau dans la peau crée des explosions d huile quand on frit — le séchage est essentiel.', 1),
  ('Le Pla Rad Prik', 'fill_in_blank', 'Pla signifie ___ en thaï', '[]', 'poisson', 'Pla est le mot générique pour désigner le poisson dans la cuisine thaïe.', 2),
  ('Le Khanom Krok', 'multiple_choice', 'Comment s appelle l ustensile de cuisson des khanom krok ?', '["Poêle en fonte à alvéoles","Wok","Tajine","Bambou à vapeur"]', 'Poêle en fonte à alvéoles', 'La poêle khanom krok a des alvéoles rondes qui donnent la forme caractéristique aux gâteaux.', 1),
  ('Le Khanom Krok', 'fill_in_blank', 'Les khanom krok sont à la fois ___ à l extérieur et crémeux à l intérieur', '[]', 'croustillants', 'Le contraste de texture est la caractéristique principale des khanom krok bien réussis.', 2),
  ('Le Gaeng Pa', 'multiple_choice', 'Pourquoi le gaeng pa n a-t-il pas de lait de coco ?', '["Il vient des montagnes où il n y en a pas","C est une question de goût","Pour être plus sain","C est un curry végétalien"]', 'Il vient des montagnes où il n y en a pas', 'Dans les régions montagneuses du nord, les cocotiers ne poussent pas — le curry de jungle s adapte.', 1),
  ('Le Gaeng Pa', 'fill_in_blank', 'Pa signifie ___ ou jungle en thaï', '[]', 'forêt', 'Le gaeng pa (curry de forêt) utilise les herbes sauvages de la jungle du nord.', 2),
  ('Le Khua Kling', 'multiple_choice', 'De quelle ville du sud thaïlandais vient le khua kling ?', '["Nakhon Si Thammarat","Phuket","Krabi","Hat Yai"]', 'Nakhon Si Thammarat', 'Le khua kling est la fierté culinaire de Nakhon Si Thammarat dans le sud de la Thaïlande.', 1),
  ('Le Khua Kling', 'fill_in_blank', 'Khua signifie ___ à sec en thaï', '[]', 'sauter', 'La technique khua consiste à sauter la viande sans liquide, juste avec la pâte d épices.', 2),
  ('Le Kai Jiew Moo Sap', 'multiple_choice', 'Comment est l omelette thaïe comparée à l omelette française ?', '["Plus cuite et plus dorée","Moins cuite et baveuse","Semblable","Cuite à la vapeur"]', 'Plus cuite et plus dorée', 'L omelette thaïe est frite jusqu à être dorée et croustillante — l opposé de l omelette française.', 1),
  ('Le Kai Jiew Moo Sap', 'fill_in_blank', 'Kai jiew signifie ___ en thaï', '[]', 'omelette', 'Kai signifie œuf et jiew signifie frit — littéralement œufs frits.', 2),
  ('Le Tub Tim Krob', 'multiple_choice', 'Que signifie tub tim en thaï ?', '["Rubis","Cerise","Fraise","Grenade"]', 'Rubis', 'Les châtaignes colorées en rouge flottant dans le lait blanc ressemblent à des rubis.', 1),
  ('Le Tub Tim Krob', 'fill_in_blank', 'Le lait de coco glacé dans lequel flottent les tub tim est ___ au sucre de palme', '[]', 'sucré', 'Le sucre de palme donne une douceur caramélisée caractéristique au lait de coco du dessert.', 2)
) AS v(lesson_title, type, question, options, correct_answer, explanation, order_index)
JOIN public.lessons l ON l.title = v.lesson_title;

-- ============================================================
-- EXERCISES FOR GREEK LESSONS 21-35
-- ============================================================
INSERT INTO public.exercises (id, lesson_id, type, question, options, correct_answer, explanation, order_index)
SELECT gen_random_uuid(), l.id, v.type, v.question, v.options::jsonb, v.correct_answer, v.explanation, v.order_index
FROM (VALUES
  ('Le Pastitsio', 'multiple_choice', 'Quelle épice aromatique parfume le pastitsio ?', '["Cannelle","Cumin","Safran","Paprika"]', 'Cannelle', 'La cannelle dans la viande hachée différencie le pastitsio du simple gratin — c est le secret grec.', 1),
  ('Le Pastitsio', 'fill_in_blank', 'Pastitsio signifie ___ de pâtes à la viande en grec', '[]', 'gratin', 'Le pastitsio est l équivalent grec des lasagnes italiennes.', 2),
  ('La Gemista', 'multiple_choice', 'Pourquoi remplit-on les légumes aux 3/4 seulement ?', '["Le riz gonfle à la cuisson","Pour qu ils soient plus légers","Pour mettre plus de légumes","Par tradition"]', 'Le riz gonfle à la cuisson', 'Le riz absorbe le jus de tomate et double de volume — un plat trop rempli débordrait.', 1),
  ('La Gemista', 'fill_in_blank', 'Gemista signifie légumes ___ en grec', '[]', 'farcis', 'Le mot gemista vient de gemisi qui signifie remplissage en grec.', 2),
  ('Le Kleftiko', 'multiple_choice', 'Pourquoi le kleftiko est-il cuit emballé dans du papier ?', '["Pour garder toutes les saveurs et l humidité","Pour une raison esthétique","Pour cuire plus vite","Par tradition moderne"]', 'Pour garder toutes les saveurs et l humidité', 'La cuisson à l étouffée dans le papier est l équivalent moderne de la cuisson en fosse des klephtes.', 1),
  ('Le Kleftiko', 'fill_in_blank', 'Les klephtes étaient des ___ grecs qui cuisaient leur viande en secret', '[]', 'brigands', 'Les klephtes cuisaient en fosses fermées pour ne pas révéler leur position avec de la fumée.', 2),
  ('Le Fasolada', 'multiple_choice', 'Quelle est la soupe nationale de la Grèce ?', '["Fasolada (haricots blancs)","Avgolemono","Kakavia","Magiritsa"]', 'Fasolada (haricots blancs)', 'Le fasolada est surnommé le plat national de la Grèce — simple, nourrissant et universel.', 1),
  ('Le Fasolada', 'fill_in_blank', 'On ajoute un filet d ___ juste avant de servir le fasolada', '[]', 'huile d olive', 'L huile d olive crue versée sur le fasolada chaud libère ses arômes et enrichit le plat.', 2),
  ('La Kakavia', 'multiple_choice', 'Depuis quand la kakavia est-elle consommée en Grèce ?', '["L Antiquité","Le Moyen Âge","Le XIXe siècle","La Seconde Guerre mondiale"]', 'L Antiquité', 'La kakavia est mentionnée dans des textes grecs antiques — c est la plus ancienne soupe de poissons connue.', 1),
  ('La Kakavia', 'fill_in_blank', 'La kakavia est parfumée au ___', '[]', 'safran', 'Le safran donne à la kakavia sa couleur dorée et son arôme caractéristique.', 2),
  ('Les Loukoumades', 'multiple_choice', 'Aux Jeux olympiques antiques, on offrait des loukoumades aux vainqueurs ?', '["Oui, trempés dans du miel","Non, c était du pain","Non, c était de l huile d olive","Oui, avec du vin"]', 'Oui, trempés dans du miel', 'Les loukoumades au miel étaient la récompense sucrée des vainqueurs des Jeux dans la Grèce antique.', 1),
  ('Les Loukoumades', 'fill_in_blank', 'La kanela est la ___ en grec', '[]', 'cannelle', 'La kanela est l épice qui parfume les loukoumades avec le miel.', 2),
  ('Le Tiropita', 'multiple_choice', 'Comment s appelle la pâte ultrafine utilisée dans le tiropita ?', '["Phyllo","Filo","Brick","Feuilletée"]', 'Phyllo', 'Le phyllo (ou filo) est une pâte étirée jusqu à la transparence, caractéristique de la pâtisserie grecque.', 1),
  ('Le Tiropita', 'fill_in_blank', 'Le tiropita est vendu dans les ___ grecques dès le matin', '[]', 'boulangeries', 'La fourno (boulangerie grecque) vend du tiropita et spanakopita chauds dès l ouverture.', 2),
  ('Le Revithia Stifado', 'multiple_choice', 'Quand mange-t-on traditionnellement les revithia stifado ?', '["Les jours de jeûne orthodoxes","Uniquement à Noël","Le dimanche","Pendant l été"]', 'Les jours de jeûne orthodoxes', 'Les jours de Carême, la cuisine grecque propose des plats végétariens riches comme ce ragoût de pois chiches.', 1),
  ('Le Revithia Stifado', 'fill_in_blank', 'Revithia signifie ___ en grec', '[]', 'pois chiches', 'Les pois chiches sont une légumineuse centrale de la cuisine méditerranéenne grecque.', 2),
  ('La Bourdeto', 'multiple_choice', 'De quelle île grecque vient la bourdeto ?', '["Corfou","Santorin","Mykonos","Crète"]', 'Corfou', 'La bourdeto est la spécialité de poisson épicé de l île de Corfou, influencée par Venise.', 1),
  ('La Bourdeto', 'fill_in_blank', 'La bourdeto est influencée par la cuisine ___', '[]', 'vénitienne', 'Corfou a été sous domination vénitienne 400 ans, laissant une empreinte culinaire forte.', 2),
  ('Le Soutzoukakia', 'multiple_choice', 'Les soutzoukakia viennent de quelle ancienne ville grecque ?', '["Smyrne (Izmir)","Constantinople","Thessalonique","Alexandrie"]', 'Smyrne (Izmir)', 'Les réfugiés grecs de Smyrne ont apporté ces boulettes épicées en Grèce en 1922.', 1),
  ('Le Soutzoukakia', 'fill_in_blank', 'Les boulettes de Smyrne sont épicées à la ___ et au cumin', '[]', 'cannelle', 'L association cannelle-cumin est la signature des soutzoukakia de Smyrne.', 2),
  ('Les Vrasta Chortarakia', 'multiple_choice', 'Que faire avec l eau de cuisson des horta ?', '["La boire comme une tisane nutritive","La jeter","La réutiliser pour cuire des pâtes","La filtrer et la congeler"]', 'La boire comme une tisane nutritive', 'L eau de cuisson des légumes verts est riche en minéraux et vitamines — une boisson santé en Grèce.', 1),
  ('Les Vrasta Chortarakia', 'fill_in_blank', 'Horta signifie ___ sauvages en grec', '[]', 'légumes verts', 'La cueillette des horta sauvages dans les champs est une tradition vivante en Grèce rurale.', 2),
  ('Le Keftedes Me Saltsa', 'multiple_choice', 'Quel ingrédient rend les keftedes moelleux ?', '["Mie de pain trempée dans le lait","Farine","Fromage râpé","Crème fraîche"]', 'Mie de pain trempée dans le lait', 'La panade (mie de pain + lait) retient l humidité dans les boulettes à la cuisson.', 1),
  ('Le Keftedes Me Saltsa', 'fill_in_blank', 'Saltsa signifie ___ en grec', '[]', 'sauce', 'Le mot saltsa vient de l italien salsa — la Grèce a été influencée par la cuisine italienne.', 2),
  ('Le Htipiti', 'multiple_choice', 'Que signifie htipiti en grec ?', '["Battu ou fouetté","Grillé","Fermenté","Séché au soleil"]', 'Battu ou fouetté', 'Le htipiti est fait en battant vigoureusement la feta avec les poivrons rôtis.', 1),
  ('Le Htipiti', 'fill_in_blank', 'Le htipiti est une ___ à base de feta et poivrons rôtis', '[]', 'tartinnade', 'Les tartinnades grecques (comme le tarama ou la skordalia) sont servies en mezze.', 2),
  ('Le Galatopita', 'multiple_choice', 'Que signifie gala en grec ?', '["Lait","Miel","Crème","Yaourt"]', 'Lait', 'Gala est le mot grec pour lait — la galatopita est littéralement une tarte au lait.', 1),
  ('Le Galatopita', 'fill_in_blank', 'Il faut laisser la galatopita ___ complètement avant de la découper', '[]', 'refroidir', 'La crème doit se figer en refroidissant pour que les parts soient nettes et se tiennent.', 2),
  ('Le Magiritsa', 'multiple_choice', 'Quand mange-t-on traditionnellement la magiritsa ?', '["À minuit après la messe de Pâques","Le matin de Pâques","Le Vendredi Saint","La veille de Noël"]', 'À minuit après la messe de Pâques', 'La magiritsa rompt le jeûne du Carême — elle est mangée après la messe de résurrection à minuit.', 1),
  ('Le Magiritsa', 'fill_in_blank', 'La sauce aux œufs et citron utilisée dans la magiritsa s appelle ___', '[]', 'avgolemono', 'L avgolemono est une technique grecque qui épaissit et acidifie les soupes et sauces.', 2)
) AS v(lesson_title, type, question, options, correct_answer, explanation, order_index)
JOIN public.lessons l ON l.title = v.lesson_title;
