-- Recipes for lessons 36-50: Mexican, Indian, Thai, Greek paths

-- ============================================================
-- RECIPES FOR MEXICAN LESSONS 36-50
-- ============================================================
INSERT INTO public.recipes (id, lesson_id, title, description, emoji, prep_time_min, cook_time_min, servings, difficulty, avg_price_eur, ingredients, instructions, chef_tip, cultural_note)
SELECT gen_random_uuid(), l.id, v.title, v.description, v.emoji, v.prep_time_min, v.cook_time_min, v.servings, v.difficulty, v.avg_price_eur, v.ingredients::jsonb, v.instructions::jsonb, v.chef_tip, v.cultural_note
FROM (VALUES
  ('Le Mole Negro d''Oaxaca', 'Mole noir profond aux piments carbonisés et chocolat amer sur volaille.', '🍫', 90, 120, 6, 'advanced', 14.0,
   '[{"qty":"1","item":"poulet entier coupé"},{"qty":"5","item":"piments chilhuacle negro séchés"},{"qty":"3","item":"piments mulato séchés"},{"qty":"50g","item":"chocolat noir 85%"},{"qty":"1","item":"tortilla brûlée"},{"qty":"30g","item":"cacahuètes"},{"qty":"30g","item":"graines de sésame"},{"qty":"2","item":"tomates"},{"qty":"4 gousses","item":"ail"},{"qty":"épices","item":"cannelle, thym, marjolaine"}]',
   '["Faites griller les piments à sec jusqu à noircissement léger — c''est voulu","Réhydratez 20 min dans l''eau chaude","Faites brûler la tortilla directement sur la flamme","Faites revenir tomates et ail à sec","Mixez piments, tortilla, tomates, ail, épices","Faites revenir la purée dans l''huile 10 min","Ajoutez bouillon peu à peu, remuez","Ajoutez chocolat, mijotez 30 min","Pochez le poulet dans le mole"]',
   'Les piments légèrement carbonisés donnent la couleur noire et l''amertume caractéristique du mole negro.', 'Le mole negro d''Oaxaca est considéré comme le plus complexe des sept moles oaxaqueños.'),
  ('Les Tlacoyos', 'Galettes ovales de masa bleue fourrées de haricots ou fèves, garnies de salsa.', '🫘', 30, 20, 4, 'intermediate', 5.0,
   '[{"qty":"300g","item":"masa harina de maïs bleu"},{"qty":"200ml","item":"eau tiède"},{"qty":"1 c.c.","item":"sel"},{"qty":"200g","item":"haricots noirs cuits et écrasés"},{"qty":"salsa verde","item":"pour servir"},{"qty":"fromage frais","item":"émietté"},{"qty":"cactus nopal","item":"cuit en dés"}]',
   '["Mélangez masa harina, eau et sel jusqu''à pâte souple","Prélevez des boules de 80g","Aplatissez en ovale, déposez une cuillère de haricots au centre","Refermez et reformez un ovale de 1cm d''épaisseur","Cuisez sur comal sec à feu moyen 4 min de chaque côté","Garnissez de salsa, fromage et nopal"]',
   'La masa doit être ni trop humide ni trop sèche — elle doit s''aplatir sans craquer.', 'Les tlacoyos sont vendus dans les marchés de Mexico City dès l''aube par les tlacoyeras.'),
  ('Le Caldo de Res', 'Bouillon copieux de bœuf aux légumes de saison — soupe du dimanche mexicain.', '🥩', 30, 120, 6, 'beginner', 9.0,
   '[{"qty":"800g","item":"jarret de bœuf"},{"qty":"2","item":"épis de maïs coupés en tronçons"},{"qty":"4","item":"carottes"},{"qty":"3","item":"courgettes"},{"qty":"1/4","item":"chou vert"},{"qty":"4 gousses","item":"ail"},{"qty":"1","item":"oignon"},{"qty":"épazote frais","item":"et coriandre"},{"qty":"citron vert","item":"et jalapeño pour servir"}]',
   '["Mettez le bœuf dans 3L d''eau froide, portez à ébullition","Écumez pendant 10 min","Ajoutez ail, oignon, sel","Cuisez 1h à feu moyen","Ajoutez maïs et carottes, cuisez 20 min","Ajoutez courgettes et chou, cuisez 15 min","Ajoutez l''épazote les 5 dernières minutes","Servez avec citron vert, jalapeño et tortillas"]',
   'Ne couvrez pas complètement la casserole pour que le bouillon reste limpide.', 'Le caldo de res est le plat dominical par excellence dans les foyers mexicains.'),
  ('La Tinga de Poulet', 'Effiloché de poulet dans une sauce tomate-chipotle — garniture versatile.', '🌶️', 20, 30, 4, 'beginner', 6.0,
   '[{"qty":"600g","item":"filets de poulet"},{"qty":"400g","item":"tomates concassées"},{"qty":"3","item":"piments chipotle en adobo"},{"qty":"1","item":"oignon émincé"},{"qty":"3 gousses","item":"ail"},{"qty":"1 c.c.","item":"origan"},{"qty":"sel","item":"et poivre"},{"qty":"2 c.s.","item":"huile"}]',
   '["Pochez le poulet 15 min, effilochez","Mixez tomates, chipotle, ail et 100ml d''eau de cuisson","Faites revenir l''oignon dans l''huile","Versez la sauce mixée, cuisez 5 min","Ajoutez le poulet effiloché","Mijotez 15 min jusqu''à sauce épaisse","Assaisonnez et servez dans des tostadas ou tacos"]',
   'Ajustez le chipotle selon votre goût — 2 piments pour piquant modéré, 4 pour intense.', 'La tinga est née à Puebla et est maintenant populaire dans tout le Mexique comme garniture polyvalente.'),
  ('Les Enchiladas Vertes', 'Tortillas farcies au poulet, nappées de salsa verde et crème fraîche.', '🌿', 30, 20, 4, 'intermediate', 7.0,
   '[{"qty":"12","item":"tortillas de maïs"},{"qty":"400g","item":"poulet effiloché cuit"},{"qty":"500g","item":"tomatilles"},{"qty":"2","item":"jalapeños"},{"qty":"1/2","item":"oignon"},{"qty":"2 gousses","item":"ail"},{"qty":"bouquet","item":"de coriandre"},{"qty":"200ml","item":"crème fraîche"},{"qty":"150g","item":"fromage frais émietté"}]',
   '["Faites rôtir tomatilles, jalapeños, oignon à sec","Mixez avec ail, coriandre et sel — salsa verde","Chauffez légèrement les tortillas dans une poêle","Farcissez de poulet, roulez","Disposez dans un plat, nappez généreusement de salsa verde","Arrosez de crème fraîche","Parsemez de fromage frais","Passez 10 min au four à 180°C"]',
   'Réchauffez les tortillas avant de les rouler — elles se plieront sans se déchirer.', 'Les enchiladas vertes sont un classique de la cuisine mexicaine quotidienne, verte de Guerrero.')
) AS v(lesson_title, title, description, emoji, prep_time_min, cook_time_min, servings, difficulty, avg_price_eur, ingredients, instructions, chef_tip, cultural_note)
JOIN public.lessons l ON l.title = v.lesson_title;

-- ============================================================
-- RECIPES FOR INDIAN LESSONS 36-50
-- ============================================================
INSERT INTO public.recipes (id, lesson_id, title, description, emoji, prep_time_min, cook_time_min, servings, difficulty, avg_price_eur, ingredients, instructions, chef_tip, cultural_note)
SELECT gen_random_uuid(), l.id, v.title, v.description, v.emoji, v.prep_time_min, v.cook_time_min, v.servings, v.difficulty, v.avg_price_eur, v.ingredients::jsonb, v.instructions::jsonb, v.chef_tip, v.cultural_note
FROM (VALUES
  ('Le Murgh Makhani', 'Poulet tandoori dans une sauce tomate-crème onctueuse — le butter chicken.', '🍗', 30, 40, 4, 'intermediate', 9.0,
   '[{"qty":"600g","item":"poulet en morceaux"},{"qty":"marinade:","item":""},{"qty":"150g","item":"yogourt"},{"qty":"1 c.s.","item":"garam masala"},{"qty":"1 c.c.","item":"piment rouge"},{"qty":"sauce makhani:","item":""},{"qty":"400g","item":"tomates concassées"},{"qty":"100ml","item":"crème liquide"},{"qty":"50g","item":"beurre"},{"qty":"1 c.s.","item":"kasuri methi (fenugrec séché)"},{"qty":"épices","item":"cardamome, cannelle, clou"}]',
   '["Marinez le poulet dans yogourt + épices au moins 2h","Faites griller au four à 220°C 15 min (ou poêle très chaude)","Faites revenir oignon dans le beurre","Ajoutez tomates, cuisez 10 min","Mixez, filtrez","Remettez dans la poêle avec crème et beurre","Ajoutez le poulet grillé","Kasuri methi en fin — le secret de l''authenticité"]',
   'Le kasuri methi (fenugrec séché) est l''ingrédient secret du butter chicken authentique.', 'Le murgh makhani a été inventé en 1948 au Moti Mahal de Delhi par Kundan Lal Gujral.'),
  ('Le Samosa Maison', 'Chaussons croustillants farcis aux pommes de terre épicées et petits pois.', '🥐', 45, 20, 4, 'intermediate', 5.0,
   '[{"qty":"pâte:","item":""},{"qty":"200g","item":"farine"},{"qty":"60ml","item":"huile"},{"qty":"eau","item":"froide"},{"qty":"farce:","item":""},{"qty":"4","item":"pommes de terre cuites écrasées"},{"qty":"100g","item":"petits pois"},{"qty":"1 c.c.","item":"cumin"},{"qty":"1 c.c.","item":"coriandre moulue"},{"qty":"1 c.c.","item":"amchur"},{"qty":"piment vert","item":"émincé"},{"qty":"huile","item":"pour friture"}]',
   '["Mélangez farine et huile jusqu''à texture sablée","Ajoutez eau froide pour une pâte ferme, reposez 30 min","Faites revenir épices à sec","Mélangez pommes de terre, petits pois, épices, amchur","Divisez la pâte en boules, abaissez en ovales","Coupez en deux, formez des cônes","Farcissez, scellez les bords avec de l''eau","Faites frire à 165°C 5-6 min jusqu''à dorés"]',
   'Faites frire à basse température (165°C) pour que la pâte cuise à l''intérieur avant de dorer.', 'Le samosa est originaire d''Asie centrale et arrivé en Inde avec les marchands persans au XIIIe siècle.'),
  ('Le Tandoori Murgh', 'Poulet mariné au yogourt et épices, cuit à haute température pour une char parfaite.', '🔥', 240, 25, 4, 'intermediate', 8.0,
   '[{"qty":"1","item":"poulet entier coupé en morceaux"},{"qty":"150g","item":"yogourt épais"},{"qty":"2 c.s.","item":"pâte gingembre-ail"},{"qty":"2 c.c.","item":"piment rouge Kashmir"},{"qty":"1 c.c.","item":"garam masala"},{"qty":"1 c.c.","item":"cumin"},{"qty":"jus","item":"de 1 citron"},{"qty":"2 c.s.","item":"huile"},{"qty":"colorant rouge","item":"optionnel"}]',
   '["Incisez le poulet profondément","Mélangez tous les ingrédients de marinade","Enduisez généreusement, incluant sous la peau","Marinez minimum 4h, idéalement 12h","Préchauffez le four à 240°C (maximum)","Posez sur grille, cuisez 20 min","Retournez et cuisez encore 5 min","Terminez sous le gril 2 min pour la char"]',
   'Les incisions profondes permettent à la marinade de pénétrer jusqu''à l''os — ne les négligez pas.', 'Le tandoor est un four en argile à 480°C — le four domestique est une approximation valide.'),
  ('Le Fish Curry de Goa', 'Curry de poisson à la noix de coco et tamarin — acidulé et parfumé.', '🐟', 20, 25, 4, 'intermediate', 8.0,
   '[{"qty":"600g","item":"filets de poisson ferme (cabillaud, vivaneau)"},{"qty":"400ml","item":"lait de coco"},{"qty":"2 c.s.","item":"pâte de curry Goan"},{"qty":"2 c.s.","item":"pâte de tamarin"},{"qty":"2","item":"tomates"},{"qty":"1","item":"oignon"},{"qty":"1 c.c.","item":"curcuma"},{"qty":"feuilles","item":"de curry"},{"qty":"huile de coco","item":"pour cuire"}]',
   '["Faites revenir oignon dans l''huile de coco","Ajoutez la pâte de curry, cuisez 2 min","Ajoutez tomates et curcuma","Versez le lait de coco et tamarin, portez à ébullition","Ajoutez les feuilles de curry","Déposez le poisson délicatement","Cuisez 8-10 min à feu doux — le poisson doit être nacré","Servez avec du riz basmati"]',
   'Ne remuez pas trop le poisson — il se défait facilement. Inclinez la casserole pour l''arroser.', 'Goa, ancienne colonie portugaise, a une cuisine unique qui mélange influences indiennes et européennes.'),
  ('Le Malai Kofta', 'Boulettes de paneer et pommes de terre dans une sauce makhani dorée et crémeuse.', '🧀', 45, 30, 4, 'advanced', 8.0,
   '[{"qty":"koftas:","item":""},{"qty":"200g","item":"paneer râpé"},{"qty":"200g","item":"pommes de terre cuites"},{"qty":"2 c.s.","item":"farine"},{"qty":"épices","item":"garam masala, sel"},{"qty":"noix de cajou","item":"et raisins secs"},{"qty":"sauce:","item":""},{"qty":"2","item":"oignons"},{"qty":"3","item":"tomates"},{"qty":"100ml","item":"crème"},{"qty":"épices","item":"cardamome, cannelle, safran"}]',
   '["Mélangez paneer, pommes de terre, farine et épices","Farcissez de cajou et raisins, formez des boulettes","Faites frire à 170°C 4 min jusqu''à dorées","Mixez oignons + tomates, faites revenir","Ajoutez crème et épices, mijotez 10 min","Infusez le safran dans 2 c.s. d''eau chaude","Incorporez au moment de servir","Déposez les koftas dans la sauce chaude"]',
   'Ajoutez les koftas dans la sauce juste avant de servir — sinon ils absorbent la sauce et ramollissent.', 'Le malai kofta est un plat de fête Mughal servi lors des occasions spéciales en Inde du Nord.')
) AS v(lesson_title, title, description, emoji, prep_time_min, cook_time_min, servings, difficulty, avg_price_eur, ingredients, instructions, chef_tip, cultural_note)
JOIN public.lessons l ON l.title = v.lesson_title;

-- ============================================================
-- RECIPES FOR THAI LESSONS 36-50
-- ============================================================
INSERT INTO public.recipes (id, lesson_id, title, description, emoji, prep_time_min, cook_time_min, servings, difficulty, avg_price_eur, ingredients, instructions, chef_tip, cultural_note)
SELECT gen_random_uuid(), l.id, v.title, v.description, v.emoji, v.prep_time_min, v.cook_time_min, v.servings, v.difficulty, v.avg_price_eur, v.ingredients::jsonb, v.instructions::jsonb, v.chef_tip, v.cultural_note
FROM (VALUES
  ('Le Pad Krapow Moo', 'Porc haché sauté au basilic sacré et œuf frit — plat national thaï.', '🌿', 10, 10, 2, 'beginner', 6.0,
   '[{"qty":"300g","item":"porc haché"},{"qty":"grande poignée","item":"de basilic sacré (krapow)"},{"qty":"3 gousses","item":"ail"},{"qty":"2","item":"piments rouges thaïs"},{"qty":"2 c.s.","item":"sauce huître"},{"qty":"1 c.s.","item":"sauce poisson"},{"qty":"1 c.c.","item":"sucre de palme"},{"qty":"2","item":"œufs"},{"qty":"huile","item":"pour friture"}]',
   '["Chauffez le wok à feu très vif","Faites frire les œufs dans beaucoup d''huile — bords croustillants","Réservez","Dans la même huile, faites revenir ail et piments","Ajoutez le porc, cuisez à feu vif","Assaisonnez sauce huître, sauce poisson, sucre","Ajoutez le basilic sacré hors feu — il noircit vite","Servez sur riz blanc avec l''œuf frit sur le dessus"]',
   'Le basilic sacré krapow est différent du basilic thaï — son arôme poivré est irremplaçable.', 'Le pad krapow est le plat comfort food des Thaïlandais — disponible partout à toute heure.'),
  ('Le Som Tum', 'Salade de papaye verte écrasée au mortier — piquante, acidulée et croquante.', '🥗', 15, 0, 2, 'beginner', 5.0,
   '[{"qty":"300g","item":"papaye verte râpée"},{"qty":"2","item":"piments rouges thaïs"},{"qty":"2 gousses","item":"ail"},{"qty":"50g","item":"haricots verts coupés"},{"qty":"2","item":"tomates cerises"},{"qty":"30g","item":"cacahuètes grillées"},{"qty":"2 c.s.","item":"sauce poisson"},{"qty":"1 c.s.","item":"jus de citron vert"},{"qty":"1 c.c.","item":"sucre de palme"},{"qty":"crevettes séchées","item":"au goût"}]',
   '["Écrasez les piments et l''ail au mortier","Ajoutez crevettes séchées, écrasez légèrement","Ajoutez haricots verts, écrasez pour les attendrir","Ajoutez papaye râpée, sauce poisson, citron vert, sucre","Mélangez en écrasant et retournant — tout doit être parfumé","Ajoutez tomates cerises, écrasez légèrement","Garnissez de cacahuètes","Goûtez et ajustez l''équilibre des 4 saveurs"]',
   'Le som tum se prépare commande par commande au mortier — fait en avance, il perd son croquant.', 'Le som tum est le plat de rue le plus vendu en Thaïlande, particulièrement dans les régions du nord-est.'),
  ('Le Khao Man Gai', 'Poulet poché, riz cuit dans le bouillon de poulet, sauce au gingembre et soja.', '🍚', 10, 50, 4, 'beginner', 7.0,
   '[{"qty":"1","item":"poulet entier"},{"qty":"400g","item":"riz jasmin"},{"qty":"5cm","item":"gingembre frais"},{"qty":"4 gousses","item":"ail"},{"qty":"sauce:","item":""},{"qty":"3 c.s.","item":"sauce soja noire"},{"qty":"2 c.s.","item":"gingembre émincé"},{"qty":"1 c.s.","item":"ail écrasé"},{"qty":"1 c.s.","item":"vinaigre de riz"},{"qty":"1 c.c.","item":"sucre"}]',
   '["Plongez le poulet dans 3L d''eau froide avec gingembre et ail","Portez doucement à ébullition, cuisez 30 min à frémissement","Retirez le poulet, laissez reposer","Récupérez 2 tasses de bouillon","Cuisez le riz dans ce bouillon avec un peu d''ail frit","Mélangez les ingrédients de sauce","Découpez le poulet en tranches","Servez avec le riz, bouillon clair et sauce"]',
   'Le secret du khao man gai est la qualité du poulet — fermier, il donnera un bouillon exceptionnel.', 'Le khao man gai est inspiré du Hainanese chicken rice de Singapour, adapté aux goûts thaïlandais.'),
  ('La Tom Kha Gai', 'Soupe de poulet au lait de coco, galanga et citronelle — douce et parfumée.', '🥥', 15, 20, 4, 'beginner', 7.0,
   '[{"qty":"400g","item":"poulet en tranches"},{"qty":"400ml","item":"lait de coco"},{"qty":"200ml","item":"bouillon de poulet"},{"qty":"3 tranches","item":"de galanga frais"},{"qty":"2 tiges","item":"de citronnelle"},{"qty":"5","item":"feuilles de combava"},{"qty":"200g","item":"champignons shiitake"},{"qty":"2 c.s.","item":"sauce poisson"},{"qty":"jus","item":"de 1-2 citrons verts"},{"qty":"piments","item":"et coriandre pour servir"}]',
   '["Portez bouillon et lait de coco à ébullition","Ajoutez galanga, citronnelle (écrasée), feuilles de combava","Laissez infuser 5 min à feu doux","Ajoutez le poulet et champignons","Cuisez 10 min jusqu''à poulet cuit","Assaisonnez avec sauce poisson","Ajoutez jus de citron vert hors feu","Servez avec piments et coriandre"]',
   'Le galanga et la citronnelle sont pour l''arôme uniquement — on ne les mange pas.', 'La tom kha est moins connue que la tom yum mais ses fans la considèrent plus sophistiquée.'),
  ('Le Pla Pao', 'Poisson entier grillé sur charbon avec sel gemme et herbes dans le ventre.', '🐟', 20, 20, 2, 'intermediate', 9.0,
   '[{"qty":"1","item":"poisson entier (daurade ou bar — 500g)"},{"qty":"gros sel","item":"gemme"},{"qty":"3 tiges","item":"de citronnelle"},{"qty":"feuilles","item":"de combava"},{"qty":"sauce dip:","item":""},{"qty":"3 c.s.","item":"sauce poisson"},{"qty":"2 c.s.","item":"jus de citron vert"},{"qty":"piments","item":"et ail émincés"},{"qty":"échalotes","item":"émincées"},{"qty":"herbes fraîches","item":"coriandre, menthe"}]',
   '["Fendez le ventre du poisson, retirez les viscères","Farcissez de citronnelle et feuilles de combava","Enduisez le poisson de gros sel (une couche épaisse)","Préparez les braises — bois de charbon","Posez le poisson directement sur la grille","Grillez 10 min de chaque côté","La croûte de sel protège la chair","Retirez la croûte avant de servir","Servez avec la sauce dip et riz gluant"]',
   'Le gros sel forme une croûte protectrice qui garde la chair juteuse — ne le retirez qu''au moment de servir.', 'Le pla pao est la technique de cuisson traditionnelle des pêcheurs thaïlandais de la côte.')
) AS v(lesson_title, title, description, emoji, prep_time_min, cook_time_min, servings, difficulty, avg_price_eur, ingredients, instructions, chef_tip, cultural_note)
JOIN public.lessons l ON l.title = v.lesson_title;

-- ============================================================
-- RECIPES FOR GREEK LESSONS 36-50
-- ============================================================
INSERT INTO public.recipes (id, lesson_id, title, description, emoji, prep_time_min, cook_time_min, servings, difficulty, avg_price_eur, ingredients, instructions, chef_tip, cultural_note)
SELECT gen_random_uuid(), l.id, v.title, v.description, v.emoji, v.prep_time_min, v.cook_time_min, v.servings, v.difficulty, v.avg_price_eur, v.ingredients::jsonb, v.instructions::jsonb, v.chef_tip, v.cultural_note
FROM (VALUES
  ('La Saganaki', 'Fromage kefalograviera frit dans une poêle, flambé à l''ouzo — spectaculaire.', '🔥', 5, 5, 4, 'beginner', 7.0,
   '[{"qty":"300g","item":"fromage kefalograviera ou kasseri"},{"qty":"50g","item":"farine"},{"qty":"50ml","item":"huile d''olive"},{"qty":"50ml","item":"ouzo"},{"qty":"jus","item":"de citron"},{"qty":"pain","item":"pour accompagner"}]',
   '["Coupez le fromage en tranche de 1.5cm","Humidifiez légèrement, passez dans la farine","Chauffez l''huile dans une petite poêle en fonte","Posez le fromage, cuisez 2 min sans toucher","Retournez délicatement quand le dessous est doré","Cuisez encore 1 min","Versez l''ouzo chauffé et flambez devant les convives","Arrosez de jus de citron, servez immédiatement"]',
   'La poêle doit être très chaude avant d''ajouter le fromage — il doit saisir, pas fondre.', 'Saganaki vient du sagani (poêle à deux poignées) — le fromage frit est servi dedans au restaurant.'),
  ('Les Dolmades', 'Feuilles de vigne farcies au riz, herbes et citron — froid ou chaud.', '🍃', 60, 45, 6, 'intermediate', 6.0,
   '[{"qty":"40","item":"feuilles de vigne en saumure"},{"qty":"200g","item":"riz à grains ronds"},{"qty":"2","item":"oignons émincés"},{"qty":"bouquet","item":"de persil et aneth"},{"qty":"100ml","item":"huile d''olive"},{"qty":"jus","item":"de 2 citrons"},{"qty":"sel","item":"et poivre blanc"},{"qty":"avgolemono:","item":""},{"qty":"2","item":"œufs"},{"qty":"jus","item":"de 1 citron"}]',
   '["Rincez les feuilles de vigne, égouttez","Faites revenir oignon dans l''huile","Ajoutez riz, persil, aneth, sel, jus de 1 citron","Déposez 1 c.s. de farce sur chaque feuille","Roulez en cigare serré","Tapissez une casserole de feuilles","Disposez les dolmades serrés","Couvrez d''eau et huile, pesez avec une assiette","Cuisez 45 min à feu doux","Faites l''avgolemono: battez œufs + citron, incorporez bouillon chaud"]',
   'Serrez bien les dolmades dans la casserole pour qu''ils gardent leur forme à la cuisson.', 'Les dolmades (feuilles farcies) existent dans toute la région méditerranéenne orientale.'),
  ('La Spanakopita', 'Tourte feuilletée aux épinards, feta et aneth — la pâtisserie salée grecque par excellence.', '🥬', 30, 45, 8, 'intermediate', 7.0,
   '[{"qty":"500g","item":"épinards frais ou surgelés"},{"qty":"300g","item":"feta émiettée"},{"qty":"4","item":"œufs"},{"qty":"1","item":"oignon"},{"qty":"bouquet","item":"d''aneth frais"},{"qty":"noix de muscade","item":"râpée"},{"qty":"12 feuilles","item":"de phyllo"},{"qty":"150g","item":"beurre fondu"},{"qty":"graines","item":"de sésame"}]',
   '["Blanchissez les épinards, essorez très bien","Faites revenir l''oignon","Mélangez épinards, feta, œufs, aneth, muscade, oignon","Beurrez un grand plat","Disposez 6 feuilles de phyllo en badigeonnant de beurre","Étalez la farce","Couvrez de 6 feuilles de phyllo beurrées","Scarifiez en carrés","Saupoudrez de sésame","Enfournez à 180°C 40-45 min"]',
   'Les épinards doivent être très bien essorés — l''humidité ramollit le phyllo.', 'La spanakopita est vendue dans les boulangeries grecques dès le matin — un petit-déjeuner national.'),
  ('Le Bakaliaros Skordalia', 'Morue salée frite en pâte à beignet, accompagnée de skordalia à l''ail.', '🐟', 720, 20, 4, 'intermediate', 8.0,
   '[{"qty":"600g","item":"morue salée dessalée 24h"},{"qty":"pâte:","item":""},{"qty":"200g","item":"farine"},{"qty":"250ml","item":"bière blonde"},{"qty":"1 c.c.","item":"levure chimique"},{"qty":"skordalia:","item":""},{"qty":"4 tranches","item":"de pain de mie rassis"},{"qty":"6 gousses","item":"ail"},{"qty":"100ml","item":"huile d''olive"},{"qty":"jus","item":"de citron"}]',
   '["Dessalez la morue 24h en changeant l''eau toutes les 8h","Séchez, coupez en morceaux","Mélangez farine, bière, levure pour la pâte","Faites la skordalia: pain trempé+ail mixé+huile en filet+citron","Trempez la morue dans la pâte","Faites frire à 180°C jusqu''à dorée","Servez avec la skordalia et citron"]',
   'La skordalia doit être très aillée — c''est son caractère. Ajustez l''ail selon votre goût.', 'Le 25 mars (Fête Nationale) et le Vendredi Saint, le bakaliaros skordalia est mangé dans toute la Grèce.'),
  ('La Galaktoboureko', 'Flan de semoule dans une pâte phyllo, imbibé de sirop au citron.', '🍮', 30, 50, 8, 'intermediate', 5.0,
   '[{"qty":"12 feuilles","item":"de phyllo"},{"qty":"100g","item":"beurre fondu"},{"qty":"crème:","item":""},{"qty":"1L","item":"lait"},{"qty":"150g","item":"semoule fine"},{"qty":"150g","item":"sucre"},{"qty":"4","item":"œufs"},{"qty":"1","item":"gousse de vanille"},{"qty":"sirop:","item":""},{"qty":"300g","item":"sucre"},{"qty":"300ml","item":"eau"},{"qty":"zeste","item":"de citron"}]',
   '["Faites le sirop: sucre+eau+zeste, cuisez 5 min, refroidissez","Faites la crème: chauffez lait+vanille, ajoutez semoule en pluie, remuez jusqu''à épaississement, hors feu ajoutez œufs battus+sucre","Beurrez un plat, disposez 6 feuilles de phyllo beurrées","Versez la crème","Couvrez de 6 feuilles phyllo beurrées","Scarifiez le dessus","Enfournez 45 min à 175°C","Versez le sirop FROID sur la galaktoboureko CHAUDE"]',
   'La règle : sirop froid sur gâteau chaud OU sirop chaud sur gâteau froid — jamais chaud sur chaud.', 'La galaktoboureko est le dessert du dimanche par excellence dans les pâtisseries grecques.')
) AS v(lesson_title, title, description, emoji, prep_time_min, cook_time_min, servings, difficulty, avg_price_eur, ingredients, instructions, chef_tip, cultural_note)
JOIN public.lessons l ON l.title = v.lesson_title;
