-- Lessons 36-50: Chinese, Pastry, BBQ, Vegan paths (batch 6)

-- ==================== CHINESE ====================
INSERT INTO public.lessons (id, path_id, title, description, order_index, duration_min, difficulty, chef_tip, cultural_note, vocabulary)
SELECT gen_random_uuid(), p.id, v.title, v.description, v.order_index, v.duration_min, v.difficulty, v.chef_tip, v.cultural_note, v.vocabulary::jsonb
FROM (VALUES
  ('Le Porc Laqué de Pékin', 'La préparation du porc laqué, avec sa peau croustillante et sa chair tendre, est l''une des recettes les plus emblématiques de la cuisine chinoise.', 36, 60, 'advanced', 'Séchez bien la peau avant de laquer pour obtenir un croustillant parfait.', 'Le porc laqué de Pékin date de la dynasty Ming et était réservé à l''Empereur.', '[{"term":"laquer","definition":"enduire de sauce sucrée pour caraméliser"},{"term":"mandarin","definition":"crêpe fine servant à enrouler le porc"}]'),
  ('Les Xiaolongbao', 'Ces dumplings à la vapeur renferment un bouillon gélatineux qui devient liquide à la cuisson, créant une explosion de saveurs en bouche.', 37, 50, 'advanced', 'Faites figer le bouillon en gelée avant de farcir les dumplings.', 'Les xiaolongbao sont originaires de Shanghai et leur nom signifie "petit pain panier vapeur".', '[{"term":"xiaolongbao","definition":"dumpling vapeur avec bouillon intégré"},{"term":"aspic","definition":"bouillon gélifié utilisé pour la farce"}]'),
  ('Le Mapo Tofu', 'Ce plat du Sichuan allie tofu soyeux, porc haché et sauce pimentée au doubanjiang pour un résultat puissant en saveurs.', 38, 30, 'intermediate', 'Utilisez du poivre du Sichuan fraîchement moulu pour son effet anesthésiant caractéristique.', 'Le nom "mapo" signifie "vieille femme grêlée" en référence à la cuisinière qui aurait créé ce plat.', '[{"term":"doubanjiang","definition":"pâte de haricots fermentés pimentée"},{"term":"mala","definition":"saveur engourdissante et pimentée typique du Sichuan"}]'),
  ('Le Canard aux Huit Trésors', 'Ce plat festif consiste à farcir un canard entier avec un mélange de riz gluant, champignons, châtaignes et autres délices, puis à le cuire longuement.', 39, 90, 'advanced', 'Blanchissez le canard avant la cuisson pour éliminer les impuretés et raffermir la peau.', 'Ce plat est traditionnel lors du Nouvel An chinois, les "huit trésors" symbolisant la prospérité.', '[{"term":"riz gluant","definition":"riz à haute teneur en amidon qui colle à la cuisson"},{"term":"champignons shiitake","definition":"champignons séchés réhydratés, très parfumés"}]'),
  ('Le Char Siu', 'Ce porc rôti laqué cantonais se reconnaît à sa couleur rouge caractéristique et son glaçage sucré-salé. Il garnit de nombreux plats et buns.', 40, 45, 'intermediate', 'Laissez mariner le porc au moins 12h pour une pénétration maximale des saveurs.', 'Le char siu est l''une des viandes rôties les plus consommées à Hong Kong, vendue dans des boucheries spécialisées.', '[{"term":"char siu","definition":"porc rôti laqué cantonais"},{"term":"maltose","definition":"sucre utilisé pour le glaçage brillant du char siu"}]'),
  ('La Soupe Wonton', 'Des dumplings délicatement farcis de porc et de crevettes flottent dans un bouillon clair parfumé au gingembre et à la ciboulette.', 41, 35, 'beginner', 'Travaillez la pâte à wonton jusqu''à ce qu''elle soit très fine pour des dumplings translucides.', 'Les wontons sont consommés depuis plus de 1 000 ans en Chine, souvent lors du solstice d''hiver.', '[{"term":"wonton","definition":"dumpling à pâte fine typique de la cuisine cantonaise"},{"term":"bouillon dashi","definition":"bouillon clair à base d''os et d''aromates"}]'),
  ('Le Poulet Kung Pao', 'Ce classique du Sichuan marie poulet sauté, cacahuètes, piments secs et sauce aigre-douce-pimentée dans un équilibre parfait.', 42, 25, 'intermediate', 'Faites revenir les piments secs jusqu''à ce qu''ils noircissent légèrement pour libérer toute leur saveur.', 'Le kung pao doit son nom au gouverneur Ding Baozhen dont le titre honorifique était "Kung Pao".', '[{"term":"kung pao","definition":"technique de sauté à feu vif avec piments et cacahuètes"},{"term":"veloutage","definition":"marinade à la fécule pour attendrir la viande"}]'),
  ('Les Rouleaux de Printemps Frais', 'Ces rouleaux non frits enveloppent légumes croquants, vermicelles et crevettes dans une galette de riz translucide, servis avec sauce hoisin.', 43, 20, 'beginner', 'Trempez les galettes de riz une par une et travaillez rapidement avant qu''elles ne collent.', 'Les rouleaux de printemps frais sont typiques du Guangdong et sont servis lors du repas Yum Cha.', '[{"term":"galette de riz","definition":"feuille translucide à base de farine de riz réhydratée"},{"term":"vermicelle de riz","definition":"nouille fine à base de farine de riz"}]'),
  ('Le Bœuf au Brocoli', 'Un grand classique de la cuisine sino-américaine: lamelles de bœuf tendres, brocolis croquants et sauce aux huîtres brillante.', 44, 20, 'beginner', 'Blanchissez le brocoli 1 minute avant de sauter pour garder son croquant et sa couleur verte.', 'Ce plat est plus populaire aux États-Unis qu''en Chine, adapté aux goûts occidentaux par la diaspora chinoise.', '[{"term":"sauce aux huîtres","definition":"condiment épais et savoureux à base d''huîtres fermentées"},{"term":"veloutage","definition":"technique de marinade à la fécule pour attendrir la viande"}]'),
  ('Le Riz Cantonais', 'Ce riz sauté emblématique marie riz cuit de la veille, œufs, petits pois, carottes, crevettes et jambon dans une préparation rapide et savoureuse.', 45, 15, 'beginner', 'Utilisez impérativement du riz cuit la veille et refroidi pour éviter un riz pâteux.', 'Le riz cantonais est né à Canton (Guangzhou) et s''est répandu dans le monde entier avec la diaspora.', '[{"term":"wok hei","definition":"saveur fumée et légèrement brûlée caractéristique du wok à haute température"},{"term":"riz long grain","definition":"variété de riz dont les grains restent séparés après cuisson"}]'),
  ('Les Dim Sum Cheung Fun', 'Ces rouleaux de riz cuits à la vapeur, farcis de crevettes ou de bœuf, sont nappés de sauce soja sucrée et d''huile de sésame.', 46, 40, 'advanced', 'La pâte doit être très liquide et étalée en couche ultra-fine sur la plaque huilée.', 'Le cheung fun est incontournable dans le Yum Cha, tradition de déjeuner cantonais autour de thé et dim sum.', '[{"term":"cheung fun","definition":"rouleau de pâte de riz vapeur farci"},{"term":"yum cha","definition":"tradition cantonaise de thé et dim sum en famille"}]'),
  ('Le Congee de Poulet', 'Cette bouillie de riz crémeuse cuite lentement avec bouillon de poulet est le comfort food par excellence en Chine, garnie de gingembre et ciboulette.', 47, 60, 'beginner', 'Plus la cuisson est longue, plus le congee sera crémeux et savoureux.', 'Le congee est consommé depuis des millénaires comme remède et nourriture réconfortante lors des maladies.', '[{"term":"congee","definition":"bouillie de riz très cuite typique de l''Asie"},{"term":"gingembre frais","definition":"rhizome utilisé pour ses propriétés digestives et son piquant"}]'),
  ('Le Bao au Porc Rôti', 'Ces petits pains moelleux cuits à la vapeur, farcis de char siu, sont l''un des emblèmes de la boulangerie chinoise et du Yum Cha.', 48, 55, 'intermediate', 'Laissez lever les bao deux fois pour obtenir une texture ultra-moelleuse.', 'Les bao sont vendus dans des boulangeries cantonaises (boulangeries dim sum) depuis des siècles.', '[{"term":"bao","definition":"petit pain vapeur à la farine de blé fermentée"},{"term":"levée","definition":"temps de repos permettant à la pâte de doubler de volume"}]'),
  ('Le Poulet à la Sauce Noire', 'Ce plat cantonais classique marie des morceaux de poulet sautés avec poivrons et une sauce aux haricots noirs fermentés très parfumée.', 49, 25, 'intermediate', 'Rincez légèrement les haricots noirs fermentés avant usage pour atténuer leur salinité.', 'Les haricots noirs fermentés (douchi) sont l''un des condiments les plus anciens de la gastronomie chinoise.', '[{"term":"douchi","definition":"haricots noirs fermentés très salés et parfumés"},{"term":"wok","definition":"poêle bombée en acier utilisée pour la cuisson à haute température"}]'),
  ('La Fondue Chinoise Hot Pot', 'Ce repas convivial autour d''un bouillon frémissant où chacun cuit ses propres viandes, légumes et tofu est un rituel social profondément ancré dans la culture chinoise.', 50, 30, 'beginner', 'Préparez deux bouillons de saveurs différentes (épicé et neutre) pour satisfaire tous les goûts.', 'Le hot pot remonte à plus de 1 000 ans et est particulièrement populaire en hiver dans toute l''Asie.', '[{"term":"hot pot","definition":"bouillon frémissant partagé pour cuire les aliments à table"},{"term":"tahini","definition":"pâte de sésame utilisée comme trempette pour le hot pot"}]')
) AS v(title, description, order_index, duration_min, difficulty, chef_tip, cultural_note, vocabulary)
CROSS JOIN (SELECT id FROM public.paths WHERE slug='chinese' LIMIT 1) p;

-- ==================== PASTRY ====================
INSERT INTO public.lessons (id, path_id, title, description, order_index, duration_min, difficulty, chef_tip, cultural_note, vocabulary)
SELECT gen_random_uuid(), p.id, v.title, v.description, v.order_index, v.duration_min, v.difficulty, v.chef_tip, v.cultural_note, v.vocabulary::jsonb
FROM (VALUES
  ('La Tarte au Citron Meringuée', 'Un grand classique de la pâtisserie française: une pâte sablée croustillante, une crème au citron acidulée et une meringue dorée et moelleuse.', 36, 70, 'intermediate', 'Précuisez à blanc la pâte pour éviter qu''elle ne ramollisse sous la crème.', 'La tarte au citron meringuée est née aux États-Unis au XIXe siècle avant d''être adoptée par la pâtisserie française.', '[{"term":"crème au citron","definition":"crème cuite à base de jus de citron, œufs et beurre"},{"term":"meringue italienne","definition":"meringue à base de sirop de sucre cuit qui la stabilise"}]'),
  ('Le Saint-Honoré', 'Ce gâteau élaboré associe pâte feuilletée, pâte à choux, choux glacés au caramel et crème Chiboust ou chantilly dans un chef-d''œuvre technique.', 37, 120, 'advanced', 'Travaillez le caramel rapidement: il durcit en quelques secondes et peut brûler.', 'Le Saint-Honoré doit son nom au saint patron des boulangers et pâtissiers, célébré le 16 mai.', '[{"term":"crème Chiboust","definition":"crème pâtissière allégée à la meringue italienne"},{"term":"chouquette","definition":"petit chou non farci recouvert de sucre perlé"}]'),
  ('Le Fraisier', 'Ce gâteau estival emblématique alterne génoise moelleuse, mousseline à la vanille et fraises fraîches disposées en décoration élégante.', 38, 90, 'intermediate', 'Imbibez bien la génoise de sirop pour éviter qu''elle ne soit sèche.', 'Le fraisier moderne a été popularisé par Gaston Lenôtre dans les années 1960, devenant un classique des fêtes.', '[{"term":"mousseline","definition":"crème pâtissière montée au beurre pour plus de légèreté"},{"term":"génoise","definition":"biscuit moelleux à base d''œufs entiers montés avec le sucre"}]'),
  ('L''Opéra', 'Ce gâteau au café et chocolat très sophistiqué superpose biscuit joconde, ganache chocolat, crème au beurre café et miroir chocolat.', 39, 120, 'advanced', 'Veillez à ce que chaque couche soit bien lisse avant d''ajouter la suivante.', 'L''Opéra a été créé en 1955 par Cyriaque Gavillon chez Dalloyau, inspiré par la façade de l''Opéra Garnier.', '[{"term":"biscuit joconde","definition":"biscuit aux amandes très fin utilisé dans les entremets"},{"term":"ganache","definition":"mélange de chocolat fondu et de crème pour napper ou garnir"}]'),
  ('Le Kouign-Amann', 'Cette spécialité bretonne est une pâte levée feuilletée caramélisée, beurrée et sucrée à l''extrême, croustillante dehors et fondante dedans.', 40, 90, 'intermediate', 'Ne lésinez pas sur le beurre et le sucre: c''est le secret du kouign-amann authentique.', 'Le kouign-amann ("gâteau au beurre" en breton) a été créé à Douarnenez en 1860 par le boulanger Yves-René Scordia.', '[{"term":"feuilletage","definition":"technique de laminage du beurre dans la pâte pour créer des couches"},{"term":"caramélisation","definition":"transformation du sucre sous l''effet de la chaleur"}]'),
  ('Les Macarons Parisiens', 'Ces délicates coques de meringue à la farine d''amandes, collées par une ganache ou crème, sont le symbole de la haute pâtisserie française.', 41, 80, 'advanced', 'Laissez croûter les coques 30 minutes avant cuisson pour obtenir la collerette caractéristique.', 'Le macaron parisien a été popularisé par Ladurée au début du XXe siècle, bien distinct des macarons anciens.', '[{"term":"tant-pour-tant","definition":"mélange égal de farine d''amandes et sucre glace"},{"term":"macaronage","definition":"technique de mélange pour obtenir la texture parfaite des coques"}]'),
  ('La Tarte Bourdaloue', 'Cette tarte classique associe une pâte sablée, une crème frangipane parfumée à la vanille et des poires pochées dans un sirop léger.', 42, 60, 'intermediate', 'Pochez les poires dans un sirop vanillé pour les parfumer délicatement.', 'La tarte Bourdaloue doit son nom à la rue parisienne où un pâtissier du XIXe siècle l''aurait créée.', '[{"term":"frangipane","definition":"crème d''amandes mélangée à de la crème pâtissière"},{"term":"poire pochée","definition":"poire cuite doucement dans un sirop aromatisé"}]'),
  ('Le Paris-Brest Revisité', 'Une relecture moderne du classique: pâte à choux crousteline, pralinée feuilletée et crème mousseline praliné pour un équilibre entre tradition et innovation.', 43, 90, 'advanced', 'La crousteline (craquelin) posée sur les choux avant cuisson donne un aspect et croquant unique.', 'Le Paris-Brest original fut créé en 1910 par Louis Durand en hommage à la course cycliste du même nom.', '[{"term":"craquelin","definition":"couche croustillante posée sur les choux avant cuisson"},{"term":"praliné feuilleté","definition":"praliné mélangé à des crêpes dentelles émiettées"}]'),
  ('La Bûche de Noël', 'Ce dessert emblématique des fêtes françaises se compose d''une génoise roulée garnie de crème au beurre et décorée façon tronc d''arbre.', 44, 90, 'intermediate', 'Roulez la génoise encore chaude pour éviter qu''elle ne se fissure.', 'La bûche de Noël commémore l''ancienne tradition de brûler une vraie bûche dans la cheminée la nuit de Noël.', '[{"term":"roulade","definition":"génoise imbibée et garnie puis roulée sur elle-même"},{"term":"crème au beurre","definition":"mélange de beurre et de meringue ou crème pâtissière très riche"}]'),
  ('La Tarte Tropézienne', 'Cette brioche moelleuse fourrée d''une crème légère mêlant pâtissière et mousseline, parfumée à la fleur d''oranger, est la spécialité ensoleillée de Saint-Tropez.', 45, 80, 'intermediate', 'La recette originale de la crème reste secrète; la fleur d''oranger est sa signature.', 'La Tropézienne fut créée en 1955 par le pâtissier polonais Alexandre Micka et renommée par Brigitte Bardot.', '[{"term":"crème diplomatique","definition":"mélange de crème pâtissière et crème fouettée"},{"term":"fleur d''oranger","definition":"eau distillée des fleurs d''oranger, parfum signature de la Tropézienne"}]'),
  ('Le Mille-Feuille Revisité', 'La version contemporaine aligne feuilletage inversé caramélisé, crème légère vanille Bourbon et finition au sucre glace ou caramel.', 46, 90, 'advanced', 'Le feuilletage inversé (beurre à l''extérieur) donne un feuilletage plus croustillant et régulier.', 'Le mille-feuille, connu en anglais comme "Napoleon", est l''un des gâteaux les plus anciens de la pâtisserie française.', '[{"term":"feuilletage inversé","definition":"variante où le beurre entoure la détrempe pour plus de croustillant"},{"term":"fondant","definition":"glaçage à base de sucre cuit utilisé pour le dessus du mille-feuille classique"}]'),
  ('Le Soufflé au Grand Marnier', 'Ce dessert aérien et spectaculaire demande précision et rapidité: un soufflé ne s''attend pas et doit être servi dès la sortie du four.', 47, 40, 'advanced', 'Beurrez et sucrez parfaitement le moule et ne jamais ouvrir le four pendant la cuisson.', 'Le soufflé a été mis au point au XVIIIe siècle et reste le test ultime du savoir-faire pâtissier.', '[{"term":"soufflé","definition":"préparation gonflée à la cuisson grâce aux blancs en neige"},{"term":"base pâtissière","definition":"crème épaisse qui sert de base et donne la saveur au soufflé"}]'),
  ('La Tarte Tatin au Pamplemousse', 'Une relecture agrumée de la Tatin classique: pamplemousse rose caramélisé, pâte feuilletée croustillante et pointe de romarin pour une sophistication inattendue.', 48, 50, 'intermediate', 'Caramélisez à sec sans remuer pour un caramel homogène et éviter la cristallisation.', 'La Tatin classique aux pommes fut accidentellement créée par les sœurs Tatin en 1898 à Lamotte-Beuvron.', '[{"term":"caramel à sec","definition":"caramel fait sans eau, directement avec du sucre fondu"},{"term":"pâte feuilletée inversée","definition":"variante de feuilletage très croustillante idéale pour la Tatin"}]'),
  ('Le Gâteau Basque', 'Ce gâteau traditionnel du Pays Basque emprisonne une crème pâtissière à la vanille ou une confiture de cerises noires dans une pâte sablée dorée.', 49, 65, 'intermediate', 'Tracez le motif basque traditionnel sur le dessus avant d''enfourner.', 'Le gâteau basque est produit depuis le XVIIe siècle à Cambo-les-Bains et possède sa propre fête annuelle.', '[{"term":"crème pâtissière","definition":"crème cuite à base de lait, œufs, sucre et farine"},{"term":"cerises noires d''Itxassou","definition":"variété locale basque utilisée dans la confiture traditionnelle"}]'),
  ('La Charlotte aux Framboises', 'Ce dessert d''assemblage élégant tapisse un moule de biscuits à la cuillère et le garnit d''une bavaroise légère aux framboises fraîches.', 50, 60, 'intermediate', 'Imbibez délicatement les biscuits sans les détremper pour maintenir la structure.', 'La charlotte doit son nom à la reine Charlotte, épouse du roi George III d''Angleterre, grande amatrice de desserts.', '[{"term":"bavaroise","definition":"mousse légère à base de crème anglaise, gélatine et crème fouettée"},{"term":"biscuit à la cuillère","definition":"biscuit léger en forme d''allumette utilisé pour tapisser la charlotte"}]')
) AS v(title, description, order_index, duration_min, difficulty, chef_tip, cultural_note, vocabulary)
CROSS JOIN (SELECT id FROM public.paths WHERE slug='pastry' LIMIT 1) p;

-- ==================== BBQ ====================
INSERT INTO public.lessons (id, path_id, title, description, order_index, duration_min, difficulty, chef_tip, cultural_note, vocabulary)
SELECT gen_random_uuid(), p.id, v.title, v.description, v.order_index, v.duration_min, v.difficulty, v.chef_tip, v.cultural_note, v.vocabulary::jsonb
FROM (VALUES
  ('Le Brisket de Texas', 'La poitrine de bœuf fumée lentement pendant 12 à 18 heures est le roi du BBQ texan: un anneau de fumée rose, une croûte noire et une chair qui fond.', 36, 90, 'advanced', 'La règle des 160°F: enveloppez dans du papier boucher quand la température interne atteint 74°C.', 'Le brisket texan est originaire des traditions de fumage des bouchers juifs et tchèques immigrés au Texas.', '[{"term":"bark","definition":"croûte noire et croustillante formée à la surface par le sel, le poivre et la fumée"},{"term":"stall","definition":"plateau de température autour de 74°C où la viande semble ne plus cuire"}]'),
  ('Les Ribs St. Louis Style', 'Ces côtes de porc avec l''extrémité carrée sont rubées, fumées, puis lacquées au BBQ sauce selon la méthode 3-2-1 pour une tendresse absolue.', 37, 360, 'intermediate', 'La méthode 3-2-1 (3h fumer, 2h enveloppé, 1h à la sauce) garantit des ribs qui tombent de l''os.', 'Le style St. Louis désigne une coupe précise qui uniformise les côtes pour une cuisson homogène.', '[{"term":"rub","definition":"mélange d''épices appliqué à sec sur la viande avant cuisson"},{"term":"méthode 3-2-1","definition":"technique de cuisson en trois phases pour des ribs tendres"}]'),
  ('Le Poulet Entier sur Canette', 'Cuire un poulet entier en position verticale sur une canette de bière au BBQ garantit une chair moelleuse et une peau croustillante grâce à la vapeur interne.', 38, 90, 'beginner', 'Utilisez une canette à moitié pleine pour que la vapeur parfume l''intérieur du poulet.', 'La technique "beer can chicken" est un classique du BBQ américain populaire depuis les années 1990.', '[{"term":"chaleur indirecte","definition":"cuisson à côté de la source de chaleur, non directement au-dessus"},{"term":"temps de repos","definition":"période après cuisson permettant aux jus de se redistribuer"}]'),
  ('Le Pulled Pork Carolina', 'L''épaule de porc fumée 10 heures puis effilochée, servie avec sauce vinaigre-poivre de Caroline du Nord, est l''emblème du BBQ des Carolines.', 39, 600, 'intermediate', 'Effilochez le porc quand il atteint 95°C interne avec deux fourchettes ou vos mains protégées.', 'Le BBQ des Carolines est le plus ancien des États-Unis, influencé par les techniques des Amérindiens Cherokees.', '[{"term":"pulled pork","definition":"porc effiloché après longue cuisson fumée"},{"term":"vinegar sauce","definition":"sauce acide à base de vinaigre typique des Carolines"}]'),
  ('Les Burnt Ends de Kansas City', 'Ces cubes de pointe de poitrine caramélisés une seconde fois dans la sauce BBQ sont considérés comme la "friandise" ultime du BBQ américain.', 40, 480, 'advanced', 'Les burnt ends doivent cuire une seconde fois après découpe pour que la sauce caramélise bien.', 'Les burnt ends de Kansas City sont si populaires qu''ils se vendent séparément dans les BBQ joints locaux.', '[{"term":"burnt ends","definition":"cubes de brisket recuits dans la sauce pour une caramélisation maximale"},{"term":"point","definition":"partie grasse du brisket utilisée spécifiquement pour les burnt ends"}]'),
  ('La Côte de Bœuf au Charbon de Bois', 'Cuire une côte de bœuf épaisse sur charbon de bois naturel à haute température, puis la laisser reposer, révèle une saveur qu''aucune autre cuisson ne peut reproduire.', 41, 30, 'intermediate', 'Remontez la viande à température ambiante 1 heure avant cuisson pour une cuisson homogène.', 'La cuisson au charbon de bois produit des temperatures dépassant 600°C, inatteignables au gaz.', '[{"term":"cuisson directe","definition":"cuisson directement au-dessus des braises"},{"term":"marque de gril","definition":"quadrillage visuel obtenu en tournant la viande à 45° sur le gril"}]'),
  ('Le Porc Effiloché à la Bière', 'L''épaule de porc mijotée dans la bière brune et les épices puis effilochée crée un plat généreux et réconfortant, parfait pour les grands repas.', 42, 240, 'beginner', 'Choisissez une bière brune maltée (stout ou porter) pour des notes caramélisées profondes.', 'L''association porc et bière est un classique des traditions culinaires germaniques et américaines.', '[{"term":"braisage","definition":"cuisson lente en milieu humide (bouillon, bière) à couvert"},{"term":"effilochage","definition":"technique de déchiquetage de la viande très cuite en fibres"}]'),
  ('Les Saucisses Fumées Maison', 'Fabriquer ses propres saucisses, les assaisonner, les emboîter dans des boyaux naturels et les fumer à basse temperature est la quintessence du charcutier-fumeur.', 43, 120, 'advanced', 'Maintenez la température de fumage en dessous de 80°C pour une saucisse juteuse et non sèche.', 'La fabrication de saucisses maison est un art millénaire, pérennisé par les communautés germaniques et polonaises aux USA.', '[{"term":"boyau naturel","definition":"intestin de porc ou mouton utilisé comme enveloppe de saucisse"},{"term":"fumage à froid","definition":"fumage à moins de 30°C pour parfumer sans cuire"}]'),
  ('Le Lamb Rack Méditerranéen au BBQ', 'Un carré d''agneau mariné aux herbes et ail grillé sur barbecue au charbon capte à la fois les saveurs du gril et la fraîcheur des herbes.', 44, 35, 'intermediate', 'Protégez les manchons avec du papier aluminium pour éviter qu''ils noircissent.', 'Le carré d''agneau grillé est un classique des tables méditerranéennes du Maghreb à la Grèce.', '[{"term":"manchon","definition":"extrémité de l''os d''agneau nettoyée pour une présentation élégante"},{"term":"marinade sèche","definition":"mélange d''épices sans liquide appliqué avant la cuisson"}]'),
  ('Le Salmon Cédré', 'Cuire un filet de saumon directement sur une planche de cèdre trempée imprègne le poisson d''un arôme boisé délicat tout en le protégeant des flammes directes.', 45, 25, 'beginner', 'Trempez la planche au moins 2 heures (idéalement toute la nuit) pour éviter qu''elle ne prenne feu.', 'Le cèdre plank salmon est originaire des nations autochtones du Pacifique Nord-Ouest américain.', '[{"term":"planche de cèdre","definition":"planche de bois utilisée comme support de cuisson au BBQ"},{"term":"fumage doux","definition":"fumage léger pour parfumer sans dominer la saveur du poisson"}]'),
  ('Les Légumes Grillés en Brochettes', 'Composer des brochettes de légumes colorés marinés et les griller sur braises vives révèle leur sucre naturel et crée des saveurs caramélisées insoupçonnées.', 46, 20, 'beginner', 'Faites tremper les piques en bois 30 minutes dans l''eau pour éviter qu''ils ne brûlent.', 'Les brochettes de légumes grillés sont universelles, des yakitori japonais aux brochettes marocaines.', '[{"term":"caramélisation","definition":"transformation des sucres naturels sous l''effet de la chaleur"},{"term":"marinade","definition":"préparation liquide aromatique pour imprégner et attendrir les aliments"}]'),
  ('Le Smokehouse Mac and Cheese', 'Le gratin de macaronis enrichi de fromages fumés et fini au BBQ acquiert une profondeur de saveur fumée impossible à reproduire au four traditionnel.', 47, 45, 'intermediate', 'Utilisez un mélange de cheddar fumé et gruyère pour une sauce cheese optimale.', 'Le mac and cheese au BBQ est un side dish incontournable des compétitions de BBQ americaines.', '[{"term":"roux","definition":"mélange de beurre et farine cuits servant de base à la béchamel"},{"term":"side dish","definition":"accompagnement servi à côté de la viande principale au BBQ"}]'),
  ('Les Ailes de Poulet Buffalo', 'Ces ailes de poulet frites ou grillées, nappées de sauce piquante au beurre, sont l''en-cas BBQ américain par excellence, servies avec sauce bleu fromage.', 48, 30, 'beginner', 'Séchez bien les ailes avant cuisson pour une peau ultra-croustillante.', 'La sauce Buffalo originale a été créée en 1964 au Anchor Bar de Buffalo, New York, par Teressa Bellissimo.', '[{"term":"buffalo sauce","definition":"sauce piquante à base de Frank''s RedHot et beurre fondu"},{"term":"blue cheese dip","definition":"sauce crémeuse au fromage bleu typique accompagnement des wings"}]'),
  ('Le Porc Mariné à la Coréenne (Bulgogi))', 'Ce porc mariné dans la poire asiatique, sauce soja, gochujang et sésame, grillé sur braises, est l''un des BBQ les plus populaires d''Asie.', 49, 25, 'intermediate', 'La poire asiatique attendrit la viande naturellement grâce à ses enzymes.', 'Le BBQ coréen (gogi-gui) est une expérience sociale où l''on grill à table, entouré de banchan.', '[{"term":"gochujang","definition":"pâte de piment fermentée coréenne, épicée et légèrement sucrée"},{"term":"banchan","definition":"petits plats d''accompagnement servis dans la cuisine coréenne"}]'),
  ('Le Bœuf Wagyu à la Braise', 'Un steak de bœuf wagyu, grillé rapidement sur braises très chaudes pour ne pas fondre le précieux gras marbré, révèle une richesse et onctuosité incomparables.', 50, 15, 'advanced', 'Le wagyu se cuit toujours à point ou saignant: la cuisson prolongée détruit le marbrage unique.', 'Le bœuf wagyu est élevé selon des normes extrêmement strictes au Japon, certains atteignant 12 sur 12 au score BMS.', '[{"term":"marbrage","definition":"infiltrations de gras dans le muscle qui donnent au wagyu sa texture fondante"},{"term":"BMS","definition":"Beef Marbling Score, échelle de 1 à 12 mesurant la qualité du marbrage wagyu"}]')
) AS v(title, description, order_index, duration_min, difficulty, chef_tip, cultural_note, vocabulary)
CROSS JOIN (SELECT id FROM public.paths WHERE slug='bbq' LIMIT 1) p;

-- ==================== VEGAN ====================
INSERT INTO public.lessons (id, path_id, title, description, order_index, duration_min, difficulty, chef_tip, cultural_note, vocabulary)
SELECT gen_random_uuid(), p.id, v.title, v.description, v.order_index, v.duration_min, v.difficulty, v.chef_tip, v.cultural_note, v.vocabulary::jsonb
FROM (VALUES
  ('Le Seitan Maison', 'Préparer son propre seitan à partir de farine de blé lavée révèle un "steak végétal" protéiné, avec une texture fibreuse proche de la viande.', 36, 60, 'intermediate', 'Pétrissez longuement puis rincez la pâte sous l''eau froide jusqu''à ce que l''eau soit claire.', 'Le seitan est utilisé en cuisine bouddhiste depuis plus de 1 000 ans en Asie du Est comme substitut à la viande.', '[{"term":"gluten de blé","definition":"protéine élastique du blé qui forme la structure du seitan"},{"term":"lavage de la pâte","definition":"technique de rinçage qui élimine l''amidon pour ne garder que le gluten"}]'),
  ('Le Bowl de Buddha', 'Ce bol complet associe grains, protéines végétales, légumes rôtis et sauce tahini pour un repas équilibré et coloré qui nourrit corps et âme.', 37, 30, 'beginner', 'Variez les grains (quinoa, riz brun, farro) et les sources protéiques pour ne jamais vous lasser.', 'Le "Buddha bowl" doit son nom aux bols ronds qui rappellent le ventre rond et serein de Bouddha.', '[{"term":"tahini","definition":"pâte de sésame torréfié, riche en protéines et graisses saines"},{"term":"protéines végétales","definition":"sources de protéines d''origine végétale: légumineuses, tofu, tempeh"}]'),
  ('Le Fromage de Cajou', 'En trempant et mixant des cajous avec levure nutritionnelle et probiotiques, on obtient un fromage vegan crémeux surprenant de réalisme.', 38, 20, 'intermediate', 'Laissez fermenter à température ambiante 24-48h pour développer des saveurs complexes.', 'Le fromage végétal à base de noix est au cœur du mouvement vegan depuis les années 2000, copiant les techniques fromagères traditionnelles.', '[{"term":"levure nutritionnelle","definition":"levure inactivée au goût fromager et umami, très utilisée en cuisine vegan"},{"term":"fermentation","definition":"transformation par des micro-organismes qui développe les saveurs"}]'),
  ('Le Tempeh Grillé Teriyaki', 'Le tempeh, soja fermenté d''origine indonésienne, mariné en sauce teriyaki et grillé, offre une texture ferme et un goût umami satisfaisant.', 39, 25, 'beginner', 'Faites bouillir le tempeh 10 minutes avant marinade pour atténuer son amertume naturelle.', 'Le tempeh est l''aliment traditionnel indonésien par excellence, consommé à Java depuis des siècles.', '[{"term":"tempeh","definition":"soja fermenté sous forme de bloc compact, riche en protéines et probiotiques"},{"term":"umami","definition":"cinquième saveur fondamentale: goût savoureux et profond"}]'),
  ('La Quiche Lorraine Vegan', 'Reproduire la texture soyeuse d''une quiche sans œufs ni crème grâce au tofu soyeux et à la farine de pois chiche est un défi relevé avec brio.', 40, 55, 'intermediate', 'Ajoutez du kala namak (sel noir indien) pour reproduire l''arôme soufré des œufs.', 'Le kala namak est le secret des cuisiniers vegans pour singer les arômes caractéristiques des œufs.', '[{"term":"tofu soyeux","definition":"tofu très lisse et humide utilisé pour remplacer les œufs en cuisine"},{"term":"kala namak","definition":"sel noir volcanique indien qui imite l''arôme soufré des œufs"}]'),
  ('Le Curry de Patates Douces et Pois Chiches', 'Ce curry réconfortant marie patates douces fondantes, pois chiches croquants et lait de coco dans un bouillon épicé au curcuma et gingembre.', 41, 35, 'beginner', 'Ajoutez le lait de coco en fin de cuisson pour préserver sa douceur et éviter qu''il se sépare.', 'Le curry végétarien est au cœur de l''alimentation indienne depuis des millénaires, notamment pour les jours de fête hindous.', '[{"term":"curcuma","definition":"épice jaune aux propriétés anti-inflammatoires, base de nombreux currys"},{"term":"garam masala","definition":"mélange d''épices indiennes chaudes ajouté en fin de cuisson"}]'),
  ('Le Jackfruit Effiloché BBQ', 'Le jeune jackfruit en saumure, une fois effiloché et cuit en sauce BBQ, reproduit étonnamment la texture du pulled pork pour un résultat bluffant.', 42, 40, 'intermediate', 'Utilisez exclusivement du jackfruit jeune en saumure (non sucré) pour un résultat neutre à cuisiner.', 'Le jackfruit (jacquier) pousse en Asie tropicale et est le plus gros fruit comestible du monde.', '[{"term":"jackfruit","definition":"fruit tropical jeune utilisé comme substitut de viande grâce à sa texture fibreuse"},{"term":"pulled pork vegan","definition":"imitation végétale du porc effiloché avec du jackfruit effiloché"}]'),
  ('Le Gaspacho Vegan Enrichi', 'Ce gaspacho espagnol traditionnel, débarrassé de toute trace animale et enrichi de tomates séchées et basilic, atteint une profondeur de saveur remarquable.', 43, 15, 'beginner', 'Passez la soupe au tamis après mixage pour une texture soyeuse et raffinée.', 'Le gaspacho andalou est consommé depuis l''époque romaine; la version actuelle aux tomates date du XIXe siècle.', '[{"term":"gaspacho","definition":"soupe froide espagnole à base de tomates crues et légumes"},{"term":"émulsion","definition":"mélange de deux liquides non miscibles (eau et huile) stabilisé par mixage"}]'),
  ('Les Falafels Maison', 'Ces boulettes croquantes de pois chiches trempés (non cuits), herbes et épices orientales, frites ou cuites au four, sont le street food végétal du Moyen-Orient.', 44, 30, 'beginner', 'N''utilisez jamais de pois chiches en conserve: les pois chiches crus trempés donnent la texture croustillante authentique.', 'Les falafels sont originaires d''Égypte et restent aujourd''hui un aliment de rue populaire dans tout le Moyen-Orient.', '[{"term":"falafel","definition":"boulette frite de pois chiches crus trempés et herbes"},{"term":"pita","definition":"pain plat du Moyen-Orient dans lequel on glisse les falafels"}]'),
  ('La Paella Vegan aux Légumes', 'Cette paella sans viande ni fruits de mer mise sur des légumes de saison, safran et bouillon de légumes corsé pour un plat savoureux et festif.', 45, 45, 'intermediate', 'Le socarrat (fond de riz légèrement grillé) est la récompense d''une paella réussie: laissez chauffer à feu vif les 2 dernières minutes.', 'La paella originale de Valence était déjà végétarienne, à base de légumes et escargots de la campagne.', '[{"term":"socarrat","definition":"croûte de riz caramélisée au fond de la paella, très appréciée"},{"term":"safran","definition":"épice dorée la plus chère au monde, indispensable à la paella authentique"}]'),
  ('Le Burger Vegan Maison', 'Un steak végétal à base de lentilles, champignons et flocons d''avoine, avec tous les garnitures d''un burger classique, peut convaincre même les plus sceptiques.', 46, 40, 'intermediate', 'Réfrigérez les steaks 30 minutes avant cuisson pour qu''ils tiennent bien à la poêle.', 'Le mouvement du burger vegan a explosé dans les années 2010, stimulé par des startups comme Beyond Meat et Impossible Foods.', '[{"term":"liant","definition":"ingrédient qui permet à la préparation de tenir ensemble: lin moulu, avoine"},{"term":"steak végétal","definition":"galette à base de protéines végétales imitant la texture d''un steak"}]'),
  ('Le Tiramisu Vegan', 'Remplacer mascarpone et œufs par crème de cajou et aquafaba ouvre la porte à un tiramisu vegan bluffant qui rivalise avec l''original.', 47, 30, 'intermediate', 'L''aquafaba (eau de pois chiches) monte en neige comme les blancs d''œufs: fouettez-le bien froid.', 'La cuisine vegan moderne réinterprète les classiques avec des ingrédients comme l''aquafaba, découvert par les blogueurs en 2014.', '[{"term":"aquafaba","definition":"eau de cuisson des pois chiches utilisée comme substitut de blanc d''œuf"},{"term":"crème de cajou","definition":"noix de cajou mixées avec eau pour créer une crème végétale riche"}]'),
  ('La Crème Brûlée Végétale', 'Substituer le lait entier par lait de coco entier et les jaunes d''œufs par amidon de maïs et agar permet d''obtenir une crème brûlée végétale surprenante.', 48, 45, 'advanced', 'Utilisez du lait de coco entier (non allégé) pour une onctuosité proche de l''original.', 'L''agar-agar, algue gélifiant naturel, remplace la gélatine d''origine animale dans de nombreuses pâtisseries veganes.', '[{"term":"agar-agar","definition":"gélifiant naturel d''origine végétale extrait d''algues marines"},{"term":"caramel brûlé","definition":"fine couche de sucre caramélisée au chalumeau en surface de la crème"}]'),
  ('Le Kimchi Maison Vegan', 'Le kimchi traditionnel coréen est adapté sans sauce de poisson ni crevettes fermentées, avec miso et algues pour reproduire l''umami marin.', 49, 40, 'intermediate', 'Le kimchi maison se conserve des mois au réfrigérateur et se bonifie avec le temps.', 'Le kimchi est patrimoine culturel immatériel de l''UNESCO en Corée du Sud depuis 2013.', '[{"term":"pâte de gochugaru","definition":"piment coréen en flocons, base épicée du kimchi"},{"term":"umami végétal","definition":"saveur profonde reproduite avec algues, miso et champignons séchés"}]'),
  ('Le Festin des Fêtes Vegan', 'Un repas de fêtes entièrement végétal: rôti de lentilles aux herbes, purée de céleri-rave, jus brun aux champignons et bûche de marrons pour finir.', 50, 90, 'advanced', 'Le jus brun vegan se réalise avec champignons séchés, tamari, miso et légumes rôtis.', 'La cuisine vegan festive prouve que le végétal peut être aussi célébratoire et généreux que la cuisine traditionnelle.', '[{"term":"rôti végétal","definition":"préparation végétale moulée imitant le rôti en termes de présentation"},{"term":"jus brun","definition":"sauce riche à base de légumes rôtis et champignons pour accompagner le rôti"}]')
) AS v(title, description, order_index, duration_min, difficulty, chef_tip, cultural_note, vocabulary)
CROSS JOIN (SELECT id FROM public.paths WHERE slug='vegan' LIMIT 1) p;

-- ==================== EXERCISES ====================

-- Chinese exercises
INSERT INTO public.exercises (id, lesson_id, type, question, options, correct_answer, explanation, order_index)
SELECT gen_random_uuid(), l.id, v.type, v.question, v.options::jsonb, v.correct_answer, v.explanation, v.order_index
FROM (VALUES
  ('Le Porc Laqué de Pékin', 'multiple_choice', 'Comment obtient-on la peau croustillante du porc laqué de Pékin ?', '["En la séchant avant de laquer","En la marinant dans l''eau","En la bouillant longuement","En la fumant à froid"]', 'En la séchant avant de laquer', 'Sécher parfaitement la peau est essentiel pour un résultat croustillant.', 1),
  ('Le Porc Laqué de Pékin', 'fill_in_blank', 'La crêpe fine utilisée pour enrouler le porc laqué s''appelle une crêpe ___', '[]', 'mandarin', 'Les crêpes mandarin sont fines et délicates, parfaites pour enrouler le porc.', 2),
  ('Les Xiaolongbao', 'multiple_choice', 'Qu''est-ce qui rend les xiaolongbao uniques parmi les dumplings ?', '["Le bouillon gélifié intégré dans la farce","La pâte très épaisse","La cuisson à la poêle","La farce aux légumes"]', 'Le bouillon gélifié intégré dans la farce', 'Le bouillon fige pendant la préparation puis redevient liquide à la cuisson.', 1),
  ('Les Xiaolongbao', 'fill_in_blank', 'Le bouillon gélatineux utilisé dans les xiaolongbao s''appelle un ___', '[]', 'aspic', 'L''aspic est un bouillon concentré gélifié qui fond à la vapeur.', 2),
  ('Le Mapo Tofu', 'multiple_choice', 'Quelle épice donne au mapo tofu son effet anesthésiant caractéristique ?', '["Le poivre du Sichuan","Le piment rouge","Le gingembre","L''ail"]', 'Le poivre du Sichuan', 'Le poivre du Sichuan contient des composés qui enggourdissent légèrement la bouche.', 1),
  ('Le Mapo Tofu', 'fill_in_blank', 'La pâte de haricots fermentés pimentée utilisée dans le mapo tofu s''appelle ___', '[]', 'doubanjiang', 'Le doubanjiang est l''ingrédient fondamental du mapo tofu et de la cuisine du Sichuan.', 2),
  ('Le Canard aux Huit Trésors', 'multiple_choice', 'Quand est traditionnellement servi le canard aux huit trésors ?', '["Lors du Nouvel An chinois","À Pâques","En été","Pour les anniversaires"]', 'Lors du Nouvel An chinois', 'Les huit trésors symbolisent la prospérité, rendant ce plat idéal pour le Nouvel An.', 1),
  ('Le Canard aux Huit Trésors', 'fill_in_blank', 'Le type de riz utilisé dans la farce du canard aux huit trésors est du riz ___', '[]', 'gluant', 'Le riz gluant colle et absorbe toutes les saveurs de la farce.', 2),
  ('Le Char Siu', 'multiple_choice', 'Quelle est la durée minimale de marinade recommandée pour le char siu ?', '["12 heures","1 heure","30 minutes","3 heures"]', '12 heures', 'Une marinade longue permet aux saveurs de pénétrer profondément dans le porc.', 1),
  ('Le Char Siu', 'fill_in_blank', 'Le sucre utilisé pour le glaçage brillant du char siu s''appelle le ___', '[]', 'maltose', 'Le maltose donne au char siu son glaçage caramélisé et brillant caractéristique.', 2),
  ('La Soupe Wonton', 'multiple_choice', 'Pour obtenir des wontons translucides, que doit-on faire avec la pâte ?', '["La travailler jusqu''à ce qu''elle soit très fine","La cuire à la vapeur avant de farcir","La congeler avant usage","La laisser reposer 1 nuit"]', 'La travailler jusqu''à ce qu''elle soit très fine', 'Une pâte très fine devient translucide à la cuisson, révélant la farce.', 1),
  ('La Soupe Wonton', 'fill_in_blank', 'Les wontons sont des dumplings typiques de la cuisine ___', '[]', 'cantonaise', 'Les wontons sont une spécialité de Canton (Guangzhou) exportée dans le monde entier.', 2),
  ('Le Poulet Kung Pao', 'multiple_choice', 'D''où vient le nom "kung pao" ?', '["Du titre honorifique d''un gouverneur","D''un village du Sichuan","D''un ingrédient de la recette","D''une technique de cuisson"]', 'Du titre honorifique d''un gouverneur', 'Kung Pao était le titre du gouverneur Ding Baozhen qui aurait apprécié ce plat.', 1),
  ('Le Poulet Kung Pao', 'fill_in_blank', 'La technique de marinade à la fécule pour attendrir la viande s''appelle le ___', '[]', 'veloutage', 'Le veloutage enrobe la viande d''une couche protectrice qui la garde juteuse.', 2),
  ('Les Rouleaux de Printemps Frais', 'multiple_choice', 'Combien de temps faut-il tremper les galettes de riz avant de les utiliser ?', '["Quelques secondes","1 heure","30 minutes","Une nuit entière"]', 'Quelques secondes', 'Les galettes de riz se ramollissent en quelques secondes dans l''eau tiède.', 1),
  ('Les Rouleaux de Printemps Frais', 'fill_in_blank', 'La tradition cantonaise de thé et dim sum s''appelle le ___', '[]', 'Yum Cha', 'Le Yum Cha est une tradition de déjeuner en famille autour du thé et des dim sum.', 2),
  ('Le Bœuf au Brocoli', 'multiple_choice', 'Pourquoi blanchit-on le brocoli avant de le sauter ?', '["Pour garder son croquant et sa couleur","Pour l''attendrir complètement","Pour le parfumer","Pour le dessaler"]', 'Pour garder son croquant et sa couleur', 'Le blanchiment fixe la chlorophylle et précuit légèrement le brocoli.', 1),
  ('Le Bœuf au Brocoli', 'fill_in_blank', 'La sauce épaisse à base d''huîtres fermentées utilisée dans ce plat s''appelle sauce aux ___', '[]', 'huîtres', 'La sauce aux huîtres donne une profondeur umami caractéristique à ce plat.', 2),
  ('Le Riz Cantonais', 'multiple_choice', 'Pourquoi doit-on utiliser du riz cuit la veille pour le riz cantonais ?', '["Pour éviter un riz pâteux","Pour plus de saveur","Pour gagner du temps","Pour faciliter la découpe"]', 'Pour éviter un riz pâteux', 'Le riz refroidi a perdu son humidité et ses grains se séparent bien à la cuisson.', 1),
  ('Le Riz Cantonais', 'fill_in_blank', 'La saveur fumée caractéristique du wok à haute température s''appelle le ___', '[]', 'wok hei', 'Le wok hei est cette touche fumée et légèrement brûlée impossible à reproduire sans wok très chaud.', 2),
  ('Les Dim Sum Cheung Fun', 'multiple_choice', 'Comment doit être la pâte du cheung fun pour un résultat authentique ?', '["Très liquide et en couche ultra-fine","Épaisse et consistante","Ferme comme une pâte à pain","Crémeuse et aérée"]', 'Très liquide et en couche ultra-fine', 'La pâte très liquide permet d''étaler une couche translucide sur la plaque.', 1),
  ('Les Dim Sum Cheung Fun', 'fill_in_blank', 'La tradition cantonaise de thé et dim sum en famille s''appelle le ___', '[]', 'Yum Cha', 'Le Yum Cha est au cœur de la culture culinaire cantonaise.', 2),
  ('Le Congee de Poulet', 'multiple_choice', 'Qu''est-ce qui détermine la texture crémeuse du congee ?', '["La durée de cuisson","La quantité d''eau","Le type de riz","La température"]', 'La durée de cuisson', 'Plus le congee cuit longtemps, plus le riz se brise et la consistance devient crémeuse.', 1),
  ('Le Congee de Poulet', 'fill_in_blank', 'Le rhizome piquant utilisé pour aromatiser le congee de poulet est le ___', '[]', 'gingembre', 'Le gingembre frais apporte piquant et propriétés digestives au congee.', 2),
  ('Le Bao au Porc Rôti', 'multiple_choice', 'Pourquoi les bao doivent-ils lever deux fois ?', '["Pour une texture ultra-moelleuse","Pour plus de saveur","Pour une meilleure conservation","Pour un aspect lisse"]', 'Pour une texture ultra-moelleuse', 'La double levée développe le gluten et crée une mie aérée et moelleuse.', 1),
  ('Le Bao au Porc Rôti', 'fill_in_blank', 'Le porc laqué cantonais qui garnit les bao s''appelle le ___', '[]', 'char siu', 'Le char siu est la garniture classique des bao cantonais.', 2),
  ('Le Poulet à la Sauce Noire', 'multiple_choice', 'Pourquoi rince-t-on les haricots noirs fermentés avant usage ?', '["Pour atténuer leur salinité","Pour les attendrir","Pour enlever leur amertume","Pour les parfumer"]', 'Pour atténuer leur salinité', 'Les haricots noirs fermentés sont très salés et un rinçage équilibre leur intensité.', 1),
  ('Le Poulet à la Sauce Noire', 'fill_in_blank', 'Les haricots noirs fermentés très salés et parfumés s''appellent ___', '[]', 'douchi', 'Le douchi est l''un des condiments les plus anciens de la gastronomie chinoise.', 2),
  ('La Fondue Chinoise Hot Pot', 'multiple_choice', 'Quelle est la recommandation pour satisfaire tous les convives au hot pot ?', '["Préparer deux bouillons différents","Cuire tout à l''avance","Servir uniquement des légumes","N''utiliser que du bouillon épicé"]', 'Préparer deux bouillons différents', 'Un bouillon épicé et un neutre permettent à chacun de choisir selon ses préférences.', 1),
  ('La Fondue Chinoise Hot Pot', 'fill_in_blank', 'La pâte de sésame utilisée comme trempette dans le hot pot s''appelle le ___', '[]', 'tahini', 'Le tahini est utilisé pour créer des sauces crémeuses qui accompagnent le hot pot.', 2)
) AS v(lesson_title, type, question, options, correct_answer, explanation, order_index)
JOIN public.lessons l ON l.title = v.lesson_title;

-- Pastry exercises
INSERT INTO public.exercises (id, lesson_id, type, question, options, correct_answer, explanation, order_index)
SELECT gen_random_uuid(), l.id, v.type, v.question, v.options::jsonb, v.correct_answer, v.explanation, v.order_index
FROM (VALUES
  ('La Tarte au Citron Meringuée', 'multiple_choice', 'Pourquoi précuit-on la pâte à blanc pour la tarte au citron ?', '["Pour éviter qu''elle ramollisse sous la crème","Pour la colorer","Pour la parfumer","Pour la durcir davantage"]', 'Pour éviter qu''elle ramollisse sous la crème', 'La cuisson à blanc sèche la pâte et l''imperméabilise avant la garniture humide.', 1),
  ('La Tarte au Citron Meringuée', 'fill_in_blank', 'La meringue à base de sirop de sucre cuit qui stabilise la préparation s''appelle meringue ___', '[]', 'italienne', 'La meringue italienne est la plus stable car le sirop cuit cuit les blancs d''œufs.', 2),
  ('Le Saint-Honoré', 'multiple_choice', 'À qui doit-on la dédicace du Saint-Honoré ?', '["Au saint patron des boulangers","À un chef célèbre","À un roi de France","À une rue parisienne"]', 'Au saint patron des boulangers', 'Saint Honoré est le saint patron des boulangers et pâtissiers, célébré le 16 mai.', 1),
  ('Le Saint-Honoré', 'fill_in_blank', 'La crème pâtissière allégée à la meringue italienne utilisée dans le Saint-Honoré s''appelle crème ___', '[]', 'Chiboust', 'La crème Chiboust allie légèreté de la meringue et onctuosité de la pâtissière.', 2),
  ('Le Fraisier', 'multiple_choice', 'Quel chef a popularisé le fraisier moderne dans les années 1960 ?', '["Gaston Lenôtre","Alain Ducasse","Paul Bocuse","Pierre Hermé"]', 'Gaston Lenôtre', 'Lenôtre est l''un des pères de la pâtisserie française moderne.', 1),
  ('Le Fraisier', 'fill_in_blank', 'La crème pâtissière montée au beurre pour plus de légèreté s''appelle la ___', '[]', 'mousseline', 'La crème mousseline est plus légère qu''une pâtissière simple grâce à l''ajout de beurre pommade.', 2),
  ('L''Opéra', 'multiple_choice', 'Qui a créé le gâteau Opéra en 1955 ?', '["Cyriaque Gavillon chez Dalloyau","Pierre Hermé","Lenôtre","Ladurée"]', 'Cyriaque Gavillon chez Dalloyau', 'Gavillon s''inspira de la façade de l''Opéra Garnier pour créer ce chef-d''œuvre.', 1),
  ('L''Opéra', 'fill_in_blank', 'Le biscuit aux amandes très fin utilisé dans les entremets s''appelle biscuit ___', '[]', 'joconde', 'Le biscuit joconde est une base de l''entremets français, souple et parfumé aux amandes.', 2),
  ('Le Kouign-Amann', 'multiple_choice', 'Dans quelle ville bretonne le kouign-amann a-t-il été créé en 1860 ?', '["Douarnenez","Brest","Quimper","Rennes"]', 'Douarnenez', 'Le boulanger Yves-René Scordia créa accidentellement le kouign-amann à Douarnenez.', 1),
  ('Le Kouign-Amann', 'fill_in_blank', 'En breton, "kouign-amann" signifie gâteau au ___', '[]', 'beurre', 'Kouign = gâteau, amann = beurre en langue bretonne.', 2),
  ('Les Macarons Parisiens', 'multiple_choice', 'Pourquoi laisse-t-on croûter les coques de macarons avant cuisson ?', '["Pour obtenir la collerette caractéristique","Pour les durcir","Pour les parfumer","Pour les stabiliser"]', 'Pour obtenir la collerette caractéristique', 'Le croûtage crée une pellicule qui force la pâte à s''étaler vers le bas en formant la collerette.', 1),
  ('Les Macarons Parisiens', 'fill_in_blank', 'La technique de mélange pour obtenir la texture parfaite des coques s''appelle le ___', '[]', 'macaronage', 'Le macaronage est crucial: trop peu = coques craquelées, trop = coques plates.', 2),
  ('La Tarte Bourdaloue', 'multiple_choice', 'Qu''est-ce que la frangipane ?', '["Crème d''amandes mélangée à de la crème pâtissière","Purée d''amandes pure","Crème au beurre","Mousse de noisettes"]', 'Crème d''amandes mélangée à de la crème pâtissière', 'La frangipane est plus légère que la crème d''amandes pure grâce à la crème pâtissière.', 1),
  ('La Tarte Bourdaloue', 'fill_in_blank', 'Les poires pochées dans un sirop aromatisé sont cuites dans un sirop ___', '[]', 'vanillé', 'Le sirop vanillé parfume délicatement les poires et les garde moelleuses.', 2),
  ('Le Paris-Brest Revisité', 'multiple_choice', 'Qu''est-ce que le craquelin posé sur les choux apporte à la cuisson ?', '["Un aspect et un croquant unique","Une saveur sucrée","Un parfum beurré","Une couleur dorée"]', 'Un aspect et un croquant unique', 'Le craquelin fond sur les choux pendant la cuisson et crée une surface croustillante.', 1),
  ('Le Paris-Brest Revisité', 'fill_in_blank', 'Le praliné mélangé à des crêpes dentelles émiettées s''appelle praliné ___', '[]', 'feuilleté', 'Le praliné feuilleté donne une texture croquante à l''intérieur du Paris-Brest.', 2),
  ('La Bûche de Noël', 'multiple_choice', 'À quel moment doit-on rouler la génoise pour éviter les fissures ?', '["Encore chaude","Après refroidissement complet","Tiède","Congelée"]', 'Encore chaude', 'La génoise chaude est souple et s''enroule sans se casser.', 1),
  ('La Bûche de Noël', 'fill_in_blank', 'La génoise garnie et roulée sur elle-même s''appelle une ___', '[]', 'roulade', 'La roulade est la technique de base pour réaliser une bûche de Noël.', 2),
  ('La Tarte Tropézienne', 'multiple_choice', 'Qui a renommé la Tropézienne ainsi ?', '["Brigitte Bardot","Coco Chanel","Édith Piaf","Marilyn Monroe"]', 'Brigitte Bardot', 'Bardot en tournage à Saint-Tropez en 1955 rebaptisa la tarte "Tropézienne".', 1),
  ('La Tarte Tropézienne', 'fill_in_blank', 'Le parfum signature de la Tropézienne est l''eau de fleur d''___', '[]', 'oranger', 'L''eau de fleur d''oranger est le secret aromatique de la Tropézienne originale.', 2),
  ('Le Mille-Feuille Revisité', 'multiple_choice', 'Qu''apporte le feuilletage inversé par rapport au feuilletage classique ?', '["Plus de croustillant et régularité","Plus de légèreté","Plus de saveur","Plus de hauteur"]', 'Plus de croustillant et régularité', 'En inversant le feuilletage (beurre à l''extérieur), les couches sont plus uniformes.', 1),
  ('Le Mille-Feuille Revisité', 'fill_in_blank', 'Le glaçage à base de sucre cuit utilisé sur le mille-feuille classique s''appelle le ___', '[]', 'fondant', 'Le fondant donne au mille-feuille son glaçage lisse et brillant caractéristique.', 2),
  ('Le Soufflé au Grand Marnier', 'multiple_choice', 'Qu''est-ce qui est absolument interdit pendant la cuisson du soufflé ?', '["Ouvrir le four","Surveiller la température","Beurrer le moule","Fouetter les blancs"]', 'Ouvrir le four', 'Ouvrir le four provoque un choc thermique qui fait immédiatement tomber le soufflé.', 1),
  ('Le Soufflé au Grand Marnier', 'fill_in_blank', 'La crème épaisse qui sert de base et donne la saveur au soufflé s''appelle la base ___', '[]', 'pâtissière', 'La base pâtissière aromatisée est la fondation de tout soufflé sucré.', 2),
  ('La Tarte Tatin au Pamplemousse', 'multiple_choice', 'Qui a inventé accidentellement la Tatin originale aux pommes ?', '["Les sœurs Tatin","Marie-Antoine Carême","Auguste Escoffier","Paul Bocuse"]', 'Les sœurs Tatin', 'L''accident culinaire des sœurs Tatin en 1898 donna naissance à ce classique renversé.', 1),
  ('La Tarte Tatin au Pamplemousse', 'fill_in_blank', 'Le caramel réalisé sans eau directement avec du sucre fondu s''appelle caramel à ___', '[]', 'sec', 'Le caramel à sec donne un résultat plus concentré et moins susceptible de cristalliser.', 2),
  ('Le Gâteau Basque', 'multiple_choice', 'Quelles sont les deux garnitures traditionnelles du gâteau basque ?', '["Crème pâtissière ou confiture de cerises noires","Chocolat ou fraise","Crème au beurre ou poires","Noisettes ou abricot"]', 'Crème pâtissière ou confiture de cerises noires', 'Ces deux variantes coexistent dans la tradition basque, chaque famille ayant sa préférence.', 1),
  ('Le Gâteau Basque', 'fill_in_blank', 'La variété de cerises locales basques utilisée dans la confiture s''appelle cerise d''___', '[]', 'Itxassou', 'Les cerises d''Itxassou sont réputées pour leur goût unique dans tout le Pays Basque.', 2),
  ('La Charlotte aux Framboises', 'multiple_choice', 'Comment doit-on imbiber les biscuits pour la charlotte ?', '["Délicatement, sans les détremper","Généreusement en les trempant longuement","Sans les imbiber du tout","En les badigeonnant de confiture"]', 'Délicatement, sans les détremper', 'Des biscuits trop imbibés s''effondrent et la charlotte perd sa structure.', 1),
  ('La Charlotte aux Framboises', 'fill_in_blank', 'La mousse légère à base de crème anglaise, gélatine et crème fouettée s''appelle ___', '[]', 'bavaroise', 'La bavaroise est la garniture classique de la charlotte aux fruits.', 2)
) AS v(lesson_title, type, question, options, correct_answer, explanation, order_index)
JOIN public.lessons l ON l.title = v.lesson_title;

-- BBQ exercises
INSERT INTO public.exercises (id, lesson_id, type, question, options, correct_answer, explanation, order_index)
SELECT gen_random_uuid(), l.id, v.type, v.question, v.options::jsonb, v.correct_answer, v.explanation, v.order_index
FROM (VALUES
  ('Le Brisket de Texas', 'multiple_choice', 'À quelle température interne enveloppe-t-on le brisket dans du papier boucher ?', '["74°C (160°F)","55°C","90°C","100°C"]', '74°C (160°F)', 'C''est la règle des 160°F: envelopper à ce stade aide à passer le "stall".', 1),
  ('Le Brisket de Texas', 'fill_in_blank', 'La croûte noire et croustillante formée à la surface du brisket s''appelle le ___', '[]', 'bark', 'Le bark est formé par la réaction de Maillard entre le rub et la surface de la viande.', 2),
  ('Les Ribs St. Louis Style', 'multiple_choice', 'Que signifie la méthode 3-2-1 pour les ribs ?', '["3h fumer, 2h enveloppé, 1h à la sauce","3 épices, 2 sauces, 1 heure de cuisson","3 jours de marinade, 2h cuisson, 1h repos","3 couches de sauce appliquées toutes les heures"]', '3h fumer, 2h enveloppé, 1h à la sauce', 'Cette méthode en trois phases garantit des ribs tendres qui tombent de l''os.', 1),
  ('Les Ribs St. Louis Style', 'fill_in_blank', 'Le mélange d''épices appliqué à sec sur la viande avant cuisson s''appelle le ___', '[]', 'rub', 'Le rub sèche la surface et forme la croûte aromatique lors de la cuisson.', 2),
  ('Le Poulet Entier sur Canette', 'multiple_choice', 'Quel est l''avantage de cuisiner le poulet sur une canette de bière ?', '["Chair moelleuse et peau croustillante grâce à la vapeur","Cuisson plus rapide","Saveur de bière prononcée","Meilleure coloration"]', 'Chair moelleuse et peau croustillante grâce à la vapeur', 'La vapeur de bière hydrate la chair de l''intérieur pendant que l''air sec croustille la peau.', 1),
  ('Le Poulet Entier sur Canette', 'fill_in_blank', 'La cuisson à côté de la source de chaleur, non directement au-dessus, s''appelle chaleur ___', '[]', 'indirecte', 'La chaleur indirecte permet une cuisson douce et uniforme sans brûler la surface.', 2),
  ('Le Pulled Pork Carolina', 'multiple_choice', 'À quelle température interne effiloche-t-on le pulled pork ?', '["95°C","70°C","80°C","60°C"]', '95°C', 'À 95°C, le collagène s''est entièrement transformé en gélatine et la viande s''effiloche facilement.', 1),
  ('Le Pulled Pork Carolina', 'fill_in_blank', 'La sauce acide à base de vinaigre typique des Carolines s''appelle ___', '[]', 'vinegar sauce', 'La vinegar sauce tranche le gras du porc et apporte l''acidité caractéristique du BBQ Carolina.', 2),
  ('Les Burnt Ends de Kansas City', 'multiple_choice', 'Qu''est-ce qui différencie les burnt ends d''un brisket ordinaire ?', '["Ils sont recuits dans la sauce pour caraméliser","Ils sont plus épicés","Ils proviennent d''une autre coupe","Ils sont fumés plus longtemps"]', 'Ils sont recuits dans la sauce pour caraméliser', 'La deuxième cuisson dans la sauce concentre les saveurs et crée une caramélisation profonde.', 1),
  ('Les Burnt Ends de Kansas City', 'fill_in_blank', 'La partie grasse du brisket spécifiquement utilisée pour les burnt ends s''appelle le ___', '[]', 'point', 'Le point est plus gras et plus savoureux que le flat, idéal pour les burnt ends.', 2),
  ('La Côte de Bœuf au Charbon de Bois', 'multiple_choice', 'Quelle température le charbon de bois peut-il atteindre par rapport au gaz ?', '["Dépassant 600°C, inatteignable au gaz","Environ 200°C","La même qu''au gaz","300°C maximum"]', 'Dépassant 600°C, inatteignable au gaz', 'Cette chaleur extrême crée la réaction de Maillard intense impossible au gaz.', 1),
  ('La Côte de Bœuf au Charbon de Bois', 'fill_in_blank', 'Le quadrillage visuel obtenu en tournant la viande à 45° sur le gril s''appelle marque de ___', '[]', 'gril', 'Les marques de gril témoignent d''une saisie à haute temperature et améliorent la présentation.', 2),
  ('Le Porc Effiloché à la Bière', 'multiple_choice', 'Quel type de bière est recommandé pour le porc effiloché à la bière ?', '["Une bière brune maltée (stout ou porter)","Une bière blonde légère","Une bière blanche","Une bière sans alcool"]', 'Une bière brune maltée (stout ou porter)', 'Les bières brunes apportent des notes caramélisées et chocolatées qui enrichissent la sauce.', 1),
  ('Le Porc Effiloché à la Bière', 'fill_in_blank', 'La technique de cuisson lente en milieu humide à couvert s''appelle le ___', '[]', 'braisage', 'Le braisage convient parfaitement aux pièces de viande dures qui nécessitent une longue cuisson.', 2),
  ('Les Saucisses Fumées Maison', 'multiple_choice', 'À quelle température maximum doit-on maintenir le fumage pour des saucisses juteuses ?', '["80°C","120°C","50°C","100°C"]', '80°C', 'Au-dessus de 80°C, la graisse fond et s''écoule, rendant les saucisses sèches.', 1),
  ('Les Saucisses Fumées Maison', 'fill_in_blank', 'Le fumage à moins de 30°C pour parfumer sans cuire s''appelle fumage à ___', '[]', 'froid', 'Le fumage à froid préserve la texture crue tout en apportant des arômes de fumée.', 2),
  ('Le Lamb Rack Méditerranéen au BBQ', 'multiple_choice', 'Pourquoi protège-t-on les manchons d''agneau avec du papier aluminium ?', '["Pour éviter qu''ils noircissent","Pour les faire cuire plus vite","Pour les parfumer","Pour les attendrir"]', 'Pour éviter qu''ils noircissent', 'Les manchons fins cuisent beaucoup plus vite que la viande et brûlent sans protection.', 1),
  ('Le Lamb Rack Méditerranéen au BBQ', 'fill_in_blank', 'L''extrémité de l''os d''agneau nettoyée pour une présentation élégante s''appelle le ___', '[]', 'manchon', 'Nettoyer les manchons est une opération de finition qui donne au carré son aspect élégant.', 2),
  ('Le Salmon Cédré', 'multiple_choice', 'Combien de temps minimum faut-il tremper la planche de cèdre avant de l''utiliser ?', '["2 heures minimum","30 minutes","5 minutes","10 minutes"]', '2 heures minimum', 'Une planche bien trempée ne prend pas feu et dégage une vapeur aromatique continue.', 1),
  ('Le Salmon Cédré', 'fill_in_blank', 'La planche de bois utilisée comme support de cuisson au BBQ s''appelle planche de ___', '[]', 'cèdre', 'La planche de cèdre est la plus utilisée pour le saumon, apportant un arôme subtil et boisé.', 2),
  ('Les Légumes Grillés en Brochettes', 'multiple_choice', 'Combien de temps faut-il tremper les piques en bois avant de les utiliser ?', '["30 minutes dans l''eau","1 heure dans l''huile","5 minutes dans l''eau","Pas besoin de les tremper"]', '30 minutes dans l''eau', 'Un trempage de 30 minutes empêche les piques en bois de brûler et de donner un goût amer.', 1),
  ('Les Légumes Grillés en Brochettes', 'fill_in_blank', 'La transformation des sucres naturels des légumes sous la chaleur s''appelle ___', '[]', 'caramélisation', 'La caramélisation révèle la douceur naturelle des légumes et crée des saveurs complexes.', 2),
  ('Le Smokehouse Mac and Cheese', 'multiple_choice', 'Quel fromage est recommandé pour un mac and cheese optimal au BBQ ?', '["Un mélange de cheddar fumé et gruyère","Du parmesan uniquement","De la mozzarella","Du camembert"]', 'Un mélange de cheddar fumé et gruyère', 'Le cheddar fumé apporte la saveur BBQ et le gruyère assure la fonte crémeuse parfaite.', 1),
  ('Le Smokehouse Mac and Cheese', 'fill_in_blank', 'Le mélange de beurre et farine cuits servant de base à la béchamel s''appelle le ___', '[]', 'roux', 'Le roux est la base de la sauce béchamel qui enrobe les macaronis.', 2),
  ('Les Ailes de Poulet Buffalo', 'multiple_choice', 'Où et par qui la sauce Buffalo originale a-t-elle été créée en 1964 ?', '["Au Anchor Bar de Buffalo par Teressa Bellissimo","À Nashville par un chef anonyme","À Memphis dans un BBQ joint","À Houston lors d''un concours BBQ"]', 'Au Anchor Bar de Buffalo par Teressa Bellissimo', 'Teressa Bellissimo aurait improvise la recette pour nourrir les amis de son fils un soir tardif.', 1),
  ('Les Ailes de Poulet Buffalo', 'fill_in_blank', 'La sauce piquante à base de Frank''s RedHot et beurre fondu s''appelle sauce ___', '[]', 'Buffalo', 'La sauce Buffalo est le mélange emblématique de piment liquide et beurre fondu.', 2),
  ('Le Porc Mariné à la Coréenne (Bulgogi))', 'multiple_choice', 'Quel ingrédient de la marinade coréenne attendrit naturellement la viande ?', '["La poire asiatique","Le gochujang","Le sésame","La sauce soja"]', 'La poire asiatique', 'La poire asiatique contient des enzymes protéolytiques qui attendrissent les protéines de la viande.', 1),
  ('Le Porc Mariné à la Coréenne (Bulgogi))', 'fill_in_blank', 'La pâte de piment fermentée coréenne, épicée et légèrement sucrée, s''appelle le ___', '[]', 'gochujang', 'Le gochujang est l''assaisonnement le plus iconique de la cuisine coréenne.', 2),
  ('Le Bœuf Wagyu à la Braise', 'multiple_choice', 'Pourquoi ne faut-il pas cuire le wagyu bien cuit ?', '["La cuisson prolongée détruit le marbrage unique","Le wagyu est trop cher à gaspiller","La texture devient caoutchouteuse","La saveur est trop forte"]', 'La cuisson prolongée détruit le marbrage unique', 'Le gras marbré fond trop avec une cuisson prolongée, éliminant la texture fondante unique.', 1),
  ('Le Bœuf Wagyu à la Braise', 'fill_in_blank', 'L''échelle de 1 à 12 mesurant la qualité du marbrage wagyu s''appelle le score ___', '[]', 'BMS', 'Le BMS (Beef Marbling Score) est le standard international pour évaluer la qualité du wagyu.', 2)
) AS v(lesson_title, type, question, options, correct_answer, explanation, order_index)
JOIN public.lessons l ON l.title = v.lesson_title;

-- Vegan exercises
INSERT INTO public.exercises (id, lesson_id, type, question, options, correct_answer, explanation, order_index)
SELECT gen_random_uuid(), l.id, v.type, v.question, v.options::jsonb, v.correct_answer, v.explanation, v.order_index
FROM (VALUES
  ('Le Seitan Maison', 'multiple_choice', 'Quelle est la technique pour faire du seitan à partir de farine de blé ?', '["Pétrir puis rincer jusqu''à ce que l''eau soit claire","Faire bouillir la farine directement","Mélanger avec des légumineuses","Cuire au four sans rinçage"]', 'Pétrir puis rincer jusqu''à ce que l''eau soit claire', 'Le rinçage élimine l''amidon et ne laisse que le gluten élastique.', 1),
  ('Le Seitan Maison', 'fill_in_blank', 'La protéine élastique du blé qui forme la structure du seitan s''appelle le ___', '[]', 'gluten', 'Le gluten est la protéine qui donne au seitan sa texture fibreuse proche de la viande.', 2),
  ('Le Bowl de Buddha', 'multiple_choice', 'D''où vient le nom "Buddha bowl" ?', '["Des bols ronds rappelant le ventre de Bouddha","D''un temple bouddhiste","D''un chef cuisinier bouddhiste","D''une région d''Asie"]', 'Des bols ronds rappelant le ventre de Bouddha', 'La forme ronde et généreuse du bol évoque le ventre arrondi et serein du Bouddha.', 1),
  ('Le Bowl de Buddha', 'fill_in_blank', 'La pâte de sésame torréfié riche en protéines utilisée dans les sauces s''appelle le ___', '[]', 'tahini', 'Le tahini est la base des sauces crémeuses qui accompagnent les Buddha bowls.', 2),
  ('Le Fromage de Cajou', 'multiple_choice', 'Combien de temps faut-il fermenter le fromage de cajou pour des saveurs complexes ?', '["24 à 48 heures","1 heure","5 jours","1 semaine"]', '24 à 48 heures', 'Une fermentation de 24-48h développe les saveurs acidulées et complexes du fromage vegan.', 1),
  ('Le Fromage de Cajou', 'fill_in_blank', 'La levure inactivée au goût fromager utilisée en cuisine vegan s''appelle levure ___', '[]', 'nutritionnelle', 'La levure nutritionnelle est le substitut universel du fromage dans la cuisine vegan.', 2),
  ('Le Tempeh Grillé Teriyaki', 'multiple_choice', 'Pourquoi fait-on bouillir le tempeh avant de le mariner ?', '["Pour atténuer son amertume naturelle","Pour le parfumer","Pour l''attendrir","Pour le cuire entièrement"]', 'Pour atténuer son amertume naturelle', 'Le blanchiment élimine les composés amers du soja fermenté et améliore l''absorption de la marinade.', 1),
  ('Le Tempeh Grillé Teriyaki', 'fill_in_blank', 'Le soja fermenté sous forme de bloc compact et riche en protéines s''appelle le ___', '[]', 'tempeh', 'Le tempeh est un aliment traditionnel indonésien aux propriétés nutritionnelles excellentes.', 2),
  ('La Quiche Lorraine Vegan', 'multiple_choice', 'Quel sel est utilisé pour reproduire l''arôme des œufs dans la quiche vegan ?', '["Le kala namak (sel noir indien)","Le sel de mer","Le sel de l''Himalaya","Le sel fumé"]', 'Le kala namak (sel noir indien)', 'Le kala namak contient du sulfure d''hydrogène qui imite l''arôme soufré des œufs.', 1),
  ('La Quiche Lorraine Vegan', 'fill_in_blank', 'Le tofu très lisse utilisé pour remplacer les œufs en cuisine s''appelle tofu ___', '[]', 'soyeux', 'Le tofu soyeux mimique la texture crémeuse des œufs dans les préparations vegan.', 2),
  ('Le Curry de Patates Douces et Pois Chiches', 'multiple_choice', 'Quand ajoute-t-on le lait de coco dans ce curry ?', '["En fin de cuisson","Au début de la cuisson","En même temps que les légumes","Après avoir servi"]', 'En fin de cuisson', 'Ajouté trop tôt, le lait de coco perd sa douceur et peut se séparer.', 1),
  ('Le Curry de Patates Douces et Pois Chiches', 'fill_in_blank', 'Le mélange d''épices indiennes chaudes ajouté en fin de cuisson s''appelle ___', '[]', 'garam masala', 'Le garam masala est ajouté en fin de cuisson pour préserver ses arômes volatils.', 2),
  ('Le Jackfruit Effiloché BBQ', 'multiple_choice', 'Quel type de jackfruit doit-on utiliser pour imiter le pulled pork ?', '["Jeune jackfruit en saumure (non sucré)","Jackfruit mûr en sirop","Jackfruit frais mûr","Jackfruit séché"]', 'Jeune jackfruit en saumure (non sucré)', 'Le jeune jackfruit non sucré a une texture fibreuse neutre parfaite pour absorber les saveurs BBQ.', 1),
  ('Le Jackfruit Effiloché BBQ', 'fill_in_blank', 'Le fruit tropical jeune utilisé comme substitut de viande grâce à sa texture fibreuse s''appelle le ___', '[]', 'jackfruit', 'Le jackfruit jeune s''effiloche comme de la viande et absorbe parfaitement les sauces.', 2),
  ('Le Gaspacho Vegan Enrichi', 'multiple_choice', 'Que fait-on après avoir mixé le gaspacho pour une texture raffinée ?', '["On le passe au tamis","On y ajoute de la fécule","On le chauffe légèrement","On le congèle"]', 'On le passe au tamis', 'Le tamisage élimine les peaux et pépins pour une soupe parfaitement lisse.', 1),
  ('Le Gaspacho Vegan Enrichi', 'fill_in_blank', 'La soupe froide espagnole à base de tomates crues et légumes s''appelle le ___', '[]', 'gaspacho', 'Le gaspacho andalou est consommé depuis l''époque romaine pour se rafraîchir en été.', 2),
  ('Les Falafels Maison', 'multiple_choice', 'Pourquoi ne peut-on pas utiliser des pois chiches en conserve pour les falafels ?', '["Ils ne donnent pas la texture croustillante authentique","Ils ont mauvais goût","Ils contiennent trop de sel","Ils sont trop mous à cuire"]', 'Ils ne donnent pas la texture croustillante authentique', 'Les pois chiches cuits sont trop humides; les crus trempés donnent la texture idéale.', 1),
  ('Les Falafels Maison', 'fill_in_blank', 'Le pain plat du Moyen-Orient dans lequel on glisse les falafels s''appelle la ___', '[]', 'pita', 'La pita est le pain accompagnement indissociable des falafels.', 2),
  ('La Paella Vegan aux Légumes', 'multiple_choice', 'Qu''est-ce que le "socarrat" dans la paella ?', '["Le fond de riz légèrement grillé au fond de la poêle","La couche de légumes du dessus","L''épice principale","La sauce de service"]', 'Le fond de riz légèrement grillé au fond de la poêle', 'Le socarrat est la couche de riz caramélisée qui colle au fond et est très appréciée.', 1),
  ('La Paella Vegan aux Légumes', 'fill_in_blank', 'L''épice dorée la plus chère au monde, indispensable à la paella authentique, s''appelle le ___', '[]', 'safran', 'Le safran colore la paella en jaune et lui donne son arôme floral caractéristique.', 2),
  ('Le Burger Vegan Maison', 'multiple_choice', 'Combien de temps faut-il réfrigérer les steaks vegans avant cuisson ?', '["30 minutes","5 minutes","2 heures","Une nuit entière"]', '30 minutes', 'Le refroidissement raffermit le steak vegan et l''empêche de se désagréger à la cuisson.', 1),
  ('Le Burger Vegan Maison', 'fill_in_blank', 'L''ingrédient qui permet à la préparation vegan de tenir ensemble (lin moulu, avoine) s''appelle le ___', '[]', 'liant', 'Le liant est essentiel dans tout steak vegan pour une tenue parfaite à la cuisson.', 2),
  ('Le Tiramisu Vegan', 'multiple_choice', 'Comment doit être l''aquafaba avant de le fouetter en neige ?', '["Bien froid","À température ambiante","Légèrement chauffé","Directement sorti de la boîte"]', 'Bien froid', 'L''aquafaba froid monte mieux en neige, comme les blancs d''œufs.', 1),
  ('Le Tiramisu Vegan', 'fill_in_blank', 'L''eau de cuisson des pois chiches utilisée comme substitut de blanc d''œuf s''appelle ___', '[]', 'aquafaba', 'L''aquafaba fut découvert en 2014 et révolutionna la pâtisserie vegan.', 2),
  ('La Crème Brûlée Végétale', 'multiple_choice', 'Quel lait végétal est recommandé pour la crème brûlée végétale ?', '["Lait de coco entier (non allégé)","Lait d''amande","Lait de soja","Lait d''avoine"]', 'Lait de coco entier (non allégé)', 'Le lait de coco entier a la richesse en matières grasses nécessaire à la texture crémeuse.', 1),
  ('La Crème Brûlée Végétale', 'fill_in_blank', 'Le gélifiant naturel d''origine végétale extrait d''algues marines s''appelle l''___', '[]', 'agar-agar', 'L''agar-agar est le substitut végétal de la gélatine d''origine animale.', 2),
  ('Le Kimchi Maison Vegan', 'multiple_choice', 'Quelle est la distinction du kimchi vegan par rapport au kimchi traditionnel ?', '["Sans sauce de poisson ni crevettes, remplacées par miso et algues","Sans piment","Sans ail","Sans chou"]', 'Sans sauce de poisson ni crevettes, remplacées par miso et algues', 'Le miso et les algues reproduisent l''umami marin des ingrédients animaux traditionnels.', 1),
  ('Le Kimchi Maison Vegan', 'fill_in_blank', 'Le piment coréen en flocons qui est la base épicée du kimchi s''appelle le ___', '[]', 'gochugaru', 'Le gochugaru est irremplaçable dans l''authentique kimchi coréen.', 2),
  ('Le Festin des Fêtes Vegan', 'multiple_choice', 'Comment réalise-t-on un jus brun vegan ?', '["Avec champignons séchés, tamari, miso et légumes rôtis","Avec du bouillon de poulet végétalisé","Avec uniquement du tamari dilué","Avec de la sauce tomate"]', 'Avec champignons séchés, tamari, miso et légumes rôtis', 'Ces ingrédients combinent umami, couleur brune et richesse pour imiter le jus de viande.', 1),
  ('Le Festin des Fêtes Vegan', 'fill_in_blank', 'La préparation végétale moulée imitant le rôti en termes de présentation s''appelle le rôti ___', '[]', 'végétal', 'Le rôti végétal est la pièce maîtresse d''un repas de fête vegan réussi.', 2)
) AS v(lesson_title, type, question, options, correct_answer, explanation, order_index)
JOIN public.lessons l ON l.title = v.lesson_title;
