-- Migration: Add recipes for all new lessons added in 20260629_expand_lessons_v2.sql
-- Run AFTER 20260629_expand_lessons_v2.sql
-- Uses gen_random_uuid() and JOIN on lesson title to avoid hardcoded UUIDs

INSERT INTO public.recipes (id, lesson_id, title, description, emoji, prep_time_min, cook_time_min, servings, difficulty, avg_price_eur, ingredients, instructions, chef_tip, cultural_note)
SELECT gen_random_uuid(), l.id, v.title, v.description, v.emoji, v.prep_time_min::int, v.cook_time_min::int, v.servings::int, v.difficulty, v.avg_price_eur, v.ingredients::jsonb, v.instructions::jsonb, v.chef_tip, v.cultural_note
FROM (VALUES

-- ===== FRENCH PATH =====
('La Ratatouille',
 'Ratatouille Provençale', 'Le grand plat d''été de Provence : légumes du soleil fondants et parfumés', '🫑', '25', '45', '4', 'facile', '~8€',
 '[{"qty":"2","item":"courgettes","tip":"Coupez en rondelles de 5mm d''épaisseur"},{"qty":"2","item":"aubergines","tip":"Dégorger au sel 20 min si amer"},{"qty":"3","item":"tomates mûres","tip":"Ou 400g de tomates en boîte hors saison"},{"qty":"2","item":"poivrons (rouge + jaune)"},{"qty":"1","item":"oignon"},{"qty":"4 gousses","item":"ail"},{"qty":"1 branche","item":"thym frais"},{"qty":"1 branche","item":"romarin"},{"qty":"4 c.s.","item":"huile d''olive extra vierge"},{"qty":"sel & poivre","item":"à votre goût"}]',
 '["Coupez tous les légumes en rondelles fines et régulières.","Faites revenir l''oignon et l''ail dans l''huile d''olive à feu moyen 5 min.","Ajoutez les poivrons, faites cuire 5 min supplémentaires.","Incorporez les courgettes, les aubergines et les tomates.","Assaisonnez, ajoutez thym et romarin.","Couvrez et laissez mijoter à feu doux 35 min en remuant doucement.","Retirez le couvercle les 10 dernières minutes pour concentrer la sauce.","Rectifiez l''assaisonnement et servez chaud ou froid."]',
 'La ratatouille est meilleure réchauffée : préparez-la la veille pour que les saveurs se développent pleinement.',
 'Plat traditionnel de Nice et de toute la Provence, la ratatouille est mentionnée dès le XVIIIe siècle. Elle a été popularisée mondialement par le film d''animation Pixar en 2007.'),

('Le Confit de Canard',
 'Confit de Canard', 'Cuisse de canard confite dans sa propre graisse, croustillante à l''extérieur', '🦆', '30', '150', '4', 'moyen', '~18€',
 '[{"qty":"4","item":"cuisses de canard"},{"qty":"800g","item":"graisse de canard","tip":"En bocal au rayon conserves"},{"qty":"4 gousses","item":"ail"},{"qty":"2 branches","item":"thym"},{"qty":"2 feuilles","item":"laurier"},{"qty":"1 c.s.","item":"gros sel"},{"qty":"1/2 c.c.","item":"poivre noir concassé"}]',
 '["La veille : frottez les cuisses avec le sel, l''ail haché, le thym et le laurier. Filmez et réfrigérez 12 h.","Rincez les cuisses à l''eau froide et séchez-les soigneusement.","Faites fondre la graisse de canard dans une cocotte à feu doux.","Immergez les cuisses dans la graisse et faites confire à 80°C pendant 2h30 à 3h.","Les cuisses doivent être tendres (une lame de couteau entre facilement).","Pour servir : faites revenir les cuisses à la poêle côté peau 8-10 min jusqu''à obtenir une peau dorée et croustillante."]',
 'Le secret du confit parfait : une température constante et basse (80°C). Un thermomètre de cuisine est indispensable.',
 'Le confit est une technique de conservation médiévale de Gascogne. Avant la réfrigération, les confits se gardaient plusieurs mois immergés dans la graisse.'),

('La Tarte Tatin',
 'Tarte Tatin', 'La tarte aux pommes renversée, caramélisée et fondante', '🍎', '20', '35', '6', 'moyen', '~6€',
 '[{"qty":"1,5kg","item":"pommes (Golden ou Reinette)"},{"qty":"150g","item":"beurre","tip":"Demi-sel pour plus de saveur"},{"qty":"200g","item":"sucre"},{"qty":"1 rouleau","item":"pâte feuilletée","tip":"Achetée ou maison"},{"qty":"1 c.c.","item":"vanille en poudre"}]',
 '["Épluchez et coupez les pommes en quartiers.","Dans une poêle allant au four, faites un caramel à sec avec le sucre jusqu''à couleur ambre.","Ajoutez le beurre hors du feu en fouettant.","Disposez les quartiers de pommes debout, bien serrés, dans le caramel.","Faites cuire à feu moyen 15 min pour compoter légèrement les pommes.","Couvrez avec la pâte feuilletée en rentrant les bords sous les pommes.","Enfournez à 200°C pendant 25-30 min jusqu''à dorure.","Laissez refroidir 5 min puis retournez sur un plat de service. Servez tiède."]',
 'Utilisez des pommes fermes qui tiennent la cuisson. La reinette du Canada reste ma préférence — son acidité équilibre parfaitement le caramel.',
 'Créée par accident par les sœurs Tatin dans leur hôtel de Lamotte-Beuvron (Sologne) vers 1880, cette tarte est devenue l''un des desserts les plus copiés au monde.'),

('Le Pot-au-Feu',
 'Pot-au-Feu', 'Le grand plat traditionnel français : viande et légumes mijotés dans un bouillon parfumé', '🥩', '30', '180', '6', 'facile', '~22€',
 '[{"qty":"1kg","item":"paleron ou plat-de-côtes de bœuf"},{"qty":"500g","item":"os à moelle"},{"qty":"4","item":"carottes"},{"qty":"4","item":"poireaux"},{"qty":"4","item":"navets"},{"qty":"1","item":"oignon piqué de clous de girofle"},{"qty":"1 bouquet","item":"garni (thym, laurier, persil)"},{"qty":"gros sel","item":"et poivre en grains"}]',
 '["Placez la viande et les os dans une grande marmite, couvrez d''eau froide.","Portez à ébullition, écumez soigneusement pendant 10 min.","Ajoutez l''oignon piqué, le bouquet garni, sel et poivre.","Laissez mijoter doucement (frémissement) pendant 2h.","Ajoutez les légumes coupés en tronçons et poursuivez 45 min.","Retirez les os à moelle 20 min après les légumes.","Filtrez le bouillon — servez-le en entrée avec des croûtons.","Servez viande et légumes sur un grand plat avec cornichons, moutarde et fleur de sel."]',
 'Ajoutez les légumes par ordre de durée de cuisson : navets et carottes d''abord, poireaux en dernier pour qu''ils restent verts.',
 'Le pot-au-feu est considéré comme le plat national français. Henri IV souhaitait que chaque Français puisse « mettre la poule au pot tous les dimanches ».'),

('Les Gougères',
 'Gougères au Gruyère', 'Petits choux au fromage légers et croustillants, parfaits à l''apéritif', '🧀', '20', '25', '30', 'moyen', '~5€',
 '[{"qty":"250ml","item":"eau"},{"qty":"100g","item":"beurre"},{"qty":"150g","item":"farine tamisée"},{"qty":"4","item":"œufs"},{"qty":"120g","item":"gruyère râpé","tip":"Ou comté pour plus de saveur"},{"qty":"1 pincée","item":"noix de muscade"},{"qty":"sel & poivre","item":"à votre goût"}]',
 '["Préchauffez le four à 200°C.","Portez l''eau, le beurre et une pincée de sel à ébullition.","Hors du feu, ajoutez la farine en une seule fois et mélangez vigoureusement.","Remettez sur feu doux et desséchez la pâte 2 min en remuant (elle doit se décoller des bords).","Hors du feu, incorporez les œufs un par un en mélangeant bien entre chaque.","Ajoutez 80g de gruyère, la muscade, le poivre.","Pochez des boules de 3cm sur une plaque recouverte de papier cuisson.","Parsemez du reste de gruyère et enfournez 25 min sans ouvrir le four."]',
 'N''ouvrez JAMAIS le four pendant la cuisson : les gougères retomberaient immédiatement.',
 'Les gougères sont originaires de Bourgogne où elles accompagnent traditionnellement les dégustations de vins.'),

('La Bavette à l''Échalote',
 'Bavette à l''Échalote', 'Steak saignant en sauce échalote-beurre, un classique des bistrots parisiens', '🥩', '10', '15', '2', 'facile', '~14€',
 '[{"qty":"2 (200g ch.)","item":"bavettes d''aloyau"},{"qty":"4","item":"échalotes"},{"qty":"100ml","item":"vin rouge"},{"qty":"50g","item":"beurre demi-sel"},{"qty":"1 bouquet","item":"persil plat"},{"qty":"2 c.s.","item":"huile neutre"},{"qty":"sel & poivre","item":"du moulin"}]',
 '["Sortez la viande du réfrigérateur 30 min avant cuisson.","Émincez finement les échalotes.","Faites revenir les échalotes dans le beurre à feu moyen 5 min jusqu''à translucidité.","Déglacez au vin rouge, laissez réduire des 2/3 (3-4 min).","Dans une poêle très chaude, saisissez les bavettes 2-3 min de chaque côté (saignant).","Salez et poivrez en fin de cuisson.","Laissez reposer la viande 3 min sur une planche.","Servez avec la sauce et le persil ciselé."]',
 'La bavette doit être saignante — c''est une règle. Si vous la cuisez bien cuite, elle sera dure et sans saveur.',
 'La bavette à l''échalote est le plat phare du bistrot parisien. La « bavette » désigne la partie du flanc du bœuf.'),

('Le Coq au Vin',
 'Coq au Vin', 'L''emblématique ragoût de poulet au vin rouge de Bourgogne', '🍷', '30', '90', '4', 'moyen', '~20€',
 '[{"qty":"1 (1.8kg)","item":"poulet fermier découpé en morceaux"},{"qty":"75cl","item":"vin rouge de Bourgogne","tip":"Pinot noir de préférence"},{"qty":"200g","item":"lardons fumés"},{"qty":"250g","item":"champignons de Paris"},{"qty":"20","item":"oignons grelots"},{"qty":"2 gousses","item":"ail"},{"qty":"2","item":"carottes"},{"qty":"1 bouquet","item":"garni"},{"qty":"2 c.s.","item":"farine"},{"qty":"2 c.s.","item":"cognac (facultatif)"}]',
 '["La veille : faites mariner les morceaux de poulet dans le vin avec les légumes et aromates.","Égouttez et séchez le poulet, réservez la marinade.","Faites revenir les lardons puis les oignons grelots dans une cocotte. Réservez.","Faites dorer les morceaux de poulet sur toutes les faces.","Flambez au cognac si désiré.","Saupoudrez de farine et mouillez avec la marinade filtrée.","Ajoutez lardons, oignons, champignons et bouquet garni.","Mijotez à couvert 1h à feu doux."]',
 'Le vin de la marinade sera le vin de la sauce — utilisez donc un vin que vous boiriez.',
 'Le coq au vin est l''une des recettes les plus anciennes de France. Selon la légende, Jules César aurait reçu un coq en gage de combat et l''aurait fait cuire au vin gaulois par défi.'),

('La Vichyssoise',
 'Vichyssoise', 'Potage glacé aux poireaux et pommes de terre, élégance froide à la française', '🥣', '20', '30', '4', 'facile', '~7€',
 '[{"qty":"4","item":"blancs de poireaux"},{"qty":"3","item":"pommes de terre (type Charlotte)"},{"qty":"1","item":"oignon"},{"qty":"1L","item":"bouillon de volaille"},{"qty":"20cl","item":"crème fraîche épaisse"},{"qty":"50g","item":"beurre"},{"qty":"ciboulette","item":"pour décorer"},{"qty":"sel & poivre blanc","item":"au goût"}]',
 '["Émincez les poireaux et l''oignon. Épluchez et coupez les pommes de terre en dés.","Faites fondre le beurre et faites suer les poireaux et l''oignon sans coloration 8 min.","Ajoutez les pommes de terre et le bouillon. Portez à ébullition.","Laissez mijoter 25 min jusqu''à tendreté.","Mixez finement jusqu''à obtenir une texture veloutée.","Passez au tamis fin pour plus de finesse.","Incorporez la crème, salez et poivrez.","Réfrigérez au moins 4h. Servez très froid, décoré de ciboulette."]',
 'Pour une couleur vert pâle sublime, mixez quelques feuilles de vert de poireau blanchi avec la soupe.',
 'Créée en 1917 par le chef français Louis Diat au Ritz-Carlton de New York, en souvenir de la soupe que préparait sa mère à Vichy.'),

('Le Canard à l''Orange',
 'Canard à l''Orange', 'Magret de canard laqué à la sauce bigarade orange et Grand Marnier', '🍊', '20', '25', '2', 'difficile', '~22€',
 '[{"qty":"2","item":"magrets de canard"},{"qty":"3","item":"oranges bio"},{"qty":"50g","item":"sucre"},{"qty":"50ml","item":"vinaigre de vin"},{"qty":"200ml","item":"fond de volaille"},{"qty":"50ml","item":"Grand Marnier"},{"qty":"sel & poivre","item":"du moulin"}]',
 '["Quadrillez la peau des magrets au couteau (sans couper la chair). Salez et poivrez.","Posez les magrets côté peau dans une poêle froide. Faites cuire à feu moyen 8-10 min jusqu''à rendu du gras.","Retournez et cuisez 3-4 min (rosé). Laissez reposer 5 min.","Faites caraméliser le sucre à sec. Déglacez au vinaigre (attention aux projections).","Ajoutez le jus de 2 oranges, le Grand Marnier et le fond de volaille.","Laissez réduire 5 min jusqu''à consistance nappante.","Ajustez en sel. Ajoutez des suprêmes d''orange à la dernière minute.","Tranchez les magrets, nappez de sauce. Décorez avec le zeste de la 3e orange."]',
 'Le secret du magret parfait : commencez TOUJOURS côté peau froide. Le gras fond doucement et la peau devient croustillante sans brûler.',
 'Le canard à l''orange est une recette de la Renaissance, introduite en France par Catherine de Médicis.'),

('Les Oeufs Cocotte',
 'Œufs Cocotte à la Crème', 'Œufs cuits au four en ramequin, onctueux et parfumés aux herbes', '🥚', '10', '12', '2', 'facile', '~4€',
 '[{"qty":"4","item":"œufs très frais"},{"qty":"4 c.s.","item":"crème fraîche épaisse"},{"qty":"20g","item":"beurre"},{"qty":"2 tranches","item":"jambon cru (facultatif)"},{"qty":"ciboulette & persil","item":"ciselés"},{"qty":"sel, poivre","item":"noix de muscade"}]',
 '["Préchauffez le four à 180°C. Faites chauffer un bain-marie.","Beurrez généreusement 2 ramequins. Tapissez de jambon cru si désiré.","Versez 1 c.s. de crème dans chaque ramequin. Ajoutez une pincée de muscade.","Cassez délicatement 2 œufs par ramequin sans percer les jaunes.","Versez encore 1 c.s. de crème sur le dessus. Salez légèrement.","Posez les ramequins dans le bain-marie, l''eau doit arriver à mi-hauteur.","Enfournez 10-12 min : le blanc doit être pris, le jaune encore coulant.","Parsemez d''herbes fraîches. Servez immédiatement avec des mouillettes."]',
 'La cuisson parfaite se juge au toucher : le blanc est ferme mais le jaune tremble encore légèrement.',
 'Les œufs cocotte sont un classique de la cuisine familiale française du XIXe siècle, jadis cuits dans des cocottes en fonte individuelles.'),

('La Brandade de Morue',
 'Brandade de Morue', 'La spécialité nîmoise : morue, huile d''olive et ail en émulsion crémeuse', '🐟', '30', '20', '4', 'moyen', '~12€',
 '[{"qty":"500g","item":"morue salée","tip":"Faire dessaler 24h à 48h en changeant l''eau régulièrement"},{"qty":"200ml","item":"huile d''olive de qualité"},{"qty":"200ml","item":"crème fraîche liquide"},{"qty":"3 gousses","item":"ail"},{"qty":"4","item":"pommes de terre (facultatif)"},{"qty":"pain grillé","item":"pour servir"},{"qty":"poivre blanc","item":"et persil"}]',
 '["Dessalez la morue 24-48h en changeant l''eau 3-4 fois.","Pochez la morue dans de l''eau frémissante (pas bouillante) 15 min.","Égouttez, retirez la peau et les arêtes. Émiettez la chair.","Faites chauffer séparément l''huile d''olive et la crème avec l''ail écrasé.","Mettez la morue dans une casserole à feu très doux. Incorporez alternativement huile et crème en fouettant énergiquement.","Ajoutez les pommes de terre cuites réduites en purée si désiré.","La brandade doit avoir la texture d''une purée onctueuse.","Servez chaude sur du pain grillé frotté à l''ail."]',
 'La qualité de l''huile d''olive est primordiale — c''est l''âme du plat. Choisissez une huile fruitée de Provence.',
 'La brandade de morue est la spécialité de Nîmes depuis le XVIIIe siècle, époque où la morue de Terre-Neuve remontait jusqu''en Languedoc.'),

('Le Paris-Brest',
 'Paris-Brest', 'La couronne de pâte à choux garnie de crème mousseline pralinée', '🎂', '45', '30', '8', 'difficile', '~8€',
 '[{"qty":"250ml","item":"eau"},{"qty":"100g","item":"beurre"},{"qty":"150g","item":"farine"},{"qty":"4","item":"œufs"},{"qty":"50g","item":"amandes effilées"},{"qty":"500ml","item":"lait (crème pâtissière)"},{"qty":"4","item":"jaunes d''œufs"},{"qty":"100g","item":"sucre"},{"qty":"40g","item":"maïzena"},{"qty":"200g","item":"beurre (mousseline)"},{"qty":"150g","item":"praliné noisette"}]',
 '["Préchauffez le four à 200°C.","Faites la pâte à choux (eau + beurre + farine + œufs). Pochez un cercle de 20cm double, parsemez d''amandes effilées. Enfournez 30 min sans ouvrir.","Crème pâtissière : chauffez le lait, fouettez jaunes + sucre + maïzena, incorporez le lait chaud, cuisez 3 min. Filmez, refroidissez complètement.","Mousseline : fouettez le beurre pommade, incorporez la crème pâtissière et le praliné.","Coupez la couronne en deux, garnissez généreusement de crème. Refermez.","Saupoudrez de sucre glace. Servez frais."]',
 'La mousseline pralinée doit être incorporée froide dans le beurre à température ambiante — jamais l''inverse.',
 'Créé en 1910 par Louis Durand de Maisons-Laffitte pour célébrer la course cycliste Paris-Brest-Paris.'),

('La Bouillabaisse',
 'Bouillabaisse Marseillaise', 'La soupe de poissons provençale, monumentale et parfumée', '🐠', '45', '60', '6', 'difficile', '~35€',
 '[{"qty":"2kg","item":"poissons de roche variés (rascasse, grondin, saint-pierre)"},{"qty":"500g","item":"moules et palourdes"},{"qty":"4","item":"tomates mûres"},{"qty":"2","item":"oignons"},{"qty":"4 gousses","item":"ail"},{"qty":"1 bulbe","item":"fenouil"},{"qty":"1 pincée","item":"safran"},{"qty":"huile d''olive","item":"généreusement"},{"qty":"Rouille:","item":""},{"qty":"4 gousses","item":"ail"},{"qty":"1","item":"jaune d''œuf"},{"qty":"150ml","item":"huile d''olive"},{"qty":"1 pincée","item":"safran et piment de Cayenne"}]',
 '["Faites revenir oignons, fenouil et ail dans l''huile 10 min.","Ajoutez les tomates concassées et le safran. Cuisez 5 min.","Ajoutez les poissons entiers et couvrez d''eau. Portez à ébullition forte 20 min.","Retirez les poissons, filtrez le bouillon et remettez à ébullition.","Ajoutez les poissons nobles en dernier (5 min de cuisson suffisent).","Ajoutez les coquillages et cuisez 5 min.","Rouille : écrasez l''ail au mortier, incorporez le jaune d''œuf, montez à l''huile, ajoutez safran et piment.","Servez le bouillon avec de la rouille sur du pain grillé. Posez les poissons à côté."]',
 'La vraie bouillabaisse se fait avec la rascasse — sans elle, ce n''est pas une bouillabaisse.',
 'Institution marseillaise protégée par une « Charte de la Bouillabaisse » depuis 1980. À l''origine, c''était le plat des pêcheurs qui cuisaient les poissons invendus.'),

('Le Millefeuille',
 'Millefeuille Classique', 'Mille couches de pâte feuilletée, crème légère à la vanille et fondant blanc', '🍰', '60', '25', '8', 'expert', '~10€',
 '[{"qty":"500g","item":"pâte feuilletée"},{"qty":"500ml","item":"lait entier"},{"qty":"1","item":"gousse de vanille"},{"qty":"4","item":"jaunes d''œufs"},{"qty":"100g","item":"sucre"},{"qty":"50g","item":"maïzena"},{"qty":"200ml","item":"crème liquide 35%"},{"qty":"300g","item":"fondant blanc pâtissier"},{"qty":"50g","item":"chocolat noir fondu"}]',
 '["Étalez la pâte feuilletée en 3 rectangles de 30x10cm, piquez-les, réfrigérez 30 min.","Enfournez à 200°C entre deux plaques 20-25 min. Saupoudrez de sucre glace et grillez 2 min.","Crème pâtissière à la vanille : chauffez le lait, fouettez jaunes + sucre + maïzena, cuisez 3 min. Filmez, refroidissez.","Montez la crème en chantilly ferme. Incorporez délicatement à la crème pâtissière (crème diplomate).","Pochez la crème sur une plaque de feuilletage, posez la deuxième, pochez à nouveau, posez la troisième.","Fondant : chauffez à 35°C, étalez sur le dessus. Tracez des lignes de chocolat et marbrez."]',
 'Le millefeuille doit être assemblé maximum 2h avant de servir : la crème va ramollir le feuilletage.',
 'La technique de la pâte feuilletée est attribuée au pâtissier Claude Gellée vers 1645. Il reste l''une des préparations les plus techniques au monde.'),

-- ===== ITALIAN PATH =====
('Le Pesto Genovese',
 'Pesto Genovese', 'Le vrai pesto de Gênes : basilic, pignons, parmesan et ail au mortier', '🌿', '15', '0', '4', 'facile', '~6€',
 '[{"qty":"60g","item":"basilic frais (feuilles seulement)","tip":"Basilic genovese DOP si possible"},{"qty":"30g","item":"pignons de pin"},{"qty":"50g","item":"parmesan râpé (Parmigiano Reggiano)"},{"qty":"20g","item":"pecorino sardo râpé"},{"qty":"2 gousses","item":"ail de Gênes"},{"qty":"100ml","item":"huile d''olive extra vierge ligure"},{"qty":"fleur de sel","item":"(quelques grains)"}]',
 '["Lavez délicatement le basilic et séchez à plat sans frotter.","Dans le mortier en marbre, écrasez l''ail avec la fleur de sel en pâte lisse.","Ajoutez les pignons et broyez en crème.","Incorporez les feuilles de basilic par petites poignées en tournant le pilon (mouvement circulaire).","Ajoutez les fromages râpés et incorporez.","Versez l''huile d''olive en filet en continuant à tourner.","La consistance doit être crémeuse et légèrement granuleuse.","Servez immédiatement sur des trofie ou des linguines."]',
 'L''huile doit être ligure — douce et fruitée. Le mouvement du mortier doit être rotatif, JAMAIS de pilonnage.',
 'Le pesto genovese est protégé par un Consortium. La tradition du mortier en marbre existe à Gênes depuis le XVIe siècle.'),

('Les Gnocchi di Patate',
 'Gnocchi di Patate', 'Les petits pilous de pomme de terre italiens, légers et fondants', '🥔', '40', '10', '4', 'moyen', '~5€',
 '[{"qty":"1kg","item":"pommes de terre farineuses (Bintje ou Russet)"},{"qty":"200-250g","item":"farine 00","tip":"Ajustez selon l''humidité des pommes de terre"},{"qty":"1","item":"jaune d''œuf"},{"qty":"1 pincée","item":"sel"},{"qty":"1 pincée","item":"noix de muscade"}]',
 '["Cuisez les pommes de terre EN CHEMISE (avec la peau) dans l''eau bouillante salée 30-35 min.","Épluchez immédiatement, passez au presse-purée.","Étalez sur le plan de travail pour laisser l''humidité s''échapper 5 min.","Faites un puits, ajoutez la farine, le jaune et la muscade. Pétrissez très rapidement.","Formez des boudins de 2cm et coupez en tronçons de 2cm.","Roulez chaque gnocchi sur une fourchette pour créer les stries.","Cuisez dans de l''eau bouillante salée : dès qu''ils remontent à la surface (30 secondes), c''est prêt.","Servez immédiatement avec du beurre sauge ou du pesto."]',
 'Moins vous travaillez la pâte, meilleurs seront les gnocchi. Trop de pétrissage = gnocchi caoutchouteux.',
 'Les gnocchi existent sous différentes formes dans toute l''Italie. Les variétés aux pommes de terre sont originaires de Vénétie et Frioul.'),

('La Focaccia Genovese',
 'Focaccia Genovese', 'Pain plat moelleux à l''huile d''olive, tradition génoise', '🫓', '30', '25', '6', 'facile', '~4€',
 '[{"qty":"500g","item":"farine 00"},{"qty":"350ml","item":"eau tiède"},{"qty":"7g","item":"levure sèche active"},{"qty":"10g","item":"sel"},{"qty":"80ml","item":"huile d''olive extra vierge"},{"qty":"Saumure:","item":""},{"qty":"80ml","item":"eau"},{"qty":"40ml","item":"huile d''olive"},{"qty":"10g","item":"sel"},{"qty":"romarin","item":"fleur de sel pour finir"}]',
 '["Mélangez levure, sucre et eau tiède. Attendez 10 min.","Incorporez la farine, le sel et 40ml d''huile. Pétrissez 10 min.","Laissez lever 1h couvert dans un endroit chaud.","Huilez généreusement une plaque (40x30cm) et étalez la pâte avec les doigts.","Laissez lever encore 30 min.","Préparez la saumure en mélangeant eau + huile + sel.","Versez la saumure sur la focaccia, faites des trous profonds avec les doigts.","Parsemez de romarin et de fleur de sel. Enfournez à 230°C pendant 20-25 min."]',
 'La saumure est le secret de la focaccia génoise : elle pénètre dans les trous et crée des alvéoles moelleuses à l''intérieur.',
 'La focaccia génoise (fugàssa) est consommée au petit-déjeuner à Gênes, trempée dans le cappuccino.'),

('L''Osso Buco à la Milanaise',
 'Osso Buco alla Milanese', 'Jarret de veau braisé à la gremolata, la grande recette de Milan', '🥩', '20', '90', '4', 'moyen', '~28€',
 '[{"qty":"4 (3cm épaisseur)","item":"tranches de jarret de veau"},{"qty":"1","item":"oignon"},{"qty":"2","item":"carottes"},{"qty":"2 tiges","item":"céleri"},{"qty":"400g","item":"tomates concassées"},{"qty":"200ml","item":"vin blanc sec"},{"qty":"500ml","item":"bouillon de veau"},{"qty":"farine","item":"pour fariner"},{"qty":"Gremolata: zeste de citron","item":"+ ail + persil plat"}]',
 '["Farinez légèrement les tranches de jarret. Salez et poivrez.","Faites dorer dans l''huile et le beurre, 4 min de chaque côté. Réservez.","Dans la même cocotte, faites revenir oignon, carottes et céleri 8 min.","Déglacez au vin blanc, laissez réduire à moitié.","Ajoutez les tomates et le bouillon. Remettez les jarrets.","Couvrez et laissez braiser à 160°C au four pendant 1h30.","Gremolata : mélangez zeste de citron + ail haché + persil ciselé.","Servez sur du risotto alla milanese, parsemez de gremolata."]',
 'Ne sautez pas la gremolata — c''est elle qui transforme un bon plat en plat mémorable.',
 'L''osso buco (« os avec trou ») tire son nom du trou central de l''os d''où l''on extrait la précieuse moelle. À Milan, il se mange OBLIGATOIREMENT avec le risotto zafferano.'),

('La Panna Cotta',
 'Panna Cotta al Caramello', 'Crème cuite au caramel, silky et tremblante comme un nuage', '🍮', '15', '15', '4', 'facile', '~5€',
 '[{"qty":"500ml","item":"crème fraîche entière 35%"},{"qty":"80g","item":"sucre"},{"qty":"1","item":"gousse de vanille"},{"qty":"4 feuilles","item":"gélatine (8g)"},{"qty":"Caramel: 150g sucre","item":"+ 4 c.s. eau + 100ml crème chaude"}]',
 '["Faites tremper la gélatine dans l''eau froide 5 min.","Chauffez la crème avec le sucre et la gousse de vanille fendue.","Hors du feu, incorporez la gélatine essorée. Mélangez.","Versez dans des moules huilés ou des verres. Réfrigérez 4h minimum.","Caramel : faites chauffer sucre + eau jusqu''à couleur ambre foncé.","Ajoutez la crème chaude (attention aux projections) et remuez hors du feu.","Pour démouler : passez brièvement sous l''eau tiède, retournez sur l''assiette.","Nappez de caramel et servez immédiatement."]',
 'La panna cotta parfaite tremble comme de la gélatine mais fond dès le contact avec la bouche.',
 'La panna cotta est originaire du Piémont. Son nom signifie simplement « crème cuite ».'),

('Les Arancini Siciliens',
 'Arancini al Ragù', 'Boulettes de riz siciliennes farcies et panées, frites jusqu''à l''or', '🍊', '60', '30', '12', 'moyen', '~10€',
 '[{"qty":"600g","item":"riz arborio"},{"qty":"1.2L","item":"bouillon de viande"},{"qty":"3","item":"œufs"},{"qty":"100g","item":"parmesan râpé"},{"qty":"1 sachet","item":"safran"},{"qty":"Farce ragù: 200g bœuf haché","item":"+ 50g petits pois + 50g concentré de tomate"},{"qty":"Panure: 2 œufs battus","item":"+ 200g chapelure fine + huile pour friture"}]',
 '["Cuisez le riz dans le bouillon avec le safran jusqu''à absorption. Ajoutez 2 œufs et le parmesan. Étalez et laissez refroidir.","Ragù : faites revenir le bœuf, ajoutez les petits pois et la tomate. Cuisez 15 min.","Humidifiez vos mains, prenez une boule de riz (80g), creusez un trou.","Remplissez de ragù, refermez en forme de cône ou de boule.","Passez dans l''œuf battu puis dans la chapelure. Appuyez bien.","Faites frire à 180°C environ 4 min jusqu''à couleur orange vif.","Égouttez sur papier absorbant.","Servez immédiatement — les arancini doivent être mangés chauds."]',
 'Les arancini se congèlent parfaitement avant friture. Frissonnez-les directement congelés (ajoutez 2 min de cuisson).',
 'Les arancini (« petites oranges ») sont la street food emblématique de la Sicile, mentionnée dès le Xe siècle sous domination arabe.'),

('La Parmigiana di Melanzane',
 'Parmigiana di Melanzane', 'Le gratin d''aubergines napolitain, fondant et généreux', '🍆', '40', '45', '6', 'moyen', '~10€',
 '[{"qty":"3 grosses","item":"aubergines"},{"qty":"700g","item":"sauce tomate napolitaine"},{"qty":"300g","item":"mozzarella fior di latte"},{"qty":"100g","item":"parmesan râpé"},{"qty":"10","item":"feuilles de basilic frais"},{"qty":"huile","item":"pour friture ou gril"},{"qty":"sel","item":"pour dégorger"}]',
 '["Tranchez les aubergines en rondelles de 7mm. Salez et laissez dégorger 30 min. Rincez et séchez.","Faites frire ou griller les rondelles jusqu''à dorure. Réservez sur papier absorbant.","Tapissez le fond d''un plat à gratin de sauce tomate.","Disposez une couche d''aubergines, nappez de sauce, ajoutez mozzarella tranchée, basilic et parmesan.","Répétez jusqu''à épuisement des ingrédients.","Terminez par de la sauce, mozzarella et parmesan.","Enfournez à 180°C pendant 40-45 min.","Laissez reposer 15 min avant de servir."]',
 'La parmigiana est meilleure préparée à l''avance et réchauffée. Les saveurs s''imbriquent et le plat devient plus compact.',
 'Contrairement à son nom, la parmigiana n''est pas originaire de Parme mais de Naples et Sicile.'),

('Cacio e Pepe Romaine',
 'Cacio e Pepe', 'La trinité romaine : spaghetti, pecorino, poivre. Trois ingrédients, une technique', '🧀', '5', '12', '2', 'difficile', '~5€',
 '[{"qty":"200g","item":"tonnarelli ou spaghetti"},{"qty":"100g","item":"pecorino romano DOP finement râpé","tip":"À la microplane si possible"},{"qty":"30g","item":"parmesan parmigiano reggiano finement râpé"},{"qty":"2 c.c.","item":"poivre noir en grains","tip":"Fraîchement concassé au mortier"},{"qty":"sel","item":"pour l''eau de cuisson (modéré)"}]',
 '["Faites griller doucement les grains de poivre à sec dans la poêle. Concassez grossièrement au mortier.","Cuisez les pâtes dans de l''eau peu salée.","Dans la poêle, faites revenir le poivre concassé 30 secondes dans un peu d''eau de cuisson.","Ajoutez les pâtes al dente égouttées (conservez 2 verres d''eau de cuisson).","Hors du feu, ajoutez les fromages râpés avec quelques cuillères d''eau de cuisson en faisant tournoyer la poêle vigoureusement.","La texture doit être crémeuse et nappante.","Si trop sèche, ajoutez de l''eau de cuisson. Si trop liquide, remettez brièvement sur feu doux.","Servez immédiatement dans des assiettes creuses chaudes."]',
 'Jamais de crème, jamais de beurre. L''émulsion se forme grâce à l''amidon de l''eau de cuisson et au gras du fromage.',
 'Plat des bergers romains de la Campagne : un morceau de pecorino, des pâtes sèches, du poivre. Simple, nourrissant, indémodable.'),

('Les Lasagne al Forno',
 'Lasagne alla Bolognese', 'Le symbole de la cuisine bolognaise : pâtes fraîches, ragù et béchamel', '🍝', '60', '150', '8', 'difficile', '~20€',
 '[{"qty":"300g","item":"pâtes fraîches pour lasagnes"},{"qty":"Ragù: 400g bœuf haché","item":"+ 200g porc haché + 150g pancetta"},{"qty":"1 oignon, 1 carotte","item":"1 céleri"},{"qty":"200ml","item":"vin rouge"},{"qty":"400g","item":"tomates pelées"},{"qty":"100ml","item":"lait entier"},{"qty":"Béchamel: 1L lait","item":"+ 80g beurre + 80g farine + noix de muscade"}]',
 '["Ragù (3h) : faites revenir pancetta + soffritto. Ajoutez les viandes, colorez. Déglacez au vin, ajoutez tomates + lait. Mijotez 2-3h à feu très doux.","Béchamel : faites un roux beurre-farine, incorporez le lait chaud progressivement. Cuisez 5 min. Muscade.","Préchauffez le four à 180°C. Beurrez un grand plat à gratin.","Étalez une couche de béchamel, puis de pâtes, ragù, béchamel, parmesan.","Répétez 4-5 fois. Terminez par béchamel + parmesan généreux.","Enfournez 40 min jusqu''à dorure de surface.","Laissez reposer impérativement 20 min avant de découper.","Servez en carrés nets avec une salade verte."]',
 'Un ragù de 3 heures change tout. Le collagène fond lentement et crée une sauce fondante et soyeuse.',
 'La vraie lasagne bolognaise est enregistrée à la Chambre de Commerce de Bologne depuis 1982.'),

('La Polenta Crémeuse',
 'Polenta Crémeuse et Champignons', 'La polenta veloutée du nord de l''Italie, garnie de champignons sauvages', '🍄', '15', '40', '4', 'facile', '~8€',
 '[{"qty":"250g","item":"polenta de qualité (pas instantanée)"},{"qty":"1L","item":"eau ou bouillon de légumes"},{"qty":"50g","item":"beurre"},{"qty":"80g","item":"parmesan râpé"},{"qty":"Champignons: 500g champignons mélangés","item":"+ 2 gousses ail + thym + 50ml vin blanc"}]',
 '["Portez le bouillon à ébullition, salez légèrement.","Versez la polenta en pluie fine en fouettant constamment.","Baissez le feu au minimum et cuisez 30-40 min en remuant toutes les 5 min.","La polenta est prête quand elle se décolle des parois.","Hors du feu, incorporez beurre et parmesan. Couvrez 5 min.","Champignons : faites sauter les champignons à feu très vif, 3 min sans toucher.","Ajoutez l''ail, le thym et déglacez au vin blanc.","Servez la polenta crémeuse avec les champignons et leur jus."]',
 'Ne salez l''eau qu''après avoir incorporé la polenta — le sel se concentre et peut la rendre trop salée.',
 'La polenta est le plat du nord de l''Italie depuis l''introduction du maïs d''Amérique au XVIe siècle.'),

('Le Saltimbocca alla Romana',
 'Saltimbocca alla Romana', 'Escalopes de veau, prosciutto et sauge sautées au beurre et vin blanc', '🥩', '15', '10', '2', 'facile', '~18€',
 '[{"qty":"4 fines","item":"escalopes de veau"},{"qty":"4 tranches","item":"prosciutto di Parma"},{"qty":"8 feuilles","item":"sauge fraîche"},{"qty":"50g","item":"beurre"},{"qty":"100ml","item":"vin blanc sec (Frascati)"},{"qty":"sel & poivre","item":"avec parcimonie (prosciutto salé)"}]',
 '["Aplatissez légèrement les escalopes entre deux films.","Posez une tranche de prosciutto sur chaque escalope.","Fixez 2 feuilles de sauge avec un cure-dent.","Dans une grande poêle, faites fondre le beurre à feu vif.","Posez les escalopes côté prosciutto vers le bas. Cuisez 1 min 30.","Retournez délicatement et cuisez 1 min côté veau.","Retirez les escalopes. Déglacez au vin blanc, laissez réduire 1 min.","Versez la sauce sur les escalopes. Servez immédiatement."]',
 'Le nom « saltimbocca » signifie « saute en bouche » — la cuisson ultra-rapide est essentielle pour garder le veau tendre.',
 'Plat romain par excellence, mentionné dans la littérature italienne depuis le XIXe siècle.'),

('La Ribollita Toscane',
 'Ribollita Toscane', 'La soupe paysanne florentine rebouille avec du pain rassis et du cavolo nero', '🥬', '30', '60', '6', 'facile', '~7€',
 '[{"qty":"200g","item":"haricots cannellini (secs, trempés la veille)"},{"qty":"1 bouquet","item":"cavolo nero (chou noir toscan) ou chou frisé"},{"qty":"2 carottes, 2 tiges céleri","item":"1 oignon"},{"qty":"400g","item":"tomates pelées"},{"qty":"300g","item":"pain toscan rassis (sans sel)"},{"qty":"4 gousses","item":"ail"},{"qty":"romarin, sauge, thym","item":""},{"qty":"huile d''olive","item":"généreusement"}]',
 '["Cuisez les haricots trempés 90 min jusqu''à tendreté. Réservez avec leur eau.","Faites revenir oignon, carottes et céleri dans l''huile 10 min.","Ajoutez l''ail, les herbes, les tomates. Cuisez 10 min.","Ajoutez le cavolo nero haché, les haricots avec leur eau de cuisson.","Laissez mijoter 30 min. Écrasez partiellement les haricots pour épaissir.","Ajoutez le pain rassis en morceaux, mélangez et laissez absorber.","La ribollita (« re-bouilli ») est encore meilleure réchauffée le lendemain.","Servez avec un filet généreux d''huile d''olive nouvelle et du poivre noir."]',
 'La ribollita est littéralement meilleure le lendemain — le nom le dit ! Préparez-la toujours à l''avance.',
 'Née de la cucina povera toscane médiévale : les servants récupéraient les restes de soupe des banquets nobles et les « rebouillaient » avec du pain rassis.'),

('La Torta Caprese',
 'Torta Caprese al Cioccolato', 'Le gâteau au chocolat et aux amandes de Capri, sans farine, fondant', '🍫', '20', '35', '8', 'facile', '~8€',
 '[{"qty":"200g","item":"chocolat noir 70% minimum"},{"qty":"200g","item":"beurre"},{"qty":"4","item":"œufs"},{"qty":"200g","item":"sucre"},{"qty":"200g","item":"amandes en poudre"},{"qty":"1 pincée","item":"sel"},{"qty":"sucre glace","item":"pour décorer"}]',
 '["Préchauffez le four à 170°C. Beurrez et farinez un moule de 22cm.","Faites fondre le chocolat avec le beurre au bain-marie. Laissez tiédir.","Séparez les blancs des jaunes.","Fouettez les jaunes avec le sucre jusqu''à blanchiment.","Incorporez le chocolat fondu tiède, puis la poudre d''amandes.","Montez les blancs en neige ferme avec une pincée de sel.","Incorporez délicatement les blancs en 3 fois (mouvement de bas en haut).","Enfournez 30-35 min — le cœur doit rester légèrement humide. Saupoudrez de sucre glace."]',
 'La torta caprese doit être sous-cuite : le cœur légèrement fondant est une caractéristique, pas une erreur.',
 'Créée par accident en 1920 par le cuisinier Carmine Di Fiore sur l''île de Capri, qui aurait oublié d''ajouter la farine.'),

('Le Cannolo Sicilien',
 'Cannolo Siciliano', 'La pâtisserie iconique de Sicile : tube croustillant fourré à la ricotta', '🧁', '60', '15', '12', 'difficile', '~9€',
 '[{"qty":"Coques: 200g farine 00","item":"+ 1 c.s. sucre + saindoux + 50ml marsala"},{"qty":"huile","item":"pour friture"},{"qty":"Farce: 500g ricotta fraîche de brebis","item":"(égouttée 24h si possible)"},{"qty":"150g","item":"sucre glace"},{"qty":"50g","item":"pistaches hachées"},{"qty":"50g","item":"écorces d''orange confites"}]',
 '["Pâte des coques : mélangez farine, sucre, sel, saindoux. Incorporez le marsala jusqu''à pâte lisse. Filmez, réfrigérez 1h.","Étalez très finement (2mm). Découpez des disques de 12cm.","Enroulez chaque disque autour d''un tube métal, scellez le bord avec du blanc d''œuf.","Faites frire à 180°C pendant 3-4 min. Retirez les tubes immédiatement. Laissez refroidir.","Farce : mixez la ricotta égouttée avec le sucre glace jusqu''à crème lisse.","Incorporez les pistaches, les écorces et le chocolat.","Garnissez les coques à la dernière minute (sinon elles ramollissent).","Saupoudrez de sucre glace et décorez les extrémités de pistache."]',
 'Ne garnissez les cannoli qu''au dernier moment — une coque garnie à l''avance devient molle et perd tout son intérêt.',
 'Le cannolo siciliano est consommé depuis le Xe siècle. Son nom vient de « canna » (roseau) car les coques étaient originellement roulées autour de roseaux coupés.'),

-- ===== JAPANESE PATH =====
('La Soupe Miso',
 'Soupe Miso Maison', 'L''âme de la cuisine japonaise : dashi et miso en harmonie parfaite', '🍜', '10', '10', '4', 'facile', '~4€',
 '[{"qty":"1L","item":"dashi (kombu + katsuobushi)"},{"qty":"60g","item":"pâte miso (shiromiso ou awasemiso)","tip":"Ne jamais faire bouillir le miso"},{"qty":"200g","item":"tofu soyeux en dés"},{"qty":"2","item":"ciboules émincées"},{"qty":"10g","item":"wakamé (algue séchée)"}]',
 '["Préparez le dashi : chauffez 1L d''eau avec un carré de kombu (10x10cm) à 60°C pendant 20 min. Retirez le kombu.","Portez à 85°C, ajoutez 20g de katsuobushi, retirez du feu. Infusez 5 min, filtrez.","Faites tremper le wakamé 5 min dans l''eau froide.","Portez le dashi à frémissement (pas ébullition).","Ajoutez le tofu en dés et le wakamé essoré.","Hors du feu, dissolvez le miso dans une louche de dashi, reversez dans la casserole.","Ne jamais faire bouillir après l''ajout du miso.","Servez dans des bols laqués avec la ciboule."]',
 'La règle d''or : ne JAMAIS faire bouillir le miso. L''ébullition détruit les ferments vivants et les arômes délicats.',
 'Au Japon, la soupe miso est le repas du matin depuis des siècles. Les moines bouddhistes en consommaient dès le XIIe siècle.'),

('Les Gyoza',
 'Gyoza Maison', 'Les raviolis japonais croustillants-vapeur, la recette complète', '🥟', '60', '20', '30', 'moyen', '~8€',
 '[{"qty":"300g","item":"porc haché gras"},{"qty":"150g","item":"chou chinois"},{"qty":"2 cm","item":"gingembre frais râpé"},{"qty":"3 gousses","item":"ail écrasé"},{"qty":"2 tiges","item":"ciboule émincée"},{"qty":"2 c.s.","item":"sauce soja + 1 c.s. huile de sésame"},{"qty":"30 feuilles","item":"gyoza (Gyoza-no-kawa)"},{"qty":"Sauce: soja + vinaigre de riz","item":"+ huile de piment"}]',
 '["Effeuillez le chou, salez, attendez 10 min, essorez vigoureusement.","Mélangez viande, chou, gingembre, ail, ciboule, soja, sésame.","Façonnage : mouiller le bord d''une feuille, poser 1 c.c. de farce, plier en demi-lune.","Faire 5-6 petits plis sur un bord pour sceller.","Dans une poêle antiadhésive, chauffez l''huile à feu moyen-vif.","Disposez les gyoza à plat, faites dorer le fond 2-3 min.","Versez 80ml d''eau, couvrez immédiatement. Cuisez à la vapeur 6 min.","Retirez le couvercle, laissez s''évaporer jusqu''à croustillant."]',
 'L''astuce des gyoza parfaits : la technique frit + vapeur. La vapeur cuit la farce, puis l''eau s''évapore pour créer la croûte croustillante.',
 'Les gyoza sont une adaptation japonaise des jiaozi chinois, introduits au Japon après la 2e Guerre mondiale par les soldats rentrant de Mandchourie.'),

('Le Tonkatsu',
 'Tonkatsu', 'Escalope de porc panée japonaise, croustillante et tendre', '🥩', '20', '15', '2', 'facile', '~10€',
 '[{"qty":"2","item":"côtelettes de porc (2cm épaisseur)"},{"qty":"100g","item":"panko (chapelure japonaise)","tip":"La clé du croustillant"},{"qty":"50g","item":"farine"},{"qty":"2","item":"œufs battus"},{"qty":"huile","item":"pour friture"},{"qty":"Sauce: 3 c.s. Worcestershire","item":"+ 3 c.s. ketchup + soja + sucre"},{"qty":"chou émincé très fin","item":"pour servir"}]',
 '["Entaillez les nerfs sur les bords des côtelettes (évite qu''elles se recroquevillent).","Aplatissez légèrement avec un attendrisseur.","Salez, poivrez. Passez successivement dans farine, œuf battu, panko.","Appuyez bien le panko pour qu''il adhère.","Faites frire à 170°C pendant 4 min de chaque côté jusqu''à doré profond.","Égouttez sur papier absorbant 2 min.","Sauce tonkatsu : mélangez tous les ingrédients de la sauce.","Tranchez en lanières de 2cm, servez sur riz avec chou émincé et sauce."]',
 'La température de l''huile est critique : 170°C. Trop chaud = extérieur brûlé, intérieur cru. Un thermomètre est indispensable.',
 'Le tonkatsu est apparu au Japon à la fin du XIXe siècle, fusion de la technique de panure occidentale et du goût japonais.'),

('L''Oyakodon',
 'Oyakodon', 'Le bol réconfortant poulet-œuf sur riz, la recette familiale japonaise', '🍳', '15', '15', '2', 'facile', '~6€',
 '[{"qty":"300g","item":"filet de poulet en dés"},{"qty":"4","item":"œufs"},{"qty":"1","item":"oignon émincé"},{"qty":"400ml","item":"dashi"},{"qty":"3 c.s.","item":"sauce soja"},{"qty":"2 c.s.","item":"mirin"},{"qty":"1 c.s.","item":"sucre"},{"qty":"400g","item":"riz japonais cuit"},{"qty":"ciboule","item":"pour garnir"}]',
 '["Mélangez dashi, soja, mirin et sucre dans une casserole (tsuyu).","Portez à frémissement. Ajoutez l''oignon émincé, cuisez 3 min.","Ajoutez les dés de poulet. Cuisez 5 min à feu moyen.","Battez légèrement 3 œufs (pas trop — on veut des stries de blanc et jaune).","Versez 2/3 des œufs sur le poulet. Couvrez, cuisez 30 secondes.","Versez le reste des œufs, couvrez encore 15 secondes (baveuse à l''intérieur).","Servez immédiatement sur du riz dans des bols.","Garnissez de ciboule."]',
 'La texture des œufs doit être mi-prise : coulante à l''intérieur. Les œufs continuent à cuire dans le bol chaud.',
 'Oyakodon signifie « bol mère et enfant » — la poule (poulet) et son œuf dans le même plat. Inventé à Tokyo en 1891.'),

('Le Katsu Curry',
 'Katsu Curry', 'Le curry japonais au tonkatsu, version réconfortante et populaire', '🍛', '30', '30', '4', 'facile', '~12€',
 '[{"qty":"2","item":"tonkatsu (escalopes panées)"},{"qty":"2 carottes, 2 pommes de terre","item":"1 oignon"},{"qty":"1 pomme","item":"râpée (secret du curry japonais !)"},{"qty":"1 cube","item":"curry japonais (S&B Golden Curry)"},{"qty":"600ml","item":"eau ou bouillon"},{"qty":"riz japonais","item":"pour servir"}]',
 '["Coupez carottes et pommes de terre en biseaux, l''oignon en demi-lunes.","Faites revenir l''oignon jusqu''à caramélisation douce (10 min).","Ajoutez carottes et pommes de terre, cuisez 3 min.","Ajoutez l''eau et la pomme râpée. Portez à ébullition.","Cuisez 15 min jusqu''à tendreté des légumes.","Hors du feu, dissolvez le cube de curry dans la casserole.","Remettez à feu doux 5 min pour épaissir.","Servez le curry sur du riz avec le tonkatsu tranché posé dessus."]',
 'La pomme râpée est le secret des curry japonais maison : elle apporte une douceur naturelle et un léger épaississement.',
 'Le curry japonais a été introduit au Japon à la fin du XIXe siècle par la Marine britannique.'),

('Les Onigiri',
 'Onigiri', 'Les triangles de riz japonais, compagnons de route du quotidien', '🍙', '30', '0', '4', 'facile', '~3€',
 '[{"qty":"400g","item":"riz japonais court grain (Koshihikari)"},{"qty":"sel","item":"pour l''eau de façonnage"},{"qty":"Garnitures au choix:","item":""},{"qty":"100g","item":"thon à l''huile + 1 c.s. mayonnaise japonaise"},{"qty":"2","item":"prunes umeboshi dénoyautées"},{"qty":"feuilles de nori","item":"pour envelopper"}]',
 '["Rincez le riz 5-6 fois jusqu''à eau claire. Cuisez selon absorption (1:1,1 eau).","Laissez reposer 10 min couvert. Mélangez délicatement.","Préparez vos garnitures choisies.","Mouillez vos mains, salez légèrement les paumes.","Prenez 80-100g de riz dans le creux de la main.","Formez un creux au centre, insérez 1 c.s. de garniture.","Refermez le riz et formez un triangle compact en 3-4 pressions fermes.","Enveloppez de nori, servez immédiatement."]',
 'La pression est la clé : trop fort = onigiri compact et sec. Trop mou = onigiri qui se défait.',
 'Les onigiri existent au Japon depuis plus de 2000 ans. Les konbini en vendent des millions chaque jour dans plus de 50 variétés.'),

('Le Poulet Teriyaki',
 'Poulet Teriyaki', 'Le classique laqué sucré-salé, la recette authentique', '🍗', '15', '15', '2', 'facile', '~8€',
 '[{"qty":"2","item":"cuisses de poulet désossées (avec peau)"},{"qty":"Sauce teriyaki: 4 c.s. sauce soja","item":"+ 4 c.s. mirin + 2 c.s. sake"},{"qty":"1 c.s.","item":"miel (facultatif)"},{"qty":"sésame et ciboule","item":"pour servir"}]',
 '["Mélangez soja, mirin et sake — c''est la base teriyaki.","Quadrillez légèrement la peau des cuisses au couteau.","Dans une poêle, faites dorer les cuisses côté peau 7 min à feu moyen-vif.","Retournez et cuisez 5 min côté chair.","Versez la sauce teriyaki dans la poêle. Laissez caraméliser 3-4 min en arrosant souvent.","La sauce doit napper le poulet d''un laque brillant.","Laissez reposer 2 min. Tranchez en biais.","Servez sur riz avec sésame et ciboule."]',
 'Le secret du teriyaki : l''arrosage constant. Nappez la viande de sauce pendant qu''elle caramélise — c''est ça qui crée l''effet laqué brillant.',
 '« Teri » signifie brillant et « yaki » désigne la cuisson à la chaleur sèche. Cette technique existe au Japon depuis le XVIIe siècle.'),

('L''Udon en Bouillon',
 'Udon Kake', 'Les grosses nouilles de blé dans un bouillon dashi-soja délicat', '🍜', '15', '15', '2', 'facile', '~5€',
 '[{"qty":"200g","item":"udon frais (ou 4 blocs udon surgelés)"},{"qty":"Bouillon kake: 600ml dashi","item":"+ 2 c.s. sauce soja claire + 2 c.s. mirin + 1 c.c. sel"},{"qty":"Garnitures au choix:","item":"ciboule, kamaboko, nori, gingembre râpé"}]',
 '["Cuisez les udon frais 3 min dans l''eau bouillante non salée. Rincez à l''eau froide, égouttez.","Préparez le bouillon kake : chauffez dashi + soja clair + mirin + sel.","Réchauffez les udon en les plongeant 30 secondes dans de l''eau bouillante.","Disposez les udon chauds dans des bols profonds.","Versez le bouillon chaud sur les nouilles.","Ajoutez les garnitures choisies.","Servez immédiatement — les udon ramollissent vite.","En option : ajoutez un œuf poché ou mollet."]',
 'Les udon tolèrent un peu mieux le temps dans le bouillon que le ramen. Les Japonais slurpent bruyamment : c''est un compliment.',
 'Les udon sont nés dans la région de Sanuki (actuel Kagawa) sur l''île de Shikoku, qui reste la capitale mondiale de l''udon.'),

('L''Okonomiyaki',
 'Okonomiyaki', 'La « pizza japonaise » — galette moelleuse au chou, garnie à volonté', '🥞', '20', '20', '2', 'facile', '~8€',
 '[{"qty":"200g","item":"farine"},{"qty":"200ml","item":"dashi froid"},{"qty":"2","item":"œufs"},{"qty":"1/2","item":"chou blanc émincé très fin"},{"qty":"150g","item":"blancs de crevettes ou lardons"},{"qty":"Sauces: sauce okonomiyaki","item":"+ mayonnaise japonaise Kewpie"},{"qty":"katsuobushi","item":"+ aonori pour décorer"}]',
 '["Mélangez farine, dashi et œufs jusqu''à pâte lisse. Ne pas trop travailler.","Incorporez le chou émincé.","Chauffez une poêle huilée à feu moyen. Versez la pâte en cercle épais (2cm).","Disposez crevettes ou lardons sur le dessus.","Cuisez 5 min jusqu''à dorure en dessous.","Retournez délicatement avec deux spatules. Cuisez encore 5 min.","Nappez de sauce okonomiyaki et de mayonnaise en zig-zag.","Parsemez de katsuobushi et d''aonori. Servez dans la poêle."]',
 'Le katsuobushi « danse » sur l''okonomiyaki chaud grâce à la chaleur : c''est l''une des images les plus satisfaisantes de la cuisine japonaise.',
 'L''okonomiyaki (« ce qu''on aime grillé ») existe en deux versions rivales : Osaka-yaki et Hiroshima-yaki. La guerre des styles est une source de fierté régionale intense.'),

('Les Mochi Maison',
 'Mochi au Thé Vert', 'Gâteaux de riz glutineux au matcha, fondants et lisses', '🍡', '30', '15', '12', 'moyen', '~5€',
 '[{"qty":"200g","item":"farine de riz glutineux (mochiko)"},{"qty":"200ml","item":"eau"},{"qty":"100g","item":"sucre"},{"qty":"2 c.s.","item":"matcha cérémonie"},{"qty":"200g","item":"pâte d''azuki (an) sucrée pour la garniture"},{"qty":"fécule de pomme de terre","item":"pour saupoudrer"}]',
 '["Mélangez mochiko, sucre, matcha et eau dans une casserole.","Cuisez à feu moyen en remuant constamment jusqu''à consistance épaisse et brillante (10 min).","La pâte est prête quand elle se décolle des bords.","Saupoudrez généreusement votre plan de travail de fécule.","Étalez la pâte chaude (attention brûlant) en couche de 5mm.","Découpez des cercles de 8cm avec un emporte-pièce.","Posez une boule d''azuki au centre, refermez en pinçant les bords.","Conservez à température ambiante max 24h (le réfrigérateur durcit le mochi)."]',
 'La pâte de mochi est extrêmement collante. Travaillez avec des mains bien farinées et des ustensiles huilés.',
 'Le mochi est utilisé dans les cérémonies japonaises depuis plus de 1000 ans. Le pilonnage rituel du riz est une tradition du Nouvel An japonais.'),

('Le Shabu-Shabu',
 'Shabu-Shabu', 'La fondue japonaise : viande de wagyu et légumes trempés dans un bouillon délicat', '🥩', '30', '20', '4', 'facile', '~35€',
 '[{"qty":"600g","item":"viande de bœuf wagyu tranchée très finement","tip":"Tranches de 2mm"},{"qty":"1L","item":"dashi clair"},{"qty":"200g","item":"tofu ferme en dés"},{"qty":"200g","item":"champignons (shiitake, enoki)"},{"qty":"chou nappa et jeunes pousses","item":""},{"qty":"Sauces: ponzu (soja + yuzu)","item":"+ goma dare (sauce sésame)"}]',
 '["Disposez joliment tous les ingrédients dans des assiettes séparées.","Versez le dashi dans le poêlon. Portez à frémissement à table.","Technique : saisissez une tranche de viande, plongez 3-5 secondes dans le bouillon en faisant des va-et-vient.","La viande doit rester rosée — ne la cuisez pas trop.","Trempez dans la sauce de votre choix : ponzu (frais) ou goma dare (crémeux).","Cuisez les légumes et le tofu plus longtemps (3-5 min).","Le bouillon s''enrichit au fil du repas.","En fin de repas : ajoutez du riz ou des udon dans le bouillon."]',
 'Le shabu-shabu se nomme d''après le son de la viande dans le bouillon. La qualité du dashi et de la viande est primordiale.',
 'Le shabu-shabu est arrivé au Japon via la Chine dans les années 1950. Son nom a été déposé par le restaurant Suehiro d''Osaka en 1952.'),

('Le Karaage',
 'Karaage', 'Le poulet frit japonais, mariné au gingembre et soja, doublement frit', '🍗', '20', '15', '4', 'facile', '~9€',
 '[{"qty":"600g","item":"cuisses de poulet désossées"},{"qty":"Marinade: 3 c.s. sauce soja","item":"+ 2 c.s. sake + gingembre + ail + huile de sésame"},{"qty":"100g","item":"fécule de pomme de terre (katakuriko)","tip":"Pas de farine — la fécule donne l''aspect craquant"},{"qty":"huile pour friture","item":""},{"qty":"citron et mayonnaise japonaise","item":"pour servir"}]',
 '["Coupez le poulet en morceaux de 4cm. Mélangez avec tous les ingrédients de la marinade.","Laissez mariner 30 min minimum (1h idéal).","Enrobez généreusement de fécule de pomme de terre. Secouez l''excès.","1ère friture à 160°C pendant 4 min : l''intérieur cuit.","Sortez, laissez reposer 5 min.","2ème friture à 180°C pendant 2 min : la croûte devient ultra-croustillante.","Égouttez sur papier absorbant. Salez légèrement.","Servez avec quartiers de citron et mayonnaise japonaise."]',
 'La double friture est le secret absolu. La première cuisson à basse température cuit la viande, la deuxième crée la croûte légère qui ne ramollit pas.',
 'Le karaage est la version japonaise du poulet frit, adapté dès les années 1930. C''est l''une des trois recettes les plus googlelisées au Japon.'),

('Le Takoyaki',
 'Takoyaki', 'Les boulettes de pieuvre d''Osaka, croustillantes dehors, fondantes dedans', '🐙', '30', '20', '24', 'moyen', '~8€',
 '[{"qty":"Pâte: 200g farine","item":"+ 600ml dashi + 2 œufs + 1 c.s. sauce soja"},{"qty":"200g","item":"poulpe cuit en dés de 1cm"},{"qty":"ciboule émincée et tenkasu","item":"(tempura crumbs)"},{"qty":"gingembre rouge","item":"(beni shoga)"},{"qty":"Sauces: sauce takoyaki","item":"+ mayonnaise japonaise + katsuobushi + aonori"}]',
 '["Mélangez pâte : farine + dashi + œufs + soja jusqu''à lisse.","Chauffez votre plaque à takoyaki bien huilée.","Versez la pâte pour remplir toutes les alvéoles en débordant légèrement.","Ajoutez rapidement poulpe, ciboule, tenkasu et beni shoga dans chaque alvéole.","Quand les bords commencent à cuire (2 min), retournez à 90° avec une brochette.","Continuez à tourner toutes les 30 secondes pour obtenir une boule parfaite.","Cuisez 5-6 min au total jusqu''à dorure uniforme.","Servez immédiatement avec sauce, mayo, katsuobushi et aonori."]',
 'La technique de rotation des takoyaki demande de la pratique. Utilisez deux brochettes simultanément et retournez d''un geste sûr.',
 'Le takoyaki est l''emblème de la street food d''Osaka, inventé en 1935 par Tomekichi Endo.'),

('Le Matcha Parfait',
 'Parfait Matcha Japonais', 'La tour de glaces, gelée, haricots et mochi — le dessert de salon de thé', '🍵', '30', '10', '2', 'moyen', '~8€',
 '[{"qty":"500ml","item":"glace matcha (ou crème glacée vanille + 4 c.c. matcha)"},{"qty":"Gelée matcha: 4g agar-agar","item":"+ 400ml eau + 60g sucre + 2 c.c. matcha"},{"qty":"4 c.s.","item":"pâte d''azuki sucrée"},{"qty":"shiratama mochi","item":"(petites boules de mochi blanc)"},{"qty":"wafers ou cornflakes","item":"pour le croquant"},{"qty":"sirop de cassonade (kuromitsu)","item":"(facultatif)"}]',
 '["Gelée matcha : dissolvez matcha dans un peu d''eau chaude. Portez le reste d''eau à ébullition avec sucre et agar. Incorporez le matcha, versez dans un plat. Laissez figer 2h.","Shiratama : mélangez 100g de mochiko + 70ml d''eau. Formez des petites boules, cuisez 3 min dans l''eau bouillante. Plongez dans l''eau froide.","Détaillez la gelée en cubes.","Montage en verres hauts : azuki, cubes de gelée, shiratama, glace matcha.","Ajoutez wafers ou cornflakes pour le croquant.","Versez un filet de kuromitsu si désiré.","Parsemez d''une pincée de matcha tamisé.","Servez immédiatement avec une longue cuillère."]',
 'Le parfait matcha doit offrir une palette de textures : fondant (glace), gélatineux (kanten), moelleux (mochi), croustillant (wafer).',
 'Né dans les salons de thé japonais des années 1950, c''est une adaptation créative du parfait américain avec des ingrédients japonais traditionnels.')

) AS v(lesson_title, title, description, emoji, prep_time_min, cook_time_min, servings, difficulty, avg_price_eur, ingredients, instructions, chef_tip, cultural_note)
JOIN public.lessons l ON l.title = v.lesson_title
ON CONFLICT (lesson_id) DO NOTHING
;
