-- Lessons 36-50 for Mexican, Indian, Thai, Greek paths

-- ============================================================
-- MEXICAN LESSONS 36-50
-- ============================================================
INSERT INTO public.lessons (id, path_id, title, description, order_index, duration_min, difficulty, chef_tip, cultural_note, vocabulary)
SELECT gen_random_uuid(), p.id, v.title, v.description, v.order_index, v.duration_min, v.difficulty, v.chef_tip, v.cultural_note, v.vocabulary::jsonb
FROM (VALUES
  ('Le Mole Negro d Oaxaca', 'Le plus complexe des moles — 30 ingrédients, noir et profond.', 36, 180, 'advanced', 'Brûlez certains piments à la fumée noire — c est ce qui donne la couleur et l amertume caractéristiques.', 'Le mole negro d Oaxaca est considéré comme la sauce la plus complexe du monde.', '[{"term":"mole negro","definition":"mole noir aux piments brûlés — le plus profond et complexe"},{"term":"chilhuacle negro","definition":"piment séché noir d Oaxaca"}]'),
  ('Les Tlacoyos aux Fèves', 'Galettes ovales de masa fourrées de fèves, garnies de salsa et fromage frais.', 37, 30, 'beginner', 'Le tlacoyo doit être cuit sur comal jusqu à avoir des marques de grillé.', 'Le tlacoyo est un aliment de rue ancien — consommé depuis l époque préhispanique.', '[{"term":"tlacoyo","definition":"galette ovale de masa farcie"},{"term":"comal","definition":"disque de cuisson en terre cuite ou métal"}]'),
  ('Le Caldo de Res', 'Bouillon de bœuf aux légumes, maïs et piment — soupe réconfortante mexicaine.', 38, 90, 'beginner', 'La qualité des os de bœuf est déterminante — prenez des os à moelle.', 'Le caldo de res est le plat de récupération dominical mexicain.', '[{"term":"caldo","definition":"bouillon en espagnol"},{"term":"epazote","definition":"herbe mexicaine aromatique au goût pénétrant"}]'),
  ('Les Molotes Oaxaqueños', 'Beignets de masa fourrés au fromage, chorizo ou haricots — frits et croustillants.', 39, 40, 'intermediate', 'La masa doit être bien pétrie et assez humide pour ne pas craquer en pliant.', 'Les molotes sont des beignets de rue emblématiques d Oaxaca.', '[{"term":"molote","definition":"beignet oval de masa farci et frit"},{"term":"chorizo oaxaqueño","definition":"chorizo frais non séché d Oaxaca"}]'),
  ('La Tinga de Poulet', 'Effiloché de poulet en sauce tomate-chipotle — farce parfaite pour tostadas.', 40, 40, 'beginner', 'Le chipotle en conserve (adobo) donne la profondeur fumée sans chercher le piment séché.', 'La tinga est polyvalente — dans des tacos, des burritos ou sur des tostadas.', '[{"term":"tinga","definition":"viande effilochée en sauce tomate chipotle"},{"term":"chipotle en adobo","definition":"jalapeño fumé en conserve dans sauce tomate"}]'),
  ('Le Agua Fresca de Jamaica', 'Boisson fraîche à la fleur d hibiscus, eau et sucre — rafraîchissante.', 41, 15, 'beginner', 'Faites bouillir les fleurs d hibiscus pour extraire la couleur rouge intense.', 'L agua de jamaica est la boisson non alcoolisée des marchés mexicains.', '[{"term":"agua fresca","definition":"eau fraîche — boisson mexicaine non alcoolisée"},{"term":"jamaica","definition":"fleur d hibiscus séchée — hibiscus sabdariffa"}]'),
  ('Les Enchiladas Vertes', 'Tortillas roulées farcies au poulet, nappées de salsa verde et crème.', 42, 40, 'intermediate', 'La salsa verde doit être légèrement grillée au four pour un goût plus profond.', 'Les enchiladas sont un pilier de la cuisine mexicaine maison depuis l époque aztèque.', '[{"term":"enchilada","definition":"tortilla en-chile — enveloppée dans la sauce au piment"},{"term":"salsa verde","definition":"sauce verte aux tomatilles et piments verts"}]'),
  ('Le Guacamole Artisanal', 'Avocats écrasés au molcajete avec tomate, oignon et jalapeño frais.', 43, 15, 'beginner', 'Ne mixez jamais le guacamole — écrasez à la fourchette pour garder la texture.', 'Le guacamole vient du nahuatl ahuacamolli — sauce d avocat.', '[{"term":"molcajete","definition":"mortier et pilon en pierre volcanique mexicain"},{"term":"ahuacamolli","definition":"sauce d avocat en nahuatl — mot d origine du guacamole"}]'),
  ('Les Picadas Veracruzanas', 'Galettes de masa à bords relevés, garnies de salsa y haricots — Veracruz.', 44, 35, 'intermediate', 'Les bords relevés de la picada retiennent la salsa — pincez-les soigneusement.', 'Les picadas sont le plat de rue de Veracruz, port symbole du Mexique atlantique.', '[{"term":"picada","definition":"galette de masa avec bords relevés pour contenir la garniture"},{"term":"salsa veracruzana","definition":"sauce tomate épicée de Veracruz"}]'),
  ('Le Ceviche de Camarones', 'Crevettes marinées au citron vert, tomate, oignon et coriandre.', 45, 20, 'beginner', 'Laissez mariner 30 min minimum — l acide du citron dénature les protéines.', 'Le ceviche mexicain est différent du péruvien — plus de légumes et moins piquant.', '[{"term":"ceviche","definition":"poisson cru mariné dans le jus de citron"},{"term":"aguachile","definition":"ceviche mexicain très pimenté — version mexicaine intense"}]'),
  ('La Sopa Tarasca', 'Soupe de haricots pinto mixés et tomates — spécialité du Michoacán.', 46, 45, 'intermediate', 'La pâte de chile ancho frite dans l huile donne la profondeur de la soupe tarasca.', 'La sopa tarasca vient de la région tarasque (purépecha) du Michoacán.', '[{"term":"tarasca","definition":"appartenant au peuple Purépecha du Michoacán"},{"term":"chile ancho","definition":"piment pasilla rouge séché — doux et fruité"}]'),
  ('Les Antojitos Mexicains', 'Sélection de petits plats de rue — sopes, huaraches et garnachas.', 47, 60, 'intermediate', 'Chaque région du Mexique a ses antojitos spécifiques — cette recette est une introduction.', 'Antojito signifie petite envie — les plats de rue sont l âme de la cuisine mexicaine.', '[{"term":"antojito","definition":"petite envie — plat de rue mexicain"},{"term":"sope","definition":"galette épaisse de masa avec bords"},{"term":"huarache","definition":"galette de masa ovale comme une sandale"}]'),
  ('Le Ponche de Fruits', 'Boisson chaude aux fruits tropicaux, épices, piloncillo — punch de Noël mexicain.', 48, 30, 'beginner', 'La tejocote (pomme mexicaine) est l ingrédient clé du ponche authentique.', 'Le ponche de fruits est la boisson des posadas (fêtes de Noël) mexicaines.', '[{"term":"posadas","definition":"fêtes mexicaines des 9 jours avant Noël"},{"term":"tejocote","definition":"fruit mexicain entre pomme et nèfle — clé du ponche"}]'),
  ('Le Pan de Muerto', 'Pain sucré aux fleurs d anis, en forme de crâne — fête des morts.', 49, 90, 'intermediate', 'La croûte doit être beurrée et sucrée encore chaude pour qu elle soit parfaite.', 'Le pan de muerto est posé sur les autels (ofrendas) lors du Día de los Muertos.', '[{"term":"pan de muerto","definition":"pain des morts — offrande du Día de Muertos"},{"term":"ofrenda","definition":"autel orné pour les défunts lors de la fête des morts"}]'),
  ('Le Pozole Verde du Guerrero', 'Pozole au bouillon vert de tomatilles, épinards et piments — version du Guerrero.', 50, 90, 'advanced', 'Le bouillon vert doit être ajouté en fin de cuisson pour garder sa couleur vive.', 'Le Guerrero est l état mexicain célèbre pour sa version verte du pozole.', '[{"term":"pozole verde","definition":"version verte du pozole avec tomatilles et herbes"},{"term":"pepitas","definition":"graines de courge — utilisées dans le bouillon vert"}]')
) AS v(title, description, order_index, duration_min, difficulty, chef_tip, cultural_note, vocabulary)
CROSS JOIN (SELECT id FROM public.paths WHERE slug='mexican' LIMIT 1) p;

-- ============================================================
-- INDIAN LESSONS 36-50
-- ============================================================
INSERT INTO public.lessons (id, path_id, title, description, order_index, duration_min, difficulty, chef_tip, cultural_note, vocabulary)
SELECT gen_random_uuid(), p.id, v.title, v.description, v.order_index, v.duration_min, v.difficulty, v.chef_tip, v.cultural_note, v.vocabulary::jsonb
FROM (VALUES
  ('Le Murgh Makhani (Butter Chicken)', 'Poulet en sauce tomate crémeuse au beurre — le curry le plus populaire du monde.', 36, 60, 'intermediate', 'La sauce makhani doit être mixée et filtrée pour une texture parfaitement lisse et soyeuse.', 'Le butter chicken a été inventé au restaurant Moti Mahal de Delhi dans les années 1950.', '[{"term":"makhani","definition":"beurre en hindi — sauce au beurre et crème"},{"term":"tikka","definition":"morceaux de viande marinés et grillés au tandoor"}]'),
  ('Le Samosa Maison', 'Chaussons frits à la pâte de pois chiches farcis pommes de terre et petits pois épicés.', 37, 60, 'intermediate', 'La pâte doit être ferme et non souple — trop molle, les samosas absorbent l huile.', 'Le samosa est l un des snacks les plus consommés en Inde et au monde entier.', '[{"term":"samosa","definition":"chausson frit triangulaire farci"},{"term":"chaat masala","definition":"mélange d épices aigre-pimenté pour saupoudrer"}]'),
  ('Le Tandoori Murgh', 'Poulet mariné au yaourt et épices, cuit dans un four tandoor — rouge et parfumé.', 38, 30, 'intermediate', 'La marinade doit pénétrer toute la nuit minimum — entaillez profondément la chair.', 'Le poulet tandoori est né dans les années 1940 au restaurant Moti Mahal de Delhi.', '[{"term":"tandoor","definition":"four cylindrique en terre cuite à très haute température"},{"term":"tikka masala","definition":"sauce crémeuse pour le poulet tandoori — version britannique"}]'),
  ('La Salade Kachumber', 'Salade fraîche de tomates, concombre, oignon et coriandre au citron.', 39, 10, 'beginner', 'Assaisonnez avec du chaat masala pour l authenticité.', 'Le kachumber est la salade servie avec tous les repas indiens — fraîcheur et légèreté.', '[{"term":"kachumber","definition":"salade fraîche indienne de base"},{"term":"chaat masala","definition":"mélange d épices complexe — sel noir, amchur, cumin"}]'),
  ('Les Idli Sambhar', 'Gâteaux de riz cuits à la vapeur avec soupe de lentilles épicée — petit-déjeuner du Sud.', 40, 480, 'intermediate', 'La pâte d idli doit fermenter 8-12h — elle doit être légèrement acide et pétillante.', 'L idli sambhar est le petit-déjeuner national du sud de l Inde.', '[{"term":"idli","definition":"gâteau de riz cuit à la vapeur — léger et moelleux"},{"term":"sambhar","definition":"soupe de lentilles aux légumes du sud de l Inde"}]'),
  ('Le Keema Matar', 'Viande hachée aux petits pois dans une sauce épicée — plat du quotidien indien.', 41, 35, 'beginner', 'Le keema doit être bien doré avant d ajouter les épices — caramélisation essentielle.', 'Le keema matar est le plat de semaine des familles indiennes du nord.', '[{"term":"keema","definition":"viande hachée en ourdou"},{"term":"matar","definition":"petits pois en hindi"}]'),
  ('Le Fish Curry de Goa', 'Filets de poisson dans un curry rouge de noix de coco et tamarinde — côte de Malabar.', 42, 35, 'intermediate', 'Le tamarin est l acide caractéristique du curry de Goa — ne le remplacez pas par du citron.', 'Le fish curry de Goa est influencé par 450 ans de domination portugaise.', '[{"term":"Goa","definition":"état côtier indien d influence portugaise"},{"term":"kokum","definition":"fruit acide de Goa parfois utilisé à la place du tamarin"}]'),
  ('Les Papdi Chaat', 'Snack de galettes de blé croustillantes, yaourt, chutneys et pommes de terre.', 43, 20, 'beginner', 'Assemblez les papdi chaat au dernier moment — les galettes ramollissent rapidement.', 'Les chaat sont les snacks de rue les plus populaires d Inde du Nord.', '[{"term":"chaat","definition":"goûter/snack de rue indien — mélange de saveurs"},{"term":"papdi","definition":"galettes de blé frites et croustillantes"}]'),
  ('Le Mutton Rogan Josh Cachemiri', 'Mouton en sauce cachemirienne aux piments rouges et yogourt — version complète.', 44, 90, 'advanced', 'Le ratan jot (colorant rouge naturel) est l ingrédient authentique du rogan josh — cherchez-le.', 'La cuisine cachemirienne est une des plus raffinées de l Inde — influencée par la Perse.', '[{"term":"ratan jot","definition":"colorant naturel rouge d Alkanna tinctoria"},{"term":"maval","definition":"épice florale cachemirienne — comme la cardamome"}]'),
  ('La Aloo Paratha', 'Pain plat de blé farci aux pommes de terre épicées — petit-déjeuner du Punjab.', 45, 40, 'intermediate', 'Le farce doit être sèche — une farce humide troue la pâte.', 'La aloo paratha est le petit-déjeuner du Punjab — servie avec du beurre et yaourt.', '[{"term":"paratha","definition":"pain plat de blé — version farcie ou feuilletée"},{"term":"tawa","definition":"plaque de cuisson en fonte pour les chapatis et parathas"}]'),
  ('Le Pulao de Légumes', 'Riz basmati au ghee avec légumes et épices entières — le riz festif indien.', 46, 35, 'beginner', 'Faire sauter les épices entières dans le ghee libère leurs huiles essentielles.', 'Le pulao est la version simplifiée du biryani — riz cuit avec les épices dès le début.', '[{"term":"pulao","definition":"riz sauté épicé aux légumes"},{"term":"ghee","definition":"beurre clarifié indien — base de la cuisine indienne"}]'),
  ('Le Raita au Concombre', 'Yaourt épais au concombre, cumin et menthe — accompagnement frais des currys.', 47, 10, 'beginner', 'Le yogourt doit être épais — égouttez-le si nécessaire dans un linge.', 'Le raita est le contra-point frais et acide qui équilibre les currys épicés.', '[{"term":"raita","definition":"yaourt épicé — l accompagnement frais des repas indiens"},{"term":"boondi","definition":"petites perles de pâte de pois chiches frites — version boondi raita"}]'),
  ('Le Malai Kofta', 'Boulettes de pommes de terre-fromage en sauce crémeuse au safran — plat de fête végétarien.', 48, 60, 'advanced', 'Les koftas doivent être frits à feu modéré pour cuire à cœur sans brûler.', 'Le malai kofta est le plat de célébration végétarien de l Inde du Nord.', '[{"term":"malai","definition":"crème en hindi — la sauce est à la crème"},{"term":"kofta","definition":"boulette de viande ou légumes — terme d origine persane"}]'),
  ('Les Vada Pav de Mumbai', 'Beignet de pommes de terre épicé dans un petit pain — le burger de Mumbai.', 49, 40, 'beginner', 'La pâte à beignet doit être épaisse pour une croûte protectrice croustillante.', 'Le vada pav est le fast-food emblématique de Mumbai — né dans les années 1960.', '[{"term":"vada pav","definition":"beignet-pain — le burger de Mumbai"},{"term":"pav","definition":"petit pain mou d influence portugaise"}]'),
  ('Le Shahi Paneer', 'Paneer dans une sauce royale à la noix de cajou, safran et crème fraîche.', 50, 45, 'intermediate', 'La sauce doit être mixée et tamisée pour une texture royalement lisse.', 'Shahi signifie royal — le shahi paneer était le plat de la cour moghole.', '[{"term":"shahi","definition":"royal en ourdou — le plat de la cour moghole"},{"term":"paneer","definition":"fromage frais indien non fermenté"}]')
) AS v(title, description, order_index, duration_min, difficulty, chef_tip, cultural_note, vocabulary)
CROSS JOIN (SELECT id FROM public.paths WHERE slug='indian' LIMIT 1) p;

-- ============================================================
-- THAI LESSONS 36-50
-- ============================================================
INSERT INTO public.lessons (id, path_id, title, description, order_index, duration_min, difficulty, chef_tip, cultural_note, vocabulary)
SELECT gen_random_uuid(), p.id, v.title, v.description, v.order_index, v.duration_min, v.difficulty, v.chef_tip, v.cultural_note, v.vocabulary::jsonb
FROM (VALUES
  ('Le Pad Krapow Moo', 'Porc haché sauté aux feuilles de basilic sacré épicées — plat de rue #1 de Thaïlande.', 36, 15, 'beginner', 'Le basilic sacré (krapow) est différent du basilic ordinaire — cherchez-le en épicerie asiatique.', 'Le pad krapow est le plat commandé par défaut dans toute la Thaïlande — à toute heure.', '[{"term":"krapow","definition":"basilic sacré thaï — holybasil, plus poivré que le commun"},{"term":"nam pla","definition":"sauce poisson thaïe — condiment de base"}]'),
  ('Le Som Tum (Papaya Verte)', 'Salade de papaye verte râpée, piments, ail, haricots et cacahuètes — Isan.', 37, 15, 'intermediate', 'Écrasez délicatement au mortier pour meurtrir sans réduire en purée.', 'Le som tum est originaire de l Isan (nord-est) et est le plat le plus commandé en Thaïlande.', '[{"term":"som tum","definition":"salade de papaye verte — acide (som) et pilée (tum)"},{"term":"Isan","definition":"région nord-est de Thaïlande — cuisine lao-thaïe"}]'),
  ('Le Khao Man Gai', 'Poulet poché servi sur riz cuit dans le bouillon de poulet — plat thaï-hainais.', 38, 60, 'beginner', 'Le riz doit cuire dans le bouillon de poulet pour absorber ses arômes.', 'Le khao man gai est d influence hainaise (Chine du Sud) — arrivé avec les immigrants chinois.', '[{"term":"khao man gai","definition":"riz gras au poulet — plat hainais thaïlandisé"},{"term":"Hainanese","definition":"d origine Hainan — île du sud de la Chine"}]'),
  ('Le Gaeng Liang', 'Soupe végétarienne au bouillon de crevettes séchées et légumes d hiver thaïs.', 39, 30, 'beginner', 'Le gaeng liang n utilise pas de lait de coco — c est un curry léger et bouillonné.', 'Le gaeng liang est le curry le plus sain de Thaïlande — léger et végétal.', '[{"term":"gaeng liang","definition":"curry épicé des amoureux en thaï"},{"term":"krachai","definition":"petit gingembre thaï sauvage — caractéristique du gaeng liang"}]'),
  ('Le Miang Kham', 'Bouchées de feuilles de bétel garnies de noix de coco, citron vert, piment.', 40, 20, 'intermediate', 'Chaque bouchée doit contenir tous les éléments — la feuille enveloppe tout.', 'Le miang kham est une collation royale thaïlandaise — servie pour les visiteurs importants.', '[{"term":"miang kham","definition":"bouchée enveloppée — collation thaïe traditionnelle"},{"term":"bai cha plu","definition":"feuille de bétel sauvage utilisée pour envelopper"}]'),
  ('Le Kao Kha Moo', 'Pied de porc braisé à la sauce de soja foncée et cinq épices — plat sino-thaï.', 41, 180, 'intermediate', 'Le porc doit confire dans la sauce — la texture gélatineuse est la caractéristique du kao kha moo.', 'Le kao kha moo est d influence sino-thaïe — adapté par les immigrants chinois à Bangkok.', '[{"term":"kha moo","definition":"pied de porc en thaï"},{"term":"cinq épices","definition":"mélange étoile anis, cannelle, clou, fenouil, poivre de Sichuan"}]'),
  ('La Soupe Tom Kha Gai', 'Soupe lait de coco au poulet, galangal, citronnelle et kaffir — douce et parfumée.', 42, 25, 'beginner', 'Le galangal ne se mange pas — c est un aromate pour infuser, retirez-le avant de servir.', 'La tom kha gai est moins piquante que la tom yum — la noix de coco adoucit les épices.', '[{"term":"tom kha","definition":"soupe bouillie avec galangal"},{"term":"galangal","definition":"rhizome de la famille du gingembre — arôme distinct et floral"}]'),
  ('Le Pla Pao', 'Poisson entier grillé dans une croûte de sel avec lemongrass — technique du charbon.', 43, 40, 'intermediate', 'Le sel forme une croûte protectrice — le poisson cuit dans sa propre humidité.', 'Le pla pao est le plat de pique-nique des thaïlandais — grillé sur charbon en plein air.', '[{"term":"pla pao","definition":"poisson grillé en thaï"},{"term":"ta krai","definition":"citronnelle — inséré dans le ventre du poisson"}]'),
  ('Les Khao Lam', 'Riz gluant cuit dans du lait de coco dans des bambous — dessert de fête.', 44, 45, 'intermediate', 'Les bambous doivent être trempés dans l eau pour éviter qu ils brûlent.', 'Le khao lam est préparé pour les fêtes bouddhistes et les marchés de nuit en Thaïlande.', '[{"term":"khao lam","definition":"riz dans le bambou — cuit sur le feu directement"},{"term":"takian","definition":"bambou géant utilisé pour le khao lam"}]'),
  ('Le Yam Nuea Yang', 'Salade de bœuf grillé aux herbes fraîches, piment et jus de citron vert.', 45, 25, 'intermediate', 'Le bœuf doit être grillé saignant — il continue de cuire dans la sauce acide.', 'Les salades yam thaïlandaises sont toujours servies à température ambiante — jamais froides.', '[{"term":"nuea","definition":"bœuf en thaï"},{"term":"nam jim jaew","definition":"sauce de trempage pour viande grillée — piment grillé"}]'),
  ('Le Khao Niao Dam', 'Riz gluant noir à la noix de coco — dessert riche et nourrissant du nord thaï.', 46, 40, 'beginner', 'Faites tremper le riz noir 8h pour une texture optimale à la vapeur.', 'Le riz gluant noir est naturellement coloré par ses anthocyanines — riche en antioxydants.', '[{"term":"khao niao dam","definition":"riz gluant noir — dam signifie noir en thaï"},{"term":"nam kathi","definition":"lait de coco — versé chaud sur le riz cuit"}]'),
  ('Le Pad Char Talay', 'Fruits de mer sautés aux herbes fraîches et piments — wok à haute flamme.', 47, 15, 'intermediate', 'La clé est la chaleur extrême du wok — les fruits de mer cuisent en 2-3 minutes maximum.', 'Le pad char est le plat des pêcheurs thaïlandais de la côte — simple et ultra-frais.', '[{"term":"talay","definition":"mer/fruits de mer en thaï"},{"term":"grachai","definition":"petit gingembre sauvage — essentiel au pad char"}]'),
  ('Le Kaeng Tai Pla', 'Curry fermenté aux abats de poisson — spécialité très parfumée du sud thaïlandais.', 48, 45, 'advanced', 'Le kaeng tai pla est l un des plats les plus piquants et aromatiques de Thaïlande — pour initiés.', 'Le tai pla (intérieur de poisson fermenté) est un condiment du sud de la Thaïlande.', '[{"term":"tai pla","definition":"entrailles de poisson fermentées — ingrédient unique du sud thaï"},{"term":"bambou jeune","definition":"pousses de bambou fraîches — incontournables dans ce curry"}]'),
  ('Les Desserts de Rue Thaïs', 'Tour d horizon des douceurs de rue : bua loy, tub tim krob, look choup.', 49, 45, 'intermediate', 'Les desserts thaïs jouent toujours sur les textures — doux, crémeux et gélatineux.', 'La pâtisserie thaïlandaise est un art minutieux — les look choup (fruits en pâte de haricots) sont des chefs d œuvre miniatures.', '[{"term":"bua loy","definition":"boulettes de riz dans le lait de coco"},{"term":"look choup","definition":"fruits miniatures en pâte de haricots adzuki"}]'),
  ('Le Khao Pad Naem', 'Riz sauté à la saucisse fermentée du nord thaï — plat acidulé et unique.', 50, 20, 'intermediate', 'La saucisse naem fermentée doit être saisie jusqu à légèrement brûlée pour un goût intense.', 'Le naem (saucisse de porc fermentée) est une spécialité du nord de la Thaïlande.', '[{"term":"naem","definition":"saucisse fermentée du nord thaï — acide et piquante"},{"term":"kai dao","definition":"œuf au plat qui accompagne le khao pad naem"}]')
) AS v(title, description, order_index, duration_min, difficulty, chef_tip, cultural_note, vocabulary)
CROSS JOIN (SELECT id FROM public.paths WHERE slug='thai' LIMIT 1) p;

-- ============================================================
-- GREEK LESSONS 36-50
-- ============================================================
INSERT INTO public.lessons (id, path_id, title, description, order_index, duration_min, difficulty, chef_tip, cultural_note, vocabulary)
SELECT gen_random_uuid(), p.id, v.title, v.description, v.order_index, v.duration_min, v.difficulty, v.chef_tip, v.cultural_note, v.vocabulary::jsonb
FROM (VALUES
  ('La Saganaki', 'Fromage (kefalotyri ou graviera) poêlé et flambé à l ouzo ou au brandy.', 36, 10, 'beginner', 'Farinez légèrement le fromage — cela donne une croûte dorée sans que le fromage ne fonde trop.', 'Le saganaki est le plat qui s accompagne du cri Opa ! dans les tavernes grecques.', '[{"term":"saganaki","definition":"petite poêle à deux anses — donne son nom au plat"},{"term":"kefalotyri","definition":"fromage grec dur et salé — idéal pour saganaki"}]'),
  ('La Psarosoupa Avgolemono', 'Soupe de poisson à la sauce avgolemono — douce, citronnée et veloutée.', 37, 40, 'intermediate', 'Versez la sauce avgolemono dans la soupe hors feu pour éviter la coagulation.', 'La soupe avgolemono est le symbole de la cuisine grecque — simple et magnifique.', '[{"term":"psarosoupa","definition":"soupe de poisson en grec"},{"term":"avgolemono","definition":"sauce aux œufs et citron — épaissit et acidifie les soupes"}]'),
  ('Les Dolmades Feuilles de Vigne', 'Feuilles de vigne farcies au riz et herbes — servies avec sauce avgolemono.', 38, 90, 'intermediate', 'Roulez les dolmades serrées mais laissez de l espace pour que le riz gonfle.', 'Les dolmades (feuilles farcies) existent dans toute la Méditerranée et au Moyen-Orient.', '[{"term":"dolmades","definition":"feuilles farcies — dolma en turc"},{"term":"ampelofyllo","definition":"feuille de vigne en grec"}]'),
  ('Le Kokoretsi', 'Abats d agneau enfilés sur broche, enveloppés d intestins grillés.', 39, 120, 'advanced', 'Le kokoretsi doit griller lentement sur braise pendant 2h en tournant.', 'Le kokoretsi est le plat de Pâques orthodoxes — grillé la nuit de la résurrection.', '[{"term":"kokoretsi","definition":"brochette d abats d agneau enroulés d intestins"},{"term":"Pâques orthodoxes","definition":"le kokoretsi est LA tradition du dimanche de Pâques"}]'),
  ('Le Stifado de Poulpe', 'Poulpe braisé aux petits oignons, vin rouge et épices douces.', 40, 120, 'intermediate', 'Congelez le poulpe 24h avant — le froid brise les fibres et il devient tendre.', 'Le stifado (ragoût aux petits oignons) fonctionne avec du poulpe, du bœuf ou du chevreuil.', '[{"term":"stifado","definition":"ragoût aux petits oignons confits et épices"},{"term":"chtapodi","definition":"poulpe en grec"}]'),
  ('Les Spanakopita', 'Tourte feuilletée aux épinards et feta — la plus populaire des pitas grecques.', 41, 60, 'intermediate', 'Égouttez absolument les épinards — l excès d eau ramollit le phyllo.', 'La spanakopita est la pita préférée de tous les Grecs — disponible partout à toute heure.', '[{"term":"spanakopita","definition":"tourte aux épinards et feta"},{"term":"spanaki","definition":"épinards en grec"}]'),
  ('Le Bakaliaros Skordalia', 'Morue frite et sauce à l ail crémeuse — plat du Vendredi Saint grec.', 42, 30, 'intermediate', 'La skordalia maison est infiniment meilleure que l industrielle — ne la sautez pas.', 'La morue frite à la skordalia est le plat traditionnel du Vendredi Saint grec orthodoxe.', '[{"term":"bakaliaros","definition":"morue (cod) salée en grec"},{"term":"skordalia","definition":"sauce à l ail crémeuse — avec pommes de terre ou pain"}]'),
  ('Le Mousakas Végétarien', 'Version végétarienne du mousakas — aubergines, champignons et béchamel.', 43, 90, 'intermediate', 'Les aubergines doivent être bien grillées avant le montage — élimine l excès d eau.', 'Le mousakas végétarien est aussi riche et savoureux que l original avec la viande.', '[{"term":"mousakas","definition":"gratin d aubergines à la viande hachée et béchamel"},{"term":"sfela","definition":"fromage grec fumé qui peut s intégrer au mousakas végétarien"}]'),
  ('La Manestra', 'Orzo cuit dans une sauce tomate avec légumes — risotto grec à l orzo.', 44, 40, 'beginner', 'L orzo absorbe beaucoup de liquide — ajoutez le bouillon graduellement.', 'La manestra est le plat de la semaine dans chaque famille grecque — économique et délicieux.', '[{"term":"manestra","definition":"orzo — pâtes en forme de grains de riz"},{"term":"orzo","definition":"petites pâtes en grain de riz — base de la manestra"}]'),
  ('Les Thrapsalo (Calamars Farcis)', 'Calamars entiers farcis de riz, herbes et pignons — cuits au four.', 45, 60, 'intermediate', 'Remplissez les calamars aux 2/3 seulement — le riz gonfle à la cuisson.', 'Les calamars farcis sont un classique des tavernes des îles grecques.', '[{"term":"thrapsalo","definition":"calamar en dialecte crétois"},{"term":"kalamari","definition":"calamar en grec standard"}]'),
  ('Les Melitzanosalata', 'Caviar d aubergines grillées à la flamme — dip fumé et crémeux.', 46, 30, 'beginner', 'Brûlez les aubergines directement sur la flamme pour le goût fumé authentique.', 'La melitzanosalata est une mezze classique — servie avec du pain pita et des légumes.', '[{"term":"melitzanosalata","definition":"salade d aubergines grillées"},{"term":"melitzana","definition":"aubergine en grec"}]'),
  ('Le Tsoureki', 'Brioche grecque tressée parfumée à la mahlab et mastika — Pâques et Noël.', 47, 180, 'advanced', 'La pâte doit lever longtemps à température ambiante — la mahlab est l arôme clé.', 'Le tsoureki est la brioche des grandes fêtes orthodoxes — tressée et magnifique.', '[{"term":"tsoureki","definition":"brioche tressée grecque parfumée"},{"term":"mahlab","definition":"noyau de cerise de Sainte-Lucie — arôme floral du tsoureki"}]'),
  ('La Galaktoboureko', 'Crème semoule en feuilles de phyllo, sirop de citron et miel — pâtisserie de fête.', 48, 60, 'intermediate', 'Versez le sirop froid sur la pâtisserie chaude — le choc thermique permet l absorption.', 'La galaktoboureko est la pâtisserie crémeuse la plus populaire de Grèce après le baklava.', '[{"term":"galaktoboureko","definition":"crème de lait dans le phyllo"},{"term":"souvlaki","definition":"brochettes — rien à voir, mais terme grec festif"}]'),
  ('Les Vradia Sarakosti', 'Menu complet du jeûne orthodoxe — légumes, légumineuses, sans viande ni produits laitiers.', 49, 90, 'intermediate', 'Les plats de Carême grecs sont naturellement végétaliens — huile d olive, légumes et légumineuses.', 'La tradition de jeûne orthodoxe 180 jours par an a façonné toute la cuisine grecque.', '[{"term":"Sarakosti","definition":"le Carême orthodoxe — 40 jours de jeûne"},{"term":"nisteia","definition":"jeûne orthodoxe — s abstenir des produits animaux"}]'),
  ('Le Mezes Complet', 'Grand assortiment de mezze — dips, fromages, charcuteries et snacks grecs.', 50, 30, 'intermediate', 'L ordre traditionnel est : dips puis fromages puis charcuteries — la varieté est clé.', 'Le mezze est la culture du partage grec — manger ensemble, goûter à tout, prendre son temps.', '[{"term":"mezze","definition":"petits plats partagés — de l arabe maza (goûter)"},{"term":"ouzeri","definition":"bar à ouzo servant des mezze — institution grecque"}]')
) AS v(title, description, order_index, duration_min, difficulty, chef_tip, cultural_note, vocabulary)
CROSS JOIN (SELECT id FROM public.paths WHERE slug='greek' LIMIT 1) p;

-- ============================================================
-- EXERCISES FOR MEXICAN LESSONS 36-50
-- ============================================================
INSERT INTO public.exercises (id, lesson_id, type, question, options, correct_answer, explanation, order_index)
SELECT gen_random_uuid(), l.id, v.type, v.question, v.options::jsonb, v.correct_answer, v.explanation, v.order_index
FROM (VALUES
  ('Le Mole Negro d Oaxaca', 'multiple_choice', 'Combien d ingrédients peut compter le mole negro d Oaxaca ?', '["Jusqu à 30","5-10","15","50 minimum"]', 'Jusqu à 30', 'Le mole negro est la sauce la plus complexe du Mexique — certaines recettes comptent 30 ingrédients.', 1),
  ('Le Mole Negro d Oaxaca', 'fill_in_blank', 'Le mole negro est noir grâce aux piments ___', '[]', 'brûlés', 'Certains piments sont carbonisés intentionnellement — c est ce qui donne la couleur noire et l amertume.', 2),
  ('Les Tlacoyos aux Fèves', 'multiple_choice', 'Sur quoi cuit-on traditionnellement les tlacoyos ?', '["Sur un comal","Dans une poêle","Au four","À la vapeur"]', 'Sur un comal', 'Le comal est la plaque de cuisson mexicaine — utilisée pour les tortillas et antojitos.', 1),
  ('Les Tlacoyos aux Fèves', 'fill_in_blank', 'Le tlacoyo est une galette ___ de masa farcie', '[]', 'ovale', 'La forme ovale du tlacoyo est caractéristique — différente des galettes rondes.', 2),
  ('La Tinga de Poulet', 'multiple_choice', 'Quel est l ingrédient fumé caractéristique de la tinga ?', '["Chipotle en adobo","Jalapeño frais","Piment guajillo","Ancho séché"]', 'Chipotle en adobo', 'Le chipotle (jalapeño fumé) en conserve dans l adobo apporte la saveur fumée signature de la tinga.', 1),
  ('La Tinga de Poulet', 'fill_in_blank', 'La tinga est parfaite pour garnir des ___', '[]', 'tostadas', 'Les tostadas (tortillas grillées croustillantes) accueillent la tinga avec ses garnitures fraîches.', 2),
  ('L Agua Fresca de Jamaica', 'multiple_choice', 'Qu est-ce que la jamaica ?', '["Fleur d hibiscus séchée","Un agrume jamaïcain","Un extrait de canne","Un fruit tropical rouge"]', 'Fleur d hibiscus séchée', 'La jamaica (hibiscus sabdariffa) est une fleur séchée qui donne une boisson rouge rubis acidulée.', 1),
  ('L Agua Fresca de Jamaica', 'fill_in_blank', 'L agua fresca est une ___ non alcoolisée mexicaine', '[]', 'boisson', 'Les aguas frescas mexicaines sont faites de fruits, fleurs ou graines mixés à l eau et sucrés.', 2),
  ('Les Enchiladas Vertes', 'multiple_choice', 'De quoi est faite la salsa verde mexicaine ?', '["Tomatilles et piments verts","Avocats","Jalapeños et citron","Herbes fraîches mixées"]', 'Tomatilles et piments verts', 'La salsa verde mexicaine utilise des tomatilles (tomates vertes mexicaines) — pas des tomates ordinaires.', 1),
  ('Les Enchiladas Vertes', 'fill_in_blank', 'Enchilada signifie tortilla ___ en espagnol', '[]', 'en-chile', 'Enchilada vient de en-chilar (tremper dans le chile) — les tortillas sont nappées de sauce pimentée.', 2),
  ('Le Guacamole Artisanal', 'multiple_choice', 'D où vient le mot guacamole ?', '["Du nahuatl ahuacamolli","De l espagnol","Du maya","De l anglais avocado sauce"]', 'Du nahuatl ahuacamolli', 'Ahuacatl (avocat) + molli (sauce) en nahuatl — langue des Aztèques.', 1),
  ('Le Guacamole Artisanal', 'fill_in_blank', 'Le mortier et pilon en pierre volcanique mexicain s appelle ___', '[]', 'molcajete', 'Le molcajete est l outil traditionnel pour préparer le guacamole — jamais le mixeur.', 2),
  ('Le Ceviche de Camarones', 'multiple_choice', 'Comment le citron vert cuit-il les crevettes dans le ceviche ?', '["En dénaturant les protéines (acide citrique)","En cuisson thermique","En fermentation","En salage"]', 'En dénaturant les protéines (acide citrique)', 'L acide citrique change la structure des protéines comme la chaleur — c est une cuisson chimique.', 1),
  ('Le Ceviche de Camarones', 'fill_in_blank', 'La version ultra-pimentée du ceviche mexicain s appelle ___', '[]', 'aguachile', 'L aguachile est du ceviche dans de l eau de piment vert frais — très piquant et vif.', 2),
  ('Le Pan de Muerto', 'multiple_choice', 'Pour quelle fête prépare-t-on le pan de muerto ?', '["Día de los Muertos","Noël","Pâques mexicaine","Cinco de Mayo"]', 'Día de los Muertos', 'Le pan de muerto est posé sur les ofrendas (autels) le 1-2 novembre pour la fête des morts.', 1),
  ('Le Pan de Muerto', 'fill_in_blank', 'L autel orné pour les défunts lors de la fête des morts s appelle une ___', '[]', 'ofrenda', 'L ofrenda contient photos, fleurs de cempasúchil, nourriture et objets du défunt.', 2),
  ('Le Pozole Verde du Guerrero', 'multiple_choice', 'De quel état mexicain vient le pozole verde ?', '["Guerrero","Jalisco","Oaxaca","Mexico"]', 'Guerrero', 'Le Guerrero est renommé pour son pozole verde — le rouge est de Jalisco.', 1),
  ('Le Pozole Verde du Guerrero', 'fill_in_blank', 'Les graines de courge utilisées dans le bouillon vert s appellent ___', '[]', 'pepitas', 'Les pepitas (graines de courge mexicaines) donnent de la richesse et de la couleur au bouillon vert.', 2),
  ('Les Molotes Oaxaqueños', 'multiple_choice', 'Les molotes sont des beignets de quelle ville mexicaine ?', '["Oaxaca","Puebla","Mexico","Guadalajara"]', 'Oaxaca', 'Les molotes sont emblématiques des marchés de rue d Oaxaca.', 1),
  ('Les Molotes Oaxaqueños', 'fill_in_blank', 'Le chorizo frais non séché d Oaxaca s appelle ___', '[]', 'chorizo oaxaqueño', 'Le chorizo oaxaqueño est frais et doux — différent du chorizo sec d Espagne ou du nord du Mexique.', 2),
  ('Le Caldo de Res', 'multiple_choice', 'Quel type d os est idéal pour le caldo de res ?', '["Os à moelle","Os de poulet","Os de porc","Os de jarret"]', 'Os à moelle', 'Les os à moelle donnent un bouillon riche et gélatineux — la base d un caldo parfait.', 1),
  ('Le Caldo de Res', 'fill_in_blank', 'Le caldo de res est traditionnellement mangé le ___ en famille', '[]', 'dimanche', 'Le dimanche est le jour du grand repas familial mexicain — le caldo est souvent au menu.', 2),
  ('Les Picadas Veracruzanas', 'multiple_choice', 'Quelle est la particularité des picadas par rapport aux autres galettes ?', '["Leurs bords relevés pour contenir la garniture","Leur taille plus grande","Leur pâte plus épaisse","Elles ne sont pas cuites au comal"]', 'Leurs bords relevés pour contenir la garniture', 'Les bords pincés des picadas retiennent la salsa et les garnitures — fonctionnalité essentielle.', 1),
  ('Les Picadas Veracruzanas', 'fill_in_blank', 'Veracruz est un port symbole du Mexique ___', '[]', 'atlantique', 'Veracruz est le principal port de la côte atlantique mexicaine — porte de l Amérique centrale.', 2),
  ('La Sopa Tarasca', 'multiple_choice', 'De quel peuple indigène vient le nom tarasca ?', '["Purépecha","Aztèque","Maya","Mixtèque"]', 'Purépecha', 'Les Purépecha étaient aussi appelés Tarasques par les Espagnols — leur civilisation au Michoacán.', 1),
  ('La Sopa Tarasca', 'fill_in_blank', 'Le piment ___ séché et frit dans l huile donne la profondeur de la sopa tarasca', '[]', 'ancho', 'Le chile ancho (pasilla rouge séché) apporte des notes fruitées et profondes à la soupe.', 2),
  ('Les Antojitos Mexicains', 'multiple_choice', 'Que signifie antojito en espagnol ?', '["Petite envie","Petit pain","Petit plat","Petite bouchée"]', 'Petite envie', 'Antojito vient d antojo (envie, caprice) — c est la nourriture de l envie et du plaisir immédiat.', 1),
  ('Les Antojitos Mexicains', 'fill_in_blank', 'La galette de masa ovale comme une sandale s appelle ___', '[]', 'huarache', 'Le huarache (sandale) ressemble à une semelle de cuir — garni de haricots, salsa et garnitures.', 2),
  ('Le Ponche de Fruits', 'multiple_choice', 'Lors de quelles fêtes mexicaines boit-on le ponche ?', '["Les posadas (fêtes de Noël)","Le Ramadan","La Toussaint","Pâques"]', 'Les posadas (fêtes de Noël)', 'Les posadas sont les 9 soirées de fête avant Noël au Mexique — avec piñatas et ponche.', 1),
  ('Le Ponche de Fruits', 'fill_in_blank', 'Le fruit mexicain clé du ponche entre une pomme et une nèfle s appelle ___', '[]', 'tejocote', 'La tejocote (Crataegus mexicana) est un fruit mexicain indispensable au ponche de Navidad.', 2)
) AS v(lesson_title, type, question, options, correct_answer, explanation, order_index)
JOIN public.lessons l ON l.title = v.lesson_title;

-- ============================================================
-- EXERCISES FOR INDIAN LESSONS 36-50
-- ============================================================
INSERT INTO public.exercises (id, lesson_id, type, question, options, correct_answer, explanation, order_index)
SELECT gen_random_uuid(), l.id, v.type, v.question, v.options::jsonb, v.correct_answer, v.explanation, v.order_index
FROM (VALUES
  ('Le Murgh Makhani (Butter Chicken)', 'multiple_choice', 'Où a été inventé le butter chicken ?', '["Moti Mahal à Delhi","Taj Mahal à Mumbai","Bukhara à Delhi","Chez une ménagère du Punjab"]', 'Moti Mahal à Delhi', 'Le butter chicken (murgh makhani) a été créé par Kundan Lal Gujral au Moti Mahal de Delhi.', 1),
  ('Le Murgh Makhani (Butter Chicken)', 'fill_in_blank', 'La sauce makhani doit être ___ et filtrée pour une texture parfaite', '[]', 'mixée', 'Le mixage et le filtrage éliminent les fibres de tomate et donnent une texture soyeuse.', 2),
  ('Le Samosa Maison', 'multiple_choice', 'Comment doit être la pâte à samosa ?', '["Ferme et non souple","Souple et élastique","Collante","Très molle"]', 'Ferme et non souple', 'Une pâte ferme absorbe moins d huile à la friture — les samosas resteront secs et croustillants.', 1),
  ('Le Samosa Maison', 'fill_in_blank', 'Le mélange d épices aigre-pimenté pour saupoudrer les chaat s appelle ___', '[]', 'chaat masala', 'Le chaat masala contient sel noir, amchur, cumin, piment — il acidifie et pimenté instantanément.', 2),
  ('Le Tandoori Murgh', 'multiple_choice', 'À quelle température cuit le four tandoor ?', '["Plus de 450°C","200°C","350°C","150°C"]', 'Plus de 450°C', 'Le tandoor en terre cuite peut atteindre 480°C — bien supérieur à tout four domestique.', 1),
  ('Le Tandoori Murgh', 'fill_in_blank', 'La version britannique du poulet tandoori avec sauce crémeuse s appelle ___', '[]', 'tikka masala', 'Le chicken tikka masala a été créé par des restaurants indo-pakistanais au Royaume-Uni.', 2),
  ('Les Idli Sambhar', 'multiple_choice', 'Qu est-ce qu un idli ?', '["Gâteau de riz cuit à la vapeur","Beignet de lentilles","Crêpe de riz fermentée","Riz soufflé"]', 'Gâteau de riz cuit à la vapeur', 'L idli est un gâteau de riz cuit à la vapeur — léger, moelleux et très digestible.', 1),
  ('Les Idli Sambhar', 'fill_in_blank', 'La pâte d idli doit fermenter ___ à 12 heures', '[]', '8', 'La fermentation développe l acidité et les bactéries lactiques qui rendent l idli léger et digeste.', 2),
  ('Le Fish Curry de Goa', 'multiple_choice', 'Quelle influence culinaire a le curry de Goa ?', '["Portugaise après 450 ans de domination","Britannique","Arabe","Française"]', 'Portugaise après 450 ans de domination', 'Goa a été une colonie portugaise de 1510 à 1961 — la cuisine en garde une empreinte forte.', 1),
  ('Le Fish Curry de Goa', 'fill_in_blank', 'L acide caractéristique du curry de Goa est le ___', '[]', 'tamarin', 'Le tamarin (ou kokum) est l acide de Goa — ne jamais le remplacer par du citron.', 2),
  ('Le Keema Matar', 'multiple_choice', 'Que signifie keema matar ?', '["Viande hachée aux petits pois","Poulet aux épices","Agneau au curry","Légumes sautés"]', 'Viande hachée aux petits pois', 'Keema = viande hachée, matar = petits pois — le plat en deux mots.', 1),
  ('Le Keema Matar', 'fill_in_blank', 'Keema signifie ___ en ourdou', '[]', 'viande hachée', 'Le mot keema vient du turc kıyma (viande hachée) — héritage de l empire moghol.', 2),
  ('Les Papdi Chaat', 'multiple_choice', 'Quand assemblent-on les papdi chaat ?', '["Au dernier moment — les galettes ramollissent vite","1h à l avance","La veille","30 min à l avance"]', 'Au dernier moment — les galettes ramollissent vite', 'Les papdi (galettes croustillantes) absorbent le yaourt rapidement — servez immédiatement.', 1),
  ('Les Papdi Chaat', 'fill_in_blank', 'Les galettes de blé frites et croustillantes s appellent ___', '[]', 'papdi', 'Le papdi est la base croustillante du chaat — fait de farine de blé frite en galettes.', 2),
  ('La Aloo Paratha', 'multiple_choice', 'Pourquoi la farce de pommes de terre du paratha doit-elle être sèche ?', '["Une farce humide troue la pâte","Pour le goût","Pour la cuisson","Par tradition"]', 'Une farce humide troue la pâte', 'L humidité dans la farce crée de la vapeur qui troue la pâte à l étalage — désastre culinaire.', 1),
  ('La Aloo Paratha', 'fill_in_blank', 'La plaque de cuisson en fonte pour les parathas s appelle un ___', '[]', 'tawa', 'Le tawa est la plaque plate en fonte — aussi utilisée pour les chapatis et les dosas.', 2),
  ('Le Pulao de Légumes', 'multiple_choice', 'Quelle est la différence entre pulao et biryani ?', '["Dans le pulao le riz cuit avec les épices — dans le biryani ils se cuisent séparément","Le pulao a moins d épices","Le biryani est végétarien","Pas de vraie différence"]', 'Dans le pulao le riz cuit avec les épices — dans le biryani ils se cuisent séparément', 'Dans le biryani, riz et viande sont cuits séparément puis superposés — dans le pulao, tout cuit ensemble.', 1),
  ('Le Pulao de Légumes', 'fill_in_blank', 'Le beurre clarifié indien essentiel à la cuisine indienne s appelle ___', '[]', 'ghee', 'Le ghee est du beurre fondu dont on a retiré l eau et les protéines — très haute température de fumée.', 2),
  ('Le Raita au Concombre', 'multiple_choice', 'Quelle est la fonction du raita dans un repas indien ?', '["Équilibrer la chaleur des currys","Remplacer la sauce","Être l entrée","Accompagner uniquement le biryani"]', 'Équilibrer la chaleur des currys', 'Le raita froid et acide apaise les papilles irritées par les épices des currys.', 1),
  ('Le Raita au Concombre', 'fill_in_blank', 'Les petites perles de pâte de pois chiches frites dans le raita s appellent ___', '[]', 'boondi', 'Le boondi raita utilise de petites perles frites de besan qui s imprègnent du yaourt.', 2),
  ('Le Malai Kofta', 'multiple_choice', 'Que signifie malai en hindi ?', '["Crème","Noix de cajou","Beurre","Lait"]', 'Crème', 'Malai est la crème en hindi — la sauce du malai kofta est une sauce crémeuse luxueuse.', 1),
  ('Le Malai Kofta', 'fill_in_blank', 'Kofta est un terme d origine ___ signifiant boulette de viande', '[]', 'persane', 'Le mot kofta vient du persan kōfta (viande pilée/hachée) — héritage de la cuisine moghole.', 2),
  ('Les Vada Pav de Mumbai', 'multiple_choice', 'Dans quelles années a été créé le vada pav ?', '["Années 1960","Années 1930","Années 1990","Années 1800"]', 'Années 1960', 'Le vada pav a été inventé en 1966 par Ashok Vaidya à Dadar, Mumbai — comme alternative bon marché.', 1),
  ('Les Vada Pav de Mumbai', 'fill_in_blank', 'Le pain mou de style portugais de Mumbai s appelle le ___', '[]', 'pav', 'Le pav (du portugais pão = pain) est un héritage des colons portugais à Goa et Mumbai.', 2),
  ('Le Mutton Rogan Josh Cachemiri', 'multiple_choice', 'Quelle cuisine a influencé la cuisine cachemirienne ?', '["La cuisine persane","La cuisine indienne du Sud","La cuisine chinoise","La cuisine tibétaine"]', 'La cuisine persane', 'Le Cachemire était une route commerciale entre l Inde et la Perse — cuisine de cour très raffinée.', 1),
  ('Le Mutton Rogan Josh Cachemiri', 'fill_in_blank', 'La couleur rouge du rogan josh vient du colorant naturel ___', '[]', 'ratan jot', 'Le ratan jot (Alkanna tinctoria) est une racine qui donne la couleur rouge sang authentique.', 2),
  ('Le Shahi Paneer', 'multiple_choice', 'Que signifie shahi en ourdou ?', '["Royal","Délicieux","Crémeux","Parfumé"]', 'Royal', 'Shahi (شاہی) signifie royal en ourdou/persan — le shahi paneer était servi à la cour moghole.', 1),
  ('Le Shahi Paneer', 'fill_in_blank', 'La sauce du shahi paneer est mixée et ___ pour une texture royalement lisse', '[]', 'tamisée', 'Le tamisage élimine les fibres et graines pour une sauce d une finesse incomparable.', 2),
  ('Le Chole Bhature', 'multiple_choice', 'Quand est célébré ce plat ?', '["Le dimanche matin à Delhi","Les jours de fête uniquement","Pour le dîner","Après l université"]', 'Le dimanche matin à Delhi', 'Le chole bhature est le rituel du dimanche matin pour les familles de Delhi.', 1),
  ('Le Chole Bhature', 'fill_in_blank', 'Bhature signifie pain ___ en hindi', '[]', 'frit gonflé', 'Le bhature est un pain frit à la farine de blé et yogourt qui gonfle comme un ballon à la friture.', 2)
) AS v(lesson_title, type, question, options, correct_answer, explanation, order_index)
JOIN public.lessons l ON l.title = v.lesson_title;

-- ============================================================
-- EXERCISES FOR THAI LESSONS 36-50
-- ============================================================
INSERT INTO public.exercises (id, lesson_id, type, question, options, correct_answer, explanation, order_index)
SELECT gen_random_uuid(), l.id, v.type, v.question, v.options::jsonb, v.correct_answer, v.explanation, v.order_index
FROM (VALUES
  ('Le Pad Krapow Moo', 'multiple_choice', 'Quel basilic est utilisé dans le pad krapow ?', '["Basilic sacré (krapow) — Holy basil","Basilic thaï","Basilic commun","Basilic violet"]', 'Basilic sacré (krapow) — Holy basil', 'Le basilic sacré (Ocimum tenuiflorum) est plus poivré et épicé que les autres basilics.', 1),
  ('Le Pad Krapow Moo', 'fill_in_blank', 'La sauce poisson thaïe de base s appelle ___', '[]', 'nam pla', 'Le nam pla (น้ำปลา) est le condiment de base de toute la cuisine thaïlandaise.', 2),
  ('Le Som Tum (Papaya Verte)', 'multiple_choice', 'De quelle région thaïlandaise vient le som tum ?', '["L Isan (nord-est)","Bangkok","Le Sud","Le Nord (Chiang Mai)"]', 'L Isan (nord-est)', 'Le som tum est d origine lao-thaïe de l Isan — la région nord-est à influence laotienne.', 1),
  ('Le Som Tum (Papaya Verte)', 'fill_in_blank', 'Som signifie ___ et tum signifie pilé en thaï', '[]', 'acide', 'Le nom décrit parfaitement le plat : la papaye acide (som) pilée au mortier (tum).', 2),
  ('Le Khao Man Gai', 'multiple_choice', 'D où vient l influence du khao man gai ?', '["De Hainan (île du sud de la Chine)","De Hong Kong","De Taiwan","Du Yunnan"]', 'De Hainan (île du sud de la Chine)', 'Les immigrants hainais ont apporté leur poulet au riz (Hainanese chicken rice) en Thaïlande.', 1),
  ('Le Khao Man Gai', 'fill_in_blank', 'Le riz du khao man gai doit cuire dans le ___ de poulet', '[]', 'bouillon', 'Le riz absorbe les arômes du bouillon de poulet — c est ce qui donne le khao man (riz gras) son goût.', 2),
  ('La Tom Kha Gai', 'multiple_choice', 'Comment la tom kha diffère-t-elle de la tom yum ?', '["La tom kha a du lait de coco qui adoucit les épices","La tom kha est plus piquante","La tom kha n a pas de citron vert","Ce sont les mêmes"]', 'La tom kha a du lait de coco qui adoucit les épices', 'La noix de coco de la tom kha la rend plus douce et crémeuse que la tom yum qui est bouillonnante.', 1),
  ('La Tom Kha Gai', 'fill_in_blank', 'L arôme central de la tom kha vient du ___', '[]', 'galangal', 'Le galangal (kha) donne le nom à la soupe et son arôme poivré et camphré distinctif.', 2),
  ('Le Som Tum (Papaya Verte)', 'multiple_choice', 'Comment prépare-t-on le som tum dans le mortier ?', '["On meurtrit sans réduire en purée","On pilonne jusqu à purée lisse","On mélange sans piler","On hache au couteau d abord"]', 'On meurtrit sans réduire en purée', 'La technique du som tum consiste à meurtrir pour libérer les jus sans écraser totalement.', 1),
  ('Le Miang Kham', 'multiple_choice', 'Comment appelle-t-on les feuilles dans lesquelles on enveloppe le miang kham ?', '["Bai cha plu (bétel sauvage)","Feuilles de bananier","Feuilles de coriandre","Feuilles de pandan"]', 'Bai cha plu (bétel sauvage)', 'Le bai cha plu (bétel sauvage, piper sarmentosum) a un goût légèrement poivré et légèrement amer.', 1),
  ('Le Miang Kham', 'fill_in_blank', 'Le miang kham est une collation ___ thaïlandaise servie aux visiteurs importants', '[]', 'royale', 'Le miang kham est d origine royale — il faisait partie de la cuisine de palais siamoise.', 2),
  ('Le Kao Kha Moo', 'multiple_choice', 'Quelle est la texture caractéristique du kao kha moo bien cuit ?', '["Gélatineuse — le collagène fondu","Ferme et caoutchouteuse","Tendre mais sèche","Croustillante"]', 'Gélatineuse — le collagène fondu', 'Le pied de porc est riche en collagène qui fond en gelée après longue cuisson — texture fondante.', 1),
  ('Le Kao Kha Moo', 'fill_in_blank', 'Le mélange étoile anis, cannelle, clou, fenouil et poivre de Sichuan s appelle les ___', '[]', 'cinq épices', 'Les cinq épices (cinq saveurs chinoises) parfument le kao kha moo sino-thaï.', 2),
  ('Le Pla Pao', 'multiple_choice', 'Quel effet a le sel sur le poisson dans le pla pao ?', '["Il forme une croûte protectrice — le poisson cuit dans sa vapeur","Il assaisonne profondément","Il accélère la cuisson","Il fait dorer la peau"]', 'Il forme une croûte protectrice — le poisson cuit dans sa vapeur', 'La croûte de sel crée un four hermétique — le poisson cuit à l étouffée dans sa propre humidité.', 1),
  ('Le Pla Pao', 'fill_in_blank', 'La citronnelle insérée dans le ventre du poisson s appelle en thaï ___', '[]', 'ta krai', 'Le ta krai (citronnelle) parfume le poisson de l intérieur pendant la cuisson.', 2),
  ('Le Yam Nuea Yang', 'multiple_choice', 'Comment doit être le bœuf dans le yam nuea yang ?', '["Saignant — il continue de cuire dans la sauce acide","Bien cuit","À point","Poché"]', 'Saignant — il continue de cuire dans la sauce acide', 'L acide du citron vert continue de cuire légèrement le bœuf — sortez-le saignant du grill.', 1),
  ('Le Yam Nuea Yang', 'fill_in_blank', 'Les salades yam sont toujours servies à ___ ambiante en Thaïlande', '[]', 'température', 'Les arômes des herbes et épices du yam s expriment mieux à température ambiante.', 2),
  ('Le Pad Char Talay', 'multiple_choice', 'Combien de temps cuisent les fruits de mer dans le pad char ?', '["2-3 minutes maximum","10 minutes","5 minutes","Jusqu à bien cuits"]', '2-3 minutes maximum', 'Les fruits de mer durcissent s ils cuisent trop — 2-3 min à feu très vif est suffisant.', 1),
  ('Le Pad Char Talay', 'fill_in_blank', 'Le petit gingembre sauvage essentiel au pad char s appelle ___', '[]', 'grachai', 'Le grachai (Kaempferia parviflora) a un arôme distinctif — il n est pas substituable.', 2),
  ('Les Desserts de Rue Thaïs', 'multiple_choice', 'Les look choup sont des miniatures de quoi ?', '["Fruits en pâte de haricots adzuki","Légumes en marzipan","Fleurs en sucre","Animaux en chocolat"]', 'Fruits en pâte de haricots adzuki', 'Les look choup sont des fruits miniatures en pâte de haricots colorée — chefs d œuvre d artisanat.', 1),
  ('Les Desserts de Rue Thaïs', 'fill_in_blank', 'Les boulettes de riz dans le lait de coco s appellent ___', '[]', 'bua loy', 'Le bua loy (fleur de lotus qui flotte) est un dessert doux et poétique de la cuisine thaïe.', 2),
  ('Le Khao Niao Dam', 'multiple_choice', 'Pourquoi le riz gluant noir est-il bon pour la santé ?', '["Riche en anthocyanines — antioxydants naturels","Sans calories","Plus digeste que le blanc","Riche en protéines"]', 'Riche en anthocyanines — antioxydants naturels', 'La couleur noire du riz vient des anthocyanines — les mêmes antioxydants que les myrtilles.', 1),
  ('Le Khao Niao Dam', 'fill_in_blank', 'Dam signifie ___ en thaï', '[]', 'noir', 'Khao niao dam = riz gluant noir — la couleur est naturelle, sans colorant.', 2),
  ('Le Gaeng Liang', 'multiple_choice', 'Quelle est la particularité du gaeng liang par rapport aux autres currys thaïs ?', '["Il n a pas de lait de coco — c est un curry léger","Il est plus piquant","Il vient du Nord","Il est uniquement végétarien"]', 'Il n a pas de lait de coco — c est un curry léger', 'Le gaeng liang est un curry bouillonné sans lait de coco — le plus léger de la cuisine thaïe.', 1),
  ('Le Gaeng Liang', 'fill_in_blank', 'Le petit gingembre sauvage caractéristique du gaeng liang s appelle ___', '[]', 'krachai', 'Le krachai (Boesenbergia rotunda) est un rhizome avec un arôme camphrée distinctif.', 2),
  ('Le Kaeng Tai Pla', 'multiple_choice', 'Qu est-ce que le tai pla ?', '["Entrailles de poisson fermentées — ingrédient unique du sud thaï","Sauce de poisson très forte","Poisson séché","Pâte de crevettes"]', 'Entrailles de poisson fermentées — ingrédient unique du sud thaï', 'Le tai pla est une pâte fermentée d intestins de poisson — très odorant mais d une profondeur unique.', 1),
  ('Le Kaeng Tai Pla', 'fill_in_blank', 'Le kaeng tai pla est une spécialité du ___ de la Thaïlande', '[]', 'Sud', 'Les currys du sud de la Thaïlande sont les plus piquants et les plus complexes du pays.', 2),
  ('Le Khao Pad Naem', 'multiple_choice', 'Qu est-ce que le naem thaïlandais ?', '["Saucisse de porc fermentée du nord thaï","Sauce pimentée","Porc séché","Condiment fermenté de soja"]', 'Saucisse de porc fermentée du nord thaï', 'Le naem est une saucisse fermentée aigre et piquante — spécialité du nord de la Thaïlande.', 1),
  ('Le Khao Pad Naem', 'fill_in_blank', 'Kai dao signifie ___ en thaï', '[]', 'œuf au plat', 'Kai (œuf) + dao (étoile) = œuf au plat en thaï — le yolk jaune comme une étoile.', 2)
) AS v(lesson_title, type, question, options, correct_answer, explanation, order_index)
JOIN public.lessons l ON l.title = v.lesson_title;

-- ============================================================
-- EXERCISES FOR GREEK LESSONS 36-50
-- ============================================================
INSERT INTO public.exercises (id, lesson_id, type, question, options, correct_answer, explanation, order_index)
SELECT gen_random_uuid(), l.id, v.type, v.question, v.options::jsonb, v.correct_answer, v.explanation, v.order_index
FROM (VALUES
  ('La Saganaki', 'multiple_choice', 'Quel cri accompagne le saganaki dans les tavernes grecques ?', '["Opa !","Yamas !","Kalimera !","Efharisto !"]', 'Opa !', 'Le Opa ! est le cri d enthousiasme grec — il accompagne le flambage du saganaki.', 1),
  ('La Saganaki', 'fill_in_blank', 'Le fromage dur et salé grec idéal pour le saganaki s appelle ___', '[]', 'kefalotyri', 'Le kefalotyri (tête du fromage) est un fromage dur qui résiste à la friture sans fondre complètement.', 2),
  ('La Psarosoupa Avgolemono', 'multiple_choice', 'Pourquoi ajouter l avgolemono hors feu dans la soupe ?', '["Pour éviter la coagulation des œufs","Pour la couleur","Pour le refroidir","Par tradition uniquement"]', 'Pour éviter la coagulation des œufs', 'Si la soupe bout avec les œufs de l avgolemono, ils coagulent et la sauce griaille.', 1),
  ('La Psarosoupa Avgolemono', 'fill_in_blank', 'Avgolemono signifie ___ et citron en grec', '[]', 'œufs', 'Avgo (oeuf) + lemono (citron) = la sauce de base de nombreux plats grecs.', 2),
  ('Les Dolmades Feuilles de Vigne', 'multiple_choice', 'Pourquoi ne remplir les dolmades qu à moitié ?', '["Le riz gonfle à la cuisson","La feuille de vigne cuit mal","Pour qu ils soient légers","Par tradition"]', 'Le riz gonfle à la cuisson', 'Un dolma trop plein éclatera à la cuisson quand le riz absorbe le bouillon.', 1),
  ('Les Dolmades Feuilles de Vigne', 'fill_in_blank', 'La feuille de vigne en grec s appelle ___', '[]', 'ampelofyllo', 'Ampelo (vigne) + fyllo (feuille) = feuille de vigne.', 2),
  ('Le Kokoretsi', 'multiple_choice', 'Lors de quelle fête mange-t-on le kokoretsi ?', '["La nuit de Pâques orthodoxes","Noël","Le Carnaval","La fête nationale"]', 'La nuit de Pâques orthodoxes', 'Le kokoretsi est grillé la nuit du samedi de Pâques — après la messe de résurrection.', 1),
  ('Le Kokoretsi', 'fill_in_blank', 'Le kokoretsi doit griller ___ sur braise en tournant', '[]', '2 heures', 'La cuisson lente de 2h sur braise garantit que les abats cuisent à cœur.', 2),
  ('Le Stifado de Poulpe', 'multiple_choice', 'Pourquoi congeler le poulpe avant cuisson ?', '["Le froid brise les fibres — il devient plus tendre","Pour l hygiène","Pour le conserver plus longtemps","Pour faciliter le nettoyage"]', 'Le froid brise les fibres — il devient plus tendre', 'La congélation rompt les fibres musculaires du poulpe — il devient beaucoup plus tendre à la cuisson.', 1),
  ('Le Stifado de Poulpe', 'fill_in_blank', 'Le poulpe en grec s appelle ___', '[]', 'chtapodi', 'Le chtapodi (χταπόδι) est un incontournable des tavernes des îles grecques.', 2),
  ('Les Spanakopita', 'multiple_choice', 'Pourquoi égoutter absolument les épinards ?', '["L excès d eau ramollit le phyllo","Pour le goût","Pour réduire le volume","Pour l hygiène"]', 'L excès d eau ramollit le phyllo', 'Le phyllo mouillé devient mou et ne croustille plus — les épinards doivent être bien pressés.', 1),
  ('Les Spanakopita', 'fill_in_blank', 'Spanaki signifie ___ en grec', '[]', 'épinards', 'Spanakopita = épinards (spanaki) + pita (tourte) = tourte aux épinards.', 2),
  ('Le Bakaliaros Skordalia', 'multiple_choice', 'Lors de quelle fête mange-t-on le bakaliaros skordalia ?', '["Vendredi Saint grec orthodoxe","Pâques","Noël","Jour de l Indépendance"]', 'Vendredi Saint grec orthodoxe', 'La morue frite est le plat traditionnel du Vendredi Saint — jour de jeûne de la viande.', 1),
  ('Le Bakaliaros Skordalia', 'fill_in_blank', 'La skordalia est une sauce crémeuse à l ___', '[]', 'ail', 'Skordalia vient de skordo (ail) — une sauce à l ail avec pommes de terre ou pain rassis.', 2),
  ('La Manestra', 'multiple_choice', 'Qu est-ce que l orzo ?', '["Petites pâtes en forme de grain de riz","Riz à grain court","Semoule","Farro"]', 'Petites pâtes en forme de grain de riz', 'L orzo (grge en italien) est une pâte qui ressemble à du riz — utilisée comme le riz dans la manestra.', 1),
  ('La Manestra', 'fill_in_blank', 'L orzo absorbe beaucoup de liquide — ajoutez le ___ graduellement', '[]', 'bouillon', 'Comme un risotto, la manestra demande un ajout graduel de bouillon pour que l orzo l absorbe sans coller.', 2),
  ('Les Thrapsalo (Calamars Farcis)', 'multiple_choice', 'Jusqu où remplit-on les calamars pour qu ils ne débordent pas ?', '["Aux 2/3","À moitié","Complètement","Au 3/4"]', 'Aux 2/3', 'Le riz dans la farce double de volume — si le calamar est trop plein, il éclate.', 1),
  ('Les Thrapsalo (Calamars Farcis)', 'fill_in_blank', 'Le calamar en grec standard s appelle ___', '[]', 'kalamari', 'Kalamari (καλαμάρι) vient du grec kalamari (plume de calmar) — c est le mot moderne utilisé.', 2),
  ('Les Melitzanosalata', 'multiple_choice', 'Comment obtient-on le goût fumé de la melitzanosalata ?', '["En brûlant les aubergines directement sur la flamme","En ajoutant du paprika fumé","En les faisant fumer à froid","Au four avec fumée de bois"]', 'En brûlant les aubergines directement sur la flamme', 'Le contact direct avec la flamme carbonise la peau et donne une saveur fumée impossible autrement.', 1),
  ('Les Melitzanosalata', 'fill_in_blank', 'Melitzana signifie ___ en grec', '[]', 'aubergine', 'Melitzana (μελιτζάνα) est le mot grec pour aubergine — melitzanosalata est littéralement salade d aubergines.', 2),
  ('La Galaktoboureko', 'multiple_choice', 'Comment verse-t-on le sirop sur la galaktoboureko ?', '["Sirop froid sur pâtisserie chaude","Sirop chaud sur pâtisserie froide","Les deux chauds","Les deux froids"]', 'Sirop froid sur pâtisserie chaude', 'Le choc thermique chaud-froid permet au sirop de pénétrer uniformément dans la pâtisserie.', 1),
  ('La Galaktoboureko', 'fill_in_blank', 'Galakto signifie ___ en grec', '[]', 'lait', 'Galakto (γαλακτο) = lait, boureko = gâteau — la galaktoboureko est littéralement un gâteau au lait.', 2),
  ('Le Tsoureki', 'multiple_choice', 'Quel est l arôme central du tsoureki ?', '["La mahlab (noyau de cerise de Sainte-Lucie)","La cannelle","La vanille","L anis"]', 'La mahlab (noyau de cerise de Sainte-Lucie)', 'La mahlab est une épice de noyau de cerise sauvage — florale et légèrement amère.', 1),
  ('Le Tsoureki', 'fill_in_blank', 'Le tsoureki est une ___ tressée parfumée des fêtes orthodoxes', '[]', 'brioche', 'Le tsoureki est la brioche des Pâques orthodoxes et de Noël — souvent ornée d un œuf rouge.', 2),
  ('Les Vradia Sarakosti', 'multiple_choice', 'Combien de jours par an les orthodoxes grecs jeûnent-ils ?', '["Jusqu à 180 jours","40 jours","7 jours","365 jours"]', 'Jusqu à 180 jours', 'La tradition orthodoxe inclut de nombreuses périodes de jeûne — Carême, Apôtres, Dormition...', 1),
  ('Les Vradia Sarakosti', 'fill_in_blank', 'Le jeûne orthodoxe (s abstenir des produits animaux) s appelle la ___', '[]', 'nisteia', 'La nisteia (νηστεία) est le jeûne alimentaire — sans viande, lait, œufs selon les jours.', 2),
  ('Le Mousakas Végétarien', 'multiple_choice', 'Pourquoi griller les aubergines avant le montage ?', '["Pour éliminer l excès d eau","Pour le goût uniquement","Pour les attendrir","Par tradition"]', 'Pour éliminer l excès d eau', 'Les aubergines contiennent beaucoup d eau — si elles ne sont pas grillées, elles rendent et détremp le mousakas.', 1),
  ('Le Mousakas Végétarien', 'fill_in_blank', 'Le mousakas est un ___ d aubergines à la béchamel', '[]', 'gratin', 'Le mousakas est un gratin en couches — aubergines, farce (viande ou légumes) et béchamel.', 2),
  ('Le Mezes Complet', 'multiple_choice', 'D où vient le mot mezze ?', '["De l arabe maza (goûter)","Du grec meso (milieu)","Du turc mezes","Du persan maza"]', 'De l arabe maza (goûter)', 'Le mot mezze est partagé entre les cuisines grecque, turque, libanaise et iranienne.', 1),
  ('Le Mezes Complet', 'fill_in_blank', 'Le bar à ouzo servant des mezze s appelle une ___', '[]', 'ouzeri', 'L ouzeri est une institution grecque — on y boit de l ouzo et on grignote des mezze entre amis.', 2)
) AS v(lesson_title, type, question, options, correct_answer, explanation, order_index)
JOIN public.lessons l ON l.title = v.lesson_title;
